### ISSUE TITLE
Seemingly inconsistent behaviour for newlines before comments

### ISSUE THREAD

**Issue by nrinaudo** [scalameta/scalafmt#1001]
- **Version**: 1.1.0
- **Integration**: command line (coursier wrapper)
- **Configuration**:
```
style                           = defaultWithAlign
maxColumn                       = 120
includeCurlyBraceInSelectChains = false

project {
  git = true
}

binPack {
  parentConstructors = true
}

rewrite {
  rules = [RedundantBraces, RedundantParens, SortImports, PreferCurlyFors]
}

rewriteTokens {
  "->": "→"
  "=>": "⇒"
  "<-": "←"
}

align {
  arrowEnumeratorGenerator = true
  tokens.add               = [":="]
}
```

## Steps

Apply the above conf to the following code:

```scala
object Test {
  /* some doc */
  def i: Int = 1
}

object Test2 {
  /** some doc */
  def i: Int = 1
}
```

## Problem

Scalafmt formats code like this:
```scala
object Test {
  /* some doc */
  def i: Int = 1
}

object Test2 {

  /** some doc */
  def i: Int = 1
}
```

Note the fact that a newline was inserted before the scaladoc, but not the plain comment.

## Expectation

I expected both comments to be treated the same way - either a new line both cases, or never.

I'm not sure whether this behaviour is intended, and it might very well be - maybe scaladoc is being given a different behaviour because it makes the corresponding member more "official"?

I personally like the behaviour for plain comments better, _when talking about the first element of a new scope_.

That is, the following is what my preference would be, after formatting:

```scala
object Test {
  /** some doc */
  def i: Int = 1

  /** some doc */
  def j: Int = 2
}
```

**Comment by pjrt** [comment]
Interesting, I didn't know that was happening. Personally I like having an extra space after all block starters (object, def with curly, etc). 

I would say that we should add the space in both cases. @olafurpg ?

**Comment by olafurpg** [comment]
Scalafmt forces a blank line before scaladoc comments but they're optional for regular comments. Scalafmt will preserve a blank line before a regular comment. This is working as intended from my point of view, but I'm open to be convinced otherwise.

**Comment by olafurpg** [comment]
Does the current special handling of scaladoc comments make sense?

**Comment by nrinaudo** [comment]
My personal opinion is that it's a bit weird that both are treated differently. I don't have a strong opinion either way though, whatever works best for you is fine for me.

**Comment by olafurpg** [comment]
The PR https://github.com/scalameta/scalafmt/pull/1101 added `optIn.blankLineBeforeDocstring=true` which exposes full  control over whether to insert blank lines before docstrings or not.
