### ISSUE TITLE
Want class args to be on multiple lines

### ISSUE THREAD

**Issue by firerml** [scalameta/scalafmt#1004]
- **Version**: 1.1.0
- **Integration**: IntelliJ
- **Configuration**:
```
style = IntelliJ
maxColumn = 120
optIn.configStyleArguments = true
```

## Problem

The problem is that if scalafmt can fit all the args in one line in under maxColumn characters, it does, but I don't want it to. I want it to have no preference. I like to make my case class args very visible, for example.
```scala
case class Thing(hey: Option[Int], blah: Option[String])
```

## Expectation

I would like the formatted output to look like this:
```scala
case class Thing(hey: Option[Int],
                 blah: Option[String])
```

**Comment by pjrt** [comment]
Scalafmt is based around the maxColumn setting (almost all the settings do nothing unless the maxColumn is surpassed). Supporting this style would go against that philosophy so I'm against this.

**Comment by olafurpg** [comment]
It's possible to use "config style" to break lines that fit within maxColumn http://scalameta.org/scalafmt/#Configstyle
```scala
case class Thing(
  hey: Option[Int],
  blah: Option[String]
)
```
scalafmt will otherwise not line break if the code already fits within maxColumn, this is working as intended.

**Comment by vsapronov** [comment]
Hi @olafurpg,
You mentioned "config style", I also saw it mentioned in documentation few times. Though how exactly to use it?

I want this (formatted by `ScalafmtConfig.default`):
```
case class User(email: Option[String],
                username: Option[String],
                lastName: Option[String],
                firstName: Option[String],
                password: Option[String])
```
to become this:
```
case class User(
    email: Option[String],
    username: Option[String],
    lastName: Option[String],
    firstName: Option[String],
    password: Option[String]
)
```
I'm using scalafmt as a library in my codegen tool.
Please, help.

**Comment by olafurpg** [comment]
@vsapronov have you tried `align=none` and `danglingParentheses=true`?

**Comment by vsapronov** [comment]
@olafurpg Thank you! This is exactly what I was looking for!
