### ISSUE TITLE
New files not found when running `scalafmt` with `git = true`

### ISSUE THREAD

**Issue by pjrt** [scalameta/scalafmt#1010]
This template is a guideline, not a strict requirement.
- **Version**: 1.1.0
- **Integration**: CLI
- **Configuration**:
```
project.git = true
```

## Steps

```bash
# inside a git repo
cat > Test.scala
  class Test { def     f =    1 }
git add Test.scala
scalafmt
```

## Problem

Test.scala was not picked up (it stayed unformatted)

## Expectation

It should be formatted

## Workaround

If you run `scalafmt --diff-branch HEAD` it will pick it up (because that command uses a different file lookup strategy).

## Notes

More than likely this is related to https://github.com/scalameta/scalafmt/issues/1000, and both are probably caused by my changes to the file lookup strategies on v1.0.

**Comment by pjrt** [comment]
Fixed with afc446

**Comment by ctoomey** [comment]
Thanks for fixing this, I just ran into it for a renamed file.
