### ISSUE TITLE
neo-sbt-scalafmt is nice

### ISSUE THREAD

**Issue by eed3si9n** [scalameta/scalafmt#1020]
http://scalameta.org/scalafmt says:

> Please report back if you find neo-sbt-scalafmt useful. We might want to promote it to become the official sbt plugin for scalafmt.

I like neo-sbt-scalafmt. If a project adopts Scalafmt, `scalafmtOnCompile in ThisBuild := true` is a must have for me. Once set up, I don't have to worry about it any more. 

/cc @pauldraper

**Comment by olafurpg** [comment]
Glad to hear! I hope we can improve the bincompat situation so neo-scalafmt can support a wider range of scalafmt versions https://github.com/lucidsoftware/neo-sbt-scalafmt/pull/36

**Comment by olafurpg** [comment]
Following feedback from @dwijnand, what do y'all think about removing com.geirsson:sbt-scalafmt to make it clearer that neo-scalafmt is the recommended integration for sbt?

**Comment by kflorence** [comment]
@olafurpg the neo-sbt-scalafmt plugin is great, I would support it becoming the officially supported plugin.

**Comment by dwijnand** [comment]
This can be closed probably.

**Comment by olafurpg** [comment]
The neo-sbt-scalafmt plugin has problems keeping up to date with recent releases and developers have been slow to respond to feedback on how to address binary compatibility https://github.com/lucidsoftware/neo-sbt-scalafmt/issues/69

In the meantime, we have an sbt-scalafmt plugin in this repo that was contributed by the ENSIME fund and supports reformat on compile. I think going forward it is best to endorse the plugin in this repo as the officially recommended sbt installation, although note that I will likely assign reported tickets to sbt-scalafmt contributors.
