### ISSUE TITLE
coursier bootstrap Cannot find default main class

### ISSUE THREAD

**Issue by stephennancekivell** [scalameta/scalafmt#1021]
- **Version**: 1.2.0
- **Integration**: coursier

## Steps

I tried to install scalafmt like this:

```bash
$ coursier bootstrap com.geirsson:scalafmt-cli_2.12:1.2.0 \
  -o scalafmt
Cannot find default main class. Specify one with -M or --main.

```

## Problem

coursier errors
```scala
Cannot find default main class. Specify one with -M or --main.
```

## Expectation

I would expect install to work and have a file which I could run.
```scala
./scalafmt --version # should be 1.2.0
```

##

Perhaps we just need to update the documentation. http://scalameta.org/scalafmt/#Coursier

**Comment by olafurpg** [comment]
Thank you for reporting! `--main org.scalafmt.cli.Cli` was missing. It got removed in https://github.com/scalameta/scalafmt/pull/1011#discussion_r132041045 under the assumption that it would be automatically inferred but it seems that is still not the case. I've updated the docs to add --main back again, the CI will update the website in the next half hour.

**Comment by olafurpg** [comment]
cc/ @dwijnand

**Comment by stephennancekivell** [comment]
Legend, Thanks mate!

**Comment by dwijnand** [comment]
Perhaps detecting the main class is feature of a recent version of Coursier that I was using compared to Stephen?

**Comment by stephennancekivell** [comment]
oh wow, my coursier is old! I was on `1.0.0-M15` If I upgrade to `1.0.0-RC-10` It install fine without the `--main`.

Sorry about that.

Im a bit surprised I have it installed via homebrew, which I have auto updating. I dont know why that didnt work for the coursier package.

**Comment by dwijnand** [comment]
If you installed it from https://github.com/coursier/homebrew-formulas, that formula's not maintained sadly.
