### ISSUE TITLE
Re-enable Appveyor

### ISSUE THREAD

**Issue by olafurpg** [scalameta/scalafmt#1023]
We can use the workaround from https://github.com/scalameta/scalameta/pull/1069#pullrequestreview-56579144 to fix the problems that started in https://github.com/scalameta/scalafmt/pull/1014

**Comment by tgodzik** [comment]
Shouldn't we close this one since we are now using github actions? @kitbellew

**Comment by kitbellew** [comment]
> Shouldn't we close this one since we are now using github actions? @kitbellew

@olafurpg ^^^
