### ISSUE TITLE
Cross Build for SBT 1.0.0

### ISSUE THREAD

**Issue by swachter** [scalameta/scalafmt#1026]

**Comment by olafurpg** [comment]
The plugin or the scalafmt build itself?

**Comment by olafurpg** [comment]
sbt-scalafmt is already published for 1.0 https://repo1.maven.org/maven2/com/geirsson/sbt-scalafmt_2.12_1.0/1.2.0/

**Comment by swachter** [comment]
Ok. I need the plugin. Thanks!

**Comment by olafurpg** [comment]
Note that you can use neo-scalafmt for sbt 1.0 as well ;)
