### ISSUE TITLE
Different styles for single- and multi-lines literal functions

### ISSUE THREAD

**Issue by nrinaudo** [scalameta/scalafmt#1027]
A coding style I've sometimes seen (and personally use) has:
- `(` for single-line literal functions
- `{` for multi-line literal functions

For example:

```scala
// Single line
xs.map(i => i + 1)

// Multi line
xs.map { i =>
  println(i)
  i + 1
}
```

This was discussed in [gitter](https://gitter.im/scalameta/scalafmt?at=59955261578b44a046ba7629) and seemed to generate some enthusiasm.

**Comment by sjrd** [comment]
That's also what's prescribed by the Scala.js coding style, FWIW.

**Comment by pjrt** [comment]
Just to be clear, this wants to re-write a function that has a single statement like:

```scala
xs.map { x =>
  x + 1
}
```
to a single-line one:

```scala
xs.map(x => x + 1)
```

Correct?

**Comment by sjrd** [comment]
The way I see it, both your snippets would stay untransformed, because each is valid. However
```scala
xs.map { x => x + 1 }
```
would be rewritten as
```scala
xs.map(x => x + 1)
```
and
```scala
xs.map(x =>
  x + 1)
```
or things like that would be rewritten as
```scala
xs.map { x =>
  x + 1
}
```

**Comment by pjrt** [comment]
Not sure what you mean by valid, every snippet is valid (mine, yours and OP). 

Not sure I follow what rule you are using @sjrd . The `\n` determines whether we use paren or curly? I understood @nrinaudo 's post as "make single-statement use paren and multi-statements stay curly" (hence why I asked for clarification).

**Comment by sjrd** [comment]
I meant *valid* according to the coding style rules exposed in the original issue description, i.e.,

> * `(` for single-line literal functions
> * `{` for multi-line literal functions

**Comment by sjrd** [comment]
> The \n determines whether we use paren or curly?

Yes, basically. Any `\n` between the first parameter of the lambda and the closing `)`/`}` would force going to `{}`, and there isn't such `\n` would force going to `()`.

Note that, it's not completely clear from the issue description, but in my book (and I guess other people would disagree) the following style is also acceptable:
```scala
foobar(
    x => x + 1)
```
(the lambda itself contains no `\n`, although there is one just before it). It becomes "important" to allow this when the lambda is not the only parameter to the function, and the parameters together don't fit on one line anymore. If you don't allow this, you might be forced to introduce `{}` where *neither* `{}` nor `()` were necessary.

**Comment by pjrt** [comment]
```scala
foobar(
    x => x + 1)
```
the way I see it, that style only acceptable if having it in one line would break the maxColumn limit. If it doesn't, I would just force it into one line with parens (since it looks better that way).

**Comment by sjrd** [comment]
Sure, you are absolutely right. ;) I should have used a longer identifier instead of `foobar` for my example.

**Comment by nrinaudo** [comment]
My initial intention was as @sjrd understood it: if there's a line break, turn `(` to `{`. If there's no line break, turn `{` to `(`.

But of course, it seems even better to go one step further - if no line break is necessary, turn `{` to `(`. If a line break is necessary, turn `(` to `{`.

**Comment by kitbellew** [comment]
@nrinaudo @sjrd #1660 and #1663 cover the first part of your request (using parens for single-line calls with a single argument).

#1663 also presents an argument why the opposite rewrite will not work in some cases (and whether the check for trailing infix operator will suffice is unclear). for now, i have no plans to tackle that second part.

feel free to close this issue if the solution presented is enough.

**Comment by nrinaudo** [comment]
I certainly would be enough for me, and I've no issue with this ticket being closed. I'll let @sjrd be the final judge on that.

**Comment by sjrd** [comment]
Given the difficulty explained in #1663, I also think we can close this ticket.
