### ISSUE TITLE
RedundantBraces does not seem to catch all redundant braces

### ISSUE THREAD

**Issue by nrinaudo** [scalameta/scalafmt#1032]
```scala
def j: Int ⇒ Int = i ⇒ { i }
```

When `RedundantBraces` is enabled, I would expect the formatted code to look like:

```scala
def j: Int ⇒ Int = i ⇒ i
```

The braces are, however left alone. See [this gitter conversation](https://gitter.im/scalameta/scalafmt?at=59a01b5e210ac26920be3181) for @olafurpg's explanation of why this is expected but maybe not desirable.

**Comment by olafurpg** [comment]
Thanks for reporting! v1.5 added `RedundantBraces.generalExpressions = true` that allows removing redunant braces for all expressions. It's currently a bit over-agressive for my personal taste, but you may like it 😉 Please refer to the docs for more information.
