### ISSUE TITLE
Feature: would like the opposite of binPack.parentConstructors=true

### ISSUE THREAD

**Issue by kitbellew** [scalameta/scalafmt#1039]
This template is a guideline, not a strict requirement.
- **Version**: 1.2.0
- **Integration**: CLI
- **Configuration**:
```
style = default
maxColumn = 100
danglingParentheses = true

align = none
align.tokens = []
align.openParenCallSite = false

newlines.alwaysBeforeTopLevelStatements = true
newlines.sometimesBeforeColonInMethodReturnType = false
newlines.alwaysBeforeCurlyBraceLambdaParams = true
newlines.afterImplicitKWInVerticalMultiline = true
newlines.beforeImplicitKWInVerticalMultiline = true

runner.fatalWarnings = true
runner.optimizer.forceConfigStyleOnOffset = 50
runner.optimizer.forceConfigStyleMinArgCount = 5

rewrite.rules = [ExpandImportSelectors, PreferCurlyFors]
```

## Steps

I ran scalafmt like this:

```bash
scalafmt
```

## Problem

Scalafmt formats code like this:
```scala
object A extends B with C {
```

## Expectation

I would like the formatted output to look like this:
```scala
object A
    extends B
    with C
{
```

**Comment by olafurpg** [comment]
This should be possible to accommodate, scalafmt tries to fit the template parent constructors in a single line if it fits and falls back to one line per `extends/with`. The relevant piece of code is here https://github.com/scalameta/scalafmt/blob/509bad695ef6c4643554c72aef8d6975a18b92ce/scalafmt-core/shared/src/main/scala/org/scalafmt/internal/FormatOps.scala#L654
and your expected output can probably be obtained by ignoring the `Split(Space, 0)` case under a configuration option like `newlines.alwaysInParentConstructors=true` (false by default)

```scala
      Split(Space, 0, ignoreIf = newlines.alwaysInParentConstructors)
```

**Comment by olafurpg** [comment]
This is an interesting idea. I am open to merge a PR adding this functionality. I've added the revisit label, please reopen if you would like to take a stab at this ticket.
