### ISSUE TITLE
Bug: includeCurlyBraceInSelectChains=true doesn't always work

### ISSUE THREAD

**Issue by kitbellew** [scalameta/scalafmt#1041]
This template is a guideline, not a strict requirement.
- **Version**: 1.2.0
- **Integration**: CLI
- **Configuration**:
```
style = default
maxColumn = 100
danglingParentheses = true

align = none
align.tokens = []
align.openParenCallSite = false

newlines.alwaysBeforeTopLevelStatements = true
newlines.sometimesBeforeColonInMethodReturnType = false
newlines.alwaysBeforeCurlyBraceLambdaParams = true
newlines.afterImplicitKWInVerticalMultiline = true
newlines.beforeImplicitKWInVerticalMultiline = true

runner.fatalWarnings = true
runner.optimizer.forceConfigStyleOnOffset = 50
runner.optimizer.forceConfigStyleMinArgCount = 5

rewrite.rules = [ExpandImportSelectors, PreferCurlyFors]
```

## Steps

I ran scalafmt like this:

```bash
scalafmt
```

## Problem

Scalafmt formats code like this:
```scala
case class Z(
    x: (String, StructField)*
) {

  private val y: Map[String, A] =
    x.map {
      case (a, b) =>
        a -> A(
          ...
        )
    }.toMap
```

## Expectation

I would like the formatted output to look like this:
```scala
case class Z(
    x: (String, StructField)*
) {

  private val y: Map[String, A] =
    x
      .map {
        case (a, b) =>
          a -> A(
            ...
          )
      }
      .toMap
```

**Comment by olafurpg** [comment]
Thanks for reporting! This is a "feature" of scalafmt where it tries to not over-eagerly force

```
aaaa
  .b()
  .c()
```

for too short select chains. The relevant code is here https://github.com/scalameta/scalafmt/blob/509bad695ef6c4643554c72aef8d6975a18b92ce/scalafmt-core/shared/src/main/scala/org/scalafmt/internal/FormatOps.scala#L129-L135
we could add a `selectChains.minSize=2` option which you could change to `=0` or `=1` if you always want to force select chains. I might personally be tempted to set it to `=3` since I find it breaks chains a bit too eagerly.

**Comment by olafurpg** [comment]
The setting is working according to my personal preferences. I prefer
```
    x.map {
      case (a, b) =>
        a -> A(
          ...
        )
    }.toMap
```
over
```    x
      .map {
        case (a, b) =>
          a -> A(
            ...
          )
      }
      .toMap
```

Please reopen if you'd like to take a stab at adding a flag to get the other layout
          ...
        )
    }.toMap

**Comment by kitbellew** [comment]
@olafurpg thanks. i would normally just implement it and submit for review, but i have to admit that i have tried contributing to your project a few times and realized that my knowledge of scala is not as advanced as what's used in this codebase.

**Comment by olafurpg** [comment]
I understand, I admit the code is quite hairy 😅 the token-based best-first-search engine that dictates line wrapping (similar architecture as http://journal.stuffwithstuff.com/2015/09/08/the-hardest-program-ive-ever-written/) is really hard to scale.

FWIW, we have good progress in https://github.com/scalacenter/scala-syntax that implements a tree printer by traversing the AST and producing syntax from there. This design is simpler to reason about, be introduces new challenges like how to handle comments!
