### ISSUE TITLE
Functions with multiple parameters lists (e.g. implicit & explicit params, or curryable functions) look ugly

### ISSUE THREAD

**Issue by oliverlockwood** [scalameta/scalafmt#1059]
This template is a guideline, not a strict requirement.
- **Version**: 1.2
- **Integration**: neo-sbt-scalafmt
- **Configuration**:
```
style = defaultWithAlign
maxColumn = 120
includeCurlyBraceInSelectChains = false
newlines.sometimesBeforeColonInMethodReturnType = false
rewrite.rules = [SortImports, RedundantBraces, RedundantParens, PreferCurlyFors]
project.git = true
spaces.beforeContextBoundColon = true
```

## Steps

I ran scalafmt like this:

```bash
sbt
scalafmt
```

## Problem

Scalafmt formats code like this (a couple of examples):
```scala
  private def streamTest(test: (Probe[DecodeResult[Json]]) => Unit)(
     streamFactory: (Feed, ActiveMqConfig) => Probe[DecodeResult[Json]]): Unit = {
    ...
  }
```

```scala
  private def manageFragmentState(result: DecodeResult[(FragmentId, Fragment)],
                                  fragmentStateActor: ActorRef)(implicit ec: ExecutionContext, askTimeout: Timeout) = {
    ...
  }
```

## Expectation

I would like the formatted output to look like this:
```scala
  private def streamTest(test: (Probe[DecodeResult[Json]]) => Unit)
                        (streamFactory: (Feed, ActiveMqConfig) => Probe[DecodeResult[Json]]): Unit = {
    ...
  }
```

```scala
  private def manageFragmentState(result: DecodeResult[(FragmentId, Fragment)], fragmentStateActor: ActorRef)
                                 (implicit ec: ExecutionContext, askTimeout: Timeout) = {
    ...
  }
```

## Workaround

I've not managed to find one.

## Notes

I guess to my mind, I'd like the separate parameter lists to be aligned to the same point (as is done for multiple parameters within a single list) and have a higher priority given to splitting lines *between* those parameter lists, rather than *within* them.

What do people think?

**Comment by olafurpg** [comment]
Duplicate of https://github.com/scalameta/scalafmt/issues/337 ?

**Comment by oliverlockwood** [comment]
@olafurpg Right you are.  Apologies for not discovering the existing issue page.
