### ISSUE TITLE
optIn.configStyleArguments = false breaks with trailing commas

### ISSUE THREAD

**Issue by Katrix** [scalameta/scalafmt#1060]
This template is a guideline, not a strict requirement.
- **Version**: 1.3.0
- **Integration**: IntelliJ
- **Configuration**:
```
optIn.configStyleArguments = false
```

## Steps

I ran scalafmt like this:

```bash
Ctrl + Shift + L
```

## Problem

Formatted this
```scala
object Dummy {
  Seq(
    1,
    2,
    3,
  )
}
```

Scalafmt formats code like this:
```scala
object Dummy {
  Seq(1, 2, 3, )
}
```

## Expectation

I would like the formatted output to look like this:
```scala
object Dummy {
  Seq(1, 2, 3)
}
```

## Notes
Don't actually remember why I disabled configStyleArguments, but I think it had something to do with bad compatibility with IntelliJ style back in the day. Here'a bug report anyway.

**Comment by olafurpg** [comment]
Pending PR fixing this ticket

**Comment by olafurpg** [comment]
Link: https://github.com/scalameta/scalafmt/pull/1174
