### ISSUE TITLE
Parse error with trailing comma on last line followed by comments

### ISSUE THREAD

**Issue by jatcwang** [scalameta/scalafmt#1061]
```
  class Boo(
    a: Int,
    b: Int, // nope
  )
```

I'm getting a parse error `error: identifier expected but ) found )`. Removing the comment and it no longer errors

**Comment by olafurpg** [comment]
Thank you for reporting, this is a scalameta parser bug. I've reported it in https://github.com/scalameta/scalameta/issues/1131

It should be easy to fix in the parser. However, note that scalafmt is still on scalameta 1.7 and I'm not sure when we will be able to upgrade to scalameta 2.0.
