### ISSUE TITLE
Should not collapse class with trailing comma to one line, as it cause parse error for subsequent runs

### ISSUE THREAD

**Issue by jatcwang** [scalameta/scalafmt#1062]
Currently both Scala 2.12.3 and Scalafmt 1.3.0 emits parse error for the following snippet of code:

```
class Foo(a: Int, b: Int, )
```
which is expected. However, Scalafmt seems to convert the following snippet to one line (i.e. the code above)

```
class Foo(
  a: Int, 
  b: Int, 
)
```

This means that scalafmt actually turns valid code into code that no longer compiles (nor formats, if you run scalafmt again).

**Comment by olafurpg** [comment]
Duplicate of #1060 ?

**Comment by jatcwang** [comment]
Yeap I'll close and add some comment to that. Cheers
