### ISSUE TITLE
optIn.breakChainOnFirstMethodDot = false seems to not work , 1.3.0

### ISSUE THREAD

**Issue by jhegedus42** [scalameta/scalafmt#1064]
original : 
```
   val ref: Ref[Line] =
      Ref.make[Line]().lens(_.uuid.id)
         .set("4ce6fca0-0fd5-4197-a946-90f5e7e00d9d")
```

result : 
```
    val ref: Ref[Line] =
      Ref
        .make[Line]().lens(_.uuid.id)
        .set("4ce6fca0-0fd5-4197-a946-90f5e7e00d9d")
```

expected: keep original

Version : 1.3.0, IntelliJ plugin

**Comment by olafurpg** [comment]
Thanks for reporting! The setting is working as intended, scalafmt will always break chains that exceed the column limit. You might like `optIn.breaksInsideChains = true` which gives you full control over where to break in select chains.
