### ISSUE TITLE
Consume Scalameta Source object directly

### ISSUE THREAD

**Issue by mikaelstaldal** [scalameta/scalafmt#1065]
This template is a guideline, not a strict requirement.
- **Version**: 1.3.0
- **Integration**: standalone library

I use Scalameta for code generation (from scratch, there is no initial Scala source to parse), and I want to format the end result with scalafmt.

It would be useful to be able to feed a Scalameta `Source` object directly into scalafmt, without going through a `String`.

**Comment by olafurpg** [comment]
Scalafmt v1 requires tokens to work correctly so even if it had a method accepting `Source` it would have to use the scalameta built-in pretty-printer to first produce a `String`. There's a WIP tree printer in https://github.com/scalacenter/scala-syntax that will make printing `Source` possible while keeping comments etc.
