### ISSUE TITLE
RFE: no spaces in by-name parameters

### ISSUE THREAD

**Issue by fommil** [scalameta/scalafmt#1067]
it would be nice to have the option to format by-name parameters like `=>A` rather than `=> A`, making the arrow look like part of the type.

Hint from Olaf:
https://github.com/scalameta/scalafmt/blob/d2f968b943a5982dd2f24ec8763af19cd9e7149e/scalafmt-core/shared/src/main/scala/org/scalafmt/internal/Router.scala#L1375

**Comment by vovapolu** [comment]
![1000](https://user-images.githubusercontent.com/4629312/33205552-6493ff9e-d118-11e7-80eb-1a91b4c7a2a3.jpg)

**Comment by olafurpg** [comment]
@vovapolu scalafmt v2 is on track to become yet another huge pattern match but hopefully a bit easier to maintain https://github.com/olafurpg/scala-syntax/blob/19d283682167ad732dfa97cc256b870306113cdc/format/src/main/scala/org/scalafmt/internal/TreePrinter.scala#L42-L514

**Comment by vovapolu** [comment]
:) It's just a joke. I've almost figured it out.

**Comment by vovapolu** [comment]
Hmm, is v2 going to be a replacement for this? I mean should I fix this version or new?

**Comment by olafurpg** [comment]
it will still be a while until v2 gets released, I haven't yet solved how to preserve comments :)

**Comment by vovapolu** [comment]
@olafurpg PR is here!

**Comment by olafurpg** [comment]
Fixed by #1079
