### ISSUE TITLE
newlines.alwaysBeforeTopLevelStatements` does not recognize top-level statements with modifiers

### ISSUE THREAD

**Issue by mikaelstaldal** [scalameta/scalafmt#1068]
This template is a guideline, not a strict requirement.
- **Version**: 1.3.0
- **Integration**: standalone library
- **Configuration**:
```
newlines.alwaysBeforeTopLevelStatements = true
```

## Steps

I ran scalafmt like this:

```scala
import org.scalafmt.Scalafmt
import org.scalafmt.config.{Newlines, ScalafmtConfig}

object ScalaFormat {
  def main(args: Array[String]): Unit = {
    val source =
      """import collection.JavaConverters._
import com.foo.baz.Grunka
sealed trait Record
trait Entity {
  val kind: Kind
  val uri: String
}
object Entity {
  def foo = "bar"
}
case class EntityCase(foo: Int, bar: String) {
  def name = "Entity"
}
class Entity {
  def bar = 17
}"""

    val scalafmtConfig = ScalafmtConfig(newlines = Newlines(alwaysBeforeTopLevelStatements = true))
    val formattedSource = Scalafmt.format(source, scalafmtConfig).get
    print(formattedSource)
  }
}
```

## Problem

Scalafmt formats code like this:
```scala
import collection.JavaConverters._
import com.foo.baz.Grunka
sealed trait Record

trait Entity {
  val kind: Kind
  val uri: String
}

object Entity {
  def foo = "bar"
}
case class EntityCase(foo: Int, bar: String) {
  def name = "Entity"
}

class Entity {
  def bar = 17
}
```

## Expectation

I would like the formatted output to look like this:
```scala
import collection.JavaConverters._
import com.foo.baz.Grunka

sealed trait Record

trait Entity {
  val kind: Kind
  val uri: String
}

object Entity {
  def foo = "bar"
}

case class EntityCase(foo: Int, bar: String) {
  def name = "Entity"
}

class Entity {
  def bar = 17
}
```

## Notes

It seems like that `newlines.alwaysBeforeTopLevelStatements` does not recognize top-level statements with modifiers like `sealed` and `case` on top-level `class` and `trait`.

**Comment by olafurpg** [comment]
I believe this is intentional to support compact definitions of ADTs, wdyt @Daxten ?

**Comment by Daxten** [comment]
yes exactly, but maybe it should only keep them compact for:

* sealed trait
* case object
* case class

a normal object isn't normally part of an ADT

**Comment by sjrd** [comment]
If one wants compact definition of ADTs, by construction they don't want newlines *always*-before-top-level-statements. It does not make any sense for `newlines.alwaysBeforeTopLevelStatements` to have an exception for ADTs. It's *always*.

**Comment by olafurpg** [comment]
Please reopen if someone would like to take a stab at this.
