### ISSUE TITLE
Latest IntelliJ EAP no longer formats .sbt files

### ISSUE THREAD

**Issue by olafurpg** [scalameta/scalafmt#1076]
I upgrade IntelliJ to the latest EAP and it seems the scalafmt plugin no longer formats .sbt files, I'm handicapped 😨

**Comment by carstenlenz** [comment]
Same here :(

**Comment by olafurpg** [comment]
Should be fixed in 1.4.0 release https://plugins.jetbrains.com/plugin/8236-scalafmt/update/41928
