### ISSUE TITLE
Sponsorship of Vladimir for Functional Programming features

### ISSUE THREAD

**Issue by fommil** [scalameta/scalafmt#1078]
I am donating $4k of the (future) profits from [Functional Programming for Mortals with Scalaz](https://leanpub.com/fpmortals/) to Vladimir Polushin (@vovapolu) to improve scalafix, specifically for use in principled Functional Programming libraries and applications. Vladimir has already proven to be a capable developer and has delivered on two Scala Google Summer of Code projects and has been the [ENSIME sponsored developer](http://ensime.org/sponsor/) for several months.

A wise man once said that the more you learn about Scala, the more you learn what **not** to write. Much of the knowledge of what not to write can be codified in scalafix, a Scala Center project, often with automated rewrite rules. Although the goal of the [wartremover](https://github.com/wartremover/wartremover) project was similar, to restrict the developer to a safe subset of the Scala language, it is burdened by limitations of the compiler API that are only overcome by scala.meta and scalafix.

My priorities in the two months of Vladimir's time that I am funding are:

- to implement [new linters](https://github.com/wartremover/wartremover/issues/created_by/fommil) that I specifically wish to use
- to migrate the core wartremover warts to scalafix
- to ensure that the scalafix sbt plugin runs performantly on an sbt 1.0 build and respects per project and config scoping rules

If you would like to continue funding Vladimir, I urge you to contribute on bountysource, a sponsorship programme has been set up at:

  https://salt.bountysource.com/teams/scalafix

// @ClaireNeveu

**Comment by olafurpg** [comment]
Woot! I'm am thrilled @fommil. Thank you.

I hope this inspires more people to invest in Scala developer tooling, it's a ripe area sorely missing more funding.

I am eager to help Vladimir succeed in this project. I have seen him do great work in ENSIME (and scalafmt!), I'm excited to see what he will contribute to scalafix. I am happy to discuss more details over video chat if you want.

PS. Did you mean to open this ticket in the scalafmt repo or scalacenter/scalafix?

**Comment by fommil** [comment]
doh! I'll recreate!
