### ISSUE TITLE
Make sbt-scalafmt format on compile incremental

### ISSUE THREAD

**Issue by olafurpg** [scalameta/scalafmt#1091]
The new sbt-scalafmt plugin in #1085 currently does not cache the parsed .scalafmt.conf or which files have been formatted. This means on every compile, scalafmt re-parses .scalafmt.conf and re-formats **every** scala source file

**Comment by olafurpg** [comment]
Ping, any update on this?

**Comment by vovapolu** [comment]
Yeah, I remember :) I will fix it after scalafix tasks.

**Comment by olafurpg** [comment]
Fixed in #1136
