### ISSUE TITLE
Default indentation within function/class definition

### ISSUE THREAD

**Issue by jahan01** [scalameta/scalafmt#1094]
This not an issue, but a request for help.

I would like to set the indentation within function/class definition to 4 from the default 2. However I dont see any setting related to it. I see couple of settings for callsite and definition site but they dont fit my purpose. I scanned through documentation entirely, but couldnt find.

**Comment by olafurpg** [comment]
Hi, 2 space indentation is one of the few formatting conventions that pretty much the whole Scala community agrees on. I read in some experiment that  over 99% of Scala projects on GitHub use 2 space indent. I would like to keep it that way if possible, so scalafmt never got the option to configure indent.

**Comment by olafurpg** [comment]
Link to GitHub experiment https://ukupat.github.io/tabs-or-spaces/ 98.6% of major scala projects on github use 2 space indent

**Comment by Tasselmi** [comment]
hi guys,  I want to set the indentation to 4.........
How can I do it ?
2 is too short for me.....

**Comment by Tasselmi** [comment]
Can you guys make this to be self-configured ?
