### ISSUE TITLE
Add support for copying .scalafmt.conf from a resource

### ISSUE THREAD

**Issue by nrinaudo** [scalameta/scalafmt#1095]
This is something that I have implemented in my own autoplugins, and some interest in seeing it in the core plugin was expressed [on gitter](https://gitter.im/scalameta/scalafmt?at=5a48271f29ec6ac3119f724c).

My plan is to basically implement what I put in my own plugins:
- a `scalafmtResource` setting that contains the optional path to a `.scalafmt.conf` resource
- a `copyScalafmtConfig` task that copies `scalafmtResource` whenever it's set and differs from whatever is at the target destination.

I'll probably need to change things a bit to accomodate for the new `scalafmtConfig` setting.

@olafurpg is that what you expected, or did you have something different in mind?

**Comment by olafurpg** [comment]
In http://scalameta.org/scalafmt/#sbt-scalafmt there is currently a recommendation to generate .scalafmt.conf on sbt load with a hack like this. Can you elaborate why copying should happen on the `scalafmt` task instead of on sbt load?

```scala
SettingKey[Unit]("scalafmtGenerateConfig") :=
  IO.write( // writes to file once when build is loaded
    file(".scalafmt.conf"),
    """style = IntelliJ
      |# Your configuration here
      """.stripMargin.getBytes("UTF-8")
  )
```

**Comment by nrinaudo** [comment]
It's slightly more subtle than that: on every `scalafmt` call, _check if .scalafmt.conf needs to be copied_.

The subtlety lies in the fact that the conf is only copied if the target does not exist or is different from the expected one, not every single time `scalafmt` is called. In practice, this is usually 0 times.

My reasoning was that the requirement is not to have a valid `.scalafmt.conf` when sbt starts, but when you need to read the configuration file.

Also, I have some unusually sneaky colleagues who would change their local configurations and complain when CI failed their builds. It took me long enough to work out the first time that I decided to basically prevent this kind of behaviour.

**Comment by olafurpg** [comment]
Please reopen if someone would like to take a stab at this!
