### ISSUE TITLE
Unwated newline in PartialFunction

### ISSUE THREAD

**Issue by Katrix** [scalameta/scalafmt#1097]
This template is a guideline, not a strict requirement.
- **Version**: 1.4
- **Integration**: IntelliJ/CLI
- **Configuration**: Default

## Steps

Given code like this:
```scala
client.onEventCAlternate { implicit c => {
    case APIMessage.Ready(_)            => println("Foo")
    case APIMessage.ChannelCreate(_, _) => println("Foo")
  }
}
```

When I run scalafmt like this:

```bash
scalafmt -i /path/to/file
```

## Problem

Scalafmt formats code like this:
```scala
client.onEventCAlternate { implicit c =>
  {
    case APIMessage.Ready(_)            => println("Foo")
    case APIMessage.ChannelCreate(_, _) => println("Foo")
  }
}
```

## Expectation

I would like the formatted output to look like this:
```scala
client.onEventCAlternate { implicit c => {
    case APIMessage.Ready(_)            => println("Foo")
    case APIMessage.ChannelCreate(_, _) => println("Foo")
  }
}
```

**Comment by olafurpg** [comment]
Interesting, I have not seen that pattern before but I agree with you on the expected output. Fixing this issue should be doable with minor special handling for the newline before the opening `{`. The instructions in https://github.com/scalameta/scalafmt/blob/v0.6.8/Tutorial.md explain how it's possible to track down that `Split` if someone is interested in taking a swing at this.

**Comment by olafurpg** [comment]
Scalafmt is working as expected. A workaround is to write it like this instead

```scala
  client.onEventCAlternate(implicit c => {
    case APIMessage.Ready(_) => println("Foo")
    case APIMessage.ChannelCreate(_, _) => println("Foo")
  })
```

I am happy to merge a PR making scalafmt produce the expected syntax however if someone wants to take a stab at this!
