### ISSUE TITLE
Support trailing commas in sbt files

### ISSUE THREAD

**Issue by olafurpg** [scalameta/scalafmt#1098]
Currently, the sbt dialect is based of 211, which does not permit trailing commas. We should base it off the default lenient dialect.

**Comment by dwijnand** [comment]
I'm happy to try and fix this. How do I setup a failing test for this? I'm happy to look at prior art/PRs.

**Comment by olafurpg** [comment]
Very cool @dwijnand See 

- https://github.com/scalameta/scalafmt/blob/509bad695ef6c4643554c72aef8d6975a18b92ce/scalafmt-core/shared/src/main/scala/org/scalafmt/config/ScalafmtRunner.scala#L92
- https://github.com/scalameta/scalameta/blob/ecdaadfba7e883a93f4ddf2be7120631975a86ed/scalameta/dialects/shared/src/main/scala/scala/meta/dialects/package.scala#L173-L174

As for failing test, I think it should be sufficient to have a `org.scalafmt.DialectSuite` FunSuite that unit tests that

```scala
ScalafmtRunner.sbt("""
lazy 
val x = project(
  a,


  b,
)
"".parse[Source].get
```

doesn't crash
