### ISSUE TITLE
scalafmt is not compatible with scalameta 3+

### ISSUE THREAD

**Issue by pshirshov** [scalameta/scalafmt#1118]
Do you have any plans to port the library to 3.+?

RN it is failing on `import scala.meta.inputs.Input`:

`Missing class: scala/meta/inputs/Input
java.lang.NoClassDefFoundError: scala/meta/inputs/Input`

**Comment by olafurpg** [comment]
Duplicate of #975. This is a known issue, it's not clear when we'll be able to upgrade.
