### ISSUE TITLE
Bug: includeCurlyBraceInSelectChains=false doesn't always work

### ISSUE THREAD

**Issue by DieMyst** [scalameta/scalafmt#1124]
- **Version**: 1.4.0
- **Integration**: IntelliJ, CLI
- **Configuration**:
```
docstrings = JavaDoc
maxColumn = 120
includeCurlyBraceInSelectChains = false
rewriteTokens {
  "=>": "⇒"
  "<-": "←"
}
align.tokens = [
  { code = "=>", owner = "Case" },
  { code = "⇒", owner = "Case" },
  { code = "%", owner = "Infix" }
  { code = "%%", owner = "Infix" }
  { code = "%%%", owner = "Infix" }
  { code = ":=", owner = "Infix" }
]
spaces.inImportCurlyBraces = true
continuationIndent.extendSite = 2
binPack.parentConstructors = true
align.openParenDefnSite = false
danglingParentheses = true
spaces.beforeContextBoundColon = true
```

## Steps
I reformat code in IntelliJ or run scalafmt from CLI

## Problem

Code from guide works fine:
```scala
List(1)
  .map { x ⇒
    x + 2
  }.filter(_ > 2)
```

But if we add one line:
```scala
List(1)
  .map(x ⇒ x + 2)
  .map { x ⇒
    x + 2
  }.filter(_ > 2)
```

Scalafmt formats code like this:
```scala
List(1)
  .map(x ⇒ x + 2)
  .map { x ⇒
    x + 2
  }
  .filter(_ > 2)
```

## Expectation

I would like the formatted output to look like this:
```scala
List(1)
  .map(x ⇒ x + 2)
  .map { x ⇒
    x + 2
  }.filter(_ > 2)
```

**Comment by olafurpg** [comment]
Thanks for reporting! Although the documentation is not clear on the exact details on this setting, I believe it's working as intended. Once a chain has started it's not possible for a curly brace to escape it. The setting only has impact on the beginning of a chain with curly braces.
