### ISSUE TITLE
Long `type` assignments on multiple lines are collapsed to a single long line

### ISSUE THREAD

**Issue by iantabolt** [scalameta/scalafmt#1125]
We use long `type`s as a way of dependency injection similar to the cake pattern. We generally format the alias with one `with HasX` on each line. Some types might have dozens of dependencies so Scalafmt collapses this `type` assignment into a single very long line, potentially hundreds or thousands of characters long.

- **Version**: 1.4.0
- **Integration**: Commandline
- **Configuration**:
```
maxColumn = 100
```

## Steps

Given code like this:
```scala
object SomeJobService {
  type RequiredServices = Bag
    with HasClockService
    with HasDynamicConfig
    with HasFSLogger
    with HasFutureService
    with HasThrottles
    with HasThrowableNotifier
}
```

When I run scalafmt like this:

```bash
scalafmt SomeJobService.scala
```

## Problem

Scalafmt formats code like this (creates lines potentially much longer than 100 characters):
```scala
object SomeJobService {
  type RequiredServices =
    Bag with HasClockService with HasDynamicConfig with HasFSLogger with HasFutureService with HasThrottles with HasThrowableNotifier
}
```

## Expectation

I would like the formatted output to look like this:
```scala
object SomeJobService {
  type RequiredServices = Bag
    with HasClockService
    with HasDynamicConfig
    with HasFSLogger
    with HasFutureService
    with HasThrottles
    with HasThrowableNotifier
}
```
Well really I would expect it to be anything that doesn't violate the 100 maxColumn rule that is in place.

## Workaround

No workaround that I know of besides disabling the formatter for the line.

## Notes

Maybe this needs it's own configuration options to wrap it only at maxColumn, or to do one type per line like we have it.

**Comment by olafurpg** [comment]
Thanks for reporting! I agree the current output is a bug. Intersection types in type aliases should be treated the same way as template parent constructors (`extends Bag with HasClockService ...`).

**Comment by iantabolt** [comment]
Thanks for reviewing! I can try to fix this (and the other issue I just opened) myself if I get a chance in the next week or two.

So do you think it should follow whatever is in the parent constructors configuration, or use the same functionality but in a separate new configuration?

**Comment by olafurpg** [comment]
I took a quick stab at this issue and got promising results in https://github.com/scalameta/scalafmt/compare/master...olafurpg:1125?expand=1 The fix is to treat `with` chains in type aliases the same as with chains in self annotations `class A { self: A with B with C => ...}`

Could you try and add more relevant test cases @iantabolt ? If it works for you feel free to open a PR :)

**Comment by iantabolt** [comment]
Awesome!! Yes I'll add a couple more test cases and open a PR if it works

**Comment by iantabolt** [comment]
Another similar scenario pops up in our codebase is

```scala
trait NeedsServices {
  def services: Bag
    with SomeOtherService.RequiredServices
    with HasDynamicConfig
    with HasThrottles
    with HasThrowableNotifier
}
```

Currently, this test ends up getting formatted as

```scala
trait NeedsServices {
  def services
    : Bag with SomeOtherService.RequiredServices with HasDynamicConfig with HasThrottles with HasThrowableNotifier
}
```

Do you think this is in the scope of this issue? I'd like to add a fix for that as well.

**Comment by yesufeng** [comment]
still get this issue in version 3.1.0

def method(a: A): Dataset[T with B with C with D...]
the type of Dataset can be a long line that scalafmt does not wrap
