### ISSUE TITLE
Unnecessary newline+indent before function call with multiline argument

### ISSUE THREAD

**Issue by iantabolt** [scalameta/scalafmt#1126]
### Background:

Our style guide requires parentheses around all function calls -- so `Future({ ... })` instead of `Future { ... }`. Scalafmt handles this well unless it follows a `def`, in which case it inserts a newline and indents the entire block.

### Before scalafmt:

```scala
def foo = bar(x => {
  // some code
})
```

### After scalafmt:
```scala
def foo = 
  bar(x => {
    // some code
  })
```

### Expected: 

No change. 

Interestingly, these similar cases are unchanged as expected:

```scala
// val instead of def
val foo = bar(x => {
  // some code
})

// no parens
def foo = bar { x =>
  // some code
}
```

**Comment by olafurpg** [comment]
Thanks for reporting!

> Our style guide requires parentheses around all function calls -- so Future({ ... }) instead of Future { ... }

Have you considered implementing a rewrite rule to automatically enforce that? It should be quite simple, in psuedocode

```scala
tree.collect {
  case Term.Apply(_, (block @ Term.Block(_)) :: Nil) if !block.tokens.last.is[Token.RightParen] =>
    Seq(AddLeft(block, "("), AddRight(block, ")"))
}
```

Back to the issue, this is an unintended side effect of some decisions I made in the early days that haven't been questioned until today 😄 I agree the behavior is inconsistent between def/val

Commenting out a single line makes the behavior consistent for val/def https://github.com/scalameta/scalafmt/commit/0861b3b84a7e50825272592ee6f6cb458554255e Would you be tempted to turn that into a configuration option with the new behavior under an opt-in flag? Any suggestions for a name?

**Comment by olafurpg** [comment]
There is in fact a simpler change that makes the handling of ( and { consistent

https://github.com/scalameta/scalafmt/commit/b06cea0323f8a9a3b321c780ed5fc54dbc376134

I can't remember why I wanted to allow config style
```scala
def foo = Bar(
 ...
)
```
but not
```scala
def foo = Bar(x =>
  ...
)
```
I would prefer your expected output over the current default.

We'd still need a flag for users to opt-out of the new changes...

**Comment by iantabolt** [comment]
> Have you considered implementing a rewrite rule to automatically enforce that?

Great idea!

> Would you be tempted to turn that into a configuration option with the new behavior under an opt-in flag?

Yes

> Any suggestions for a name?

This is tough. The best I could think of is `breakBeforeFunctionCallBody` but it still doesn't quite sum up what is going on. Do you have any suggestions?

Also, you might be aware but the `val`/`def` inconsistency seems to exist for any multi-line body:

Before:

```scala
  def foo = bar.flatMap(f)
    .map(g)

  val foo = bar.flatMap(f)
    .map(b)
```

After:

```scala
  def foo =
    bar
      .flatMap(f)
      .map(g)

  val foo = bar
    .flatMap(f)
    .map(g)
```

Should this config control this behavior as well, or only the original issue of the higher order function body?

**Comment by olafurpg** [comment]
> Also, you might be aware but the val/def inconsistency seems to exist for any multi-line body:

Those are caused by the same SingleLinePolicy. I don't remember to original motivation for treating val/def separately so I think it would be an improvement to make them behave the same.

> The best I could think of is breakBeforeFunctionCallBody but it still doesn't quite sum up what is going on. Do you have any suggestions?

With https://github.com/scalameta/scalafmt/commit/0861b3b84a7e50825272592ee6f6cb458554255e the setting could be called `newlines.alwaysBeforeMultilineDef`. The SingleLinePolicy eliminates the space after `=` is the body of the def can't fit on a single line. The setting would be true by default (current behavior) and when it's false the policy is empty instead of SingleLinePolicy. WDYT?

**Comment by iantabolt** [comment]
>  I don't remember to original motivation for treating val/def separately

I think this issue only stands out because the `def` has no parameters or return type, which isn't very common. The line break is nice after a typical `def foo(bar: Bar): Foo = ` kind of signature. I can definitely see an argument for it.

> the setting could be called `newlines.alwaysBeforeMultilineDef`.

Perfect name

> WDYT?

Makes total sense. I'll open a PR.
