### ISSUE TITLE
Integration test formatting gone?

### ISSUE THREAD

**Issue by NeQuissimus** [scalameta/scalafmt#1127]
When updating to `sbt-scalafmt` v1.4.0, it seems that the plugin no longer formats sources in `src/it/scala`.

Before, it would, presumably because of #297.

It would be amazing if we could have that functionality back.

Or, if it already exists, I could not figure it out and I would appreciate a "how-to" :)

**Comment by olafurpg** [comment]
From what version did you upgrade? You will need to opt-into formatting IntegrationTest with settings like here https://github.com/scalameta/scalafmt/blob/b5b25e13aeaa05e8d17422f4f512971e2619b918/scalafmt-sbt/src/main/scala/org/scalafmt/sbt/ScalafmtPlugin.scala#L204

**Comment by olafurpg** [comment]
@vovapolu could you please update the docs on sbt-scalafmt to explain how to enable integration test config?

**Comment by NeQuissimus** [comment]
I came from v1.3.0 and am pretty sure it formatted integration tests but I don't have them in too many projects, so I am actually not 100% on that.
I will try out the solution above. Thank you very much

**Comment by yawaramin** [comment]
This seems to be affecting older versions too. My project is currently on 1.14. I'm actually not sure how to apply the suggested solution. We have a standard setup with the sbt-scalafmt plugin and the `scalafmtOnCompile` setting in our `build.sbt` file. We're going to track this issue for now, but let me know if there's anything else I can do.
