### ISSUE TITLE
Complex Json reads broken after formatting

### ISSUE THREAD

**Issue by PatrykRudnicki** [scalameta/scalafmt#1141]
Hello!

I found a problem with formatting scala files contains classes with custom JSON reads and writes.

So we can start from this link: https://www.playframework.com/documentation/2.6.x/ScalaJsonCombinators#complex-reads

Here you can see two different way of creating complex reads. I have a problem with formatting second one (in one statement):
Original version from play documentation:
```
implicit val locationReads: Reads[Location] = (
  (JsPath \ "lat").read[Double] and
  (JsPath \ "long").read[Double]
)(Location.apply _)
```

So if you have configuration: remove redundant braces and adding dot near method Scalafmt changed this code to this:
```
implicit val locationReads: Reads[Location] =
    (JsPath \ "lat").read[Double].and((JsPath \ "long").read[Double])
  (Location.apply _)
```

This version is incorrect and during compilation, there are some errors.

For short moment I think that there is one workaround for it. Split it like in example version in the documentation for a method with a builder and apply, but the problem is with `and` too.

In my opinion, the expected behaviour should don't remove parenthesis in reads and writes.

I don't have any idea how to solve it. If you have some comments, hint it can be awesome :)

I look for issues similar to my problem, but I don't find anything so I decided to create a new one.

Have a nice evening!

**Comment by olafurpg** [comment]
Thanks for reporting! Can you please include the configuration? This seems like a problem with either AvoidInfix or RedundantParens.

**Comment by PatrykRudnicki** [comment]
Yeah, It can be helpful :)

```
align: true
align {
  openParenCallSite: false
  openParenDefnSite: false
}
maxColumn: 120
style: IntelliJ
docstrings: JavaDoc
spaces.afterKeywordBeforeParen: false
binPack.parentConstructors: true
includeCurlyBraceInSelectChains: false
optIn.breakChainOnFirstMethodDot: false
includeCurlyBraceInSelectChains: false
newlines {
  penalizeSingleSelectMultiArgList: true
  beforeImplicitKWInVerticalMultiline: false
  afterImplicitKWInVerticalMultiline: false
  alwaysBeforeElseAfterCurlyIf: false
}
rewrite.rules: [
  AvoidInfix,
  PreferCurlyFors
  RedundantBraces,
  RedundantParens,
  SortImports
]
```
In `plugins.sbt` version 1.15.

The problem appears during using shortcut inside Intellij. 
I have a scalafmt plugin version: 1.4.0
Intellij IDEA Ultimate 2017.2.7

During using command scalafmt from console to format the whole project is the same problem.

**Comment by olafurpg** [comment]
Thanks for the config, I was able to reproduce. What is your expected output?

**Comment by olafurpg** [comment]
The culprit rewrite seems to be `AvoidInfix`, any chance you could take a look @ysusuk ?

```scala
// before
implicit val locationReads: Reads[Location] = (
  (JsPath \ "lat").read[Double] and
  (JsPath \ "long").read[Double]
)(Location.apply _)
// after
  implicit val locationReads: Reads[Location] =
    (JsPath \ "lat").read[Double].and((JsPath \ "long").read[Double])
  (Location.apply _)
// expected (my guess)
  implicit val locationReads: Reads[Location] = (
    (JsPath \ "lat").read[Double].and((JsPath \ "long").read[Double])
  )(Location.apply _)
```

with `rewrite.rules = [AvoidInfix]`. It seems the enclosparentheses

**Comment by PatrykRudnicki** [comment]
Hello @olafurpg! Yeah, your expected solution from the previous method is good :)

One comment, we need to think that the class can contain more field, so the reads and writes will be longer. My propose is to split expression by `.and` so, in that case, every `JsPath` should be in new line (similar to the example from play documentation) or `JsPath` with `and` in a new line (I don't know what is better, I think the previous solution).

**Comment by olafurpg** [comment]
@PatrykRudnicki can you please write concrete code examples? It's difficult to infer code formatting from natural language explanations

**Comment by PatrykRudnicki** [comment]
Code example (for short version):
```scala
implicit val locationReads: Reads[Location] = 
  ((JsPath \ "lat").read[Double].and((JsPath \ "long").read[Double]))(Location.apply _)
```

For more fields:
```scala
implicit val locationReads: Reads[Location] = (
  (JsPath \ "lat").read[Double].and
  ((JsPath \ "long).read[Double]).and
  ((JsPath \ "anotherField").read[String])
)(Location.apply _)
```

Or with open parenthesis near and:
```scala
implicit val locationReads: Reads[Location] = (
  (JsPath \ "lat").read[Double].and(
  (JsPath \ "long").read[Double]).and(
  (JsPath \ "anotherField").read[String])
)(Location.apply _)
```

**Comment by olafurpg** [comment]
Superseded by #1196
