### ISSUE TITLE
Move the website to something tut + markdown based

### ISSUE THREAD

**Issue by olafurpg** [scalameta/scalafmt#1146]
The current website http://scalameta.org/scalafmt/ is built with scalatex (http://www.lihaoyi.com/Scalatex/). While I've personally found scalatex to be pretty great, the unorthodox markup language is a barrier for contributors. I would love to migrate the website to something tut + markdown based.

Copy-paste from #1144 

I've tried hugo, gitbook, docusaurus, jekyll, [ornate](https://szeiger.github.io/ornate-doc/), [doxidize](https://steveklabnik.github.io/doxidize/quickstart.html), [sphinx](http://www.sphinx-doc.org/en/master/), read the docs, [mkdocs](http://www.mkdocs.org/) but struggled to get

- github-flavored markdown 
- mobile friendly
- always accessible sidebar to jump between pages
- always accessible TOC for open page
- search (either generated in site or algolia is fine too)
- "edit on github" links
- anchor refs to headers for easy "click and share link to section"
- template variable splicing to insert dynamic strings like project version (for copy-paste friendly installation instructions).
- ability to inline subsets of external files, like `@hl.ref` in http://www.lihaoyi.com/Scalatex/#Highlighter (ideally with link to original file on github)
- fast edit/preview feedback loop
- nice landing page, something like https://docusaurus.io/ or https://bucklescript.github.io/
- (optional) single page pdf generation

I can configure tut integration and publish to ghpages with mostly anything, and also port the existing scalatex pages to markdown + tut. My failure is a bigger sign of my experience with html/css than lack of functionality in those site generators 😅

**Comment by olafurpg** [comment]
PS. We are working on setting up a site for metals in https://github.com/scalameta/metals/pull/294 thanks to @gabro . I would love to reuse the same setup for

- http://scalameta.org/metals
- http://scalameta.org/
- http://scalameta.org/tutorial
- http://scalameta.org/scalafmt
- http://scalameta.org/metadoc (and move code browser demo to another subpage)

**Comment by gabro** [comment]
This is now live!
