### ISSUE TITLE
New SortModifiers overwrites modifiers of implicit class parameter val/vars

### ISSUE THREAD

**Issue by lorandszakacs** [scalameta/scalafmt#1148]
- **Version**: 1.5.0
- **Integration**: IntelliJ, SBT
- **Configuration**:
```
rewrite {
  rules = [SortModifiers]
  sortModifiers {
    #the crucial part of this bug is for modifiers to have higher precedence than "implicit"
    order = ["private", "protected", "implicit", "final", "sealed", "abstract", "override", "lazy"]
  }
}
```

## Steps

Given code like this:
```scala
class Test(private val x: Int)(
  implicit
  private val i1: Int,
  private val i2: String
)
```

When I run scalafmt anywhere (IntelliJ, or SBT).

## Problem

Scalafmt formats code like this:
```scala
class Test2(private val x: Int)(
  implicit
  implicit val i1: Int,
  implicit val i2: String
)
```

## Expectation

I would like the formatted output to look like this:
```scala
class Test2(private val x: Int)(
  implicit
  private val i1: Int,
  private val i2: String
)
```

## Workaround

I've found that this happens only if the class parameters have modifiers that have higher precedence than `implicit`.

**Comment by olafurpg** [comment]
I'm wondering if we can "fix" this issue by skipping `Term.Param`? Alternatively, note that `Mod.Implicit()` is attached to all parameters in the implicit parameter list.
