### ISSUE TITLE
SortModifiers website examples looks weird

### ISSUE THREAD

**Issue by olafurpg** [scalameta/scalafmt#1149]
<img width="1419" alt="screen shot 2018-04-24 at 09 08 48" src="https://user-images.githubusercontent.com/1408093/39171444-239795e8-479f-11e8-8ba3-5710814cfd5e.png">

I think it would be clearer if the code examples were smaller and vertically next to each other
```scala
implicit final val x // before
final implicit val x // after
```

cc/ @lorandszakacs

**Comment by olafurpg** [comment]
This went by review since the SortModifiers PR was open at the same time as the website css change, it was unfortunate they conflicted in this way.

**Comment by lorandszakacs** [comment]
@olafurpg can be closed. Did not use correct `Closes` syntax in the PR 😊
