### ISSUE TITLE
Enable danglingParentheses by default

### ISSUE THREAD

**Issue by dwijnand** [scalameta/scalafmt#1151]
Given the community's vote: https://twitter.com/dwijnand/status/983979109918347264 I propose the default for `danglingParentheses` be flipped to `true`.

What do you think?

(This isn't a problem/expectation type of request, more of a discussion, so I've not filled out the template - I hope that's ok.)

**Comment by olafurpg** [comment]
Can you please include motivating examples for this change with code examples before and after?

**Comment by dwijnand** [comment]
Will a link to the gist do? I can inline if you prefer.

https://gist.github.com/dwijnand/13b07e9f749f318602887edeb32603c1

**Comment by olafurpg** [comment]
It's better to inline here. I haven't tried, what happens if `align.openParen{Call,Defn}Site` remains true by default? I think they need to be false for dangling parens to work as expected. It would be good to expand on that.

Once those details are cleared I'll ping people on gitter for comments.

**Comment by dwijnand** [comment]
## Context

In current Scalafmt (1.5.0) the default configs are:

```
align.openParenCallSite = true
align.openParenDefnSite = true
danglingParentheses = false
```

I'm proposing flipping `danglingParentheses = true`, but Olaf rightly wants to look at how `align.openParenCallSite` and `align.openParenDefnSite` affects the change.

## Case 1: `class ChangeOwnerAndModuleClassTraverser`

### a. just disable open paren

```
align.openParenCallSite = false
align.openParenDefnSite = false
danglingParentheses = false
```

```scala
  private[this] class ChangeOwnerAndModuleClassTraverser(
      oldowner: global.Symbol,
      newowner: global.Symbol)
      extends global.ChangeOwnerTraverser(oldowner, newowner) {
    override def traverse(tree: global.Tree): Unit = {
      tree match {
```

### b. disable open paren, enable dangling parens

```
align.openParenCallSite = false
align.openParenDefnSite = false
danglingParentheses = true
```

```scala
  private[this] class ChangeOwnerAndModuleClassTraverser(
      oldowner: global.Symbol,
      newowner: global.Symbol
  ) extends global.ChangeOwnerTraverser(oldowner, newowner) {
    override def traverse(tree: global.Tree): Unit = {
      tree match {
```

### c. just enable dangling parens

```
align.openParenCallSite = true
align.openParenDefnSite = true
danglingParentheses = true
```

```scala
  private[this] class ChangeOwnerAndModuleClassTraverser(oldowner: global.Symbol,
                                                         newowner: global.Symbol)
      extends global.ChangeOwnerTraverser(oldowner, newowner) {
    override def traverse(tree: global.Tree): Unit = {
      tree match {
```

## Case 2: `def transformWrappers`

### a. just disable open paren

```
align.openParenCallSite = false
align.openParenDefnSite = false
danglingParentheses = false
```

```scala
   * Typically, `f` is a `Select` or `Ident`.
   * The wrapper is replaced with the result of `subWrapper(<Type of T>, <Tree of v>, <wrapper Tree>)`
   */
  def transformWrappers(
      t: Tree,
      subWrapper: (String, Type, Tree, Tree) => Converted[ctx.type]): Tree = {
    // the main tree transformer that replaces calls to InputWrapper.wrap(x) with
    //  plain Idents that reference the actual input value
    object appTransformer extends Transformer {
```

### b. disable open paren, enable dangling parens

```
align.openParenCallSite = false
align.openParenDefnSite = false
danglingParentheses = true
```

```scala
   * Typically, `f` is a `Select` or `Ident`.
   * The wrapper is replaced with the result of `subWrapper(<Type of T>, <Tree of v>, <wrapper Tree>)`
   */
  def transformWrappers(
      t: Tree,
      subWrapper: (String, Type, Tree, Tree) => Converted[ctx.type]
  ): Tree = {
    // the main tree transformer that replaces calls to InputWrapper.wrap(x) with
    //  plain Idents that reference the actual input value
    object appTransformer extends Transformer {
```

### c. just enable dangling parens

```
align.openParenCallSite = true
align.openParenDefnSite = true
danglingParentheses = true
```

```scala
    * Typically, `f` is a `Select` or `Ident`.
    * The wrapper is replaced with the result of `subWrapper(<Type of T>, <Tree of v>, <wrapper Tree>)`
    */
   def transformWrappers(t: Tree,
                         subWrapper: (String, Type, Tree, Tree) => Converted[ctx.type]): Tree = {
     // the main tree transformer that replaces calls to InputWrapper.wrap(x) with
     //  plain Idents that reference the actual input value
     object appTransformer extends Transformer {
```

## Case 3: `ApplyTree`

### a. just disable open paren

```
align.openParenCallSite = false
align.openParenDefnSite = false
danglingParentheses = false
```

```scala
private[this] def makeKList(
    revInputs: Inputs[c.universe.type],
    klist: Tree,
    klistType: Type): Tree =
  revInputs match {
    case in :: tail =>
      val next = ApplyTree(
        TypeApply(
          Ident(kcons),
          TypeTree(in.tpe) :: TypeTree(klistType) :: TypeTree(mTC) :: Nil),
        in.expr :: klist :: Nil)
      makeKList(tail, next, appliedType(kconsTC, in.tpe :: klistType :: mTC :: Nil))
    case Nil => klist
  }
```

### b. disable open paren, enable dangling parens

```
align.openParenCallSite = false
align.openParenDefnSite = false
danglingParentheses = true
```

```scala
private[this] def makeKList(
    revInputs: Inputs[c.universe.type],
    klist: Tree,
    klistType: Type
): Tree =
  revInputs match {
    case in :: tail =>
      val next = ApplyTree(
        TypeApply(
          Ident(kcons),
          TypeTree(in.tpe) :: TypeTree(klistType) :: TypeTree(mTC) :: Nil
        ),
        in.expr :: klist :: Nil
      )
      makeKList(tail, next, appliedType(kconsTC, in.tpe :: klistType :: mTC :: Nil))
    case Nil => klist
  }
```

### c. just enable dangling parens

```
align.openParenCallSite = true
align.openParenDefnSite = true
danglingParentheses = true
```

```scala
      private[this] def makeKList(revInputs: Inputs[c.universe.type],
                                  klist: Tree,
                                  klistType: Type): Tree =
        revInputs match {
          case in :: tail =>
            val next = ApplyTree(
              TypeApply(Ident(kcons),
                        TypeTree(in.tpe) :: TypeTree(klistType) :: TypeTree(mTC) :: Nil),
              in.expr :: klist :: Nil
            )
            makeKList(tail, next, appliedType(kconsTC, in.tpe :: klistType :: mTC :: Nil))
          case Nil => klist
        }
```

**Comment by olafurpg** [comment]
Thanks @dwijnand.

This is a proposal to enable by default the following settings

```
align.openParenCallSite = false
align.openParenDefnSite = false
danglingParentheses = true
```

In the current v1.5 release, those values are flipped by default.

In summary, this implies the following change

```scala
// before
case class User(name: String,
                age: Int)
// after
case class User(
    name: String,
    age: Int
)

// before
List(
  libraryDependencies := List(
      "org" % "name" % "version",
      "org" % "name" % "version"),
  scalacOptions := List(
      "-Ywarn-unused-import",
      "-fatal-warning"))
// after
List(
  libraryDependencies := List(
      "org" % "name" % "version",
      "org" % "name" % "version"
  ),
  scalacOptions := List(
      "-Ywarn-unused-import",
      "-fatal-warning"
  )
)
```

For a larger example, see [this diff](https://github.com/non/jawn/commit/a74c34cd0b65041903a019d5862f59e544063a23) from the jawn repo.

One additional benefit of this change is improved performance and fewer "Search state exploded" errors. I personally use these settings by default in my projects so I'm in favor of making them default 👍

**Comment by olafurpg** [comment]
Upvote this comment if you want to keep the defaults unchanged.

**Comment by olafurpg** [comment]
Upvote this comment if you are in favor of this proposal to change the defaults.

**Comment by dwijnand** [comment]
> One additional benefit of this change is improved performance and fewer "Search state exploded" errors.

Indeed. There's a few files in sbt/sbt that are now finally formatted (e.g AList.scala).

**Comment by mads-hartmann** [comment]
@olafurpg It might make sense to then change the defaults for `excludeDanglingParens.excludeDanglingParens` to the empty list as well (before we merge #1154) ☺️

**Comment by olafurpg** [comment]
The response so far is strongly in favor of the change (12 votes vs. 0 votes). Voting closes the end of this week May 6th.

**Comment by olafurpg** [comment]
One more day left to vote, the results are 23 in favor of changing the defaults and 1 vote in favor of keeping the default unchanged.

**Comment by olafurpg** [comment]
Voting is over! The default will change 🎉 

Will get #1145 merged first before looking at this. Don't expect 1.6 to be out until around June.

**Comment by dwijnand** [comment]
https://github.com/scalameta/scalafmt/labels/good%20first%20time%20contribution ?

**Comment by olafurpg** [comment]
It requires a bit of custom work to flip the defaults so I don't think it's a good fit for first-time contributors. In particular, I'd like to add more unit tests stressing the new settings to prevent further regressions.

**Comment by olafurpg** [comment]
Maybe we can do it at the spree on Tuesday in Berlin :)

**Comment by olafurpg** [comment]
Opened https://github.com/scalameta/scalafmt/pull/1198 to change the default 🎉
