### ISSUE TITLE
Indentation of if-expressions in for comprehensions

### ISSUE THREAD

**Issue by lbialy** [scalameta/scalafmt#1166]
- **Version**: 0.5
- **Integration**: IntelliJ
- **Configuration**:

## Steps

Given single line if expression I'd like to break into two lines:
```
      _ <- if (namespace.requireActivation) activation.initialize(user, namespace) else user.pure[F]
```

I get:
```
      _ <- if (namespace.requireActivation) activation.initialize(user, namespace)
      else user.pure[F]
```
where I'd prefer else to be indented to if level:
```
      _ <- if (namespace.requireActivation) activation.initialize(user, namespace)
           else user.pure[F]
```

**Comment by Kavit900** [comment]
@olafurpg  I would like to get my hands dirty on this, it could be my first time scala contribution. What do you think ?

**Comment by olafurpg** [comment]
Hi @Kavit900 👋 Thanks for the interest! I took another look and am afraid I estimate this issue is more work that I originally expected since it will require touching Router.scala. I have removed the "good first time contribution". We recently cleaned up the scalafmt issue tracker so there are not many low hanging fruit issues remaining 🤔

**Comment by Kavit900** [comment]
Hi @olafurpg  got it, no worries, let me know if there is any beginner's issue that I can work on and learn more about open source contribution. Thank you @olafurpg  :)

**Comment by MaximeKjaer** [comment]
As a workaround for now, you can parenthesize the if-expression to achieve the expected formatting.

```scala
for {
  _ <- (if (namespace.requireActivation) activation.initialize(user, namespace)
        else user.pure[F])
} yield ???
```

**Comment by kitbellew** [comment]
@lbialy @Kavit900 @MaximeKjaer can you please check out v2.5.0-RC2? looking at the code, if you use `align.arrowEnumeratorGenerator = true`, it will align on the arrow; and if you don't, will fit on one line or break before `if`.

**Comment by MaximeKjaer** [comment]
The changes from v2.5.0-RC2 work nicely on the one example that I have of this in my codebase, so I think this issue can be closed.

The only small thing that I'm noticing is that the spacing with `align.arrowEnumeratorGenerator = true` is not quite what I expect. I get:

```scala
for {
  pathExists <- fs.pathExists(artifactPath).toFuture
  file <- if (pathExists) fetchLocal(artifactPath)
         else fetchRemote(artifact.url, artifactPath)
} yield file
```

Whereas I would expect the `else` to be aligned with `if`:

```scala
for {
  pathExists <- fs.pathExists(artifactPath).toFuture
  file <- if (pathExists) fetchLocal(artifactPath)
          else fetchRemote(artifact.url, artifactPath)
} yield file
```

Is this as intended?

**Comment by poslegm** [comment]
Weird alignment `if/else` with `arrowEnumeratorGenerator` is a known bug https://github.com/scalameta/scalafmt/issues/1797
