### ISSUE TITLE
Export (effective) scalafmt configuration in IntellJ-compatible format

### ISSUE THREAD

**Issue by hmemcpy** [scalameta/scalafmt#1167]
(I just started using scalafmt/intellij plugin, so if I'm obviously missing something, I apologize)

I just installed the plugin, and am very happy with the results of pressing Ctrl+Shift+L in my file. However, it seems that scalafmt style does not replace the built in IntelliJ style for Scala (Editor -> Code Style -> Scala).
If I understood correctly, the work being done in https://youtrack.jetbrains.com/issue/SCL-13658 intends to replace the internal formatting engine with scalafmt, allowing IntelliJ to correctly auto-format the code elements.

Until that happens, I propose a feature, where the current (effective, taking into account various overrides from .scalafmt.conf) settings can be exported into IntelliJ-compatible XML format (packed in a .jar file), so they could be imported globally into IntelliJ.

Alternatively, as an improvement for #419, a button in the plugin settings that could apply scalafmt style to the current IntelliJ code style settings.

Is there an obvious usage mode I'm missing here?

**Comment by olafurpg** [comment]
Thanks for reporting! I am personally on the fence to support this functionality since that would require the CLI, sbt plugin and other editor integrations (vscode, ...) to understand the XML format. I understand it's annoying to copy-paste the .scalafmt.conf file between projects but it's the only way I see to make all integrations work the same way.

**Comment by hmemcpy** [comment]
Thanks for your reply! Just to make sure we're talking about the same thing, what I meant was, e.g. a command-line argument for scalafmt to export its effective config settings. The default could be a `.scalafmt.conf` format. An additional flag would specify the target output format, i.e. IntelliJ.
Just to be sure, when I invoke "Export Settings" in IntelliJ, selecting only "Code Style", produces:
`settings.jar` -> `./codestyles/Default.xml`, which contains:
```
<code_scheme name="Default" version="173">
  <ScalaCodeStyleSettings>
    <option name="NOT_CONTINUATION_INDENT_FOR_PARAMS" value="true" />
    <option name="INDENT_FIRST_PARAMETER_CLAUSE" value="true" />
    <option name="ALIGN_TYPES_IN_MULTILINE_DECLARATIONS" value="true" />
  </ScalaCodeStyleSettings>
  <codeStyleSettings language="Scala">
    <option name="METHOD_PARAMETERS_LPAREN_ON_NEXT_LINE" value="true" />
    <option name="METHOD_PARAMETERS_RPAREN_ON_NEXT_LINE" value="true" />
  </codeStyleSettings>
</code_scheme>
```
etc.

This would be an IntelliJ-specific file. In the future, there could be other export providers to support additional editors.

But... having said that, I understand your reluctance in introducing this feature, as it would effectively mean "duplicating" scalafmt functionality into the editor.

**Comment by olafurpg** [comment]
I see, thanks for the explanation @hmemcpy . I am afraid this is outside the scope of the scalafmt IntelliJ plugin. I think the best place to move this forward would be to leave a comment in https://youtrack.jetbrains.com/issue/SCL-13658 The official IntelliJ Scala plugin may be able to support this use case!
