### ISSUE TITLE
Enforce or remove trailing commas

### ISSUE THREAD

**Issue by gabro** [scalameta/scalafmt#1173]
I think it would be useful for scalafmt to enforce/remove trailing commas, so that a codebase can adopt a consistent style with those.

Ideally

with this config

```json
{
  "align": "none",
  "danglingParentheses": true,
  "trailingCommas": true
}
```

and given this code

```scala
// column limit   |
case class MyClass(a: String, b: Int)
```

this would happen

```scala
case class MyClass(
  a: String,
  b: String,
)
```

---

Some other cases:

```scala
// column limit                      |
case class MyClass(a: String, b: Int)
```

nothing happens (trailing commas not inserted if not followed by a newline).

---

```json
{
  "align": "none",
  "danglingParentheses": false,
  "trailingCommas": true
}
```

```scala
// column limit   |
case class MyClass(a: String, b: Int)
```

no trailing comma, because danglingParentheses is `false` (and a trailing comma would be invalid syntax)

```scala
case class MyClass(
  a: String,
  b: String)
```

---

I'll flesh out more details as we discuss.

**Comment by olafurpg** [comment]
This is a great idea! I think it would be good if scalafmt would both insert trailing commas when they're applicable and also remove trailing commas if moving a multi-line argument list into a single line
```scala
// before
foo(
  a,
)
// after
foo(a)
```

I think the best place to implement this is in `FormatWriter` where syntax is written to a StringBuilder
https://github.com/scalameta/scalafmt/blob/8a7f26913a24c9eff9ad4adc64e059c87087eef9/scalafmt-core/shared/src/main/scala/org/scalafmt/internal/FormatWriter.scala#L32-L59

The idea would be to either synthesize a `,` when it's needed or skip a `,` when it should be removed. I don't see better approach to implement this given the current architecture.

**Comment by olafurpg** [comment]
For reference, here are the rules used by the parser to determine a trailing comma https://github.com/scalameta/scalameta/blob/6a8d24b638c27e4cbf8db5ba3889c56ba6a6e335/scalameta/parsers/shared/src/main/scala/scala/meta/internal/parsers/ScalametaParser.scala#L204-L211
