### ISSUE TITLE
Unicode literals in pattern position are not preserved

### ISSUE THREAD

**Issue by olafurpg** [scalameta/scalafmt#1176]
The following test fails on master despite the upgrade to scalameta v3.7 in #1170
```scala
<<< ONLY scalafix#619
def a = (1, 2, 3) match { case (r, \u03b8, \u03c6) => r + \u03b8 + \u03c6 }
>>>
def a = (1, 2, 3) match { case (r, \u03b8, \u03c6) => r + \u03b8 + \u03c6 }
```

**Comment by tanishiking** [comment]
This will be fixed as upgrading scalameta v4.0.0-M6
https://github.com/scalameta/scalameta/releases/tag/v4.0.0-M6
https://github.com/scalameta/scalameta/pull/1627
