### ISSUE TITLE
Enable trailingCommas = always by default?

### ISSUE THREAD

**Issue by olafurpg** [scalameta/scalafmt#1184]
The PR #1174 added a new option `trailingCommas` that allows to enforce that a trailing comma is always used when applicable

```scala
// before
foo(
  a,
  b
)
// after
foo(
  a,
  b,
)
```

The current default value is `preserve` which means the user chooses when to use trailing comma. I propose we make the default `trailingCommas = always` forcing people on 2.11 to explicitly mention `trailingCommas = never`.

**Comment by sjrd** [comment]
Paradoxically, IMO `trailingCommas = preserve` is the least useful one. This setting is highly dependent on whether one cross-compiles for 2.11 (2.10) or not:

* If cross-compiled: `trailingCommas = never` is simply the only viable setting
* If not cross-compiled: your coding style should either enforce it or forbid it, so `never` and `always` are the reasonable values for this setting

IMO, there is no scenario where `preserve` makes sense.

**Comment by dwijnand** [comment]
Or if your coding style is ambivalent on trailing comma usage.

**Comment by gabro** [comment]
I agree 'preserve' is not a good choice, if you explicitly make it. I've introduced the option to preserve retrocompatibility with the previous behavior, but I don't think it's a good default, precisely for the reasons @sjrd exposed.

**Comment by olafurpg** [comment]
I have changed my opinion and I think `always` is not a good default. Consider the scenario: you are a data scientist who just started Scala and are writing a Spark job, formatting with `always` will produce code that does not parse on 2.11. I think that running scalafmt should always be a safe operation so I think `preserve` is the best default.

**Comment by gabro** [comment]
In that case, I would go with never. It's both safe and opinionated.

**Comment by olafurpg** [comment]
But `never` would mean that code that strategically uses trailing commas only for vararg call sites will have that nicety removed, forever! 😨

**Comment by gabro** [comment]
Can you make an example of those vararg call sites? I don't think I know what you're talking about. Also, preserve stays as an option :)

**Comment by olafurpg** [comment]
```scala
libraryDependencies := List(
  "a" % "b",
  "a" % "b",
)
```

**Comment by olafurpg** [comment]
With preserve, trailing commas sort of naturally appear in places where you copy-paste arguments

**Comment by gabro** [comment]
except when it doesn't and the codebase is inconsistent. I'm not particularly invested into this, since I'll likely configure this manually on my projects, but if the goal is to be safe and opinionated, then never is a sensible default choice, that at least ensures consistency.

**Comment by olafurpg** [comment]
Scalafmt already leaves several choices to the user, for example where to insert blank lines and which infix operators to break at. I am personally fine between `preserve` and `never`, but I firmly believe `always` is a dangerous choice.

**Comment by gabro** [comment]
After some consideration, I agree. I've changed my vote from always to never :) Does the end date means the new release of scalafmt will happen on June 1st?

**Comment by dwijnand** [comment]
What about the idea of making the default dependant on the dialect?

**Comment by olafurpg** [comment]
The dialect should support trailing commas regardless of the setting imo
since even with "never" I would like scalafmt to remove trailing commas
instead of reporting a parse error.

**Comment by dwijnand** [comment]
My point was clearly a `trailingCommas = always` default makes no sense in a dialect where trailing commas aren't supported (Scala 2.11).

But, given the fact that Scala 2.11 is on it's way out, perhaps that shouldn't exclude `always` as a good default for the other dialects.

**Comment by dwijnand** [comment]
> `never` remove the trailing commas

is super-confusing.

Let's chat IRL. 😄

**Comment by dwijnand** [comment]
I wonder how many people, like me, implicitly assume that of course a default of `always` doesn't mean "yeah, scalafmt, go ahead and break my 2.11 code"...

**Comment by olafurpg** [comment]
Voting is closed! The results are

- 6 in favor of `preserve`
- 11 in favor of `always`
- 13 in favor of `never`

The new default will be `trailingCommas = never` 🎉 Thanks to all who voted.

**Comment by scarf005** [comment]
i know it's necroposting, but the poll result seems to have changed after 7 years:

![Image](https://github.com/user-attachments/assets/a2de904b-ed71-4540-965e-2201a0f496ff)
