### ISSUE TITLE
Add configuration to format multiline conditionals with dangling parenthesis

### ISSUE THREAD

**Issue by iantabolt** [scalameta/scalafmt#1190]
With `danglingParenthesis = true` I would expect conditionals to be formatted like this -

```scala
if (
  numTries > 0 &&
  oldestCompleteTimestampOpt.isDefined &&
  activityCache.nonEmpty
) {
```

instead of -

```scala
if (numTries > 0 &&
    oldestCompleteTimestampOpt.isDefined &&
    activityCache.nonEmpty) {
```

I'm thinking this should either fall under the `danglingParenthesis` config, or there should be some other config to get this output (maybe there already is?). Anyways, this is very low priority but any guidance would be greatly appreciated. Thank you always!

**Comment by olafurpg** [comment]
Hei, this is a good idea! I agree this seems consistent with danging parentheses, I had not thought of if condition parentheses that way before.

I'm open to include this under `danglingParentheses.ifCondition = true`. We can create a `case class DanglingParentheses(ifCondition: Boolean = false, argumentList: Boolean = true)` and have `danglingParentheses = true` default to `DanglingParentheses()`

I can't promise if/when I'll take a look at this myself, but in case someone is motivated to take a stab at it beware the changes require work in "Router.scala", which is likely the hairites part of scalafmt. I suspect the relevant line of code is in this case here https://github.com/scalameta/scalafmt/blob/4b198a1865f62c73e8930522274ecc323d203135/scalafmt-core/shared/src/main/scala/org/scalafmt/internal/Router.scala#L1079-L1098

**Comment by the-codinator** [comment]
+1
