### ISSUE TITLE
verticalMultiline configuration error

### ISSUE THREAD

**Issue by tudormaz** [scalameta/scalafmt#1193]
This template is a guideline, not a strict requirement.
- **Version**: 1.5.1
- **Integration**: IntelliJ
- **Configuration**:
```
# Align
align = none
align.openParenCallSite = false
align.openParenDefnSite = false
# Indent
continuationIndent.callSite = 2
continuationIndent.defnSite = 2
continuationIndent.extendSite = 4
# Newlines
newlines.alwaysBeforeTopLevelStatements = true
newlines.penalizeSingleSelectMultiArgList = false
# Vertical multiline
#verticalMultiline.atDefnSite = true
#verticalMultiline.arityThreshold = 3
verticalMultiline.excludeDanglingParens = []
```

## Steps

When I run scalafmt in IntelliJ IDEA like this:

```
Ctrl + Shift + L
```

## Problem

I get the following error message in IntelliJ
```scala
Scalafmt
Failed to read
/<path to project root folder>/.scalafmt.conf. Invalid fields: verticalMultiline
```

## Expectation

I would like the formatted output to look like this:
```scala
EXPECTED FORMATTING OUTPUT
```

## Notes

If I disable that verticalMultiline configuration, I no longer get that error message.
For these two parameters, I don't get any errors, but these are marked as deprecated. 
``` 
verticalMultilineAtDefinitionSite = false
verticalMultilineAtDefinitionSiteArityThreshold = 100
```
Their equivalent are not working for the same reason as above
```
verticalMultiline.atDefnSite = true
verticalMultiline.arityThreshold = 3
```

**Comment by olafurpg** [comment]
Thanks for reporting! The website documents the latest features merged into master while the latest released v1.5.1 does not contain the `verticalMultiline.*` setting. I admit this is confusing, sorry!

**Comment by tudormaz** [comment]
Any news on when a new release would be done with these latest changes?

**Comment by olafurpg** [comment]
I hope it'll be out in the next couple weeks :)

**Comment by tudormaz** [comment]
@olafurpg Hi again. I don't think I should open a new issue. If I should, please let me know. This is more of a question. Is there some configuration parameter which would force a new line after an annotation?
```scala
  @Provides
  @Named("dummy-property")
  def dummyPropertyFactory(
    @Named("dummy-property-values") dummyPropertyValue: List[String],
    @Named("null-value-format") nullValue: String,
    randomProvider: RandomProvider
  ): DummyPropertyValueFactory =
    new RandomValueFromListValuesFactory(
...
```
Displayed like this
```scala
  @Provides
  @Named("dummy-property")
  def dummyPropertyFactory(
    @Named("dummy-property-values") 
    dummyPropertyValue: List[String],
    @Named("null-value-format") 
    nullValue: String,
    randomProvider: RandomProvider
  ): DummyPropertyValueFactory =
    new RandomValueFromListValuesFactory(
...
```
The following don't apply (I think) to the annotations inside parameter lists.
```scala
optIn.selfAnnotationNewline = true
optIn.annotationNewlines = true
```

**Comment by olafurpg** [comment]
`optIn.annotationNewlines = true` means scalafmt will preserve a line break if it's before the field name so that if the input is
```scala
    @Named("dummy-property-values") 
    dummyPropertyValue: List[String],
```

then it's kept unchanged
