### ISSUE TITLE
scalafmt does not support leading comma

### ISSUE THREAD

**Issue by pshirshov** [scalameta/scalafmt#1195]
So, from all I can understand it's impossible have such a style with scalafmt at the moment:

```
Seq(
  1
  , 2
  , 3
)
```

Though many teams use/like leading commas. Is it something what can be supported?..

**Comment by olafurpg** [comment]
Thanks for reporting! On the website there is an easter egg in the "other" section https://scalameta.org/scalafmt/#Other

```
poorMansTrailingCommasInConfigStyle = true
```

The setting is not officially supported so issue reports will be closed unless there is an assigned person to fix them.
