### ISSUE TITLE
java.lang.NoSuchMethodError: fastparse.all$.CharsWhileIn$default$2()I

### ISSUE THREAD

**Issue by fommil** [scalameta/scalafmt#1200]
in 1.6.0-RC1 I'm getting this...

I figure this is a configuration / dependency version problem that can probably be eyeballed and creating a minimisation would be a lot of work for little benefit.

```
> fmt
[error] java.lang.NoSuchMethodError: fastparse.all$.CharsWhileIn$default$2()I
[error] 	at scala.meta.internal.tokenizers.XmlParser.<init>(XmlParser.scala:16)
[error] 	at scala.meta.internal.tokenizers.LegacyScanner.getXml(LegacyScanner.scala:990)
[error] 	at scala.meta.internal.tokenizers.LegacyScanner.fetchLT$1(LegacyScanner.scala:347)
[error] 	at scala.meta.internal.tokenizers.LegacyScanner.fetchToken(LegacyScanner.scala:355)
[error] 	at scala.meta.internal.tokenizers.LegacyScanner.nextToken(LegacyScanner.scala:241)
[error] 	at scala.meta.internal.tokenizers.LegacyScanner.foreach(LegacyScanner.scala:1068)
[error] 	at scala.meta.internal.tokenizers.ScalametaTokenizer.uncachedTokenize(ScalametaTokenizer.scala:153)
[error] 	at scala.meta.internal.tokenizers.ScalametaTokenizer.tokenize(ScalametaTokenizer.scala:31)
[error] 	at scala.meta.internal.tokenizers.ScalametaTokenizer$$anon$2.apply(ScalametaTokenizer.scala:287)
[error] 	at scala.meta.tokenizers.Api$XtensionTokenizeDialectInput.tokenize(Api.scala:21)
[error] 	at scala.meta.tokenizers.Api$XtensionTokenizeInputLike.tokenize(Api.scala:10)
[error] 	at scala.meta.internal.parsers.ScalametaParser.scannerTokens$lzycompute(ScalametaParser.scala:183)
[error] 	at scala.meta.internal.parsers.ScalametaParser.scannerTokens(ScalametaParser.scala:183)
[error] 	at scala.meta.internal.parsers.ScalametaParser.<init>(ScalametaParser.scala:140)
[error] 	at scala.meta.internal.parsers.ScalametaParser$$anon$189.apply(ScalametaParser.scala:3462)
[error] 	at scala.meta.parsers.Api$XtensionParseDialectInput.parse(Api.scala:21)
[error] 	at org.scalafmt.rewrite.Rewrite$.apply(Rewrite.scala:78)
[error] 	at org.scalafmt.Scalafmt$.format(Scalafmt.scala:50)
[error] 	at org.scalafmt.Scalafmt$.format(Scalafmt.scala:82)
[error] 	at org.scalafmt.sbt.ScalafmtPlugin$.$anonfun$withFormattedSources$2(ScalafmtPlugin.scala:73)
[error] 	at scala.collection.TraversableLike$WithFilter.$anonfun$map$2(TraversableLike.scala:739)
[error] 	at scala.collection.mutable.ResizableArray.foreach(ResizableArray.scala:59)
[error] 	at scala.collection.mutable.ResizableArray.foreach$(ResizableArray.scala:52)
[error] 	at scala.collection.mutable.ArrayBuffer.foreach(ArrayBuffer.scala:48)
[error] 	at scala.collection.TraversableLike$WithFilter.map(TraversableLike.scala:738)
[error] 	at org.scalafmt.sbt.ScalafmtPlugin$.withFormattedSources(ScalafmtPlugin.scala:70)
[error] 	at org.scalafmt.sbt.ScalafmtPlugin$.formatSources(ScalafmtPlugin.scala:105)
[error] 	at org.scalafmt.sbt.ScalafmtPlugin$.$anonfun$scalafmtConfigSettings$3(ScalafmtPlugin.scala:174)
[error] 	at org.scalafmt.sbt.ScalafmtPlugin$.$anonfun$scalafmtConfigSettings$3$adapted(ScalafmtPlugin.scala:165)
```

**Comment by olafurpg** [comment]
Thanks for reporting! Can you check what version of fastparse is in your sbt classpath? Scalameta and scalafmt are on fastparse v1.0.0, which is the latest release. If another plugin is bringing in fastparse v0.4.2 or older then this might be causing problems.

**Comment by fommil** [comment]
I don't know how to debug the dependency tree of the project itself :man_shrugging:  

This must be an sbt or coursier bug if it's not evicting old versions. I could try forcing the dependency version.

**Comment by olafurpg** [comment]
Looks like zinc needs to update it's ScalaPB dependency, in sbt/zinc
```
$ rg scalapb
project/plugins.sbt
6:libraryDependencies += "com.trueaccord.scalapb" %% "compilerplugin" % "0.6.0"
```

Reported in https://github.com/sbt/zinc/issues/546

**Comment by olafurpg** [comment]
Ticket moved to https://github.com/scalameta/scalameta/issues/1573 seems better to fix it on our front instead of waiting for sbt 2.

**Comment by tksfz** [comment]
Is there a short-term work-around for this?

**Comment by fommil** [comment]
I've been trying to convince @olafurpg to just shade or fork fastparse :stuck_out_tongue:

**Comment by olafurpg** [comment]
Forking won't happen. I'm not aware of any user land workaround except to
the the command line interface or IntelliJ plugin.

**Comment by tksfz** [comment]
I ended up just excluding the problematic file

**Comment by fommil** [comment]
or just downgrade your version to that used by sbt...

**Comment by olafurpg** [comment]
Besides the migration cost to downgrade, that would be a breaking change force all scalameta users on a ~2 year old dependency of fastparse.

**Comment by fommil** [comment]
scalameta users should all be scala tooling authors, who'll almost certainly have to deal with the sbt storm anyway...

**Comment by olafurpg** [comment]
I've been convinced that it is a good idea to shade sbt-scalafmt dependencies to avoid binary conflicts with sbt/zinc and other sbt plugins.

**Comment by olafurpg** [comment]
Just merged #1218 where I added a new module `scalafmt-big` that is a fat jar with shaded dependencies. The PR also removes the sbt-scalafmt plugin, which will live in a separate repo from now on. Will create scalameta/sbt-scalaft repo now.

**Comment by olafurpg** [comment]
sbt-scalafmt v1.6.0-RC3 is out with a shaded version of fastparse and scalameta. Please let me know if this issue has been resolved :)

**Comment by olafurpg** [comment]
Got a confirmation in https://github.com/scalameta/scalafmt/pull/1218#issuecomment-396667124 that this issue has been fixed. Please reopen if you encounter binary incompatibilities in sbt!
