### ISSUE TITLE
Make it easier to customize align setting

### ISSUE THREAD

**Issue by joan38** [scalameta/scalafmt#1202]
I think https://scalameta.org/scalafmt/#align.openParenDefnSite is broken in 1.6.0-RC1
- **Version**: 1.6.0-RC1
- **Configuration**:
```
maxColumn = 120
continuationIndent.defnSite = 2
assumeStandardLibraryStripMargin = true
align.openParenCallSite = true
align.openParenDefnSite = true
align = more
rewrite.rules = [SortImports, RedundantBraces, RedundantParens, SortModifiers]
```

## Steps

Given code like this:
```scala
case class AddAliasActionRequest(alias: String,
                                 index: String,
                                 routing: Option[String] = None,
                                 indexRouting: Option[String] = None,
                                 searchRouting: Option[String] = None,
                                 filter: Option[Query] = None)
```

When I run scalafmt like this:

```bash
scalafmt
```

## Problem

Scalafmt formats code like this:
```scala
case class AddAliasActionRequest(
  alias: String,
  index: String,
  routing: Option[String] = None,
  indexRouting: Option[String] = None,
  searchRouting: Option[String] = None,
  filter: Option[Query] = None
)
```

## Expectation

Stay the same since `align.openParenDefnSite = true` is provided.

**Comment by olafurpg** [comment]
Thanks for reporting! What happens if you remove `align=more`? This is a peculiarity of hocon, the json equivalent of your config looks like 

```json
{
  align: { openParenCallSite = true, openParenDefnSite = true},
  align: more
}
```

**Comment by olafurpg** [comment]
I have considered special casing the `align` key to detect when `align={none,some,more,most}` are used and apply those first and the apply the rest. This would work similarly to how `style = ...` currently works. Given it's not directly obvious how to get the v1.5.1 config in v1.6.0-RC1 I think this justifies the making this easier. WDYT?

**Comment by joan38** [comment]
So I have tried:
```
align = more
align.openParenCallSite = true
align.openParenDefnSite = true
```
and it resolve the issue but now we loose the `align = more` feature.

To me it sounds like a conflict in the hocon config loading.
Should the `align = {none,some,more,most}` be under another key? Something like:
```
align.vertically = more
align.openParenCallSite = true
align.openParenDefnSite = true
```

**Comment by olafurpg** [comment]
I see two actionable ways to address this

- Change `align = more` to have
```
align.openParenCallSite = true
align.openParenDefnSite = true
```

- customize config reading of `align` so that it behaves the same way as `style`, `align={more,some,..}` is read first and the rest of the settings are applied on top.

The second option is tempting but I'd like to keep the semantics of the config reading JSON compatible since I'd like to support .scalafmt.json soon.

Will need to think about this more 🤔

**Comment by joan38** [comment]
The current situation is already not JSON compatible right?
For example the following is not JSON ok since we have 2 key on the same name:
```
{
  align: { openParenCallSite = true, openParenDefnSite = true},
  align: more
}
```

Another is to breakdown `align` like `rewrite.rules = []`:
```
align = [caseArrows, assignment, extends, parenCallSite, parenDefnSite, openParenCallSite, openParenDefnSite]
```
That makes it consistent with the rest, JSON compatible and customisable.

**Comment by olafurpg** [comment]
Related issue #1205, seems `align` is confusing more people

That is an interesting proposal @joan38 it sort of already works that way today with `align.tokens = [caseArrow]`

**Comment by joan38** [comment]
So maybe we can merge all of those settings in a unique way like I proposed or `align.token`?

**Comment by olafurpg** [comment]
Opened #1215 making it easier to set `align.tokens` by supporting `align.tokens = more`. The current behavior will continue unchanged following regular HOCON/JSON semantics. That is,

```
align = more
align.openParen = true
```
is equivalent to

```
align.openParen = true
```

**Comment by olafurpg** [comment]
The PR updates the docs to show configuration examples for all `align={some,none,more,most}`.

**Comment by olafurpg** [comment]
I think it would be better to support `align.baseTokens = none | some | more | most` to free up `align.tokens` for custom tokens

**Comment by olafurpg** [comment]
Following question in https://gitter.im/scalameta/scalafmt?at=5b233f8c32618e705ebc1502

**Comment by kitbellew** [comment]
i will close this, because `align.preset` is now available and will allow specifying both `align.preset = more` and `align.openParenCallSite = true`.
