### ISSUE TITLE
Config loader methods removed in 1.6.0-RC1

### ISSUE THREAD

**Issue by nedtwigg** [scalameta/scalafmt#1204]
- **Version**: 1.6.0-RC1
- **Integration**: https://github.com/diffplug/spotless/blob/c346971673336d4256b1ae8837701b0ff6d809ab/lib/src/main/java/com/diffplug/spotless/scala/ScalaFmtStep.java#L98-L115

## Problem

Up until `0.6.8`, you could load configuration with `org.scalafmt.config.Config::fromHocon`.  From then until `1.6.0-rc1`, you could use `org.scalafmt.config.Config::fromHoconString`.  It seems these methods have been removed in `1.6.0-rc1`, which causes breakage in downstream projects:

https://github.com/diffplug/spotless/issues/252

## Expectation

The transition from `1.5` to `1.6` won't have breaking API changes.

## Workaround

We can find the new method names, and use those.  Not a big deal :)

**Comment by olafurpg** [comment]
Hei, thanks for reporting and thanks for spotless :) It's a great project.

The library compatibility story is that only `org.scalafmt.Scalafmt` guarantees binary and source compatibility between releases. You can use the following method instead
https://github.com/scalameta/scalafmt/blob/645e72b71974ce0c42e9a3b957fbbb75ada0045e/scalafmt-core/shared/src/main/scala/org/scalafmt/Scalafmt.scala#L85

The website contains examples how to load configuration this API https://scalameta.org/scalafmt/#Standalonelibrary

I'm sorry for the change, I was not aware this method was being used.

**Comment by olafurpg** [comment]
FYI @nedtwigg I opened #1212 to add back the `fromHoconString(String,Option)` overload since it was being used by another integration (#1206). However, I am committed to keep the API s in `org.scalafmt.Scalafmt` stable so I recommend using that instead. I'm happy to add more methods there if you are missing functionality from the API.

**Comment by nedtwigg** [comment]
Dunno if or when migating to `org.scalafmt.Scalafmt` will make it to the top of one of our contributor's todo lists, but I'll be sure to leave it open.  Thanks for fixing us in the meantime 👍

**Comment by olafurpg** [comment]
That's totally fair, I'll be sure to keep the old method around 😉

**Comment by olafurpg** [comment]
FYI v1.6.0-RC2 is out https://github.com/scalameta/scalafmt/releases/tag/v1.6.0-RC2 Please let me know if that fixes the issue.

**Comment by nedtwigg** [comment]
@joan38 can you check that `1.6.0-RC2` fixes your problem?

**Comment by joan38** [comment]
I will do tomorrow when I have access to a laptop.
Thanks

**Comment by joan38** [comment]
It didn't work at the end. Not sure why.

**Comment by olafurpg** [comment]
@joan38 what is the error? I don't see what the problem is in the linked Spotless PR 🤔
