### ISSUE TITLE
NoSuchMethodError running release candidate

### ISSUE THREAD

**Issue by aninhumer** [scalameta/scalafmt#1206]
Using versions:
- `sbt` version 0.13.16
- `neo-sbt-scalafmt` version 1.15 (coursier version `sbt-scalafmt-coursier`)
- `scalafmt` version 1.6.0-RC1 (set in `scalafmtVersion` sbt setting)

When I run scalafmt like this:
```bash
sbt scalafmt
```

Scalafmt fails with the following error message:
```
[error] (compile:scalafmt::scalafmtter) com.google.common.util.concurrent.ExecutionError: java.lang.NoSuchMethodError: org.scalafmt.config.Config$.fromHoconString(Ljava/lang/String;Lscala/Option;)Lmetaconfig/Configured;
```

Using scalafmt version 1.5.1 this does not occur.

**Comment by olafurpg** [comment]
Thanks for reporting! I admit I removed this method too eagerly, it was previously not well documented that only `org.scalafmt.Scalafmt`is protected by binary compatibility. Docs on integrating with scalafmt as a standalone library are here https://scalameta.org/scalafmt/#Standalonelibrary

Given this is the second ticket on the same issue (see https://github.com/scalameta/scalafmt/issues/1204) I think it's best to re-introduce the old method

**Comment by olafurpg** [comment]
Opened #1212 to fix this issue

**Comment by olafurpg** [comment]
Note that neo-scalafmt is using internal APIs which are subject to binary and source breaking changes between any release. Docs on using scalafmt as a library can be seen here https://scalameta.org/scalafmt/#Standalonelibrary
