### ISSUE TITLE
OsSpecific utils use JVM-specific code

### ISSUE THREAD

**Issue by laughedelic** [scalameta/scalafmt#1207]
- **Version**: 1.6.0-RC1
- **Integration**: using as a library

## Steps

Calling files filter from Scala.js:
```scala
config.project.matcher.matches(...)
```

Crashes with `Cannot read property 'toLowerCase' of null`.

## Problem

It calls to `OsSpecific.fixSeparatorsInPathPattern`:

https://github.com/scalameta/scalafmt/blob/295cee602b9bd6fb1fd6a2aa4aef5a808f272848/scalafmt-core/shared/src/main/scala/org/scalafmt/config/ProjectFiles.scala#L15-L16

Which is not platform independent, if I understand correctly:

https://github.com/scalameta/scalafmt/blob/645e72b71974ce0c42e9a3b957fbbb75ada0045e/scalafmt-core/shared/src/main/scala/org/scalafmt/util/OsSpecific.scala#L4-L7

But is still a shared code: `scalafmt/scalafmt-core/shared/src/main/scala/org/scalafmt/util/OsSpecific.scala`.

## Expectation

I guess this code should be in `scalafmt/scalafmt-core/jvm/src/` and the JS-specific code cannot use `System.getProperty`.

## Workaround

I just defined a matcher without the `OsSpecific.fixSeparatorsInPathPattern` method:

```scala
val matcher = FilterMatcher(
  config.project.includeFilters,
  config.project.excludeFilters,
)
```

**Comment by olafurpg** [comment]
Thanks for reporting! Would it be acceptable to have a fallback `.getPropertyOrDefault("os.name", "UNKNOWN")`? Same for `line.separator`, I'm OK falling back to `\n` and `/`

**Comment by sjrd** [comment]
For `line.separator` you should use [`System.lineSeparator`](https://docs.oracle.com/javase/8/docs/api/java/lang/System.html#lineSeparator--) instead anyway ;)

**Comment by olafurpg** [comment]
Opened https://github.com/scalameta/scalafmt/pull/1211 to fix this
