### ISSUE TITLE
Alignment for ADTs

### ISSUE THREAD

**Issue by AesaKamar** [scalameta/scalafmt#1210]
Given: 
```
sealed trait ADT
case object A extends ADT
case class B(b: Something) extends ADT
final case class C(c1: Something, c2: Something) extends ADT
final case class D(d1: Something, d2: Something, d3: Something, d4: Something) extends ADT
```

Produce: 
```
sealed trait ADT
case object      A                               extends ADT
case class       B(b: Something)                 extends ADT
final case class C(c1: Something, c2: Something) extends ADT
final case class D(
  d1: Something, 
  d2: Something, 
  d3: Something, 
  d4: Something)                                 extends ADT
```

Is there a way to modify my `scalafmt.conf` to achieve this?

**Comment by olafurpg** [comment]
Thanks for reporting! This is supported with `align=more`, see docs https://scalameta.org/scalafmt/#align=more. It will not work for the alignment of `A` with `B`/`C`/`D` or the `extends` in `D`. There is no plan to change that unless someone wants to write a new alignment engine.

**Comment by AesaKamar** [comment]
Thanks for the response. 

For reference, the specific key needed for alignment of the `extends` keyword was

```
align.tokens = [
  { code = "extends", owner = "Defn.(Class|Trait|Object)" }
]
```
