### ISSUE TITLE
doc links are 404

### ISSUE THREAD

**Issue by SethTisue** [scalameta/scalafmt#1219]
http://scalameta.org/scalafmt and http://scalafmt.org/ are both 404

**Comment by olafurpg** [comment]
Thanks for reporting! I can reproduce, it's weird since https://scalameta.org/scalafmt/index.html works fine 🤔 will need to look closer

**Comment by olafurpg** [comment]
I am no longer able to reproduce https://scalameta.org/scalafmt/
