### ISSUE TITLE
Wrong indentation of closing paren if there are newlines and parentheses between "case" and "=>"

### ISSUE THREAD

**Issue by tanishiking** [scalameta/scalafmt#1244]
This template is a guideline, not a strict requirement.
- **Version**: 1.6.0-RC4
- **Integration**: sbt
- **Configuration**:
```
# default
```

## Steps

Given code like this:
```scala
x match {
  case Foo(
      a,
      b
  ) =>
    ???
}
```

When I run scalafmt like this:

```bash
$ sbt scalafmt
```

## Problem

Scalafmt formats code like this:
```scala
x match {
  case Foo(
      a,
      b
      ) =>
    ???
}
```

## Expectation

I would like the formatted output to look like this:
```scala
x match {
  case Foo(
      a,
      b
  ) =>
    ???
}
```

## Workaround

There are no workarounds as far as I know.

**Comment by kitbellew** [comment]
@tanishiking how would you format the following:

- one split `extract` and one `if`
```
x match {
  case Foo(
      a,
      b
  )
      if condition =>
    ???
```

- two split `extract` and one `if`
```
x match {
  case Foo(
      a,
      b
  )
  infix Bar(
       c,
       d
  )
      if condition =>
    ???
```

- one split `extract`, one single-line `extract`
```
x match {
  case Foo(
      a,
      b
  )
  infix Bar(c, d) =>
    ???
  case _ => ...
```

I would actually go in the opposite direction and do something like this, for consistency:

```
x match {
  case Foo(
        a,
        b
      ) // aligns with if
      infix Bar(
        c,
        d
      ) // aligns with if
      if condition =>
    ???
```

or

```
x match {
  case Foo(
        a,
        b
    ) // aligns with body
    infix Bar(
        c,
        d
    ) // aligns with body
      if condition =>
    ???
```

**Comment by vito-c** [comment]
short conditions
```
x match {
  case Foo(
    a,
    b
  ) if condition => // aligns with case
    ???
}
```
super long conditions
```
x match {
  case Foo(
    a,
    b
  ) 
  if conditionxxxxxxxxxxxxxxxxxxxxxxxxx => //aligns with case
    ???
}
```

infixes
```
x match {
  case Foo(
    a,
    b
  ) // aligns with if && case
  infix Bar(
    c,
    d
  ) // aligns with if && case
  if condition =>
    ???
}
```

The long case statement is broken down into multiple lines with each new line starting at the same indention as the case. Then subsequent newlines with indention are only indented by two spaces from the case.

Then you can easily see everything included int he case

**Comment by kitbellew** [comment]
@vito-c

* it's inconsistent with the current approach of indenting `if` two spaces to the right of case body (after `=>`)
* what do we do if the `if` part also contains multiple lines, possibly with parens, infixes/continuations (which require their own indentation) etc?
* we don't break before an infix operation, so it would have to be tucked.

i am all for it (and have tried implementing it twice, before running into dilemmas) but before we make the change, we need to consider all possible cases. this very bug is about a case that wasn't considered before.

**Comment by vito-c** [comment]
> it's inconsistent with the current approach of indenting if two spaces to the right of case body (after =>)

Well not to bike shed too much but why is that the current approach? It seems inconsistent with everything else for example you wouldn't indent each new statement ... things are typically indented when they are a new block... the if statement is still part of the case so my argument is it should have the same indentation.

> what do we do if the if part also contains multiple lines, possibly with parens, infixes/continuations (which require their own indentation) etc?

Ideally you'd have parens around your statement
```scala
blah match {
  case x if ( .................................................................
    ......................
    .....................
  ) => true
  case _ => false
}
```

```scala
blah match {
  case x if .................................................................
    ......................
    .....................
  => true
  case _ => false
}
```

```scala
blah match {
  case x if .................................................................
    ......................
    ..................... => true
  case _ => false
}
```

then they should match normal indentation per my argument above.

> we don't break before an infix operation, so it would have to be tucked.

That's fine like this then?
```scala
x match {
  case Foo(
    a,
    b
  ) infix Bar(
    c,
    d
  ) // aligns with if && case
  if condition =>
    ???
}
```

> we need to consider all possible cases. this very bug is about a case that wasn't considered before. this very bug is about a case that wasn't considered before.

sweet let's work through it :)
