### ISSUE TITLE
Feature request: prefer parens over braces for lambdas

### ISSUE THREAD

**Issue by mpilquist** [scalameta/scalafmt#1246]
I'd love the ability to rewrite code like this:

```scala
List(1, 2, 3).map { _ * 2 }.filter { _ % 2 == 0 }
```
to:
```scala
List(1, 2, 3).map(_ * 2).filter(_ % 2 == 0)
```

Curlies would remain in cases where there are multiple statements or when pattern matching is used.

Apologies if this is already supported though I didn't see a way to configure it.

**Comment by matthughes** [comment]
I don't know the scalafmt code but it seems possible given that it can support this rule: https://scalameta.org/scalafmt/#PreferCurlyFors

**Comment by olafurpg** [comment]
This is a good idea! There is no rewrite rule for it at the moment but I suspect implementing it should not be too hard. If someone wants to take a stab at this, a somewhat related rule is https://github.com/scalameta/scalafmt/blob/fd0df2a8d6ce94815fef87ff8257eb5f5e8d63e6/scalafmt-core/shared/src/main/scala/org/scalafmt/rewrite/PreferCurlyFors.scala The rule only needs to replace the `{` and `}` tokens with `(` and `)`, scalafmt will take care of reformatting.

**Comment by kitbellew** [comment]
@mpilquist #1663 does this for one-line lambdas, and curlies are kept for multiline, as requested in #1027. would that be sufficient?

**Comment by mpilquist** [comment]
@kitbellew Awesome, that looks great!
