### ISSUE TITLE
Support formatting of multiline type parameters

### ISSUE THREAD

**Issue by Tvaroh** [scalameta/scalafmt#1249]
Can we support this type formatting:

```scala
class Foo[
  F[_] : Bar
       : Sync
       : ExecuteUnsafe,
  T
]
```

or

```scala
class Foo[
  F[_]
    : Bar
    : Sync
    : ExecuteUnsafe,
  T
]
```

or something similar to that, when you have multiline type parameters with potentially long context bounds list with each bound on a separate line for clarity.

**Comment by olafurpg** [comment]
Thanks for reporting! This should be doable, we could treat it similar to select chains. If someone wants to take a stab at this, a good place to start would be where context bounds are formatted
 https://github.com/scalameta/scalafmt/blob/a20d6d8a6cfe38fbcb25d8f54920de7ca844c311/scalafmt-core/shared/src/main/scala/org/scalafmt/internal/Router.scala#L856
and also how select chains are handled https://github.com/scalameta/scalafmt/blob/a20d6d8a6cfe38fbcb25d8f54920de7ca844c311/scalafmt-core/shared/src/main/scala/org/scalafmt/internal/Router.scala#L945
