### ISSUE TITLE
Preserve newlines in for comprehension generators and values

### ISSUE THREAD

**Issue by psttf** [scalameta/scalafmt#1256]
Since newlines are preserved after `=` in `val`s and `def`s it seems reasonable to do the same inside `for`s and preserve newlines after `<-` as well as `=`:

Original:

    for {
      myLongBooleanValue <- 
        some.very.very.very.very.very.very.long.option.map(_ => true)
      myResult = 
        if (myLongBooleanValue) compute_one_thing
        else compute_another_thing
    } yield myResult

Scalafmt:

    for {
      myLongBooleanValue <- some.very.very.very.very.very.very.long.option
        .map(_ => true)
      myResult = if (myLongBooleanValue) compute_one_thing
      else compute_another_thing
    } yield myResult

The original version seems more readable to me and It would be nice if such inputs were not reformatted.

Using scalafmt 1.6.0-RC3, `style = default`

**Comment by mt40** [comment]
Recently, I also came across a similar situation:
```scala
for {
  _ <- doSth(param1, param2, ..., paramN) // very long
}
```
(let say I cannot group the parameters any further)
and it would be awesome if Scalafmt can break it down to multiple lines:
```scala
for {
  _ <- doSth(param1, param2,...,
             paramM, ..., paramN)
}
```
