### ISSUE TITLE
Scalafmt brings old scalameta

### ISSUE THREAD

**Issue by jozic** [scalameta/scalafmt#1263]
- **Version**: 1.5.1
- **Integration**: sbt plugins

## Steps
Given an sbt project that has other plugins using scalameta of newer version (e.g. [sbt-doctest](https://github.com/tkawachi/sbt-doctest) uses scalameta 3.7.4) 

When I run scalafmt I get

```bash
java.lang.NoClassDefFoundError: scala/meta/inputs/Input
```

## Expectation

I would like both plugins to co-exist in piece in harmony.
I guess solution for now is to release new stable scalafmt with latest binary compatible scalameta

## Notes

See https://github.com/tkawachi/sbt-doctest/issues/120

**Comment by olafurpg** [comment]
Thanks for reporting! The latest v1.6.0-RC4 depends on the latest version of scalameta so you can try that release :)
