### ISSUE TITLE
Fix "multiline defaults" in configuration on the website

### ISSUE THREAD

**Issue by gabro** [scalameta/scalafmt#1268]
See https://github.com/scalameta/scalafmt/pull/1199/files/d53bce55fb049ad4674c0f2c1f721179f539bd0f#diff-76e731333fb756df3bff5ddb3b731c46R502

**Comment by kitbellew** [comment]
@gabro can you explain what you are looking for, please?

**Comment by gabro** [comment]
Honestly I can't remember, it was probably an issue with the `scala mdoc:defaults` modifier. It doesn't seem important, I'll close this

**Comment by poslegm** [comment]
I guess it's about

```      
scala mdoc:defaults

rewrite.redundantBraces.generalExpressions
rewrite.redundantBraces.methodBodies
rewrite.redundantBraces.includeUnitMethods
```

Documentation can't render multiple default settings in one block.

**Comment by gabro** [comment]
ah yes, that's it. We can re-open if it's still an issue today

**Comment by kitbellew** [comment]
Shouldn't it be in the repository which implements mdoc instead, or at least in addition to?

**Comment by gabro** [comment]
It's a custom modifier in this repository, here's the source  https://github.com/scalameta/scalafmt/blob/master/scalafmt-docs/src/main/scala/docs/DefaultsModifier.scala

**Comment by kitbellew** [comment]
ah, very interesting, who knew... thank you. I'll reopen.
