### ISSUE TITLE
Should be no space after the +- sign as variance annotations

### ISSUE THREAD

**Issue by tkrs** [scalameta/scalafmt#1280]
One space is inserted after the +- sign if the type parameter is a variance annotation with a underscore.

- **Version**: 1.5.1
- **Integration**: cli
- **Configuration**: default

## Steps

Given code like this:
```scala
object A {
  type T1[X]
  type T2[+X]
  type T3[-X]
  type T4[_]
  type T5[+_]
  type T6[-_]
}
```

When I run scalafmt like this:

```bash
λ scalafmt A.scala
```

## Problem

Scalafmt formats code like this:
```scala
object A {
  type T1[X]
  type T2[+X]
  type T3[-X]
  type T4[_]
  type T5[+ _]
  type T6[- _]
}
```

## Expectation

I would like the formatted output to look like this:
```scala
object A {
  type T1[X]
  type T2[+X]
  type T3[-X]
  type T4[_]
  type T5[+_]
  type T6[-_]
}
```

## Workaround

I did't find it...

**Comment by olafurpg** [comment]
Thanks for reporting! I agree the expected output should not insert a space before the underscore.
