### ISSUE TITLE
Align regression

### ISSUE THREAD

**Issue by ArturGajowy** [scalameta/scalafmt#1289]
- **Version**: 1.6.0-RC4
- **Integration**: sbt
- **Configuration**:
```
project {
  git = true
  excludeFilters = ["target/", "build.sbt"]
}
style = default
rewrite.rules = [PreferCurlyFors, RedundantBraces, SortImports]
maxColumn = 98
align = most
maxColumn = 100
```

## Steps

Given code like this:
```scala

    developers := List(
      Developer(
        id    = "guardbotmk3",
        name  = "Kyle Butt",
        email = "kyle@pyrofex.net",
        url   = url("https://www.pyrofex.net")
      ),
      Developer(
        id    = "ys-pyrofex",
        name  = "Yaraslau Levashkevich",
        email = "yaraslau@pyrofex.net",
        url   = url("https://www.pyrofex.net")
      ),
      Developer(
        id    = "KentShikama",
        name  = "Kent Shikama",
        email = "kent@kentshikama.com",
        url   = url("https://www.rchain.coop")
      ),
      Developer(
        id    = "henrytill",
        name  = "Henry Till",
        email = "henrytill@gmail.com",
        url   = url("https://www.pyrofex.net")
      )
    )
```

When I run scalafmt like this:

```bash
sbt scalafmtSbt
```

## Problem

Scalafmt formats code like this:
```scala
    developers := List(
      Developer(
        id = "guardbotmk3",
        name = "Kyle Butt",
        email = "kyle@pyrofex.net",
        url = url("https://www.pyrofex.net")
      ),
      Developer(
        id = "ys-pyrofex",
        name = "Yaraslau Levashkevich",
        email = "yaraslau@pyrofex.net",
        url = url("https://www.pyrofex.net")
      ),
      Developer(
        id = "KentShikama",
        name = "Kent Shikama",
        email = "kent@kentshikama.com",
        url = url("https://www.rchain.coop")
      ),
      Developer(
        id = "henrytill",
        name = "Henry Till",
        email = "henrytill@gmail.com",
        url = url("https://www.pyrofex.net")
      )
    )
```

## Expectation

I would like the formatted output to look like the "given" code above.

## Workaround

None found/tried.

## Notes

See: https://github.com/rchain/rchain/pull/1549/files#diff-fdc3abdfd754eeb24090dbd90aeec2ceR372

**Comment by ArturGajowy** [comment]
TBH I'm not sure if that's a regression - those files haven't been formatted for a while. My expectations about how that should be formatted are as above though :)

**Comment by olafurpg** [comment]
Thanks for reporting! I don't think this is a regression because Scalafmt has never aligned named arguments, related tickets

- https://github.com/scalameta/scalafmt/issues/289
- https://github.com/scalameta/scalafmt/issues/850
- https://github.com/scalameta/scalafmt/issues/914

Please reopen if you would like to take a stab at this. Further improvements to vertical alignment is not on the roadmap unless somebody volunteers to work on it.

**Comment by leobenkel** [comment]
Any plans to fix the vertical alignement for `=` for explicit argument names ?
Just curious since it has been two years :)
