### ISSUE TITLE
Lambda functions misaligning braces

### ISSUE THREAD

**Issue by howardjohn** [scalameta/scalafmt#1290]
This template is a guideline, not a strict requirement.
- **Version**: 1.5.1
- **Integration**: CLI
- **Configuration**: default

## Steps

Given code like this:
```bash
echo "object Test {
  val test =
    (x: String) =>
      Option {
        "a"
    }
}" | scalafmt --stdin -c /dev/null
```

Result:
```scala
object Test {
  val test =
    (x: String) =>
      Option {
        "a"
    }
}
```

## Problem

The closing brace for the `Option` is not aligned with its opening brace correctly.
## Expectation

I would like the formatted output to look like this:
```scala
object Test {
  val test =
    (x: String) =>
      Option {
        "a"
      }
}
```

**Comment by olafurpg** [comment]
Thanks for reporting! This is fixed in the latest 1.6 release candidate 
```
echo "object Test {
  val test =
    (x: String) =>
      Option {
        "a"
    }
}" | coursier launch com.geirsson:scalafmt-cli_2.12:1.6.0-RC4 --main org.scalafmt.cli.Cli -- --stdin
object Test {
  val test =
    (x: String) =>
      Option {
        a
      }
}
```

The 1.6 release still has a couple regressions so 1.5.1 remains the current stable version.
