### ISSUE TITLE
Add `--test-and-format` option to return non-zero on formatted files present

### ISSUE THREAD

**Issue by ArturGajowy** [scalameta/scalafmt#1291]
`scalafmt file1 file2 file3` will return 0 when it successfully formats all of the files, no matter if any of them changed or not.

It would be useful to have a flag that would modify the exit status so that it's 0 only when no files were changed.

So far, I have to first `scalafmt --test` and then `scalafmt` if the test failed.

**Comment by olafurpg** [comment]
Thanks for reporting! I agree this would be a nice feature, contributions are welcome 👍

**Comment by kitbellew** [comment]
@ArturGajowy @olafurpg is this similar to my early desire for #928?

**Comment by olafurpg** [comment]
Yes. Sounds similar. I still think it’s a good idea.

**Comment by kitbellew** [comment]
> Yes. Sounds similar. I still think it’s a good idea.

so did i :) we still run scalafmt twice in our build...
