### ISSUE TITLE
continuationIndent.withSite configuration option

### ISSUE THREAD

**Issue by evis** [scalameta/scalafmt#1298]
- **Version**: 1.5.1
- **Integration**: mvn plugin
- **Configuration**: default

## Steps

Given code like this:
```scala
class TestClass extends SomeClass with SomeTraitOne with SomeTraitTwo with SomeVeryLongTrait with OneMoreTrait
```

When I run scalafmt like this:

```bash
mvn mvn-scalafmt_2.11:format
```

## Problem

Scalafmt formats code like this:
```scala
class TestClass
    extends SomeClass
    with SomeTraitOne
    with SomeTraitTwo
    with SomeVeryLongTrait
    with OneMoreTrait
```

## Expectation

I would like to have some new configuration option, which could help to align `extends` and `with` differently. For example, with such configuration:
```
continuationIndent.extendSite = 2
continuationIndent.withSite = 4
```

the formatted output should look like this:

```scala
class TestClass
  extends SomeClass
    with SomeTraitOne
    with SomeTraitTwo
    with SomeVeryLongTrait
    with OneMoreTrait
```

**Comment by olafurpg** [comment]
Thanks for reporting!  I'm generally on the fence for new configuration options but this one sounds reasonable to me, contributions are welcome 👍
