### ISSUE TITLE
Formatting of new object creation with mixins

### ISSUE THREAD

**Issue by evis** [scalameta/scalafmt#1300]
- **Version**: 1.5.1
- **Integration**: mvn plugin
- **Configuration**:
```
maxColumn = 39
```

## Steps

Given code like this:
```scala
new A with B with C with D with E with F
```

When I run scalafmt like this:

```bash
mvn mvn-scalafmt_2.11:format
```

## Problem

Scalafmt formats code like this:
```scala
new A with B with C with D with E
with F
```

## Expectation

I would like the formatted output to look like this:
```scala
new A
  with B
  with C
  with D
  with E
  with F
```

Basically, the same way, as for class definition.

**Comment by olafurpg** [comment]
Thanks for reporting! I can confirm this is a bug, I've encountered it myself.

**Comment by poslegm** [comment]
@evis please try version 2.1.0. It includes fix for this issue.
