### ISSUE TITLE
Hard to add new value to list while preserving defaults in config

### ISSUE THREAD

**Issue by Katrix** [scalameta/scalafmt#1307]
Unsure if this has been brought it up before, but creating this issue as I didn't find any other issue for this,
- **Version**: 1.5.1
- **Integration**: CLI

Currently, it's kind of hard to add a value to one of the lists in the config while preserving the default values. For example, I wanted to add `:=` as a token to align on in one of my projects (I'm using the more align setting for context).

I would think this would do that
```
align.tokens += {code = ":=", owner = "Term.ApplyInfix"}
```
However, what this does is make `:=` the only token that aligning is performed on. If I want to preserve the default aligning, I have to go hunt in the code for the default for my case and set that in the config.

```
align.tokens = [
  {code = "extends", owner = "Defn.(Class|Trait|Object)"}
  {code = "//", owner = ".*"}
  {code = "{", owner = "Template"}
  {code = "}", owner = "Template"}
  {code = "%", owner = "Term.ApplyInfix"}
  {code = "%%", owner = "Term.ApplyInfix"}
  {code = "%%%", owner = "Term.ApplyInfix"}
  {code = "⇒", owner = "Case"}
  {code = "<-", owner = "Enumerator.Generator"}
  {code = "←", owner = "Enumerator.Generator"}
  {code = "->", owner = "Term.ApplyInfix"}
  {code = "→", owner = "Term.ApplyInfix"}
  {code = "=", owner = "(Enumerator.Val|Defn.(Va(l|r)|Def|Type))"}
  //My custom stuff
  {code = ":=", owner = "Term.ApplyInfix"}
]
```

Seeing as this AFAIK does not follow behavior I would expect from HOCON, it would be neat if this could be fixed.

**Comment by olafurpg** [comment]
Thanks for reporting! Have you tried?
```
align.tokens.add = {code = ":=", owner = "Term.ApplyInfix"}
```

The `+=` HOCON operator does not work since the base configuration is defined in Scala instead of `application.conf`.

**Comment by Katrix** [comment]
Nope, had no idea something like add existed. The docs doesn't mention it at all. Will try when I get home.

**Comment by Katrix** [comment]
Sorry for taking so long with this. So yes, 
```
align.tokens.add = [{code = ":=", owner = "Term.ApplyInfix"}]
```
 does work. Thanks. Would be neat if it could be mentioned in the docs though.

**Comment by olafurpg** [comment]
Glad it worked! Customization of alignment tokens is fragile so it's intentionally not documented on the website. I recommend you consider not using `align.tokens`.
