### ISSUE TITLE
Failed to load scalafmt config

### ISSUE THREAD

**Issue by asarkar** [scalameta/scalafmt#1312]
- **Version**: 1.5.1
- **Integration**: IntelliJ
- **Configuration**:
```
// https://scalameta.org/scalafmt/docs/configuration.html
maxColumn = 120
docstrings = JavaDoc
align = none
rewrite.rules = [ExpandImportSelectors, SortImports, SortModifiers, PreferCurlyFors, RedundantBraces, RedundantParens]
continuationIndent.defnSite = 2
verticalMultiline {
  atDefnSite = true
  arityThreshold = 2
  newlineAfterOpenParen = true
  newlineBeforeImplicitKW = true
}
project.git = true
```

## Steps
Given code like shown in the screenshot, when I save the file, I get an error as shown in the screenshot.

## Problem
Error

## Expectation
Well, it should work, shouldn't it?

## Workaround
None

![scalafmt](https://user-images.githubusercontent.com/1302775/48254961-39568e80-e3c0-11e8-93a0-c5d00b23ea99.jpg)

**Comment by olafurpg** [comment]
Thanks for reporting! `verticalMultiline` was added in v1.6.0 and intellij is on v1.5.1. Can you please open a ticket in IntelliJ Scala asking to include the scalafmt error from parsing the configuration?

**Comment by olafurpg** [comment]
One workaround is to use the scalafmt IntelliJ plugin from the "nightly" channel https://plugins.jetbrains.com/plugin/8236-scalafmt

**Comment by asarkar** [comment]
https://youtrack.jetbrains.com/issue/KT-28114

**Comment by asarkar** [comment]
@olafurpg 
> Scalafmt v1.5.1 comes pre-installed with the IntelliJ Scala plugin

The documentation makes it sound like scalafmt comes with whatever version of plugin is compatible, and works out of the box. It is misleading; since you _do_ depend on IntelliJ plugin version, I suggest updating the docs to clearly state the compatibility requirement.

**Comment by olafurpg** [comment]
Thanks for the suggestion @asarkar maybe it's best to not recommend the built-in scalafmt support in intellij since it's unclear when it will be able to support multiple scalafmt versions 🤔

**Comment by asarkar** [comment]
I upgraded to the nightly plugin and it didn't solve the problem. When you say "it's best to not recommend", how do you suggest using scalafmt then? Only from command line? (sbt)

**Comment by olafurpg** [comment]
> I upgraded to the nightly plugin and it didn't solve the problem.

What is the error? The Scalafmt IntelliJ plugin has a different shortcut to format than the built-in support. You should disable the built-in support to avoid the "failed to load scalafmt config" error.

> how do you suggest using scalafmt then?

The Scalafmt IntelliJ plugin via `Cmd + Shift + L` (on macOS).

**Comment by asarkar** [comment]
Same as before, except now it shows that vertical newline isn't supported. I'm new to scalafmt, so it's not clear to me what you mean by "Scalafmt IntelliJ plugin". The only Scala related plugin I've got installed is the Scala plugin; I don't have any scalafmt plugin installed, hence, I don't know how I'd disable something I don't have.

**Comment by olafurpg** [comment]
Have you followed the instructions here https://scalameta.org/scalafmt/docs/installation.html#intellij ?

**Comment by olafurpg** [comment]
> upgraded to the nightly plugin

This referred to the  nightly scalafmt plugin not (not intellij-scala plugin), see https://plugins.jetbrains.com/plugin/8236-scalafmt

**Comment by asarkar** [comment]
https://scalameta.org/scalafmt/docs/assets/img/intellij-install.png
Yup, that pop up showed up, and I clicked on "Use scalafmt formatter". I didn't install anything else, because the doc made it sound like I didn't need it.
> Scalafmt v1.5.1 comes pre-installed with the IntelliJ Scala plugin.

**Comment by asarkar** [comment]
I think I figured out the disconnect. The scalafmt plugin is different from the Scala plugin. I'm not even sure why you mentioned the Scala plugin in the docs, because anyone working with Scala in IntelliJ must have it installed anyway. That's what confused me; you'll have to admit there's not much difference between "Scala plugin" and "scalafmt" plugin to a newbie, especially if the docs claim the plugin comes bundled with scalafmt.

**Comment by olafurpg** [comment]
I understand the confusion. The built-in scalafmt support in intellij still needs more work I'm afraid to recommend it like we do on the website. Thanks for being persistent and sharing your thoughts!

**Comment by olafurpg** [comment]
The new IntelliJ installation instructions are live https://scalameta.org/scalafmt/docs/installation.html
