### ISSUE TITLE
Support option newlines.eof

### ISSUE THREAD

**Issue by tdauth** [scalameta/scalafmt#1317]
I am not sure why this was added by default in #1073 and #1054 but with scalastyle I could configure it to warn me if there is one with `org.scalastyle.file.NoNewLineAtEofChecker`.
Is it required by Scala to have a new line at the EOF?

**Comment by olafurpg** [comment]
Thanks for reporting! I opened #1333 which fixes one case where scalafmt sometimes didn't insert newlines at the end of a file. There is no option to not insert newlines at the end of a file, many unix tools require files to have newlines at the end of the file, although the scala compiler doesn't require it.
