### ISSUE TITLE
Editor vs Build tool version syncing

### ISSUE THREAD

**Issue by ShaneDelmore** [scalameta/scalafmt#1318]
It would be helpful if the editor integration and the build tool integration could be synced on the version of scalafmt they use.  In my use case for example pants has a version of scalafmt, and IntelliJ has another version.  I try to keep them in sync, but they are on different release schedules and go out of sync sometimes.

Any solution works for me but one idea I had was to add a config option specifying the invocation syntax to use for scalafmt.  For example 
```
scalafmtExecTemplate = "./pants scalafmt {{fileOrDir}}
```
or 
```
scalafmtExecTemplate = "./bin/scalafmt {{fileOrDir}}
```

**Comment by olafurpg** [comment]
Thanks for reporting! I agree this is a problem.

In Metals we opted to launch the scalafmt version based on the `version=1.5.1` setting in `.scalafmt.conf`. The IntelliJ plugin and cli integration don't respect this setting, but they could for example refuse to format or report a warning if the version number in `.scalafmt.conf` is a mismatch with the running scalafmt instance.

**Comment by olafurpg** [comment]
I opened #1337 that introduces a new `scalafmt-dynamic` module which has a stable binary API and automatically fetches the Scalafmt version matching the 'version' setting in `.scalafmt.conf`. The hard work remains for build tool integrations like sbt/pants/intellij to this module, I will make sure at least sbt-scalafmt, IntelliJ Scalafmt and Metals use it.

**Comment by tanishiking** [comment]
Introducing scalafmt-dynamic (that enable us to switch running scalafmt version using `setting` field of `.scalafmt.conf`) to each integration is working on progress. 
Currently, the following integrations have introduced scalafmt-dynamic.

- [x] sbt-scalafmt (2.0.0-RC5 ~)
  - https://github.com/scalameta/sbt-scalafmt/pull/20
- [x] scalafmt-cli (2.0.0-RC5 ~)
  - https://github.com/scalameta/scalafmt/pull/1366
- [x] intellij-scalafmt (2.0.0-RC5 ~)
  - https://github.com/scalameta/scalafmt/pull/1368
- [x] metals (0.4.0 ~)
  - https://scalameta.org/metals/blog/2019/01/24/tin.html
  - https://github.com/scalameta/metals/pull/429
- [x] gradle-scalafmt
  - https://github.com/alenkacz/gradle-scalafmt/pull/25
- [ ] and more ...?

**Comment by ches** [comment]
Shall this issue be closed? It looks like everything remotely in the scope of scalafmt maintainers has been covered now (and some beyond!).

> - [ ] and more …?

Fingers crossed for the IntelliJ Scala plugin's built-in integration to follow suit soon.

Thank you @tanishiking and @olafurpg for the work on this. ❤️

**Comment by tanishiking** [comment]
As @ches said, most of the scalafmt integrations have been already covered!
Now we close this issue:rocket:
