### ISSUE TITLE
How to rewrite just one file?

### ISSUE THREAD

**Issue by leobenkel** [scalameta/scalafmt#1327]
How to rewrite just one file ?

**Comment by olafurpg** [comment]
Can you please include more information?

**Comment by leobenkel** [comment]
Something like `sbt scalaFmt ./path/to/my/file.scala`

**Comment by olafurpg** [comment]
You mean the `scalafmtOnly` task? https://scalameta.org/scalafmt/docs/installation.html#task-keys

**Comment by leobenkel** [comment]
oh thanks ! That might be it ! I missed this one !
