### ISSUE TITLE
Wired alignment when chain contains comment / no parenthesis call / with parenthesis call

### ISSUE THREAD

**Issue by lxohi** [scalameta/scalafmt#1334]
- **Version**: 1.5.1 (scalafmt plugin version)
- **Integration**: IntelliJ
- **Configuration**:
```
maxColumn = 150
docstrings = JavaDoc
align = none
```

## Steps

Given code like this:
```scala
class Foo {
  val vv = v.aaa //
    .aaa
    .bbb()
}
```

When I run scalafmt like this:
```bash
<press Reformat with scalafmt key>
```

## Problem

Scalafmt formats code like this:
```scala
class Foo {
  val vv = v.aaa //
  .aaa
    .bbb()
}
```

## Expectation

I would like the formatted output to look like this:
```scala
class Foo {
  val vv = v.aaa //
    .aaa
    .bbb()
}
```
Or like this:
```scala
class Foo {
  val vv = v
    .aaa //
    .aaa
    .bbb()
}
```

## Notes

I found a config key `includeNoParensInSelectChains` in the [document](https://scalameta.org/scalafmt/docs/configuration.html#includenoparensinselectchains) may related with this issue.
But after I added this key to my conf, intellij IDEA reports:
```
12:33	Scalafmt
			Failed to read /................/.scalafmt.conf. 
			Invalid fields: includeNoParensInSelectChains
```
Meanwhile the `Show original` / `Show formatted` button in the [document](https://scalameta.org/scalafmt/docs/configuration.html#includenoparensinselectchains) for this config key was not functional either at this time.

**Comment by andwxh** [comment]
I've tried night version 1.6.0-RC4. This behavior was the same.

**Comment by TaranTheMonk** [comment]
this problem also happened from my side, if my .scalafmt.conf file has `includeNoParensInSelectChains=True`, the IDE(intellij) will failed on reading it.

**Comment by kitbellew** [comment]
@lxohi this was fixed when using `newlines.source` (you can use `keep` although i'd suggest trying one of the other two modes). i do not think i will fix it for the classic mode, the select-chain rule in that case is too complex.
