### ISSUE TITLE
sbt scalafmt only formats the compile sources

### ISSUE THREAD

**Issue by cb372** [scalameta/scalafmt#1335]
- **Version**: 1.5.1
- **Integration**: sbt

Maybe I'm being slow, but I only just noticed that `scalafmt` and `scalafmtCheck` only act upon the compile sources (i.e. `src/main/scala`). To format your test sources you have to run `test:scalafmt`.

I assumed that `scalafmt` would aggregate both `compile:scalafmt` and `test:scalafmt`. I'm not sure whether that's a reasonable assumption, but I bet it's caught other people out as well.

Should the default behaviour be changed to that? Or should the current behaviour be kept and better documented?

For now I've worked around it by writing my own wrapper tasks:

```scala
val scalafmtAll =
  taskKey[Unit]("format the compile sources, test sources and integration test sources")
val scalafmtCheckAll = taskKey[Unit](
  "check the formatting of the compile sources, test sources and integration test sources")
scalafmtAll := {
  (Compile / scalafmt).value
  (Test / scalafmt).value
  (IntegrationTest / scalafmt).value
}
scalafmtCheckAll := {
  (Compile / scalafmtCheck).value
  (Test / scalafmtCheck).value
  (IntegrationTest / scalafmtCheck).value
}

```

**Comment by olafurpg** [comment]
Thanks for reporting! I think the `scalafmt` task formatted both test and main sources to begin with but this apparently goes against sbt idioms so it got changed to the current behavior. The same story happened for sbt-scalafix, you need to run `test:scalafix` to fix test sources.

The current behavior should stay but it can probably be better documented. Here's what it currently says https://scalameta.org/scalafmt/docs/installation.html#sbt

<img width="609" alt="screenshot 2019-01-04 at 20 06 57" src="https://user-images.githubusercontent.com/1408093/50705827-5627df00-105c-11e9-80a7-fd7dcc425d7c.png">

Any ideas to improve it? In scalafix it's highlighted with a custom header https://scalacenter.github.io/scalafix/docs/users/installation.html#main-and-test-sources

**Comment by cb372** [comment]
In my workaround I hardcoded the three configurations I cared about, but I wonder if we could add a `scalafmtAll` task to the plugin that iterates through the project's configurations and executes all the `scalafmt` tasks it can find?

I've no idea how to do that with sbt, or whether it's even possible, but I'll do a bit of investigation.

**Comment by dwijnand** [comment]
Try experimenting with `.all` and `ScopeFilter`, specifically `inAnyConfiguration`:

https://www.scala-sbt.org/1.x/docs/Tasks.html#Getting+values+from+multiple+scopes

> I think the `scalafmt` task formatted both test and main sources to begin with but this apparently goes against sbt idioms so it got changed to the current behavior. The same story happened for sbt-scalafix, you need to run `test:scalafix` to fix test sources.

If you do remember why, I'd love to hear more about it, because I think you were onto something by having `scalafmt`/`scalafix` do "configuration aggregation" instead of just delegating to `Compile/scalafmt`/`Compile/scalafix`.  I can more easily believe it goes against some sbt bug, rather an some sbt idiom.

**Comment by cb372** [comment]
@dwijnand Thanks for the tip, and for reminding me I'd opened this issue. It was actually really simple once I'd RTFM.
