### ISSUE TITLE
Update metadata in IntelliJ plugin info page

### ISSUE THREAD

**Issue by dwijnand** [scalameta/scalafmt#1349]
The metadata in https://plugins.jetbrains.com/plugin/8236-scalafmt (like the link to the source code) still points to https://github.com/olafurpg/scalafmt.

**Comment by poslegm** [comment]
<img width="255" alt="Screen Shot 2019-11-08 at 8 25 36 PM" src="https://user-images.githubusercontent.com/4687050/68497598-fd216c80-0265-11ea-8e3e-d786ac19b5e5.png">

Link now points to the actual repo.
