### ISSUE TITLE
Conflict between new line before / after implicit and verticalMultilineAtDefinitionSite?

### ISSUE THREAD

**Issue by alexarchambault** [scalameta/scalafmt#1362]
- **Version**: 2.0.0-RC4
- **Integration**: CLI
- **Configuration**:
```
maxColumn = 80
continuationIndent.callSite = 2
continuationIndent.defnSite = 2
align.openParenCallSite = false
align.openParenDefnSite = false
danglingParentheses = true

verticalMultiline.newlineBeforeImplicitKW = false
verticalMultiline.newlineAfterImplicitKW = true
newlines.afterImplicitKWInVerticalMultiline = true

verticalMultilineAtDefinitionSite = true
```

## Steps

Given code like this:
```scala
case class Foo(
  a: Int,
  b: Boolean,
  c: String,
  d: String,
  e: String,
  f: String,
  g: String
) {
  def run[F[_]](
    fetch: ResolutionProcess.Fetch[F],
    maxIterations: Int = ResolutionProcess.defaultMaxIterations
  )(implicit
    F: Monad[F]
  ): F[Resolution] =
    ???
}
```

## Problem

Scalafmt formats code like this:
```scala
case class Foo(
  a: Int,
  b: Boolean,
  c: String,
  d: String,
  e: String,
  f: String,
  g: String) {
  def run[F[_]](
    fetch: ResolutionProcess.Fetch[F],
    maxIterations: Int = ResolutionProcess.defaultMaxIterations
  )(implicit
    F: Monad[F]
  ): F[Resolution] =
    ???
}
```

## Expectation

I would like
```scala
  f: String,
  g: String
) {
```
to be left as-is, rather than changed to
```scala
  f: String,
  g: String) {
```

## Workaround

Setting
```
verticalMultilineAtDefinitionSite = false
```
fixes that, but in turn, changes
```scala
  )(implicit
```
to
```scala
  )(
    implicit
```
(which I would like to avoid too).

**Comment by olafurpg** [comment]
Thanks for reporting! The two features were contributed separately so it could be that they don't play nicely together.

**Comment by kitbellew** [comment]
@alexarchambault you have reported two issues:
* dangling parens in case of vertical multiline
* split before implicit outside of vertical multiline

the first issue should be solved by setting `verticalMultiline.excludeDanglingParens = []` (which, for some reason, include `class` and `trait` by default). the vertical multiline logic doesn't use the `danglingParentheses` setting (which also only applies to methods).

the second issue remains, and i will send in a patch to address it.

**Comment by alexarchambault** [comment]
Thanks a lot for having fixed that, @kitbellew!
