### ISSUE TITLE
Default Indent Operator & unindentTopLevelOperators = true failing test

### ISSUE THREAD

**Issue by er1c** [scalameta/scalafmt#1370]
- **Version**: master
- **Integration**: CLI
- **Configuration**:
```
unindentTopLevelOperators = true
indentOperator = default
```
## Problem

Original Code:

```scala
      val foo = 1 +
      2 -
      2 *
      3 \
      4
```

Scalafmt Output:
```scala
       val foo = 1 +
         2 -
         2 *
           3 \
             4
```

## Expectation

```scala
       val foo = 1 +
         2 -
         2 *
         3 \
         4
```

## Notes

Failing Test PR:  https://github.com/scalameta/scalafmt/pull/1369

**Comment by tanishiking** [comment]
This issue seems already resolved by https://github.com/scalameta/scalafmt/issues/1370
Thank you so much for contribution @er1c !
Closing
