### ISSUE TITLE
feature this repo on facebook/Docusaurus site

### ISSUE THREAD

**Issue by ahtee** [scalameta/scalafmt#1373]
Hello, facebook/Docusaurus repo would like to feature you project on Docusaurus!! Please respond on your choice if you are ok with it!

source: [https://github.com/facebook/Docusaurus/issues/1080#issuecomment-466700926](https://github.com/facebook/Docusaurus/issues/1080#issuecomment-466700926)

Thank you!

**Comment by olafurpg** [comment]
Great idea! Sounds good to me 👍

**Comment by ahtee** [comment]
Thank you @olafurpg! 😍
