### ISSUE TITLE
How to avoid newlines after ⇒ / => on lambda functions?

### ISSUE THREAD

**Issue by fmv1992** [scalameta/scalafmt#1382]
This template is a guideline, not a strict requirement.
- **Version**: scalafmt 2.0.0-RC5
- **Integration**: CLI
- **Configuration**:
```
(none)
```

## Steps

Given code like this:
```scala
object Main {

  def f[A](x: A): A = {
    (x: A) ⇒ x
  }

}
```

When I run scalafmt like this:

```bash
scalafmt --config /dev/null a.scala
```

## Problem

Scalafmt formats code like this:
```scala
object Main {

  def f[A](x: A): A = { (x: A) ⇒
    x
  }

}
```

## Expectation

I would like the formatted output to look like this:
```scala
object Main {

  def f[A](x: A): A = {
    (x: A) ⇒ x
  }

}
```

## Workaround

I can manually join the lines ending with `⇒$`.

## Notes

I seached the documentation and google for a way to avoid breaking after the `⇒` token but I could not find one. I know how I can keep the `(x: A) ...` on the separate line but it always breaks on `⇒`.

**Comment by kitbellew** [comment]
@fmv1992 with the next release, which includes #1660, it will not break after arrow if and only if everything fits on one line. if that's sufficient, please close this request.

**Comment by kitbellew** [comment]
@fmv1992 please use `newlines.source=keep`.
