### ISSUE TITLE
Newline after scaladoc annotation

### ISSUE THREAD

**Issue by etspaceman** [scalameta/scalafmt#1387]
Recently I had a requirement to move descriptions for scaladoc annotations to a new line. E.g.:

```
/* Some scaladoc for my class
* @tparam someTParam This is a description for my type-param
* @param someParam This is a description for my param
...
*/
```

Becomes:
```
/* Some scaladoc for my class
* @tparam 
* someTParam This is a description for my type-param
* @param someParam 
* This is a description for my param
...
*/
```

I would love to see this as an officially supported option in scalafmt.

**Comment by kitbellew** [comment]
@etspaceman generally, scalafmt formats code, not comments. i doubt it will be implemented.

**Comment by etspaceman** [comment]
There are format rules for this kind of stuff in docstrings... so I would think something like this could absolutely fall under the responsibility of scalafmt

**Comment by kitbellew** [comment]
@etspaceman you're right, it could. there's a similar issue (possibly a superset): #1234

**Comment by Scarysize** [comment]
Sorry to chime into this old issue. Is there a way to prevent a newline after a scaladoc annotation?

```scala
/**
 * Foo bar lorem...
 *
 * @tparam C This sentence should stay on the same line as the type parameter annotation
 */
```

**Comment by tgodzik** [comment]
I think https://scalameta.org/scalafmt/docs/configuration.html#docstringswrap should help

**Comment by Scarysize** [comment]
`docstring.wrap = no` did work. Thanks!

**Comment by NihalJain** [comment]
> `docstring.wrap = no` did work. Thanks!

I think you meant `docstrings.wrap = no`, anyways thanks!

**Comment by coryfklein** [comment]
I wish there was a way to keep `docstring.wrap` enabled, but only disable the specific thing the OP asked for: splitting annotation descriptions onto a newline! If your comments are terse, you don't really want to break them into newlines.

For example:
```
/**
  * @return something great
  */
```

Becomes
```
/**
  * @return
  *   something great
  */
```

Obviously if you have 3 paragraphs of english after `@return` then the newline sets this content off nicely, but for shorter scaladocs it's such a waste.
