### ISSUE TITLE
Scalafmt cannot parse trailing commas in XML literals

### ISSUE THREAD

**Issue by Atry** [scalameta/scalafmt#1389]
This template is a guideline, not a strict requirement.
- **Version**: 1.5.1
- **Integration**: IntelliJ
- **Configuration**:
```
maxColumn = 120
```

## Steps

Given code like this:
```scala
class CommaInXml {
  def myXml = <div class={
    Set(
      "foo",
      "bar",
      "baz",
    ).mkString(" ")
  }></div>
}
```

When I run scalafmt in IntelliJ

## Problem

Scalafmt reports an error like this:
```scala
<input>:3: error: malformed xml literal
def myXml = <div class={
^
```

## Expectation

I expect no error reported

## Workaround

Delete the comma after `"baz"`

## Notes

Seems like a bug in Scala Meta

**Comment by poslegm** [comment]
Does not reproduce at version 2.2.2:

```
scalafmt --stdin --config-str "trailingCommas=preserve"  
class CommaInXml {
  def myXml = <div class={
    Set(
      "foo",
      "bar",
      "baz",
    ).mkString(" ")
  }></div>
}
class CommaInXml {
  def myXml =
    <div class={
      Set(
        "foo",
        "bar",
        "baz",
      ).mkString(" ")
    }></div>
}
```
