### ISSUE TITLE
Wrong indentation for boolean expression continuation in new line

### ISSUE THREAD

**Issue by anilkumarmyla** [scalameta/scalafmt#1393]
- **Version**: 2.0.0-RC5
- **Integration**: `sbt scalafmt`
- **Configuration**:
```
version = 2.0.0-RC5
```

## Steps

Given code like this:
```
  def a: Boolean = {
    true && true &&
      true
  }
```

When I run scalafmt like this:

```
sbt scalafmt
```

## Problem

Scalafmt formats code like this:
```
  def a: Boolean = {
    true && true &&
    true
  }
```

## Expectation

I would like the formatted output to look like this:
```
  def a: Boolean = {
    true && true &&
      true
  }
```

## Workaround

I've found that by removing the curly braces, it works correctly
```
  def a: Boolean =
    true && true &&
      true
```

**Comment by tanishiking** [comment]
@anilkumarmyla Thank you for reporting!

By default, scalafmt doesn't add indent for infix operator `&&` and `||`.
https://github.com/scalameta/scalafmt/blob/master/scalafmt-core/shared/src/main/scala/org/scalafmt/config/IndentOperator.scala#L35

You may you want to try

```
indentOperator = akka
```

[valid rhs of indentOperator is defined here](https://github.com/scalameta/scalafmt/blob/master/scalafmt-core/shared/src/main/scala/org/scalafmt/config/IndentOperator.scala#L55)

Or remove the operators from `indentOperator.exclude` manually

```
// default
indentOperator.exclude = "^(&&|\|\|)$"
// to
indentOperator.exclude = "^(\|\|)$"
```

**Comment by anilkumarmyla** [comment]
wow, I definitely missed this in the configuration. Any reason the default behavior is not to indent for `&&` and `||` ? I'd expect a continuation of an expression to be visually noticeable by extra indent.

You can close this issue if this is by design, thank you!

**Comment by tanishiking** [comment]
@olafurpg Do you know the original intention for this configuration?

I think we don't need to change the default value to avoid breaking change, I'm just curious :)

**Comment by kitbellew** [comment]
@anilkumarmyla closing the issue as you requested.
