### ISSUE TITLE
Update Installation docs, decide fate of IntelliJ plugin?

### ISSUE THREAD

**Issue by ches** [scalameta/scalafmt#1396]
### Plugin Future

~~Forgive me if there's been discussion in Gitter, I haven't been able to catch up, but~~
**edit**: _I [caught up with Gitter](https://gitter.im/scalameta/scalafmt?at=5c9bc2c95636de703defa71c)_

Since [IntelliJ Scala plugin's scalafmt support now uses scalafmt-dynamic][1], I wonder what the vision is for the plugin maintained in this repository. Are there reasons to continue maintaining it?

### Installation Docs

Perhaps lower-hanging fruit, let's update [the installation section of the doc site][2]. I can speak from experience in a sizable organization that the situation of Jetbrains support + our external plugin and "Use scalafmt formatter" + "Continue using IntelliJ formatter" confuses new users and gives some hesitation for adoption ("sounds like more trouble than it's worth if it's confusing to maintain integration with the main tools in our workflow").

The quick uptake of dynamic thanks to the community means that is mostly behind us now, but the doc site's marketing hasn't caught up 😉 

I'm happy to work up a docs PR, just want to get consensus on what to recommend. My inclination is to emphasize the seamless experience:

1. Install IntelliJ's Scala plugin.
2. Add a `.scalafmt.conf` with `version`.
3. Profit.

And relegate the external plugin to a footnote mainly for users who can't upgrade to IntelliJ 2019.1 yet for whatever reason.

Include a screenshot of `Editor > Code Style > Scala` with scalafmt selected.

Thoughts?

[1]: https://blog.jetbrains.com/scala/2019/03/27/intellij-scala-plugin-2019-1-highlighting-for-comprehensions-find-usages-for-implicits-and-more/#scalafmt
[2]: https://scalameta.org/scalafmt/docs/installation.html

**Comment by olafurpg** [comment]
Thanks for starting this discussion! I haven't tried the new IntelliJ EAP with Scalafmt dynamic support yet but if you say it's good then I'll take your word for it. I am OK with sunsetting the Scalafmt IntelliJ plugin and recommending the built-in integration instead. I will be very happy if I never have to update that plugin again since it always required quite many fragile manual steps :)

A PR updating the installation docs recommending the built-in Scalafmt integration in IntelliJ would be very welcome 🙏 

cc/ @unkarjedy

**Comment by ches** [comment]
I've marked the doc update to close this issue, @olafurpg could you create a new one as a task for sunsetting the plugin, with your preferred timeline and steps that should be taken (retire code and build setup, indicate deprecated in description on the JetBrains plugin directory, etc.)?
