### ISSUE TITLE
Weird indenting for Try/recover blocks

### ISSUE THREAD

**Issue by anilkumarmyla** [scalameta/scalafmt#1400]
This template is a guideline, not a strict requirement.
- **Version**: 2.0.0-RC6
- **Configuration**:
```
align = none
```

## Steps

Given code like this:
```
object Test {
  def a(b: Option[String]): String = {
    Try {
      "something1"
    }.recover {
      case NonFatal(_) => "something2"
    }.getOrElse("something3")
  }
}
```

When I run scalafmt like this:

```
sbt scalafmt
```

## Problem

Scalafmt formats code like this:
```
object Test {
  def a(b: Option[String]): String = {
    Try {
      "something1"
    }.recover {
        case NonFatal(_) => "something2"
      }
      .getOrElse("something3")
  }
}
```

## Expectation

I would like the formatted output to look like this (same as original):
```
object Test {
  def a(b: Option[String]): String = {
    Try {
      "something1"
    }.recover {
      case NonFatal(_) => "something2"
    }.getOrElse("something3")
  }
}
```

**Comment by kitbellew** [comment]
@anilkumarmyla is it still a problem? i can't reproduce.

**Comment by anilkumarmyla** [comment]
@kitbellew I can still reproduce this with 2.3.2

**Comment by anilkumarmyla** [comment]
Unfortunately I cannot test with latest 2.3.3-RC* releases 
```
[error] scalafmt version 2.3.3-RC2 classpath is corrupted: /Users/anilkumarmyla/foo/.scalafmt.conf
```

**Comment by anilkumarmyla** [comment]
@kitbellew just tried out 2.4.0-RC1 which doesn't exhibit the classpath corrupted problem and can still reproduce

**Comment by kitbellew** [comment]
@anilkumarmyla the linked PR solves the problem when `optIn.breaksInsideChains = false` or when there is only one select (i.e., the case when that flag doesn't apply). otherwise, the flag mandates preserving the break and the indentation, or it leads to non-idempotence issues.
