### ISSUE TITLE
Changes to .scalafmt.conf should invalidate the scalafmt cache and reformat all files again

### ISSUE THREAD

**Issue by anilkumarmyla** [scalameta/scalafmt#1401]
- **Version**: 2.0.0-RC6
- **Configuration**:
```
align = none
```

## Steps
1. Run `sbt scalafmt`
2. Modify .scalafmt.conf
3. Run `sbt scalafmt`
## Problem
No files are re-formatted as per modified .scalafmt.conf

## Expectation
Reformat all files

## Workaround

I've found that by deleting the target directory, I can make scalafmt reformat all files again

**Comment by poslegm** [comment]
@anilkumarmyla what version of sbt plugin do you use? I tried to reproduce it with sbt-scalafmt v2.0.2 and config modifications applies correct.

**Comment by anilkumarmyla** [comment]
@poslegm I can reproduce this with sbt-scalafmt v2.0.2 and scalafmt v2.0.0

I repeatedly run `sbt scalafmt test:scalafmt` until I see that no source changes are being made. Then I modify `.scalafmt.conf` and then run `sbt scalafmt test:scalafmt`, and see that no source changes occur.

**Comment by anilkumarmyla** [comment]
when i do `cat target/streams/compile/scalafmt/\$global/streams/in-cache` at the point when no changes are being made, the entries in that file don't have .scalafmt.conf file.

**Comment by poslegm** [comment]
@anilkumarmyla 

Can you please try this steps:

1. `sbt scalafmt test:scalafmt` until I see that no source changes
2. modify `.scalfmt.conf`
3. `sbt clean`
4. `sbt scalafmt test:scalafmt`

Looks like sbt caches source files after first formatting action

**Comment by dwijnand** [comment]
Changes to `.scalafmt.conf` should invalidate the `scalafmt`/`test:scalafmt`'s cache (but it looks like it doesn').

**Comment by FabioPinheiro** [comment]
I also have this problem.
Now that we have incremental compilation always on. 
Would be nice to also have a command to delete the cache

**Comment by dwijnand** [comment]
As a workaround you can run arbitrary Scala with `eval`, such as:

```scala
$ eval new java.io.File("target/streams/compile/compile/$global/streams/out").delete()
```

**Comment by poslegm** [comment]
The problem is that sbt-scalafmt use common sbt cache. So we can handle config modifications in plugin and force cache cleanup, but user will have to build all project without incremental compilation.

I think that ideal solution is different cache for formatting results. As a temporary trade-off we can force `sbt clean` after config modification in plugin.

**Comment by bjaglin** [comment]
@anilkumarmyla does https://github.com/scalameta/sbt-scalafmt/pull/40/commits/76bf2af2c1a47e2503eb2015643d12a94e82f9ce fix your issue?

**Comment by anilkumarmyla** [comment]
@bjaglin that sounds promising, can try it on a local build

**Comment by anilkumarmyla** [comment]
This is fixed by https://github.com/scalameta/sbt-scalafmt/pull/40

Thanks @bjaglin for the fix
