### ISSUE TITLE
IntelliJ plugin not working as expected

### ISSUE THREAD

**Issue by gmendonca** [scalameta/scalafmt#1402]
- **Version**: 2.0.0-RC5
- **Integration**: IntelliJ
- **Configuration**:
```
align = none
maxColumn = 120
version=2.0.0-RC5
```

## Steps

Given code like this:
```scala
  def someCoolFunction(
      SomeCoolParameter: String,
      SomeOtherCoolParameter: Boolean,
      SomeOtherEvenCoolerParameter: String): String = {
    "Cool"
  }
```

When I run scalafmt like this:

```bash
sbt scalafmt
```

## Problem

Scalafmt formats code like this:
```scala
  def someCoolFunction(
      SomeCoolParameter: String,
      SomeOtherCoolParameter: Boolean,
      SomeOtherEvenCoolerParameter: String
  ): String = {
    "Cool"
  }
```

However, if a run `Reformat Code with Scalafmt` on IntelliJ, it stays the same:
```scala
  def someCoolFunction(
      SomeCoolParameter: String,
      SomeOtherCoolParameter: Boolean,
      SomeOtherEvenCoolerParameter: String): String = {
    "Cool"
  }
```

## Expectation

That both IntelliJ and `sbt scalafmt` works the same way.

## Notes

After I ran `sbt scalafmt`, and if I try run `Reformat Code with Scalafmt` on IntelliJ it doesn't change the code either. In other words, it accept both ways. However, `sbt scalaCheck` fails if I just reformat with IntelliJ, as expected of `align.openParenCallSite = false`.

**Comment by tanishiking** [comment]
@gmendonca Thank you for reporting!
Which version of `IntelliJ Scala Plugin` and sbt-scalafmt are you using?
FYI, [custamizable scalafmt version from inttelij-scala-plugin is available after 2019.1](https://blog.jetbrains.com/scala/2019/03/27/intellij-scala-plugin-2019-1-highlighting-for-comprehensions-find-usages-for-implicits-and-more/#scalafmt)

I tried to reproduce it with `IntelliJ Scala Plugin 2019.1`, and `sbt-scalafmt 2.0.0`, but I couldn't.

**Comment by gmendonca** [comment]
Ok, you led me for the solution. Even though I was using `addSbtPlugin("org.scalameta" % "sbt-scalafmt" % "2.0.0")`, `version=2.0.0-RC5` on `.scalafmt.conf` and `IntelliJ Scala Plugin 2019.1`, the plugin installed from the Marketplace was still the `1.5.1`. Thus, even though IntelliJ showed the configuration being used as from `sbt-scalafmt 2.0.0`, it was actually using the stable version for formatting.

**Comment by gmendonca** [comment]
I was being fooled the whole time, I am sorry for the confusion.

**Comment by tanishiking** [comment]
Glad to hear that :) :+1:

**Comment by antoinewdg-mt** [comment]
I spent too much time on this thread before getting it, so I'll clarify:

**UN**install the scalafmt plugin (it has been incorporated in recent IDEA versions) to fix the issue.
