### ISSUE TITLE
Oneline short scaladoc

### ISSUE THREAD

**Issue by dwijnand** [scalameta/scalafmt#1403]
- **Version**: 2.0.0-RC5
- **Integration**: CLI
- **Configuration**:
```
docstrings = ScalaDoc
```

## Steps

Given code like this:
```scala
/**
  * Main entry-point.
  */
class Main
```

When I run scalafmt like this:

```bash
scalafmt
```

## Problem

Scalafmt formats code like this:
```scala
/**
  * Main entry-point.
  */
class Main
```

## Expectation

I would like the formatted output to look like this:
```scala
/** Main entry-point. */
class Main
```

## Workaround

No workaround (outside of manual formatting, which at least is preserved).

## Notes

The Scaladoc usage documentation (https://docs.scala-lang.org/style/scaladoc.html) expressly mentions this case:

> When only a simple, short description is needed, a one-line format can be used:
> 
> ```scala
> /** Does something very simple */
> def simple: Unit = ()
> ```

I would, personally, like to have access to this behaviour also using `docstrings = JavaDoc`.

I'd be happy to attempt to resolve this, given some guidance.

**Comment by dwijnand** [comment]
In https://github.com/scalameta/scalafmt/issues/891 @eed3si9n suggests the style guide is promoting a style that is only upheld in the scala/scala repo and not in other major Scala projects and therefore Scalafmt should go the other way: enforce a newline is inserted (making each Scaladoc minimum 3 lines).

I'd be happy for oneline scaladocs to be an opt-in behaviour change, rather than default behaviour change.

**Comment by dwijnand** [comment]
> I'd be happy to attempt to resolve this, given some guidance.

Assuming that this opt-in is acceptable (please let me know if not), could someone tell me how I would go about implementing this?  I assume this tests like every other vanilla scalafmt opt-in.

**Comment by eed3si9n** [comment]
I am getting nerd sniped into providing code examples from the repos that I listed that uses JavaDoc style.

### Scala 2.12.2 Predef.scala
https://github.com/scala/scala/blob/v2.12.2/src/library/scala/Predef.scala#L145
```scala
  /**  @group aliases */
  type Map[A, +B] = immutable.Map[A, B]
```

### Akka 2.5.0 
https://github.com/akka/akka/blob/v2.5.0/akka-actor/src/main/scala/akka/actor/Actor.scala
They do not use one-line style. This could be related to the fact that they actually run `javadoc` via genjavadoc.
```scala
/**
 * A message all Actors will understand, that when processed will terminate the Actor permanently.
 */
@SerialVersionUID(1L)
case object PoisonPill extends PoisonPill {
```

### ScalaTest 3.0.2
With everything is commented heavily, so it's rare to find one-liner in ScalaTest, but when they do they use multi-line JavaDoc.
https://github.com/scalatest/scalatest/blob/release-3.0.2/scalatest/src/main/scala/org/scalatest/concurrent/AbstractPatienceConfiguration.scala#L93-L96
```scala
  /**
   * Returns a <code>PatienceConfig</code> value providing default configuration values if implemented and made implicit in subtraits.
   */
  def patienceConfig: PatienceConfig
```

### Cats 0.9.0
https://github.com/typelevel/cats/blob/v0.9.0/core/src/main/scala/cats/MonadError.scala
It seems like Cats also use multi-line JavaDoc style for one-lines.
```scala
  /**
   * Turns a successful value into an error if it does not satisfy a given predicate.
   */
  def ensure[A](fa: F[A])(error: => E)(predicate: A => Boolean): F[A] =
```

### sbt 0.13.17
https://github.com/sbt/sbt-zero-thirteen/blob/v0.13.17/main/settings/src/main/scala/sbt/Structure.scala
```scala
/** Methods and types related to constructing settings, including keys, scopes, and initializations. */
object Scoped {
```

### summary

Among the "JavaDoc" camp, which I believe is the one true style for API comments, there are traditionalists (Akka, ScalaTest, Cats) and one-liner centralists (Scala, sbt).

**Comment by dwijnand** [comment]
Lovely, thank you.
