### ISSUE TITLE
project.excludeFilters with slash causes problem on Windows

### ISSUE THREAD

**Issue by eed3si9n** [scalameta/scalafmt#1404]
This template is a guideline, not a strict requirement.
- **Version**: 2.0.0-RC5
- **Integration**: sbt-scalafmt
- **Configuration**:
```
version = 2.0.0-RC5
maxColumn = 100
project.git = true
project.excludeFilters = [ /sbt-test/, /input_sources/, /contraband-scala/ ]
```

## Steps

Run scalafmt on Windows, for example Image: Visual Studio 2015.

## Problem

I get errors like:

```
[error] Illegal/unsupported escape sequence near index 13
[error] (\sbt-test\|\input_sources\|\contraband-scala\)
[error]              ^: C:\projects\sbt\scripted-sbt-redux\src\main\scala\sbt\scriptedtest\BatchScriptRunner.scala
```

## Expectation

Works like it works on Linux.

## Notes

Likely related:
https://github.com/scalameta/scalafmt/blob/v2.0.0-RC6/scalafmt-core/shared/src/main/scala/org/scalafmt/util/OsSpecific.scala
https://github.com/scalameta/scalafmt/blob/v2.0.0-RC6/scalafmt-core/shared/src/main/scala/org/scalafmt/config/FilterMatcher.scala

**Comment by eed3si9n** [comment]
I thought 

```
project.excludeFilters = [ \Wsbt-test\W, \Winput_sources\W, \Wcontraband-scala\W ]
```

would be a workaround, but now it's hitting a different behavior:

```
[error] missing setting 'version'. To fix this problem, add the following line to .scalafmt.conf: 'version=2.0.0-RC5'.: C:\projects\sbt\.scalafmt.conf
```

**Comment by olafurpg** [comment]
I just kickstarted a 2.0.0-RC7 release to publish the fix
