### ISSUE TITLE
trailing comma after closing bracket of 'else'

### ISSUE THREAD

**Issue by aBnormaLz** [scalameta/scalafmt#1406]
- **Version**: 2.0.0-RC5
- **Integration**: IntelliJ
- **Configuration**:
```
version = 2.0.0-RC5
maxColumn = 160
trailingCommas = always
align.openParenCallSite = false
align.openParenDefnSite = false
align = most
```

I think the important part is the 'trailingCommas', but I copied my whole configuration just in case

## Steps

Given code like this:
```scala
  def invalidComma(): Future[Boolean] = {
    Future
      .successful(true)
      .flatMap(theBoolean => {
        if (theBoolean) {
          Future.successful(doSomething())
        } else {
          Future.successful(doSomethingElse())
        }
      })
  }
```

When I run scalafmt like this:

I call the scala FMT plugin with the hotkey (Reformat with scalafmt)

## Problem

Scalafmt formats code like this (please note the invalid comma at the closing bracket of 'else'):
```scala
  def invalidComma(): Future[Boolean] = {
    Future
      .successful(true)
      .flatMap(theBoolean => {
        if (theBoolean) {
          Future.successful(doSomething())
        } else {
          Future.successful(doSomethingElse())
        },
      })
  }
```

## Expectation

I would like the formatted output to look like this:
```scala
  def invalidComma(): Future[Boolean] = {
    Future
      .successful(true)
      .flatMap(theBoolean => {
        if (theBoolean) {
          Future.successful(doSomething())
        } else {
          Future.successful(doSomethingElse())
        }
      })
  }
```

**Comment by aBnormaLz** [comment]
Seems like only IntelliJ thinks that this is an invalid comma, since `sbt compile` doesn't give an error, but still i think there shouldn't be a comma. Do you agree?

**Comment by tanishiking** [comment]
@aBnormaLz Thank you for reporting :smile: 

>  there shouldn't be a comma. Do you agree?

IMHO, I can't agree with this because I believe that `trailingCommas = always` should add a trailing comma as long as it compiles (in Scala 2.12 or later), even though it looks bit wired for sure (because `map` doesn't accept any more arguments).

**Comment by aBnormaLz** [comment]
Yeah after I figured out that it compiles I thought somebody will say that :D well then i'll make an issue for IntelliJ about this.

Thanks for your answer!

**Comment by tanishiking** [comment]
>  i'll make an issue for IntelliJ about this.

It'll be great :+1:
Let me close this issue, thanks again for reporting!

**Comment by aBnormaLz** [comment]
The issue is done, now let's see what happens :)

https://youtrack.jetbrains.com/issue/WEB-38518

Keep up the good work guys!
