### ISSUE TITLE
allow styleVersion setting

### ISSUE THREAD

**Issue by eed3si9n** [scalameta/scalafmt#1412]
```
maxColumn = 100
project.git = true
docstrings = JavaDoc
spaces.inImportCurlyBraces = true
align.openParenCallSite = false
align.openParenDefnSite = false
danglingParentheses = true
```

## Steps

1. Run scalafmt 1.5.1. Git commit.
2. Run scalafmt 2.0.0-RC5

## Problem

There are some format changes because the default has changed.

## Expectation

I would like to update to the latest release of scalafmt for compatibility with Scalameta or to pick up some bug fixes, but without stylistic changes. The changes themselves might be perfectly valid for new code base, but for existing code, there's a tradeoff of adding more commits.

I would be nice if I could specify some number:

```
styleVersion = 1.5
```

and scalafmt attempted to default to the style 1.5.x did.

**Comment by tanishiking** [comment]
@eed3si9n
The most of latest scalafmt plugins have such functionality to specify the running scalafmt version using `version=1.5.1` in `.scalafmt` :)
 Could you update the scalafmt plugins?

Refer the following comment for required plugins version to use the feature.
https://github.com/scalameta/scalafmt/issues/1318#issuecomment-471176843

**Comment by eed3si9n** [comment]
I am aware of `version = 2.0.0-RC5` setting. That's why I noted "I would like to update to the latest release of scalafmt for compatibility with Scalameta or to pick up some bug fixes, but without stylistic changes."

**Comment by olafurpg** [comment]
The style changes in the v2 release were unavoidable due to the changed syntax trees from upgrading the Scalameta dependency. Otherwise, we try not to merge style changes without options to preserve the old style.

**Comment by eed3si9n** [comment]
> The style changes in the v2 release were unavoidable due to the changed syntax trees from upgrading the Scalameta dependency. Otherwise, we try not to merge style changes without options to preserve the old style.

I understand it would not be possible to keep 100% compatibility, but for example `trailingCommas = preserve` would be something `styleVersion` could benefit. To lower the expectation of fidelity, I'd also be happy if the `styleVersion` is a separately increased integer like `styleVersion=10` or something.

**Comment by olafurpg** [comment]
I see. My concern is that the `styleVersion=10` could end up being yet another a cryptic entry in `.scalafmt.conf` adding to the already (too) complex configuration format. It also opens questions about how to handle precedence/conflicts, for example what happens when `styleVersion=10` and `trailingCommas = never`?

One thing we could do better is highlight in the release notes what defaults have changed and provide copy-paste settings to use the old defaults 🤔

**Comment by eed3si9n** [comment]
> It also opens questions about how to handle precedence/conflicts, for example what happens when `styleVersion=10` and `trailingCommas = never`?

`styleVersion = 10` is a replacement of defaults, so setting should win. An example would be something like `docstrings = JavaDoc`, which existed in 1.5.1.

```
styleVersion = 10
docstrings = JavaDoc
```

would get the same style for both docstrings and trailingCommas on 1.5.1 or 2.0.

> One thing we could do better is highlight in the release notes what defaults have changed and provide copy-paste settings to use the old defaults 🤔

I mean that _could_ work, but that could start to clutter the `.scalafmt.conf` with more corner-case configurations, and could get confusing as some defaults may flip-flop over time. `styleVersion` gives Scalafmt freedom to change the defaults while allowing users to freeze their configuration as of their adoption.
