### ISSUE TITLE
ScalaFmt doesn't like escape characters next to string-interpolated value

### ISSUE THREAD

**Issue by lihaoyi-databricks** [scalameta/scalafmt#1414]
- **Version**: 2.0.0-RC5
- **Integration**: Homebrew
- **Configuration**:

default

## Steps

Given code like this:
```scala
object Hello{
  s"\"$filter\""
}
```

When I run scalafmt like this:

```bash
scalafmt foo.scala
```

## Problem

I get this error
```scala
/Users/lihaoyi/universe/foo.scala:2: error: ; expected but string constant found
  s"\"$filter\""
              ^
```

## Expectation

It should be a no-op

**Comment by lihaoyi-databricks** [comment]
actually, this seems like broken scala syntax...

**Comment by RaduGrama** [comment]
https://github.com/scala-js/scala-js/issues/2210#issuecomment-176834314
