### ISSUE TITLE
Trailing Commas shouldn't be added to function literals

### ISSUE THREAD

**Issue by daniel-shuy** [scalameta/scalafmt#1417]
- **Version**: 2.0.0-RC6
- **Integration**: IntelliJ
- **Configuration**:
```
trailingCommas = always
```

## Steps

Given code like this:
```scala
Option("Hello World").foreach(str => {
  println(x)
})
```

When I run scalafmt like this:

```bash
scalafmt
```

## Problem

Scalafmt formats code like this:
```scala
Option("Hello World").foreach(str => {
  println(x),
})
```

While the code still compiles, Intellij highlights it as an error.

## Expectation

I would like the formatted output to look like this:
```scala
Option("Hello World").foreach(str => {
  println(x)
})
```

## Workaround
Oddly enough if the function literal has more than 1 line `scalafmt` will not append a trailing comma.

## Notes

Although the example given can be worked around by removing the braces, eg.
```scala
Option("Hello World").foreach(str => println(x))
```

Given a more complicated example, with nested function literals, eg.
```scala
def scopedCommandName(
    project: String,
    command: Command,
): Option[State => String] = {
  command.nameOption.map(commandName => {state: State =>
    s";project $project; $commandName; project ${Project.extract(state).currentProject.id}"
  })
}
```
produces
```scala
def scopedCommandName(
    project: String,
    command: Command,
): Option[State => String] = {
  command.nameOption.map(commandName => {
    state: State =>
      s";project $project; $commandName; project ${Project.extract(state).currentProject.id}",
  })
}
```
which again is highlighted as an error in Intellij.

**Comment by tanishiking** [comment]
@daniel-shuy 
Thanks for reporting :) but this issue might be duplicate with https://github.com/scalameta/scalafmt/issues/1406, and @aBnormaLz opened the issue on intelliJ
https://youtrack.jetbrains.com/issue/SCL-15349?p=WEB-38518

**Comment by tanishiking** [comment]
Ah, let me close because of duplication with https://github.com/scalameta/scalafmt/issues/1410
