### ISSUE TITLE
RedundantBraces fails on String interpolation when the identifier started with underscore 

### ISSUE THREAD

**Issue by FabioPinheiro** [scalameta/scalafmt#1420]
This template is a guideline, not a strict requirement.
- **Version**: 2.0.0-RC7
- **Integration**: sbt / any?
- **Configuration**:
```
rewrite {
  rules = [ RedundantBraces ]
  redundantBraces.stringInterpolation = true
}
```

## Steps

Given code like this:
```scala
object a {
  s"Hello ${_id}"
}
```

## Problem

`error: error in interpolated string: identifier, `this' or block expected`

Scalafmt formats code like this:
```scala
object a {
  s"Hello $_id"
}
```

## Expectation
If identifier started with underscore it should be no a block expected
The formatting output should not remove the braces on that case

## Workaround
object a {
  val workaround = _id
  s"Hello $workaround"
}

## Notes
O found a related ticket https://github.com/scalameta/scalafmt/issues/1227
@gaelrenoux

**Comment by poslegm** [comment]
@FabioPinheiro please try it with scalafmt [2.0.0-RC8](https://github.com/scalameta/scalafmt/releases/tag/v2.0.0-RC8)

**Comment by tanishiking** [comment]
It had already fixed by https://github.com/scalameta/scalafmt/pull/1425, thank you so much for @poslegm and @FabioPinheiro !
