### ISSUE TITLE
Multiline comments have * alignment changed with "format: off"

### ISSUE THREAD

**Issue by huonw** [scalameta/scalafmt#1424]
- **Version**: 0.5
- **Integration**: sbt
- **Configuration**:
```
version=2.0.0-RC5
```

## Steps

Given code like this:
```scala
// format: off
/*
        *
*

*/

/**
 * Javadoc style
 *
 */
// format: on
```

When I run scalafmt like this:

```bash
sbt scalafmt 
```

## Problem

Scalafmt formats code like this:
```scala
// format: off
/*
 *
 *

 */

/**
  * Javadoc style
  *
  */
// format: on
```

Notice the indentation has changed, including removing the "javadoc" alignment.

## Expectation

I would like the formatted output to look like this (same as it was originally):
```scala
// format: off
/*
        *
*

*/


/**
 * Javadoc style
 *
 */
// format: on
```

## Workaround

If it's a whole file that needs to have this sort of formatting preserved, `project.excludeFilters = [ "path/to/file" ]` seems to stop the formatting entirely for that file, including of comments.

**Comment by kitbellew** [comment]
@huonw is it still a problem?

**Comment by huonw** [comment]
Sorry, I've changed projects and am no longer using Scala. If the reproducer still reproduces, this is likely still a problem for that project; if it does not (the output matches the expectation), then it is not a problem.
