### ISSUE TITLE
Using intellij plugin behind corporate proxy

### ISSUE THREAD

**Issue by Johnlon** [scalameta/scalafmt#1427]
The intellij scalafmt plugin expects to be able to reach out to standard internet locations to fetch dependencies.
If I am on a corporate net where access to all maven repos is blocked.

Is there a way to override the location/path from which the plugins dependencies are loaded? Eg so I could configure an alternative maven cache as the location.

In gradle and maven for instance we can redefine the repo locations.
Does scalafmt plugin allow me to do same?

**Comment by stephennancekivell** [comment]
Hi, I havent tried this myself. But I can try point you in the right direction.

Scalafmt uses [coursier](https://get-coursier.io) for downloading, so you should be able to configure the repositories through it. https://get-coursier.io/docs/other-repositories.
Im not sure where you could set the environment variables for idea though.

**Comment by Johnlon** [comment]
Yes couldn't work out how to make this cfg work either.
Seems there's a hard coded list of repos in the code.
Couldn't figure out how to influence this!?

**Comment by stephennancekivell** [comment]
Have you tried setting the variable on the command line and launching idea from the command line.

eg
```
export COURSIER_REPOSITORIES="https://corporate.com/repo" 
/Applications/IntelliJ\ IDEA.app/Contents/MacOS/idea                                               
```

**Comment by olafurpg** [comment]
Thanks for reporting! Please report this issue to YouTrack. The IntelliJ Scala plugin has built-in support for Scalafmt and there is not much we can do about this on our side.

**Comment by Johnlon** [comment]
didn't manage to get this working.

So IntelliJ scalafmt plugin still reports missing dependencies in the ide
when opening project.
