### ISSUE TITLE
Using literals.long = Upper leads to upper case hex prefix 0X

### ISSUE THREAD

**Issue by aumann** [scalameta/scalafmt#1437]
- **Version**: 2.0.0-RC8
- **Integration**: IntelliJ
- **Configuration**:
```
version = "2.0.0-RC8"
style = defaultWithAlign
maxColumn = 100
lineEndings = preserve
rewrite.rules = [SortImports]
```

## Steps

Given code like this:
```scala
   object UInt32 {
     val Mask: Long     = 0xFFFFFFFFL
   }
```

When I run scalafmt (sbt or IntelliJ, same result)

## Problem

Scalafmt formats code like this:
```scala
   object UInt32 {
     val Mask: Long     = 0XFFFFFFFFL
   }
```

## Expectation
scalafmt should not uppercase the 'x'

I would like the formatted output to look like this:
```scala
   object UInt32 {
     val Mask: Long     = 0xFFFFFFFFL
   }
```

## Workaround
Add configuration to leave literals unchanged:
```
literals.long = Unchanged
```

**Comment by stephennancekivell** [comment]
Are the examples in the description correct ? It sounds like the value should be changing, but it looks the same.

**Comment by aumann** [comment]
Maybe it's a font/device thing. Some of them really do not show the upper case 'x' well. The difference between the three examples is that the 'x' is upper case in the 'Problem' section - at least on my displays.

**Comment by stephennancekivell** [comment]
Right, sorry I see now.

**Comment by aeons** [comment]
This setting will also uppercase the actual hex digits, changing `val l: Long = 0xffffL` to `val l: Long = 0XFFFFL`.
I would assume it only changed the suffix specifier.

**Comment by aeons** [comment]
It still uppercases the actual hex digits though.
