### ISSUE TITLE
how to get more vertical alignments than 'most'?

### ISSUE THREAD

**Issue by taeguk** [scalameta/scalafmt#1438]
## What I want
![image](https://user-images.githubusercontent.com/9107889/60155456-25637e00-9825-11e9-9a20-ae08493dd4bf.png)

## Actually what I get with scalafmt
![image](https://user-images.githubusercontent.com/9107889/60155492-4035f280-9825-11e9-9977-3389c33e3e82.png)

Is there any way to get vertical alignments like what I want?
I tried tweaking some options such as `align = most`, but I couldn't get what I want.

**Comment by poslegm** [comment]
`align = most` leaves only one space after `=`. So there is no option to reach your expected alignment.

**Comment by tanishiking** [comment]
scalafmt can configure the vertical alignment behavior using `align.token` options https://scalameta.org/scalafmt/docs/configuration.html#aligntokens :) (but I'm not sure how we can realize the behavior you want...)
