### ISSUE TITLE
Regression: duplicate "missing Scalafmt version" error 

### ISSUE THREAD

**Issue by olafurpg** [scalameta/scalafmt#1442]
When upgrading to scalafmt-dynamic v2.0.0 in Metals we encountered a regression from 2.0.0-RC4 where a "missing scalafmt version" warning is reported for a config file that has been updated to include a scalafmt version
https://dev.azure.com/olafurpg/Metals/_build/results?buildId=646&view=logs&jobId=0da5d1d9-276d-5173-c4c4-9d4d4ed14fdb&taskId=5494183b-801e-5084-3b4b-5451c6a14ee1&lineStart=3604&lineEnd=3606&colStart=1&colEnd=126

Steps to reproduce:

- format with .scalafmt.conf that is missing a `version` settings, a "missing version" warning is reported as expected
- add `version` setting and format again, an invalid "missing version" warning is reported when I expected the format to succeed since the config file has been updated.

It looks like `ReentrantCache.getOrAddToCache` returns stale results (it doesn't pick up changes in .scalafmt.conf files).

**Comment by anilkumarmyla** [comment]
Is this similar to #1401 ?
