### ISSUE TITLE
Application-wide preferences memory leak

### ISSUE THREAD

**Issue by imatt611** [scalameta/scalafmt#1445]
- **Version**: 1.5.1
- **Integration**: IntelliJ
- **Configuration**: OS X 10.14.5

## Steps

1. Open IntelliJ with no project windows.
2. Open Preferences
3. Set scalafmt as the Scala formatter
4. Close Preferences
5. Open Preferences

## Problem

When scalafmt is set as the Scala formatter, Preferences is unusable when no project windows are open (if a project window is open, Preferences work as expected).

## Expectation

IntelliJ Preferences function normally when scalafmt is the Scala formatter and there are no project windows open.

## Workaround

Open a project window before opening preferences. This may make it more difficult to configure one's preferences for new projects.

## Notes

See [this video](https://drive.google.com/open?id=1a0zvMpLEjQXbYsegep6ET6zG4JvOUyE4), in which the steps above are followed while Activity Monitor is showing the memory usage of IntelliJ, a memory limit event occurs, and a project window is opened to demonstrate the workaround.

**Comment by poslegm** [comment]
I can't reproduce it with OS X and IDEA 2019.2.4. Is it actual for you on the latest versions of IDEA and Scala plugin?

**Comment by imatt611** [comment]
This does appear to be resolved. Difficult to say when, for I've updated my macOS to Catalina 10.15 and IDEA to the latest as well.
