### ISSUE TITLE
Unnecesary indent on case

### ISSUE THREAD

**Issue by wdanilo** [scalameta/scalafmt#1454]
## Steps
I have tested literally every option and I cannot this code:
Given code like this:
```scala
compare(op1.prec, op2.prec) match {
  case GT => (seg2_, seg1 :: inp.stack)
  case LT => (inp.seg, reduce2(inp.stack))
  case EQ =>
    (op1.assoc, op2.assoc) match {
      case (Left, Left)   => (inp.seg, reduce2(inp.stack))
      case (Right, Right) => (seg2_, seg1 :: inp.stack)
      case _              => ???
    }
}
```
To be formatted this way:

```scala
compare(op1.prec, op2.prec) match {
  case GT => (seg2_, seg1 :: inp.stack)
  case LT => (inp.seg, reduce2(inp.stack))
  case EQ => (op1.assoc, op2.assoc) match {
    case (Left, Left)   => (inp.seg, reduce2(inp.stack))
    case (Right, Right) => (seg2_, seg1 :: inp.stack)
    case _              => ???
  }
}
```

I would really be happy if scalafmt would just leave it as is when I write it my way, but everytime it uses additional, unnecessary indentation. Is there any way I could keep the indentation smaller?

**Comment by tanishiking** [comment]
Thank you for reporting 👍  and sorry for being unanswered, let me close this for https://github.com/scalameta/scalafmt/issues/1518
