### ISSUE TITLE
Use the passed `<file>` arguments as a pre-filter (vs an override)

### ISSUE THREAD

**Issue by ArturGajowy** [scalameta/scalafmt#1457]
Currently, running:

`scalafmt README.md`

causes it to fail with an error, because that's no Scala code (duh!).

I would though expect scalafmt to simply skip the file, or IOW treat the passed files as a discovery pre-filter rather than accepting them as is. This would help greatly in setup of commit hooks, as then one could simply

`scalafmt CHANGED_FILE1 CHANGED_FILE2 CHANGED_FILE3`

without re-implementing scalafmt's logic for what's a scala source and what's not.

**Comment by ArturGajowy** [comment]
I should add that I find it unintuitive, because running just `scalafmt` skips non-scala sources

**Comment by tanishiking** [comment]
This behavior is intended. I don't think it is unintuitive for scalafmt-cli to try to format the file specified in the arguments.

> This would help greatly in setup of commit hooks, as then one could simply

You may you want to use `scalafmt --mode changed`

**Comment by ArturGajowy** [comment]
You're right! Thx for the hint! :)
