### ISSUE TITLE
Random `recv: Connection reset by peer` (using Nailgun)

### ISSUE THREAD

**Issue by ArturGajowy** [scalameta/scalafmt#1461]
I'm running scalafmt 2.0.0 via nailgun (fresh `brew install`, set up as a service using systemd and generated by doing `coursier bootstrap --standalone`). I get random `recv: Connection reset by peer` on reformatting:

```
11:16 $ scalafmt build.sbt 
Reformatting...
✔ ~/projects/rchain-bloop 
11:16 $ scalafmt build.sbt 
Reformatting...
✔ ~/projects/rchain-bloop 
11:16 $ scalafmt build.sbt 
Reformatting...
recv: Connection reset by peer
✘-227 ~/projects/rchain-bloop 
11:16 $ scalafmt build.sbt 
Reformatting...
recv: Connection reset by peer
✘-227 ~/projects/rchain-bloop 
```

Seems like a nailgun integration issue? Or maybe its nailgun itself?

**Comment by tanishiking** [comment]
Thank you for reporting!
It looks like the issue of nailgun itself, and according to https://github.com/propensive/fury/issues/71 nailgun 1.0.0 fixed this problem (though I'm not sure which commit to facebook/nailgun fixed this...).
