### ISSUE TITLE
Trailing comma in one-line lambdas with curly braces.

### ISSUE THREAD

**Issue by adampauls** [scalameta/scalafmt#1464]
- **Version**: 2.0.0
- **Integration**: IntelliJ
- **Configuration**:
```
version = "2.0.0"
maxColumn = 120 
rewrite.rules = [PreferCurlyFors, SortModifiers, AvoidInfix]
trailingCommas = always
assumeStandardLibraryStripMargin = true
optIn.breakChainOnFirstMethodDot = false
spaces.inImportCurlyBraces = true
includeCurlyBraceInSelectChains = true
spaces.beforeContextBoundColon = Always
// These are copied from  https://scalameta.org/scalafmt/docs/configuration.html#other
rewrite.neverInfix.excludeFilters = [
  until
  to
  by
  eq
  ne
  "should.*"
  "contain.*"
  "must.*"
  in
  ignore
  be
  taggedAs
  thrownBy
  synchronized
  have
  when
  size
  only
  noneOf
  oneElementOf
  noElementsOf
  atLeastOneElementOf
  atMostOneElementOf
  allElementsOf
  inOrderElementsOf
  theSameElementsAs
  // these are new
  throws
  returns
]
```

## Steps

Given code like this:
```scala
object Foo {
  Some(1).map(data => {
    data
  })
}
```

When I run scalafmt like this:

Save in IntelliJ.

## Problem

Scalafmt formats code like this:
```scala
object Foo {
  Some(1).map(data => {
    data,
  })
}

```

## Expectation

I would like the formatted output to look like this:
```scala
object Foo {
  Some(1).map(data => {
    data
  })
}

```

## Workaround

None that I know of.

## Notes

I see that there was already some discussion about this in https://github.com/scalameta/scalafmt/issues/1406#issuecomment-485402736, but in that comment, but I believe that comment misunderstands the problem.

   > IMHO, I can't agree with this because I believe that trailingCommas = always should add a trailing comma as long as it compiles (in Scala 2.12 or later), even though it looks bit wired for sure (because map doesn't accept any more arguments).

The problem is not that a comma is being added after the argument to map, it's that it's being added in the body of a lambda, and only in a very specific situation (though it does compile). Note that the comma is *not* added in any of these situations:

```scala
object Foo {
  Some(1).map(data => {
    data
    data
  })
}
```

```scala
object Foo {
  Some(1).map { data =>
    {
      data
    }
  }
}
```

```scala
object Foo {
  Some(1).map { data =>
    data
  }
}
```

But it is added here:

```scala
object Foo {
  Some(1).map(
    data => //
      data,
  )
}
```

Though in the last case, it makes sense because there could be another argument to `map`. In the original case at the top of the bug, the comma appears inside the `{ }`, which seems like a bug no matter how you slice it (though it does compile). 

Note that, confusingly, you can have a second comma in the place you'd expect (delineating a second possible argument to `map`).

```scala
object Foo {
  Some(1).map(
    data => {
      data, // This comma is bad.
    }, // This comma I understand.
  )
}
```

Scalafmt believes this be formatted and it compiles.

**Comment by adampauls** [comment]
The trailing comma is also added in constructor bodies which, although it compiles, is just really weird and confuses IntelliJ really badly.

```scala
def this() = {
  this(1),
}
```

**Comment by tanishiking** [comment]
Thank you for reporting, let me close this issue for duplication with https://github.com/scalameta/scalafmt/issues/1410

**Comment by adampauls** [comment]
Sorry to be difficult, but #1410 isn't the same issue. That issue is about trailing commas in function argument lists that happen to be of length one. This issue is about commas in curly brace bodies. I think expecting the formatter not to place trailing commas on functions with only one argument is not ideal, because the whole point of trailing commas is that if you add a second argument, you shouldn't have to add that pesky comma to the first.

In these cases above, that does not apply because the trailing comma is being added at the end of a `{ }` expression.

**Comment by tanishiking** [comment]
Ah, I'm so sorry. I misunderstood the problem. It is a different one from https://github.com/scalameta/scalafmt/issues/1410 !

**Comment by adampauls** [comment]
I think the fix is pretty easy, I'll put something up soon!

**Comment by adampauls** [comment]
I put up https://github.com/scalameta/scalafmt/pull/1479.
