### ISSUE TITLE
tput: No value for $TERM and no -T specified

### ISSUE THREAD

**Issue by anilkumarmyla** [scalameta/scalafmt#1477]
## Steps
When I run scalafmt like this:

```bash
sbt scalafmt test:scalafmt
```

## Problem
There is an error `tput: No value for $TERM and no -T specified` that spews in our build systems where there might be no tty

## Expectation
No warning

**Comment by tanishiking** [comment]
Thank you for reporting! Could you elaborate on the environment? (like sbt plugin's version, working environment, hot to reproduce it).

**Comment by anilkumarmyla** [comment]
@tanishiking thank you for getting back, here are the reproduction steps

```
$ unset TERM
$ sbt scalafmt
...
[info] Formatting 1 Scala sources...
tput: No value for $TERM and no -T specified
[success] Total time: 3 s, completed Sep 9, 2019, 3:56:20 PM
```

**Comment by anilkumarmyla** [comment]
might be coming off of https://github.com/scalameta/scalafmt/blob/master/scalafmt-cli/src/main/scala/org/scalafmt/cli/TermDisplay.scala#L33
