### ISSUE TITLE
newlines.alwaysBeforeTopLevelStatements doesn't apply for private defs

### ISSUE THREAD

**Issue by anilkumarmyla** [scalameta/scalafmt#1486]
This template is a guideline, not a strict requirement.
- **Version**: 2.0.1
- **Integration**: IntelliJ
- **Configuration**:
```
version = 2.0.1
continuationIndent.defnSite = 2
newlines.alwaysBeforeTopLevelStatements = true
```

## Steps

Given code like this:
```scala
object Test {
  private val a: String = "a"
  private val b: String = "b"
  private val c: String = "c"
  private def d: String = {
    "d"
  }
  private def e: String = {
    "e"
  }
  private def f: String = {
    "f"
  }
}
```

When I run scalafmt like this:

```bash
sbt scalafmt
```

## Problem

Scalafmt formats code like this:
```scala
object Test {
  private val a: String = "a"
  private val b: String = "b"
  private val c: String = "c"
  private def d: String = {
    "d"
  }
  private def e: String = {
    "e"
  }
  private def f: String = {
    "f"
  }
}
```

## Expectation

I would like the formatted output to look like this:
```scala
object Test {
  private val a: String = "a"
  private val b: String = "b"
  private val c: String = "c"
  
  private def d: String = {
    "d"
  }
  
  private def e: String = {
    "e"
  }
  
  private def f: String = {
    "f"
  }
}
```

## Workaround

I've found that by removing the private modifiers for the defs, code is formatted correctly
```scala
object Test {
  private val a: String = "a"
  private val b: String = "b"
  private val c: String = "c"

  def d: String = {
    "d"
  }

  def e: String = {
    "e"
  }

  def f: String = {
    "f"
  }
}
```

## Notes

Not sure if this is a bug or feature request or the tool working as expected (private defs may not be considered a top level statement?)

**Comment by poslegm** [comment]
I doubt the tool works as expected because formatter ignores all modifiers except annotations.

**Comment by poslegm** [comment]
@anilkumarmyla please try version 2.1.0. It includes fix for this issue.

**Comment by anilkumarmyla** [comment]
@poslegm thanks it works!
