### ISSUE TITLE
How to append to default pattern array?

### ISSUE THREAD

**Issue by anilkumarmyla** [scalameta/scalafmt#1490]
Hello, I'd like to add a pattern to `rewrite.neverInfix.excludeFilters` and I add this in `.scalafmt.conf`
```
rewrite.neverInfix.excludeFilters += "exclude"
```
and apparently that doesn't work as expected as only what is added is considered. So how to append to default pattern array?

**Comment by poslegm** [comment]
There is one way: copy-paste all array from [website](scalameta.org/scalafmt/docs/configuration.html) and add your pattern 😞 

Scalafmt uses https://github.com/olafurpg/metaconfig for HOCON parsing. HOCON has `+=` [operator](https://github.com/lightbend/config/blob/master/HOCON.md#the--field-separator
). If operator works not as expected issue may be in the metaconfig.

**Comment by poslegm** [comment]
This feature already [implemented](https://github.com/scalameta/scalafmt/blob/master/scalafmt-core/shared/src/main/scala/org/scalafmt/config/ScalafmtConfig.scala#L377-L387) for `align.tokens.add`: https://scalameta.org/scalafmt/docs/configuration.html#aligntokensadd

There is a possibility to implement `ConfDecoder[Seq[T]]` with support of `.add` of `+=`. In metaconfig or in scalafmt.
