### ISSUE TITLE
Remove scalafmt-intellij / scalafmt-intellij-plugin

### ISSUE THREAD

**Issue by tanishiking** [scalameta/scalafmt#1498]
Now, scalafmt features had merged into [scala-intellij-plugin](https://github.com/JetBrains/intellij-scala), and we don't need to use `scalafmt-intellij-plugin` for using scalafmt from intellij (right?).
On top of that, unfortunately, scalafmt-intellij is no longer maintained (it doesn't support scalafmt-dynamic feature).
I think it's time to deleting the scalafmt-intellij from the codebase to pursue the maintainability (by removing this, newcomers can compile this project without downloading intellij SDK).

What do you think about this? @olafurpg

**Comment by olafurpg** [comment]
Sounds good to me 👍 Improving the contributor experience is a good enough reason to remove it. People who want to revive the old IntelliJ plugin can always checkout an older commit.
