### ISSUE TITLE
sbt formats code the wrong way upon `compile`, need to run `scalafmtAll` manually to fix

### ISSUE THREAD

**Issue by PiotrJander** [scalameta/scalafmt#1499]
```
version = 2.0.0
```

I have added `scalafmt` to my project by adding

```
addSbtPlugin("org.scalameta" % "sbt-scalafmt" % "2.0.0")
```

to `project/plugins.sbt`.

IntelliJ integration and `sbt scalafmt*` commands work just fine, but upon `sbt compile`, formatting of my code gets broken and I have to run `sbt scalafmtAll` to fix it.

I don't mention `scalafmt` or formatting anywhere in my `build.sbt`

What could be the problem? What other info is needed to diagnose it?

**Comment by poslegm** [comment]
There is only one reason of formatting upon `sbt compile`: `scalafmtOnCompile` setting in `build.sbt`.

Can you please provide minimal `build.sbt` file with which it can be reproduced? Do you have another linter/formatter integrations and project? And code samples before/after `sbt compile` would be very helpful.

**Comment by PiotrJander** [comment]
Turns out I had `scalariform` enabled in `project/plugins.sbt`. Closing.
