### ISSUE TITLE
Allow single line case if it fits on line

### ISSUE THREAD

**Issue by olafurpg** [scalameta/scalafmt#150]
From @lihaoyi on Gitter.

> How is it that sometimes it puts `case (foo, bar) =>` on a new line, and sometimes it doesn't:
> 
> ``` diff
> -        .action { (x, c) => c.copy(file = Some(Path(x, cwd))) }
> +        .action { (x, c) =>
> +          c.copy(file = Some(Path(x, cwd)))
> +        }
> ```
> 
> but
> 
> ``` diff
> -    val reads = paramSymbols.zip(apply.args).map{ case (param, term) =>
> -      val assign = term match{
> -        case q"ammonite.repl.ScriptInit.arg($inner)" =>
> -
> -          val newPrefix = q"ammonite.repl.ScriptInit.parseScriptArg"
> -          q"$newPrefix[${param.typeSignature}](${param.name.decoded}, $inner)"
> -        case x => x // This case should only be for default args, which we leave unchanged
> -      }
> -      assign
> +    val reads = paramSymbols.zip(apply.args).map {
> +      case (param, term) =>
> +        val assign = term match {
> +          case q"ammonite.repl.ScriptInit.arg($inner)" =>
> +            val newPrefix = q"ammonite.repl.ScriptInit.parseScriptArg"
> +            q"$newPrefix[${param.typeSignature}](${param.name.decoded}, $inner)"
> +          case x =>
> +            x // This case should only be for default args, which we leave unchanged
> +        }
> +        assign
>      }
> ```

**Comment by olafurpg** [comment]
For some reason I can't find a solution I'm happy with, I got really deep into issues with the `pruneSlowStates` optimization until I gave. Saving this issue for a later release, 0.2.1 is already useful as it is.

**Comment by tindzk** [comment]
I think the same rule should apply to the `implicit` keyword. An example:

```scala
DOM.render { implicit ctx =>
  ...
}
```

Currently, it gets indented as follows:

```scala
DOM.render {
  implicit ctx =>
    ...
}
```

**Comment by olafurpg** [comment]
Closing as won't fix.

**Comment by ches** [comment]
@olafurpg I thought I recalled seeing a reference to why this is wontfix, maybe it is elsewhere. Was it something hoped that could be addressed through Paiges (or conclusively cannot), or due to Scala 3 potentially not needing the `case` anyway, or something else?

**Comment by olafurpg** [comment]
Mostly closed since I don't think it's worth pursuing with the current implementation. A tree printer with paiges should make it easier to support this desirable output.
