### ISSUE TITLE
would it make sense to allow `implicit` occupy its own line?

### ISSUE THREAD

**Issue by mr-git** [scalameta/scalafmt#1501]
## Steps

https://scalameta.org/scalafmt/docs/configuration.html#verticalmultilinenewlinebeforeimplicitkw provides option to move implicit keyword, like:
```scala
def format(
    code: String,
    age: Int
  )(
    implicit ev: Parser,
    c: Context
  ): String
```

Would it make sense to allow 3 kinds - not move, move to new line, move to own line, like:
```scala
def format(
    code: String,
    age: Int
  )(implicit 
    ev: Parser,
    c: Context
  ): String
```

This way all implicit arguments are kept in order too

**Comment by emanb29** [comment]
See also https://github.com/scalameta/scalafmt/issues/735

**Comment by kitbellew** [comment]
@mr-git wouldn't your desired result be achieved with `newlineBeforeImplicitKW=false` and `newlineAfterImplicitKW=true`?

**Comment by mr-git** [comment]
@kitbellew, sadly enough, it didn't work.
And correct config is:
```
verticalMultiline.newlineBeforeImplicitKW=false
verticalMultiline.newlineAfterImplicitKW=true
```

**Comment by mr-git** [comment]
I tried from #735:
```
newlines.beforeImplicitKWInVerticalMultiline = true
newlines.afterImplicitKWInVerticalMultiline = true
```
It didn't work either

**Comment by kitbellew** [comment]
> @kitbellew, sadly enough, it didn't work.

then what exactly are you expecting? in my tests, when the signature doesn't fit on a single line, it gets formatted across multiple lines exactly as you suggested.

here are some examples from the tests: https://github.com/scalameta/scalafmt/blob/489a2b5617d697360a6c0fb6c85d5914774674ec/scalafmt-tests/src/test/resources/vertical-multiline/afterImplicitKW.stat

> And correct config is:
> ```
> verticalMultiline.newlineBeforeImplicitKW=false
> verticalMultiline.newlineAfterImplicitKW=true
> ```

yes, that was implicit.

**Comment by mr-git** [comment]
```
verticalMultiline = {
  atDefnSite = true
  newlineAfterImplicitKW = true
}
```
With config like above, I managed to get code formatted like:
```scala
  def of[F[_]](
    g: G,
  )(implicit
    timer: TImer[F],
    contextShift: ContextShift[F],
  ): F[ExitCode] = {
```

Thank you!
