### ISSUE TITLE
Scalafmt Reformats Valid Code to Code that is Invalid on Dotty

### ISSUE THREAD

**Issue by adamgfraser** [scalameta/scalafmt#1509]
With the changes in the latest version of Dotty regarding indentation and control structures we are seeing code that would be valid in 2.13 and Dotty reformatted to code that is still legal under 2.13 but not under Dotty. Minimized example below shows code that will compile under Dotty and will not compile. With our scalafmt settings the first is rewritten to the second, which is particularly problematic. Is there something we can change in our settings to prevent this? Is there a way we can go the other way, and get scalafmt to rewrite the second version to the first version, or automatically put braces around the first clause of the `if` statement?

I have included our settings below.

```scala
object Example {

  val okay =
    if (true)
      List(1, 2, 3) match {
        case x :: xs => ???
        case Nil => ???
      }
    else {
      2
    }

  val notOkay = 
    if (true)
      List(1, 2, 3) match {
        case x :: xs => ???
        case Nil => ???
    } else {
      2
    }
}
```

```
version = "2.0.1"
maxColumn = 120
align = most
continuationIndent.defnSite = 2
assumeStandardLibraryStripMargin = true
docstrings = JavaDoc
lineEndings = preserve
includeCurlyBraceInSelectChains = false
danglingParentheses = true
spaces {
  inImportCurlyBraces = true
}
optIn.annotationNewlines = true

rewrite.rules = [SortImports, RedundantBraces]
```

**Comment by ekrich** [comment]
I ran across this same thing but only we the latest `0.19.0-RC1` - prior versions worked.
```Scala
sbt:sconfig-root> sconfigJVM/test
[info] Compiling 104 Scala sources and 1 Java source to /Users/eric/workspace/sconfig/sconfig/jvm/target/scala-0.19/classes ...
[error] -- Error: /Users/eric/workspace/sconfig/sconfig/shared/src/main/scala/org/ekrich/config/impl/PropertiesParser.scala:144:10 
[error] 144 |        } else
[error]     |          ^^^^
[error]     |          end of statement expected but else found
[error] -- [E040] Syntax Error: /Users/eric/workspace/sconfig/sconfig/shared/src/main/scala/org/ekrich/config/impl/PropertiesParser.scala:145:8 
[error] 145 |        value = ConfigImpl.fromAnyRef(pathMap.get(path),
[error]     |        ^^^^^
[error]     |        ';' expected, but identifier found
```

**Comment by ekrich** [comment]
I really think this should work given the error.
```Scala
  val notOkay = 
    if (true)
      List(1, 2, 3) match {
        case x :: xs => ???
        case Nil => ???
    }; else {
      2
    }
```

**Comment by adamgfraser** [comment]
I can confirm that we only observed the issue after upgrading to `0.19.0-RC1`. I reached out to the Dotty team and they confirmed that they view this code as improperly indented and from their perspective failing to compile is the expected behavior. So it would be really nice to have options in `scalafmt` to avoid rewriting valid code to invalid code and ideally go the other way.

**Comment by olafurpg** [comment]
Thank you for reporting! Opened a PR with a fix https://github.com/scalameta/scalafmt/pull/1520

**Comment by ekrich** [comment]
@olafurpg Thank you kind sir! That will help a bunch of folks.
