### ISSUE TITLE
Unable to set align configuration as wanted

### ISSUE THREAD

**Issue by spi-x-i** [scalameta/scalafmt#1512]
Hello dear Community,
I'd like to customize my code format but I am not able to properly set the `.scalafmt.conf` to make the format work.

- **Version**: 2.0.5 
- **Scala version**: 2.11.12
- **sbt version**: 1.3.2
- **Integration**: sbt
- **Configuration**:
```
version=2.0.0
# style = defaultWithAlign
maxColumn = 120
newlines.alwaysBeforeTopLevelStatements = true
align.openParenCallSite = true
align.openParenDefnSite = true
```

## Steps

Given code like this:
```scala
noException should be thrownBy ClosureCleaner.clean(
  AggregateByKey.copipeline(configurationManager),
  checkSerializable = true
)
```

When I run scalafmt like this:

```bash
sbt:my-project> scalafmt
```

## Problem

Scalafmt formats code like this:
```scala
noException should be thrownBy ClosureCleaner.clean(
  AggregateByKey.copipeline(configurationManager),
  checkSerializable = true
)
```

## Expectation

I would like the formatted output to look like this:
```scala
noException should be thrownBy ClosureCleaner.clean(AggregateByKey.copipeline(config),
                                                    checkSerializable = true)
```

## Notes
I would expect that my configuration works as far as I understood the documentation. 
Thank you in advance for your help.

Andrea

**Comment by poslegm** [comment]
Hmm, `openParenCallSite` works really weird. I got expected result from formatter only if original code is 
```scala
noException should be thrownBy ClosureCleaner.clean(AggregateByKey.copipeline(config), checkSerializable = true)
```

If user adds newlines between arguments manually alignment will not happen.

I don't understand is it bug or very strange feature.

cc @tanishiking @olafurpg

**Comment by kitbellew** [comment]
it works correctly; this example clashes with config style argument formatting.

please do one of these:
* set `optIn.configStyleArguments = false`, or
* remove newline after `(` or before `)`
