### ISSUE TITLE
newlines.alwaysBeforeTopLevelStatements=false documentation doesn't seem to do anything

### ISSUE THREAD

**Issue by jsoref** [scalameta/scalafmt#1517]
This template is a guideline, not a strict requirement.
- **Version**: 0.5
- **Integration**: 
- **Configuration**:
```
version = 2.1.0
maxColumn = 100
```

## Steps

Visit
https://scalameta.org/scalafmt/docs/configuration.html#newlinesalwaysbeforetoplevelstatements

Click the pretty "Show original" and "Show formatted" buttons to try to figure out what the thing does. Actual result, see no change.

I cloned the repo @ ba6ebc3d40fe04debb97a2425c01a753abbca7e8, built, and self hosted to play w/ the docs to see if I could figure out what it's doing.

(You can copy the example from the docs, but it wasn't terribly helpful in figuring out what might be going on, so I'm borrowing from #1486 because at least I could almost get a sense of maybe something should probably happen.)

Given code like this:

```scala
object Test {
  private val a: String = "a"
  private val b: String = "b"

  private val c: String = "c"
  private def d: String = {
    "d"
  }

  private def e: String = {
    "e"
  }
  private def f: String = {
    "f"
  }
}
```

`scalafmt.conf.false`:

```
newlines.alwaysBeforeTopLevelStatements = false
maxColumn = 100
```

there's also a `scalafmt.conf.true`:

```
newlines.alwaysBeforeTopLevelStatements = true
maxColumn = 100
```

When I run scalafmt like this:

```bash
for a in true false; do
  cp test.scala.orig test.scala;
  scalafmt -i -f test.scala --config scalafmt.conf.$a ;

  echo $a;
  diff -u test.scala.orig test.scala;
done
```

## Problem

Scalafmt formats code like this:
exactly the same as input.
## Expectation

I would like the formatted output to be different from its input, because, the configuration should probably do something.

## Workaround

I've found that by... filing issues in github people will fix the documentation or implementation.

## Notes

I can't figure out what this is supposed to do. If I could figure out what's supposed to happen, or how to give sample input showing a change, I'd happily provide a PR to the docs, but, I can't see any change.

**Comment by jsoref** [comment]
Doesn't change anything for me. You should also be able to see what I'm describing by clicking the button on the website... I can provide a video, but that seems pretty silly.

**Comment by kitbellew** [comment]
@jsoref this parameter (or its 2.5.0 replacement, `topLevelStatements=[before,after]`) doesn't _remove_ blank lines. therefore, the `false` example simply demonstrates that there are not blank lines *added*.

as to whether blank lines should be removed in such cases is a matter of discussion. @poslegm, @olafurpg, do you have an opinion?

**Comment by jsoref** [comment]
@kitbellew: Ok, that's enough information for someone to update the documentation explaining what it does/doesn't do. If you want, I could probably document that. (I'm on vacation now and don't really intend to do such things during my vacation, but...)
