### ISSUE TITLE
Complete configs documentation

### ISSUE THREAD

**Issue by poslegm** [scalameta/scalafmt#1523]
I was a witness and participant of scalafmt adoption into a few large codebases and it always caused the developers to study the scalafmt sources for optimal configuration selection. In my opinion software should not force users to read source code (even if users is programmers).

In my sweet dreams [configuration](https://scalameta.org/scalafmt/docs/configuration.html) page in docs contains examples for _all_ available options from `.scalafmt.conf`.

I propose two things:
1. Step-by-step increase documentation coverage for scalafmt settings
2. Don't merge PRs with new features without documentation

Are there any reasons why we shouldn't do this?

**Comment by tanishiking** [comment]
It must be a good idea to increase the documentation coverage. 👍 

If we add a lot of examples, we may want to decide "recommended / popular" configs and "minor" configs so that users don't need to consider too much about which ones should they configure.

**Comment by olafurpg** [comment]
The undocumented configuration options are intentionally not documented since they are usually not well tested or supported. Maybe we should remove the undocumented settings from the source code rather than adding them to the website 😅

**Comment by kitbellew** [comment]
@poslegm anything still missing in documentation?

**Comment by poslegm** [comment]
I think that all notable features are documented now. So, this issue can be closed.

Documentation quality increased a lot over the past year
