### ISSUE TITLE
Different configuration for scala and sbt files

### ISSUE THREAD

**Issue by limansky** [scalameta/scalafmt#1534]
Hi,

 As a user I'd like to have ability to set different rules for different files. For example I'd lke to have alignment for `%` and `%%` in build.sbt, but I definitely don't want to align by `%` in my Scala code. For example, this doesn't make any sense:

```
   def baseTimeList(fromTime: Long, toTime: Long, table: Table) = {
     val startBaseTime = fromTime - (fromTime % table.rowTimeSpan)
     val stopBaseTime = toTime - (toTime      % table.rowTimeSpan)
     startBaseTime to stopBaseTime by table.rowTimeSpan
   }
```

I have following `aling.tokens` value:

```
align.tokens = [
  {code = "=>", owner = "Case"},
  {code = "%", owner = "Term.ApplyInfix"},
  {code = "%%", owner = "Term.ApplyInfix"}
]
```

**Comment by poslegm** [comment]
I've already thought about it. It's really the right feature for sbt configs alignment.

**Comment by poslegm** [comment]
Current workaround: just override scalafmt config inside file like [here]( https://github.com/scalameta/scalafmt/blob/master/project/Dependencies.scala#L5)

**Comment by poslegm** [comment]
@limansky please let us know if config overriding is not enough for this issue solution.

**Comment by poslegm** [comment]
Configs overriding documented on top of "Configuration" section: https://scalameta.org/scalafmt/docs/configuration.html

**Comment by limansky** [comment]
Hi  @poslegm. I've added the line to build.sbt:

```
// scalafmt: { alignTokens = [ {code = "%", owner = "Term.ApplyInfix"}, {code = "%%", owner = "Term.ApplyInfix"} ] }
```

It seems like scalafmt ignore it.

**Comment by poslegm** [comment]
What about 
```
// scalafmt: { align.tokens = [ {code = "%", owner = "Term.ApplyInfix"}, {code = "%%", owner = "Term.ApplyInfix"} ] }
```
?

**Comment by limansky** [comment]
Works like a charm! Thanks!

The only thing, I don't like in this solution is that if I have multiple sbt files, I have to add this line to each of them.

**Comment by limansky** [comment]
Another issue I observed (not related to this issue directly) is that scalafmt organize group name, artifact name and version in columns, but doesn't do it for the scope, e.g:

```
    libraryDependencies ++= Seq(
      "joda-time"      % "joda-time"   % versions.joda,
      "org.scalatest"  %% "scalatest"  % versions.scalaTest % Test,
      "org.scalacheck" %% "scalacheck" % versions.scalaCheck % Test
    )
```

**Comment by poslegm** [comment]
@limansky issue created https://github.com/scalameta/scalafmt/issues/1783
