### ISSUE TITLE
2.2.0 regression - extra space in super-constructor second argument list

### ISSUE THREAD

**Issue by neko-kai** [scalameta/scalafmt#1536]
```
version = 2.2.0
```

## Steps

Code formatted with scalafmt version `2.0.1` (no configuration, just `version = 2.0.1`):

```scala  
final class Dummy[F[+_, +_]: BIOApplicative]
      extends DIResource.Make_[F[Nothing, ?], Component[F]](
        acquire = Ref(Map.empty[Key, Item]).map(new Dummy.Impl(_))
      )(release = F.unit)
```

But, scalafmt version `2.2.0` formats the same code like this:

```scala
final class Dummy[F[+_, +_]: BIOApplicative]
      extends DIResource.Make_[F[Nothing, ?], Component[F]](
        acquire = Ref(Map.empty[Key, Item]).map(new Dummy.Impl(_))
      ) (release = F.unit)
```

## Problem

There's an additional space before the second parameter list in:

```scala
      ) (release = F.unit)
```

This space just appeared when upgrading versions, there doesn't seem to be a configuration to control it.

## Workaround

None so far

**Comment by poslegm** [comment]
Already fixed in https://github.com/scalameta/scalafmt/pull/1535. Try to update to 2.1.1, please

**Comment by neko-kai** [comment]
@poslegm Version `2.2.1` works :+1:
