### ISSUE TITLE
Automatically reformatting when IntelliJ reformat settings are disabled

### ISSUE THREAD

**Issue by lwilli** [scalameta/scalafmt#1538]
- **Version**: 1.5.1
- **Integration**: IntelliJ IDEA 2019.2.3 (Community Edition) Build #IC-192.6817.14
- **Configuration**:
```
version = "1.5.1"
maxColumn = 120
rewrite.rules = [SortImports,SortModifiers,PreferCurlyFors]
align.openParenCallSite = false
newlines.alwaysBeforeTopLevelStatements = true
newlines.alwaysBeforeElseAfterCurlyIf = true```

## Steps

Given code like this with an improperly new-lined/indented method argument:
```scala
class TestBug {

  def testFormatBugMethod(
       incorrectlyIndentedArg: Option[String]): Set[String] = {
    Set(someArgument.getOrElse(""))
  }
}
```

When I switch to another program other than IntelliJ...

## Problem

Scalafmt formats code like this:
```scala
class TestBug {

  def testFormatBugMethod(someArgument: Option[String]): Set[String] = {
    Set(someArgument.getOrElse(""))
  }
}
```

## Expectation

Although this is the correct formatting, scalafmt should not be reformatting code automatically when I have `Preferences | Editor | Code Style | Scala > Scalafmt > Reformat on file save` disabled and `Preferences | Editor | Code Style | Scala > Other > Reformat on compile` disabled.

## Workaround

I've found that by disabling the IntelliJ scalafmt plugin solves this problem.

## Notes

Also submitted an IntelliJ issue: https://youtrack.jetbrains.com/issue/SCL-16449

**Comment by tanishiking** [comment]
@lwilli  Thank you for reporting (and submitting it to the intellij issue tracker)!

As Andrey Sugak said, removing scalafmt intellij plugin would help you because scalafmt support has moved to intellij-scala-plugin https://blog.jetbrains.com/scala/2019/03/27/intellij-scala-plugin-2019-1-highlighting-for-comprehensions-find-usages-for-implicits-and-more/#scalafmt

> @Logan Williams you should probably disable standalone scalafmt plugin, scalafmt support has since moved to the scala-plugin itself
> https://youtrack.jetbrains.com/issue/SCL-16449#focus=streamItem-27-3750258.0-0

**Comment by lwilli** [comment]
Yes, the feedback from Andrey on the other ticket solved my problem! I didn't realize `scalafmt` was supported within the regular scala plugin now. Removing the `scalafmt` standalone plugin seems to have solved the issue. Thank you @tanishiking!
