### ISSUE TITLE
verticalMultiline disables optIn.configStyleArguments

### ISSUE THREAD

**Issue by neko-kai** [scalameta/scalafmt#1539]
- **Version**: 2.2.1
- **Integration**: IntelliJ
- **Configuration**:
```
version = 2.2.1
maxColumn = 100

verticalMultiline.atDefnSite = true
optIn.configStyleArguments = true
```

## Steps

Given code like this:
```scala
class Abc(
  x: Int, 
  b: Int
)
```

## Problem

With `verticalMultiline.atDefnSite = true` scalafmt formats code like this:
```scala
class Abc(x: Int, b: Int)
```
i.e. the `optIn.configStyleArguments=true` option is ignored - the config list is not preserved on re-format.

## Expectation

However, if verticalMultiline is disabled with `verticalMultiline.atDefnSite = true`, the output is:
```scala
class Abc(
  x: Int,
  b: Int
)
```
`optIn.configStyleArguments=true` works again – the config list is not squashed into one line despite being smaller than `maxColumn`

## Workaround

None

**Comment by kitbellew** [comment]
@neko-kai vertical multiline, apparently, intends to fully control formatting regardless of source newlines.

given this, what would you expect to happen? what's the *identical* way it should format both
```
  class A(b, c)
  class D(
    e,
    f
  )
```

you can change its parameters to mimic config style, by reducing arity to 2, setting the flag to break after the opening parenthesis and, in this case, removing class from their exclusion list for f dangling closing parenthesis.

**Comment by neko-kai** [comment]
@kitbellew 
> @neko-kai vertical multiline, apparently, intends to fully control formatting regardless of source newlines.
> given this, what would you expect to happen? what's the identical way it should format both

Clearly this is unsolvable because I want these two to be *non-identical*, i.e. I'm turning on the `optIn` option to control what to break into multi-line and what to keep horizontal. For verticalMultiline that would mean that if the braces are already on separate lines (config-style) it can no longer reformat them back to horizontal and must assume minimal arity threshold for that section.

**Comment by kitbellew** [comment]
> Clearly this is unsolvable because I want these two to be _non-identical_, i.e. I'm turning on the `optIn` option to control what to break into multi-line and what to keep horizontal. For verticalMultiline that would mean that if the braces are already on separate lines (config-style) it can no longer reformat them back to horizontal and must assume minimal arity threshold for that section.

if i may ask, why do you want to use vertical multiline if you'd like to control line breaks? is something missing in the non-vertical-multiline mode?

**Comment by neko-kai** [comment]
@kitbellew 
Yes, multiple parameter lists in config-style force an empty line just for braces:

```scala
def myMethod(
  arg1: Arg1,
  arg2: Arg2,
)(
  arg3: Arg3,
  arg4: Arg4,
)(
  arg5: Arg5,
  arg6: Arg6,
): Unit = ()
```

vs. verticalMultiline's compact formatting:

```scala
def myMethod(
    arg1: Arg1,
    arg2: Arg2,
  )(arg3: Arg3,
    arg4: Arg4,
  )(arg5: Arg5,
    arg6: Arg6,
  ): Unit = ()
```
