### ISSUE TITLE
In some cases lines exceed `maxColumn` after formatting

### ISSUE THREAD

**Issue by sisidra** [scalameta/scalafmt#1543]
This template is a guideline, not a strict requirement.
- **Version**: 2.0.6
- **Integration**: IntelliJ
- **Configuration**:
```
version = "2.0.0"
maxColumn = 30
```

## Steps

Given code like this:
```scala
case class LongLines(
    field1: String,
    field2: String
)

object LongLines {
  LongLines(
    field1 = "123456789012345",
    field2 = ""
  )
}
```

When I run scalafmt like this:

`Opt` + `Cmd` + `L`

## Problem

Scalafmt formats code like this:
```scala
case class LongLines(
    field1: String,
    field2: String
)

object LongLines {
  LongLines(
    field1 = "123456789012345",
    field2 = ""
  )
}
```

## Expectation

I would like the formatted output to look like this:
```scala
case class LongLines(
    field1: String,
    field2: String
)

object LongLines {
  LongLines(
    field1 =
      "123456789012345",
    field2 = ""
  )
}
```

## Workaround

None, except reorganize code (extract variables and similar) to avoid this cornercase.

**Comment by poslegm** [comment]
### Note

In code sample longest line length is 31. Scalafmt adds line break if there is 32 symbols in line. Maybe formatter ignores the comma at the end.

```
> scalafmt --config-str="maxColumn=30" --stdin
object LongLines {
  LongLines(
    field1 = "1234567890123451",
    field2 = ""
  )
}
object LongLines {
  LongLines(
    field1 =
      "1234567890123451",
    field2 = ""
  )
}
```
