### ISSUE TITLE
formatting check issue for code with comments

### ISSUE THREAD

**Issue by mr-git** [scalameta/scalafmt#1550]
This template is a guideline, not a strict requirement.
- **Version**: `"org.scalameta" % "sbt-scalafmt" % "2.0.6"`
- **Integration**: IntelliJ
- **Configuration**:
```
version = 2.1.0
maxColumn = 120
align = none
continuationIndent {
  callSite = 2
  defnSite = 2
}
rewrite.rules = [
  RedundantBraces, RedundantParens, SortModifiers, prefercurlyfors
]
```

## Steps

Given code like this:
```scala
CaseClass(
  id: "id", // comment about a field, like TODO: fix this issue
)
```

When I run scalafmt like this:

```sbt
scalafmtCheck
```

## Problem

Scalafmt complains about :
```text
Parse error: <input>:52: error: illegal start of simple expression ) ^
```

## Expectation

Comments on last line for case class instance creation and trailing comma and `)` on next line do not generate parsing errors

## Workaround

I've found that by removing comment so that it is before field, instead of "at end of line", parsing succeeds

**Comment by poslegm** [comment]
I can't reproduce it. Are you sure that described configuration and code sample are enough for bug reproducing?

**Comment by mr-git** [comment]
hm.. I am using it only in IDEA... maybe it is a bug on JetBrains side? let me try to create minimal example project

**Comment by poslegm** [comment]
I can't reproduce it in Intellij IDEA too.

Also, there is syntax error in your code sample:

```scala
// bad
CaseClass(
  id: "id", // comment about a field, like TODO: fix this issue
)
// good
CaseClass(
  id = "id", // comment about a field, like TODO: fix this issue
)
```

**Comment by mr-git** [comment]
indeed, `:` for `=`

**Comment by mr-git** [comment]
sadly, in small project with one file
```scala
object Main extends App {
  val a = A(
    id = "id", // xxx
  )
}

case class A(
  id: String
)
```

there is no issue reported by IDEA, though `sbt scalafmtCheck` reports:
```text
[warn] /Users/.../git/tmp/A.scala isn't formatted properly!
```

what I found is that if I leave trailing comma, then `scalafmtCheck` complains about not formatted properly. 
running `sbt scalafmt` removes the comma.
adding `trailingCommas = always` to config allows them.

all works fine in this small project, but in larger project it is impossible to use `trailingCommas = always` - IDEA complains `Invalid fields: trailingCommas`, which makes me think that there is something else left behind in my larger project, which I cannot find, possibly IDEA has some leftovers from previous plugin somewhere in local working directory or similar.

must be IDEA issue and/or config issue in my bigger project :(

thank you for looking into it!

**Comment by mr-git** [comment]
upgraded larger project to `version = 2.2.2` - `trailingCommas` works now and there are no more issues with strange parsing error about trailing `)` on new-line with comments on end of previous line.

must have been compatibility issue between IDEA plugin and config file.

**Comment by mr-git** [comment]
sadly, when using commands from sbt - all is fine, but when IDEA starts to format/parse code - errors are back... I will live with them, for now :/

**Comment by tanishiking** [comment]
@mr-git Probably, are you using an old version of the intellij-scalafmt plugin (maybe 1.5.1)?
That plugin is no longer maintained. Please use the `intellij-scala` plugin (that supports the formatting feature based on scalafmt) instead.
https://scalameta.org/scalafmt/docs/installation.html#intellij

I think removing old intellij-scalafmt plugin will fix it :)

**Comment by mr-git** [comment]
@tanishiking, thank you!
Indeed I have that old plugin installed, removing it makes all work as expected.
