### ISSUE TITLE
Changelog on homepage not updated

### ISSUE THREAD

**Issue by ahockersten** [scalameta/scalafmt#1558]
The changelog on the homepage (https://scalameta.org/scalafmt/docs/changelog.html) lists the latest version as 2.0.1, while the latest version available for download is actually 2.2.2.

Similarly, on the installation page (https://scalameta.org/scalafmt/docs/installation.html) the instruction to install via sbt might cause you to add the older 2.2.0 due to this line:
```
// In project/plugins.sbt. Note, does not support sbt 0.13, only sbt 1.x.
addSbtPlugin("org.scalameta" % "sbt-scalafmt" % "2.2.0")
```

This might seem relatively minor, but I had a discrepancy between the locally installed version of scalafmt and the version intellij was using that took me a while to figure out due to this.

**Comment by poslegm** [comment]
Changelog and versions update on website is not automated :(

I updated it, thank you for your attention!
