### ISSUE TITLE
Allow setting newlines at EOF to false.

### ISSUE THREAD

**Issue by bruno-medeiros** [scalameta/scalafmt#1605]
I don't really care that some old fashioned Unix tools required newlines at end of file, I'd like a setting that would remove them please.

**Comment by poslegm** [comment]
I think it will be reasonable to have config for it

**Comment by olafurpg** [comment]
Thank you for reporting! I’m on the fence about introducing a new configuration option for this feature. Is there a reason the newline at the end of the file is causing issues?

**Comment by bruno-medeiros** [comment]
It is not causing any issues per se. It is just for aesthetics: ie, one less scroll line, and also having the editor cursor going after the final '}' in the file when one presses Ctrl+End or so. (as opposed to the line below the `}`). I understand these are subjective preferences :)

**Comment by olafurpg** [comment]
Closing as wontfix since newlines at the end-of-file is a widely used convention in the programming community.
