### ISSUE TITLE
Intellij is unable to resolve older scalafmt versions

### ISSUE THREAD

**Issue by eatkins** [scalameta/scalafmt#1630]
- **Version**: 2.2.1
- **Integration**: IntelliJ
- **Configuration**:
```
version = 2.2.1
maxColumn = 100
project.git = true
project.excludeFilters = [ "\\Wsbt-test\\W", "\\Winput_sources\\W", "\\Wcontraband-scala\\W" ]

# http://docs.scala-lang.org/style/scaladoc.html recommends the JavaDoc style.
# scala/scala is written that way too https://github.com/scala/scala/blob/v2.12.2/src/library/scala/Predef.scala
docstrings = JavaDoc

# This also seems more idiomatic to include whitespace in import x.{ yyy }
spaces.inImportCurlyBraces = true

# This is more idiomatic Scala.
# http://docs.scala-lang.org/style/indentation.html#methods-with-numerous-arguments
align.openParenCallSite = false
align.openParenDefnSite = false

# For better code clarity
danglingParentheses = true

trailingCommas = preserve
```

## Steps

Set intellij to autoformat on save.
## Problem

Intellij is unable to resolve scalafmt to 2.2.1 so no formatting on save occurs.

## Expectation

Intellij should correctly resolve scalafmt 2.2.1

## Workaround

If I bump the version to 2.3.1, then intellij resolves it fine. Unfortunately, this creates many format changes in the sbt project (where I noticed the issue). It is annoying for my local development that I have to upgrade scalafmt, generate a huge diff, check it in, keep working on my feature and when I'm done revert the scalafmt diff.

## Notes
The no formatting is especially annoying with intellij because sbt has scalafmtOnCompile set to true (I know...) so the file ends up being changed out from underneath intellij if any formatting is done.

Also, I've noticed this behavior since early in the 2.x series. It seems like intelij will almost always be ok resolving the latest scalafmt versions but not always the older ones.

**Comment by olafurpg** [comment]
Thank you for reporting! The IntelliJ integration is maintained by the Scala plugin team at JetBrains. Have you reported a ticket on YouTrack? I don’t think there is much we can do about this on the Scalafmt side.

**Comment by eatkins** [comment]
Ok. I'm guessing the scalafmt plugin for intellij is using an old version of scalafmt that uses the legacy vendored coursier to resolve the scalafmt artifacts. I'll report an issue there.
