### ISSUE TITLE
Migrate from Travis CI to Github Actions

### ISSUE THREAD

**Issue by poslegm** [scalameta/scalafmt#1632]
We already have native images pipeline in Github Actions. It might make sense to move the rest jobs to Actions for unified CI system.

**Comment by olafurpg** [comment]
This is a good idea. In Metals we still run the publish jobs from Travis because it’s already working and migrating requires updating secrets. I’m fine if we do the same partial migration in Scalafmt, only move test jobs and keep release jobs on Travis
