### ISSUE TITLE
Please support the newest dotty syntax

### ISSUE THREAD

**Issue by blueway** [scalameta/scalafmt#1638]
This template is a guideline, not a strict requirement.
- **Version**: 0.5
- **Integration**: IntelliJ
- **Configuration**:
```
version = 2.0.1
maxColumn = 100
```

## Steps

Given code like this:
```scala
ORIGINAL CODE
```

When I run scalafmt like this:

```bash
scalafmt
```

## Problem

Scalafmt formats code like this:
```scala
//dotty : 0.21.0-rc1
error: identifier expected but ( found
def (xs: Seq[String]) longestStrings = {
```

## Expectation

I would like the formatted output to look like this:
```scala
EXPECTED FORMATTING OUTPUT
```

## Workaround

```

## Notes

See also..

**Comment by kitbellew** [comment]
@blueway have you tried setting `runner.dialect = dotty`?

**Comment by kitbellew** [comment]
superseded by #2216.
