### ISSUE TITLE
Please allow to disable rules

### ISSUE THREAD

**Issue by msilvestre** [scalameta/scalafmt#1643]
- **Configuration**:
```
version = 2.0.1
maxColumn = 100
ontinuationIndent.defnSite = disable
```

## Steps

Given code like this:
```scala
class StreamProcessing(val inputTopic: String,
                       val outputTopic: String,
                       val inputSerialization: String,
                       val outputSerialization: String) {
```

When I run scalafmt:

## Problem

Scalafmt formats code like this:
```scala
class StreamProcessing(
    val inputTopic: String,
    val outputTopic: String,
    val inputSerialization: 
    val outputSerialization: String) {
```

## Expectation

I would like the formatted output to look like this:
```scala
class StreamProcessing(val inputTopic: String,
                       val outputTopic: String,
                       val inputSerialization: String,
                       val outputSerialization: String) {
```

## Notes

Even better is a configuration that allows scalafmt to indent it like it. 
But disabling rules is a must have feature in my opinian

Thanks!

**Comment by poslegm** [comment]
Scalafmt already has config for it: `align.openParenDefnSite = true`. See https://scalameta.org/scalafmt/docs/configuration.html#alignopenparendefnsite

**Comment by msilvestre** [comment]
Awesome!!!! 

Sorry for the ticket.
