### ISSUE TITLE
CLI: ignore most common typical generated files consistent to SBT integration

### ISSUE THREAD

**Issue by mroth** [scalameta/scalafmt#1644]
This template is a guideline, not a strict requirement.
- **Version**: 2.3.2
- **Integration**: CLI
- **Configuration**: N/A (any)

## Steps

1. Run `scalafmt` binary from the CLI in a typical Scala project workspace.
2. Bombs/errors abound from generated files in `target` directories.

## Problem

Way back in #429 this was fixed by default, but that appears to have only been addressed for running via the SBT integration.

As direct CLI usage is becoming more common (especially with the native binary releases), this presents a confusing first usage scenario for a typical CLI user.

## Expectation

Should the CLI behavior be changed to essentially include a `project.excludeFilters` of `["target/"]` in a default invocation? My assumption as a user/developer is that invoking the CLI binary in a typical Scala project structure would ignore the most common build/generated destinations without requiring additional user configuration.

**Comment by poslegm** [comment]
`^target/.*` regex may be reasonable in [default filters](https://github.com/scalameta/scalafmt/blob/fadab3012f9cb01d119270e6459f2a65ca885e55/scalafmt-core/shared/src/main/scala/org/scalafmt/config/ProjectFiles.scala#L11).

**Comment by poslegm** [comment]
@olafurpg what do you think?

**Comment by olafurpg** [comment]
Fine with me, we could also include `.metals/readonly`

**Comment by olafurpg** [comment]
My reservation with this change is that users overwrite the defaults if they start tweaking the excludes. I think it might be better to change the default value to `project.git=true` if there exists a `.git/` directory 🤔

**Comment by poslegm** [comment]
related issue #1526

**Comment by poslegm** [comment]
You are right. `project.git = true` by default should solve problem for most use cases.

[Config reads here](https://github.com/scalameta/scalafmt/blob/84376adb3aa10410932ccba9bac39f2365f3d01b/scalafmt-cli/src/main/scala/org/scalafmt/cli/CliOptions.scala#L228)

Also we have `git` [field](https://github.com/scalameta/scalafmt/blob/a90ca60f778c48fd1fd13c312500c5a4b2f16a3c/scalafmt-core/shared/src/main/scala/org/scalafmt/config/ProjectFiles.scala#L7) in the `ProjectFiles` class. It's never used and project builds successfully without it. What is the purpose of it?

**Comment by kitbellew** [comment]
@olafurpg @poslegm what about a new flag `project.excludeCommonArtefacts` or something like that? applicable if `git = false`.

**Comment by olafurpg** [comment]
@kitbellew i think that would defeat the purpose of improving the default behavior. I don’t like excluding a hard coded set of patterns like “target/“. I think it’s best to nudge more users towards enabling the “git = true” setting.

**Comment by kitbellew** [comment]
then should we close this issue as there isn't anything left to do? :)

p.s. poor users of perforce or mercurial...

**Comment by olafurpg** [comment]
It should be easy to add support for perforce or mercurial similar to how we currently shell out to “git ls-files”. I don’t think it’s unreasonable that those users need to manually register what directories to exclude if they don’t want Scalafmt to touch generated code.
