### ISSUE TITLE
Scalafmt Fails to Format Scala Sources in Play Project

### ISSUE THREAD

**Issue by co-category** [scalameta/scalafmt#1645]
This template is a guideline, not a strict requirement.
- **Version**: 2.3.2
- **Integration**: Intellij / VS Code
- **Configuration**:
```
version=2.3.2
style = defaultWithAlign
maxColumn = 120
lineEndings = unix
importSelectors = singleLine

project {
  git = true
}

align = most

align {
  tokens = [ {code = "=>", owner = "Case|Type.Arg.ByName"}, "=", "<-", "->", "%", "%%", "should", "shouldBe", "must" ]
  arrowEnumeratorGenerator = true
  openParenCallSite = false
  openParenDefnSite = false
}

binPack {
  parentConstructors = false
}

continuationIndent {
  callSite = 2
  defnSite = 2
}

newlines {
  penalizeSingleSelectMultiArgList = false
  sometimesBeforeColonInMethodReturnType = true
}

rewrite {
  rules = [RedundantBraces, RedundantParens, AsciiSortImports]
  redundantBraces {
    maxLines = 100
    includeUnitMethods = true
    stringInterpolation = true
  }
}

spaces {
  beforeContextBoundColon = true
  inImportCurlyBraces = false
  beforeContextBoundColon = false
}

project.excludeFilters = [
  ".*\\.sc"
]
```

## Steps

Given code like this:
```scala
ORIGINAL CODE
```

When I run scalafmt like this:

```bash
scalafmt
```

## Problem

Scalafmt formats does not format this code accordingly:
```scala
case class Test(
            f : Int,
    d : Int
)
```

## Expectation

I would like the formatted output to look like this:
```scala
case class Test(
    f : Int,
    d : Int
)
```

## Notes
You can download this repo: https://github.com/hmrc/cgt-property-disposals-frontend to reproduce the bug. Create any case class in the models folder with incorrect format, open a sbt session, and compile the sources. Even though scalamfmtOnCompile is set to true and you can see in the logs that it has formatted some files, it fails to format the case class you have created.

**Comment by poslegm** [comment]
Hello!

The problem in the excludeFilters regex: it matches **all** Scala files. I think it is a bug in the scalafmt: we need to add `$` at the filter string end. Before we fix it you can to add `$` to the filters manually:

```
project.excludeFilters = [
  ".*\\.sc"
]
```

**Comment by poslegm** [comment]
See discussion in #1646 

#### Workaround
Manually add `$` at the end of exclude filter.

#### General solution
1. Implement `FilterGlobMatcher` as an alternative for [FilterMatcher](https://github.com/scalameta/scalafmt/blob/c92153e777984db6d69ec359dd1b1115bd2199d6/scalafmt-core/shared/src/main/scala/org/scalafmt/config/FilterMatcher.scala#L7)
2. Replace `exclude`/`include` in the documentation with `excludeGlobs`/`includeGlobs`
3. Keep old `exclude` and `include` in the config for compatibility purposes.

**Comment by co-category** [comment]
Thank you! That worked.
