### ISSUE TITLE
Use PathMatcher for file filters

### ISSUE THREAD

**Issue by poslegm** [scalameta/scalafmt#1648]
See #1645 #1646 

1. Implement `FilterGlobMatcher` using `java.nio.file.PathMatcher` as an alternative for [FilterMatcher](https://github.com/scalameta/scalafmt/blob/c92153e777984db6d69ec359dd1b1115bd2199d6/scalafmt-core/shared/src/main/scala/org/scalafmt/config/FilterMatcher.scala#L7)
2. Replace `exclude`/`include` in the documentation with `excludeGlobs`/`includeGlobs`
3. Keep old `exclude` and `include` in the config for compatibility purposes.

**Comment by dkartashev** [comment]
I would like to work on it. Is it free?

**Comment by poslegm** [comment]
Yes, you can take it
