### ISSUE TITLE
Adding newlines at end of top level definition

### ISSUE THREAD

**Issue by nasadorian** [scalameta/scalafmt#1653]
## Feature request
Hi All! This is a feature request that I'd be interested in working on myself, as a first time contribution. I'd love to hear feedback if anyone else cares about this kind of a rewrite rule.

There currently exists a scalafmt rule which adds a newline after top level statements. For consistency's sake, it would be great to have a symmetric additional rule which adds a newline before the closing brace of a top level module (object or class definition).

## Current
Scalafmt currently adds a newline at the beginning of top level statements. For example with the following configuration:

```
version = 2.0.1
newlines.alwaysBeforeTopLevelStatements = true
```

Given code like this:
```scala
object Foo {
  def someCode: Unit =
    ()
}
```

Scalafmt produces this:
```scala
object Foo {

  def someCode: Unit =
    ()
}
```

## Proposed
For smaller objects particularly, the above rule ends up with asymmetric looking code. So it would be nice to have an optional trailing newline as well.

So given a (hypothetical) configuration like this:
```
version = 2.0.1
newlines.alwaysBeforeTopLevelStatements = true
newlines.alwaysAfterTopLevelStatements = true // new rule
```

Given this code:
```scala
object Foo {
  def someCode: Unit
}
```

Scalafmt would produce:
```scala
object Foo {

  def someCode: Unit

}
```

**Comment by poslegm** [comment]
I found PR with flag introduction https://github.com/scalameta/scalafmt/pull/733, but motivation is lost in old gitter discussion. Symmetric code looks reasonable, but I don't think that another configuration flag is good decision.

What about small configuration refactoring? New flag with all cases coverage:

```
newlines.alwaysInsideTopLevelStatements = [before, after, both, never]
```

Current flag will be deprecated and kept for compatibility.

@olafurpg @tanishiking @kitbellew

**Comment by nasadorian** [comment]
@poslegm I think this is a flexible solution. We may want to call the new configuration `newlines.insideTopLevelStatements` though, since it is not `always`.

I started poking around in the code last night but I'm not yet familiar with how scalafmt works. Any pointers to get started on this would be appreciated. Maybe for example, where (and how) the current newline rule is implemented?

**Comment by poslegm** [comment]
You can just search by rule name: https://github.com/scalameta/scalafmt/blob/e02b1fe5f8b3331c35d9fdd5e3765a258d2578f3/scalafmt-core/shared/src/main/scala/org/scalafmt/internal/FormatWriter.scala#L319

But I prefer to wait for the decisions of other maintainers about this change.

**Comment by kitbellew** [comment]
@nasadorian @poslegm generally, i am in favour (and the "both" version specifically). however, the way our team prefers to implement this rule is not super-straightforward. we consider these newlines as visual "breathing" space to increase readability, and apply it when readability is actually improved.

for instance, there's no need for vertical lines here:
```
class A(str: String) {
  val length: Int = str.length
  def apply(i: Int): Char = str(i)
}
```

I think we prefer to *surround* with empty lines (i.e. "both") any multiline method and any sequence of single-line methods *WHEN* the class contains at least one empty line. like this:
```
class A(str: String) {

  val length: Int = str.length
  def apply(i: Int): Char = str(i)

  def validateNonNull(): Unit = {
    if (str == null)
      throw NullPointerException("oy vey")
  }

}
```

**Comment by nasadorian** [comment]
@kitbellew I like the idea of keeping small top-level statements tight. Adding lines around something like a typeclass trait introduces unecessary noise.

However I'm not sure I like the uneven spacing in the 2nd example between `length` and `apply`. As a user I would expect the formatting to just be uniform.

```scala
class A(str: String) {

  val length: Int = str.length

  def apply(i: Int): Char = str(i)

  def validateNonNull(): Unit = {
    if (str == null)
      throw NullPointerException("oy vey")
  }

}
```

Is there room for more configurability to serve both styles? Maybe some additional boolean flag like `newlines.ignoreContiguousLines`?

**Comment by poslegm** [comment]
I propose to keep this rule as simple as possible (at least at first iteration). We can firstly solve the problem with assymetric formatting and then discuss about more complex logic:

> I think we prefer to surround with empty lines (i.e. "both") any multiline method and any sequence of single-line methods WHEN the class contains at least one empty line. like this:
