### ISSUE TITLE
Release 2.3.2 of sbt-scalafmt not on Maven Central

### ISSUE THREAD

**Issue by hseeberger** [scalameta/scalafmt#1659]
The latest sbt-scalafmt on Maven Central is 2.3.1. scalafmt-core OTOH is published as 2.3.2 and later (RCs).

**Comment by poslegm** [comment]
Scalafmt and sbt-plugin has independent versioning. Version of scalafmt-core defines in the `.scalafmt.conf` file.

P.S. we need to clearly declare it at the microsite. This is not first question about sbt plugin version.

**Comment by ckipp01** [comment]
Related to this, it's a bit confusing to know what the latest release is. For example on the scalafmt badge it shows that `2.3.1` is the latest core. However, when a new scalafmt config file gets created when you try to format for the first time with Metals, it creates a `.scalafmt.conf` file with the version being `2.3.2`. Then, when looking through the documentation I'm seeing references to `2.4.1`? I'm a bit unsure what is actually the latest release for core that I should be targeting as I'm seeing 3 different ones.
