### ISSUE TITLE
Config: the two branches of an if/else should agree on newline

### ISSUE THREAD

**Issue by sjrd** [scalameta/scalafmt#166]
Original:

``` scala
         if ((req.status >= 200 && req.status < 300) || req.status == 304)
           promise.success(req)
-        else
-          promise.failure(AjaxException(req))
+        else promise.failure(AjaxException(req))
```

**Comment by olafurpg** [comment]
In 0.2.4, scalafmt will keep the body of an if/else on a separate line if it was already on a separate line. This means it won't move bodies into a single line unless you put them on a single line. Although this doesn't go the full way towards automating the style guide, I believe it's a good start. WDYT?

**Comment by sjrd** [comment]
Definitely a good start, as at least it won't "break" correctly formatted code.

**Comment by olafurpg** [comment]
The current behavior where users can force line breaks is working quite well so I think it's OK to close this ticket. It would be nice to automatically force breaks but it's not something I personally plan to work on.
