### ISSUE TITLE
Non-idempotent formatting in 2.4.0-RC1

### ISSUE THREAD

**Issue by adampauls** [scalameta/scalafmt#1667]
- **Configuration**:
```
version = "2.4.0-RC1"
maxColumn = 120 
rewrite.rules = [PreferCurlyFors, SortModifiers, AvoidInfix, SortImports]
trailingCommas = always
assumeStandardLibraryStripMargin = true
optIn.breakChainOnFirstMethodDot = false
spaces.inImportCurlyBraces = true
includeCurlyBraceInSelectChains = true
spaces.beforeContextBoundColon = Always
// These are copied from  https://scalameta.org/scalafmt/docs/configuration.html#other
rewrite.neverInfix.excludeFilters = [
  until
  to
  by
  eq
  ne
  "should.*"
  "contain.*"
  "must.*"
  in
  ignore
  be
  taggedAs
  thrownBy
  synchronized
  have
  when
  size
  only
  noneOf
  oneElementOf
  noElementsOf
  atLeastOneElementOf
  atMostOneElementOf
  allElementsOf
  inOrderElementsOf
  theSameElementsAs
  // these are new
  throws
  returns
  satisfy
]
```

## Steps

Given code like this:
```scala
object Foo {
  def foo(): Unit = {
    aaaaaaaaaaaaaaa(c, ddddddd).map { zzzzzzzzzz =>
      val ccccccccccccccccc = zzzzzzzzzz.bbbbbbbbbbbbbbbbbb(EEEEE.xxxxxxxxxxx, Schema.String).toOption.flatMap {
        case c: Seq[String] =>
          xxxxxxxxxxxxxxxxxxxxxxxx(c, (v: String) => s"""\\"$v\\"""")(Schema.String).map(s =>
            Yyyyyyyyyyyyyyyy("SSSSSSS", s),
          )
      }
    }.get
  }
}
```

(Sorry for the mess, it was hard to minimize further).

`sbt scalafmtCheckAll` does not succeed after `sbt scalamftAll` is run.

## Workaround

I can introduce newlines to get around the problem, but we don't want to have `scalafmtCheckAll` in CI if it's not idempotent.

## Notes

Even though the 
```scala
 xxxxxxxxxxxxxxxxxxxxxxxx(c, (v: String) => s"""\\"$v\\"""")(Schema.String)
            .map(s => Yyyyyyyyyyyyyyyy("SSSSSSS", s))
```

snippet is the one that gets changed back and forth by scalafmt, the `.get` seemed to be necessary for reproduction, so I think there's something going on in an interaction between the two.

**Comment by kitbellew** [comment]
@adampauls this won't be easy to fix once and for all. i fixed one such problem but i suspect they will keep coming. it's the `trailing-commas=always` rule, it triggers a different formatting path.

**Comment by adampauls** [comment]
Yeah, makes sense. By "different formatting path", do you mean a path that you don't typically test? Or do you mean something about the way the code is structured makes trailing-commas=always hard to deal with?

**Comment by adampauls** [comment]
Also, we have been using scalafmt for a while (various versions) and have not had problems with non-idempotency. You're pretty sure a bug hasn't been recently introduced? 

If it's a matter of resourcing, I can try to take a look if I get a chance.

**Comment by kitbellew** [comment]
> Yeah, makes sense. By "different formatting path", do you mean a path that you don't typically test? Or do you mean something about the way the code is structured makes trailing-commas=always hard to deal with?

both, but mostly the second one (i can test but i still can't fix). whatever logic i added recently to format `a(b => c)` similarly to `a { b => c }` likely triggers this.
