### ISSUE TITLE
Break line before if/else body in statement position

### ISSUE THREAD

**Issue by sjrd** [scalameta/scalafmt#167]
Context: https://github.com/scala-js/scala-js/blob/master/CODINGSTYLE.md#ifelse

``` scala
def f(): Unit = {
  if (poij) {
    if (x)
      y
    else
      z
  } else {
    ...
  }
}
```

Easier:

``` scala
if (index >= size)
  throw new IndexOutOfBoundsException
// no else
```

**Comment by olafurpg** [comment]
After https://github.com/scalameta/scalafmt/pull/1180/commits/b301b61feb013c3f8df802245029ea47ccc95567, scalafmt force blocks in if/else to break into a separate line. This does not handle
```scala
if (index >= size) throw new IndexOutOfBoundsException
```
but is still an improvement.

A workaround is to manually insert a line break for the body to obtain the expected output. I'm open to merge a PR if someone wants to take a stab at this.
