### ISSUE TITLE
FEATURE REQUEST: provide an officially built docker image 

### ISSUE THREAD

**Issue by jeff-knurek** [scalameta/scalafmt#1678]
## Problem

Searching for docker image for `scalafmt` results in a lot of uncertainty of what is available, and which version is applicable to the official releases. 

The installation documentation provides lots of formats to install the app into, https://scalameta.org/scalafmt/docs/installation.html
but when running the tool in CI, there's no easy way to include it into the build process. 

## Expectation
There's an official docker image at 
```
https://hub.docker.com/u/scalameta/scalafmt
```
or any other public docker registry
AND
the information about using it is included in the installation docs: https://scalameta.org/scalafmt/docs/installation.html

## Workaround

--EDIT--
the image from https://github.com/mroth/scalafmt-native actually seems to be the best workaround. 

----
There's a community image from https://github.com/wellcomecollection/dockerfiles/blob/master/scalafmt/Dockerfile
that seems to be "usable". But the last update was in August 2019, and the versioning does not align with https://github.com/scalameta/scalafmt/releases
Plus, that image comes with lots of CVEs.

**Comment by poslegm** [comment]
Done, Docker image available [here](https://hub.docker.com/layers/scalameta/scalafmt/v2.6.4/images/sha256-50708925bd69cf70c99d36b6edfde49a00fa613e6ab77144f347769a80c3da2a?context=explore)
