### ISSUE TITLE
Access to "align.treeCategory" configuration

### ISSUE THREAD

**Issue by ikempf** [scalameta/scalafmt#1682]
I am not able to configure the `align` properly .

I initially was only using `align = most` which is a good preset and mostly does what I need.
But I also want to customize the preset by:
- Adding additional tokens (`:=`)
- Overriding the "owner" of existing tokens

As it seems (#1202), overriding properties of the align presets is not possible at the moment. The following configuration drops the `most` preset altogether:
```
version = 2.3.2
align = most
align.tokens = [ ":=" ]
```

I thus tried to reproduce the preset and customize it, the configuration would then look like this:
```
align.tokens.add = [
    { code = "=>", owner = "Case" },
    { code = "extends", owner = "Defn.(Class|Trait|Object)" },
    { code = "//", owner = ".*" },
    { code = "{", owner = "Template" },
    { code = "}", owner = "Template" },
    { code = "%", owner = "Term.ApplyInfix" },
    { code = "%%", owner = "Term.ApplyInfix" },
    { code = "%%%", owner = "Term.ApplyInfix" },
    { code = "<-" },
    { code = "->", owner = "Term.ApplyInfix" },
    { code = "=" },
    { code = ":=" }
]
align.arrowEnumeratorGenerator = true
```
This configuration contains all the default tokens (as in `AlignToken.scala`). But it's missing something, `=` and `<-` are not aligned anymore in for expressions as they were using the `most` preset.
```
for {
    qwerty <- Some(5)
    a = 1
    b     <- Some(5)
    cdefg <- Some(5)
  } yield ()
```
To my understanding this happens because in the `most` preset the left arrow `<-` and the equal sign `=` are both categorized as "Assign" (in `Align.scala`).

I see two solutions to this issue
- Either the tokens can be assigned a category so they get aligned in regard to each other.
```
    { code = "<-", category = "Assign"},
    { code = "=", category = "Assign"},
```

- Or the preset can be customized

Both features seem desirable. That being said, being able to categorize tokens seems more important than being able to cutsomize presets, what is your take on this ?

**Comment by neko-kai** [comment]
@ikempf You can customize `align.tokenCategory` & `align.treeCategory` like this:

```
align.tokenCategory {
  Equals = Assign
  LeftArrow = Assign
  RightArrow = Assign
}

align.treeCategory {
  "Defn.Trait" = "class/object/trait"
  "Defn.Class" = "class/object/trait"
  "Defn.Object" = "class/object/trait"
  "Defn.Val" = "val/var/def"
  "Defn.Def" = "val/var/def"
  "Defn.Var" = "val/var/def"
  "Enumerator.Generator" = for
  "Enumerator.Val" = for
}

```

**Comment by ikempf** [comment]
Thanks, I didn't realize that customizing `tokenCategory` was already possible :)

Closing the issue then.
