### ISSUE TITLE
Single line comments don't format when they're less nested than the code

### ISSUE THREAD

**Issue by kubukoz** [scalameta/scalafmt#1702]
This template is a guideline, not a strict requirement.
- **Configuration**:
```
version = "2.1.0"
```

## Steps

Given code like this:
```scala
trait Foo {
//test
  val a = ""
}
```

When I run scalafmt like this:

```bash
scalafmt Foo.scala
```

## Problem

Scalafmt formats code like this:
```scala
trait Foo {
//test
  val a = ""
}
```

## Expectation

I would like the formatted output to look like this:
```scala
trait Foo {
  //test
  val a = ""
}
```

## Workaround

Formatting manually

## Notes

I didn't replicate that with a multi-line comment.

**Comment by olafurpg** [comment]
Thank you for reporting! This is working as intended to play nicely with how IntelliJ comments out blocks of code. Without this special case for when the comment starts at column 0 the commented out block indents large bodies of code.

**Comment by kubukoz** [comment]
Hmm, so it would indent the whole `val a = ""` line?

**Comment by olafurpg** [comment]
The current behavior is “//“ comments that start on column 0 stay unchanged (don’t get indented). You can add a single space before the comment to indent it.

**Comment by kubukoz** [comment]
Sure, I was curious about how it would work if that behavior wasn't implemented (the IDEA case you mentioned - I'm failing to imagine the exact problem)
