### ISSUE TITLE
Automate uploading native images to release notes

### ISSUE THREAD

**Issue by note** [scalameta/scalafmt#1711]
## Steps

I tried to install native image according to [docs](https://scalameta.org/scalafmt/docs/installation.html#native-image):

```
$ curl https://raw.githubusercontent.com/scalameta/scalafmt/master/bin/install-scalafmt-native.sh | sh -s -- 2.4.0 . 
...
+ curl --fail -Lo scalafmt-linux.zip https://github.com/scalameta/scalafmt/releases/download/v2.4.0/scalafmt-linux.zip
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0
curl: (22) The requested URL returned error: 404 Not Found
```

I took a look at GH release and it makes sense as the only artifacts included to release are source packages. After some digging I found that artifacts are available here: https://github.com/scalameta/scalafmt/actions/runs/39759768

I know literally nothing about Github Actions but I believe it might be worth trying to modify [native.yml](https://github.com/scalameta/scalafmt/blob/master/.github/workflows/native.yml) so it uses https://github.com/actions/upload-release-asset. `upload-release-asset` has `upload_url` as an input and https://github.com/release-drafter/release-drafter has it as output.

I may take a look at this in following days. I am assuming github actions are runnable on forks as say travis-ci.

**Comment by kitbellew** [comment]
@olafurpg @tanishiking @poslegm if one of you understands about *release-drafter* (which might be related to this problem), that component is acting up; it has stopped drafting releases, i wrote them manually.

**Comment by olafurpg** [comment]
The release drafter service has been discontinued in favor of a custom GitHub action that we haven’t setup in the Scalafmt repo (example https://github.com/scalameta/metals-languageclient/blob/master/.github/workflows/release-drafter.yml).

As for the native image, I have manually uploaded those binaries for releases so far under the assumption that Scalafmt releases are infrequent. there’s been a lot activity lately so it might be worth automating the native image uploading, but to fix this issue it’s probably best to manually download the binaries from the GitHub actions web ui and upload them in the GitHub releases ui. 

The tricky part with automating the uploading is that we normally wait with creating a release until the artifacts are available on maven central. Maybe we can somehow run the action on the “release” event 🤔
