### ISSUE TITLE
cats-effect: Unable to format file due to bug in scalafmt

### ISSUE THREAD

**Issue by rossabaker** [scalameta/scalafmt#1714]
This template is a guideline, not a strict requirement.
- **Version**: 2.4.1
- **Integration**: sbt-scalafmt
- **Configuration**:
```
version = 2.4.1
align = none
align.openParenCallSite = true
align.openParenDefnSite = true
maxColumn = 120
continuationIndent.defnSite = 2
assumeStandardLibraryStripMargin = true
danglingParentheses = true
rewrite.rules = [AvoidInfix, SortImports, RedundantBraces, RedundantParens, SortModifiers]
docstrings = JavaDoc
lineEndings=preserve
```

## Steps

Given code like [this](https://github.com/scala-steward/cats-effect/blob/521cf8deaac3cbedb8a6238a8d244a416f8f23f1/laws/shared/src/test/scala/cats/effect/ResourceTests.scala):
```scala
  testAsync("Resource.make is equivalent to a partially applied bracket") { implicit ec =>
    check { (acquire: IO[String], release: String => IO[Unit], f: String => IO[String]) =>
      acquire.bracket(f)(release) <-> Resource.make(acquire)(release).use(f)
    }
  }
```

When I run scalafmt like this:

```bash
sbt lawsJVM/scalafmtAll
```

## Problem

Scalafmt fails:
```
[error] /home/ross/src/cats-effect/laws/shared/src/test/scala/cats/effect/ResourceTests.scala:56: error: Unable to format file due to bug in scalafmt
[error]       acquire.bracket(f)(release) <-> Resource.make(acquire)(release).use(f)
[error]                                 ^: /home/ross/src/cats-effect/laws/shared/src/test/scala/cats/effect/ResourceTests.scala
[error] (lawsJVM / Test / scalafmt) /home/ross/src/cats-effect/laws/shared/src/test/scala/cats/effect/ResourceTests.scala:56: error: Unable to format file due to bug in scalafmt
[error]       acquire.bracket(f)(release) <-> Resource.make(acquire)(release).use(f)
[error]                                 ^: /home/ross/src/cats-effect/laws/shared/src/test/scala/cats/effect/ResourceTests.scala
```

## Expectation

scalafmt succeeds and the output still compiles

## Workaround

Not upgrading to 2.4.1.

## Notes

Similar to #1599, but not the same as what @larsrh reported for cats-effect on 2.4.0.

**Comment by kitbellew** [comment]
> Similar to #1599, but not the same as what @larsrh reported for cats-effect on 2.4.0.

what was the problem in 2.4.0? i don't think i have seen that report.

**Comment by larsrh** [comment]
@kitbellew See https://github.com/scalameta/scalafmt/issues/1599#issuecomment-586575046

**Comment by kitbellew** [comment]
> @kitbellew See [#1599 (comment)](https://github.com/scalameta/scalafmt/issues/1599#issuecomment-586575046)

@larsrh is there a code example which can be used to reproduce the problem?

**Comment by larsrh** [comment]
Yes, you can run `scalafmtAll` on the PR.

**Comment by kitbellew** [comment]
> Yes, you can run `scalafmtAll` on the PR.

of course.

**Comment by kitbellew** [comment]
> > @kitbellew See [#1599 (comment)](https://github.com/scalameta/scalafmt/issues/1599#issuecomment-586575046)
> 
> @larsrh is there a code example which can be used to reproduce the problem?

@larsrh please see if your problem is fixed by #1719.

also, it would make it easier in the future if you could share your problems with the tool by submitting a new issue with the configuration and exact steps to reproduce.

**Comment by rossabaker** [comment]
I can test.  Are snapshots published anywhere?  I checked Sonatype, and don't see any past 2.3.1.  Thanks!

**Comment by kitbellew** [comment]
> I can test. Are snapshots published anywhere? I checked Sonatype, and don't see any past 2.3.1. 

honestly, i don't know. i build locally and run this:
```
v=2.4.1
# build
sbt publishLocal
# turn into a binary
coursier bootstrap org.scalameta:scalafmt-cli_2.13:$v-SNAPSHOT \
  -f -r sonatype:snapshots \
  -o scalafmt.new --standalone --main org.scalafmt.cli.Cli
# run
./scalafmt.new --test
```
