### ISSUE TITLE
Spreading of shebang in *.sc files

### ISSUE THREAD

**Issue by ckipp01** [scalameta/scalafmt#1716]
This template is a guideline, not a strict requirement.
- **Version**: 2.3.2
- **Integration**: Metals
- **Configuration**:
```
version = "2.3.2"
```

## Steps

Given code that uses a shebang like the following:
```scala
#!/usr/bin/env amm
```

When I run scalafmt the result is as follows:

```git
#!/ usr / bin / env amm
```

## Problem and expectation

I would expect this line to be unchanged, as this change prevents the script from being executed correctly.

##### search terms
scripts, amm, shebang

**Comment by fabianpage** [comment]
I have the same problem. Also it's not possible to turn of scalafmt on these lines with // format:off because the shebang has to be on the start of the file
