### ISSUE TITLE
AlignTab style alignment configuration

### ISSUE THREAD

**Issue by paulp** [scalameta/scalafmt#172]
[Sorry, I'm not trying to spread out over multiple tickets without cause. Please feel free to consolidate my comments as you deem appropriate.]

An example of where alignment inference is needed. See what happens to the function arrows.

The thing about vertical alignment is that anyone who wants it is prone to be using it already to communicate information to the code reader. Such a person will invariably be unenthusiastic about seeing that hard-fought alignment destroyed by the formatter. These people are difficult to satisfy: even the 95% solution stomps meaningful information out of 5% of their code, which prevents them from integrating the formatter directly into the development process where it belongs.

Thus, the compelling motivation to take note of when columns are already aligned and avoid leaving them in disarray.

Original:

``` scala
 abstract class Laws[A : Eq] {
  def associative(f: BinOp[A]): Forall3[A]               = (a, b, c) => f(a, f(b, c)) === f(f(a, b), c)
  def distributive(f: BinOp[A], g: BinOp[A]): Forall3[A] = (a, b, c) => f(a, g(b, c)) === g(f(a, b), f(a, c))
  def commutative(f: BinOp[A]): Forall2[A]               = (a, b)    => f(a, b) === f(b, a)
  def absorption(f: BinOp[A], g: BinOp[A]): Forall2[A]   = (a, b)    => f(a, g(a, b)) === a
  def identity(f: BinOp[A], id: A): Forall1[A]           = a         => f(a, id) === a
  def idempotence(f: BinOp[A]): Forall1[A]               = a         => f(a, a) === a
 }
```

Scalafmt:

``` scala
abstract class Laws[A : Eq] {
  def associative(f: BinOp[A]): Forall3[A]               = (a, b, c) => f(a, f(b, c)) === f(f(a, b), c)
  def distributive(f: BinOp[A], g: BinOp[A]): Forall3[A] = (a, b, c) => f(a, g(b, c)) === g(f(a, b), f(a, c))
  def commutative(f: BinOp[A]): Forall2[A]               = (a, b) => f(a, b) === f(b, a)
  def absorption(f: BinOp[A], g: BinOp[A]): Forall2[A]   = (a, b) => f(a, g(a, b)) === a
  def identity(f: BinOp[A], id: A): Forall1[A]           = a => f(a, id) === a
  def idempotence(f: BinOp[A]): Forall1[A]               = a => f(a, a) === a
}
```

I would like the input to look like the original. Sample collected with `scalafmt --style defaultWithAlign --maxColumn 160`.

**Comment by olafurpg** [comment]
My problem with alignment inference is false positives, that is aligning by tokens that aren't supposed to be aligned. It leaves the user with no hope to get the formatting they want it to look like without waiting for scalafmt to improve.

Also, I believe that the most demanding users probably appreciate powerful

Finally, automatically inferring alignment forces you to write the aligned code in the first place.   

I have considered adding support for dynamic configuration, that is allow blocks of code to be wrapped in

**Comment by paulp** [comment]
Inferring alignment doesn't "force" you to write the aligned code in the first place. That has already happened. Inferring it prevents the formatter from destroying the alignment which was already there.

If the configuration language is equal in power to https://github.com/randy3k/AlignTab then I could probably configure all this in one place and use the same configuration everywhere. But enumerating the names of individual operators like `^^` isn't going to fly. The promise of a code formatter is to be able to fork a large project, then 1) format all its code and 2) apply the formatter automatically from that point forward. I can't do 1) if the formatter is prone to breaking code, as in the stripMargin case, and I can't do 2) if the formatter will break any introduced formatting unless the format configuration is hand massaged.

I addressed false positives when I first mentioned it, but surely it's clear that ten lines in a row which have `^^` in the same columns has the same chance of being a false positive as earth does of being hit by an asteroid in the next nanosecond. It's simply a question of where you draw the line. If false positives are a problem, the line was drawn in the wrong place.

**Comment by olafurpg** [comment]
Fine. I won't argue against the merit of this idea. I also agree that enumerating all the individual operators is insufficient for super users like yourself.

I would appreciate input from more folks on this. How many users are affected by the limitations of the current vertical alignment implementation?

I need more time to wrap my head around alignment inference. Maybe some hands-on experience with AlignTab could help.

**Comment by olafurpg** [comment]
I tried AlignTab and I think going that direction would be better than inferring alignment. We could support configuration like

```scala
// only tokens that match the same category will align together
case class AlignToken(category: String, regexp: String)

// scala configuration
AlignToken("sbt_operator", "[&|@#<+:~]+[=]")
// cli configuration
--addAlignToken "sbt_operator;[&|@#<+:~]+[=]"
```
On top of the plain regex match, scalafmt can behind the scenes assure that we don't align tokens with owners of different type.

How important are the aligntab options (justification and space configuration)?. I think scalafmt may be able to infer if there should be a space or no space. Right justification gives marginal benefits over left justification in my opinion (looks very fancy though).

**Comment by paulp** [comment]
> How important are the aligntab options (justification and space configuration)

Important. Sometimes, they make all the difference. For instance, left justification is materially worse in a situation such as
```
                organization :=  "org.improving",
    scalacOptions in compile ++= Seq("-Ywarn-unused", "-Ywarn-unused-import"),
         libraryDependencies +=  "com.novocode" % "junit-interface" % "0.11" % "test",
                    licenses :=  Seq("Apache-2.0" -> url("http://www.apache.org/licenses/LICENSE-2.0")),
                scalaVersion :=  "2.11.8",
                 logBuffered :=  false,
                   maxErrors :=  15,
            triggeredMessage :=  Watched.clearWhenTriggered
```
Having even one long key name (and sbt and plugins are happy to inflict ridiculously long key names on you) can create enough whitespace between keys and values to make one uncertain what goes with what. There's no reason to live with uncertainty of that kind.

The presence or absence of a space is often quite important. The quest for information aesthetics is a precision undertaking.

**Comment by olafurpg** [comment]
I see the use case for right justified columns in sbt column.

I can't promise when this will be implemented. I've assigned the 0.3 milestone, but it may be postponed to a later release.

I'm happy to help out if someone is interested contributing an implementation. The [implementation that decides which columns match](https://github.com/olafurpg/scalafmt/blob/d38c94e002477b8c47ab2dea7d5eee23f002a12b/core/src/main/scala/org/scalafmt/internal/FormatWriter.scala#L159) is quite separate from the rest of the alignment implementation. See `isCandidate` for how tokens get picked for alignment. We would also have to change the `alignTokens` member of `ScalafmtStyle`.

Also, the `alignmentTokens` implementation is super imperative/ugly/flaky and may be worth refactoring. It does not reflect my typical coding style.
