### ISSUE TITLE
Configuration to preserve existing breaks in call chains

### ISSUE THREAD

**Issue by paulkore** [scalameta/scalafmt#1744]
Version: 2.4.2

```
private val a = Set(2, 10, 3, 9, 4, 8)

// 1
a.toList.sorted.foreach(println)
// 2
a.toList.sorted
  .foreach(println)

// example 1 is unaffected

// with [includeNoParensInSelectChains=false], example 2 is unaffected:
a.toList.sorted
  .foreach(println)

// with [includeNoParensInSelectChains=true], example 2 is rewritten to:
a.toList
  .sorted
  .foreach(println)

// with [optIn.breakChainOnFirstMethodDot=false], example 2 is rewritten to:
a.toList.sorted.foreach(println)
```

However, there doesn't appears to be a way to completely disable call-chain formatting.

We would like to request a feature to preserve existing call chain separations.

(This is up for debate of course, but we feel that given the size of our existing code base, the style of call chaining is not something that is practical to control with global settings; We would like to leave it for the implementer to decide on a case by case basis)

**Comment by paulkore** [comment]
@tanishiking , @kitbellew, what would be your opinion?

**Comment by kitbellew** [comment]
@paulkore i am working on a sequence of changes primarily designed to *ignore* newlines in the input, but it also contains an option to preserve them (#1627). however, it is a single all-or-nothing approach, without any granular settings for every possible context. you'll find the maintainers generally averse to adding new parameters as they create a plethora of interactions and consequently bugs.

**Comment by paulkore** [comment]
@kitbellew thanks for pointing out the new feature you're working on. 
The way it looks, this is going to be a game-changing update which will allow my organization to adopt scalafmt, because we really want to preserve our existing approach to line breaks.
Any indication on when we should expect it to be released? 🙏

**Comment by kitbellew** [comment]
RC1 should be available in a couple of weeks. Keep in mind that this is a big change and likely with some cases missed, so it will be considered experimental until the dust settles. Hopefully there will be enough people trying the additional options out so kinks can be ironed out quickly.

**Comment by paulkore** [comment]
Happy to help test the release candidate against our code base, when it's available.

**Comment by kitbellew** [comment]
@paulkore have you tried using `optIn.breaksInsideChains = true`? i think that should do the trick.

**Comment by paulkore** [comment]
@kitbellew just tried it, however it doesn't seem to have any effect.... is it possible that some other configuration is overpowering it?

This is my config before applying `optIn.breaksInsideChains=true`:

```
version=2.4.2

align=none

assumeStandardLibraryStripMargin=false

binPack {
  parentConstructors=false
  literalArgumentLists=true
  literalsMinArgCount=5
}

continuationIndent {
  defnSite=2
  callSite=2
  extendSite=4
}

danglingParentheses {
  callSite=true
  defnSite=true
}

importSelectors=noBinPack

includeCurlyBraceInSelectChains=true

includeNoParensInSelectChains=false

indentYieldKeyword=false

literals {
  long=Upper
  float=Lower
  double=Lower
}

maxColumn=120

newlines {
  neverInResultType=false
  neverBeforeJsNative=false
  sometimesBeforeColonInMethodReturnType=true
  penalizeSingleSelectMultiArgList=true
  alwaysBeforeCurlyBraceLambdaParams=false
  alwaysBeforeTopLevelStatements=false
  alwaysBeforeElseAfterCurlyIf=false
  alwaysBeforeMultilineDef=false
  avoidAfterYield=true
  afterCurlyLambda=never
}

optIn {
  configStyleArguments=true
  breaksInsideChains=false
  breakChainOnFirstMethodDot=true
  selfAnnotationNewline=true
  annotationNewlines=true
  blankLineBeforeDocstring=true
}

spaces {
  beforeContextBoundColon=Never
  afterTripleEquals=false
  inImportCurlyBraces=false
  inParentheses=false
  afterKeywordBeforeParen=true
  inByNameTypes=true
  afterSymbolicDefs=false
}

trailingCommas=preserve

unindentTopLevelOperators=false

verticalAlignMultilineOperators=false

verticalMultiline {
  atDefnSite=false
  arityThreshold=3
  newlineBeforeImplicitKW=false
  newlineAfterImplicitKW=false
  newlineAfterOpenParen=false
}

```

**Comment by kitbellew** [comment]
@paulkore i just ran a test specifically on
```
a.toList.sorted
  .foreach(println)
```
with the flag i mentioned above (plus `align=none`, rest is default), and got
```
a.toList.sorted
  .foreach(println)
```

**Comment by paulkore** [comment]
In the sample above, `.toList` and `.sorted` are "no-parens", whereas `.foreach(println)` falls under the other classification.

I believe that `includeNoParensInSelectChains=false` by default.

What happens if you run your minimal config against this sample ?
```
a.toList
  .sorted
  .foreach(println)
```

**Comment by kitbellew** [comment]
@paulkore my understanding is that you're looking for a set of parameters which would leave those dot breaks alone, not to prove that using `includeNoParensInSelectChains=false` doesn't.

With this:
```
optIn.breaksInsideChains = true
includeNoParensInSelectChains = true
includeCurlyBraceInSelectChains = true
```

this snippet:
```
object foo {
  a.b.c(d).e { f }.g.h { i }.j(k)

  a.b.c(d).e { f }.g.h { i }
    .j(k)

  a.b.c(d).e { f }.g
    .h { i }.j(k)

  a.b.c(d).e { f }
    .g.h { i }.j(k)

  a.b.c(d)
    .e { f }.g.h { i }.j(k)

  a.b
    .c(d).e { f }.g.h { i }.j(k)

  a
    .b.c(d).e { f }.g.h { i }.j(k)
}
```

changes only the last one, because the first select is shorter than indentation. if you change the last example to
```
  aaa
    .b.c(d).e { f }.g.h { i }.j(k)
```
it will stay unchanged.

**Comment by paulkore** [comment]
@kitbellew gotcha, so all 3 properties above must be set to true for the desired effect to be achieved. 

It does seem to work as expected on most of my samples, with the exception of this problematic case involving a fully-qualified call to a function that's prefixed with an object hierarchy:

```
Foo.Bar.Baz.calculate(2, 3)
  .toList
  .sorted
```

becomes:
```
Foo
  .Bar.Baz.calculate(2, 3)
  .toList
  .sorted
```

Overall, we're now in much better shape on the topic of call chains!

From our standpoint, we would like line breaks to be left alone in other places too - object constructors, if/else, match blocks.... so we look forward to the release of #1627 before we can adopt scalafmt.
