### ISSUE TITLE
Align = to the right in for comprehension

### ISSUE THREAD

**Issue by saksmt** [scalameta/scalafmt#1753]
I couldn't find any config option to change the aligning of `=` in for comprehension.
I want it to be aligned to the right instead of to the left, so that such code

```scala
for {
  _ <- f1
  someValue <- f2
  _ = doLogs
 _ <- f3
} yield ()
```
becomes:
```scala
for {
  _         <- f1
  someValue <- f2
  _          = doLogs
  _         <- f3
} yield ()
```
instead of:
```scala
for {
  _         <- f1
  someValue <- f2
  _         = doLogs
  _         <- f3
} yield ()
```

**Comment by poslegm** [comment]
Yes, I agree that we need improve `=` alignment. `doLogs` should be aligned with other right-side expressions.
