### ISSUE TITLE
poorManTrailingCommasInConfigStyle only for tuples

### ISSUE THREAD

**Issue by saksmt** [scalameta/scalafmt#1754]
Haskell style formatting for tuples would be useful, so that tuples with mapN/parMapN/tupled would be formatted as following:
```scala
( userNameF
, credentialsF
, cityF
, smthElseF
).mapN(User.apply)
```
Don't know if it is actually possible without interfering with other formatting rules, but still.

**Comment by poslegm** [comment]
@olafurpg `poorMansTrailingCommasInConfigStyle` setting marked as "experimental" and "[just for fun](https://github.com/scalameta/scalafmt/commit/f681d46a165de009f87557db73b8b5b867543960)" 4 years ago. What do you think, should we support and evolve it further?

**Comment by saksmt** [comment]
Well, dunno really, it depends what community think about such syntax. And this syntax is a little bit different from that provided by this setting (I mentioned it just to give some insight about what code in scalafmt could be adapted for this case). As for me I think it is much more robust and pleasant for eyes than:
```scala
(
  userNameF,
  credentialsF,
  cityF,
  smthElseF
).mapN(User.apply)
```

**Comment by poslegm** [comment]
I'v really rarely seen this syntax in Scala projects. And [examples](https://typelevel.org/cats/datatypes/validated.html#meeting-applicative) from cats documentation uses commas for applicative operations in «classic» Scala way.

Personally I think that it's too unpopular approach for Scala to support it in formatter.

**Comment by saksmt** [comment]
Probably you're right, and maybe I'm just inventing a bicycle here, anyway at least it is useful to at least have such issue anyway so that anyone looking for such syntax now or in future could express their opinion about this or see that it is really unpopular and happily forget about it.

**Comment by neko-kai** [comment]
We used leading comma before adopting scalafmt and tried to use trailing comma as much as possible afterwards. After a new release with `trailingComma=multiple` we'll be able to automate usage of trailing commas everywhere.

**Comment by kitbellew** [comment]
Since `poorMansTrailingCommasInConfigStyle` has been deprecated in #1758, I will close this.
