### ISSUE TITLE
Changelog on website is missing 2.4 release

### ISSUE THREAD

**Issue by Daenyth** [scalameta/scalafmt#1775]
As the title says. The 2.4 release isn't here: https://scalameta.org/scalafmt/docs/changelog.html

**Comment by poslegm** [comment]
Thank you for notification!

**Comment by poslegm** [comment]
How appropriate is it to have two changelogs (wesite and github releases)? May be just refer from website to github release notes?
 
@olafurpg @tanishiking @kitbellew What do you think?

**Comment by olafurpg** [comment]
Fine by me to link to GitHub releases from the website. It should be possible down the road to implement an mdoc modifier that extracts release notes from GitHub releases and automatically generates a webpage on your site. The nice thing with having the notes on the website is that users can search through the release notes

**Comment by Daenyth** [comment]
From my (user) perspective, the most important things I want from a changelog are:
- easy for me to scroll down and see changes of multiple versions at a time
- I can link directly to a specific version's changelog (to put in a commit message on upgrading, for example)

**Comment by olafurpg** [comment]
I agree. I wish the GitHub releases UI made it easier to browse multiple release notes in one page and also made it easier to search through release notes. It's hard to beat cmd+f on a large HTML page :)
