### ISSUE TITLE
Idempotence violations on implicit arguments handling

### ISSUE THREAD

**Issue by poslegm** [scalameta/scalafmt#1787]
This template is a guideline, not a strict requirement.
- **Version**: master branch after v2.4.2 tag 
- **Integration**: IntelliJ
- **Configuration**:
```
```

## Steps
Unit test for reproduction:
```
<<< ONLY step 1
private def getTopN[T](s: Iterable[T], n: Int)(
      implicit ord: Ordering[T]): Seq[T]
>>>
private def getTopN[T](s: Iterable[T], n: Int)(
    implicit ord: Ordering[T]	   
): Seq[T]
<<< ONLY step 2
private def getTopN[T](s: Iterable[T], n: Int)(
    implicit ord: Ordering[T]	   
): Seq[T]
>>>
private def getTopN[T](s: Iterable[T], n: Int)(implicit
    ord: Ordering[T]
): Seq[T]
```

Introduced after https://github.com/scalameta/scalafmt/pull/1749

**Comment by kitbellew** [comment]
@poslegm need your opinion; would you prefer formatting in step1 or in step 2?

specifically, step1 would mean that no special `implicit` handling would be applied when only one argument is present. step2 would "tuck" the modifier on the previous line regardless of the number of arguments.

`scala-repos` diffs:
* step1: https://github.com/kitbellew/scala-repos/commit/21a3a27b7e9fbf47cd2f44cdc89f5d049cb02e55
* step2: https://github.com/kitbellew/scala-repos/commit/ccf06da015f6efca3f22e5541434f4f8ce47e9ec

**Comment by poslegm** [comment]
[step2](kitbellew/scala-repos@21a3a27) looks better
