### ISSUE TITLE
Support import group for import rewriter

### ISSUE THREAD

**Issue by kerrlovepanda** [scalameta/scalafmt#1794]
```scala
package akka.actor

import akka.AkkaException
import akka.event.LoggingAdapter
import java.util.Optional

import scala.annotation.tailrec
import scala.beans.BeanProperty
import scala.util.control.NoStackTrace
import akka.annotation.InternalApi
import akka.util.unused
```

would be better with first `java then scala, others and finally akka` support which will be 
```scala
package akka.actor

import java.util.Optional

import scala.annotation.tailrec
import scala.beans.BeanProperty
import scala.util.control.NoStackTrace

import akka.AkkaException
import akka.event.LoggingAdapter
import akka.annotation.InternalApi
import akka.util.unused
```

**Comment by hepin1989** [comment]
I will try to contribute to this later.

**Comment by poslegm** [comment]
Please look at https://github.com/NeQuissimus/sort-imports

It is not scalafmt scope of responsibility because correct import grouping requires **semantic** information.

Same issues: https://github.com/scalameta/scalafmt/issues/722 https://github.com/scalameta/scalafmt/issues/188

**Comment by kitbellew** [comment]
i have code to do this but without semantic logic it assumes relative imports have not dots and are grouped at the end. i gave up after reading the older threads, assuming it wouldn't be approved.

**Comment by poslegm** [comment]
I will close it because
1. It's impossible to do clear at scalafmt
2. There is existing solution with scalafix
3. It's out of scalafmt scope

**Comment by hepin1989** [comment]
@poslegm thanks for all those informations
