### ISSUE TITLE
Keep lambda with single definition statement on separate line 

### ISSUE THREAD

**Issue by olafurpg** [scalameta/scalafmt#1809]
This template is a guideline, not a strict requirement.
- **Version**: 2.4.2
- **Integration**: cli
- **Configuration**: defaults
```
version = 2.4.2

```

## Steps

Given code like this:
```scala
    files.par.foreach { p =>
      val td = mtags.index(p.toLanguage, p)
    }
```

## Problem

Scalafmt formats code like this:
```scala
    files.par.foreach { p => val td = mtags.index(p.toLanguage, p) }
```

## Expectation

I would like the formatted output to remain unchanged. The body is a definition, I'm planning to write another statement. 

## Workaround

I've found that by adding an extra dummy statement I get the expected behavior.

**Comment by poslegm** [comment]
@kitbellew what about to hide this behavior under `newlines.source = fold`?

**Comment by kitbellew** [comment]
@poslegm certainly.

however... what is the significance of using `val td`? what's the difference between
```
files.par.foreach { p => val td = mtags.index(p.toLanguage, p) }
```
and
```
files.par.foreach { p => mtags.index(p.toLanguage, p) }
```

**Comment by olafurpg** [comment]
The significance of `val` is that I'm about to write a second statement to use the `td` variable.

I personal preference would be to preserve newlines in all `{` blocks like in older versions of Scalafmt but I'm on board with making Scalafmt more opinionated about newlines so I'm trying to get used to the new behavior. It's only in the case of this issue where I've found the latest Scalafmt to be too strict so far about moving the block into a single line.
