### ISSUE TITLE
Inconsistent number of arguments per-line with single-line block lambda

### ISSUE THREAD

**Issue by olafurpg** [scalameta/scalafmt#1825]
- **Version**: 2.4.2
- **Integration**: cli
- **Configuration**: defaults

## Steps

Upgrading to 2.4.2 from 2.3.2 I got the following diff in a project.

```diff
-  check("lambda".tag(NoDotty), { (y: String) =>
-    y.head
-  }, "(y: String) =>\n    y.head")
+  check(
+    "lambda".tag(NoDotty), { (y: String) => y.head },
+    "(y: String) =>\n    y.head"
+  )
```

## Problem

It's inconsistent to have two arguments on the same line.
```scala
  check(
    "lambda".tag(NoDotty), { (y: String) => y.head },
    "(y: String) =>\n    y.head"
  )
```
## Expectation

I would like the formatted output to look something like this instead:
```scala
  check(
    "lambda".tag(NoDotty),
    { (y: String) => y.head },
    "(y: String) =>\n    y.head"
  )
```

I'm not sure what is the expected behavior for multi-line lambdas 🤔 Maybe we should remove the special case altogether that tries to keep the opening brace `{` on the same line as the leading comma `,`

```scala
  check("lambda".tag(NoDotty), { (y: String) =>
    y.head
    x.head
  }, "(y: String) =>\n    y.head")
  // vs
  check(
    "lambda".tag(NoDotty),
    { (y: String) =>
      y.head
      x.head
    },
    "(y: String) =>\n    y.head"
  )
```

Any thoughts?

**Comment by poslegm** [comment]
It formats fine for large lines in lambda body:

```scala
  check("lambda".tag(NoDotty), { (y: String) =>
    y.headaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa
  }, 1)
```

@kitbellew what about keeping splits «as is» for `newlines.source` values except `fold`? And for fold also add `Newline` before lambda

**Comment by kitbellew** [comment]
@olafurpg can you try with the current master? is it possible it has been fixed in #1743?

**Comment by poslegm** [comment]
Yes, it works well on master

```scala
<<< ONLY 1825
check("lambda".tag(NoDotty), { (y: String) =>
    y.head
}, "(y: String) =>\n    y.head")
>>>
check(
  "lambda".tag(NoDotty),
  { (y: String) => y.head },
  "(y: String) =>\n    y.head"
)
```

**Comment by olafurpg** [comment]
Great! Closing as fixed then 😄  Thank you
