### ISSUE TITLE
Interest in containerizing scalafmt?

### ISSUE THREAD

**Issue by bsolomon1124** [scalameta/scalafmt#1829]
`scalafmt` as a standalone CLI tool seems like a good candidate for containerization given its lack of support in package managers.  (See for example: https://github.com/koalaman/shellcheck.)

Here is a working Dockerfile:

```
FROM openjdk:8
ARG SCALAFMT_VERSION=2.4.2
ARG SCALAFMT_INSTALL_LOCATION=/usr/local/bin/scalafmt
RUN set -ex \
    && apt-get update -y \
    && rm -rf /var/lib/apt/lists/* \
    && echo insecure > "$HOME/.curlrc" \
    && curl -Lo coursier https://git.io/coursier-cli \
    && chmod u+x coursier \
    && ./coursier bootstrap "org.scalameta:scalafmt-cli_2.12:$SCALAFMT_VERSION" \
        -r sonatype:snapshots \
        -o "$SCALAFMT_INSTALL_LOCATION" \
        --main org.scalafmt.cli.Cli \
    && rm -f coursier \
    && scalafmt --version
CMD ["/usr/local/bin/scalafmt"]
```

Verification:

```
$ docker container run --rm scalafmt-test:4 scalafmt --version
scalafmt 2.4.2
```

The resulting image is 573MB, which adds an incremental 60MB over openjdk:8.

**Comment by poslegm** [comment]
Related: https://github.com/scalameta/scalafmt/issues/1678

Personally I don't see the need to create an Docker image for scalafmt. 

But if some volunteer want  to:
1. create image
2. publish it to public image registry
3. integrate it into our release process
4. and will support in the future

...

Contributions are welcome!

**Comment by bsolomon1124** [comment]
@poslegm would the maintainers of this project willing to host the images under an organization page such as https://hub.docker.com/u/scalameta/?  (I see that org doesn't exist on Docker Hub currently.)

**Comment by poslegm** [comment]
@olafurpg what about Docker Hub account for scalameta projects?

**Comment by olafurpg** [comment]
I just pushed a docker container that you can run like this
```
❯ docker run scalameta/scalafmt:2.4.2 scalafmt --help
```
Does it work for you?

My biggest concern is keeping this image up-to-date with releases. The JVM binary dynamically downloads the appropriate Scalafmt version so in theory I think we don't have to push a new docker image for every release. Any thoughts?

**Comment by bsolomon1124** [comment]
Looks good @olafurpg!  The pull/run is working for me.

I left some suggestions on https://github.com/olafurpg/scalafmt/commit/944cc2b0d8a653ecff6d836286ac831fbfab8955 for possible small improvements to image quality.

Regarding your comment,

> My biggest concern is keeping this image up-to-date with releases. The JVM binary dynamically downloads the appropriate Scalafmt version so in theory I think we don't have to push a new docker image for every release. Any thoughts?

I'm afraid I won't be a ton of help on that since I don't know scalafmt all that well.  Could you elaborate on how that happens?  I see `./coursier bootstrap "org.scalameta:scalafmt-cli_2.12:$SCALAFMT_VERSION"` which seems to imply a one-time pull of a specific version but I'm sure I am missing some steps.

**Comment by poslegm** [comment]
Done in #2059 

Docker image: https://hub.docker.com/layers/scalameta/scalafmt/v2.6.4/images/sha256-50708925bd69cf70c99d36b6edfde49a00fa613e6ab77144f347769a80c3da2a?context=explore
