### ISSUE TITLE
Shouldn't ParseError cause non-zero exit code?

### ISSUE THREAD

**Issue by bsolomon1124** [scalameta/scalafmt#1835]
I noticed in cases where a source file contains invalid syntax and a ParseError is thrown, when used with `--test` scalafmt will still return a 0 exit code.

Is this the expected behavior, and might it make more sense to return a non-zero exit code in this situation?

Reproducible example:

```shell
$ # This file has a syntax error (missing close bracket) and will not compile
$ echo -e 'class Foo extends App {\n  println("foo")' > BadSyntax.scala
$ scalafmt --test BadSyntax.scala
/BadSyntax.scala:3: error: } expected but end of file found

^
error: ParseError=2
$ echo "$?"
0

$ # This file will compile but is not properly formatted scalafmt-style
$ echo -e 'class Foo extends App\n{  println(   "foo" )'} > BadFormat.scala
$ scalafmt --test BadFormat.scala
--- /BadFormat.scala
+++ /BadFormat.scala-formatted
@@ -1,2 +1,1 @@
-class Foo extends App
-{  println(   "foo" )}
+class Foo extends App { println("foo") }
error: --test failed
$ echo "$?"
1
```

```shell
$ scalafmt --version
scalafmt 2.4.2
$ cat /etc/debian_version
10.3
```

**Comment by poslegm** [comment]
It's ignored [here](https://github.com/scalameta/scalafmt/blob/master/scalafmt-cli/src/main/scala/org/scalafmt/cli/Cli.scala#L149-L156). This code was authored @olafurpg about 2 years ago and I don't know reasons of this decision.

**Comment by bsolomon1124** [comment]
For similar tools with other languages (one I can think of is Python's [black](https://github.com/psf/black)), they will not return 0 if they can't parse or construct an AST.

In other words, it seems logical that if `scalac -Ystop-after:parser foo.scala` errors out, then `scalafmt` shouldn't act as if everything is ok.

**Comment by olafurpg** [comment]
The original motivation to ignore parse errors was that Scalafmt is not a linting tool to determine the correctness of your programs. The thinking was that your CI pipeline would fail with other tools like the scalac, sbt or ammonite.

I don't have a strong opinion on this today, except that flipping the switch will likely break a lot of people's builds. If we make the change we will need to communicate/document it clearly and ideally provide some option to get the old behavior.

**Comment by bsolomon1124** [comment]
> The thinking was that your CI pipeline would fail with other tools like the scalac, sbt or ammonite.

That's understandable; I guess at the least it could be better-advertised that scalafmt does not look for syntax errors/parse errors but rather is purely concerned with formatting.

We ended up adding a pipeline job in prior to `scalafmt` that runs `scalac -Ystop-after:parser` and a few other jobs, and that prevents `scalafmt` from being run if those initial sanity checks don't pass.

**Comment by olafurpg** [comment]
I'm BTW totally open to add a `--report-parse-errors` flag that makes Scalafmt return a non-zero exit code on parse errors. I estimate it would be easy to contribute if you're interested 😉

**Comment by bsolomon1124** [comment]
Update: I've found that setting `runner.fatalWarnings = true` in `.scalafmt.conf` has the desired effect here.  While this setting is not documented, it does seem to have a bit broader of a scope than raising from just parse errors alone, but that is fine in our case at least.
