### ISSUE TITLE
`trailingCommas = multiple` results in config parsing error

### ISSUE THREAD

**Issue by TJC** [scalameta/scalafmt#1838]
- **Version**: 2.4.2 (or is it?)
- **Integration**: sbt plugin sbt-scalafmt version 2.3.2
```
version = 2.4.2
trailingCommas = multiple
```

## Steps

When I run scalafmt like this:

```bash
sbt scalafmtAll
```

## Problem

```
[error] Unknown input 'multiple'. Expected one of: always, never, preserve: /Users/myusername/example/.scalafmt.conf
```

## Expectation

I assumed the documentation here would apply to the latest release of scalafmt.

https://scalameta.org/scalafmt/docs/configuration.html#trailing-commas

As of now, it refers to the option "multiple", that was added in 2716c44d88e3797

## Notes

I suspect it's simply the case that the online documentation is ahead of the general release, but this does result in confusion for users like me.

**Comment by poslegm** [comment]
Sorry for the confusion :(

We will release 2.5.0-RC1 with this setting support soon
