### ISSUE TITLE
Trailing comments force reformat

### ISSUE THREAD

**Issue by ekrich** [scalameta/scalafmt#1842]
I am really not sure about this issue but wanted to add it in case, I am not sure what the correct behavior should be honestly but preferred ignoring the trailing comment.
- **Previous Version**: 2.3.2
- **Configuration**:
```
version = 2.4.2
```

## Examples

Given code like this:
```scala
-    assert(Pattern.quote("1.5-2.0?") == "1\\.5-2\\.0\\?") // TODO: taken from re2j, behaviour might differ jdk
+    assert(
+      Pattern.quote("1.5-2.0?") == "1\\.5-2\\.0\\?"
+    ) // TODO: taken from re2j, behaviour might differ jdk
```
or
```scala
-    Array("", "x", "abc", "xaxbxcx", "false"), // with pattern that does not match the empty string.
+    Array("",
+          "x",
+          "abc",
+          "xaxbxcx",
+          "false"), // with pattern that does not match the empty string.
```
or
```scala
-    Test("a(b*)", "abbaab", 3, 0, 3, 1, 3, 3, 4, 4, 4, 4, 6, 5, 6), // fixed bugs
+    Test("a(b*)",
+         "abbaab",
+         3,
+         0,
+         3,
+         1,
+         3,
+         3,
+         4,
+         4,
+         4,
+         4,
+         6,
+         5,
+         6), // fixed bugs
```
## Expectation

I liked the previous behaviour.

## Workaround

Put the comment above the code that gets wrapped.

**Comment by poslegm** [comment]
It was introduced here https://github.com/scalameta/scalafmt/pull/1604. So it is not a bug but conscious change.

**Comment by ekrich** [comment]
Ok thanks. If nobody has any important feedback then I would be fine with closing this. 

For context, I am trying to upgrade Scala Native from 1.5.1 to the latest and the finish line keeps changing - https://github.com/scala-native/scala-native/pull/1714

I really appreciate the responsive support and the direction of scalafmt in general.

**Comment by kitbellew** [comment]
@ekrich is there any reason to write a comment if it can't be read?

**Comment by ekrich** [comment]
In later versions of `scalafmt` the 80 char default limit has gotten stricter and this change just forced us to change code that had been stable since version `1.5.1` and changed in the latest version `2.4.2` so I felt it should be reported. We only had a few cases.

**Comment by kitbellew** [comment]
perhaps you could use an `edition` around 2019-11 or before, that should get you older behaviour.
