### ISSUE TITLE
Format hexadecimal numbers consistently

### ISSUE THREAD

**Issue by ekrich** [scalameta/scalafmt#1844]
This is an enhancement request. Please format hexadecimal numbers throughout the code base.
My personal preference is to make them lowercase like the current e-notation default because lowercase stands out better against the numerals.
```
version = 2.4.2
```

## Steps

Given code like this:
```scala
private final val UINT_MAX = 0xFFFFFFFF
assertEquals(0x7F, buf.get(6))
```

When I run scalafmt.

## suggested format

Scalafmt should format code like this:
```scala
private final val UINT_MAX = 0xffffffff
assertEquals(0x7f, buf.get(6))
```

## Notes
Currently if the hexadecimal uses a suffix for the type like `L` the number format
gets cased along with the suffix case. They should be independent.

Combining e-notation and hexadecimal with types be independent of each other if there are settings to choose the preference. Defaults should be like the following:
```scala
2.028241e31f
1.9958403095347198e292d
0xffffffffL
assertEquals(0x838281807f7e7d7cL, buf.getLong())
```

**Comment by poslegm** [comment]
I think that reasonable to introduce `literals.hex` with default `Lower` to be consistent with other `literals.*` settings.
