### ISSUE TITLE
Literal format default changes hexadecimal numbers and potentially e-notation

### ISSUE THREAD

**Issue by ekrich** [scalameta/scalafmt#1845]
- **Configuration**:
```
version = 2.4.2
```

## Steps

Examples:
```scala
-      assertEquals(0x797a7b7c7d7e7f80L, longBuf1.get())
+      assertEquals(0x797A7B7C7D7E7F80L, longBuf1.get())

// this is okay but the default L would upper case or if
// you had the upper case D set and wanted lower case e
-    assertD2sEquals("1.0E7", 1.0E7d)
+    assertD2sEquals("1.0E7", 1.0e7d)

-    ((i3 & 0xffff).toLong << 32) | (i4.toLong & 0xffffffffL)
+    ((i3 & 0xffff).toLong << 32) | (i4.toLong & 0xFFFFFFFFL)

-  final val MIN_NORMAL        = 1.17549435E-38f
+  final val MIN_NORMAL        = 1.17549435e-38f
```

## Expectation

Scalafmt should change the type at the end of the numeric number consistently
like `f,d,L` but not change e-notation or hexidecimal number they are attached to.

## Workaround

Use the following non-default settings

```properties
# leave literals alone
literals.long = unchanged
literals.float = unchanged
literals.double = unchanged
```

**Comment by ekrich** [comment]
Related - https://github.com/scalameta/scalafmt/issues/1844

**Comment by poslegm** [comment]
I think that reasonable to introduce `literals.scientific` to be consistent with other `literals.*` settings.

But I am not sure about default. Usual I see lower `e` in codebases but it is open question.

**Comment by ekrich** [comment]
I noticed above that the e-notation's that didn't change are in string format so I suppose that part is fine. The current default is lower based on the diff above.

**Comment by ekrich** [comment]
> I think that reasonable to introduce `literals.scientific` to be consistent with other `literals.*` settings.

I think that is great.
> 
> But I am not sure about default. Usual I see lower `e` in codebases but it is open question.

I think that lower for the `e` and hex digits are easier to distinguish with numerals. The `L` for long is an exception because `l` can look like `1`. I think that is the logic anyway. Others could disagree so that is why there is a setting for preference or to avoid a big diff if the code base is one way or the other.
