### ISSUE TITLE
local comment configuration does not work

### ISSUE THREAD

**Issue by amesgen** [scalameta/scalafmt#1861]
This template is a guideline, not a strict requirement.
- **Version**: 2.4.2
- **Integration**: metals
- **Configuration**:
```
version = 2.4.2
```

## Steps

Given code like this:
```scala
object Test {
  // scalafmt: { trailingCommas = always }
  val coreDeps = Seq(
    "org.typelevel" %% "cats-core" % catsV,
    "org.typelevel" %% "cats-effect" % catsEffectV
  )
  // scalafmt: { trailingCommas = never }
}
```

When I run scalafmt like this:

via LSP code formatting (but also via a scalafmt binary)

## Problem

Scalafmt formats code like this:
```scala
object Test {
  // scalafmt: { trailingCommas = always }
  val coreDeps = Seq(
    "org.typelevel" %% "cats-core" % catsV,
    "org.typelevel" %% "cats-effect" % catsEffectV
  )
  // scalafmt: { trailingCommas = never }
}
```
(the same code)

## Expectation

I would like the formatted output to look like this:
```scala
object Test {
  // scalafmt: { trailingCommas = always }
  val coreDeps = Seq(
    "org.typelevel" %% "cats-core" % catsV,
    "org.typelevel" %% "cats-effect" % catsEffectV,
  )
  // scalafmt: { trailingCommas = never }
}
```
(note the trailing comma)

## Workaround

N.A.

## Notes

This does not seem to be related to `trailingCommas` specifically; in fact, the local configuration does not seem to work at all, which is confusing, as there exist tests for this e.g. [here](https://github.com/scalameta/scalafmt/blob/master/scalafmt-tests/src/test/resources/test/DynamicStyle.stat) at a quick glance.

**Comment by kitbellew** [comment]
just like any rewrite rule (even though it's not explicitly marked as such), `trailingCommas` is not implemented as a parameter that can be locally modified.

what _other_ local adjustments to configuration don't work?

**Comment by amesgen** [comment]
`align` and `maxColumn` also do not work.

**Comment by kitbellew** [comment]
> `align` and `maxColumn` also do not work.
> 
> e.g.
> 
> ```scala
> object Test {
>   // scalafmt: { maxColumn = 30 }
>   val coreDeps = Seq(
>     "org.typelevel" %% "cats-core" % catsV,
>     "org.typelevel" %% "cats-effect" % catsEffectV
>   )
> }
> ```
> 
> is idempotent.

this example uses infix operations, and scalafmt doesn't _yet_ format them (i.e., preserves line breaks, regardless of `maxColumn`). so your example wouldn't change.

the `format:off` block from your linked issue also _looked_ already aligned. can you share another example?

**Comment by amesgen** [comment]
Sorry for giving examples with unrelated issues ;) I hope this is helpful:

.scalafmt.conf:
```hocon
version = "2.4.2"
align = none
```
Test.scala
```scala
object Test {
  // scalafmt: { align = most }
  val coreDeps = Seq(
    "test" %% "test" % test,
    "test" % "testttttttttttttt" % "test"
  )
}
```

**Comment by kitbellew** [comment]
@poslegm you were looking into this recently, any ideas?

**Comment by poslegm** [comment]
@amesgen How are you running scalafmt? Latest example works fine for me:

```
~ scalafmt --stdin
object Test {
  // scalafmt: { trailingCommas = always }
  val coreDeps = Seq(
    "org.typelevel" %% "cats-core" % catsV,
    "org.typelevel" %% "cats-effect" % catsEffectV
  )
  // scalafmt: { trailingCommas = never }
}
object Test {
  // scalafmt: { trailingCommas = always }
  val coreDeps = Seq(
    "org.typelevel" %% "cats-core" % catsV,
    "org.typelevel" %% "cats-effect" % catsEffectV
  )
  // scalafmt: { trailingCommas = never }
}
```

**Comment by poslegm** [comment]
Hmm, I can prove that it is not working from IDEA. Will look at it later
