### ISSUE TITLE
What to do with local config overrides?

### ISSUE THREAD

**Issue by poslegm** [scalameta/scalafmt#1871]
Comment from #1856 

Fixed for alignment. But global problem is still here:
1. every contributor and code-reviewer can forgot the `styleMap` and look at the `initStyle`;
2. There is no documentation about what configs can't be overridden.

File override looks like more reliable and simple mechanism. What do you think, should we continue to support config overrides for code blocks or deprecate it in favor of file override?

More info in #1861

**Comment by kitbellew** [comment]
@poslegm i'd keep them :)
