### ISSUE TITLE
fileOverride settings are not used

### ISSUE THREAD

**Issue by yoohaemin** [scalameta/scalafmt#1881]
- **Version**: 2.5.0-RC1
- **Integration**: sbt, intellij
- **Configuration**:
```
version   = "2.5.0-RC1"
maxColumn = 120

fileOverride {
  "glob:*.sbt" {
    maxColumn = 180
  }
}
```

## Steps

Given code like this:
```scala
// build.sbt
lazy val verylongvariablenameverylongvariablenameverylongvariablenameverylongvariablenameverylongvariablenameverylongvariablenameverylongvariablename = 4
// line above is 153 chars
```

When I run scalafmt like this:

```bash
sbt scalafmtSbtCheck
```

## Problem
```
[warn] /path/to/project/build.sbt isn't formatted properly!
```

## Expectation
task succeeds.

## Notes
- reproduction: https://github.com/yoohaemin/scalafmt-fileoverride-bug

**Comment by kitbellew** [comment]
can you try `glob:**/*.sbt`?

**Comment by yoohaemin** [comment]
It works, thanks a lot! 
This would be a documentation issue then, the example in the website could be misleading.
