### ISSUE TITLE
Scalafmt fails to parse nested partial function

### ISSUE THREAD

**Issue by Katrix** [scalameta/scalafmt#1889]
- **Version**: 2.4.2
- **Integration**: IntelliJ

## Steps

Scalafmt fails to parse code like this. The `implicit` is important. It works without it.
```scala
function { implicit c =>
  {
    case bar => foo
  }
}
```

This also breaks
```scala
function(c => {
  case bar => foo
})
```

## Workaround

Define something before the partial function

```scala
function { implicit c =>
  5

  {
    case bar => foo
  }
}

**Comment by poslegm** [comment]
Hello! Can you please provide your `.scalafmt.conf`? It works fine on default settings.

**Comment by Katrix** [comment]
Oh, sorry. Assumed it would fail everywhere since it's a parse issue.

```hocon
version = "2.4.2"
project.git = true
style = defaultWithAlign
maxColumn = 120

danglingParentheses = true

assumeStandardLibraryStripMargin = true

rewrite.rules = [
  RedundantBraces,
  RedundantParens,
  SortModifiers,
  PreferCurlyFors
]
rewrite.redundantBraces.maxLines = 3
```

**Comment by poslegm** [comment]
Thank you. It's `RedundantBraces` bug.
