### ISSUE TITLE
Fail to align of case with CJK(East Asian Width) char

### ISSUE THREAD

**Issue by ncaq** [scalameta/scalafmt#1892]
- **Version**: scalafmt 2.5.0-RC1
- **Integration**: CLI
- **Configuration**:
```
version = "2.4.2"
```

## Steps

Given code like this:
```scala
object Main {
  def main(args: Array[String]) {
    val c = "あ"
    c match {
      case "あ" => println("い")
      case _ => println("")
    }
  }
}
```

When I run scalafmt like this:

```bash
scalafmt scalafmt-asia.scala
```

## Problem

Scalafmt formats code like this:
```scala
object Main {
  def main(args: Array[String]) {
    val c = "あ"
    c match {
      case "あ" => println("い")
      case _   => println("")
    }
  }
}
```

## Expectation

I would like the formatted output to look like this:
```scala
object Main {
  def main(args: Array[String]) {
    val c = "あ"
    c match {
      case "あ" => println("い")
      case _    => println("")
    }
  }
}
```

GitHub markdown render is odd.
Please see soure code in edit.

## Workaround

I can not found.

## Notes

[Halfwidth and fullwidth forms - Wikipedia](https://en.wikipedia.org/wiki/Halfwidth_and_fullwidth_forms)

**Comment by kitbellew** [comment]
@ncaq 
* how do you tell the difference between a fullwidth and a halfwidth?
* what is the width of each of them, compared to a regular `0`?
* does that width change between different monospaced fonts? if yes, this problem CANNOT be solved.

i tested with 35 of these characters:
```
// original
object a {
  def foo =
    c match {
      case "あああああああああああああああああああああああああああああああああああ" => bar
      case "aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa" => baz
      case _ => qux
    }
}
// aligned: +23 on github
object a {
  def foo =
    c match {
      case "あああああああああああああああああああああああああああああああああああ" => bar
      case "aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa"                        => baz
      case _ => qux
    }
}
```
to align, I needed to add 25 spaces in Menlo 12 font I use locally. on github's fixed font, that number is 23. So it looks like different fonts use different width. which means, this is intractable.

**Comment by ncaq** [comment]
> how do you tell the difference between a fullwidth and a halfwidth?

Unicode code point have Abbreviation of hull or half [Halfwidth and fullwidth forms - Wikipedia](https://en.wikipedia.org/wiki/Halfwidth_and_fullwidth_forms)
exclude "Ambiguous"(This is inherently ambiguous and even if you have a monospaced font, you have to give up because different fonts have different widths.)

If we use icu4j, for instance.

```
int ea = UCharacter.getIntPropertyValue(c, UProperty.EAST_ASIAN_WIDTH);
```

[UCharacter (ICU4J 67.1)](https://unicode-org.github.io/icu-docs/apidoc/released/icu4j/com/ibm/icu/lang/UCharacter.html)
[UCharacter.EastAsianWidth (ICU4J 67.1)](https://unicode-org.github.io/icu-docs/apidoc/released/icu4j/com/ibm/icu/lang/UCharacter.EastAsianWidth.html)

> what is the width of each of them, compared to a regular 0?

In a monospaced font, the widths of Wide and Fullwidth are generally twice zero.

> does that width change between different monospaced fonts? if yes, this problem CANNOT be solved.

Menlo does not include Japanese fonts, so proportional fonts may be used as a complement to Menlo.
A full-width character is always twice as long as a half-width character in a normal monospaced font used for programming by people living in CJK (Chinese, Japan, Korea) cultures.
For example, MS Gothic, Consolas + Meiryo and M+ M Type-1 (RictyDiminished) have this feature.
However, Source Han Code JP full-width characters are three times longer than half-width characters.
For verification, RictyDiminished, which is free and easy to use, may be a good choice.

[edihbrandon/RictyDiminished: Ricty Diminished --- fonts for programming](https://github.com/edihbrandon/RictyDiminished)

**Comment by kitbellew** [comment]
@olafurpg @poslegm @tanishiking @lihaoyi-databricks do you think it's a reasonably common use-case presented here, to add a new external dependency on the icu4j library?

the case here is strictly limited to aligning, and my concern is in the width being dependent on the font, and two fonts i tried add a different width (for 35 chars, one adds 23 and the other 25). the one i used, Menlo, seems to space a few of CJK characters I tried *exactly the same*, and not proportionally as the author claims (I tried wide ones: `あ`, `セ`, `ヵ`, `ヽ`, `きゃ`; and narrow `ｶ`, `ｾ` are not adding extra width and look like a regular `a`).

we can add a parameter to specify the ratio of wide-to-narrow (1.714 and 1.657 for those two fonts i tried) to enable and treat this case, but if another user is reading the resulting code using a different font... well, what's the point?

**Comment by olafurpg** [comment]
Thank you for reporting! The icu4j library weighs 13mb, which is more than what I'm comfortable with adding to the Scalafmt footprint to support this use-case. It would be a different story if the library was <1mb. 
```
❯ cs fetch 'com.ibm.icu:icu4j:67.1' | xargs du -h
 13M	/Users/lgeirsson/Library/Caches/Coursier/v1/https/repo1.maven.org/maven2/com/ibm/icu/icu4j/67.1/icu4j-67.1.jar
```

Is there a more lightweight way to detect what characters are half/full width? (just brainstorming, I'm not at all an expert in this domain) can we somehow reach a tradeoff where we solve 80% of the problem with a simpler solution?

**Comment by poslegm** [comment]
[StackOverflow](https://stackoverflow.com/a/35666229/5309954) suggests such way: 

```
@ "ア".getBytes("MS932").length
res0: Int = 2

@ "a".getBytes("MS932").length
res1: Int = 1

@ "A".getBytes("MS932").length
res2: Int = 1

@ "あ".getBytes("MS932").length
res3: Int = 2
```

But I'm pretty bad at unicode encoding and not sure that it's quite generic and reliable solution.

**Comment by kitbellew** [comment]
> [StackOverflow](https://stackoverflow.com/a/35666229/5309954) suggests such way:
> 
> ```
> @ "ア".getBytes("MS932").length
> res0: Int = 2
> 
> @ "a".getBytes("MS932").length
> res1: Int = 1
> 
> @ "A".getBytes("MS932").length
> res2: Int = 1
> 
> @ "あ".getBytes("MS932").length
> res3: Int = 2
> ```
> 
> But I'm pretty bad at unicode encoding and not sure that it's quite generic and reliable solution.

MS932 is only for Japanese. I don't know if C or K have the same issue.

**Comment by kitbellew** [comment]
@ncaq let's do it this way: if you provide the code implementing the following method, without using any additional libraries not already sourced by scalafmt, we will use it:
```
  def getCountOfCjkWideChars(str: String): Int

  // test
  val str = "aあbｶcヵ"
  require(str.length == 6)
  require(getCountOfCjkWideChars(str) == 2)
```

**Comment by ncaq** [comment]
MS932(CP932)(Shift_JIS) solution is not enough limited Japanese.
for example

```
scala> "𠮟".getBytes("MS932").length
"𠮟".getBytes("MS932").length
val res5: Int = 1
```

Because Shift_JIS do not have "𠮟" .

**Comment by ncaq** [comment]
> @ncaq let's do it this way: if you provide the code implementing the following method, without using any additional libraries not already sourced by scalafmt, we will use it:

I went back and looked into it.
It seems that there is at least a function to identify Unicode blocks in the Java standard library.
I couldn't find one that returns a string width, though.

```
scala> java.lang.Character.UnicodeBlock.of('あ')
java.lang.Character.UnicodeBlock.of('あ')
val res6: Character.UnicodeBlock = HIRAGANA

scala> java.lang.Character.UnicodeBlock.of('a')
java.lang.Character.UnicodeBlock.of('a')
val res7: Character.UnicodeBlock = BASIC_LATIN

scala> java.lang.Character.UnicodeBlock.of('ｱ')
java.lang.Character.UnicodeBlock.of('ｱ')
val res8: Character.UnicodeBlock = HALFWIDTH_AND_FULLWIDTH_FORMS

scala> java.lang.Character.UnicodeBlock.of('ア')
java.lang.Character.UnicodeBlock.of('ア')
val res9: Character.UnicodeBlock = KATAKANA
```

Also, I think the functions would be better to be unified like displayWidth.
This is because there are some non-CJK characters such as emoticons,
I think it's better to get the width of the string all the way through this function instead of length.

```
def displayLength(str: String): Int
```
