### ISSUE TITLE
2.5.0-RC1: Alignment is too aggressive, aligns over unrelated expressions

### ISSUE THREAD

**Issue by neko-kai** [scalameta/scalafmt#1896]
- **Version**: 2.5.0-RC1
- **Configuration**:
```
version = "2.5.0-RC1"
align.tokens.add = ["="]
```

## Steps

Given code like this, formatted with scalafmt `2.4.2`:

```scala
object fmt {
  val header  = JwtHeader(algorithm = Some(JwtAlgorithm.HMD5))
  val content = payload.toString
  val claim   = JwtClaim(content = content)
}
```
## Problem

Scalafmt re-formats this code like this, on `2.5.0-RC1`:
```scala
object fmt {
  val header  = JwtHeader(algorithm = Some(JwtAlgorithm.HMD5))
  val content = payload.toString
  val claim   = JwtClaim(content    = content)
}
```

## Workaround

Setting `align = most` instead of adding `=` makes equals align only for `val _ =`, but not in expressions. However, this _removes_ alignment in "config-style" applications like:
```scala
JwtClaim(
  abc     = cba,
  content = content
)
```
->
```scala
JwtClaim(
  abc = cba,
  content = content
)
```

## Expectation

Expected the output to not change. the `=` on 3rd line aligns over to `=` on first line in completely unrelated expression, which seems like too much.

Note the alignment for `val _ =` is expected to be preserved for multiple vals in a row...

**Comment by neko-kai** [comment]
I've updated the minimal config above.

**Comment by poslegm** [comment]
Works well with
```
align.tokens.add = [{code = "=", owner = "(Enumerator.Val|Defn.(Va(l|r)|Def|Type))"}]
```

The problem is in counterintuitive defaults: scalafmt adds any owner if you didn't specified it. I think that better approach would be to add default owner if not specified and `.*` only if user added it explicitly.

What about config-style alignment: currently you can get it with
```
align.tokens.add = [{code = "=", owner = "(Enumerator.Val|Defn.(Va(l|r)|Def|Type)|Term.Assign)"}]
```
But it may be **too** much because it will align all assignments. So, it's a subject for another feature request.

**Comment by poslegm** [comment]
@neko-kai please see https://github.com/scalameta/scalafmt/pull/1914

`align.tokens.add` will work more convenient in next release. Current workaround is explicit `owner` in config.

**Comment by neko-kai** [comment]
@poslegm Hmm, this does not address the problem of alignment over unrelated expressions. In scalafmt-2.4.2, even with an explicit `owner: ".*"` or `owner: "(Enumerator.Val|Defn.(Va(l|r)|Def|Type)|Term.Assign|Term.Param)"` it did not align unrelated lines, but it did align 'config-style' parameters within the _same_ applicaton.

On scalafmt 2.4.2 this stays the same:

```
version = "2.4.2"
align.tokens.add = [{ code: "=", owner: "(Enumerator.Val|Defn.(Va(l|r)|Def|Type)|Term.Assign|Term.Param)" }]
```

```scala
object fmt {
  val header  = JwtHeader(algorithm = Some(JwtAlgorithm.HMD5))
  val claim   = JwtClaim(content = content)
  val content = makePayloadStr(paymentId, userId, template)
}
```

But if you move the parameter `content` up into JwtHeader, it becomes aligned to the `=` in `algorithm` parameter - the behavior is not caused by ignoring `Term.Param` or `Term.Assign` owner, they're explicitly included:

```scala
object fmt {
  val header = JwtHeader(
    algorithm = Some(JwtAlgorithm.HMD5),
    content   = content
  )
  val claim   = JwtClaim()
  val content = makePayloadStr(paymentId, userId, template)
}
```

I'm not sure it's exactly subject to a feature request because that's how it worked in the immediate prior version...

**Comment by poslegm** [comment]
Previous behavior has a bug: it didn't align tokens with same owner on the tail of row. So the alignment with `Term.Assign` worked pretty by a happy coincidence.

I agree that align with `Term.Assign` is ugly and will work on specifying owner more accurate in this case to achieve config-style alignment without aligning all assignments at all. It may be possible to do this by working with `Term.Assign` owner or creating dedicated setting for config-style arguments.

**Comment by poslegm** [comment]
Created issue for this https://github.com/scalameta/scalafmt/issues/1921
