### ISSUE TITLE
Please share pre-built binaries for release v2.5.0 ?

### ISSUE THREAD

**Issue by vn971** [scalameta/scalafmt#1935]
Same as release v2.4.2 had it https://github.com/scalameta/scalafmt/releases/tag/v2.4.2
, can you please add pre-built binaries for `scalafmt-linux.zip` and `scalafmt-macos.zip` ?

I'm maintaining this package on AUR (ArchLinux): https://aur.archlinux.org/packages/scalafmt-native-bin/
It would be nice to update it with the latest scalafmt binaries ^^

**Comment by poslegm** [comment]
Small problems with CI, working on it. Native images will be attached to release soon

**Comment by vn971** [comment]
Thanks!

**Comment by poslegm** [comment]
Binaries are ready, thank you very much for package maintaining!

**Comment by vn971** [comment]
Hi, is it possible to again publish binaries for release v2.5.1 ?

**Comment by poslegm** [comment]
Done

**Comment by vn971** [comment]
Hi! It happens again from time to time. While I do appreciate the manual work, I'm also thinking, is it possible to make it part of the automated release process somehow?

**Comment by poslegm** [comment]
Yes, there is a possibility to automate it: https://ctrpeach.io/posts/scala-console-native-github/
[Example](https://github.com/scalameta/fastpass/blob/a29572224818224226dc1a86d7d96998d55200c0/.github/workflows/native.yml#L34-L43).

I want to do it when I have free time. And contributions are welcome :)

**Comment by vn971** [comment]
Is it possible to release pre-built binaries for 2.7.0 or 2.7.1 ?

**Comment by poslegm** [comment]
![Screenshot 2020-09-14 at 23 15 36](https://user-images.githubusercontent.com/4687050/93133627-345f7600-f6e0-11ea-9119-d80c64e2f10c.png)

They already attached to release notes

**Comment by vn971** [comment]
Oh thanks!
I didn't notice that the new CI is up, the build instruction was pointing at the old "zip" location. It's working now :)
