### ISSUE TITLE
The Discord Link in the Readme is not working.

### ISSUE THREAD

**Issue by busti** [scalameta/scalafmt#1942]
When I follow the Discord link, which is linked at the top of the readme document, I get this cryptic error message from discord:  
![image](https://user-images.githubusercontent.com/3575167/80894615-d6a43180-8cdc-11ea-9be3-a0f737dee6ff.png)
  
This is the link I followed:  
https://discordapp.com/channels/632642981228314653/632665341864181780  

I would be delighted if you could replace it with a valid invite link to the "server".

**Comment by poslegm** [comment]
Thank you for reporting! Link fixed, please try it

**Comment by busti** [comment]
Can confirm, the link does now work again.
