### ISSUE TITLE
Multiline alignment offset issue

### ISSUE THREAD

**Issue by ghostdogpr** [scalameta/scalafmt#1948]
- **Configuration**:
```
version = 2.5.1
align = most
```

## Steps

Given code like this:
```scala
for {
  superLongVariableName <- Option(2)
  a <- Option(2).flatMap { s =>
         if (s == 1) Option(1)
         else Option(2)
       }
} yield (superLongVariableName, a)
```

When I run scalafmt like this:

```bash
scalafmt
```

## Problem

The offset applied before the second `<-` is not applied to the lines below.

Scalafmt formats code like this:
```scala
for {
  superLongVariableName <- Option(2)
  a                     <- Option(2).flatMap { s =>
         if (s == 1) Option(1)
         else Option(2)
       }
} yield (superLongVariableName, a)
```

## Expectation

I would like the formatted output to look like this:
```scala
for {
  superLongVariableName <- Option(2)
  a                     <- Option(2).flatMap { s =>
                             if (s == 1) Option(1)
                             else Option(2)
                           }
} yield (superLongVariableName, a)
```

**Comment by poslegm** [comment]
Behavior for `align.preset=most` is OK, because it shouldn't align entire block statement by `<-`. In ideal world issue should be fixed with

```
align.preset=most
align.arrowEnumeratorGenerator=true
```

But there is a bug in `align.arrowEnumeratorGenerator`: it indents block to _origin_ position of `<-` before alignment. Therefore it necessary to fix `arrowEnumeratorGenerator` first

**Comment by kitbellew** [comment]
@poslegm i think this is a slightly more difficult problem. we should fix indentation of lines following a token which uses a `StateColumn` indentation and which is itself aligned. `arrowEnumeratorGenerator` is simply one such case.
