### ISSUE TITLE
Upgrading to 2.5.1 Causes Extremely Large Diff and Compilation Failure

### ISSUE THREAD

**Issue by adamgfraser** [scalameta/scalafmt#1952]
In ZIO we were previously on version 2.4.2 with a configuration file that looked like this:

```scala
version = "2.4.2"
maxColumn = 120
align = most
continuationIndent.defnSite = 2
assumeStandardLibraryStripMargin = true
docstrings = JavaDoc
lineEndings = preserve
includeCurlyBraceInSelectChains = false
danglingParentheses = true
spaces {
  inImportCurlyBraces = true
}
optIn.annotationNewlines = true

rewrite.rules = [SortImports, RedundantBraces]

project.excludeFilters = [
  "core/shared/src/main/scala/zio/Has.scala",
  "core/shared/src/main/scala/zio/ZLayer.scala",
  "core/shared/src/main/scala-2.x/zio/VersionSpecific.scala"
]
```

I just tried to upgrade to version 2.5.1 and made what I thought were minimal changes to upgrade the version number and use `align.preset` instead of `align` and `danglingParentheses.preset` instead of `danglingParentheses`:

```scala
version = "2.5.1"
maxColumn = 120
align.preset = most
continuationIndent.defnSite = 2
assumeStandardLibraryStripMargin = true
docstrings = JavaDoc
lineEndings = preserve
includeCurlyBraceInSelectChains = false
danglingParentheses.preset = true
spaces {
  inImportCurlyBraces = true
}
optIn.annotationNewlines = true

rewrite.rules = [SortImports, RedundantBraces]

project.excludeFilters = [
  "core/shared/src/main/scala/zio/Has.scala",
  "core/shared/src/main/scala/zio/ZLayer.scala",
  "core/shared/src/main/scala-2.x/zio/VersionSpecific.scala"
]
```

When I then format I get a massive diff that impacts about every file in our code base with a lot of formatting that looks poor (e..g `=` set far to the right after function definition), some that seem like very poor style (e.g. removing braces around `else` branch of a condition when `if` branch also has braces and branches perform side effects), and some that make the code fail to compile entirely (e.g. removing braces around right hand side of the below code in our `build.sbt` file).

```
scalacOptions ~= _ filterNot (_ startsWith "-Xlint")
```

Is there some way we can recover something closer to the previous formatting and functionality? We like to stay on the latest version and understand that in a large code base the details of how some things are formatted are going to change slightly over time. But it would be great to have more stability in these changes. Perhaps it would be possible to check that the output of formatting changes continues to compile with a sample of libraries, and at least before doing a release that it looks reasonable?

**Comment by poslegm** [comment]
Hello!

> (e..g = set far to the right after function definition)

I guess that [align.multiline = false](https://scalameta.org/scalafmt/docs/configuration.html#alignmultiline) will help you.

> (e.g. removing braces around else branch of a condition when if branch also has braces and branches perform side effects)

[rewrite.redundantBraces.generalExpressions = false](https://scalameta.org/scalafmt/docs/configuration.html#configuration-options) (also I am thinking about extracting if-else braces into dedicated setting)

> (e.g. removing braces around right hand side of the below code in our build.sbt file)

Created https://github.com/scalameta/scalafmt/issues/1953. Please try to add

```
fileOverride {
  "glob:**/*.sbt" {
    rewite.rules=[]
  }
}
```
to your config, it may solve the problem.

What other formatting problems do you have?

> Perhaps it would be possible to check that the output of formatting changes continues to compile with a sample of libraries

Yes, it would be great to have something like community build for scalafmt, but it hard to verify compilation of large codebase, it requires a lot of time and computing power. For now I don't know how to do it.

P.S. Thank you very much for ZIO maintaining, it's a great library and we have a lot of benefits by it production usage.

**Comment by kitbellew** [comment]
@adamgfraser we tried to describe the defaults that have changed in the new release, please review and let us if anything is missing: https://github.com/scalameta/scalafmt/releases/tag/v2.5.0

as to the `scalacOptions` bug, i will fix it and release in 2.5.2.

**Comment by kitbellew** [comment]
@adamgfraser can this be closed? the bug is fixed, and @poslegm explained how to change the parameters.

**Comment by adamgfraser** [comment]
@kitbellew Sorry for the delay on my end. Let me try to use this to get ZIO onto the latest version and then will close this. Thanks for your help and appreciate everything you do in writing this tool. I know it can be a thankless job sometimes. 😄

**Comment by poslegm** [comment]
resolved https://github.com/zio/zio/pull/4106
