### ISSUE TITLE
Invalid fields: ctorSite

### ISSUE THREAD

**Issue by bkhuong** [scalameta/scalafmt#1955]
I am getting an invalid field error when trying to specify the `continuationIndent.ctorSite` field. 
 
- **Version**: 2.5.1 (set from the conf file)
- **Integration**: IntelliJ
- **Scalafmt plugin version**: 1.5.1
- **Configuration**:
```
version = 2.5.1
maxColumn = 120
continuationIndent.defnSite = 2
continuationIndent.ctorSite = 2
```

## Steps
1. add `continuationIndent.ctorSite = 2` to configuration file 
2. code -> reformat with scalafmt 
3. invalid fields error 

## Problem
Won't reformat with `continuationIndent.ctorSite` when version is specified as > 2.5.0

## Expectation
Reformats with `continuationIndent.ctorSite` when version is specified as >2.5.0 

![image](https://user-images.githubusercontent.com/40499864/81201964-c8734100-8f7a-11ea-83cb-3df7a456dc29.png)

**Comment by poslegm** [comment]
What version of IDEA and Scala Plugin do you have?

**Comment by kitbellew** [comment]
@poslegm I think @bkhuong explicitly specified that "scala plugin version 1.5.1" is being used, and it doesn't support dynamic loading of newer versions.

**Comment by bkhuong** [comment]
Yup! @kitbellew is correct, I am using scala plugin version 1.5.1. 

For IDEA: 
- IntelliJ IDEA 2020.1.1 (Ultimate Edition)
- Build #IU-201.7223.91, built on April 29, 2020
- Runtime version: 11.0.6+8-b765.40 x86_64
- VM: OpenJDK 64-Bit Server VM by JetBrains s.r.o
- macOS 10.15.2
- GC: ParNew, ConcurrentMarkSweep
- Memory: 1979M
- Cores: 16
- Registry: documentation.show.toolbar=true
- Non-Bundled Plugins: Lombook Plugin, org.scalafmt.ScalaFmt, Pythonid, org.intellij.scala, com.spotify.scio-idea

Correct me if i'm wrong, but 1.5.1 seems to be the highest version of the plug-in that I am able to install for intellij.

**Comment by kitbellew** [comment]
@bkhuong uninstall the scalafmt plugin. keep the scala plugin.

**Comment by bkhuong** [comment]
Oh awesome, it's working! Thank you :)
