### ISSUE TITLE
scalafmt cli does not respect excludes for files past in on the command line

### ISSUE THREAD

**Issue by ShaneDelmore** [scalameta/scalafmt#1964]
This template is a guideline, not a strict requirement.
- **Version**: 2.5.1
- **Integration**: None
- **Configuration**:
```
# Format method declarations as follows when they exceed line length:
# def callMeMaybe(
#   number: Option[String],
#   typeOfPhone: String,
#   hoursOfAvailability: Range = 9.to(12)
# ) (
#    areaCodeFilter: String => Boolean
# ): Boolean = {

align.preset = none

assumeStandardLibraryStripMargin = false

binPack.parentConstructors = false

continuationIndent.callSite = 2
continuationIndent.defnSite = 2

danglingParentheses.preset = false
danglingParentheses.defnSite = true

docstrings = JavaDoc

literals.double = Unchanged
literals.float = Unchanged
literals.long = Unchanged

maxColumn = 100

newlines.sometimesBeforeColonInMethodReturnType = false
newlines.implicitParamListModifierForce = [before]
newlines.neverInResultType = false
newlines.alwaysBeforeMultilineDef = false

# Do not force breaks inside of chains. This prevents the following fmt change, e.g.:
#   client
# -   .consumer.sessionTimeout(30.seconds)
# -   .consumer.heartbeatInterval(1.second)
# +   .consumer
# +   .sessionTimeout(30.seconds)
# +   .consumer
# +   .heartbeatInterval(1.second)
#
# However, long chains will no longer be broken, e.g.:
#   client.consumer.sessionTimeout(30.seconds).consumer.heartbeatInterval(1.second)
#
# Note: if the chain is longer than maxColumn, it will be broken irrespective of the chain, e.g.:
#   client
# -   .consumer.sessionTimeout(30.seconds).consumer.heartbeatInterval(1.second).producer.retries(300)
# +   .consumer.sessionTimeout(30.seconds).consumer.heartbeatInterval(1.second).producer.retries(
# +     300
# +   )
optIn.breaksInsideChains = true

project.git = true
project.excludeFilters = [
  ".*/bin/.*"
  ".*/config/.*"
  ".*/console/.*"
  ".*/experimental/.*"
  ".*/repl/.*"
  ".*/resources/.*"
  ".*/sandbox/.*"
  ".*/scripts/.*"
  ".*/templates/.*"
  "3rdparty/.*"
]

rewrite.redundantBraces.generalExpressions = false

runner.optimizer.escapeInPathologicalCases = false

spaces.inImportCurlyBraces = false
spaces.afterTripleEquals = true

trailingCommas = preserve

version = "2.5.1"

verticalMultiline.atDefnSite = true
verticalMultiline.newlineAfterOpenParen = true
```

## Steps

Given code like this:
```scala
val foo = "bar"
```

When I run scalafmt like this:

```bash
scalafmt config/foo.scala
```

## Problem

Scalafmt outputs the message:
```bash
...foo.scala:1: error: expected class or object definition
val foo = "bar"
^
```

## Expectation

I would like scalafmt to do nothing and respect the exclude filter. The reason is I call scalafmt various ways with file lists, from build tools that supply lists of files, from git ls-files, from git diff --name-only, using xargs with file lists, etc..

**Comment by ShaneDelmore** [comment]
If people generally like the convention of overriding the exclude list by passing a filename, then it would be nice to at least have an extra flag in the config or that I can pass by command line to say "force-exclusions" or something of that nature.

**Comment by kitbellew** [comment]
@ShaneDelmore try a workaround: use the 2.5.1 scalafmt and remove the version from config. i think, looking at the code, `ScalafmtDynamicRunner` doesn't filter explicitly provided files, whereas `ScalafmtCoreRunner` does.

**Comment by ShaneDelmore** [comment]
If I do that, IJ won't have the right version of the formatter.  I was thinking this should change https://github.com/scalameta/scalafmt/blob/master/scalafmt-cli/src/main/scala/org/scalafmt/cli/ScalafmtRunner.scala#L58-L60

**Comment by ShaneDelmore** [comment]
@pjrt I saw the comment in your name, would you like to weigh in on this?

**Comment by ShaneDelmore** [comment]
I could make a pr removing that special case unless --ignore-exclude-filters is passed in as an override.  Still catching up on the codebase and trying to see where I should add the override.

**Comment by pjrt** [comment]
Been a while, but what that comment is saying is that, if you pass a file, verbatim, then that fill will be ran. 

Kind of odd for filter rules to apply when u pass a file directly into the cli, but maybe that's just me.

**Comment by ShaneDelmore** [comment]
I did the test of removing the version from .scalafmt.conf and it still has the same issue. I understand what the comment was saying, I just thought it was a behavior that made integration with other tools difficult. I thought a --force flag would work but @olafurpg said he preferred an --ignore-exclude-filters flag. 

With the current state, there is no way for tools that want to call scalafmt to be able to prevent over-riding the excludes.

**Comment by pjrt** [comment]
I would think I did that because there are already several ways to get files in scalafmt (--mode, git integration, etc). 

I see no issue with making direct-injected files following the filtering rules and having a `--ignore-exclude-filers`.

**Comment by ShaneDelmore** [comment]
Great, I'll make a pr.  I have tooling at work that doesn't quite line up with any of those modes and it doesn't make sense to teach scalafmt about them so this will be helpful, thanks.

**Comment by kitbellew** [comment]
@ShaneDelmore let me know if you are planning this PR soon, as i was going to release 2.5.3 shortly.

**Comment by ShaneDelmore** [comment]
Thanks for handling this, I ended up out sick for quite some time and haven't looked at my computer in a while.  This was a pleasant surprise to come back to 👍
