### ISSUE TITLE
Format .sc Ammonite and Mill files

### ISSUE THREAD

**Issue by joan38** [scalameta/scalafmt#1966]
It would be cool if scalafmt was formatting .sc files which are used for Ammonite and Mill.
Generally it works except 2 corner cases:
- Top level definitions such as:
  ```scala
  def a = {
    "sdcfs"
    ""
  }
  ```
  are formatted:
  ```scala
  def a = {
      "sdcfs"
      ""
    }
  ```
- With Ammonite (thus Mill too) you can reload the interpreter with `@`. Useful for example to add repositories (see [an example here](http://www.lihaoyi.com/mill/page/thirdparty-modules.html#ensime)). That `@` is failing scalafmt to format.

Thanks

**Comment by poslegm** [comment]
Hello!

Can you please provide your `.scalafmt.conf` and full source file with first case?

About `@`: I didn't found scalameta [dialect](https://github.com/scalameta/scalameta/blob/master/scalameta/dialects/shared/src/main/scala/scala/meta/Dialect.scala) rule for support ammonite scripts syntax. We may need to add new dialect to scalameta first. However, I'm not sure if ammonite support is included in plans and ideology of scalameta library.

**Comment by ShaneDelmore** [comment]
My codebase has plenty of scala script files like this as well, but named *.scala. It would be great if I could add a config to allow falling back to script syntax automatically if no top level def was found.

**Comment by ShaneDelmore** [comment]
And simple example of what I might have in my repo in .sc or .scala files:
```
#!/usr/bin/env scala

println("running a scala script")
```

**Comment by joan38** [comment]
Nice thanks !

**Comment by kitbellew** [comment]
> Nice thanks !

I couldn't reproduce your problem with indentation, btw.
