### ISSUE TITLE
Control newline formatting of `extends` and `with`

### ISSUE THREAD

**Issue by jalaziz** [scalameta/scalafmt#1973]
- **Version**: 2.5.2
- **Integration**: IntelliJ
- **Configuration**:
```
version = 2.5.2
preset = IntelliJ
optIn.configStyleArguments = true
continuationIndent.extendSite = 0
continuationIndent.withSiteRelativeToExtends = 0
maxColumn = 160
docstrings = ScalaDoc
assumeStandardLibraryStripMargin = true
align.preset = some
spaces.inImportCurlyBraces = true
trailingCommas = multiple
danglingParentheses.exclude = []
verticalMultiline.atDefnSite = true
verticalMultiline.newlineAfterOpenParen = true
verticalMultiline.excludeDanglingParens = []
rewrite.rules = [AvoidInfix, SortModifiers, PreferCurlyFors]
```

## Steps

Given code like this:
```scala
trait Bar {}
trait Baz {}
case class Foo(
  a: Boolean,
  b: String,
  c: String,
) extends Bar with Baz
```

When I run scalafmt like this:

```bash
sbt scalafmtAll
```

## Problem

Scalafmt formats code like this:
```scala
trait Bar {}
trait Baz {}
case class Foo(
  a: Boolean,
  b: String,
  c: String,
)
extends Bar
with Baz
```

## Expectation

I would like the formatted output to look like this:
```scala
trait Bar {}
trait Baz {}
case class Foo(
  a: Boolean,
  b: String,
  c: String,
) extends Bar with Baz
```

## Notes

I realize this has been partially brought up before in #276. However, I can not seem to get `extends` on the same line as the closing parens even with `optIn.configStyleArguments`. What's also less than idea, is that the `with` statements always appear on their own line, even when there is plenty of space on the line.

As far as I've been able to tell, there are no configuration keys for controlling newlines around `extends` and `with` statements.

**Comment by poslegm** [comment]
Newline before `extends` always forces for multiline class definitions. I think that it can be changed [here](https://github.com/scalameta/scalafmt/blob/master/scalafmt-core/shared/src/main/scala/org/scalafmt/internal/Router.scala#L569-L581) but I still doubt the necessity of this possibility.

**Comment by jalaziz** [comment]
The second part of the the issue is the way `with` is handled when `extends` is broken into a newline.

It seems `with` statements will always end up on their own line if `extends` is forced onto a new line.

For example:
```scala
trait Bar {}
trait Baz {}
case class Foo(param1: String, param2: String, param3: String, param4: String, param5: String)(implicit val someImplicit: Int) extends Bar with Baz with StrictLogging
```

become:
```scala
trait Bar {}
trait Baz {}
case class Foo(param1: String, param2: String, param3: String, param4: String, param5: String)(implicit val someImplicit: Int)
extends Bar
with Baz
with StrictLogging
```

I'd argue that's not the greatest formatting given the fact that parameter definition is kept on one line. It effectively always favors vertical formatting.

**Comment by poslegm** [comment]
I am not completely sure but perhaps we should implement horizontal-friendly formatting for `extends` block in `newlines.source=fold`.

@kitbellew what do you think? Is it consistent with other `fold` rules?

**Comment by jalaziz** [comment]
Just in case it's missed, I've updated my original comment with the wording and style from the official scala style guide.

**Comment by jalaziz** [comment]
Actually, it seems like I can achieve the Scala style version with `with` statements on their own line with:
```
version = 2.5.2
preset = IntelliJ
optIn.configStyleArguments = true
continuationIndent.extendSite = 2
continuationIndent.withSiteRelativeToExtends = 0
maxColumn = 160
docstrings = ScalaDoc
assumeStandardLibraryStripMargin = true
align.preset = some
spaces.inImportCurlyBraces = true
trailingCommas = multiple
danglingParentheses.exclude = []
verticalMultiline.newlineAfterOpenParen = true
verticalMultiline.excludeDanglingParens = []
rewrite.rules = [AvoidInfix, SortModifiers, PreferCurlyFors]
```

I'm not sure if it correctly formats everything yet, but seems to work. So, while, folding `with` would be nice, it seems like the trick I was missing was setting `continuationIndent.extendSite`.

**Comment by kitbellew** [comment]
> I'm not sure if it correctly formats everything yet, but seems to work. So, while, folding `with` would be nice, it seems like the trick I was missing was setting `continuationIndent.extendSite`.

What's happening is that `scalafmt` inserts a newline here, but it's a special newline which is converted into a space if indenting shifts farther to the right than without it:

so
```
class A (
  foo: Int
)
extends B
class A (
  foo: Int
)
 extends B
```
are kept, but
```
class A (
  foo: Int
)
  extends B
```
is output as
```
class A (
  foo: Int
) extends B
```
