### ISSUE TITLE
Unable to format pattern-matching containing backquotes

### ISSUE THREAD

**Issue by ikempf** [scalameta/scalafmt#1974]
```
version = 2.5.2
(Already encountered the issue in 2.3.2)
```

## Steps
Given code like this:
```scala
"" match {
  case ok: String => ()
  case `nok`: String => ()
}
```

When I run scalafmt like this:
sbt => `scalafmtAll` (tried with sbt-scalafmt 2.2.1 and 2.4.0)

## Problem

Scalafmt fails formatting:
```bash
/.../Main.scala:6: error: => expected but : found
    case `nok`: String => ()
              ^: /.../Main.scala
(Compile / scalafmt) /.../Main.scala:6: error: => expected but : found
    case `nok`: String => ()
              ^: /.../Main.scala
```

## Workaround
Rename the variables to avoid needing the backquotes.

**Comment by kitbellew** [comment]
@ikempf why do you put the type `: String` after your pattern? I am not sure that's valid scala syntax, as `nok` has a type already.

**Comment by poslegm** [comment]
Interesting :thinking: 

```scala
@ "" match {
    case ok: String => println("ok")
    case `nok`: Int => println("nok")
  }
cmd1.sc:3: scrutinee is incompatible with pattern type;
 found   : Int
 required: String
  case `nok`: Int => println("nok")
              ^
Compilation Failed

@ "" match {
    case ok: String => println("ok")
    case `nok`: String => println("nok")
  }
ok
```

(Scala 2.13.2)

**Comment by kitbellew** [comment]
point is, if you don't put the type, it works. backquotes in case matching are used to match an existing variable, rather than assign a new variable name to the matching pattern.

in any case, this should be filed in scalameta, not here, as that's where parsing is implemented.
