### ISSUE TITLE
beforeContextBoundColon preset deprecation warning

### ISSUE THREAD

**Issue by mikail-khan** [scalameta/scalafmt#1976]
As discussed on the Discord channel, the following is producing the preset deprecation warning:

```
Never$: top-level presets deprecated; use 'preset' subsection

spaces {
  beforeContextBoundColon = true
  inImportCurlyBraces = false
  beforeContextBoundColon = false
}
```

According to @poslegm this is a bug related to `beforeContextBoundColon` reading.

**Comment by poslegm** [comment]
Sorry, I deceived you :(

You have duplicated key `beforeContextBoundColon` with different values. 

```
spaces {
  beforeContextBoundColon = Never
  inImportCurlyBraces = false
}

# or

spaces {
  beforeContextBoundColon = Always
  inImportCurlyBraces = false
}
```

works well.

But error message should be definitely more informative in this case.

**Comment by mikail-khan** [comment]
doh! :facepalm: thanks

**Comment by mikail-khan** [comment]
I took out the duplicate config but I still get the warning. Here is the complete config file:

```
version=2.5.2
maxColumn = 120
lineEndings = unix
importSelectors = singleLine

project {
  git = true
}

preset = defaultWithAlign
align.preset = most

align {
  tokens = [ {code = "=>", owner = "Case|Type.Arg.ByName"}, "=", "<-", "->", "%", "%%", "should", "shouldBe", "must" ]
  arrowEnumeratorGenerator = true
  openParenCallSite = false
  openParenDefnSite = false
}

spaces {
  beforeContextBoundColon = true
  inImportCurlyBraces = false
}

continuationIndent {
  callSite = 2
  defnSite = 2
}

newlines {
  penalizeSingleSelectMultiArgList = false
  sometimesBeforeColonInMethodReturnType = true
}

rewrite {
  rules = [RedundantBraces, RedundantParens, AsciiSortImports]
  redundantBraces {
    maxLines = 100
    includeUnitMethods = true
    stringInterpolation = true
  }
}

project.excludeFilters = [
  ".*\\.sc$"
]

```

**Comment by poslegm** [comment]
```
--  beforeContextBoundColon = true
++  beforeContextBoundColon = Never
```

Please do not close the issue so as not to forget warning message clarifying

**Comment by kitbellew** [comment]
@mikail-khan the correct values for `beforeContextBoundColon` are `Always`, `Never` and `IfMultipleBounds`.

if you want to use booleans as presets, specify `beforeContextBoundColon.preset = true`. that's why you see the _top-level presets_ message.

**Comment by mikail-khan** [comment]
All resolved now. Thanks. I think the documentation needs to be slightly improved to inform what are all the possible values for a key.
