### ISSUE TITLE
Docstring alignment off on * after an empty line

### ISSUE THREAD

**Issue by padjoo** [scalameta/scalafmt#1978]
- **Version**: 2.5.2
- **Integration**: IntelliJ
- **Configuration**:
```
version = 2.5.2
maxColumn = 120
```

## Steps

Given code like this:
```scala
/**
 * Description
 *
 * Line 3 below an empty line
 * Line 4
 */
```

When I run scalafmt like this:

```bash
scalafmt
```
(or by using IntelliJ to format the file)

## Problem

Scalafmt formats code like this:
```scala
/**
  * Description
  *
 * Line 3 below an empty line
  * Line 4
  */
```

## Expectation

I would like the formatted output to look like this:
```scala
/**
  * Description
  *
  * Line 3 below an empty line
  * Line 4
  */
```

## Workaround

As long as the second line has a least one additional character e.g. a space the third line is properly indented. Once formatted there is no re-issue when re-running the formatting.

**Comment by kitbellew** [comment]
previously fixed in #1968
