### ISSUE TITLE
Feature request for configuration to preserve existing alignment

### ISSUE THREAD

**Issue by marcsaegesser** [scalameta/scalafmt#1984]
I would like something like the following in configuration.

```
    align.preset = preserve
```

The result would be that any existing white space for alignment would be preserved as is. The existing `align.preset = none` causes all existing alignment to be lost and converted to a single space.

My rationale is that there are still alignments that aren't supported (e.g. aligning small if expressions) and there will always be personal alignment preferences that won't be able to be automatically generated. If a developer wants to take the effort to align code manually there should be a way to preserve that work rather than having it discarded if someone happens run scalafmt on it.

**Comment by kitbellew** [comment]
can you give an example which results in *different formatting of code* (as that's the goal of `scalafmt`) while preserving all existing whitespace? or provide definition of _whitespace for alignment_ and an example as before?

**Comment by marcsaegesser** [comment]
I hit submit on that too soon without having really thought it through. I'm going to close this, but I'll try to describe where I was coming from. The short of it is that I put a lot of effort into white space in my code to try to make it more readable and maintainable. So I wonder how I can get the benefits of automation like this without giving up so much control over the _craft_ of formatting code. What I was trying for here was some way to wrest some of that control back; to say something like "a human did this thing on purpose". Some way for scalafmt and me to negotiate who gets to control what without having to litter my code with `// format: off` all over the place. Again, that idea was half-baked.

Anyway, here are a couple simple alignment examples that I was thinking about. I would format this code as follows:

```scala
object Fubar {

  val aFoo: Int      = 1       // Describe this
  val aBazz: String  = "test"  // Describe this

  val bFoo: Int      = 42      // Describe this
  val bBaz: String   = "42"    // Describe this

  val cFubar: Int    = 42      // Describe this
  val cRabuf: String = "42"    // Describe this

}
```

Scalafmt with `align.preset=most` will create this:

```scala
  val aFoo: Int     = 1      // Describe this
  val aBazz: String = "test" // Describe this

  val bFoo: Int    = 42   // Describe this
  val bBaz: String = "42" // Describe this

  val cFubar: Int    = 42   // Describe this
  val cRabuf: String = "42" // Describe this
```
That's so close that it hurts to look at. And the world is complicated; there are definitely scenarios where I would not use my original formatting. So how do you get the benefits of automation without losing expressiveness?

I've been digging through FormatWriter.scala trying to come up with a way to format this one but it's a different duck than all the other alignments:

```scala
  if(fubar) 42
  else      21
```
That's not always appropriate, but when it is it's super clear and expressive. If you wrap that in `// format: off` and `// format: on` you've doubled the code size and buried some something very clean inside extraneous, tool-specific cruft.

**Comment by kitbellew** [comment]
This thing below is not too hard; the formatter currently stops collecting alignment candidate if a blank line is encountered, but we could add a parameter that ignores blanks and continues. The downside is that you might see strange bedfellows aligning, many lines of code apart.

> ```scala
> object Fubar {
> 
>   val aFoo: Int      = 1       // Describe this
>   val aBazz: String  = "test"  // Describe this
> 
>   val bFoo: Int      = 42      // Describe this
>   val bBaz: String   = "42"    // Describe this
> 
>   val cFubar: Int    = 42      // Describe this
>   val cRabuf: String = "42"    // Describe this
> 
> }
> ```

> I've been digging through FormatWriter.scala trying to come up with a way to format this one but it's a different duck than all the other alignments:
> 
> ```scala
>   if(fubar) 42
>   else      21
> ```

I don't really know, we could ask @poslegm, he's the expert on defining tokens and owners for alignment.

but your original request about preserving whitespace for alignment... the only way i can think of whitespace being preserved is by not formatting. that's all a formatter does: changes whitespace. i don't see a solution in those terms.
