### ISSUE TITLE
about scala doc

### ISSUE THREAD

**Issue by jxnu-liguobin** [scalameta/scalafmt#2013]
This template is a guideline, not a strict requirement.
- **Version**: 2.5.2
- **Integration**: IntelliJ
- **Configuration**:
```
align.preset = more
maxColumn = 100
continuationIndent.defnSite = 4
continuationIndent.callSite = 2
continuationIndent.ctorSite = 4
align.preset = none
align.openParenCallSite = false
align.openParenDefnSite = false
rewrite.rules = [ExpandImportSelectors]
spaces.inImportCurlyBraces = true
```

## Steps

Given code like this:
```scala
/**
  *
  * @author dreamylost
  * @since 2020-06-07
  * @version v1.0
  */
```

When I run scalafmt like this:

```bash
gradle  spotlessApply「use spotless」
```

## Problem

Scalafmt formats code like this:
```scala
/**
  *
 * @author dreamylost
  * @since 2020-06-07
  * @version v1.0
  */
```

## Expectation

I would like the formatted output to look like this:
```scala
/**
  *
  * @author dreamylost
  * @since 2020-06-07
  * @version v1.0
  */
```

## Workaround

I've found that by...

## Notes

i want to know why is the document comment changed.

**Comment by kitbellew** [comment]
fixed in #1968. will be out in 2.6.0.
