### ISSUE TITLE
Adding Braces when maxline is below a certain limit

### ISSUE THREAD

**Issue by vito-c** [scalameta/scalafmt#2019]
scalafmt.conf:
```conf
rewrite.rules = [AvoidInfix, PreferCurlyFors, SortImports, SortModifiers, RedundantBraces]
rewrite.redundantBraces.methodBodies = true
rewrite.redundantBraces.includeUnitMethods = true
rewrite.redundantBraces.maxLines = 100
danglingParentheses.defnSite = true
danglingParentheses.callSite = true
```

Input code:
```scala
  /** Redundant braces removes shouldn't remove braces */
  def bracesStay(): Option[Unit] = {
    Some("thing").map { u1 =>
      Unit
    }
  }
```

output code:
```scala
  /** Redundant braces please add some braces */
  def bracesAdd(): Option[Unit] =
    Some("thing").map { u1 =>
      Unit
    }
```

That checks out and works as expected but it  is impossible to undo the change by changing the maxLine

scalafmt.conf:
```conf
rewrite.rules = [AvoidInfix, PreferCurlyFors, SortImports, SortModifiers, RedundantBraces]
rewrite.redundantBraces.methodBodies = true
rewrite.redundantBraces.includeUnitMethods = true
rewrite.redundantBraces.maxLines = 1
danglingParentheses.defnSite = true
danglingParentheses.callSite = true
```

input code:
```scala
  /** Redundant braces please add some braces */
  def bracesAdd(): Option[Unit] =
    Some("thing").map { u1 =>
      Unit
    }
```
output code:
```scala
  /** Redundant braces please add some braces */
  def bracesAdd(): Option[Unit] =
    Some("thing").map { u1 =>
      Unit
    }
```

expected code:
```scala
  /** Redundant braces please add some braces */
  def bracesAdd(): Option[Unit] = {
    Some("thing").map { u1 =>
      Unit
    }
  }
```

**Comment by kitbellew** [comment]
@vito-c as i mentioned, the tool doesn't add braces. the rule is called *redundant* braces. maxLines simply specifies that larger code blocks should not be touched. in both cases, you are looking for the opposite of what the tool does.

**Comment by kitbellew** [comment]
other examples of why adding braces is going to be hard: #1463 #1222

**Comment by vito-c** [comment]
@kitbellew thanks! I will check this out when I have time :)

**Comment by vito-c** [comment]
I have something working on my local that adds braces when the body of a `def` function is over a certain maxlines.

It would result in changing some of the output of the tests for example:
`rewrite.redundantBraces.maxLines=1`
scalafmt-tests/src/test/resources/rewrite/RedundantBraces.stat
```
<<< #1633 1.3: func with placeholder and infix
object a {
  def findAccountByAPIKey(apiKey: APIKey) = byKeyCache.get(apiKey) match {
    case None =>
      delegate.findAccountByAPIKey(apiKey) map {
         _ map(_) tap (add(apiKey, _)) unsafePerformIO(foo)
      }
  }
}
```

no longer produces this:
```
>>>
object a {
  def findAccountByAPIKey(apiKey: APIKey) =
    byKeyCache.get(apiKey) match {
      case None =>
        delegate.findAccountByAPIKey(apiKey) map {
          _ map (_) tap (add(apiKey, _)) unsafePerformIO (foo)
        }
    }
}
```
it now produces:
```
>>>
object a {
  def findAccountByAPIKey(apiKey: APIKey) = {
    byKeyCache.get(apiKey) match {
      case None =>
        delegate.findAccountByAPIKey(apiKey) map {
          _ map _ tap (add(apiKey, _)) unsafePerformIO
        }
    }
  }
}
```

**Comment by kitbellew** [comment]
that's good to hear. one caveat: it must also work for
```
object a { def findAccountByAPIKey(apiKey: APIKey) = byKeyCache.get(apiKey) match { case None => delegate.findAccountByAPIKey(apiKey) map { _ map(_) tap (add(apiKey, _)) unsafePerformIO(foo) } } }
```
for that, the change must be in `FormatWriter`, and it shouldn't look at the number of input lines but only the proposed output.

**Comment by vito-c** [comment]
Is this the test case you are looking for?
```
<<< add braces def single line
object a { def findAccountByAPIKey(apiKey: APIKey) = byKeyCache.get(apiKey) match { case None => delegate.findAccountByAPIKey(apiKey) map { _ map(_) tap (add(apiKey, _)) unsafePerformIO(foo) } } }
>>>
object a {
  def findAccountByAPIKey(apiKey: APIKey) = {
    byKeyCache.get(apiKey) match {
      case None =>
        delegate.findAccountByAPIKey(apiKey) map {
          _ map (_) tap (add(apiKey, _)) unsafePerformIO (foo)
        }
    }
  }
}
```

**Comment by vito-c** [comment]
> and it shouldn't look at the number of input lines but only the proposed output.

Any tips here?

**Comment by kitbellew** [comment]
> > and it shouldn't look at the number of input lines but only the proposed output.
> 
> Any tips here?

if you do it in FormatWriter, you know where the formatter is putting the newlines.

**Comment by kitbellew** [comment]
> Is this the test case you are looking for?
> 
> ```
> <<< add braces def single line
> object a { def findAccountByAPIKey(apiKey: APIKey) = byKeyCache.get(apiKey) match { case None => delegate.findAccountByAPIKey(apiKey) map { _ map(_) tap (add(apiKey, _)) unsafePerformIO(foo) } } }
> >>>
> object a {
>   def findAccountByAPIKey(apiKey: APIKey) = {
>     byKeyCache.get(apiKey) match {
>       case None =>
>         delegate.findAccountByAPIKey(apiKey) map {
>           _ map (_) tap (add(apiKey, _)) unsafePerformIO (foo)
>         }
>     }
>   }
> }
> ```

Yes, something like that.

**Comment by vito-c** [comment]
I've made some good progress on this but my lack of understanding on the FormatLocation is holding me back. I guess I'm not clear on how the `State` object and splits work. 

For example:
```
                  // remove space after "{"
                  val split = state.split.withMod(NoSplit)
                  loc.copy(
                    replace = "(",
                    shift = loc.shift - 1,
                    state = state.copy(prev = prevBegState, split = split)
                  )

**Comment by vito-c** [comment]
Ok I am going to attempt to clean up what I have and create a pull request. Do you have anymore test cases I should add? @kitbellew

**Comment by vito-c** [comment]
Couple questions I have to be able to complete this:
1. How can I change the settings in the middle of a test? For example in `.stat` file I would like to set the redundant braces maxLines to value for specific tests.
2. How can I count the number of lines that an `Array[FormatLocation]` is going to produce? I tried counting `isNL` on the `FormatLocation` is that correct?
3. How can I access the settings inside the `FormatWritter` it seems like it requires context to get the settings.

**Comment by poslegm** [comment]
1. 
```
<<< my test
maxLines = 80
===
object a {}
>>>
object a {}
```

more info [here](https://github.com/scalameta/scalafmt/blob/master/scalafmt-tests/src/test/resources/readme.md)

2. not sure

3. Yes, context is recommended because settings can be customized for [code block](https://scalameta.org/scalafmt/docs/configuration.html#for-code-block)

**Comment by kitbellew** [comment]
@vito-c how's it going? i am planning to release 2.7.0 soon, please share your progress if you'd like it to be included.

**Comment by vito-c** [comment]
@kitbellew what's your eta? I am not quite there yet... The other thing I was thinking about is that people who didn't have braces before will get them added back  in when they upgrade which might be problematic.

**Comment by kitbellew** [comment]
@vito-c all configuration settings are available via `ScalafmtConfig`, with local overrides, found inside `FormatOps`, usually called `style`. Each FormatLocation should likely have one.
