### ISSUE TITLE
Add option to prevent rewrite.redundantBraces.generalExpressions from affecting statements

### ISSUE THREAD

**Issue by Katrix** [scalameta/scalafmt#2038]
This template is a guideline, not a strict requirement.
- **Version**: 2.6.1
- **Integration**: IntelliJ
- **Configuration**:
```
version = "2.6.1"
preset = default
rewrite.rules = [RedundantBraces]
```

## Steps

Given code like this, I would like an option that preserves the curly braces for control structures that will always produce unit.
```scala
if (foo) {
  doSideEffect()
}

for(i <- 0 to 5) {
  println(i)
}

while (cond) {
  doThing()
}
```

**Comment by kitbellew** [comment]
@Katrix what would `generalExpressions = true` continue to do for you?

**Comment by Katrix** [comment]
I still want
```scala
val foo =
  if (bar) {
    baz
  } else {
    bin
  }
```

to still be rewritten to
```scala
val foo =
  if (bar)
    baz
  else
    bin
```

It's more just to keep braces around side effecting control structures, similar to how you can opt out for side effecting methods with `rewrite.redundantBraces.includeUnitMethods`

**Comment by mtomko** [comment]
I was looking for a similar option. Another example might be an `if` statement with no `else` clause, irrespective of the return type. We sometimes have code like:
```scala
if (condition) {
  require(xs.nonEmpty)
}
```

I generally like anything like that to have braces to call attention to it.
