### ISSUE TITLE
Error when encountering a wrapped literal type

### ISSUE THREAD

**Issue by ckipp01** [scalameta/scalafmt#2069]
This template is a guideline, not a strict requirement.
- **Version**: 2.6.2
- **Integration**: Metals or CLI
- **Configuration**:
```
version = 2.6.2
```

## Steps

Given code like this:
```scala
val wrappedLiteral: Option["hello"] = Some("hello")
```
I am greeted with the following error either when triggering formatting via Metals or using the cli:

```
2020.07.05 22:31:56 ERROR scalafmt: /myPath/test.worksheet.sc:27: error: identifier expected but string constant found
val wrappedLiteral: Option["hello"] = Some("hello")
                           ^
```

The same things happens with a different primitive type as well:

```scala
val wrappedLiteral: Option[3] = Some(3)
```

```
2020.07.05 22:37:05 ERROR scalafmt: /myPath/test.worksheet.sc:27: error: identifier expected but integer constant found
val wrappedLiteral: Option[3] = Some(3)
                           ^
```

## Problem

Since it errors, the formatting doesn't work.

## Expectation

I would expect this to parse correctly since it compiles.

**Comment by kitbellew** [comment]
scalafmt can only format what scalameta can parse. if you don't set the _dialect_ parameter, it will support something resembling 2.13. if there's a scalameta dialect that supports these literal types, set it.

**Comment by ckipp01** [comment]
So when looking at Scalameta there seems to be a [Scala213 dialect](https://github.com/scalameta/scalameta/blob/a778d0acdc610ede31537d4d8a85beb8968d29c6/scalameta/dialects/shared/src/main/scala/scala/meta/dialects/package.scala#L55-L59), but when I attempt to set this via `runner.dialect = Scala213` I get the following:

```
Unknown input 'Scala213'. Expected one of: scala212, sbt1, dotty, paradise211, sbt0137, scala211, paradise212
```

Am I missing something or is there not a way to set the dialect as Scala213?

**Comment by kitbellew** [comment]
does it work the same if the file ended in `.scala` instead of `.sc`? do you know if scalameta can parse these literal types correctly using the dotty dialect?

default dialect that the formatter uses (custom, somewhere between 2.13 and dotty) supports literal types: https://github.com/scalameta/scalafmt/blob/master/scalafmt-core/shared/src/main/scala/org/scalafmt/config/ScalafmtRunner.scala#L84
