### ISSUE TITLE
Regression: 2.6.2 fails parsing for RestAssured `.given` syntax: "identifier expected but given found"

### ISSUE THREAD

**Issue by JannikArndt** [scalameta/scalafmt#2071]
```
version = 2.6.2
```

## Steps

We use [rest-assured](https://github.com/rest-assured/rest-assured#examples) for API tests. The syntax is usually something like

```scala
RestAssured
      .given()
      .spec(…)
      .when()
      .get("/path/to/endpoint")
      .Then()
      .log()
      .ifValidationFails()
      .statusCode(200)
      .extract()
      .body()
      .as(classOf[MyModel])
```

This worked in `2.6.1` but `2.6.2` fails with

```
error: identifier expected but given found
```

This is easily reproducable by adding

```
<<< RestAssured 'given' statement
preset = default
optIn.breakChainOnFirstMethodDot = true
===
RestAssured
  .given()
>>>
RestAssured
  .given()
}
```

to any `.stat` test:

<img width="1254" alt="image" src="https://user-images.githubusercontent.com/7119122/86598604-a196b280-bf9d-11ea-937c-af62ca4dbf45.png">

I looked at the [diff](https://github.com/scalameta/scalafmt/compare/v2.6.1...v2.6.2) but didn't find the cause.

**Comment by eikek** [comment]
It seems to fail on any "given" word. It fails on this, too:
```scala
object Main {
  val given = 42
}
```
The word "given" can be a val, a def or a parameter. This is used `.scalafmt.conf`:
```
version = "2.6.2"
```
This is `project/plugins.sbt`:
```
addSbtPlugin("org.scalameta" % "sbt-scalafmt" % "2.4.0")
```
