### ISSUE TITLE
v2.6.2 scalafmt-linux segmentation fault

### ISSUE THREAD

**Issue by ornicar** [scalameta/scalafmt#2073]
https://github.com/scalameta/scalafmt/releases/download/v2.6.2/scalafmt-linux.zip

```
./scalafmt-linux --version
[1]    392955 segmentation fault (core dumped)  ./scalafmt-linux --version
```

On Linux 5.7.5-arch1-1.

The previous version of scalafmt-linux works.

**Comment by kitbellew** [comment]
@poslegm is this a native build problem?

**Comment by poslegm** [comment]
Yes, I will take a look

**Comment by poslegm** [comment]
@ornicar I reuploaded binary, please try it now

**Comment by ornicar** [comment]
It works! Thank you so much :+1:
