### ISSUE TITLE
`newlines.implicitParamListModifierPrefer = before` is ignored (perhaps related to bin packing)

### ISSUE THREAD

**Issue by sjrd** [scalameta/scalafmt#2078]
- **Version**: 2.6.2
- **Integration**: sbt
- **Configuration**:
```
version = 2.6.2
preset = Scala.js
newlines.implicitParamListModifierPrefer = before
newlines.alwaysBeforeMultilineDef = false
rewrite.rules = [AvoidInfix, PreferCurlyFors]
docstrings.style = AsteriskSpace
```
Note in particular `implicitParamListModifierPrefer = before`

## Steps

Given code like this:
```scala
    def print(optimizerHints: OptimizerHints)(
        implicit dummy: DummyImplicit): Unit = {
      if (optimizerHints != OptimizerHints.empty) {
        print("@hints(")
        print(OptimizerHints.toBits(optimizerHints).toString)
        print(") ")
      }
    }

    def print(flags: ApplyFlags)(
        implicit dummy1: DummyImplicit, dummy2: DummyImplicit): Unit = {
      if (flags.isPrivate)
        print("private::")
    }
```

When I run scalafmt like this:

```bash
$ sbt ir2_12/scalafmt
```

## Problem

Scalafmt formats code like this:
```scala
    def print(optimizerHints: OptimizerHints)(implicit
        dummy: DummyImplicit): Unit = {
      if (optimizerHints != OptimizerHints.empty) {
        print("@hints(")
        print(OptimizerHints.toBits(optimizerHints).toString)
        print(") ")
      }
    }

    def print(flags: ApplyFlags)(implicit dummy1: DummyImplicit,
        dummy2: DummyImplicit): Unit = {
      if (flags.isPrivate)
        print("private::")
    }
```

## Expectation

I would like the formatted output to look like this:
```scala
    def print(optimizerHints: OptimizerHints)(
        implicit dummy: DummyImplicit): Unit = {
      if (optimizerHints != OptimizerHints.empty) {
        print("@hints(")
        print(OptimizerHints.toBits(optimizerHints).toString)
        print(") ")
      }
    }

    def print(flags: ApplyFlags)(implicit dummy1: DummyImplicit,
        dummy2: DummyImplicit): Unit = {
      if (flags.isPrivate)
        print("private::")
    }
```

This is for the first overload: the newline should be *before* the `implicit` keyword (like the configuration requests). For the second overload, what scalafmt produces is correct with respect to `implicitParamListModifierPrefer = before`, AFAICT (it's good for me, at least).

## Workaround

None that I can think of at the moment

## Notes

No other issue (open or closed) mentions `implicitParamListModifierPrefer` at the moment.

**Comment by kitbellew** [comment]
have you tried the Force parameter instead?

**Comment by sjrd** [comment]
Using
```
newlines.implicitParamListModifierForce = [before]
```
instead of
```
newlines.implicitParamListModifierPrefer = before
```
gives *exactly* the same result, so that doesn't solve the issue.

It's even more glaring, because it also keeps the `implicit` on the same line for the second overload, which is clearly not correct for "force". Anyway, I don't want to force it everywhere in my codebase; the config I like is the Prefer one.

**Comment by kitbellew** [comment]
I'm sorry, I just realized. in your title, you mention binpacking but there are no parameters in the config. which is it?

**Comment by sjrd** [comment]
It's part of `preset = Scala.js`, so it's `binPack.preset = true`. Here is a minimal config that shows the behavior above:
```
version = 2.6.2
binPack.preset = true
continuationIndent.callSite = 4
newlines.implicitParamListModifierPrefer = before
```

**Comment by kitbellew** [comment]
thank you. these implicit parameters have only been implemented for the regular method formatting. binpack are a bunch of completely separate rules and have not been fully tested with all other parameters, alas.
