### ISSUE TITLE
Double continuation indentation in nested fun call with bin packing

### ISSUE THREAD

**Issue by sjrd** [scalameta/scalafmt#2079]
This template is a guideline, not a strict requirement.
- **Version**: 2.6.2
- **Integration**: CLI
- **Configuration**:
```
version = 2.6.2
binPack.preset = true
continuationIndent.callSite = 4
```

## Steps

Given code like this:
```scala
object Enclosing {
  def apply(name: UTF8String): SimpleMethodName = {
    val len = name.length
    if (len == 0)
      throwInvalidEncodedName(name)

    if (false) {
      ???
    } else {
      // Normal method name
      new SimpleMethodName(
          validateSimpleEncodedName(name, 0, len, openAngleBracketOK = false))
    }
  }
}
```

When I run scalafmt like this:

```bash
scalafmt -c .scalafmt.conf --stdout Test.scala
```

## Problem

Scalafmt formats code like this:
```scala
object Enclosing {
  def apply(name: UTF8String): SimpleMethodName = {
    val len = name.length
    if (len == 0)
      throwInvalidEncodedName(name)

    if (false) {
      ???
    } else {
      // Normal method name
      new SimpleMethodName(validateSimpleEncodedName(name, 0, len,
              openAngleBracketOK = false))
    }
  }
}
```

Note that the line `openAngleBracketOK = false)` is indented *8* spaces (i.e., 2x 4, the continuation indent).

## Expectation

I would like the formatted output to look like this:
```scala
object Enclosing {
  def apply(name: UTF8String): SimpleMethodName = {
    val len = name.length
    if (len == 0)
      throwInvalidEncodedName(name)

    if (false) {
      ???
    } else {
      // Normal method name
      new SimpleMethodName(validateSimpleEncodedName(name, 0, len,
          openAngleBracketOK = false))
    }
  }
}
```

with only *4* spaces of indentation.

## Workaround

No idea

**Comment by kitbellew** [comment]
at first glance, the current output looks correct.

```
// correct
foo(bar(a,
    b), baz,
  qux)
// incorrect
foo(bar(a,
  b), baz,
  qux)
```

**Comment by sjrd** [comment]
Then I guess it must be a matter of opinion, because for me what you label "correct" is incorrect, and the "incorrect" one is the one I want. IMO the rule is that there should never ever be a double-indentation from one line to the next. It's either a block indent (2 spaces) or a continuation indent (4 spaces), depending on the nature of the wrap, but never doubling the indent.

**Comment by kitbellew** [comment]
of course. i think two factors are at play here; one, binpack is generally described as "use at your own peril" in the code (probably because it doesn't play well with other rules, or hasn't been thoroughly tested) -- and not described in the docs; two, the maintainers define `scalafmt` as an opinionated formatter. i will let others comment.
