### ISSUE TITLE
A comment that is alone in a `case` of a match gets the wrong indentation

### ISSUE THREAD

**Issue by sjrd** [scalameta/scalafmt#2081]
- **Version**: 2.6.2
- **Integration**: CLI
- **Configuration**:
```
version = 2.6.2
```

## Steps

Given code like this:
```scala
object Enclosing {
  def foo(x: Int): Unit = {
    x match {
      case 1 =>
        // nothing to do
      case 2 =>
        println("two")
      case _ =>
        /* Here, we have nothing to
         * do either.
         */
    }
  }
}
```

When I run scalafmt like this:

```bash
scalafmt -c .scalafmt.conf --stdout Test.scala
```

## Problem

Scalafmt formats code like this:
```scala
object Enclosing {
  def foo(x: Int): Unit = {
    x match {
      case 1 =>
      // nothing to do
      case 2 =>
        println("two")
      case _ =>
      /* Here, we have nothing to
       * do either.
       */
    }
  }
}
```

Note that the indentation of the two comments (both `//` and `/* */`) is obviously wrong.

## Expectation

I would like the formatted output to look exactly like the original:
```scala
object Enclosing {
  def foo(x: Int): Unit = {
    x match {
      case 1 =>
        // nothing to do
      case 2 =>
        println("two")
      case _ =>
        /* Here, we have nothing to
         * do either.
         */
    }
  }
}
```

## Workaround

Adding an explicit `()` statement convinces scalafmt to correctly indent the comments. If the input is the following, then scalafmt will correctly not modify the file:
```scala
object Enclosing {
  def foo(x: Int): Unit = {
    x match {
      case 1 =>
        // nothing to do
        ()
      case 2 =>
        println("two")
      case _ =>
        /* Here, we have nothing to
         * do either.
         */
        ()
    }
  }
}
```

**Comment by kitbellew** [comment]
it's done intentionally. most people write a comment just before the case clause, therefore, comments at the end of a case clause body are attributed to the next case.

**Comment by sjrd** [comment]
The indentation of the *input* should make it 100% clear that the intent of these comments is to be part of their block; not a comment about the following case. Could scalafmt take that into account?

**Comment by kitbellew** [comment]
perhaps, if someone wanted to try it, but that would also require a new parameter which is not likely to be approved.

from what I've seen in the code, only newlines are occasionally taken into account, otherwise the source code is considered mostly unformatted.
