### ISSUE TITLE
version in .scalafmt.conf is not recognized if `newline.source` exists

### ISSUE THREAD

**Issue by exoego** [scalameta/scalafmt#2094]
- **Version**: 2.5.2, 2.6.3
- **Integration**: sbt 1.3.13, sbt-scalafmt 2.4.0
- **Configuration**:
```
version=2.5.2
newlines.source=fold,unfold
```

## Steps

Run `scalafmt` on sbt

## Problem

Scalafmt failed to format, causing the below error:

```
[info] Formatting 29 Scala sources...
[error] missing setting 'version'. To fix this problem, add the following line to .scalafmt.conf: 'version=2.5.2'.: /home/vagrant/IdeaProjects/aws-lambda-scalajs-facade/.scalafmt.conf
[error] (Compile / scalafmt) missing setting 'version'. To fix this problem, add the following line to .scalafmt.conf: 'version=2.5.2'.: /home/vagrant/IdeaProjects/aws-lambda-scalajs-facade/.scalafmt.conf
[error] Total time: 0 s, completed 2020/07/15 13:45:52
```

However, as the above configuration shows, `version` seems specified.

## Expectation

Scalafmt should recognize `version` in `.scalafmt.conf`, and format with `newline.source` configuration.

## Workaround

N/A

**Comment by kitbellew** [comment]
you should use either `fold` or `unfold`, not both.
