### ISSUE TITLE
Error formatting file with scalafmt 2.6.3

### ISSUE THREAD

**Issue by sergiomahs** [scalameta/scalafmt#2098]
This template is a guideline, not a strict requirement.
- **Version**: 2.6.3
- **Integration**: CLI
- **Configuration**:
```
version=2.6.3

style = defaultWithAlign

maxColumn = 120
project.git = true

rewrite.rules = [RedundantBraces]
lineEndings=preserve
newlines.implicitParamListModifierPrefer = before
```

## Problem

After upgrading to version 2.6.3 when I run scalafmtAll or scalafmt I get the following error
```scala
[error] can't use: [
[error] 	binPack.unsafeCallSite || binPack.unsafeDefnSite (not implemented)
[error] ]: XYZ.scala
```

## Notes

Seems that this was introduce within the commit 
https://github.com/scalameta/scalafmt/commit/91ae24f2d1b81f19dc3b3b16012b01469553e05d
However `binPack.unsafeCallSite` and `binPack.unsafeDefnSite` are false by default, so as far as I understand this error should not happen. For the record, it even fails when I set them as false in the scalafmt config.

**Comment by poslegm** [comment]
Hello! Is it exactly all content of your config file? I can't reproduce it.

**Comment by sergiomahs** [comment]
Yes, that's it.

Digging a bit deeper it throws an error when having something like:
```scala
final case class MyCaseClass(
    whatever: Option[List[Something]]
)
```

or 

```scala
override def fetchPayMethods(
    user: User
)(implicit context: CallContext): Task[List[PayMethod]] =
  Task.pure(state.toList)
```

**Comment by poslegm** [comment]
Still can't  represent. 

`scalafmt -c .scalafmt.conf example.scala` works good.

```
~ cat .scalafmt.conf
version=2.6.3

style = defaultWithAlign

maxColumn = 120
project.git = true

rewrite.rules = [RedundantBraces]
lineEndings=preserve
newlines.implicitParamListModifierPrefer = before
```

```
~ cat example.scala
final case class MyCaseClass(
    whatever: Option[List[Something]]
)

class A {
  override def fetchPayMethods(
      user: User
  )(implicit context: CallContext): Task[List[PayMethod]] =
    Task.pure(state.toList)
}
```

Also I tried your config from sbt plugin and it works too.

**Comment by cernychristopher** [comment]
I ran into the same problem after adding the line `newlines.implicitParamListModifierPrefer = before` to _.scalafmt.conf_ in a project of mine. 

I extracted a minimal example here: https://github.com/cernychristopher/fmttest
Running `sbt scalafmt` will show the error.

**Comment by cernychristopher** [comment]
Thx for the fix. All good again with 2.6.4.

**Comment by sergiomahs** [comment]
Thanks for the fix!
