### ISSUE TITLE
Support same-line argument binding for lambdas

### ISSUE THREAD

**Issue by plaflamme** [scalameta/scalafmt#2099]
It's pretty common to bind names in lambdas using `.map { case (foo, bar) => ...`, unfortunately, if the expression is multi-line, we're forced to indent the whole expression because the pattern match is moved to a new line which also introduces an indent.

## Steps

Given code like this:
```scala
val xs = List("a", "b")
xs.zipWithIndex.map { case (c, index) =>
  s"$c -> $index"
}
```

## Problem

Scalafmt formats code like this:
```scala
xs.zipWithIndex.map {
  case (c, index) =>
    s"$c -> $index"
}
```

## Expectation

I would like the formatted output to not be modified in this case.

## Notes

This seems like a pretty common pattern in scala codebases and it'd be great if scalafmt could support this?

**Comment by kitbellew** [comment]
duplicates #150.

**Comment by plaflamme** [comment]
Sorry about that. I really tried to find a related issue, but I guess I used the wrong keywords.

It was closed as "Won't fix" in 2018 due to the fact that it was probably not worth pursuing with the implementation at the time. Is that still the case today? I know scalafmt went through some refactorings, perhaps this is now more tractable?
