### ISSUE TITLE
False parse error: illegal start of simple expression

### ISSUE THREAD

**Issue by soronpo** [scalameta/scalafmt#2104]
This template is a guideline, not a strict requirement.
- **Version**: 0.5.0
- **Integration**: IntelliJ
- **Configuration**: 
```
version = 2.5.0
maxColumn = 80
```

## Steps

Given code like this:
```scala
sealed trait Foo {
  def negate : - = -
}
trait -
case object - extends -
```
## Problem

Got parse error `illegal start of simple expression`

## Expectation
No error

**Comment by kitbellew** [comment]
if you don't use rewrite rules, parse problems should be directed to https://github.com/scalameta/scalameta
