### ISSUE TITLE
Indent closing parenthesis to match the beginning of the statement with an open parenthesis

### ISSUE THREAD

**Issue by LiuVII** [scalameta/scalafmt#2137]
- **Version**: 2.6.4
- **Integration**: Pants
- **Configuration**:
```
version = "2.6.4"
align.preset=none
maxColumn = 120
continuationIndent.callSite = 2
continuationIndent.defnSite = 2
continuationIndent.extendSite = 2
continuationIndent.withSiteRelativeToExtends = 0
danglingParentheses.callSite = true
danglingParentheses.ctrlSite = true
danglingParentheses.defnSite = true
docstrings.oneline = unfold
docstrings.style = Asterisk
includeNoParensInSelectChains = true
literals.double=Lower
literals.float=Lower
literals.hexPrefix=Lower
literals.long=Upper
newlines.source=keep
newlines.alwaysBeforeElseAfterCurlyIf = false
newlines.alwaysBeforeMultilineDef = false
newlines.avoidForSimpleOverflow = [tooLong]
newlines.alwaysBeforeCurlyBraceLambdaParams = false
newlines.afterCurlyLambda = squash
newlines.implicitParamListModifierForce = [before,after]
newlines.topLevelStatements = []
newlines.topLevelStatementsMinBreaks = 1
optIn.breakChainOnFirstMethodDot = true
optIn.breaksInsideChains = false
optIn.configStyleArguments = true
optIn.encloseClassicChains = true
rewrite.redundantBraces.maxLines = 1
rewrite.redundantBraces.generalExpressions = false
rewrite.redundantBraces.methodBodies = false
rewrite.redundantBraces.parensForOneLineApply = true
rewrite.redundantBraces.stringInterpolation = true
rewrite.rules = [AvoidInfix, PreferCurlyFors, RedundantBraces, SortImports]
rewriteTokens = {
  "⇒": "=>"
  "→": "->"
  "←": "<-"
}
runner.optimizer.forceConfigStyleMinArgCount = 3
spaces.afterKeywordBeforeParen = true
spaces.afterSymbolicDefs = false
spaces.beforeContextBoundColon = never
spaces.inByNameTypes = true
spaces.inImportCurlyBraces = false
spaces.inParentheses = false
trailingCommas = never
verticalMultiline.arityThreshold = 3
verticalMultiline.atDefnSite = true
verticalMultiline.excludeDanglingParens = []
verticalMultiline.newlineAfterOpenParen = true
```

## Steps

Given code like this:
```scala
pubSubMessage match {
  case message: IngestionMessage => (
    IngestionSubscriber(defaultServices).processEff(message)
  )
  case message: UploadMessage => {
    val services = makeUploadServices()

    UploadSubscriber(services).processEff(message)
  }
}
```

When I run scalafmt like this:

```bash
./pants fmt.scalafmt --fmt-scalafmt-scalafmt=//:scalafmt src/jvm/com/thesigma/pubsub/::
```

## Problem

Scalafmt formats code like this:
```scala
pubSubMessage match {
  case message: IngestionMessage => (
      IngestionSubscriber(services).processEff(message)
    )
  case message: UploadMessage => {
    val services = makeUploadServices()

    UploadSubscriber(services).processEff(message)
  }
}
```

## Expectation

I would like the formatted output to be unchanged, so closing parenthesis indentation is the same as for braces there.
Or, in other words, closing parenthesis matches the beginning of the statement of the line with an open parenthesis.

Upd: also, scalafmt indents the body as well which is undesirable.

## Workaround

One can change parentheses for braces to avoid this inconsistent indent in the code where it's possible.

## Notes

Similar formatting issue occurs for extensions args:

```scala
class DeleteSubscriber(
  services: DeleteSubscriber.RequiredServices
) extends PubSubSubscriber[DeleteMessage](
  name = "delete",
  timeout = 1.minute,
  idempotent = false
) {
  ???
}
```

turns into
```scala
class DeleteSubscriber(
  services: DeleteSubscriber.RequiredServices
) extends PubSubSubscriber[DeleteMessage](
    name = "delete",
    timeout = 1.minute,
    idempotent = false
  ) {
  ???
}
```

Are there any options in the config to disable this kind of indent? Or is it possible to add options like that?

**Comment by kitbellew** [comment]
@LiuVII 

if we change the example:
```
case foo => (
      bar
    ).baz(qux)
case foo => (
      bar
    ) baz qux
case foo => (bar match {
      case ....
    })...
```
it works as designed and will continue to be indented. the only time a block is not indented is when it encloses and concludes the expression.

we can look into not indenting a fully enclosed `()` expression, similar to `{}`, but partially enclosed will be indented.

however, is there any reason to put these redundant parentheses around the expression?

**Comment by LiuVII** [comment]
@kitbellew I don't have an argument with the way scalafmt default overall works just wonder if it's possible to configure or add an option to choose the indent as for other indent options there, like for methods def, calls and ctor.

On the example provided not sure for which aesthetic (or other) reasons example you posted is preferred to
```scala
case foo => (
  bar
).baz(qux)
case foo => (
  bar
) baz qux
case foo => (bar match {
  case ....
})...
```
can you elaborate why having indent of 2 or 4 or whatever (I assume it matches some of the other indents set) there is preferred and should not have options to switch to the logically visible end of the statement similar to the end of the block for braces?

**Comment by LiuVII** [comment]
it's actually even fuzzier 🤔 
this
```scala
case foo1 => (
  bar
)
case foo2 => (
  Baz
    .newBuilder
    .baz()
)
case foo3 => {
  baz
}
```
will get formatted as
```scala
case foo1 => (
    bar
  )
case foo2 => (
    Baz
      .newBuilder
      .baz()
    )
case foo3 => {
  baz
}
```
It's even harder to get why this closing parenthesis and/or block is getting certain indent and why this is a stylistically the only preferred way.
Is the current rule to indent back x from the previous line vs indent x forward from matching statement with an open parenthesis? 😕

**Comment by LiuVII** [comment]
Awesome, ty guys!

**Comment by LiuVII** [comment]
@kitbellew thx for your hard work on this! Appreciate it a lot 🙂  

using 2.7.4 now and getting back on one of the comments above, what is the logical reason/rule for this behavior 

Original
```scala
      case foo => (
        Bar
          .newBuilder
          .baz()
      )
```

Formatted
```scala
      case foo => (
        Bar
          .newBuilder
          .baz()
        )
```

And similar goes for chaining outside case-matching
Original
```scala
val baz = (
  Bar
    .newBuilder
    .baz()
)
```

Formatted
```scala
val baz = (
  Bar
    .newBuilder
    .baz()
  )
```

We have this closing parentheses indent change in a lot of places, and I'm not sure how to bring the understanding of my team on what's going on here.
Can you provide an explanation or maybe there's a reference we can use to understand this?

**Comment by kitbellew** [comment]
миша, это ваш вежливый способ указать на баг?

**Comment by LiuVII** [comment]
> миша, это ваш вежливый способ указать на баг?

Ахаха, Альберт, наверное 😅 
с учётом предыдущего ответа "it works as designed and will continue to be indented" и в связи с тем, что я не изучал глубоко логику кода, показалось самноадеяно предполагать, что является фичей, а что багом 🙂

**Comment by kitbellew** [comment]
просто ваш подход использовать круглые скобки там, где чаще всего используются фигурные, вполне нетипичен и не был полностью протестирован. проблема была конкретно в коде, который добавляет отступ в цепочку вызовов, и он зацеплял закрывающую скобку. в ближайшем релизе должно работать.
