### ISSUE TITLE
CLI: Allow an alternative way of passing lists of files to avoid exceeding the number of cli arguments

### ISSUE THREAD

**Issue by pierrechevalier83** [scalameta/scalafmt#2145]
This template is a guideline, not a strict requirement.
- **Version**: 2.6.4
- **Integration**: CLI

## Steps

Running `scalafmt --help`, I didn't find an option for what I am looking for.

## Problem

It is friendly for a command line tool that accepts a list of files to alternatively allow passing one "filelist" file which would contain all the files, separated by end-of-line characters.

This is particularly useful when interacting with scalafmt from a script where the list of files to format could be somewhat unbounded and the operating system will start complaining about "Argument list too long" after a certain point.

## Expectation

Allow a mechanism to pass all the files in a file instead of directly on the command line.

## Workaround

As a workaround, scripts calling scalafmt can manually shard their calls to scalafmt, but that is error-prone and inelegant.

## Notes

Apparently scalafix does allow that way of interacting with its CLI, so it may make sense to aim for a consistent mechanism.

**Comment by olafurpg** [comment]
Thank you for reporting! I agree this would be a nice feature. For consistency with scalac, javac and scalafix I think it would make sense to support this using the syntax `@ARGUMENTS_FILE` like this
```sh
$ cat /path/to/arguments
/path/to/File.scala
$ scalafmt @/path/to/arguments
```

In case somebody is interested in taking a stab at implementing this feature, a good place to start looking is around this line here https://github.com/scalameta/scalafmt/blob/1785d50fcf38d854e31155f7ac7ecb4578b94d66/scalafmt-cli/src/main/scala/org/scalafmt/cli/Cli.scala#L75

A good place to test this functionality would be around here https://github.com/scalameta/scalafmt/blob/1785d50fcf38d854e31155f7ac7ecb4578b94d66/scalafmt-tests/src/test/scala/org/scalafmt/cli/CliTest.scala#L835
