### ISSUE TITLE
[error] scalafmt version 2.0.0-RC8 classpath is corrupted: scala.collection.immutable.Set:

### ISSUE THREAD

**Issue by rhande-mdsol** [scalameta/scalafmt#2147]
This template is a guideline, not a strict requirement.

- **Integration**: IntelliJ 2020.1.2
- **Configuration**:
```
version = 2.0.0-RC8
maxColumn = 100
```

## Steps

When I run scalafmt like this:

```
sbt scalafmt
```

## Problem

I get this error
..
[error] scalafmt version 2.0.0-RC8 classpath is corrupted: scala.collection.immutable.Set: <<scalafmt.conf>>

## Expectation
scalafmt works properly

**Comment by poslegm** [comment]
Hello! Version 2.0.0-RC8 is very old. Does your project works with the latest version 2.6.4?

**Comment by rhande-mdsol** [comment]
I happened to solve this problem just now, by deleting the project locally and cloning from github. I am happy to close this issue.

thanks @poslegm for checking
