### ISSUE TITLE
Specify version in configuration

### ISSUE THREAD

**Issue by charpov** [scalameta/scalafmt#2148]
I couldn't get anything to work (sbt or IntelliJ) until I added an explicit version in `.scalafmt.conf`.  The documentation makes it sound like such a version is optional (_The latest version will be used by default._).  It should be fixed.

**Comment by poslegm** [comment]
It should be fixed in the latest version of sbt plugin. 

And «The latest version will be used by default» in docs relates **only** for sbt integration. For Intellij version should be specified explicitly (but Intellij uses very old version 1.5.1 by default anyway).

**Comment by charpov** [comment]
This is what I get from `sbt` 1.3.13 without a version number:
```
(Compile / scalafmtCheck) missing setting 'version'. To fix this problem, add the following line to .scalafmt.conf: 'version=2.5.2'.
```

**Comment by poslegm** [comment]
What version of sbt-scalafmt do you use? (in `project/plugins.sbt`)

**Comment by charpov** [comment]
Was using 2.4.0.  Using 2.4.2 seems to fix the problem.  Thanks.
