### ISSUE TITLE
Global settings

### ISSUE THREAD

**Issue by charpov** [scalameta/scalafmt#2149]
Is there a way to set a global configuration? `.scalafmt.conf` in the home directory seems to be ignored.  A global/local configuration (like Git) would be convenient.

**Comment by poslegm** [comment]
https://scalameta.org/scalafmt/docs/installation.html#share-configuration-between-builds

**Comment by charpov** [comment]
> https://scalameta.org/scalafmt/docs/installation.html#share-configuration-between-builds

Seems complicated for the simple global/local config many programs use.  Also, wouldn't help much with IntelliJ.

**Comment by kitbellew** [comment]
@charpov can you please describe a use case? scalafmt is normally used with version-controlled repositories which need to be shared with other people, not with other code on the same developer's computer. if two collaborators use different global configuration files, there's a high probability of constant reformatting.

**Comment by charpov** [comment]
> @charpov can you please describe a use case? scalafmt is normally used with version-controlled repositories which need to be shared with other people, not with other code on the same developer's computer. if two collaborators use different global configuration files, there's a high probability of constant reformatting.

I was thinking of common settings of an organization, with further customization on a per-project basis.  Having multiple configurations layers (system/user/project) is commonly supported in tools.  But it's not essential.  My personal use is atypical (single user on multiple projects).
