### ISSUE TITLE
RedundantParens removes parenthesis over multiline statements

### ISSUE THREAD

**Issue by matduf** [scalameta/scalafmt#2163]
- **Version**: From 2.5.0 to 2.6.4
- **Integration**: IntelliJ
- **Configuration**:
```
version = 2.6.4
rewrite.rules = [RedundantParens]
```

## Steps

Given code like this:
```scala
  val map = (Map("A" -> 1) - "Test" - "Test" - "Test" - "Test" - "Test"
    - "Test" - "Test" - "Test" - "Test" - "Test" - "Test" - "Test" + "B" -> 2)
```

When I run scalafmt like this:

```bash
scalafmt
```

## Problem

Scalafmt formats code like this:
```scala
  val map = Map("A" -> 1) - "Test" - "Test" - "Test" - "Test" - "Test"
  -"Test" - "Test" - "Test" - "Test" - "Test" - "Test" - "Test" + "B" -> 2
```

## Expectation

I would like the formatted output to look like this:
```scala
  val map = (Map("A" -> 1) - "Test" - "Test" - "Test" - "Test" - "Test"
    - "Test" - "Test" - "Test" - "Test" - "Test" - "Test" - "Test" + "B" -> 2)
```

## Workaround

I've found that by using version 2.4.2, the problem does not happen as well as manually reformatting the original statement like this:
```scala
  val map = (Map("A" -> 1) - "Test" - "Test" - "Test" - "Test" - "Test" - "Test" - "Test" - "Test" - "Test" - "Test" - "Test" - "Test" + "B" -> 2)
```
will not produce an invalid code.

**Comment by kitbellew** [comment]
@matduf are these parentheses changing the logic? is the problem with the line break before infix?

**Comment by matduf** [comment]
Yes without them Scala will consider the second line as it's own statement and the compilation will fail on `-"Test"` because `unary_-` is not a member of `String`. The parentheses are forcing Scala to consider the multiline statement as one.

As another example with Int which will not produce a compilation error but will return a different result:
```scala
object Test {
  def t(): Int = {
    val v = (10 + 10 + 10 + 10 + 10 + 10 + 10 + 10 + 10 + 10 + 10 + 10 + 10 + 10 + 10 + 10 + 10 + 10 + 10 + 10 + 10 
      + 10 + 10 + 10 + 10 + 10)
    v // 260
  }
}
``` 

```scala
object Test {
  def t(): Int = {
    val v = 10 + 10 + 10 + 10 + 10 + 10 + 10 + 10 + 10 + 10 + 10 + 10 + 10 + 10 + 10 + 10 + 10 + 10 + 10 + 10 + 10
    +10 + 10 + 10 + 10 + 10
    v // 210
  }
}
```

**Comment by matduf** [comment]
Thanks for the quick fix!
