### ISSUE TITLE
Support newlineBeforeOpenParen

### ISSUE THREAD

**Issue by eanea** [scalameta/scalafmt#2176]
Current version supports [newlineAfterOpenParen](https://scalameta.org/scalafmt/docs/configuration.html#verticalmultilineexcludedanglingparens).
But dangling parens looks unpleasant.
```
def other[F[_]](
  a: String,
  b: String
)( // <- this is nasty //
  implicit  c: String,
  d: String
) = a + b + c
```

I suggest adding option **newlineBeforeOpenParen**.
This option should add a newline before open paren.
So example with the above method will look like:
```
def other[F[_]]
(a: String, b: String)
(implicit c: String, d: String) = a + b + c
```
I guess it should work like 

1. read _**def**_ keyword
2. then the name of method
3. then bounds
4. and finally insert a newline before list param.

At first sight, this also will work with class definitions.
```
case class Foo[F[_]]
(a: String, b: String)
(implicit c: String, d: String) {
...
}
```
The difference in the keyword, instead _**def**_ keyword would be _**class**_

**Comment by kitbellew** [comment]
@eanea а что вы предлагаете делать, есть параметры не помещаются на одной строке?

**Comment by eanea** [comment]
```
def other[F[_]]
(a: String, b: Int, c: Int,
 d: Long, e: List[Int])
(implicit c: String, d: String,
 es: ExecutionContext) = {
...
}
```
@kitbellew, params that don't fit in maxColumn should be moved at the next line with Indent = 1.

**Comment by arbitrary-dev** [comment]
```
)( // <- this is nasty //
```

On the contrary, I find it rather clean, when the parameters are indented and parentheses serve as visual cues for the list boundaries. Whereas you formatting proposal lacks this clarity.
