### ISSUE TITLE
2.7.0 regression: newlines.alwaysBeforeCurlyBraceLambdaParams=true no longer preserves one-line lambdas with case

### ISSUE THREAD

**Issue by neko-kai** [scalameta/scalafmt#2187]
- **Configuration**:
```
version = "2.7.0"
newlines.alwaysBeforeCurlyBraceLambdaParams = true
```

## Steps

Given code like this:
```scala
object x {

  // one-line case
  x.map { case (k, v) => k -> v }

  // one-line no-case
  x.map { (k, v) => k -> v }

  // multiline case
  x match { case (k, v) => 
    k -> v
  }

  // multiline no-case
  x.map { (k, v) =>
    k -> v
  }

}
```

## Problem

Scalafmt formats code like this:
```scala
object x {

  // one-line case
  x.map {
    case (k, v) => k -> v
  }

  // one-line no-case
  x.map {
    (k, v) => k -> v
  }

  // multiline case
  x match {
    case (k, v) => k -> v
  }

  // multiline no-case
  x.map {
    (k, v) => k -> v
  }

}
```

That is, all the `one-line` cases are no longer preserved.

## Expectation

With version `2.6.4` the output looked like this:
```scala
object x {

  // one-line case
  x.map { case (k, v) => k -> v }

  // one-line no-case
  x.map {
    (k, v) => k -> v
  }

  // multiline case
  x match {
    case (k, v) => k -> v
  }

  // multiline no-case
  x.map {
    (k, v) => k -> v
  }

}
```

That is, the first `one-line case` line was preserved as is, but `one-line no-case` awkwardly was reformatted.

With `newlines.beforeCurlyLambdaParams = multilineWithCaseOnly` the output is now like this:

```scala
object x {

  // one-line case
  x.map { case (k, v) => k -> v }

  // one-line no-case
  x.map { (k, v) => k -> v }

  // multiline case
  x match {
    case (k, v) => k -> v
  }

  // multiline no-case
  x.map { (k, v) =>
    k -> v
  }

}
```

That is, all the one-liners are preserved, but the `multiline no-case` stands out as it has the parameters on the right.

I think adding a `newlines.beforeCurlyLambdaParams = multilineOnly` option that preserves all one-liners and breaks all multiline lambdas would make the most sense to me:

```scala
object x {

  // one-line case
  x.map { case (k, v) => k -> v }

  // one-line no-case
  x.map { (k, v) => k -> v }

  // multiline case
  x match { 
    case (k, v) => k -> v
  }

  // multiline no-case
  x.map { 
    (k, v) => k -> v
  }

}
```

That would allow me to update from 2.6.4 to 2.7.0 without losing the `one-line case` formatting and also gain consistent formatting for the `one-line no-case` case. Thank you!

## Workaround

None found

**Comment by kitbellew** [comment]
@neko-kai do you want to test the linked pr, to see if it works correctly for all your cases?

**Comment by neko-kai** [comment]
@kitbellew Hi, thank you for tackling this! I tested and found a disrepancy with the following code:

On 2.6.4 / 2.7.0 with `alwaysBeforeCurlyBraceLambdaParams=true` code is formatted like this:

```scala
abc
  .xa(???)
  .flatMap(
    result =>
      for {
        _ <- a
        _ <- b
      } yield ()
  )
```

But with #2191 
```
version = "2.7.0-SNAPSHOT"
newlines.beforeCurlyLambdaParams = multiline
```

It is reformatted like this:

```scala
abc
  .xa(???)
  .flatMap(result =>
    for {
      _ <- a
      _ <- b
    } yield ()
  )
```

That is, there's an unwanted formatting of the parameter to the right of the function body. I guess I've depended on curly brace lambda option to put parameters to the left of the body always, even in non-curly lamdas. (`=always` still does it, but unfortunately it prohibits one-line lambdas)

**Comment by kitbellew** [comment]
> @kitbellew Hi, thank you for tackling this! I tested and found a disrepancy with the following code:
> 
> On 2.6.4 / 2.7.0 with
...
> 
> code is formatted like this:
> 
> ```scala
> abc
>   .xa(???)
>   .flatMap(
>     result =>

This is a separate issue, formatted by a different rule. I will merge the linked PR and look at this after.

**Comment by kitbellew** [comment]
@neko-kai can you please try with latest pr?

**Comment by neko-kai** [comment]
@kitbellew The latest PR works great. I'm not seeing any more arguments to the right of body in the diff after reformatting on that commit with `=multiline`. 👍
