### ISSUE TITLE
removes necessary curly brackets

### ISSUE THREAD

**Issue by mrt181** [scalameta/scalafmt#2197]
This template is a guideline, not a strict requirement.
- **Version**: 2.7.1
- **Integration**: sbt-scalafmt 2.4.0
- **Configuration**:
```
version = 2.7.1
style = defaultWithAlign
maxColumn = 120
encoding = UTF-8
docstrings = JavaDoc
assumeStandardLibraryStripMargin = true
spaces.inImportCurlyBraces = true

project.git = true

rewrite.rules = [
  RedundantBraces
  RedundantParens
  SortImports
  SortModifiers
  PreferCurlyFors
]

```

## Steps

Given code like this:
```scala
object Main extends App {

  val o = Some(true)

  val result = {
    for {
      b <- o
    } yield b
  } match {
    case Some(value) => s"Some($value)"
    case None        => "None"
  }
  Console.println(result)
}
```

When I run scalafmt like this:

```bash
scalafmt
```

## Problem

Scalafmt formats code like this:
```scala
object Main extends App {

  val o = Some(true)

  val result =
    for {
      b <- o
    } yield b match {
      case Some(value) => s"Some($value)"
      case None        => "None"
    }
  Console.println(result)
}
```

## Expectation

I would like the formatted output to compile:
```scala
object Main extends App {

  val o = Some(true)

  val result = {
    for {
      b <- o
    } yield b
  } match {
    case Some(value) => s"Some($value)"
    case None        => "None"
  }
  Console.println(result)
}
```

## Workaround

I've found that by replacing the outer most curly brackets with round brackets in the definition of result the code keeps compiling and is formatted as expected.

## Notes

`scalaVersion := "2.13.3"`
`sbt.version=1.3.13`

**Comment by kitbellew** [comment]
@mrt181 thank you for reporting. seems like you have been finding a lot of new stuff; since this behaviour hasn't changed since 2.7.0, should we wait for more reports before addressing and releasing 2.7.2? :)

**Comment by mrt181** [comment]
There is a workaround for this issue so waiting should be okay.
