### ISSUE TITLE
Annotations break in Ammonite scripts when formatted

### ISSUE THREAD

**Issue by ckipp01** [scalameta/scalafmt#2204]
This template is a guideline, not a strict requirement.
- **Version**: 2.7.2
- **Integration**: Metals/CLI
- **Configuration**:
```
version     = 2.7.2
project.git = true

preset       = default
maxColumn    = 100
align.preset = more
"""

```

## Steps

Given code like this:
```scala
@doc("Here is my method")
def myMethod(): Unit = doSomeStuff()

@doc("Here is another method")
@main
def anotherMethod(): Unit = doOtherStuff()
```

When I run scalafmt like this:

```bash
scalafmt .
```

## Problem

Scalafmt formats code like this:
```scala
@
doc("Here is my method")
def myMethod(): Unit = doSomeStuff()

@
doc("Here is another method")

@
main
def anotherMethod(): Unit = doOtherStuff()
```

## Expectation
Nothing should change here.

**Comment by ckipp01** [comment]
As always, thanks for your fast feedback and getting these addressed @kitbellew! I appreciate all your work!

**Comment by kitbellew** [comment]
https://github.com/scalameta/scalafmt/releases/tag/v2.7.3
