### ISSUE TITLE
[Request] Add an option to prioritize newlines after operators instead of at method calls

### ISSUE THREAD

**Issue by Daenyth** [scalameta/scalafmt#2212]
- **Version**: 2.7.1
- **Integration**: Any
- **Configuration**:
```
version = "2.7.1"
maxColumn = 36
```

## Steps

Given code like this:
```scala
object Example {
  def foo: Bar =
    something >> otherThing.methodCall("blah")
}

```

When I run scalafmt like this:

```bash
scalafmt
```

## Problem

Scalafmt formats code like this:
```scala
object Example {
  def foo: Bar =
    something >> otherThing
      .methodCall("blah")
}

```

## Expectation

I would like the formatted output to look like this:
```scala
object Example {
  def foo: Bar =
    something >>
      otherThing.methodCall("blah")
}

```

## Workaround

Manually inserting the newline after the `>>` results in the desired output being preserved

**Comment by kitbellew** [comment]
rtfm?

**Comment by Daenyth** [comment]
Can you point out which section? It's not clear to me what part you're referring to specifically - I didn't see examples in the documentation that show this kind of layout in the before/after panels

**Comment by kitbellew** [comment]
https://scalameta.org/scalafmt/docs/configuration.html#newlinesafterinfix
