### ISSUE TITLE
enforcing line width - splitting rules question

### ISSUE THREAD

**Issue by kpbochenek** [scalameta/scalafmt#2214]
This template is a guideline, not a strict requirement.
- **Version**: 2.7.2
- **Integration**: from console
- **Configuration**:
```
version = 2.7.2
align.preset = none
align.stripMargin = true
assumeStandardLibraryStripMargin = true
binPack.parentConstructors = Oneline
docstrings = Asterisk
maxColumn = 100
newlines {
  alwaysBeforeMultilineDef = false
  avoidForSimpleOverflow = [tooLong]
  implicitParamListModifierPrefer = before
}
danglingParentheses.ctrlSite = false
project.git = true
project.excludeFilters = [
  Legacy
  bench/corpus
  test/resources
  semanticdb/semanticdb/src/main/generated
]
```

## Steps

Given code like this:
```scala
if (!sepRegions.isEmpty && (sepRegions.head.isInstanceOf[RegionEnum] || sepRegions.head.isInstanceOf[RegionIndentEnum]))
```

When I run scalafmt like this:

```bash
scalafmt
```

## Problem

Scalafmt formats code like this:
```scala
+            if (!sepRegions.isEmpty && (sepRegions.head.isInstanceOf[RegionEnum] || sepRegions.head
+                .isInstanceOf[RegionIndentEnum]))
```

## Expectation

I would like the formatted output to look like this:
```scala
+            if (!sepRegions.isEmpty && (sepRegions.head.isInstanceOf[RegionEnum] ||
+                 sepRegions.head.isInstanceOf[RegionIndentEnum]))
```

## Workaround

Manual split before formatting

Is it possible to achieve with current scalafmt?
If not is it possible to add to scalafmt?

**Comment by kitbellew** [comment]
https://scalameta.org/scalafmt/docs/configuration.html#newlinesafterinfix

**Comment by kitbellew** [comment]
also, I'd rewrite as

```
sepRegions.headOption.exists(x => x.isInstanceOf[...] || ...)
```

**Comment by kpbochenek** [comment]
would it be formatted in a way I want if I rewrite it?

**Comment by kitbellew** [comment]
> would it be formatted in a way I want if I rewrite it?

not sure if I understood the question.

the default infix formatting preserves line breaks, so if you break it yourself, it will keep it. but you already mentioned this as a workaround.
