### ISSUE TITLE
Control which line ScalaDoc text starts on

### ISSUE THREAD

**Issue by Dpetters** [scalameta/scalafmt#2215]
- **Version**: 2.7.2
- **Integration**: IntelliJ
- **Configuration**:
docstrings.style = SpaceAsterisk
```
version = 2.7.3
maxColumn = 120
docstrings.style = SpaceAsterisk
```

## Steps

Given code like this:
```scala
/** 
  *
  * Bar
  * Baz
  */
object Foo { }
```

## Problem

Scalafmt formats code like this:
```scala
/**
  * Bar
  * Baz
  */
object Foo { }
```

## Expectation

I would like the formatted output to look like this:
```scala
/** Bar
  * Baz
  */
object Foo { }
```

## Notes

Per the [ScalaDoc style](https://docs.scala-lang.org/style/scaladoc.html#general-style): "the text in the Scaladoc styles begins on the first line of the comment. This format saves vertical space in the source file."

Is there a way I can acheive this without setting `docstrings.wrap`  to `yes`?

**Comment by poslegm** [comment]
> Is there a way I can acheive this without setting docstrings.wrap to yes?

AFAIK no

cc @kitbellew

**Comment by kitbellew** [comment]
looks like possibly inconsistent. let me look.

**Comment by Dpetters** [comment]
Thank you both very much!
