### ISSUE TITLE
Following 2.7.4: can't find a way to keep first line blank in docstrings with `docstrings = Scaladoc` / `docstrings.style = SpaceAsterisk`

### ISSUE THREAD

**Issue by neko-kai** [scalameta/scalafmt#2218]
```
version = 2.7.4
docstrings = ScalaDoc
```

## Steps

Given code like this:
```scala
/**
  * abc
  * cba
  */
def x: Unit = ()
```

## Problem

Scalafmt formats code like this (with either setting for `docstrings.wrap`):
```scala
/** abc cba
  */
def x: Unit = ()
```

## Expectation

I would like the formatted output to look like this:
```scala
// docstrings.wrap = false // keep starting newline as in 2.7.3
/**
  * abc
  * cba
  */
def x: Unit = ()
```

```scala
// docstrings.wrap = true // fold everything?
/** abc cba */
def x: Unit = ()
```

## Workaround

None

## Notes

None

**Comment by kitbellew** [comment]
https://docs.scala-lang.org/style/scaladoc.html:
```
Note that, in contrast to the Javadoc convention, the text in the Scaladoc styles begins on the first line of the comment.
```

I can add a new `docstrings = AsIs` which will not format the docstring at all. Including indent and leading asterisks.

**Comment by neko-kai** [comment]
@kitbellew 
I understand the recommendation, but it's not really followed universally, even in [scala/scala](https://github.com/scala/scala/blob/6b4d32c3f518d21a798e8d3cf4a8c35866afa8e2/src/compiler/scala/tools/nsc/fsc/CompileServer.scala#L183). Scalafmt sorting out with the leading asterisks is a big help, so omitting all formatting would be regrettable. Maybe a separate option, such as `docstrings.spaces = fold/unfold` ?
