### ISSUE TITLE
Unable to align on pattern alternative, even by setting align.tokens

### ISSUE THREAD

**Issue by Kazark** [scalameta/scalafmt#2219]
- **Version**: 2.4.2
- **Integration**: SBT
- **Configuration**:
```
version = 2.7.4

style = default

maxColumn = 100

align.tokens = [{code = "|", owner = "Pat.Alternative"}]

danglingParentheses = true

trailingCommas = preserve

verticalAlignMultilineOperators = true

rewrite.rules = [
  AvoidInfix
  RedundantBraces
  RedundantParens
  AsciiSortImports
  PreferCurlyFors
]

project.excludeFilters = [
   "scalafix-inputs",
   "scalafix-outputs"
]
```

## Steps

Given code like this:
```scala
case ( Root / "foo"
     | Root / "bar"
     | Root / "baz" / _ / "qux"
     ) => unifiedResult
```

When I run scalafmt like this:

```bash
sbt scalafmtAll
```

## Problem

Scalafmt formats code like this:
```scala
case (Root / "foo" | Root / "bar" | Root / "baz" / _ / "qux") => unifiedResult
```

## Expectation

I would like the formatted output to look like this (same as original):

```scala
case ( Root / "foo"
     | Root / "bar"
     | Root / "baz" / _ / "qux"
     ) => unifiedResult
```

## Workaround

My only option right now is disabling the region with `// format: off` and `// format: on`.

## Notes

I've been trying to solve this by setting `align.tokens` to various values. I think `[{code = "|", owner = "Pat.Alternative"}]` is the right value based on:

```scala
scala> p"(2 | 3)".productPrefix
val res10: String = Pat.Alternative
```

But I've also trying setting `owner` to `Case`, `Term.Match`, and `Term.PartialFunction`, all with no success.

**Comment by kitbellew** [comment]
@Kazark 
* this is not an alignment problem, hence no need to play around with `align`
* it might be possible to preserve a newline before the `|`, similar to how we treat infix operators by default, but there's no such functionality available today
* your workaround is the right approach for this specific case

**Comment by kitbellew** [comment]
@Kazark we can consider implementing this logic for `newlines.source = keep`, which attempts to preserve newlines in the source code. let me know if that will work.

**Comment by Kazark** [comment]
@kitbellew I like the idea. Might have to see it in practice to make sure it wouldn't interact badly with a different scenario, though.
