### ISSUE TITLE
Indentation for binary operators

### ISSUE THREAD

**Issue by tusharmath** [scalameta/scalafmt#2220]
This template is a guideline, not a strict requirement.
- **Version**: 0.5
- **Integration**: IntelliJ
- **Configuration**:
```
version = 2.0.1
maxColumn = 120
```

## Steps

Given code like this:
```scala
A >>> B >>> C >>> D >>> E >>> F
```

When I run scalafmt like this:

```bash
scalafmt
```

## Problem

Scalafmt formats code like this:
```scala
A >>> B >>> C >>> 
  D >>> E >>> F
```

## Expectation

I would like the formatted output to look like this:
```scala
A >>> 
  B >>> 
  C >>> 
  D >>> 
  E >>> 
  F
```

## Workaround

I've found that by...

## Notes

See also..

**Comment by kitbellew** [comment]
@tusharmath what about
```
a >>> b + 1 >>> c * d
```
also, have you tried https://scalameta.org/scalafmt/docs/configuration.html#newlinesafterinfix
