### ISSUE TITLE
"preserve" mode for class creation newlines

### ISSUE THREAD

**Issue by kellen** [scalameta/scalafmt#2224]
I would like to preserve the location of newlines _or_ binpack the arguments for some class creation e.g.

```
val xxx = MyCaseClass(
  a, b, c, d, e, f, g,
  h, i, j, k, l, m, n, o,
  p, q, r, s, t, u, v
)
```

This occurs a lot in e.g. data pipelines where you are transforming class A into class B and need to copy a bunch of fields but aren't doing anything interesting otherwise, so putting each argument on a new line vastly decreases readability across a file where this might happen ~10 times. 

I previously asked this [on gitter](https://gitter.im/scalameta/scalafmt?at=5f4e56a989cf2d584b8e7ac9) where the recommendation was to just use `format: off`, but I have enough sites where this occurs that annotating all of them is a burden and a config option would be preferable.

The main driving factor for retaining a more packed representation is the number of arguments to the class, so off the top of my head, one of the following options might make sense:
```
binPack.classCreation.argumentThreshold = 5
newlines.classCreation.preserveArgumentThreshold = 5
```

- **Version**: 2.7.5
- **Integration**: sbt
- **Configuration**:
```
version = "2.7.5"
align.preset=none

maxColumn = 150
lineEndings=preserve
binPack.literalArgumentLists = true

continuationIndent {
  callSite = 2
  defnSite = 2
}

newlines {
  alwaysBeforeMultilineDef = false
  sometimesBeforeColonInMethodReturnType = true
  beforeCurlyLambdaParams = never
}

verticalMultiline {
  newlineAfterImplicitKW = true
  newlineBeforeImplicitKW = true
}

docstrings = JavaDoc
docstrings.oneline = fold
docstrings.style = Asterisk

project.git = false

rewrite {
  rules = [
    PreferCurlyFors,
    SortImports,
    RedundantParens,
    SortModifiers
  ]
  redundantBraces.generalExpressions = false
  redundantBraces.stringInterpolation = true
  redundantBraces.maxLines = 1
}
```

## Steps

Given code like this:
```scala
val xxx = MyCaseClass(
  a, b, c, d, e, f, g,
  h, i, j, k, l, m, n, o,
  p, q, r, s, t, u, v
)
```

When I run scalafmt like this:

```bash
scalafmt
```

## Problem

Scalafmt formats code like this:
```scala
val xxx = MyCaseClass(
  a,
  b,
  c,
  // snip
  v
)
```

## Expectation

I would like the formatted output to remain the same _or_ be binpacked according to some other config option.

## Workaround

`format: off` but as noted this is burdensome.

**Comment by kitbellew** [comment]
The assumption was that most `binPack` parameters are self-explanatory, but one must first find them:

https://scalameta.org/scalafmt/docs/configuration.html#other

```
binPack.literalsExclude = [
  String
  "Term.Name"
]
```

remove "Term.Name", and your example will work.

**Comment by kitbellew** [comment]
> This occurs a lot in e.g. data pipelines where you are transforming class A into class B and need to copy a bunch of fields but aren't doing anything interesting otherwise...

if you're using spark, copying a bunch of fields and nothing interesting otherwise doesn't require calling ctors. select or rename should be enough.

**Comment by kellen** [comment]
@kitbellew This seems like it would do some but not all of what I want.

First off, the parameters aren't really literals, so the naming doesn't really make sense to me, but more importantly for this usecase is that usually we'll have an instance `a` from which the values are copied, so some other rule seems to kick in. e.g. with `B(a.one, a.two, a.three, ..., a.twentyTwo)`. Or e.g. wrapping otherwise inoffensive things in `Option` like in `B(Option(a.one), Option(a.two), ...`

`Term.Name` is a `trees` thing? Is there some other incantation I could try here?

> if you're using spark

Using scio where this is common.

**Comment by kitbellew** [comment]
> @kitbellew This seems like it would do some but not all of what I want.
> 
> First off, the parameters aren't really literals, so the naming doesn't really make sense to me, but more importantly for this usecase is that usually we'll have an instance `a` from which the values are copied, so some other rule seems to kick in. e.g. with `B(a.one, a.two, a.three, ..., a.twentyTwo)`. Or e.g. wrapping otherwise inoffensive things in `Option` like in `B(Option(a.one), Option(a.two), ...`

Try `binPack.literalsIncludeSimpleExpr`.
