### ISSUE TITLE
Enable `scaladocs.wrap=yes` by default?

### ISSUE THREAD

**Issue by olafurpg** [scalameta/scalafmt#2229]
- **Version**: 2.7.5
- **Integration**: VS Code
- **Configuration**: defaults

I only recently started using `docstrings.wrap=yes` and it's amazing. I wish I had started using it sooner! 😄 

I think it would be natural to enable this feature by default so that beginner users benefit from docstring wrapping without reading the website to find the right configuration. WDYT @kitbellew ?

**Comment by kitbellew** [comment]
@olafurpg i am for it, having it off is akin to scalafmt not formatting the rest of the code. (and thanks for the compliment.)

still, your fans are pretty opinionated, with some denouncing the project for having too many options and changing defaults over time (while others are unhappy that scalafmt cannot be configured _not_ to modify their thoroughly custom code). what should be done about that?

**Comment by olafurpg** [comment]
My view is that Scalafmt should have opinionated defaults and we should not be afraid to change the defaults to get closer to that goal. Users who dislike the default changes can optionally enable the non-default settings.

I'm personally in favor of enabling `newlines.source=unfold` (or fold) by default. I have seen a lot of users struggle to produce readable output for infix operators, it's not obvious how the current defaults work.

**Comment by kitbellew** [comment]
> My view is that Scalafmt should have opinionated defaults and we should not be afraid to change the defaults to get closer to that goal. Users who dislike the default changes can optionally enable the non-default settings.

sounds good :)

> I'm personally in favor of enabling `newlines.source=unfold` (or fold) by default. I have seen a lot of users struggle to produce readable output for infix operators, it's not obvious how the current defaults work.

if the problem is in infix operators, we can simply change the default for https://scalameta.org/scalafmt/docs/configuration.html#newlinesafterinfix
