### ISSUE TITLE
`newlines.beforeMultiline = classic` in docs

### ISSUE THREAD

**Issue by arbitrary-dev** [scalameta/scalafmt#2243]
There is `newlines.beforeMultiline = classic` mentioned in [the docs](https://scalameta.org/scalafmt/docs/configuration.html#newlinesbeforemultiline), but:

```
[error] Invalid config: Unknown input 'classic'. Expected one of: keep, fold, unfold
```

**Comment by kitbellew** [comment]
the docs never mention you are allowed to specify `classic` explicitly, quite the contrary: https://scalameta.org/scalafmt/docs/configuration.html#newlinessource

**Comment by arbitrary-dev** [comment]
It seems like https://scalameta.org/scalafmt/docs/configuration.html#newlinesbeforemultiline
could be misleading with the following block:

```
Config for this example:

# newlines.beforeMultiline = classic
```

…until one notices the commentary sign on the left `#`
