### ISSUE TITLE
Space in single line comment

### ISSUE THREAD

**Issue by arbitrary-dev** [scalameta/scalafmt#2246]
**Configuration**:
```
version = 2.7.5
```

## Problem

Scalafmt formats code like this:
```diff
 private object ClientMetrics {
-  private val AdapterCallType = ""//empty since it is not an adapter call
+  private val AdapterCallType = "" //empty since it is not an adapter call
 }
```

## Expectation

I would like the formatted output to look like this:
```diff
 private object ClientMetrics {
-  private val AdapterCallType = ""//empty since it is not an adapter call
+  private val AdapterCallType = "" // empty since it is not an adapter call
 }
```

A space after the `//`

**Comment by kitbellew** [comment]
only with https://scalameta.org/scalafmt/docs/configuration.html#commentswrap

**Comment by arbitrary-dev** [comment]
Have tried `comments.wrap = standalone`, it doesn't add space.

**Comment by kitbellew** [comment]
yours is a trailing comment

**Comment by arbitrary-dev** [comment]
`comments.wrap = trailing` also doesn't help

**Comment by kitbellew** [comment]
yep, it only applies if the comment needs to be wrapped. ok, a feature request, then.
