### ISSUE TITLE
Indentation of named varargs

### ISSUE THREAD

**Issue by arbitrary-dev** [scalameta/scalafmt#2247]
**Configuration**:
```
version = 2.7.5
```

## Problem

Scalafmt formats code like this:
```diff
 PrometheusMetricUtils.registerHttpResponseTimePHistogram(
   name = ThirdPartyServiceRequestTimePHist.name,
   help = "Third party service response time histogram reported per method and service type",
   labelNames =
     ThirdPartyServiceTypeLabel,
-    AdapterCallLabel,
-    ThirdPartyServiceMethodLabel,
+  AdapterCallLabel,
+  ThirdPartyServiceMethodLabel,
 )
```

## Expectation

I would like the formatter to keep the same indentation as for the 1st element of varargs `ThirdPartyServiceTypeLabel`

**Comment by kitbellew** [comment]
impossible, try `scalafix`

**Comment by arbitrary-dev** [comment]
Is it because `scalafmt` operates on literals level, and doesn't have access to the parameters definitions?

**Comment by kitbellew** [comment]
correct
