### ISSUE TITLE
Should not wrap long comment if result is still long

### ISSUE THREAD

**Issue by arbitrary-dev** [scalameta/scalafmt#2251]
**Configuration**:
```
version = 2.7.5
maxColumn = 100
comments.wrap = standalone
```

## Problem

Scalafmt formats code like this:
```diff

-        // See https://very/very/very/very/very/very/very/very/very/very/very/very/very/very/very/very/very/very/very/very/very/long/link/here
+        /* See
+         * https://very/very/very/very/very/very/very/very/very/very/very/very/very/very/very/very/very/very/very/very/very/long/link/here */

```

## Expectation

I would like the formatter to skip wrapping long comments that still will result in a long comment.

**Comment by kitbellew** [comment]
can't be done. prevents legitimate wrapping of long comment into many lines, with only one still overflowing due to single token.
