### ISSUE TITLE
Make implicitParamListModifierPrefer accept a Seq[BeforeAfter] instead of an Option[BeforeAfter]

### ISSUE THREAD

**Issue by aBnormaLz** [scalameta/scalafmt#2279]
- **Version**: 2020.2
- **Integration**: IntelliJ
```
version = 2.7.5
newlines.implicitParamListModifierPrefer = [before, after] //now it is impossible
```

## Steps

Given code like this:
```scala
    def noNewLines(implicit s1: String, s2: String)

    def withNewLines(
        implicit 
        s1: String,
        s2: String,
    )
```

When I run scalafmt like this:

Format with the hotkey in IntelliJ

## Expectation

I would like the formatted output to look like this:
```scala
    def noNewLines(implicit s1: String, s2: String)

    def withNewLines(
        implicit 
        s1: String,
        s2: String,
    )
```

## Actual output

Scalafmt formats code like this:
```scala
    // newlines.implicitParamListModifierPrefer = after
    def noNewLines(implicit s1: String, s2: String)

    def withNewLines(implicit
        s1: String,
        s2: String,
    )

    // newlines.implicitParamListModifierPrefer = before
    def noNewLines(implicit s1: String, s2: String)

    def withNewLines(
        implicit s1: String,
        s2: String,
    )

```

## Problem

If I understood correctly the difference between implicitParamListModifierForce and implicitParamListModifierPrefer is the first one forces the new line, the second one only prefers but not forces it. My problem is that I want to give the option to place a new line before and/or after but since implicitParamListModifierPrefer is only an option I can only prefer it before and prohibit after or prefer it after and prohibit before. I tried all the configurations I could but none of them worked (actually the forced ones always add new lines and that's not what my expected output is)

Is there a workaround for this formatting?

**Comment by kitbellew** [comment]
`Prefer` takes an optional single parameter (you can't _prefer_ both; what happens if we _don't have to_ break in both places?), but `Force` takes a sequence (you can _force_ both).

**Comment by aBnormaLz** [comment]
In my opinion when we prefer both before and after it keeps the new line if there were any. So the following inputs stay the same after formatting.

```scala
def noNewLines(implicit s1: String, s2: String)

def newLineBefore(
    implicit s1: String,
    s2: String,
)

def newLineAfter(implicit
    s1: String,
    s2: String,
)

def newLineBoth(
    implicit 
    s1: String,
    s2: String,
)
```

It is just my opinion but I think the most readable are the first and last ones. With the force option you can only have one of them in your code but if you have only one implicit parameter you maybe want it to be formatted into one line. Basically you prefer both new lines, but there is an option to leave any or both of them.

**Comment by kitbellew** [comment]
these parameters are there to imply formatting choices regardless of what's in the original.

for what you're describing, there's a completely different parameter: `newlines.source = keep`. it might not specifically support this case, but can be changed to, if both prefer and force are omitted.

**Comment by aBnormaLz** [comment]
I took a deeper look and it kind of does the same. It is good enough for me.

Thanks for the quick reply and fast help!
