### ISSUE TITLE
Intellij plugin doesn't work with 2020.3 version

### ISSUE THREAD

**Issue by NarviDikator** [scalameta/scalafmt#2287]
This template is a guideline, not a strict requirement.
- **Version**: 0.5
- **Integration**: IntelliJ
- **Configuration**:
```
version = 2.0.1
maxColumn = 100
```

## Steps

Given code like this:
```scala
ORIGINAL CODE
```

When I run scalafmt like this:

```bash
scalafmt
```

## Problem

Scalafmt formats code like this:
```scala
Intellij plugin doesn't work with the 2020.3 version
```

## Expectation

I would like the formatted output to look like this:
```scala
Plugin 'Scalafmt' (version 1.5.1) was explicitly marked as incompatible with the current version of the IDE
```

## Workaround

I've found that by...

## Notes

See also..

**Comment by poslegm** [comment]
Intellij has built-in support of scalafmt, you can just remove deprecated plugin. Please see [Intellij section in docs](https://scalameta.org/scalafmt/docs/installation.html#intellij)

**Comment by kitbellew** [comment]
what he said
