### ISSUE TITLE
formatting fails when adding import in a class with javadocs

### ISSUE THREAD

**Issue by MarkSheinkman** [scalameta/scalafmt#2297]
- **Version**: 2.7.5
- **Integration**: IntelliJ
- **Configuration**:
```
version = 2.7.5
maxColumn = 120
verticalMultiline.atDefnSite = true
```

## Steps

Given code like this:
```scala
/** */
object Obj {
  def func[T](): Unit = ???
  def formatMe(): Unit = {
    func[TypeThatsNotInScope]
  }
}
```

Trigger basic code completion on TypeThatsNotInScope (ctrl+space)

## Problem

Error popup:
![image](https://user-images.githubusercontent.com/4921111/102717735-d1880700-42ec-11eb-9b5a-481ac1365cb6.png)

and Scalafmt formats code like this:
```scala
import TypeThatsNotInScope

/** */
object Obj {
  def func[T](): Unit = ???
  def formatMe(): Unit = {
    func[object Obj {
  def formatMe(): Unit = {
    func[
      /** StartMarker */
      TypeThatsNotInScope
      /** EndMarker */
    ]
  }
}]
  }
}
```

## Notes

It seems to happen only when a javadoc comment exists for the class. changing `/** */` to `/* */` or even removing it entirely causes the formatting to succeed.

**Comment by kitbellew** [comment]
this is a periodically reoccurring intellij problem. don't use scalafmt for range formatting or file a report with scala plugin. cc @unkarjedy.

**Comment by MarkSheinkman** [comment]
Got it. Thanks.
For posterity: https://youtrack.jetbrains.com/issue/SCL-18575
