### ISSUE TITLE
scalafmt command display wrong version number

### ISSUE THREAD

**Issue by michelou** [scalameta/scalafmt#2313]
My environment: MS Windows 10, Java JDK 11.0.9.1

## Preamble

Coursier dependencies are defined in the file `bootstrap-jar-urls` contained in the *bootstrap library* `scalafmt.jar` (part of the assembly file for Linux/MacOS); e.g.

```
$ pushd %TEMP% && %JAVA_HOME%\bin\jar xf c:\opt\scalafmt-2.6.1\lib\scalafmt.jar coursier/bootstrap/launcher/bootstrap-jar-urls && type coursier\bootstrap\launcher\bootstrap-jar-urls|findstr scalameta & popd
https://repo1.maven.org/maven2/org/scalameta/common_2.13/4.3.15/common_2.13-4.3.15.jar
https://repo1.maven.org/maven2/org/scalameta/fastparse-utils_2.13/1.0.1/fastparse-utils_2.13-1.0.1.jar
https://repo1.maven.org/maven2/org/scalameta/fastparse_2.13/1.0.1/fastparse_2.13-1.0.1.jar
https://repo1.maven.org/maven2/org/scalameta/parsers_2.13/4.3.15/parsers_2.13-4.3.15.jar
https://repo1.maven.org/maven2/org/scalameta/scalafmt-cli_2.13/2.6.1/scalafmt-cli_2.13-2.6.1.jar
https://repo1.maven.org/maven2/org/scalameta/scalafmt-core_2.13/2.6.1/scalafmt-core_2.13-2.6.1.jar
https://repo1.maven.org/maven2/org/scalameta/scalafmt-dynamic_2.13/2.6.1/scalafmt-dynamic_2.13-2.6.1.jar
https://repo1.maven.org/maven2/org/scalameta/scalafmt-interfaces/2.6.1/scalafmt-interfaces-2.6.1.jar
https://repo1.maven.org/maven2/org/scalameta/scalameta_2.13/4.3.15/scalameta_2.13-4.3.15.jar
https://repo1.maven.org/maven2/org/scalameta/trees_2.13/4.3.15/trees_2.13-4.3.15.jar
```

## Steps

Based on the above file `bootstrap-jar-urls` we have the following libraries in a `scalafmt 2.6.4` installation:

```
$ dir /s/b c:\opt\scalafmt-2.6.4\lib\scalafmt*
c:\opt\scalafmt-2.6.4\lib\scalafmt-cli_2.13-2.6.4.jar
c:\opt\scalafmt-2.6.4\lib\scalafmt-core_2.13-2.6.4.jar
c:\opt\scalafmt-2.6.4\lib\scalafmt-dynamic_2.13-2.6.4.jar
c:\opt\scalafmt-2.6.4\lib\scalafmt-interfaces-2.6.4.jar
c:\opt\scalafmt-2.6.4\lib\scalafmt.jar
```
Let's check that we have the correct files, i.e. library files for version 2.6.4 :
```
$ pushd %TEMP% && %JAVA_HOME%\bin\jar xf c:\opt\scalafmt-2.6.4\lib\scalafmt-core_2.13-2.6.4.jar META-INF/MANIFEST.MF && type META-INF\MANIFEST.MF & popd
Manifest-Version: 1.0
Implementation-Title: core
Implementation-Version: 2.6.4
Specification-Vendor: org.scalameta
Specification-Title: core
Implementation-Vendor-Id: org.scalameta
Specification-Version: 2.6.4
Implementation-URL: https://github.com/scalameta/scalafmt
Implementation-Vendor: org.scalameta

$ pushd %TEMP% && %JAVA_HOME%\bin\jar xf c:\opt\scalafmt-2.6.4\lib\scalafmt-interfaces-2.6.4.jar scalafmt.properties && type scalafmt.properties & popd
#scalafmt properties
#Mon Jul 20 17:30:28 UTC 2020
version=2.6.4
```

## Problem

Running the following command from the above 2.6.4 installation does display the wrong `scalafmt` version :
```
$ c:\opt\scalafmt-2.6.4\bin\scalafmt.bat --version
scalafmt 2.6.1
```

**NB.**  Unsurprisingly we observe the same behavior with version 2.7.5 of `scalafmt`.

From where does `scalafmt` get version 2.6.1 (is that hard-coded somewhere ?) ?!

## Expectation

Console output should be : `scalafmt 2.6.4`.

I would have expected `scalafmt` to use the version number found in file `scalafmt-interfaces-2.6.4.jar:scalafmt.properties`.

**Comment by kitbellew** [comment]
i have no idea how `scalafmt.BAT` is created; i haven't been able to find any instructions on how to install the tool for windows.

**Comment by michelou** [comment]
@kitbellew You're correct, there is currently no installer for Windows, BUT `scalafmt` itself just consists of a collection of JAR files managed by [Coursier](https://github.com/coursier/coursier) (file `bootstrap-jar-urls` above). So, I wrote `scalafmt.bat` myself (it mimics the basics of Coursier).

**NB.** I guess you know the concept of an *assembly file*; e.g. Li Haoyi uses the same technical hack for distributing his tool [`mill`](http://www.lihaoyi.com/mill/#windows) on Linux and Windows.

In fact `scalafmt.bat` is just a batch file at the end of the `scalafmt` execution chain. Thus my question relates to the internal organization of scalafmt and not to its usage by the end-user.

**Comment by kitbellew** [comment]
got it. all i can say is, the `scalafmt` that was created using `coursier` (https://scalameta.org/scalafmt/docs/installation.html#coursier) seems to show the right version.
```
$ ./scalafmt-2_7_2 --version
scalafmt 2.7.2
```
