### ISSUE TITLE
`// scalafmt: { trailingCommas = preserve }` not taking effect

### ISSUE THREAD

**Issue by adamsmd** [scalameta/scalafmt#2318]
- **`sbt-scalafmt` version**: 2.4.2
- **Integration**: SBT
- **Configuration**:
```
version = 2.7.5
maxColumn = 100
assumeStandardLibraryStripMargin = true
```

## Steps

Given code like this:
```scala
    // scalafmt: { trailingCommas = preserve }
    val x = Seq[String](
      // comment
      "string",
    )
```

When I run scalafmt like this:

```bash
sbt scalafmtAll
```

## Problem

Scalafmt formats code like this (note the missing comma after `"string"`):
```scala
    // scalafmt: { trailingCommas = preserve }
    val x = Seq[String](
      // comment
      "string"
    )
```

## Expectation

I would like the formatted output to look like this (i.e., the same as the original code):
```scala
    // scalafmt: { trailingCommas = preserve }
    val x = Seq[String](
      // comment
      "string",
    )
```

## Notes

If I add `trailingCommas = preserve` to `.scalafmt.conf`, the comma is correctly preserved.

**Comment by kitbellew** [comment]
this behaviour is expected, this specific parameter cannot be locally modified because rewrite rules are applied once per file.
