### ISSUE TITLE
Terminology: `keep` vs `preserve`

### ISSUE THREAD

**Issue by adamsmd** [scalameta/scalafmt#2319]
Some options use the `keep` keyword while others use the `preserve` keyword.  These words seem similar to me.  Is there a convention as to which options use which of these keywords?  Is there a reason to use two different words?

If not, I'd propose allowing either keyword and making them aliases of each other.  (Either that or standardize on one and deprecate the other.)

**Comment by kitbellew** [comment]
because documentation is updated immediately, without waiting for a release, this modification will be made just before v3.0.0 is released in the coming months.
