### ISSUE TITLE
Indentation of `else` in `if` expression

### ISSUE THREAD

**Issue by adamsmd** [scalameta/scalafmt#2320]
- `sbt-scalafmt` **version**: 2.4.2
- **Integration**: SBT
- **Configuration**:
```
version = 2.7.5

align.preset = none
align.stripMargin = true
assumeStandardLibraryStripMargin = true
maxColumn = 120
trailingCommas = preserve
```

## Steps

Given code like this:
```scala
object Foo {
  def bar(): Unit = {
    val keyword = if (1 == 2) { "A" } else { "B" }
    ()
  }
}

```

When I run scalafmt like this:

```bash
sbt 'scalafmtOnly Foo.scala'
```

## Problem

Scalafmt formats code like this:
```scala
object Foo {
  def bar(): Unit = {
    val keyword = if (1 == 2) { "A" }
    else { "B" }
    ()
  }
}
```

## Expectation

I would like the formatted output to look like the original code.

There are multiple ways to reasonably indent the `else` or leave it on the same line as the `if` (which is the actually desired output), but the output given by `scalafmt` is not one of them.

**Comment by kitbellew** [comment]
this behaviour is how the tool has been working historically. to format differently, try one of https://scalameta.org/scalafmt/docs/configuration.html#newlinesbeforemultiline options.

**Comment by adamsmd** [comment]
Setting `newlines.beforeMultiline` to `fold` produces

```scala
val keyword =
  if (1 == 2) { "A" }
  else { "B" }
```

That is better than what `scalafmt` was doing before, but what I really want is for the whole `if-else` expression to be put on one line like the following (column width permitting of course, and maybe only when the `if-else` is used as a sub-expression and not a statement).

```scala
val keyword = if (1 == 2) { "A" } else { "B" }
```

I'd really like this feature.  Should I open a separate issue to request the feature, or does this issue suffice?

**Comment by kitbellew** [comment]
what happens if you use `newlines.source = fold`?

**Comment by kitbellew** [comment]
ah, the reason is that `} else` is required to break. if you try
```
val keyword = if (1 == 2) "A" else { "B" }
```
it should work. if you need a block around the expression, it's too complex to be one-lined.
