### ISSUE TITLE
docstrings.style = Preserve is not recognised

### ISSUE THREAD

**Issue by unkarjedy** [scalameta/scalafmt#2343]
This template is a guideline, not a strict requirement.
- **Version**: 2.7.5
- **Integration**: IntelliJ
- **Configuration**:
```
version = 2.7.5
docstrings.style = Preserve
```

## Steps
Format any code.

Given code like this:
```scala
/*XXX*/
/*YYY*/
/**XXX*/
/**YYY*/
```
## Problem

Scalafmt config is not parsed:

```
Unknown input 'preserve'. Expected one of: asterisk, spaceasterisk, asteriskspace
```

## Expectation
It should be parsed as for
https://scalameta.org/scalafmt/docs/configuration.html#docstrings

**Comment by tototoshi** [comment]
I noticed the same problem.
The Preserve option has already appeared on the documentation site, but it seems that it will be available in the next (2.7.6?) release, which will include https://github.com/scalameta/scalafmt/commit/e726bdd1afb80f8da93e222b77b7a015ad0ede6c .
