### ISSUE TITLE
generation of example with all-configuration settings produces wrong config

### ISSUE THREAD

**Issue by unkarjedy** [scalameta/scalafmt#2344]
Just copy the huge config from
https://scalameta.org/scalafmt/docs/configuration.html#other 
(2.7.5 version at this moment)

Try format any scala file e.g. with IntelliJ.
Observe that it's not parsed due to many different issues with the config, some examples:
1. regexp are not escaped:
```
rewrite.neverInfix.includeFilters = [
  "[\w\d_]+"
]
```
it should be
```
rewrite.neverInfix.includeFilters = [
  "[\\w\\d_]+"
]
```
2. null values are present:
```
newlines.source = null
```

Looks like default values generation logic is broken.

Here is the list of the lines I had to change to make the config parsarable (I will omit all the error messages that those lines caused):
```
#continuationIndent.ctorSite = null
#continuationIndent.commaSiteRelativeToExtends = 2
#rewrite.redundantBraces.parensForOneLineApply = null
rewrite.sortModifiers.order = [
  implicit
  final
  sealed
  abstract
  override
  private
  protected
  lazy
  #open
  #transparent
  #inline
  #inline
  #infix
  #opaque
]
rewrite.neverInfix.includeFilters = [
  "[\\w\\d_]+"
]
indentOperator.exclude = "^(&&|\\|\\|)$"
#newlines.source = null
#newlines.implicitParamListModifierPrefer = null
#newlines.beforeMultiline = null
#newlines.beforeMultilineDef = null
#newlines.afterInfix = null
#runner.parser = "<Parse[Tree]>"
#runner.dialect = "<Dialect>"
project.includeFilters = [
  ".*\\.scala$"
  ".*\\.sbt$"
  ".*\\.sc$"
]
```

**Comment by kitbellew** [comment]
@unkarjedy dima, why do you need that?

generally, that list at the end is a dump of all internal values (basically, a `.toString`) and not intended as a serialization matching the parsing of parameters. some parameters, such as `newlines.source = classic`, can not be explicitly specified.

also, the page is generated from current `master` and not a specific release, so you'll see some parameters that are not yet available in any published version.

**Comment by unkarjedy** [comment]
It just confuses.
It kinda "pretends" to be a valid config :) 
I expected it to be a valid config and copy-pasted the config to test if IntelliJ at least doesn't fail with it.

If it's not supposed to be a valid config and the values are intentionally not supposed to be valid, then probably the values shouldn't be printed at all just not to confuse.

Or, if the listing isn't supposed to be useful for a user, maybe it shouldn't be added there at all?
A link to some internal class would be enough for those who want to play with the internals.
