### ISSUE TITLE
Scalafmt causes warning for infix when used with Scala 2.13

### ISSUE THREAD

**Issue by amorfis** [scalameta/scalafmt#2365]
multiarg infix syntax looks like a tuple and will be deprecated

- **Version**: 2.4.0
- **Integration**: sbt
- **Configuration**:
```
version = 2.4.0
style = defaultWithAlign
maxColumn = 120
align.openParenCallSite = false
align.openParenDefnSite = false
spaces.inImportCurlyBraces = true
danglingParentheses = true
rewrite.rules = [AsciiSortImports, PreferCurlyFors, RedundantBraces, RedundantParens]
```

## Steps

Given code like this:
```scala
class SystemUnderTestSpec extends AnyWordSpecLike with Matchers {

  "my system" should {
    "process some data and fail" when {
      "data is invalid" taggedAs(MyTag, NegativeTest) in {
        //...
      }
    }
  }
}  

```

When I run scalafmt like this:

```bash
scalafmtAll
```

## Problem

Scalafmt formats code like this:
```scala
"data is invalid" taggedAs (MyTag, NegativeTest) in {
```

## Expectation

I would like the formatted output to look like this:
```scala
"data is invalid" taggedAs(MyTag, NegativeTest) in {
```

Without the space after `taggedAs`. This space causes warning in Scala 2.13: "multiarg infix syntax looks like a tuple and will be deprecated"

Is there a way to configure scalafmt not to insert the space there? It shouldn't cause scalac warnings.

**Comment by kitbellew** [comment]
@amorfis are you saying that the warning in scala 2.13 is incorrect? aren't you in fact using a multiarg infix syntax?

**Comment by amorfis** [comment]
The warning is correct, and I don't want to use multiarg infix. I want to get rig of the space between `taggedAs` and opening parentesis but scalafmt keeps adding it.

**Comment by kitbellew** [comment]
are you saying that by removing space, it stops being a multiarg infix? what is it, then? since there's a space before `taggedAs`, it looks like an infix op. since there are two arguments after it, it looks like a multiarg. what am i missing? :)

**Comment by kitbellew** [comment]
perhaps the right solution is to add a dot before `taggedAs`?

**Comment by amorfis** [comment]
Ok, I understand now. Maybe it's a solution to add dot before `taggedAs`. However, it doesn't feel right that scalafmt formats code in a way that is causing warnings.

**Comment by kitbellew** [comment]
i think the problem is with the compiler which is confused when there's no space after the infix op and fails to produce a warning. space is optional here.
