### ISSUE TITLE
There is `docstrings.style` which is not `SpaceAsterisk` but more fit to `ScalaDoc`

### ISSUE THREAD

**Issue by taeguk** [scalameta/scalafmt#2370]
[Documentation](https://scalameta.org/scalafmt/docs/configuration.html#docstringsstyle--spaceasterisk) says, "`SpaceAsterisk` used to be called `ScalaDoc`".
But I think `AsteriskSpace` is more fit to `ScalaDoc` style because [original scaladoc guide examples](https://docs.scala-lang.org/style/scaladoc.html) and [scala standard library](https://github.com/scala/scala/blob/v2.12.2/src/library/scala/Predef.scala) use `AsteriskSpace`-like comments.

If my opinion is right, `AsteriskSpace` is better choice rather than `SpaceAsterisk` for the default value of `docstrings.style`.

**Comment by kitbellew** [comment]
@taeguk you might be right, but scalafmt tends to avoid changing defaults.
