### ISSUE TITLE
newlines.beforeMultiline = unfold doesn't seem to work correctly

### ISSUE THREAD

**Issue by haneul** [scalameta/scalafmt#2400]
- **Version**: 2.7.5
- **Integration**: cli
- **Configuration**:
```
newlines.beforeMultiline = unfold
```

## Steps

Given code like this (test.scala):
```scala
class Test {
  val a = functionCall(
    1,
    2
  )
}
```

when I run it
```bash
scalafmt tests.scala --stdout
```

Output looks like
```scala
class Test {
  val a = functionCall(
    1,
    2
  )
}
```

while I expected it to be

```scala
class Test {
  val a = 
    functionCall(
      1,
      2
    )
}
```

## Workaround

I couldn't find workaround.

## Notes

See also..

**Comment by kitbellew** [comment]
it works as designed, as it doesn't always force a newline (mostly does but not in trivial cases like this). there is no option that does.

https://scalameta.org/scalafmt/docs/configuration.html#newlinesbeforemultiline:
_... whether to force a new line before a multi-line body of `case/if/val` and **how to format it if the space is allowed.**_

**Comment by haneul** [comment]
thanks @kitbellew , 
not sure what's defined as trivial, I tried a bit more complicated ones, but newline is not forced always with

On the other hand,
```
newlines.beforeMultilineDef = unfold
```
```scala
class Test {
  def a = functionCall(
    1,
    2
  )
}
```
becomes 
```scala
class Test {
  def a =
    functionCall(
      1,
      2
    )
}
```
I think these two should exhibit the same behavior.
Any possibility to change these?

**Comment by kitbellew** [comment]
if the option is used widely by now, will be hard. `def` simply forces a break but that behavior was defined a while ago, which is why it uses a separate option.

we can change them to behave the same when both are defined at the class or object level.

**Comment by haneul** [comment]
it would be nice if the same behavior is applied for all, not limited to the class/object level.

**Comment by kitbellew** [comment]
that can be done but only in the opposite sense. if the def-specific option is not explicitly set, def will behave like val, and not val behaving like def.

**Comment by haneul** [comment]
I probably already does it. If it's the case, nvm on this. I might check some other options.
Thanks for the answers!

**Comment by kitbellew** [comment]
> it would be nice if the same behavior is applied for all, not limited to the class/object level.

do you really want your nested vals to look like this:
```
object a {

  def foo(....) = {
    // since most scala functions are limited to 30 lines
    // should it really break here?
    val bar =
      baz(
        qux
      )
    // why not this:
    val bar = baz(
      qux
    )
  }

  // this can be done, it's not subject to any method line limits
  private val bar =
    baz(
      qux
    )
}
```

**Comment by haneul** [comment]
Our guideline doesn't have method line limits.
And it simply requires if you have **multiline** then break newline before then.

```scala
class A {

  def foo(....) = {
    // so that case would likely be
    val bar = baz(qux)

    // but if something more complicated ones
    val bar2 =
       baz(
         a = blah,
         b =
           if (something) {
             blahblah
           }. else
             blahblahblah
           },
        )

    // or you may choose to do this as well
    val bar3 =
       baz(
         qux
       )
  }

**Comment by kitbellew** [comment]
let me think about it

**Comment by haneul** [comment]
thanks @kitbellew
