### ISSUE TITLE
[Scala 3] `error: outdent expected but case found` in braceless partial function

### ISSUE THREAD

**Issue by aeons** [scalameta/scalafmt#2425]
- **Version**: 3.0.0-RC1
- **Integration**: no
- **Configuration**:
```
version = 3.0.0-RC1
runner.dialect = scala3
```

## Steps

Given code like this:
```scala
val f: String => String =
  case "horses" => "are neat"
  case _ => "cows are sweet"
```

When I run scalafmt like this:

```bash
scalafmt Horses.scala
```

## Problem

Scalafmt prints:
```
scalafmt Horses.scala
/tmp/Horses.scala:2: error: outdent expected but case found
  case "horses" => "are neat"
  ^
```

## Expectation

I would expect `scalafmt` to format the partial function.

**Comment by tgodzik** [comment]
Thanks for reporting! This is already fixed in the parser, but I will leave it open to remind me to add a test when we update scalameta.
