### ISSUE TITLE
Single @ symbol when used by ammonite doesn't work with scalafmt

### ISSUE THREAD

**Issue by mdedetrich** [scalameta/scalafmt#2434]
- **Version**: 0.5
- **Integration**: Irrelevant
- **Configuration**:
```
version = 2.0.1
maxColumn = 100
```

## Steps

Given code like this within an ammonite session:
```scala
interp.load.ivy("io.circe" %% "circe-core" % "0.13.0")

@

println("Circe loaded")

```

When I run scalafmt like this:

```bash
scalafmt
```

## Problem

Scalafmt fails to format the code due to the single `@`, it just errors out.

## Expectation

Scalafmt should completely ignore the `@` since its an internal ammonite method that is used when dynamically loading jars into the current REPL session

## Workaround

Comment the `@` when doing `scalafmt` and uncomment afterwards. Note that using `// format: off` and `// format: on`, i.e.

```scala
// format: off
@
// format: on
```

Doesn't fix the issue (otherwise this would have been a very practical workaround). 

## Notes

Ammonite allows you to dynamically load jars (either by file or by maven/ivy) using bare scala code. In order to both signal to Ammonite that you are done dynamically loading these jars and allow Ammonite to cache these jars for performance reasons you need to add a `@` at the end of the block of the code that does this dynamic loading, ammonite calls this [Multi Stage Scripts](https://ammonite.io/#Multi-stageScripts).

I am not entirely sure that a single `@` like this is valid Scala code however its how Ammonite works currently, I suppose the best way would be to just ignore a single `@` for this case. If this is not valid Scala code then there is also an argument that Ammonite should change it, i.e. something like `@interp.multistage.end` or something along those lines.

**Comment by kitbellew** [comment]
what is the name of the file you're trying to format?

**Comment by kitbellew** [comment]
@mdedetrich only files with extension `.sc`  are supported for ammonite formatting. whatever tool you use should pass the filename to scalafmt.

**Comment by mdedetrich** [comment]
So I was formatting a `.sc` file in intellij's formatter, I will try again using the command line version of scalafmt
