### ISSUE TITLE
scala 3: 'with' incorrectly wrapped

### ISSUE THREAD

**Issue by raboof** [scalameta/scalafmt#2441]
This template is a guideline, not a strict requirement.
- **Version**: 2.4.2
- **Integration**: sbt
- **Configuration**:
```
version = 3.0.0-RC1
runner.dialect = scala3
```

## Steps

Given code like this:
```scala
object ValueTypes:
    case object Private
        extends ClassificationValue
        with ConstantText
```

When I run scalafmt like this:

```bash
sbt scalafmt
```

## Problem

Scalafmt formats code like this:
```scala
object ValueTypes:
    case object Private
        extends ClassificationValue
        with
          ConstantText
```

## Expectation

I would like the formatted output to ~look like this~ compile with scala3 ;)

## Workaround

(not found one yet)

## Notes

Testcase showing the problem for your convenience in 8b7ca07

**Comment by kitbellew** [comment]
@tgodzik in this case, `Template.self` points to `ConstantText`.

**Comment by tgodzik** [comment]
Just checked, this seems to be fixed in the parser already. I will release a new version.

**Comment by raboof** [comment]
confirmed :+1:
