### ISSUE TITLE
`SearchStateExploded` exception when significant indentation is used in pattern matching

### ISSUE THREAD

**Issue by tdudzik** [scalameta/scalafmt#2448]
- **Version**: 3.0.0-RC1
- **Integration**: CLI
- **Configuration**:
```
version = "3.0.0-RC1"
runner.dialect = Scala3
```

## Steps

Given code like this:
```scala
object Foo:
  def bar(): Option[RetType] = process(arg match
    case a: A if a.b =>
      None

    case a: A if a.c() =>
      None

    case a: A if a.c() =>
      None

    case a: A if a.b =>
      Some(someMethod().anotherMethod().fooBarMethod(ObjectWithLongName.method()))

    case a: A if a.c() =>
      val varName = a.method(a.someField.anotherField.method().map(ObjectWithLongName.A))
      val otherVarName = varName.method(a.someField.method(ObjectWithLongName.B))
      otherVarName

    case a: A if a.someField.otherField.function().exists(SomeObjectLongName.isTrue) =>
      None
  )
```

When I run scalafmt like this:

```bash
scalafmt
```

## Problem

Scalafmt throws `FailedToFormat` exception with a cause: `SearchStateExploded`.
```scala
org.scalafmt.cli.FailedToFormat: /path/to/Foo.scala
Caused by: org.scalafmt.Error$SearchStateExploded: Search state exploded on ')∙.[550:551]', line 19
	at org.scalafmt.internal.BestFirstSearch.shortestPath(BestFirstSearch.scala:174)
	at org.scalafmt.internal.BestFirstSearch.run$1(BestFirstSearch.scala:294)
	at org.scalafmt.internal.BestFirstSearch.getBestPath(BestFirstSearch.scala:295)
	at org.scalafmt.internal.BestFirstSearch$.apply(BestFirstSearch.scala:337)
	at org.scalafmt.Scalafmt$.$anonfun$doFormatOne$5(Scalafmt.scala:128)
```

## Expectation

No exception should be thrown. The file should be formatted.

### Workaround 1

We can make it work by adding to the configuration:
```
runner.maxStateVisits = 100000000
runner.optimizer.maxVisitsPerToken = 1000000
```
It works but formatting takes ~4 min.

### Workaround 2

The issue doesn't occur if we use curly brackets instead of significant indentation in pattern matching.

## Notes

The issue was found while running scalafmt on scaladoc project in Dotty. The code above is ~minimal code that is required to cause that issue. The original code is here: https://github.com/tdudzik/dotty/blob/master/scaladoc/src/dotty/tools/scaladoc/tasty/ClassLikeSupport.scala#L107 (`parseMember` method).

**Comment by kitbellew** [comment]
@tgodzik when parsing, do you keep `Token.Indentation.Indent/Outdent` as tokens in the tree? (they would serve as replacements for current `{}` pair for the formatter to latch on.)

**Comment by tgodzik** [comment]
> @tgodzik when parsing, do you keep `Token.Indentation.Indent/Outdent` as tokens in the tree? (they would serve as replacements for current `{}` pair for the formatter to latch on.)

I think doing `tree.tokenize` retokenizes the code within the pos of the tree, which means that those tokens are not related to the ones used in the parser:
```
  def tokens(implicit dialect: Dialect): Tokens = {
    origin match {
      case Origin.Parsed(input, dialect, pos) =>
        val tokens = dialect(input).tokenize.get
        tokens.slice(pos.start, pos.end)
      case _ =>
        dialect(Input.VirtualFile("<InternalTrees.tokens>", this.syntax)).tokenize.get
    }
  }
```

Another issue is that we insert Indentation in the same place where redundant whitespace is removed (to make it easier to parser), which means scalafmt wouldn't be able to see all the whitespaces.

What we would need to do is to first to keep the tokens for the tree (not sure why that is not so currently, it might be memory efficiency etc.) and then also insert indentation to these first tokens at the same time as we do the parsing. 

Alternatively, we could expose the additional scanner tokens on demand and look into those when needed. The biggest problem I see is the fact that the tokens are not saved.

**Comment by tgodzik** [comment]
It's all done here: https://github.com/scalameta/scalameta/blob/master/scalameta/parsers/shared/src/main/scala/scala/meta/internal/parsers/ScalametaParser.scala#L273

Indentation is actually not inserted anywhere, but served to the parser when needed. We would need to for sure to change the infrastructure here :/

**Comment by kitbellew** [comment]
> Another issue is that we insert Indentation in the same place where redundant whitespace is removed (to make it easier to parser), which means scalafmt wouldn't be able to see all the whitespaces.

the formatter doesn't really care about amount of whitespace. from what i remember, the formatter only needs to know if there were 1 or 2+ newlines, and whether the last whitespace was a newline or a space (this is primarily to handle comments which start at the beginning of the line, as many IDEs allow one to comment stuff out like that, and scalafmt doesn't indent comments "stuck" on the left).

this is the code where i "implemented" that logic in the rewriter:
https://github.com/scalameta/scalafmt/blob/369359572490c7c5ce554b1d4cfd985f398fb92a/scalafmt-core/shared/src/main/scala/org/scalafmt/rewrite/FormatTokensRewrite.scala#L269

so in essence you can replace the [last, if there are several] newline (and, if you want, all horizontal whitespace between it and a non-whitespace token) by an Indent or Outdent, as appropriate. perhaps the parser can return a different Input if the original cannot be mutated. we can change scalafmt to treat Indent as "<NL>{" and Outdent as "<NL>}".

**Comment by kitbellew** [comment]
> I think doing `tree.tokenize` retokenizes the code within the pos of the tree, which means that those tokens are not related to the ones used in the parser:
> 
> ```
>   def tokens(implicit dialect: Dialect): Tokens = {
>     origin match {
>       case Origin.Parsed(input, dialect, pos) =>
>         val tokens = dialect(input).tokenize.get
>         tokens.slice(pos.start, pos.end)
>       case _ =>
>         dialect(Input.VirtualFile("<InternalTrees.tokens>", this.syntax)).tokenize.get
>     }
>   }
> ```

i just read it again... are you saying that every single call to `x.tokens` parses the code again? why is that needed? and isn't that way too expensive?

**Comment by tgodzik** [comment]
> i just read it again... are you saying that every single call to `x.tokens` parses the code again? why is that needed? and isn't that way too expensive?

It only tokenizes the part of code the tree points to, so this should not be too expensive. It doesn't parse it at all.
