### ISSUE TITLE
The JenBrain intellij plugin marked as incompatible:

### ISSUE THREAD

**Issue by xinatcg** [scalameta/scalafmt#2489]
This template is a guideline, not a strict requirement.
- **Version**: 0.5
- **Integration**: IntelliJ
- **Configuration**:
```
version = 2.0.1
maxColumn = 100
```

## Steps

https://plugins.jetbrains.com/plugin/8236-scalafmt 

The plugin marked as incompatible:

![image](https://user-images.githubusercontent.com/55399567/116850768-21ef6980-abe9-11eb-8e54-e62b1924438b.png)

Given code like this:
```scala
ORIGINAL CODE
```

When I run scalafmt like this:

```bash
scalafmt
```

## Problem

Scalafmt formats code like this:
```scala
OUTPUT FROM SCALAFMT
```

## Expectation

I would like the formatted output to look like this:
```scala
EXPECTED FORMATTING OUTPUT
```

## Workaround

I've found that by...

## Notes

See also..

**Comment by tgodzik** [comment]
Thanks for reporting! The current versions of the Intellij Scala plugin have scalafmt support built in, so you should not use the deprecated scalafmt plugin 

More info https://scalameta.org/scalafmt/docs/installation.html
