### ISSUE TITLE
 AvoidInfix conflicts with RedundantParens in AnyFlatSpec?

### ISSUE THREAD

**Issue by Outwise** [scalameta/scalafmt#2500]
- **Version**: scalafmt 3.0.0-RC2
- **Integration**: IntelliJ
- **Configuration**:
```
version = "2.0.0"
project {
  git = true
}
align = "none"
maxColumn = 120
continuationIndent {
  defnSite = 2
  extendSite = 2
}
assumeStandardLibraryStripMargin = true
newlines {
  alwaysBeforeTopLevelStatements = true
}
verticalMultiline {
  arityThreshold = 1
  atDefnSite = true
  excludeDanglingParens = []
  newlineAfterOpenParen = true
  newlineBeforeImplicitKW = false
  newlineAfterImplicitKW = true
}
rewrite {
  rules = [
    "AvoidInfix"
    "PreferCurlyFors"
    "RedundantBraces"
    "RedundantParens"
    "SortImports"
    "SortModifiers"
  ]
  sortModifiers {
    order = [
      "override"
      "private"
      "protected"
      "implicit"
      "final"
      "sealed"
      "abstract"
      "lazy"
    ]
  }
}
```

## Steps

Given code like this:
```scala
class SomeClassSpec extends AnyFlatSpec with Matchers with Helper {

  behavior of "SomeClass"
  it should "test SomeClass in Some Way" in {
    ...
  }
```

When I run scalafmt like this:

```bash
scalafmt
```
(and same results with IntelliJ's save-on-format, format hotkey, githook)
## Problem

Scalafmt formats code like this:
```scala
class SomeClassSpec extends AnyFlatSpec with Matchers with Helper {

  behavior.of("SomeClass")
  it should "test SomeClass in Some Way" in {
    // test logic
  }
```

## Expectation

I would like the formatted output to look like this:
EITHER: (RedundantParens takes priority)
```scala
class SomeClassSpec extends AnyFlatSpec with Matchers with Helper {
  behavior of "SomeClass"
  it should "test SomeClass in Some Way" in {
    // test logic
  }
```
OR (AvoidInfix takes priority)
```scala
class SomeClassSpec extends AnyFlatSpec with Matchers with Helper {

  behavior.of("SomeClass")
  it.should("test SomeClass in Some Way").in {
    // test logic
  }
```
## Workaround

None yet...

## Notes

- These rules seem like they would conflict anyway, but I was surprised to see it handled inconsistently! I assumed it would desugar all of them or none of them, the docs seem to imply each rule does the opposite.
- AFAIK there isn't any way to order the rewrites by what should take precedent? Not sure how it decides what to apply?
- there might be something else specific to FlatSpec's sugared syntax I'm not seeing, a diff between these that would cause only one line to be modified?
- This seems to only impact the `behavior` line in our FlatSpecs, should, shouldEqual, etc are unaffected. 
- Any of these formats compile, it's a style/inconsistency problem. This happens consistently across all our spec files.

**Comment by kitbellew** [comment]
please look at `rewrite.neverInfix.{include,exclude}Filters`:

https://scalameta.org/scalafmt/docs/configuration.html#other

`should` and `in` are excluded, `of` is not. hence the behaviour you see. you can define your own list. i have an empty exclude list in our config and a https://scalameta.org/scalafmt/docs/configuration.html#fileoverride defined for `src/test/` file with a list which includes all kinds of `scalatest` matchers.
