### ISSUE TITLE
Interpolated string might be splitted

### ISSUE THREAD

**Issue by dos65** [scalameta/scalafmt#2501]
**Version**: 2.7.5 / 3.0.0-RC1

#### Existing code:

```scala
object x {
  s"aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa${f(token.pos)} ${g(foo.x)}"
}
```

#### After fmt:

```scala
object x {
  s"aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa${f(
    token.pos
  )} ${g(foo.x)}"
}
```
#### Expectation

No splits 

#### Notes:

It seems that splits produced only if it has at least two arguments and `f(>>token.pos<<)` column position is greater than `maxColumn`

**Comment by kitbellew** [comment]
@dos65 why is your expectation that a line exceeding `maxColumn` would not be split?

p.s. https://scalameta.org/scalafmt/docs/configuration.html#newlinesavoidforsimpleoverflow

**Comment by dos65** [comment]
@kitbellew because it's close to literals in their nature.

Also, I think it might confuse people. I was surprised that this compiles :smile: 
I didn't know that it's acceptable to have `\n` inside arguments in a non-multiline interpolated string.

**Comment by kitbellew** [comment]
> @kitbellew because it's close to literals in their nature.
> 
> Also, I think it might confuse people. I was surprised that this compiles 😄
> I didn't know that it's acceptable to have `\n` inside arguments in a non-multiline interpolated string.

i don't think we should change the default behaviour, but do check out that parameter, it will probably do what you want. if it does, we should probably close this issue.

**Comment by kitbellew** [comment]
@dos65 вадим, я пока закрою, но если параметр `newlines.avoidForSimpleOverflow = [tooLong]` не поможет, то ты мне скажи, пожалуйста.

**Comment by dos65** [comment]
@kitbellew 

Я тут случайно проверил - `newlines.avoidForSimpleOverflow = [tooLong]` не помогает.
Пример из scalameta:

```
// до
q"""
    ${instrument(requirement)} match {
       case (true, _) => ()
       case (false, $failures) => $InvariantFailedRaiseMethod(${showCode(requirement)}, $failures, $allDebuggees)
     }
"""

// после
q"""
  ${instrument(requirement)} match {
    case (true, _) => ()
    case (false, $failures) => $InvariantFailedRaiseMethod(${showCode(
 requirement
 )}, $failures, $allDebuggees)
   }
"""
```

Как-то не красиво выходит. 
Может все таки сделать чтобы по дефолту игнорировало интерполированные строки?

**Comment by kitbellew** [comment]
забавно... по дефолту нет, но #3080 было вчера.

**Comment by dos65** [comment]
> но #3080 было вчера

шик, тогда все ок!
