### ISSUE TITLE
Blank line before/after 2+lines defs

### ISSUE THREAD

**Issue by sjrd** [scalameta/scalafmt#251]
Original:

``` scala
trait OESVertexArrayObject extends js.Object {
  val VERTEX_ARRAY_BINDING_OES: Int = js.native
  def createVertexArrayOES(): WebGLVertexArrayObjectOES = js.native
  def deleteVertexArrayOES(arrayObject: WebGLVertexArrayObjectOES): Unit = js.native
  def isVertexArrayOES(arrayObject: WebGLVertexArrayObjectOES): Boolean = js.native
  def bindVertexArrayOES(arrayObject: WebGLVertexArrayObjectOES): Unit = js.native
}
```

Scalafmt:

``` scala
trait OESVertexArrayObject extends js.Object {
  val VERTEX_ARRAY_BINDING_OES: Int = js.native
  def createVertexArrayOES(): WebGLVertexArrayObjectOES = js.native
  def deleteVertexArrayOES(
      arrayObject: WebGLVertexArrayObjectOES): Unit = js.native
  def isVertexArrayOES(
      arrayObject: WebGLVertexArrayObjectOES): Boolean = js.native
  def bindVertexArrayOES(
      arrayObject: WebGLVertexArrayObjectOES): Unit = js.native
}
```

I would like the input to look like this:

``` scala
trait OESVertexArrayObject extends js.Object {
  val VERTEX_ARRAY_BINDING_OES: Int = js.native
  def createVertexArrayOES(): WebGLVertexArrayObjectOES = js.native

  def deleteVertexArrayOES(
      arrayObject: WebGLVertexArrayObjectOES): Unit = js.native

  def isVertexArrayOES(
      arrayObject: WebGLVertexArrayObjectOES): Boolean = js.native

  def bindVertexArrayOES(
      arrayObject: WebGLVertexArrayObjectOES): Unit = js.native
}
```

Using
- 0.2.5 --Scala.js

**Comment by olafurpg** [comment]
I agree that it would be nice to have blank lines inserted for you. It's a bit tricky however, for example should scalafmt remove blank lines when a multiline method becomes single-line?

I added the label enhancement since this is not a blocker, you can insert the blank lines yourself to get the desired output.

**Comment by djspiewak** [comment]
This is an important feature for me as well.  I would also like to see it in situations like this:

```scala
def foo(a: Int, b: Int) = {
  for {
   ...
```

Currently reformats to (with a microscopic line limit):

```scala
def foo(
    a: Int,
    b: Int) = {
  for {
   ...
```

Should be:

```scala
def foo(
    a: Int,
    b: Int) = {

  for {
   ...
```

Similarly, if we raise the microscopic line limit, it should reformat *back* to:


Currently reformats to (with a microscopic line limit):

```scala
def foo(a: Int, b: Int) = {
  for {
   ...
```

In other words, yes, delete the spurious newline.

**Comment by olafurpg** [comment]
I agree that it would be great if scalafmt could automatically add/remove blank lines like these. [Here](https://github.com/olafurpg/scalafmt/blob/c63e6203333c223741b486cdfc348d34f6c43a8e/core/src/main/scala/org/scalafmt/internal/FormatWriter.scala#L121) is the line where blank lines are generated. I believe a best way to encode these ideas would be to do a pass on the `locations` variable and figure out which `split.isDouble` should be updated.

**Comment by mikaelstaldal** [comment]
@olafurpg It is not always feasible to "insert blank lines yourself", not if you generate code with Scalameta and pass it directly to scalafmt.

**Comment by olafurpg** [comment]
@mikaelstaldal even for code generation it's possible to do `"\n" + Tree.syntax`

**Comment by olafurpg** [comment]
The convention is that users manually decide where to insert blank lines. I agree it would be a nice enhancement to be able to automatically enforce that multiline defs get a blank line before+after, please reopen if you would like to take a stab at implementing that functionality. This functionality is already partially implemented in the `newlines.alwaysBeforeTopLevelStatements` setting, but the setting does not insert a blank line after multiline defs.
