### ISSUE TITLE
Alphabetical sorting of methods in traits, objects and classes

### ISSUE THREAD

**Issue by tusharmath** [scalameta/scalafmt#2510]
This template is a guideline, not a strict requirement.
- **Version**: 0.5
- **Integration**: IntelliJ
- **Configuration**:
```
version = 2.0.1
maxColumn = 100
```

## Steps

Given code like this:
```scala
trait Foo {
  def b: String = ???
  def a: String = ???
}
```

When I run scalafmt like this:

```bash
scalafmt
```

## Problem

Scalafmt formats code like this:
```scala
trait Foo {
  def b: String = ???
  def a: String = ???
}
```

## Expectation

I would like the formatted output to look like this:
```scala
trait Foo {
  def a: String = ???
  def b: String = ???
}

```
`a` should come before `b`.

## Workaround

None

## Notes

This can significantly reduce merge conflicts in the file.

**Comment by kitbellew** [comment]
> This can significantly reduce conflicts in the file.

which conflicts, and how will it help?

also, which typical coding style does it replicate? i have seen ordering based on fields vs methods, and private vs public, and grouping by interfaces implemented, but never alphabetically...

**Comment by tusharmath** [comment]
@kitbellew apologies, I meant resolving merge conflicts. Because the methods/fields are added in a particular order, auto-merge becomes a lot more effective.

> also, which typical coding style does it replicate? i have seen ordering based on fields vs methods, and private vs public, and grouping by interfaces implemented, but never alphabetically

Here is a reference of how [tslint] a scalafmt equivalent for typescript does it.

**Summary**
1. Firstly methods and fields form groups based on modifiers such as `private` `public` `implicit` `def` `val` etc.
2. How the groups are ordered should also be configurable.
3. Within each group the ordering can be `alphabetize`.


[tslint]: https://palantir.github.io/tslint/rules/member-ordering/

**Comment by kitbellew** [comment]
scalafmt works on tokens, not trees, generally preserving their order, so this type of rewrite will probably be nearly impossible. you can try moving this request into scalafix.
