### ISSUE TITLE
Feature request: ability to have multiple blank lines around various kinds of elements

### ISSUE THREAD

**Issue by djneades** [scalameta/scalafmt#2511]
- **Version**: 3.0.0-RC2

## Desire

I should like to be able to configure Scalafmt to format code to look like this, with two blank lines surrounding top-level [template definitions (`TmplDef)`](https://dotty.epfl.ch/docs/reference/syntax.html#declarations-and-definitions):

```scala
import scala.collection.mutable.ArrayBuffer


/** 2 blank lines above and below top-level trait definition */
trait A


// 2 blank lines above top-level class definition
// (none below due to end of file)
class B:

  /** 1 blank line above and below method definition */
  def A = ???

  /** 1 blank line above and below nested trait definition */
  trait Bar
      extends A

  /** 1 blank line above (none below due to end of file) */
  lazy val x = 1
```

Some coding styles may prefer something like this, with three blank lines surrounding top-level template definitions and two blank lines surrounding nested method definitions:

```scala
import scala.collection.mutable.ArrayBuffer



/** 3 blank lines above and below top-level trait definition */
trait A:

   // 1 blank line above (2 below due to following def)
   val x = 32
  
  
   /** 2 blank lines above and below nested method definition */
   def A =
      // beginning of a lengthy method body containing a blank line
     
      // continuation of lengthy body following a blank line
      ???


   // 2 blank lines above nested method definition
   // (3 below due following class)
   def B = ???



// 3 blank lines above top-level class definition
// (none below, due to end of file)
class B:


   /** 2 blank lines above and below */
   def A = ???


   /** 2 blank lines above and below nested-trait */
   trait Bar
      extends A


   // 1 blank line normally above val, but 2 enforced due to
   // preceding nested trait (none following due to end of file)
   lazy val x = 1
```

## Rationale

Being able to add more than one blank line before certain major elements such as [template definitions (`TmplDef)`](https://dotty.epfl.ch/docs/reference/syntax.html#declarations-and-definitions) would make it easier to distinguish between the various major and minor elements in a source file. For example, it is a lot easier to see where a class begins and ends if that class is surrounded by more whitespace than the methods and other items _within_ that class. In Scala, where multiple traits, classes, objects, etc. are often defined in a single source file, marking the boundaries of such major elements clearly would be especially useful.

Similarly, it is not unusual in many Scala coding styles to allow single blank lines within a method body. It would therefore be useful to be able to configure, say, two blank lines before and after method definitions, so that the boundaries of the method are clear and not obfuscated by the the intra-method blank lines.

## Notes

1. This feature would be useful even if it addressed only top-level template definitions.

2. However, it would be beneficial to be able to configure the number of blank lines surrounding many of the different Scala 3 syntax [Declarations and Definitions](https://dotty.epfl.ch/docs/reference/syntax.html#declarations-and-definitions) (e.g. `RefineDcl`, `TmplDef`, `Extension`).

3. It may be useful to be able to configure the minimum number of blank lines surrounding top-level elements of each kind separately from those same elements when they are nested (e.g. within the body of a template or method).

4. It may also be useful to be able to treat single-line declarations and definitions separately from those that extend over several lines.

**Comment by kitbellew** [comment]
@olafurpg ^^^?

**Comment by olafurpg** [comment]
Sounds reasonable to me. I can imagine blank lines become more important when using the significant indentation syntax because you don’t have a closing brace.

**Comment by nscarcella** [comment]
I would like to see this too, since double empty lines is something I often use to keep code from cramping.

Problem is I'm not sure It's something I can generalize it to all top level elements or all methods.

What I would truly love to see as a complement of this is a `newlines.source=keepAll` sort of configuration that would maintain whatever newlines I have on the source untouched (even if this disables other insertion/deletion related rules).

**Comment by kitbellew** [comment]
> What I would truly love to see as a complement of this is a `newlines.source=keepAll` sort of configuration that would maintain whatever newlines I have on the source untouched (even if this disables other insertion/deletion related rules).

This tool is designed to keep code readable across teams collaborating on it. If you can't generalize the rules you are applying, multiple team members will never be able to follow them.

If you use multiple lines _within_ a method, you could split it into multiple methods or add a comment for visual separation and code clarity. and lines between methods would be covered if this issue is ever implemented.

**Comment by nscarcella** [comment]
@kitbellew Although I fully understand what you are saying (and completely agree for most scenarios) I don't believe that having some degree of flexibility goes against a robust rule system.

With the current configuration rules I'm able to freely choose whether or not to place single blank lines between any two lines of code and it's something everyone on my team does at their own criteria. This does not mean the tool is flawed or the criteria arbitrary, on the contrary, it means we acknowledge that the need for spacing can be context dependent and it's not unreasonable to leave it to the developer to decide.

I will gladly admit that my proposed implementation might not be the best approach if it does not align with the spirit of the tool, but I do ask you to consider that having "large gaps" to contrast with "short gaps" can be a powerful tool to organize code. Adding comments as you suggest is, of course, a very useful tool too, but having green lines all around can be very distracting and it's placement is just as hard to transmit to multiple team members as proper use of blank lines.

If keeping all the blanks feels too loose of a rule, allowing me to keep up to a certain number would be just as good to me (after all, all I want to be able to do is place two blanks after each other here and there). Many similar (very opinionated) tools for other languages have settings for the max amount of blanks you are allowed to keep and it's rarely a cause of trouble for code readability.

Even a `keepDoubleBlanks` would make me super happy. I just need more ways to visually distance abstractions now that we are kissing the brackets goodbye.

**Comment by kitbellew** [comment]
@nscarcella i understand and sympathize. however, there are multiple places around the code which assume that existence of a blank line _in the source_ is a purely binary state, and making a change like this is a full-time job.

so, the only option is to "invent" blanks at the end, when the code is printed. that requires a clear set of rules.

**Comment by nscarcella** [comment]
@kitbellew Ok, I understand. Thanks for taking the time to clarify!

I still hope the original feature request gets accepted. Being able to insert blanks to top level elements might be good enough for most cases, especially if we can have different settings for single-line declarations from those that extend over several lines.

**Comment by djneades** [comment]
@kitbellew You guys are great. Thank you!

**Comment by kitbellew** [comment]
> @kitbellew You guys are great. Thank you!

aren't we, right?! :) now if you could please test it...

**Comment by djneades** [comment]
@kitbellew Sure thing.

I think I’ve managed to get the most recent snapshot installed:

```bash
.\scalafmt --version
scalafmt 3.0.0-RC4+16-f1b5d3fe-SNAPSHOT
```

Using this configuration:

```
maxColumn = 80

runner.dialect = scala3

newlines {
  topLevelStatements = [before, after]
  topLevelStatementsMinBreaks = 1
}
```

Running Scalafmt on this code:

```scala
package dev.muve.vdom

given intToVAValueString: Conversion[Number, VAValue[String]] =
  (x: Number) => VAValue(x.toString)

// import math.Numeric.Implicits.infixNumericOps
//
// Foo
// Bar
```

Introduces a spurious blank line into the comment block (one not introduced by 3.0.0-RC4 with the same configuration):

```scala
package dev.muve.vdom

given intToVAValueString: Conversion[Number, VAValue[String]] =
  (x: Number) => VAValue(x.toString)

// import math.Numeric.Implicits.infixNumericOps

//
// Foo
// Bar
```

In addition, the same configuration takes this code:

```scala
package x.y.z

object Foo:

  def apply[V <: VAType](someProperty: String): SomePropertyBuilder[V] =
    new SomePropertyBuilder(someProperty)

/** A doc comment. */
class Bar[V <: VAType](someProperty: String)
    extends SomePropertyBuilder[V](someProperty)
```

And introduces a spurious blank line after the doc comment (again, one not introduced by 3.0.0-RC4 with the same configuration):

```scala
package x.y.z

object Foo:

  def apply[V <: VAType](someProperty: String): SomePropertyBuilder[V] =
    new SomePropertyBuilder(someProperty)

/** A doc comment. */

class Bar[V <: VAType](someProperty: String)
    extends SomePropertyBuilder[V](someProperty)
```

**Comment by djneades** [comment]
@kitbellew Reading the updated docs, I now realize that the configuration in my previous comment is now deprecated, but perhaps the behaviour shouldn’t have changed to insert the spurious lines anyway?

**Comment by djneades** [comment]
@kitbellew The spurious blank line problem also occurs with this new configuration:

```
maxColumn = 80

runner.dialect = scala3

newlines {
  topLevelStatementBlankLines = [{ blanks { before = 1, after = 1 } }]
}
```

Thus, this source code:

```scala
package x.y.z

object Foo:

  def apply[V <: VAType](someProperty: String): SomePropertyBuilder[V] =
    new SomePropertyBuilder(someProperty)

/** A doc comment. */
class Bar[V <: VAType](someProperty: String)
    extends SomePropertyBuilder[V](someProperty)
```

Is reformatted by `3.0.0-RC4+16-f1b5d3fe-SNAPSHOT` to:

```scala
package x.y.z

object Foo:

  def apply[V <: VAType](someProperty: String): SomePropertyBuilder[V] =
    new SomePropertyBuilder(someProperty)

/** A doc comment. */

class Bar[V <: VAType](someProperty: String)
    extends SomePropertyBuilder[V](someProperty)
```

**Comment by djneades** [comment]
@kitbellew There’s a missing closing brace in the new documentation for `newlines.topLevelStatementBlankLines`:

```
// these two are equivalent
newlines.topLevelStatementBlankLines = [{ blanks { before = 1, after = 1 }]
newlines.topLevelStatementBlankLines = [{ blanks = 1 }]
```

The second line in that block should be:

```
newlines.topLevelStatementBlankLines = [{ blanks { before = 1, after = 1 } }]
```

**Comment by djneades** [comment]
@kitbellew Using this config:

```
maxColumn = 80

runner.dialect = scala3

newlines {
  topLevelStatementBlankLines = [{ blanks { before = 3, after = 3 } }]
}
```

This code:

```scala
maxColumn = 80

runner.dialect = scala3

newlines {
  topLevelStatementBlankLines = [{ blanks { before = 3, after = 3 } }]
}
```

Is reformatted by `3.0.0-RC4+16-f1b5d3fe-SNAPSHOT` to:

```scala
package x.y.z

object Foo:

  def apply[V <: VAType](someProperty: String): SomePropertyBuilder[V] =
    new SomePropertyBuilder(someProperty)



/** A doc comment. */

class Bar[V <: VAType](someProperty: String)
    extends SomePropertyBuilder[V](someProperty)
```

Other than the spurious blank line after the doc comment, I would have expected there to be three blank lines rather than one before the `object Foo:` line. If the file contains imports, then the blank lines are added as I would expect. Thus, this code:

```scala
package x.y.z

import scala.scalajs.js

object Foo:

  def apply[V <: VAType](someProperty: String): SomePropertyBuilder[V] =
    new SomePropertyBuilder(someProperty)

/** A doc comment. */
class Bar[V <: VAType](someProperty: String)
    extends SomePropertyBuilder[V](someProperty)
```

Is formatted appropriately (excepting the spurious blank line after doc comment) to this:

```scala
package x.y.z

import scala.scalajs.js



object Foo:

  def apply[V <: VAType](someProperty: String): SomePropertyBuilder[V] =
    new SomePropertyBuilder(someProperty)



/** A doc comment. */

class Bar[V <: VAType](someProperty: String)
    extends SomePropertyBuilder[V](someProperty)
```

**Comment by djneades** [comment]
@kitbellew Ah, perhaps your not adding blank lines after the `package x.y.z` was deliberate, given the handling of constructs like this?

```scala
package core {

  object O {
    val x1 = 1
    val x2 = 2

    def A =
      "A"

    def B = {
      "B"
    }

  }



  object P {
    val x1 = 1
    val x2 = 2

    def A =
      "A"

    def B = {
      "B"
    }
  }

}
```

I have no problem at all with how that is formatted. This is the config I used:

```scala
maxColumn = 80

runner.dialect = scala3

newlines {
  topLevelStatementBlankLines = [
    { maxNest = 1, blanks { before = 3, after = 3 } }
    ]
}
```

Nevertheless, the situation in my previous comment does still seem somewhat strange.

**Comment by djneades** [comment]
@kitbellew One further (possibly unrelated) oddity. With this configuration:

```
maxColumn = 80

runner.dialect = scala3

newlines {
  topLevelStatementBlankLines = [
    { maxNest = 1, blanks { before = 3, after = 3 } }
    ]
}

optIn.forceBlankLineBeforeDocstring = true
```

This code:

```scala
package x.y

def foo[X](f: => X): String = ???

extension (s: String)

  /** A documentation comment. */
  def baz(cb: String => Unit): Unit =
    ???
```

Is reformatted by `3.0.0-RC4+16-f1b5d3fe-SNAPSHOT` to:

```scala
package x.y

def foo[X](f: => X): String = ???



extension (s: String)
  /** A documentation comment. */
  def baz(cb: String => Unit): Unit =
    ???
```

One can simply move the doc comment to before the `extension (s: String)` line and all is then well (and Scaladoc remains happy). However, the loss of the blank line before the doc comment in this valid code is arguably infelicitous, and means that one has to position doc comments for single-method extensions differently to doc comments for multiple-method extensions such as these:

```scala
package x.y

def foo[X](f: => X): String = ???

extension (s: String)

  /** A documentation comment. */
  def baz(cb: String => Unit): Unit =
    ???

  /** Another one. */
  def bar(cb: String => Unit): Unit =
    ???
```

The blank lines above both of those doc comments are kept upon formatting, as I would expect.

Note, however, that this code:

```scala
package x.y

def foo[X](f: => X): String = ???

extension (s: String)
  /** A documentation comment. */
  def baz(cb: String => Unit): Unit =
    ???
  /** Another one. */
  def bar(cb: String => Unit): Unit =
    ???
```

is reformatted to:

```scala
package x.y

def foo[X](f: => X): String = ???



extension (s: String)
  /** A documentation comment. */
  def baz(cb: String => Unit): Unit =
    ???

  /** Another one. */
  def bar(cb: String => Unit): Unit =
    ???
```

I would expect a blank line to have been inserted before the first doc comment there, as it was before the second.

**Comment by djneades** [comment]
@kitbellew The aforementioned observations cover all the wrinkles I have thus far encountered running `3.0.0-RC4+16-f1b5d3fe-SNAPSHOT` against my Scala 3 codebase.

I’d like to take this opportunity to convey my thanks again – I’m delighted with this feature and very much looking forward to its appearing in a release.

Now, about those non-top-level definitions … 😁

**Comment by djneades** [comment]
@kitbellew Ok, I was wrong. I have one small additional request for your consideration.

Given the following configuration:

```
maxColumn = 80

runner.dialect = scala3

newlines {
  topLevelStatementBlankLines = [{ blanks { before = 3, after = 3 } }]
}
```

This code:

```scala
package x.y

import cats.effect.IO
import cats.effect.unsafe.implicits.global

type Effect[X] = IO[X]

type MatchEffect = IO[?]

def asEffect[X](f: => X): Effect[X] = IO { f }

class Foo:
  val x = 10
```

Is formatted as:

```scala
package x.y

import cats.effect.IO
import cats.effect.unsafe.implicits.global

type Effect[X] = IO[X]

type MatchEffect = IO[?]

def asEffect[X](f: => X): Effect[X] = IO { f }



class Foo:
  val x = 10
```

That is _almost_ what I want. I like how the single-line definitions do not have additional blank lines added before them. Except that, I really would like there to be additional blank lines after the last `import` statement, like this:

```scala
package x.y

import cats.effect.IO
import cats.effect.unsafe.implicits.global



type Effect[X] = IO[X]

type MatchEffect = IO[?]

def asEffect[X](f: => X): Effect[X] = IO { f }



class Foo:
  val x = 10
```

This is related to my comments earlier about definitions directly following a `package` line with no intervening `imports`. What I am seeking is for the preliminary `package` and `import` statements to be clearly separated by several lines from the more meaningful code that follows, whether or not the first top-level definition in that subsequent code spans more than one line.
