### ISSUE TITLE
Wiki links are destroyed when docstrings.wrap is true

### ISSUE THREAD

**Issue by now** [scalameta/scalafmt#2521]
This template is a guideline, not a strict requirement.
- **Version**: 3.0.0-RC3
- **Integration**: CLI
- **Configuration**:
```
version = 3.0.0-RC3
```

## Steps

Given code like this:
```scala
/** [[https://example.org This link will be destroyed]]. */
```

When I run scalafmt like this:

```bash
scalafmt
```

## Problem

Scalafmt formats code like this:
```scala
/** [[https://example.orgThis link will be destroyed]]. */
```

## Expectation

I would like the formatted output to look like this:
```scala
/** [[https://example.org This link will be destroyed]]. */
```

## Workaround

None available.

## Notes

I tried looking for the culprit, but I couldn’t find it.  I hope that someone with more intimate knowledge of the formatter can fix this or point me in the right direction.  Thank you!

**Comment by kitbellew** [comment]
duplicate, fixed

**Comment by now** [comment]
Hi,

I’m sorry, but I can’t find the commit that fixes this since the release of 3.0.0-RC3.  Also, I couldn’t find an issue related to this issue, but I guess I didn’t search well enough.  Could you please point me in the right direction here?

Thank you!

**Comment by kitbellew** [comment]
@now no trust :) scalameta/scalameta#2350

**Comment by now** [comment]
Ouch, I forgot to check scalameta, even though I saw that the ScalaDoc parser came from there.  Sorry about that.  And it wasn’t a question of trust, it was a question of hoping to avoid any misunderstandings.  :-)

Thank you for the clarification and for your work on this project!

**Comment by kitbellew** [comment]
no problem, don't worry about it. interesting that this problem has existed since the beginning, but only now has it been reported -- and twice in a row.
