### ISSUE TITLE
Scala 3: Reformatting breaks invocation of curried method

### ISSUE THREAD

**Issue by djneades** [scalameta/scalafmt#2522]
- **Version**: 3.0.0-RC3
- **Integration**: Sbt via sbt-scalafmt 2.4.2
- **Configuration**:
```
version = 3.0.0-RC3
maxColumn = 80

runner.dialect = scala3
```

## Steps

Given code like this:
```scala
def f(s: String)(t: String) = s"$t: $s"

def g =
  f("Foo")
    ("Bar")
```

When I run scalafmt like this:

```bash
scalafmt
```

## Problem

Scalafmt formats the code like this, which does not compile:
```scala
def f(s: String)(t: String) = s"$t: $s"

def g =
  f("Foo")
  ("Bar")
```

## Expectation

I should like the formatted code to compile.

## Workaround

Scalafmt will not break code where the second opening paren is moved up a line:
 
```scala
def f(s: String)(t: String) = s"$t: $s"

def g =
  f("Foo")(
    "Bar")
```

## Notes

Using the `RedundantParens` rewrite also causes a possibly related problem. With this configuration:

```
version = 3.0.0-RC3
maxColumn = 80

runner.dialect = scala3

rewrite.rules = [ RedundantParens ]
```

Reformatting the original code above results in the following non-compiling code:

```scala
def f(s: String)(t: String) = s"$t: $s"

def g =
  f("Foo") "Bar"
```

**Comment by tgodzik** [comment]
Thanks for reporting! I wasn't aware of this kind of indentation syntax:
```
def g =
  f("Foo")
    ("Bar")
```

I opened up an issue in dotty https://github.com/lampepfl/dotty/issues/12554 since I can't find it actually documented anywhere.

**Comment by djneades** [comment]
@tgodzik Thank you!

**Comment by djneades** [comment]
@tgodzik Would you find this (currently legal with Scala 3.0) indentation syntax unexpected?

```scala
def f(aLongNameToForceWrapping: String)
     (anotherLongNameToForceWrappingOnToTheNextLine: String) =
  "hello"

def g(aLongNameToForceWrapping: String)
     (using anotherLongNameToForceWrappingOnToTheNextLine: String) =
  f("Foo")("Bar")
```

I like the above – it seems much cleaner than the following output from Scalafmt using the first configuration above:

```scala
def f(aLongNameToForceWrapping: String)(
    anotherLongNameToForceWrappingOnToTheNextLine: String
) =
  "hello"

def g(aLongNameToForceWrapping: String)(using
    anotherLongNameToForceWrappingOnToTheNextLine: String
) =
  f("Foo")("Bar")
```

Is there a way to configure Scalafmt to format along the lines of the former here?

**Comment by djneades** [comment]
@tgodzik Actually, what I’d really like Scalafmt to output is something like this (also currently legal with Scala 3.0):

```scala
def fnWithALongerName
    (aLongNameToForceWrapping: String)
    (anotherLongNameToForceWrappingOnToTheNextLine: String) =
  "hello"

def anotherFnWithALongerName
    (aLongNameToForceWrapping: String)
    (using anotherLongNameToForceWrappingOnToTheNextLine: String) =
  fnWithALongerName("Foo")("Bar")
```

**Comment by tgodzik** [comment]
The definitions parse correctly. The problem with:
```
def g =
  f("Foo")
    ("Bar")
```
is that is problematic to distinguish if it's an application of a second parameter list or just a string in parens. It seems Scala 3 distinguishes that with indentation, which wasn't the case before.

> Actually, what I’d really like Scalafmt to output is something like this (also currently legal with Scala 3.0):
Not sure if that is possible currently.

**Comment by djneades** [comment]
@tgodzik Understood, thank you. I did follow the discussions on the various indentation issues during Dotty/Scala 3 development, and there was a point in time where paren-less method arguments were being mooted. Variations along the lines of this, IIRC:

```scala
def g =
  f:
    "Foo"
    "Bar"
```

It is possible that the acceptance of my original `g` example is some hangover from that, I guess.

Incidentally, this is also currently valid:

```scala
def g =
  f
    ("Foo")
    ("Bar")
```

**Comment by tgodzik** [comment]
We should be able to support that in the parser, but I would want some clarification from the compiler team on the rules here.
