### ISSUE TITLE
Automatically insert end markers for longer braceless blocks

### ISSUE THREAD

**Issue by tgodzik** [scalameta/scalafmt#2523]
## Steps

Given code like this:
```scala
def hello = 
  println(1)
  println(2)
  println(3)
  println(4)
```

When I run scalafmt like this:

```bash
scalafmt
```

## Problem

Scalafmt formats code like this:

```scala
def hello = 
  println(1)
  println(2)
  println(3)
  println(4)
```

## Expectation

I would like the formatted output to look like this:

```scala
def hello = 
  println(1)
  println(2)
  println(3)
  println(4)
end hello
```

## Workaround

Manually inserting the markers.

## Notes

This is a follow up from https://contributors.scala-lang.org/t/should-the-compiler-help-with-inserting-end-markes/5074/9

I am not exactly sure how hard it would be to implement @kitbellew might know better. But this would essentially mean inserting a new end stat, since currently `end` is treated as a separate stat by the parser.

**Comment by kitbellew** [comment]
this is where outdent token would help...

**Comment by tgodzik** [comment]
> this is where outdent token would help...

I know :( but I am not sure how to make it work without changing the parser too much.
