### ISSUE TITLE
Multiple annotations on primary constructor

### ISSUE THREAD

**Issue by charpov** [scalameta/scalafmt#2524]
This valid Scala code:
```scala
class Test @throws[NullPointerException]("if str is null") @throws[IllegalArgumentException]("if str is empty") (str: String) {}
```
causes a parse error in all the version of Scalafmt I tried.

Note that IntelliJ seems confused as well.

**Comment by kitbellew** [comment]
i got this in the `master` version:
```
class Test @throws[
    NullPointerException](
    "if str is null") @throws[
    IllegalArgumentException](
    "if str is empty") (str: String) {}
```
no parse errors.

**Comment by charpov** [comment]
I can't seem to reproduce the error.  I don't know what was going on when I first tried it.

The output doesn't look very good, though...

**Comment by kitbellew** [comment]
> The output doesn't look very good, though...

use a different `maxColumn` (mine was 40) and a different `newlines.source`.

**Comment by charpov** [comment]
When I said it didn't look good, I was referring to *your* output.  The line breaking is pretty awful.
