### ISSUE TITLE
Renaming import and wildcard import break in Scala 3 syntax

### ISSUE THREAD

**Issue by kubukoz** [scalameta/scalafmt#2535]
- **Version**: 3.0.0-RC3
- **Integration**: vscode or none
- **Configuration**: 
```
version = "3.0.0-RC3"
runner.dialect = scala3

rewrite.rules = [
  ExpandImportSelectors
]
```

Note that `ExpandImportSelectors` is necessary for this, otherwise everything works fine.

## Steps

Given code like this:

```scala
// in foo.scala
import foo.{bar as baz, *}
```

When I run scalafmt like this:

```bash
scalafmt foo.scala
```

## Problem

Scalafmt formats code like this:
```scala
import foo.{bar => baz, _}
```

## Expectation

I would like the formatted output to look like this:
```scala
import foo.{bar as baz, *}
```

## Workaround

Split the wildcard and renaming import

**Comment by tgodzik** [comment]
Thanks for reporting! I think this is due to the fact that the default to String will use `=>`. Let me see if we can fix that in scalameta.

**Comment by kitbellew** [comment]
@tgodzik this code should work, perhaps the dialect is not passed correctly:
https://github.com/scalameta/scalameta/blob/main/scalameta/trees/shared/src/main/scala/scala/meta/internal/prettyprinters/TreeSyntax.scala#L1151

p.s. should the unimport `_` be checked for `allowStarWildcardImport`?

**Comment by tgodzik** [comment]
> @tgodzik this code should work, perhaps the dialect is not passed correctly:
> https://github.com/scalameta/scalameta/blob/main/scalameta/trees/shared/src/main/scala/scala/meta/internal/prettyprinters/TreeSyntax.scala#L1151
> 

Yeah, that might be it, we take an implicit dialect, I will check that out.

> p.s. should the unimport `_` be checked for `allowStarWildcardImport`?

It should! I will change that.

**Comment by kitbellew** [comment]
however, one quick question: why do we need to reconstruct the syntax completely? why not just take the substring directly from input, just like it was specified? we have the start-end positions within the input, right?

**Comment by kitbellew** [comment]
> That should be done, but it seems we are getting a different dialect here, which is when we try to print it again.
> 
> https://github.com/scalameta/scalameta/blob/main/scalameta/trees/shared/src/main/scala/scala/meta/internal/prettyprinters/TreeSyntax.scala#L1283

yes, seems the dialect isn't passed correctly.

p.s. why isn't the code doing ``case Origin.Parsed(_, `dialect`, _) => ...`` directly, avoid another variable?

p.p.s. why isn't the code doing
```
case Origin.Parsed(input, `dialect`, pos) => new String(input.chars, pos.start, pos.end - pos.start)
```
directly, to avoid extra substrings and another lookup to `x.pos`?

**Comment by tgodzik** [comment]
> p.s. why isn't the code doing `` case Origin.Parsed(_, `dialect`, _) => ... `` directly, avoid another variable?
> 
> p.p.s. why isn't the code doing
> 
> ```
> case Origin.Parsed(input, `dialect`, pos) => new String(input.chars, pos.start, pos.end - pos.start)
> ```
> 
> directly, to avoid extra substrings and another lookup to `x.pos`?

I have no idea, that hasn't been touched for a while. 

> should the unimport _ be checked for allowStarWildcardImport?
Actually that still uses `_`, so we are good here.

Fun fact, when I add :
```
<<< ONLY expand import selectors #2535
rewrite.rules = [ExpandImportSelectors]
===
import foo.{ bar as baz, *}
>>>
import foo.{ bar as baz, *}

```
the code stops parsing :O

**Comment by kitbellew** [comment]
i think it might be pretty simple. if a dialect is not explicitly declared as implicit, some dialect is chosen from `dialects/package.scala` (and since all of them are implicit, i don't know which one will be selected).

there should be a way to say, i want the original syntax regardless of the dialect passed.

**Comment by tgodzik** [comment]
> there should be a way to say, i want the original syntax regardless of the dialect passed.

That would be making the original dialect implicit in the current scope I guess. We don't have any other way of specifying printing options.

**Comment by kubukoz** [comment]
Kudos @tgodzik 🙏
