### ISSUE TITLE
Parse error on valid code when rewrite.rules has RedundantBraces

### ISSUE THREAD

**Issue by bbarker** [scalameta/scalafmt#2539]
This template is a guideline, not a strict requirement.
- **Version**: 3.0.0-RC3
- **Integration**: IntelliJ
- **Configuration**:
```
version = 3.0.0-RC3

align.preset = more

maxColumn = 140

lineEndings = unix

trailingCommas = always

newlines.afterCurlyLambdaParams = squash

rewrite.rules = [
  RedundantParens
  SortImports
  SortModifiers
  PreferCurlyFors
  RedundantBraces
]

rewrite.redundantBraces.maxLines = 1
rewrite.redundantBraces.includeUnitMethods = false
rewrite.redundantBraces.stringInterpolation = true
rewrite.redundantBraces.methodBodies = true
rewrite.redundantBraces.ifElseExpressions = false

```

In particular, this seems to be related to `RedundantBraces` being in the `rewrite.rules`.

## Steps

Given code like this:
```scala
          .map(foo => {
            {
              logger.info(logMarker, s"SomeFoo: $foo")
              foo
            }
          }),
```
If I actually remove one pair of redundant braces, I get the error:

```
Compile / scalafmtCheck) key not found: 1981584224133584536:
```

## Expectation

I would like to not have a parse error on correct code.

## Workaround

I've found that by leaving in extra braces.

**Comment by kitbellew** [comment]
@bbarker can you please post two entire valid, parsable code snippets? i can't reproduce.

**Comment by kitbellew** [comment]
@bbarker we are about to release. can't fix the `key not found` error without reproducible examples.

**Comment by bbarker** [comment]
@kitbellew Sorry, I'll see if I can create something in the next few hours.

**Comment by bbarker** [comment]
@kitbellew 

Sorry for the delay, here's a fairly minimal example. It is likely possible to whittle it down quite a bit more:

```scala
object ScalaFmtTest {

  def badFun(): Unit =
    for {
      out <- bar.fold(
        EitherT.right[DomainError](baz(1))
      )(
        current => doSomething(current, 2)
          .map(mapVal => {
            logger.info(logMarker, s"A message: $mapVal")
            mapVal
          })
      )
    } yield out
}
```
