### ISSUE TITLE
Scala 3 end markers should be inserted at the appropriate place

### ISSUE THREAD

**Issue by djneades** [scalameta/scalafmt#2559]
- **Version**: 3.0.0-RC4
- **Integration**: sbt-scalafmt 2.4.2
- **Configuration**:
```
version = 3.0.0-RC4
maxColumn = 80

runner.dialect = scala3
rewrite.scala3.insertEndMarkerMinLines = 2
```

## Steps

Given code like this:
```scala
def f(s: String) =
  val t = "Bar"
  val u = "Baz"
  s"$t $u $s"

/** Some doc comment */
def g = f("Foo")
```

When I run scalafmt like this:

```bash
scalafmt
```

## Problem

Scalafmt formats code like this:
```scala
def f(s: String) =
  val t = "Bar"
  val u = "Baz"
  s"$t $u $s"

/** Some doc comment */
end f
def g = f("Foo")
```

## Expectation

I should like the formatted output to look like this:
```scala
def f(s: String) =
  val t = "Bar"
  val u = "Baz"
  s"$t $u $s"
end f

/** Some doc comment */
def g = f("Foo")
```

**Comment by kitbellew** [comment]
@tgodzik is this comment part of the previous `def` body?

**Comment by tgodzik** [comment]
I think that's the case. Let me see if that is fixable in scalameta.

**Comment by tgodzik** [comment]
Ok, so it looks like the positions are actually correct, but we are using `nextNonComment` which is skipping over the comment in question. Trying to fix it here: https://github.com/scalameta/scalafmt/pull/2568
