### ISSUE TITLE
Feature request: ability to control dangling parens for tuples separately from calls

### ISSUE THREAD

**Issue by djneades** [scalameta/scalafmt#2562]
- **Version**: 3.0.0-RC4
- **Integration**: sbt-scalafmt 2.4.2
- **Configuration**:
```
version = 3.0.0-RC4
maxColumn = 40

runner.dialect = scala3

danglingParentheses {
  defnSite = false
  callSite = false
}
```

## Steps

Given code like this:
```scala
def notAnInterestingFunction(s: String)
    : (String, String, String, String) =
  ("The quick brown fox",
   "jumped over the lazy",
   "dog.",
   "Maybe.")

val f =
  notAnInterestingFunction(
    "A string that will force wrapping.")
```

When I run scalafmt like this:

```bash
scalafmt
```

## Problem

Scalafmt formats code like this, where the tuple’s opening paren looks rather ugly and unblanced:
```scala
def notAnInterestingFunction(s: String)
    : (String, String, String, String) =
  (
    "The quick brown fox",
    "jumped over the lazy",
    "dog.",
    "Maybe.")

val f =
  notAnInterestingFunction(
    "A string that will force wrapping.")
```

## Expectation

I should like the formatted output to look like this:
```scala
def notAnInterestingFunction(s: String)
    : (String, String, String, String) =
  ("The quick brown fox",
   "jumped over the lazy",
   "dog.",
   "Maybe.")

val f =
  notAnInterestingFunction(
    "A string that will force wrapping.")
```

Or, perhaps, like this, with the tuple being formatted as it would be currently with `danglingParenthesis.callSite = true`, but the method call still being formatted as with `danglingParenthesis.callSite = false`:

```scala
def notAnInterestingFunction(s: String)
    : (String, String, String, String) =
  (
    "The quick brown fox",
    "jumped over the lazy",
    "dog.",
    "Maybe."
  )

val f =
  notAnInterestingFunction(
    "A string that will force wrapping.")
```

**Comment by kitbellew** [comment]
@djneades have you tried `align.openParenCallSite`?

**Comment by djneades** [comment]
@kitbellew The problem with `align.openParenCallSite` is that affects normal method calls as well as tuples. I’d still like my method calls to look like this:

```scala
radialLine(
   s / 60.0,
   tickAndHandColour,
   width,
   length,
   -radius + padding + length)
```

and not like this:

```scala
radialLine(s / 60.0,
           tickAndHandColour,
           width,
           length,
           -radius + padding + length)
```

That option also clashes with the rest of my configuration, with Scalafmt giving this error:

```
can't use: [
        newlines.source=fold and [optIn.configStyleArguments && align.openParenCallSite]
]
```

**Comment by kitbellew** [comment]
@djneades align kinda clashes with config style, try disabling the latter.

still, what's the request? having a separate align for tuples only?

**Comment by djneades** [comment]
@kitbellew Yes, precisely – I’d like to be able to control the paren/alignment style for tuples separately from other call sites.

**Comment by kitbellew** [comment]
@djneades are you ok with this:
```
type Tuple =
  [TheOnlyTypeInTheTuple] =>> (TheOnlyTypeInTheTuple,
                               TheOnlyTypeInTheTuple
                              )

```

**Comment by djneades** [comment]
@kitbellew I would be if it didn’t have the dangling closing paren. So:

```scala
type Tuple =
  [TheOnlyTypeInTheTuple] =>> (TheOnlyTypeInTheTuple,
                               TheOnlyTypeInTheTuple)
```
