### ISSUE TITLE
ExpandImportSelectors rewrite adding braces on imports with special characters

### ISSUE THREAD

**Issue by perrin4869** [scalameta/scalafmt#2571]
This template is a guideline, not a strict requirement.
- **Integration**: sbt
- **Configuration**:
```
version = 2.7.5

rewrite.rules = [ExpandImportSelectors]
```

## Steps

Given code like this:
```scala
import zio.prelude.<=>
```

When I run scalafmt like this:

```bash
sbt scalafmt
```

## Problem

Scalafmt formats code like this:
```scala
import zio.prelude.{<=>}
```

## Expectation

I would like the formatted output to look like this:
```scala
import zio.prelude.<=>
```

I looked for possible configuration options to change this behavior but came up empty. This conflicts with the way `scalafix-organize-imports` formats the code, it would be good to align the behavior with some config option. Scalafmt is very hand in that it works fast on-save, so I would not want to disable this feature ideally.

**Comment by kitbellew** [comment]
@tgodzik remind me, why did we look for `=>` and not `Token.RightArrow`?

**Comment by tgodzik** [comment]
Not sure, but since it's in 2.7.5, it's before any Scale 3 work, so maybe that's just a bug?
