### ISSUE TITLE
Feature Request: Allow some additional settings for control sites

### ISSUE THREAD

**Issue by ekrich** [scalameta/scalafmt#2573]
The following is our proposed new config for the Scala Native project. We are super excited because we were able to remove most of the configuration items and create a format more aligned with Scala.js and take advantage of all the new features like number formatting. We share code back and forth so having the two repositories similar really helps.

```properties
version = 3.0.0-RC3
docstrings.style = AsteriskSpace
project.git = true
project.excludePaths = [
  "glob:**/scalalib/**"
]
# this creates less of a diff but is not default
# but aligned with Scala.js syntax
newlines.beforeCurlyLambdaParams = multilineWithCaseOnly

# This is not default but avoid ctrl site like if from wrapping
#danglingParentheses.ctrlSite = false
```

## Background

We are attempting to upgrade from version `2.4.2` as shown in this PR: https://github.com/scala-native/scala-native/pull/2315

The first comment includes a link to the unified diff at the bottom. The one thing that stood out to the reviewer was the change in the format of `if` statements when the condition was too long as shown in the following:

```diff
@@ -791,3 +845,5 @@
     }
-    if (uri.scheme == null && scheme != null || uri.scheme != null && scheme == null) {
+    if (
+      uri.scheme == null && scheme != null || uri.scheme != null && scheme == null
+    ) {
       return false
```
We are very interested in maintaining a format that is similar to a Scala 3 optional braces format. Given that the following code has been around for all C, Java, and Scala for a long time, we would like to have something familiar that has the least impact on current code bases.

Using the code from above we would like to see something like the following if the condition is too long:
```scala
if (uri.scheme == null && scheme != null || 
    uri.scheme != null && scheme == null) {
  return false
}
```

If I add `danglingParentheses.ctrlSite = false` and run scalafmt I can get a format like the following:

```scala
if (host.indexOf(':') != -1 && host.indexOf(']') == -1 &&
  host.indexOf('[') == -1) {
  hostVar = "[" + host + "]"
}
```
The above makes it hard to distinguish the condition continuation from the body of the `if` or `while`.

## Proposal

Control sites with wrapped conditions indent 4 spaces by default.

Here are some examples:
```scala
if (host.indexOf(':') != -1 && host.indexOf(']') == -1 &&
    host.indexOf('[') == -1) {
  hostVar = "[" + host + "]"
}

if host.indexOf(':') != -1 && host.indexOf(']') == -1 &&
    host.indexOf('[') == -1 then
  hostVar = "[" + host + "]"

if host.indexOf(':') != -1 && host.indexOf(']') == -1 &&
    host.indexOf('[') == -1
then
  hostVar = "[" + host + "]"

```
I think this should be the default without the `danglingParentheses.ctrlSite = false` setting as it is the most like current code bases and what people are used to seeing.

Some other options that could be configured if needed?

```scala
if (host.indexOf(':') != -1 && host.indexOf(']') == -1 &&
    host.indexOf('[') == -1
) {
  hostVar = "[" + host + "]"
}

if (
  host.indexOf(':') != -1 && host.indexOf(']') == -1 &&
    host.indexOf('[') == -1
) {
  hostVar = "[" + host + "]"
}
// both of the above would work with 2 space indentation on the condition continuation as well.
```

**Comment by kitbellew** [comment]
@olafurpg what do you think?

**Comment by kitbellew** [comment]
> Control sites with wrapped conditions indent 4 spaces by default.

so the ask is to add an indent setting specifically for control sites?

> I think this should be the default without the `danglingParentheses.ctrlSite = false` setting as it is the most like current code bases and what people are used to seeing.

we try to avoid changing defaults so that those who have been using the formatter for a while will not see too many changes. so let's for now limit this conversation to adding a new setting that can be customized for your case.

**Comment by ekrich** [comment]
I think this especially important because we are in the RC cycle.

**Comment by ekrich** [comment]
Note: the normal wrap is 2 spaces.
```scala
-    if (writing && options.contains(DSYNC) && !options
-          .contains(SYNC)) {
+    if (
+      writing && options.contains(DSYNC) && !options
+        .contains(SYNC)
+    ) {
```

**Comment by olafurpg** [comment]
@kitbellew no comments or objections here. The if syntax in mention was added recently and I'm not up-to-date on how to get the previous output. I like the new syntax but it makes sense that some projects like Scala Native may prefer the old one.

**Comment by ekrich** [comment]
@olafurpg So your idea is to always wrap with too long conditions and then put the `then` justified with the `if`? If so I think that is good for the default. Then trailing `then` or ident like here can be options.

This can at least be a gateway drug for future formats.
