### ISSUE TITLE
Scalafmt 2.4.2 failing on Scala 2 macro

### ISSUE THREAD

**Issue by cchantep** [scalameta/scalafmt#2587]
```
error: illegal start of statement
[error]     macro macroImpl
```

**Comment by kitbellew** [comment]
can you please check v3.0.0-RC4?

**Comment by kitbellew** [comment]
no config, no code, old version.

**Comment by cchantep** [comment]
Guys, seriously ... 2.4.2 is the latest. And there is no valid reason to fail on Scala 2 macro, whatever is the fmt config.

**Comment by kitbellew** [comment]
2.7.5 is the latest, if you don't count 3.0.0-rc5.

and we have plenty of code with macros, so, seriously, if you want this looked at, please submit the exact config and the exact code which fails.
