### ISSUE TITLE
Some Match types scenarios in Scala 3 are reported as formatting errors

### ISSUE THREAD

**Issue by calvinlfer** [scalameta/scalafmt#2595]
Hello, there seems to a formatting error issue with some Match types in Scala 3

- **Version**: 3.0.0-RC5
- **Integration**: IntelliJ
- **Configuration**:
```
version=3.0.0-RC5
runner.dialect = scala3
align.preset = more
maxColumn = 120
```

## Problem

Scalafmt reports the following code as a parse error:
> outdent expected but case found
```scala
object match_types:
  def theSameAs[A, B](using ev: A =:= B) = ()

  type Combine[Left, Right] = Left match
    case Unit => Right

    case ? => // ? is wildcard
      Right match
        case Unit => Left
        case ?    => (Left, Right)
```

## Expectation

This should not be an error as it compiles fine.

Thank you for all your work 🙏🏽

**Comment by kitbellew** [comment]
@tgodzik parser?

**Comment by tgodzik** [comment]
Most likely 😬, I can take a look at it on Wednesday.

**Comment by tgodzik** [comment]
Fixing it here https://github.com/scalameta/scalameta/pull/2383

**Comment by calvinlfer** [comment]
Closed by https://github.com/scalameta/scalameta/pull/2383
