### ISSUE TITLE
Scalafmt GraalVM prebuilt images RC2÷RC5 not working

### ISSUE THREAD

**Issue by sbushmanov** [scalameta/scalafmt#2616]
- **Version**: scalafmt 3.0.0-RC2÷RC5
- **Integration**: Bash Cli (Ubuntu)

Given code like this:
```bash
> scalafmt-native del.scala
```
i'm getting errors like:
```
Exception in thread "main" java.nio.file.NoSuchFileException: /home/runner/.../del.scala
```
None, of the downloaded `scalafmt-native 3.0.0-RC2÷RC5` native images work.

The last working image though is `scalafmt-native 3.0.0-RC1`

**Comment by kitbellew** [comment]
@sbushmanov 

1. what is your `pwd` when you run it?
2. what is the full path in the exception (what's behind those `...`)?
