### ISSUE TITLE
Feature request: Preset that leaves 0 choices to the programmers

### ISSUE THREAD

**Issue by davidpomerenke** [scalameta/scalafmt#2617]
It would be nice to have a preset that ignores all the decisions that the programmers have made regarding line breaks etc., hence leaving no decisions to the programmers and formatting the code deterministically. This, in my opinion, makes it mentally much easier to focus on the code itself. For Python code formatting, [`black`](https://github.com/psf/black) pursues this ideal. the [Elm formatter](https://github.com/avh4/elm-format) also does so. Citing from `black`s self-description, to explain better what I mean:

> Black is the uncompromising Python code formatter. By using it, you agree to cede control over minutiae of hand-formatting. In return, Black gives you speed, determinism, and freedom from pycodestyle nagging about formatting. You will save time and mental energy for more important matters.

(Note: By "preset", I mean a single top-level option [like these](https://scalameta.org/scalafmt/docs/configuration.html#top-level-presets). I do not mean a default setting that I want to force upon other people.)

So, when I type, for example, this:

```scala
val foo = 4
val bar =
  5
```

then `scalafmt` with the preset that I postulate about would format it as: 

```scala
val foo = 4
val bar = 5
```

Alternatively, `scalafmt` with the preset that I postulate about would format it as: 

```scala
val foo = 
  4
val bar = 
  5
```

-> I really don't care _how_ it is formatted, I only care that it is always formatted the same way, and that I do not need to take care of achieving consistency myself. 

I suspect that this behaviour can already be achieved by configuring some of the existing options. But there's quite a lot of configuration options and it would be a lot of duplicated work if every programmer with the described ideal needed to go through all options on their own, figuring out which ones are suitable. That's why a preset would be nice. Moreover, you as creators and contributors to `scalafmt` probably know better which options could be suitable for such a preset than I as a newbie could know. That's why I'm just putting this up for a discussion, rather than making more concrete suggestions or a pull request.

Selecting the configurations for such a preset may well cause some debate about which specific configurations are best. But, from my perspective, it would be nice to have _any_ roughly reasonable selection of configurations that achieve the described determinism. 

What do you think?

**Comment by tgodzik** [comment]
Thanks for reporting! There is quite a few style guides in the Scala community, but I do agree we could have those as presets. 

Maybe we could at least add https://docs.scala-lang.org/style/ and encourage people to use it? There is no way however other than having the config in the repository to enforce the style on other users, but I think an official one could be highly used by people.

@kitbellew does `default` already follow a style guide ?

**Comment by kitbellew** [comment]
> Maybe we could at least add https://docs.scala-lang.org/style/ and encourage people to use it? There is no way however other than having the config in the repository to enforce the style on other users, but I think an official one could be highly used by people.

frankly, i doubt it. the issue is that the style mandates _some_ things but not many. it is not as prescriptive and all-encompassing as what the requester is looking for.

> @kitbellew does `default` already follow a style guide ?

I think it might be pretty close but there have been issues submitted to make some style-mandated requirements available, and we implemented them via parameters.

i would like to understand how other solutions for the proposed top-level fixed presets fare. i really don't think we should get into a business of adjusting them for individual needs, or creating additional fixed presets if the idea becomes popular.

**Comment by kitbellew** [comment]
> (Note: By "preset", I mean a single top-level option [like these](https://scalameta.org/scalafmt/docs/configuration.html#top-level-presets). I do not mean a default setting that I want to force upon other people.)

top-level presets are the initial state, and the configuration can be further modified.

> 
> So, when I type, for example, this:
> 
> ```scala
> val foo = 4
> val bar =
>   5
> ```
> 
> then `scalafmt` with the preset that I postulate about would format it as:
> 
> ```scala
> val foo = 4
> val bar = 5
> ```

use `newlines.source = fold`.

> Alternatively, `scalafmt` with the preset that I postulate about would format it as:
> 
> ```scala
> val foo = 
>   4
> val bar = 
>   5
> ```

use `newlines.source = unfold`.

> What do you think?

creating a completely fixed, immutable configuration profile, ignoring absolutely all other options in `.scalafmt.conf`, requires a panel of industry experts, even an rfc or pip or sip of sorts. if some widely recognized external body would like to take this on, and the end result can be accomplished by this formatter, we can probably create a way to do it.
