### ISSUE TITLE
Wrong error message with invalid config

### ISSUE THREAD

**Issue by tgodzik** [scalameta/scalafmt#2631]
This template is a guideline, not a strict requirement.
- **Version**: 3.0.0-RC6
- **Integration**: Metals
- **Configuration**:
```
version = 3.0.0-RC6
align=does-not-exist
```

## Steps

When run currently:
```bash
Invalid config: <input>:3:0 error: Type mismatch;
  found    : String (value: "does-not-exist")
  expected : Object
    "align" : "does-not-exist",
^
: /home/tgodzik/Documents/metals/.scalafmt.conf
```

but previously it would be:

```bash
Invalid config: error: Type mismatch;
  found    : String (value: "does-not-exist")
  expected : Object
    "align" : "does-not-exist",
^
: /home/tgodzik/Documents/metals/.scalafmt.conf
```

## Problem

Not sure where `<input>:3:0` comes from and can't reproduce it in tests.

## Expectation

`<input>:3:0` would not be in the error message

## Workaround

Ignore the changed message

## Notes

Might be caused by the recent changes to metaconfig?

This popped up in Metals tests: https://github.com/scalameta/metals/pull/2914

This is a very minor thing, so it's not really blocking `3.0.0`, but might be good to fix and I can figure out where it's happening.

**Comment by tgodzik** [comment]
Actually, this fails in DynamicSuite:
```scala

  check("invalid-type") { f =>
    f.setConfig(
      s"""|version=3.0.0-RC6
          |align=does-not-exist 
          |""".stripMargin
    )
    val thrown = f.assertThrows[ScalafmtDynamicError.ConfigParseError]()
    println(thrown.getMessage())
    pprint.log(thrown.configPath)
    assert(thrown.getMessage.contains("Invalid config: Invalid field: max."))
  }
```

So it seems it's something in metaconfig.

**Comment by tgodzik** [comment]
We actually merge the pr in metals and the message disappeared weirdly enough 🤔

**Comment by ckipp01** [comment]
> We actually merged the pr in metals and the message disappeared weirdly enough 🤔

We only merged in for usage in our own codebase though, we didn't actually merge it in to be used when users are using format. This is still showing up here https://github.com/scalameta/metals/pull/2969

**Comment by tgodzik** [comment]
Ach, makes sense. I had only the mobile view, so didn't see the whole picture.
