### ISSUE TITLE
Scalafmt 3.0.0-RC6 with Scala3 dialect has issues with implicit inline def

### ISSUE THREAD

**Issue by mdedetrich** [scalameta/scalafmt#2640]
This template is a guideline, not a strict requirement.
- **Version**: 3.0.0-RC6
- **Integration**: sbt-scalafmt
- **Configuration**:
```
runner.dialect = scala3
version=3.0.0-RC6
maxColumn=120
project.git = true
```

## Steps

Given code like this:
```scala
implicit inline def qm: QueryMeta[PersonName, String] = { //hellooo
  queryMeta[PersonName, String](
    quote {
      (q: Query[PersonName]) => q.map(p => p.name)
    }
  )((name: String) => PersonName(name))
}
```

When I run scalafmt like this:

```bash
sbt test:scalafmt
```

## Problem

Scalafmt format fails with the following error
```
[error] /home/mdedetrich/github/protoquill/quill-sql/src/test/scala/io/getquill/QueryMetaTest.scala:66: error: => expected but def found
[error]       implicit inline def qm: QueryMeta[PersonName, String] = { //hellooo
[error]                       ^: /home/mdedetrich/github/protoquill/quill-sql/src/test/scala/io/getquill/QueryMetaTest.scala
```

## Expectation

scalafmt to format code correctly without any errors

## Workaround

None apart from deleting the code

## Notes

Here is the original code https://github.com/getquill/protoquill/blob/d095b54d4e267ed0f2a1e6a60b6f0aa16b122d99/quill-sql/src/test/scala/io/getquill/QueryMetaTest.scala#L66-L72

This seems to be just a case where the scala3 dialect isn't aware of a new case that is present in Scala3, it may also be an issue with scalameta not being up to date enough to handle this case?

**Comment by tgodzik** [comment]
Thanks for reporting! This is a parser issue, fixing it here https://github.com/scalameta/scalameta/pull/2428

**Comment by mdedetrich** [comment]
Awesome thanks! Would this be released in an upcoming `RC7`?

**Comment by tgodzik** [comment]
Most likely, next will be `3.0.0`, I think we fixed most of the bigger bugs already and any outliers can be fixed later.

**Comment by mdedetrich** [comment]
Cool, thanks for pushing this through do quickly

**Comment by kitbellew** [comment]
@mdedetrich surprisingly, i cannot reproduce this problem, hence i can't test whether the new scalameta release fixed it. cc @tgodzik

**Comment by mdedetrich** [comment]
@kitbellew Can you reproduce it by cloning the repository mentioned in the issue and running Scalafmt 3.0.0 RC-6 on it?

**Comment by kitbellew** [comment]
> @kitbellew Can you reproduce it by cloning the repository mentioned in the issue and running Scalafmt 3.0.0 RC-6 on it?

without `"static meta" - {`, it worked fine.
