### ISSUE TITLE
Ability for individuals to have their own personal formatting settings separate from project settings.

### ISSUE THREAD

**Issue by ckipp01** [scalameta/scalafmt#2665]
## Explanation of feature request

Recently in a conversation with @jastice on [Tooling Talks](https://youtu.be/5ZebGDMpPgs) this idea was randomly floated, and thinking about it a bit more today, I figured why not start a conversation about it. As everyone is aware, some have pretty strong formatting opinions, when others may just want their team to be consistent. I've personally found that the teams I've been a part of are a mix of this. At the end of the day we spend some time all agreeing on what the desired `.scalafmt` should be, set it, and then deal with it. I personally prefer narrow columns, where the team I work on prefers wide, 130. So we agree on 100, and then no one is fully happy. Pick any number of settings and you have this.

I've started to wonder more recently why we are in this situation, and why with the modern technology we have, why we cannot all just have what we want. I get my config, Landon gets her config, Talia gets their config, and then there is a base config stored in the repo that controls how your source is formatted when you check it in.

### How could this work?

I'm not really sure how this would work, but the first thing that comes to mind is having some sort of global config, not that unlike your git config. After I clone a project or when I open it in my editor, the code is formatted in my preferred way based off my global config. When I check that code in, it's back to the base formatted way that is defined in the repo. I push my changes, and no one ever needs to know that the entire time I was coding locally, it was formatted completely differently.

Maybe this could be part of Scalafmt where a command is ran and it's done for you entire project, and then done again before you commit. That might be expensive on big projects though, and often you only touch very small parts of your project. So then maybe this should instead happen on a per-file basis with some type of editor integration? I'm not sure what would be best.

Either way, I'd love to have your thoughts on this. I'd be great to change the way we think about "code formatting" and lift the limitation of _everyone_ having to agree on how we format our code, and instead have our own local environments control how our code looks. I'm not really aware of any ecosystem that has this at the moment, by maybe the Scala ecosystem can lead this.

**Comment by jastice** [comment]
Ideally it would just be the editor that renders the code in the preferred format, while the underlying code itself is represented in whatever standard. This is sort of what you get in Unison (where you always check in an AST) and MPS (where you edit the AST directly). Considering how to bring this into an existing text-based toolchain, either we'd need a formatter that works directly on the text buffer, while the editor sends a file save through a different configuration of the formatter. Not sure how practical this would be, I think the connection with the underlying text file is pretty close in IntelliJ at least.

**Comment by tgodzik** [comment]
I think this can be done in two ways:
1. Have the editor support it and present the user formatted code to the user, but keep the globally formatted file underneath. 
2. Add hooks to git that would change the code in correct places, when checking out or syncing changes.

As far as I know no editor can currently support 1, since what you see is what you get underneath and any kind of changes can cause issues (`do you want to override the file system changes?` etc.) We could have a virtual document for each actual file, but that on the other hand can create a disconnect between the editor and the actual code the user is working on.

As for 2 I think it can be resource intensive and hard to coordinate it. You would also see lots of unrelated changes or broken git history if you for example try to have an alternative main branch. 

I would say that there is no sensible way to do it currently as far as I know and honestly it might cause more issues than what it's worth. Of course, this is just totally my opinion. It's just formatting and I've never shared people's need to have everything lined up to their tastes. I kind of accept what is available and try to not waste my energy on it.

**Comment by kitbellew** [comment]
the simple problem is, in general, formatting with config A, then config B, then again config A will not necessarily result in the same code as what you started with. so even if you make absolutely no changes, you will have changes.

however, it's possible that in the specific case of `newlines.source = fold/unfold` formatter will have that property (as the desire was to format ignoring source breaks).

one can always write a special wrapper for `git` which handles `git checkout` and `git push`, and that's where you can substitute whatever config you want when checking out, and then the default one when pushing. or a hook, like tomasz mentioned.

**Comment by nafg** [comment]
Let's just store code in TASTY in an sqlite file similar to Unison ;)

**Comment by kitbellew** [comment]
@unkarjedy any thoughts on this for intellij specifically?

**Comment by ckipp01** [comment]
btw @kitbellew I threw this up here just to sort of see if there were any crazy ideas out there. It's not something I feel super strongly about at the moment. So if there is no actionable output from this, don't hesitate to close.

**Comment by unkarjedy** [comment]
> I'm not really sure how this would work, but the first thing that comes to mind is having some sort of global config, not that unlike your git config. After I clone a project or when I open it in my editor, the code is formatted in my preferred way based off my global config. When I check that code in, it's back to the base formatted way that is defined in the repo. I push my changes, and no one ever needs to know that the entire time I was coding locally, it was formatted completely differently.

> Add hooks to git that would change the code in correct places, when checking out or syncing changes.

Modifying the actual code would make it a nightmare to work with the diff in the local changes.
Thats' even with whitespaces modifications (new lines, indentations, alignments)
Even though diff viewers can ignore whitespace changes, quite frequently you do not want to ignore them 
(especially if the language uses indentation-based syntax :) )
And there are also rewriting rules...

IMO, ideally, that should be some editor feature.

>any thoughts on this for IntelliJ specifically?

In theory, this feature could be implemented for the Reader mode (e.g. when you read some code from some library jars).
We could also consider enabling the Reader mode for the unmodified project files.
https://www.jetbrains.com/help/idea/reader-mode.html
The big plus of this approach is that the formatter could be any: built-in IntelliJ or Scalafmt.

But I am not entirely sure how that feature would look like when you edit some code.
Even from the user perspective.
I predict lots of various glitches in the editor while you edit the code, especially when you have some broken code (when you are in process of typing stuff).

It could be more or less doable and usable for some very small subset of formatting rules, like indentations sizes, but I don't think that it would be viable in the general case.

**Comment by unkarjedy** [comment]
Anyway, I think that in an editable file scenario, the formatter would need to be closely bound to the underlying AST code representation in the editor (which is bound to the original code ranges).

**Comment by kitbellew** [comment]
> btw @kitbellew I threw this up here just to sort of see if there were any crazy ideas out there. It's not something I feel super strongly about at the moment. So if there is no actionable output from this, don't hesitate to close.

roger!
