### ISSUE TITLE
Import `as` failing `scalafmt check`

### ISSUE THREAD

**Issue by therockstorm** [scalameta/scalafmt#2673]
With `scalafix` v3.0.0-RC6, Scala v2.13.6 and the `-Xsource:3` compiler flag, IntelliJ's (v2021.2) Scala plugin (v2021.2.15) converts imports like this,

```
import com.example.{Value => MyValue, _}
```

To this

```
import com.example.{Value as MyValue, _}
```

Which causes this error when running `scalafmtCheck`,

```
[error] /some/path/MyClass.scala:5: error: } expected but identifier found
[error] import com.example.{Value as MyValue, _}
```

The workaround is to revert these changes.

**Comment by dos65** [comment]
@therockstorm you need to add `runner.dialect = Scala213Source3` to your `.scalafmt.conf` to enable this syntax.
