### ISSUE TITLE
error: found option 'imports' which wasn't expected, or isn't valid in this context

### ISSUE THREAD

**Issue by unkarjedy** [scalameta/scalafmt#2674]
- **Version**: 3.0.0-RC6
- **Integration**: IntelliJ
- **Configuration**:
Taken from the docs:
https://scalameta.org/scalafmt/docs/configuration.html#imports-sort--scalastyle

```
version = 3.0.0-RC6
maxColumn = 50
rewrite.rules = [Imports]
rewrite.imports.sort = scalastyle
rewrite.imports.groups = [["foo\\..*"]]
```

## Steps

1. try to format the file
2. get the error:
```
<input>:7:0 error: found option 'imports' which wasn't expected, or isn't valid in this context.
"imports" : {
^
```

**Comment by kitbellew** [comment]
@unkarjedy will be in rc7, in a couple of days.

**Comment by tgodzik** [comment]
Should we finally do 3.0.0?

**Comment by kitbellew** [comment]
> Should we finally do 3.0.0?

one last pr for your review, and we could.

**Comment by kitbellew** [comment]
for now, i released rc7.
