### ISSUE TITLE
formatting fails for Scala 2 code with `-Xsource:3` flag enabled when using Scala 2.13.6 

### ISSUE THREAD

**Issue by mr-git** [scalameta/scalafmt#2676]
- **Version**: 2.7.5
- **Integration**: IntelliJ
- **Configuration**:
```
version = 2.7.5

maxColumn = 120

preset = default
align.preset = none

trailingCommas = always

continuationIndent {
  callSite = 2
  defnSite = 2
}

rewrite.rules = [
  RedundantBraces, RedundantParens, SortModifiers, prefercurlyfors
]
```

## Steps

Given code like this:
```scala
import my.company.MyClass as YourClass
```
OR
```scala
import my.company.{MyClass as YourClass}
```

When I run scalafmt like this:

```bash
sbt scalafmt
```

## Problem

Scalafmt fails to format code with error like:
```scala
[error] /.../my/company/Clazz.scala:10: error: ; expected but identifier found
[error] import my.company.MyClass as YourClass
[error]                           ^:
```
OR
```scala
[error] /.../my/company/Clazz.scala:10: error: } expected but identifier found
[error] import my.company.{MyClass as YourClass}
[error]                            ^:
```

## Expectation

There is no error and Scala 3 syntax is supported for Scala 2.13.6 code

## Workaround

Use "legacy" approach, like:
```scala
import my.company.{MyClass => YourClass}
```

**Comment by kitbellew** [comment]
read documentation

**Comment by mr-git** [comment]
@kitbellew , please be more specific, the documentation for scalafmt is really big and hard to find some special cases.

I tried `runner.dialect = scala3` (from https://scalameta.org/scalafmt/docs/configuration.html#scala-3), but then I get errors like:
```text
[error] (logic / Compile / scalafmt) Invalid config: Unknown input 'scala3'. Expected one of: scala212, sbt1, paradise211, scala211, paradise212, default, dotty, scala213, sbt0137: /.../.scalafmt.conf
```

With `runner.dialect = dotty` same error as before.

Maybe support for Scala 3 syntax is included only in 3.x RC builds, yet?

**Comment by kitbellew** [comment]
> I tried `runner.dialect = scala3` (from https://scalameta.org/scalafmt/docs/configuration.html#scala-3), but then I get errors like:

Correct documentation section, incorrect parameter value.

> Maybe support for Scala 3 syntax is included only in 3.x RC builds, yet?

That's correct.

**Comment by mr-git** [comment]
so conclusion:
* have to use `runner.dialect = Scala213Source3`
* have to be on 3.x version

And, there are no plans to get that in place as backport to 2.x version, because 3.x will get out `soon`, correct? :)

**Comment by kitbellew** [comment]
> And, there are no plans to get that in place as backport to 2.x version, because 3.x will get out `soon`, correct? :)

`Scala213Source3` is not compatible with `Scala213`, and we will not make it default.
