### ISSUE TITLE
Scalafmt 3.0.0 fails on Scala3 code starting with case statement

### ISSUE THREAD

**Issue by mdedetrich** [scalameta/scalafmt#2687]
This template is a guideline, not a strict requirement.
- **Version**: 3.0.0
- **Integration**: scalafmt-native
- **Configuration**:
```
runner.dialect = scala3
version=3.0.0
maxColumn=120
project.git = true
```

## Steps

Given code like this:
```scala
  given liftPropertyAlias: NiceLiftable[PropertyAlias] with {
    def lift = case PropertyAlias(a, b) => '{ PropertyAlias(${ a.expr }, ${ b.expr }) }
  }
```

When I run scalafmt like this:

```bash
scalafmt
```

## Problem

Scalafmt errors out with the following

```
/home/mdedetrich/github/protoquill/quill-sql/src/main/scala/io/getquill/parser/Lifter.scala:110: error: illegal start of simple expression
    def lift = case PropertyAlias(a, b) => '{ PropertyAlias(${ a.expr }, ${ b.expr }) }
```

## Expectation

I would like for scalafmt to not error out

## Workaround

None as far as I can tell, not even using `// format: off` and `// format: on` seems to work

## Notes

Original code where it fails https://github.com/getquill/protoquill/blob/master/quill-sql/src/main/scala/io/getquill/parser/Lifter.scala#L106-L109

**Comment by tgodzik** [comment]
Thanks for reporting! This is most likely an issue with the parser. You can change it to:
```
def lift = 
  case PropertyAlias(a, b) => '{ PropertyAlias(${ a.expr }, ${ b.expr }) }
```
we will fix it in the parser and update it later on.

**Comment by tgodzik** [comment]
@mdedetrich Is it even a correct syntax though? Can `case` be after `=` without any indentation?

It does fail for me for a simple example:
```
[error] -- [E018] Syntax Error: /home/tgodzik/Documents/workspaces/dotty-example-project/src/main/scala/Main.scala:15:12 
[error] 15 |    val a = case _: String => println("hello!")
[error]    |            ^^^^
[error]    |            expression expected but case found
[error] one error found
[error] one error found
[error] (Compile / compileIncremental) Compilation failed
[error] Total time: 9 s, completed Aug 19, 2021 11:27:54 AM
```

**Comment by mdedetrich** [comment]
So this project is using dotty nightly rather than released Scala3. What's curious to me is why the `// format: off` doesn't work

**Comment by tgodzik** [comment]
> So this project is using dotty nightly rather than released Scala3 which my explain the difference. What's curious to me is why the `// format: off` doesn't work

We still need to parse the file even with the format:off.

**Comment by mdedetrich** [comment]
So interestingly this problem doesn't occur when you format the linked project at first, scalafmt won't complain and formats the project. However if you scalafmt the second time then it fails.

So I think the issue here is that scalafmt is producing incorrect code for this case?

**Comment by tgodzik** [comment]
Och, does it move the case to the previous line if there is only one case in a partial function?

**Comment by mdedetrich** [comment]
So this is before scalafmt

```scala
  given liftPropertyAlias : NiceLiftable[PropertyAlias] with {
    def lift =
      case PropertyAlias(a, b) => '{ PropertyAlias(${a.expr}, ${b.expr}) }
  }
```

and this is after a scalafmt

```scala
  given liftPropertyAlias: NiceLiftable[PropertyAlias] with {
    def lift = case PropertyAlias(a, b) => '{ PropertyAlias(${ a.expr }, ${ b.expr }) }
  }
  ```
  
  In general you can view the diff at https://github.com/getquill/protoquill/pull/17/files

**Comment by tgodzik** [comment]
You can always open an issue to discuss it, but it might indeed be too late.

**Comment by mdedetrich** [comment]
Yeah I will make an issue  since there is no reason not to but glad that we found the root cause. Looks like an exception case has to be made in scalafmt with the `scala3` dialect.

**Comment by kitbellew** [comment]
@mdedetrich @tgodzik is syntax without the newline valid or not? i tried to follow this and the other discussion and couldn't come to a conclusion.

changing the formatter not to remove the newline is easy. is there need to change the parser to support the single line version? what's the subtle difference you were referring to (two different meanings or just one valid and other invalid)?

**Comment by tgodzik** [comment]
@kitbellew syntax without the newline is invalid, we need to fix it in Scalafmt I think.

**Comment by mdedetrich** [comment]
> changing the formatter not to remove the newline is easy. is there need to change the parser to support the single line version? what's the subtle difference you were referring to (two different meanings or just one valid and other invalid)?

@kitbellew In summary yes but you have it the wrong way around, the version **without** the newline is invalid Scala3 code where as the version **with** a new line is valid Scala3 code. You need to prevent `scalafmt` from applying indentation rules (ergo creating a new line) in this specific case. To put it differently

```scala
def lift =
 case PropertyAlias(a, b) => '{ PropertyAlias(${a.expr}, ${b.expr}) }
```
 
vs

```scala
def lift = case PropertyAlias(a, b) => '{ PropertyAlias(${ a.expr }, ${ b.expr }) }
```

Are saying completely different things in Scala3. The former is saying "I want to assign lift to an anonymous partial function that has a single case statement" (which is valid) where as the latter is saying "I want to assign lift to a single case statement" (which of course doesn't make sense hence why its not compiling).

That single new line is changing the meaning of the program which is a new feature of Scala3 that it shares with Ruby/Python where indentation/new lines can have these significant changes. Having that new lines is basically the same as putting `{` and `}` around the case statement for Scala2, i.e.

```scala
def lift = {
  case PropertyAlias(a, b) => '{ PropertyAlias(${a.expr}, ${b.expr}) }
}
 ```
 
I am personally not a fun of this subtle distinction that has such a drastic effect but unless you can convince the guys at https://github.com/lampepfl/dotty-feature-requests/issues/235 to change the behavior this exception needs to be added to scalafmt otherwise formatting Scala3 codebases can produce invalid Scala3 code.

**Comment by kitbellew** [comment]
> > changing the formatter not to remove the newline is easy. is there need to change the parser to support the single line version? what's the subtle difference you were referring to (two different meanings or just one valid and other invalid)?
> 
> @kitbellew In summary yes but you have it the wrong way around, the version **without** the newline is invalid Scala3 code where as the version **with** a new line is valid Scala3 code.

i don't think i have it the wrong way around. i _understood_ that you want the version with the newline (which is why i said it's easy _not to remove it_).

all i asked is whether the version without the newline is valid; @tgodzik says it isn't, and you seem to be saying that it is but with a different meaning:

> That single new line is changing the meaning of the program ...
> I am personally not a fun of this subtle distinction that has such a drastic effect ...

if the version without the newline is invalid, then perhaps there's no confusion, there's no subtle distinction (valid vs invalid is pretty significant). seems like typical optional-braces case.

**Comment by mdedetrich** [comment]
> if the version without the newline is invalid, then perhaps there's no confusion, there's no subtle distinction (valid vs invalid is pretty significant). seems like typical optional-braces case.

Agreed, it seems we are saying the same thing in a different way
