### ISSUE TITLE
Scalafmt 3.0.0 applies new Scala 3 syntax for build.sbt and meta-project files

### ISSUE THREAD

**Issue by RomanLebid** [scalameta/scalafmt#2688]
- **Version**: 3.0.0
- **Integration**:  scalafmt-native
- **Configuration**:
```
version = 3.0.0
runner.dialect = scala3
rewrite.scala3.convertToNewSyntax = true
rewrite.scala3.removeOptionalBraces = yes
```

## Steps

Given code like this:
```scala
lazy val root = Project("root", file("."))
  .aggregate(projects: _*)
```

When I run scalafmt like this:

```bash
scalafmt
```

## Problem

Scalafmt formats code like this:
```scala
lazy val root = Project("root", file("."))
  .aggregate(projects*)
```

and then build fails to load with
```
build.sbt:25: error: value * is not a member of Seq[sbt.ProjectReference]
  .aggregate(projects *)
```

## Expectation

I would still like `build.sbt` and meta-project Scala files formatted, but not with Scala 3 Syntax, since sbt is using Scala 2.12:
```scala
lazy val root = Project("root", file("."))
  .aggregate(projects: _*)
```

## Notes

That also happens for Scala files like `Dependencies.scala`
```scala
object Dependencies:
```

and again build fails with
```
project/Dependencies.scala:3:20: ';' expected but ':' found.
[error] object Dependencies:
```

**Comment by tgodzik** [comment]
Thanks for reporting! You can use fileOverrides to specify which files should be formatted with the Scala3 dialect: https://scalameta.org/scalafmt/docs/configuration.html#scala-dialects

Or alternatively you can define which should use Scala 2 syntax.

@kitbellew should we always use sbt syntax for *.sbt files? What do you think?

**Comment by RomanLebid** [comment]
Thanks for hint, a couple of overrides seems to work 👍 
```
fileOverride {
  "glob:**/project/*.scala" {
    runner.dialect = scala212
  }
  "glob:**/*.sbt" {
    runner.dialect = sbt1
  }
}
```

**Comment by kitbellew** [comment]
> @kitbellew should we always use sbt syntax for *.sbt files? What do you think?

hardcoding a value doesn't seem like a good idea to me. and it doesn't help with the project dependencies file anyway.

since scala 3 is just slowly being adopted, a better way is to set a scala 2 dialect as default (and sbt/ammonite/md files will automatically have this dialect adjusted for them), and override it only for scala 3.
