### ISSUE TITLE
Configuring the dialect in mixed scala2/scala3 code bases

### ISSUE THREAD

**Issue by adamw** [scalameta/scalafmt#2689]
This template is a guideline, not a strict requirement.
- **Version**: 3.0.0
- **Configuration**:
```
runner.dialect = scala3
version = 3.0.0
maxColumn = 120
```

I've got a mixed scala2/scala3 code base (tapir), where each version has macros. The version-specific sources are in `scala-2` or `scala-3` source directories, which are included in sbt depending on the compilation target.

Can I somehow configure scalafmt to use the `scala213` dialect in the `scala-2` directory, but otherwise use `scala3` as the dialect? I tried adding `.scalafmt.conf` to the Scala 2 source root, but that didn't help, I'm still getting errors due to `macro` being not recognized.

**Comment by tgodzik** [comment]
Thanks for reporting! You can use fileOverrides to specify which files should be formatted by which dialect: https://scalameta.org/scalafmt/docs/configuration.html#scala-dialects

Metals will actually try to prefill the configuration file based on the defined build targets

**Comment by adamw** [comment]
Works great :) Thank you and sorry for the noise, I should have found this myself :)
