### ISSUE TITLE
`"+"` syntax for collection append may not be best

### ISSUE THREAD

**Issue by neko-kai** [scalameta/scalafmt#2690]
I haven't found a discussion for the changes in [this commit](https://github.com/scalameta/scalafmt/commit/1ecb69f2a3f5b00d823205455e45cd8233c8b1fd), so I'm opening a new issue.

Since HOCON doesn't allow unquoted operators, the resulting syntax change from
```
align.tokens.add = [...]
```
to
```
align.tokens."+" = [...]
```

Is quite awkward and looks rather wild to a casual reader. Would it be possible to reconsider a symbolic name and use an alphabetic name for a universal append operation instead, such as "append" or even the previous "add"?

```
align.tokens.append = [...]
align.tokens.add = [...]
```
Thanks!

**Comment by kitbellew** [comment]
@neko-kai short answer is probably no. the change was implemented in [metaconfig](https://github.com/scalameta/metaconfig/pull/90/commits/9ea3390d6502db50212d1934aaef9ffbd3ee0744) and allows extending any collection, including a map. if you see examples in that commit, you'll realize that we can't use anything that could potentially be a valid key in that map to extend it, and there's no reason to use different "operators" for arrays and maps.
