### ISSUE TITLE
Formatting issue with scalafmt 3.0.1

### ISSUE THREAD

**Issue by github-julien-pie** [scalameta/scalafmt#2712]
Hey there 🤙

- **Version**: 3.0.1
- **Integration**: IntelliJ
- **Configuration**:
```
version = 3.0.1

preset = defaultWithAlign
maxColumn = 100
importSelectors = singleLine
assumeStandardLibraryStripMargin = true
rewrite.rules = [RedundantBraces, RedundantParens]
rewrite.redundantBraces.stringInterpolation = true
project.git = true
optIn.breaksInsideChains = true
lineEndings = preserve
trailingCommas = preserve
newlines.implicitParamListModifierPrefer = before

rewriteTokens = {
  "⇒": "=>"
  "←": "<-"
  "→": "->"
}
```

## Steps

Given code like this:
```scala
class Toto() {}

private def myScalaFmtTest(): String = {
  val test = new Toto
  ("test")
}
```

When I run scalafmt like this:

```bash
scalafmt
```

## Problem

Scalafmt formats code like this:
```scala
class Toto() {}

private def myScalaFmtTest(): String = {
  val test = new Toto "test"
}
```

## Expectation

I would like the formatted output to look like this:
```scala
class Toto() {}

private def myScalaFmtTest(): String = {
  val test = new Toto
  "test"
}
```

## Workaround

When reformating the code manually, I can bypass this issue.

## Notes

I know the code is not that nice, but in our original use case we returned something else than a `String` and got the exact same behaviour.

**Comment by tgodzik** [comment]
Thanks for reporting! Trying to fix it in https://github.com/scalameta/scalafmt/pull/2713

**Comment by github-julien-pie** [comment]
Thank a lot guys for this quick fix 

![giphy](https://user-images.githubusercontent.com/87750553/131466567-b78bc78d-e402-4f5d-9a17-ef5ce7fc83bc.gif)
