### ISSUE TITLE
align.preset produces Invalid field error

### ISSUE THREAD

**Issue by nikoplusx** [scalameta/scalafmt#2714]
- **plugin version**: 2.4.3
- **core version**: 3.0.1
-  **platform**: Ubuntu 20.4
- **Integration**: IntelliJ 2021.2.1
- **Configuration**:
```
version = 3.0.1

align.preset = more    
maxColumn = 80 
```

## Steps
Run `sbt scalafmt`

## Problem
```
[error] Invalid config: Invalid field: preset. Expected one of openParenCallSite, openParenDefnSite, tokens, arrowEnumeratorGenerator, ifWhileOpenParen, tokenCategory, treeCategory: /home/niko/Workspace/go/src/github.com/1plusX/lookup-tables/.scalafmt.conf
```

## Expectation
Based on the documentation this is a valid config
https://scalameta.org/scalafmt/docs/configuration.html#alignpreset

**Comment by tgodzik** [comment]
Thanks for reporting! I am unable to reproduce this, what is the sbt-scalafmt version you are using?

**Comment by nikoplusx** [comment]
2.4.3

**Comment by tgodzik** [comment]
I didn't notice that you already added it in the issue template, sorry!  Nothing seems to be out of ordinary. Are you sure you don't have a typo or maybe there is a separate scalafmt config?

I added the exact same config and everything seems to work alright. Are you able to reproduce on a small project and maybe share the workspace?

**Comment by nikoplusx** [comment]
typo typo typo sorry for that :)

**Comment by tgodzik** [comment]
No worries! That's the worst of errors :sweat_smile:
