### ISSUE TITLE
Sort imports with groups can reorder program execution

### ISSUE THREAD

**Issue by Katrix** [scalameta/scalafmt#2718]
This template is a guideline, not a strict requirement.
- **Version**: 3.0.1
- **Integration**: IntelliJ
- **Configuration**:
```
version = "3.0.1"
rewrite.rules = [Imports]
rewrite.imports.groups = [["""scala\..*"""]]
```

## Steps

Given code like this:
```scala
object Main {
  import Foo._
  val bar: Bar = getBar
  import bar.ec

  def getBar: Foo.Bar = ???
}
object Foo {
  trait Bar {
    implicit def ec: ExecutionContext
  }
}
```

When I run scalafmt like this:
IntelliJ keybind

## Problem

Scalafmt formats code like this:
```scala
object Main {
  import Foo._
  import bar.ec
  val bar: Bar = getBar

  def getBar: Foo.Bar = ???
}
object Foo {
  trait Bar {
    implicit def ec: ExecutionContext
  }
}
```

## Expectation

I would like the formatted output to look like this:
```scala
object Main {
  import Foo._
  val bar: Bar = getBar
  import bar.ec

  def getBar: Foo.Bar = ???
}
object Foo {
  trait Bar {
    implicit def ec: ExecutionContext
  }
}
```

## Workaround
Keeping the first import outside the class it works fine.

## Notes

See also..

**Comment by kitbellew** [comment]
@Katrix there's a comment in the documentation specifically calling out the limitation that this rule cannot support relative imports because there's no semantic information available. what you want is possible only with scalafix.

**Comment by Katrix** [comment]
I would expect it to just cancel the current sort of it reaches a val inbetween imports though. That doesn't sound like that big of a deal. I'm not really asking for it to sort local imports like that. In this case (not top level would be good enough) I would prefer it just not doing anything instead of trying and failing.
