### ISSUE TITLE
Suggestion - warn about default `runner.dialect`

### ISSUE THREAD

**Issue by dos65** [scalameta/scalafmt#2723]
I think it will save time for both users and mantainers  if there would be an option to discover `runner.dialect` setting just by interacting with scalafmt. I think this one looks more like required one that optional and it correlates with amount of issues about that.

So, what if in case of any parsing error there will be an additional warning like:
```
[warn] runner.dialect isn't configured - the default `scala213` was used. 
Please check [link to documentation] and specify it in configuration
```

That would allow to do a soft transition of this setting from an optional to required and increase the amount of people who know about it.

@tgodzik @kitbellew wdyt?

**Comment by kitbellew** [comment]
sounds good. in fact, i will go one step further and suggest turning warn into error a few months later.

**Comment by dos65** [comment]
An additional thing: maybe we could also add dialect name to errors from parser?
That will cover the case when wrong dialect was set / incorrect `fileOverride` globs.

**Comment by kitbellew** [comment]
> An additional thing: maybe we could also add dialect name to errors from parser?
> That will cover the case when wrong dialect was set / incorrect `fileOverride` globs.

for that, we need to add a name to the dialect object in scalameta.
