### ISSUE TITLE
Infix rewriting rule for operators ending `:`

### ISSUE THREAD

**Issue by danicheg** [scalameta/scalafmt#2724]
- **Version**: 3.0.2
- **Integration**: sbt
- **Configuration**:
```
version = 3.0.2
align.openParenCallSite = true
align.openParenDefnSite = true
maxColumn = 120
continuationIndent.defnSite = 2
assumeStandardLibraryStripMargin = true
danglingParentheses.preset = true
rewrite.rules = [AvoidInfix, SortImports, RedundantParens, SortModifiers]
newlines.afterCurlyLambda = preserve
docstrings.style = Asterisk
docstrings.oneline = unfold
```

## Steps

Given code like this:
```scala
xs reverse_::: ys
```

When I run scalafmt like this:

```bash
scalafmt
```

## Problem

Scalafmt formats code like this:
```scala
xs.reverse_:::(ys)
```

## Expectation
That leads to behaviour changes (see https://www.scala-lang.org/api/2.13.6/scala/collection/immutable/List.html#reverse_:::[B%3E:A](prefix:List[B]):List[B]). Is it expected behaviour for Scalafmt or not?

**Comment by kitbellew** [comment]
@danicheg the `AvoidInfix` rule did it. I don't know how this particular infix should be rewritten but the rule doesn't reorder operands if that's what's happening.

**Comment by danicheg** [comment]
I mean that `Scalafmt` does not format `xs ::: ys` as `xs.:::(ys) when using `AvoidInfix`. But changes formatting for infix version of `reverse_:::`. Is that expected behaviour?

**Comment by kitbellew** [comment]
https://scalameta.org/scalafmt/docs/configuration.html#other

`rewrite.neverInfix` describes which operators should be rewritten. specifically, include filters do not match `:::` unlike `reverse...`. perhaps we should add `:$` to exclude.

**Comment by tgodzik** [comment]
> perhaps we should add :$ to exclude.

Yeah, everything that ends with `:` has the order reversed, so it applies to the next expression
