### ISSUE TITLE
Keep new line for a single extension method for Scala 3

### ISSUE THREAD

**Issue by danicheg** [scalameta/scalafmt#2725]
That perhaps not a bug, rather a 'help wanted' issue.

- **Scala version**: 3.0.2
- **Scalafmt version**: 3.0.2
- **Integration**: sbt
- **Configuration**:
```
version = 3.0.2
maxColumn = 100
continuationIndent.callSite = 2
newlines {
  sometimesBeforeColonInMethodReturnType = false
  source=keep
}
align {
  arrowEnumeratorGenerator = false
  ifWhileOpenParen = false
  openParenCallSite = false
  openParenDefnSite = false
  tokens = ["%", "%%"]
}
docstrings.style = Asterisk
rewrite {
  rules = [SortImports, RedundantBraces]
  redundantBraces.maxLines = 1
}
fileOverride {
  "glob:**/scala-3.x/src/main/scala/**" {
    runner.dialect = scala3
  }
}
```

## Steps

Given code like this:
```scala
extension (a: All) 
  def getAll: Boolean = a
```

When I run scalafmt like this:

```bash
scalafmt
```

## Problem

Scalafmt formats code like this:
```scala
extension (a: All) def getAll: Boolean = a
```

## Expectation

I would like the formatted output to look like this:
```scala
extension (a: All) 
  def getAll: Boolean = a
```

**Comment by tgodzik** [comment]
Thanks for reporting! I think it's rather a bug since you have `source=keep` set it should leave the newline as is.

Let me see if I can fix it quickly.

**Comment by danicheg** [comment]
Thanks to @dos65 for the initial check on this.
