### ISSUE TITLE
Spread collection constants over multiple lines

### ISSUE THREAD

**Issue by vasigorc** [scalameta/scalafmt#2732]
This template is a guideline, not a strict requirement.
- **Version**: 3.0.0
- **Integration**: IntelliJ
- **Configuration**:
```
danglingParentheses.ctrlSite = false

docstrings.blankFirstLine = yes

indent.defnSite = 2
indent.ctorSite = 4
indent.extraBeforeOpenParenDefnSite = 2

maxColumn = 120

rewrite.rules = [Imports]
rewrite.imports.sort = original
```

## Steps

Given code like this:
```scala
private[this] val friendNames = Set("Xavia", "Seyyid", "Xerxes", "Manjula", "Roise", "Rahman", "Medraut", "Fatih", "Ajay")

```

When I run scalafmt from Intellij (Opt + Cmd + L).

## Problem

Scalafmt formats code like this:
```scala
  private[this] val friendNames =
    Set("Xavia", "Seyyid", "Xerxes", "Manjula", "Roise", "Rahman", "Medraut", "Fatih", "Ajay")
```

## Expectation

I would like the formatted output to look like this:
```scala
  private[this] val friendNames = Set(
    "Xavia", 
    "Seyyid", 
    "Xerxes", 
    "Manjula", 
    "Roise", 
    "Rahman", 
    "Medraut", 
    "Fatih", 
    "Ajay"
    )
```

## Workaround

Using `newlines.source=keep` could work but it would also add other changes which I would like to avoid.

## Notes

This only applies to constant collection declaration. This particular collection declaration spans beyond `maxColumn` but I would like this rule to apply regardless.

**Comment by kitbellew** [comment]
https://scalameta.org/scalafmt/docs/configuration.html#-format-off
