### ISSUE TITLE
Control newlines with trailing commas

### ISSUE THREAD

**Issue by fdietze** [scalameta/scalafmt#2755]
The Dart code formatter `dartfmt` has a very useful feature, which I'm missing in `scalafmt` now:

If there is a trailing comma, the formatter adds line-breaks after every comma. If there isn't, it tries to put all elements into one line and wrap after `max_columns`.
(https://flutter.dev/docs/development/tools/formatting#using-trailing-commas)

You can try this behavior online here:
https://dartpad.dev/

With the following code:
```dart
// try adding and removing the trailing commas, then press the "Format" button

int multiply(
  int x,
  int y,
) =>
    x * y;

int longFunctionName(int a, int b, int c, int d, int e, int f, int g, int h,
        int i, int j, int k, int l) =>
    a + b;
```

**Comment by kitbellew** [comment]
can you please use scala examples and appropriate scalafmt configuration to explain what you're getting and what you'd like to have instead?

**Comment by fdietze** [comment]
Upon adding the trailing comma
```scala
def longFunctionName(a: Int, b: Int,) = a + b;
```
I'd like `scalafmt` to output:

```scala
def longFunctionName(
    a: Int,
    b: Int,
) = a + b;
```

Removing the comma again, should put it back together into one single line:

```scala
def longFunctionName(a: Int, b: Int) = a + b;
```

You will understand it better if you quickly play with the dart formatter.

**Comment by kitbellew** [comment]
this is not a dart formatter.

scala does not support a trailing comma if there's no newline after it, and scalafmt does not format invalid scala code.

**Comment by fdietze** [comment]
> this is not a dart formatter.

Really? I didn't know...

I just edited the code to become valid scala code.

**Comment by kitbellew** [comment]
please show what scalafmt produces and what you think it should produce? and what's the configuration?

**Comment by fdietze** [comment]
https://scastie.scala-lang.org/5a3MY6FDTEW2pX5FNSByEw

I think Scastie is using the default scalafmt configuration.

Before formatting:
```scala
def longFunctionName(a: Int, b: Int,
                    ) = a + b;

def longFunctionName2(
    a: Int,
    b: Int
) = a + b;
```

After formatting, I expect it to become:
```scala
def longFunctionName(
    a: Int,
    b: Int,
) = a + b;

def longFunctionName2(a: Int, b: Int) = a + b;
```

But the actual output is:
```scala
def longFunctionName(a: Int, b: Int) = a + b;

def longFunctionName2(
    a: Int,
    b: Int
) = a + b;
```

**Comment by kitbellew** [comment]
in your example, trailing commas are removed. the default configuration doesn't do that.

https://scalameta.org/scalafmt/docs/configuration.html#trailing-commas

**Comment by tgodzik** [comment]
Doesn't it though? The default is `never`, which corresponds to `Makes sure there are no trailing commas:`

**Comment by tgodzik** [comment]
Testing it locally I can see the trailing comas are removed, even with it set  to `always`

**Comment by fdietze** [comment]
I just reproduced it locally with the following config:
```
version = "3.0.0-RC7"
```

**Comment by tgodzik** [comment]
I think with `trailingCommas = keep` or `trailingCommas = always` it would make sense to actually split if over the different lines. 

We can keep the default to remove them.

**Comment by kitbellew** [comment]
ah, my mistake about the default. nevertheless, there's a setting which will preserve trailing commas and will likely format with one argument per line, just as requested.

the second case is called config-style formatting, and scalafmt will only turn it into a single line for `newlines.source = [un]fold`.

**Comment by fdietze** [comment]
with `trailingCommas = keep`, the result is still:

input
```scala
def longFunctionName(a: Int, b: Int,
                    ) = a + b;

def longFunctionName2(
    a: Int,
    b: Int
) = a + b;
```

output
```scala
def longFunctionName(a: Int, b: Int) = a + b;

def longFunctionName2(
    a: Int,
    b: Int
) = a + b;
```

It even removes the comma.

**Comment by kitbellew** [comment]
fixing the behaviour for `trailingCommas = keep`. it will not be allowed for `newlines.sources = [un]fold`, however.

also, the folding behaviour of
```
def longFunctionName2(
    a: Int,
    b: Int
) = a + b
```
can only be accomplished by manually formatting it as
```
def longFunctionName2(
    a: Int,
    b: Int   ) = a + b
```
or
```
def longFunctionName2(    a: Int,
    b: Int
) = a + b
```
in `newlines.source=[classic] or keep`, scalafmt will *not* attempt to fold if there's a newline after opening paren *and* a newline before closing paren.

**Comment by fdietze** [comment]
Thank you for fixing it. Do you know why Scala decided to make trailing commas in one line an invalid syntax?

**Comment by fdietze** [comment]
Found it, it was a subjective decision: https://docs.scala-lang.org/sips/trailing-commas.html
