### ISSUE TITLE
`Missing token index` error since 3.0.5

### ISSUE THREAD

**Issue by xuwei-k** [scalameta/scalafmt#2772]
- **Version**: 3.0.5
- **Integration**: sbt plugin
- **Configuration**:

```
version=3.0.5
align.preset = more
maxColumn = 120
continuationIndent.defnSite = 2
danglingParentheses.preset = true
rewrite.rules = [SortImports, RedundantBraces, RedundantParens, SortModifiers]
runner.dialect = Scala213
```

## Steps

sbt version: 1.5.5
sbt plugin version: 2.4.3

```scala
package example

class A {

  @B("c") // d
  case class E(f: Int)

  val g = E(2)

}
```

When I run scalafmt like this:

```bash
sbt scalafmt
```

## Problem

```scala
[info] Formatting 1 Scala sources...
[error] Missing token index [66:67]: `
[error] `: /Users/kenji/scalafmt-bug/A.scala
[error] (Compile / scalafmt) Missing token index [66:67]: `
[error] `: /Users/kenji/scalafmt-bug/A.scala

```

## Workaround

use 3.0.4

## Notes

- https://github.com/optics-dev/Monocle/pull/1210
- https://github.com/optics-dev/Monocle/blob/8e52b0b8a36dae68e895b6bf5c6eaa26f7424466/example/src/test/scala/monocle/LensExample.scala#L50-L53

**Comment by sideeffffect** [comment]
In ZIO Prelude, this is triggered by a mere
```scala
trait Dummy[A]
```
