### ISSUE TITLE
Separated defns get aligned since 3.0.5

### ISSUE THREAD

**Issue by yurique** [scalameta/scalafmt#2775]
- **Version**: 3.0.5
- **Configuration**:
```
version=3.0.5
runner.dialect = "scala213"
fileOverride {
  "glob:**/scala-3/**" {
    runner.dialect = scala3
  }
}
style = defaultWithAlign
align.openParenCallSite = true
align.openParenDefnSite = true
align.arrowEnumeratorGenerator = true
maxColumn = 160
continuationIndent.defnSite = 2
assumeStandardLibraryStripMargin = true
danglingParentheses.defnSite = true
danglingParentheses.callSite = true
rewrite.rules = [AvoidInfix, ExpandImportSelectors, RedundantParens, SortModifiers]
docstrings = JavaDoc
newlines.afterCurlyLambda = preserve
docstrings.style = Asterisk
docstrings.oneline = unfold
trailingCommas = "preserve"
optIn.breaksInsideChains = true
includeCurlyBraceInSelectChains = true
//includeNoParensInSelectChains = true
binPack.parentConstructors="never"
//newlines.source="keep"
align.preset = most
```

## Steps

Update scalafmt version from `3.0.4` to `3.0.5`.

Example:
https://github.com/tulz-app/laminext/pull/72/files

Given code like this:
```scala
  override protected[this] def onStart(): Unit = {
    startCallback()
    super.onStart()
  }

  override protected[this] def onStop(): Unit = {
    stopCallback()
    super.onStop()
  }
```

When I run scalafmt like this:

via the sbt-scalafmt plugin.

## Problem

Scalafmt formats code like this (there are more defs in the file, so the `=` got aligned with the furthest one):
```scala
  override protected[this] def onStart(): Unit                                         = {
    startCallback()
    super.onStart()
  }

  override protected[this] def onStop(): Unit                                          = {
    stopCallback()
    super.onStop()
  }
```

## Expectation

I would like the formatted output to look like this (same as original, as it was already correctly formatted with 3.0.4):
```scala
  override protected[this] def onStart(): Unit = {
    startCallback()
    super.onStart()
  }

  override protected[this] def onStop(): Unit = {
    stopCallback()
    super.onStop()
  }
```

## Notes

This might be related to this PR: https://github.com/scalameta/scalafmt/pull/2753

**Comment by github-dimitri-ho** [comment]
It seems to happen only when one of the methods in the object / class has a scope modifier

**Comment by yurique** [comment]
in the same example PR, same formatting got applied to the `lazy val`s in the `build.sbt`: https://github.com/tulz-app/laminext/pull/72/files#diff-5634c415cd8c8504fdb973a3ed092300b43c4b8fc1e184f7249eb29a55511f91

**Comment by poslegm** [comment]
Another example: https://github.com/poslegm/munit-zio/pull/27/commits/50387efe2b38d3e31bced008d4c3e2933a15e5dd
