### ISSUE TITLE
Method of controlling where the "other" group is placed for import rewrites

### ISSUE THREAD

**Issue by lespea** [scalameta/scalafmt#2777]
- **Version**: 3.0.5
- **Integration**: cli
- **Configuration**:
```
rewrite.rules = [Imports]
rewrite.imports.sort = ascii
rewrite.imports.groups = [
  ["foo\\..*"],
  [],
  ["bar\\..*"]
]
```

## Steps

Given code like this:
```scala
import bar._
import foo._
import other._
```

When I run scalafmt like this:

```bash
scalafmt
```

## Problem

Scalafmt formats code like this:
```scala
import foo._

import bar._

import other._
```

## Expectation

I would like the formatted output to look like this:
```scala
import foo._

import other._

import bar._
```

## Notes

Instead of forcing any unmatched import at the end of the groups, it would be nicer if we could specify where that group goes.  One idea I had was putting an empty array in the list of where it should go, but it could maybe be some specific keyword or other method of specifying where to put them.

**Comment by kitbellew** [comment]
have you tried using a matching regex?

**Comment by lespea** [comment]
The problem is then it matches everything and puts nothing in the following groups

**Comment by lespea** [comment]
Perfect solution, thanks!
