### ISSUE TITLE
rewrite.scala3.removeOptionalBraces - incorrect rewrite for lambda with body in braces

### ISSUE THREAD

**Issue by dos65** [scalameta/scalafmt#2781]
- **Version**: 3.0.5
- **Configuration**:
```
version = "3.0.5"
runner.dialect = scala3
rewrite.scala3.removeOptionalBraces = yes
```

## Steps

Given code like this:
```scala
object x:
  val y = List(1).map(v => {
    println(v)
    v + 1
  })
```

Scalafmt formats code like this:
```scala
object x:
  val y = List(1).map(
  v =>
    println(v)
    v + 1)
```

## Expectation

I would like the formatted output to look like this:
```scala
object x:
  val y = List(1).map(v => {
    println(v)
    v + 1
  })
// or
object x:
  val y = List(1).map { v =>
    println(v)
    v + 1
  }
```

**Comment by kitbellew** [comment]
> Scalafmt formats code like this:
> 
> ```scala
> object x:
>   val y = List(1).map(
>   v =>
>     println(v)
>     v + 1)
> ```

If it's incorrect, why does `scalameta` successfully parse it? aren't braces optional?

**Comment by kitbellew** [comment]
> I would like the formatted output to look like this:
> 
> ```scala
> object x:
>   val y = List(1).map(v => {
>     println(v)
>     v + 1
>   })
> ```

this would mean the braces weren't optional, no?

**Comment by kitbellew** [comment]
> I would like the formatted output to look like this:
> 
> ```scala
> object x:
>   val y = List(1).map { v =>
>     println(v)
>     v + 1
>   }
> ```

for that, you just need to enable the `RedundantBraces` rewrite.

**Comment by dos65** [comment]
@kitbellew it's correct from syntax viewpoint but not from formatter.

I wasn't correct in expectation. It should be:
```scala
object x:
  val y = List(1).map(v =>
    println(v)
    v + 1
  )
```

An interesting thing it that after the second run of scalafmt it formats the source as described above

**Comment by kitbellew** [comment]
in that case, the linked pr #2783 fixed the problem. thanks for reporting.
