### ISSUE TITLE
Line calculation rules in `rewrite.scala3.insertEndMarkersMinLines` 

### ISSUE THREAD

**Issue by dos65** [scalameta/scalafmt#2786]
- **Version**: 3.0.5
- **Configuration**:
```
runner.dialect = scala3
rewrite.scala3.convertToNewSyntax = yes
rewrite.scala3.removeOptionalBraces = yes
rewrite.scala3.insertEndMarkerMinLines = 5
```

Is more close to discussion rather to the issue. 
After [trying this setting](https://github.com/scalameta/metals/pull/3165/files) on metals I found some places where end marker inserting doesn't look great.

- Could we ignore non-body lines in the following samples?
  - Method
    ```scala
    def foo(
        a1: Int,
        a2: Int
    ): Int =
      println()
      42 
    // <- end marker is added but body is 2 lines only
    ```
  - Class
    ```scala
    case class X(
      a1: Int,
      a2: Int
    ):
      def foo: Int = 42
    // <- end marker is added but body is 1 line only
    ```
- Could end marker for  `if`-`else` being omitted if the last else block is less than min lines:
  ```scala
  def foo2: Int =
    fx()
    if true then
      println()
      println()
      println()
      println()
      println()
      println()
      println()
      32
    else 42 
   // <- end marker is added
  end foo2
  ```

**Comment by kitbellew** [comment]
> * Could end marker for  `if`-`else` being omitted if the last else block is less than min lines:
>   ```scala
>   def foo2: Int =
>     fx()
>     if true then
>       println()
>       println()
>       println()
>       println()
>       println()
>       println()
>       println()
>       32
>     else 42 
>    // <- end marker is added
>   end foo2
>   ```

the end marker is `end if`, not `end else`, so my opinion is no.

in fact, if-else not having a "body" was one of the primary reasons why i didn't even attempt to navigate the extra complexity of calculating lines based on a "body".

here's another reason. the way i interpret the end marker is this: if you look at a code snippet (let's say, in a diff) and can see the end of a method/class but not the beginning, the end marker will tell us what it belongs to. if the body is 10 lines long but the signature is 100, you can't see the start and the end marker will help.

other similar examples exist; scalastyle's line limit per method doesn't apply to the body but to the entire method, starting with the `def` line.

**Comment by dos65** [comment]
Mine attitude to end markers is different.
Honestly, I have no idea in which case I personally would want to put them manually.

However, having this setting, I would like have a sense when I need to put them and where they aren't required.
To have less failures after fmt check and to have less situations when I need to readjust the code to meet it with my taste and fmt rules.

The obvious rule for me would be the following one: `Use end marker to close the indented block that is bigger than limit`.
Visually you see these blocks and I think it's easier to estimate only these lines.
I think that approach would solve all mentioned samples for me.

Examples:
```scala
// visual part
def foo2: Int =
  fx()
  if true then
    println()  // this block is visually 
    println()  // seen as closed one
    println()  // because of `else` 
    32         // that has greater indentation
  else 42 
  end if
end foo2

// ------------
// additional thing with if-else
// getting this `end if` is weird - I believe some people will want to rewrite it
//
// I think this should be fixed as it's an opportunity for the case 
// where you wanted to make code looks pretty but made a mistake/introduced a bug
// if you wasn't careful enough 
def foo2: Int =
  fx()
  if !true then   // swap branches
    42
  else
    println()
    println()
    println()
    32 
end foo2
```
