### ISSUE TITLE
Grouped imports are missing indentation if not at top-level

### ISSUE THREAD

**Issue by martingd** [scalameta/scalafmt#2834]
- **Integration**: Metals/VSCode
- **Configuration**:
```
rewrite.rules = [Imports]
rewrite.imports.sort = original
rewrite.imports.groups = [
 ["scala\\..*"],
 ["java\\..*"],
]
```

## Steps
I have setup VSCode to format my code when saving. Using the above configuration for grouping imports, given code like this:
```scala
trait X:
  import scala.collection.mutable
  import java.io.File

  def x: Int
```

## Problem

Scalafmt formats code like this:
```scala
trait X:
  import scala.collection.mutable

import java.io.File

def x: Int
```

## Expectation

I would like the formatted output to look like this:
```scala
trait X:
  import scala.collection.mutable

  import java.io.File

def x: Int
```

## Workaround

None, apart from keeping imports at the outermost level

**Comment by kitbellew** [comment]
what's the version?

**Comment by kitbellew** [comment]
this seems to be the same issue that was fixed in #2804 and released in v3.0.7. since your config doesn't specify a version explicitly, it's whatever your IDE uses, and could be older.

**Comment by martingd** [comment]
@kitbellew You are absolutely right. It is a duplicate. I tried to search for identical issues but missed it.
When setting the version to 3.0.7 in .scalafmt.conf, it works perfectly.

**Comment by martingd** [comment]
Duplicate of #2804
