### ISSUE TITLE
Cannot use include inside {} of indentOperator

### ISSUE THREAD

**Issue by Prometheus3375** [scalameta/scalafmt#2840]
- **Version**: 3.0.8
- **Integration**: IntelliJ
- **Configuration**:
```
version = 3.0.8

runner.dialect = "scala212"

maxColumn = 100

indentOperator {
    topLevelOnly = true
    exclude = """^(&&|\|\|)$"""
    include = """^.*$"""
}
```

## Steps

Format any file.

## Problem

An error is thrown:
```
Failed to load scalafmt config:
parse error: String: 12: include keyword is not followed by a quoted string, but by: '='
```

## Expectation

No error.

---

It seems like config parser ignores the fact that `include` keyword is inside `indentOperator` braces.

**Comment by kitbellew** [comment]
https://github.com/lightbend/config/blob/main/HOCON.md#includes
