### ISSUE TITLE
Alignment of @param in ScalaDoc String

### ISSUE THREAD

**Issue by Scarysize** [scalameta/scalafmt#2842]
This template is a guideline, not a strict requirement.
- **Version**: 3.0.0
- **Integration**: IntelliJ, Visual Studio Code
- **Configuration**:
```
# Take from akka github repository, slightly adjusted

version = 3.0.0

preset = default

indentOperator.preset = akka
maxColumn = 120

newlines.selectChains = unfold

align.tokens = [{code = "=>", owner = "Case"}]
align.openParenDefnSite = false
align.openParenCallSite = false

docstrings.style = SpaceAsterisk
docstrings.blankFirstLine = keep
docstrings.wrap = no
docstrings.oneline = keep

optIn.breakChainOnFirstMethodDot = false
optIn.configStyleArguments = false

danglingParentheses.defnSite = true
danglingParentheses.ctrlSite = true
danglingParentheses.callSite = true

spaces.inImportCurlyBraces = false

# skipped the "rewrite" rules
```

## Steps

Given code like this:
```scala
/**
  * This is just a demo.
  * @param foo Some string value
  *   @param bar Some int value
  */
case class MyCaseClass(foo: String, bar: Int)

```

When I run scalafmt like this:

```bash
scalafmt
```

## Problem

Scalafmt formats code like this:
```scala
/**
  * This is just a demo.
  * @param foo Some string value
  *   @param bar Some int value
  */
case class MyCaseClass(foo: String, bar: Int)

```

## Expectation

I would like the formatted output to look like this:
```scala
/**
  * This is just a demo.
  * @param foo Some string value
  * @param bar Some int value
  */
case class MyCaseClass(foo: String, bar: Int)

```

## Workaround

I've found that by using `docstrings.wrap = yes` the `@param` lines are correctly aligned. But, of course, this wraps the parameter description.

**Comment by kitbellew** [comment]
a comment or a docstring is not code, it will not be touched unless the respective wrap parameter is on.

if the docstring is parsed, we need to know what to do with every single element (annotation, nested list, code block, etc). in this request, you've described only one such element. what about the rest?

i think the best workaround is to format this manually.

**Comment by Scarysize** [comment]
Thanks for your response, seems reasonable. I will check if I can get Intellij to format the doc strings. Its formatter has the intended effect.
