### ISSUE TITLE
Add a preset optimised to minimise merge conflicts

### ISSUE THREAD

**Issue by bplommer** [scalameta/scalafmt#2845]
This could include:

- no vertical alignment
- trailing commas
- expand imports
- Dangling parentheses

**Comment by kitbellew** [comment]
@bplommer can you provide a full list, please?

support for trailing commas depends on the dialect, and dialect must be explicitly specified.

also, should it use `newlines.source = unfold` or instead `newlines.source = keep`?

**Comment by kitbellew** [comment]
please reopen when there's more context
