### ISSUE TITLE
Separate maxColumn setting for comments

### ISSUE THREAD

**Issue by kitlangton** [scalameta/scalafmt#2850]
I'd be happy to try my hand at implementing this, but I first wanted to see if it would be a welcome addition.

My team very much enjoys the wider column width of 120 characters for code. However, we don't find comments to be quite as readable at this width. Apparently—according to the internet's many typographic gurus—somewhere from 45-75 characters per line is ideal for reading. 

I really love scalafmt's new (at least to me 😮) feature of auto-wrapping comment text, and it would be great to be able to re-enable that without getting the full 120 width wrapping. So being able to add a setting such as `maxColumn.comments = 80` would be splendid.

What do you think? 😄

**Comment by kitbellew** [comment]
not for any comments but... https://scalameta.org/scalafmt/docs/configuration.html#docstringswrapmaxcolumn

**Comment by kitlangton** [comment]
!! I must have missed that !! Thank you, other Kt! Thats perfect ❤️
