### ISSUE TITLE
How to set blanks after class/object header/end ?

### ISSUE THREAD

**Issue by KonstantinTr** [scalameta/scalafmt#2888]
Hi!

I am trying to make scalafmt to control the blanks after opening braces and before closing braces (more specifically - remove blanks over the limit) for classes/objects/traits/methods.

In IntelliJ IDEA formatting settings there is a family of settings called `keep maximum blank lines` and `minimum blank lines` (with options such as `after class header` and `before class end`).

To extend of my knowledge it is not possible to control blanks before/after curly braces with current feature set of scalafmt, would you kindly consider adding such functionality? 

Many thanks in advance for all the help!

- **Version**: 2.6.4
- **Integration**: IntelliJ
- **Configuration**:
```
version = 2.6.4
maxColumn = 100
```

## Steps

Given code like this:
```scala
object a {

  val b = 0
  val c = 1


}
```

When I run scalafmt like this:

```bash
scalafmtAll
```

## Problem

Scalafmt formats code like this:
```scala
object a {

  val b = 0
  val c = 1


}
```

## Expectation

I would like the formatted output to look like this:
```scala
object a {
  val b = 0
  val c = 1
}
```

## Workaround

The closest I have found to the solution is [this](https://github.com/scalameta/scalafmt/issues/1653) but it is not possible to have `0` blank lines. On top of that it also inserts blanks between all top level statements of the class. And I need to modify only blanks after opening brace and before closing brace of the class/trait/object

**Comment by kitbellew** [comment]
доводилось ли почитать это: https://scalameta.org/scalafmt/docs/configuration.html#newlinestoplevelstatementblanklines

**Comment by KonstantinTr** [comment]
Thanks for the link!
Unfortunately I don't see how I can achieve what I described in the issue with `newlines.topLevelStatementBlankLines`.

I was thinking to make a regex to narrow the search, but I don't think it will work due to following: 
(1) It does not match `Token.LeftBracket` cause it's not a top level statement (so I will need to somehow match definitions within template)
(2) I can't match something like `^Defn.Object` cause expected behaviour would be different if the def is on source-level or a nested definition
(3) There is no way to state minNest to omit source-level statements
(4) I couldn't find how matching only first/last statement works in scalafmt

Would it be asking to match to point out how to overcome the shortcomings posted above?

I am trying to make `unformatted`:
```scala
//somefile.scala

object A {

  val a = 0


  val b = 1

}


object B {
  
  object C {
  
    val a = 0

    val b = 1

  }

}
```

to look like `formatted`:
```scala
//somefile.scala

object A { //  no blank after header
  val a = 0
  //  max 1 blank between statements within the body
  val b = 1
} //  no blanks before closing brace
//  max 1 blank between statements on source-level
object B { //  no blank after header
  object C { //  no blank after header
    val a = 0
    //  blank between statements within the body is left intact
    val b = 1
  } //  no blanks before closing brace
} //  no blanks before closing brace

```

Would you consider reopening the issue if you agree that there is no way to configure such formatting with the current functionality of `newlines.topLevelStatementBlankLines`?

Thnx!

**Comment by kitbellew** [comment]
> I was thinking to make a regex to narrow the search, but I don't think it will work due to following: (1) It does not match `Token.LeftBracket` cause it's not a top level statement (so I will need to somehow match definitions within template)

`Token.LeftBracket` is a token, not a tree so it will never match.

> (3) There is no way to state minNest to omit source-level statements

I can add `minNest`, in addition to `maxNest`. However, you could always use a `maxNest` rule that does nothing -- and, therefore, simply blocks other rules. This scenario is clearly documented.

> (4) I couldn't find how matching only first/last statement works in scalafmt

Via `beforeAll` and `afterAll`, which are also documented.


If you didn't care about nesting constraints, what you want can be accomplished via this:
```
newlines.topLevelStatementBlankLines = [
  {
    minBreaks = 0
    blanks = {
      before = 1
      after = 1
      beforeAll = -1
      afterAll = -1
    }
  }
]
```

Otherwise, the only thing that stands in your way is a bug in how nesting is computed (which I will fix shortly).

Keep in mind that scalafmt will always _predictably set_ the number of blanks. If a rule matches (and rules do not care about the existing number of blanks), it will dictate the number. If no rules match, the number of blanks will be no more than 1 (depending on whether there were any blanks to begin with). Therefore, you can't allow a user the flexibility of controlling the number of blanks in some range.

**Comment by KonstantinTr** [comment]
@kitbellew This is amazing! 
Thanks a ton for the help and special thanks for adding minNest and the bug fix!
