### ISSUE TITLE
Alignment for fields with an annotation on the same line

### ISSUE THREAD

**Issue by deusaquilus** [scalameta/scalafmt#2894]
- **Version**: latest
- **Integration**: any
- **Configuration**:

I frequently deal with a large sequence of fields with an annotation that should preferably be on the same line.
```scala
trait MyInfo {
  @Mapping(PricingDefinitions.totalPrice) def price: BigDecimal
  @Mapping(PricingDefinitions.partialPrice) def parPrice: BigDecimal
  @Mapping(PricingDefinitions.rebate) def rebate: BigDecimal
  @Mapping(LatePricingDefinitions.lateFee) def lateFee: BigDecimal
  @Mapping(LatePricingDefinitions.maxLateFee) def maxLateFee: BigDecimal
  @Mapping(Definitions.dueDate) def due: LocalDate
  @Mapping(Definitions.daysPastDue) def daysPast: Int
  @Mapping(Definitions.launchDate) def launch: LocalDate
  @Mapping(Definitions.initialDate) def initial: Localdate
}
```

It would give me a lot of sanity to have the defs be automatically aligned:
```scala
trait MyInfo {
  @Mapping(PricingDefinitions.totalPrice)     def price: BigDecimal
  @Mapping(PricingDefinitions.partialPrice)   def parPrice: BigDecimal
  @Mapping(PricingDefinitions.rebate)         def rebate: BigDecimal
  @Mapping(LatePricingDefinitions.lateFee)    def lateFee: BigDecimal
  @Mapping(LatePricingDefinitions.maxLateFee) def maxLateFee: BigDecimal
  @Mapping(Definitions.dueDate)               def due: LocalDate
  @Mapping(Definitions.daysPastDue)           def daysPast: Int
  @Mapping(Definitions.launchDate)            def launch: LocalDate
  @Mapping(Definitions.initialDate)           def initial: Localdate
}
```
I tried several variations of `align.tokens` without success:
```
# Doesn't work
align.tokens."+" = [{
  code = ")"
  owners = [{
    regex = "Init"
    parents = [ "Mod.Annot" ]
  }]
}]

# Also doesn't work
align.tokens."+" = [{
  code = ")"
  owners = [{
    regex = "Mod\\.Annot"
    parents = [ "Defn\\.Def" ]
  }]
}]

# Also doesn't work
align.tokens."+" = [{
  code = "def"
  owners = [{
    parents = [ "Defn\\.Def" ]
  }]
}]
```
Would be really nice if scalafmt could do this!

P.S.
One more thing. If a field and an annotation are on the same line and they exceed the `maxColumn` width:
```scala
trait MyTrait {
  @AnnotationWhichIsVeryVeryVeryExtremelyLong def fieldWhichIsVeryVeryVeryExtremelyLong: ExtremelyLongType
}
```
They should overflow by moving the `def` to the next line whenever possible (i.e. if the field is in a class/trait/object body)
```scala
trait MyTrait {
  @AnnotationWhichIsVeryVeryVeryExtremelyLong
  def fieldWhichIsVeryVeryVeryExtremelyLong: ExtremelyLongType
}
```

**Comment by kitbellew** [comment]
@deusaquilus please try
```
align.tokens."+" = [{
  code = "def"
  owners = [{ regex = "Decl\\.Def" }]
}]
```

**Comment by deusaquilus** [comment]
@kitbellew That works. Thanks!
Should I close the issue?

**Comment by deusaquilus** [comment]
Also, is there some kind of way to get the Decl things in the [tree explorer](https://astexplorer.net/#/gist/ec56167ffafb20cbd8d68f24a37043a9/677e43f3adb93db8513dbe4e2c868dd4f78df4b3)?

**Comment by kitbellew** [comment]
i can see plenty of `Decl` under the `Template` under the `Trait`:

https://astexplorer.net/#/gist/ec56167ffafb20cbd8d68f24a37043a9/c4e6afb806b01cae19668dbf247e8d04ff6843bd

**Comment by deusaquilus** [comment]
Oh! I didn't even know to look under `Template`. Thanks!

**Comment by nrktkt** [comment]
piggy backing on this
is there a way to do the same for annotations on parameters?

eg. 
```scala
case class A(
 @Anno field: String,
       field2: Int
)
```

**Comment by kitbellew** [comment]
> piggy backing on this is there a way to do the same for annotations on parameters?
> 
> eg.
> 
> ```scala
> case class A(
>  @Anno field: String,
>        field2: Int
> )
> ```

maybe not. alignment works on specific tokens, the only thing they have in common is `:` which is in the wrong place.
