### ISSUE TITLE
When fields have an annotation `newlines.source = keep` never collapse an annotation and def into a single line

### ISSUE THREAD

**Issue by deusaquilus** [scalameta/scalafmt#2895]
- **Version**: Latest
- **Integration**: VS Code
- **Configuration**:
```
version = 2.0.1
maxColumn = 100
```
When `newlines.source = keep`, this:
```scala
trait MyTrait {
  @MyAnnotation
  def field: FieldType
}
```
Should never become this:
```scala
trait MyTrait {
  @MyAnnotation def field: FieldType
}
```
This should always be the case, even when doing #2894

**Comment by kitbellew** [comment]
@deusaquilus can you see if `optIn.annotationNewlines = true` solves the problem?

**Comment by deusaquilus** [comment]
I'll try it. It looks like this is the normal behavior when combined with your solution to #2894.
