### ISSUE TITLE
Uppercase long literal suffix

### ISSUE THREAD

**Issue by olafurpg** [scalameta/scalafmt#293]
Taken from Spark coding style: https://github.com/databricks/scala-style-guide/blob/master/README.md#long-literals

Original:

``` scala
11l
```

Scalafmt:

``` scala
11l
```

I would like the input to look like this:

``` scala
11L
```

Using:
- 0.2.5
- --style default

**Comment by sjrd** [comment]
:+1:

Also, lowercase float and double literals: `1f` and `1d` instead of `1F` and `1D`. The latter tends to more easily be interpreted as hexadecimal, for some weird cognitive reason.

**Comment by olafurpg** [comment]
Got most of this feature implemented but stuck on https://github.com/scalameta/scalameta/issues/459 for testing purposes. The tests fails now because I can't prove that the AST is unchanged. Hoping to get that fixed in scalameta instead of some hack my side.
