### ISSUE TITLE
Scalafmt generates code incompatible with Scala 3

### ISSUE THREAD

**Issue by Atry** [scalameta/scalafmt#3005]
- **Version**: 3.3.0
- **Integration**: @scala-steward
- **Configuration**:
```
runner.dialect = "scala3"
version = "3.3.0"
maxColumn = 80
```

## Steps

Given code like this:
```scala
        if ({ !Yield(2); false }) {
          !Yield(3)
        } else {
          !Yield(4)
        }
```

When I run scalafmt like this:

```bash
scalafmt
```

## Problem

Scalafmt formats code like this:
```scala
        if
          ({ !Yield(2); false
        }) {
          !Yield(3)
        } else {
          !Yield(4)
        }
```

The following errors will be reported by Scala 3 compiler when compiling Scalafmt generated code
```
'then' expected, but 'else' found
```

## Expectation

I would like the formatted output to look like this:
```scala

        if ({ !Yield(2); false }) {
          !Yield(3)
        } else {
          !Yield(4)
        }
```

## Notes

The scalafmt change can be found at https://github.com/ThoughtWorksInc/Dsl.scala/pull/575/files and the compile error can be found at https://github.com/ThoughtWorksInc/Dsl.scala/runs/4631021905

**Comment by kitbellew** [comment]
please share the configuration and the exact code here inline.

**Comment by Atry** [comment]
Thank you!
