### ISSUE TITLE
Is there an option that disables trimming trailing whitespaces?

### ISSUE THREAD

**Issue by chengluyu** [scalameta/scalafmt#3006]
Is there an option that disables trimming trailing whitespaces? It triggers commit fights when team up with people who don’t use a formatter. Forgive me if this is documented. I searched for a while but found nothing about trailing whitespaces.

**Comment by kitbellew** [comment]
no, such an option is not available.

also, you can't share a repository with anyone who is not using this formatter, because trailing whitespace is not the only difference that can happen in this case.
