### ISSUE TITLE
RedundantBraces for `val`/`var`/`type` cannot be configured after #3022

### ISSUE THREAD

**Issue by neko-kai** [scalameta/scalafmt#3026]
```
version = 3.3.1

rewrite.rules = [RedundantBraces, RedundantParens]
rewrite.redundantBraces.methodBodies = false // remove braces only in interpolations
rewrite.redundantBraces.generalExpressions = false // remove braces only in interpolations
rewrite.redundantBraces.includeUnitMethods = false
rewrite.redundantBraces.stringInterpolation = true
rewrite.redundantBraces.parensForOneLineApply = true
```

## Problem

The intention of the above configuration was to remove braces only in interpolations and single-line applications, however after #3022 `val`/`var`/`type` defs braces are also modified - but without an option to disable it as for `def` defs.

## Expectation

Expected `rewrite.redundantBraces.methodBodies` to also affect `val`/`var`. Often the choice between `val` & `def` affects only performance, not semantics, so it's unexpected for braces to change when switching between them.

## Proposal

However, `methodBodies` option cannot logically affect `type` definitions. The solutions, in order of increasing complexity, could be:

* Simplistic: Rename `methodBodies` option to `definitions`. Deprecate & alias old name.

* Simple: Add `defnBodies` option alongside `methodBodies`.

* Complex: Remodel option into an array similar to `danglingParentheses.exclude`:
    ```
    rewrite.redundantBraces.exclude = [def, val, var, type, macro]
    // default: rewrite.redundantBraces.exclude = []
    ```

**Comment by kitbellew** [comment]
i think you assumed that this rule is fully configurable, but it's not. there are some constructs that will be rewritten if the rule is enabled, regardless of any other parameter.

as to method bodies, this parameter should have applied to methods with parameters only, otherwise they look like variables, as you surmised.

**Comment by neko-kai** [comment]
Well, it was configurable enough for the above up until #3022. Dropping the rule entirely would allow upgrading without a diff, but would not restore the ability to specify the style of preferring braces for multi-line definitions (wheter def or val), but removing otherwise clearly redundant braces.

**Comment by kitbellew** [comment]
multi-line seems to be the key. perhaps what you need is: https://scalameta.org/scalafmt/docs/configuration.html#inserting-braces

**Comment by neko-kai** [comment]
@kitbellew 
You're right, thank you! Setting
```
rewrite.redundantBraces.maxLines = -1 // `0` still causes diffs oddly enough
```
successfully removed the diff on upgrading.

**Comment by kitbellew** [comment]
> @kitbellew You're right, thank you! Setting
> 
> ```
> rewrite.redundantBraces.maxLines = -1 // `0` still causes diffs oddly enough
> ```
> 
> successfully removed the diff on upgrading.

glad you found what you were looking for.

about  0: because the way `maxLines` was originally implemented really means `max line breaks`.
