### ISSUE TITLE
error: missing version (current 3.3.1)

### ISSUE THREAD

**Issue by Arizard** [scalameta/scalafmt#3053]
- **Version**: 3.3.1
- **Integration**: None (CLI)
- **Configuration**: None
- Installed via Coursier

## Steps

Run `scalafmt` command in terminal. Current directory is a new scala3 project (`scala/scala3.g8`).

## Problem

I get this output:
```
error: missing version (current 3.3.1)
```

I don't know what causes this, I'm sure it's something simple but I can't find any info on this error.

The reason I am running this in terminal is because I am troubleshooting a neovim plugin (ALE) which has scalafmt support.

**Comment by tgodzik** [comment]
Thanks for reporting! Do you have `version=...` set in your `scalafmt.conf` file?

**Comment by Arizard** [comment]
I did not, thanks for the tip! I got it working by adding `version = 3.3.1`. I noticed that the error message for `runner.dialect` is more descriptive. Maybe I can try creating a PR to improve the error message for `version`.

```
Default dialect is deprecated; use explicit: [sbt0137,sbt1,scala211,scala212,scala212source3,scala213,scala213source3,scala3]
Also see https://scalameta.org/scalafmt/docs/configuration.html#scala-dialects"
```

**Comment by tgodzik** [comment]
I think that's a good idea!
