### ISSUE TITLE
Clarify documentation regarding regex usage

### ISSUE THREAD

**Issue by IndiscriminateCoding** [scalameta/scalafmt#3063]
- **Configuration**:
```
version = 3.3.1
runner.dialect = scala213
newlines.topLevelStatementBlankLines = [{ blanks { after = 1 }, regex = "Import" }]
```

## Steps

Given two source files:
```scala
package a

import T.T
sealed trait A

object A
```

```scala
package a

import T.T
import T.U
sealed trait B

object B
```

When I run scalafmt like this:

```bash
sbt scalafmtCheckAll
```

## Problem

```
[warn] scalafmt: <redacted>/src/main/scala/a/B.scala isn't formatted properly!
[error] scalafmt: 1 files must be formatted
```

## Expectation

Reading through documentation I can't say why this regex matches two imports but not one.
Considering that this is not a bug (see #3059) I believe documentation should be improved, because even contributor in aforementioned ticket had difficulties saying what exactly this secret option is.

**Comment by kitbellew** [comment]
it looks like you haven't been able to determine from the documentation what the parameter is. i will tell you what it is but in return could you explain why it's not clear?

the parameter is `minBreaks`.

**Comment by kitbellew** [comment]
so, can you help me understand how to clarify the documentation?

**Comment by IndiscriminateCoding** [comment]
@kitbellew while reading `minBreaks` documentation *having this example on my mind* it looks kinda obvious.

However, when I read it before it doesn't "clicked" for me that this is about multiple statements (and not about "line breaks as empty lines" or "line breaks inside one and only one statement").
Also, the phrase "sets the minimum number of line breaks ... <skipped>" has left an impression that this settings **sets** line breaks in a sense that the code is modified with this line breaks.

I think it would be very helpful (at least from my POV) to (a) mention that all fields are statement matchers (and not code modifiers) and (b) have some example for this specific setting.

Anyway, thanks for your help and feel free to close this ticket if you think the docs is clear enough as it is.

**Comment by kitbellew** [comment]
while i don't always provide examples, there is in fact an example for this specific setting.

**Comment by kitbellew** [comment]
> However, when I read it before it doesn't "clicked" for me that this is about multiple statements...

from the documentation: _imports and exports are processed as a group of consecutive statements_

> I think it would be very helpful (at least from my POV) to (a) mention that all fields are statement matchers

let me think about this.
