### ISSUE TITLE
Binpacking not working for slightly more complex case

### ISSUE THREAD

**Issue by ekrich** [scalameta/scalafmt#3066]
This template is a guideline, not a strict requirement.
- **Version**: 3.3.2
- **Integration**: CLI
- **Configuration**:
```
# binpack related
binPack.preset = true
binPack.parentConstructors = keep
binPack.unsafeCallSite = oneline
binPack.literalsExclude = []
binPack.literalsIncludeSimpleExpr = true
```

## Steps

When I run scalafmt either in VSCode or via 2.13 CLI script.
See: https://github.com/scala-js/scala-js/pull/4522

## Problem

Scalafmt formats code and diff looks like this:

```scala
   private final val SMALL_VALUES = Array(
-    ZERO, ONE, new BigInteger(1, 2), new BigInteger(1, 3),
-    new BigInteger(1, 4), new BigInteger(1, 5), new BigInteger(1, 6),
-    new BigInteger(1, 7), new BigInteger(1, 8), new BigInteger(1, 9), TEN)
+      ZERO,
+      ONE,
+      new BigInteger(1, 2),
+      new BigInteger(1, 3),
+      new BigInteger(1, 4),
+      new BigInteger(1, 5),
+      new BigInteger(1, 6),
+      new BigInteger(1, 7),
+      new BigInteger(1, 8),
+      new BigInteger(1, 9),
+      TEN
+  )
```

## Expectation

I would like to see similar to the original format but aligned to col 80.

Ideally the `ZERO, ONE ...` would move up next to `Array(` but I am not sure if binpacking preserves line breaks or not but if it does that could be changed after formatting.

**Comment by kitbellew** [comment]
@ekrich please read this section (several parameters), this is what's taking precedence over binpacking here: https://scalameta.org/scalafmt/docs/configuration.html#newlines-config-style-formatting

i think you should start with [`preset = scalajs`](https://github.com/scalameta/scalafmt/blob/master/scalafmt-core/shared/src/main/scala/org/scalafmt/config/ScalafmtConfig.scala#L281) in your config.
