### ISSUE TITLE
Splitting link tag in scaladoc causes warning and link fails to render

### ISSUE THREAD

**Issue by ekrich** [scalameta/scalafmt#3070]
This template is a guideline, not a strict requirement.
- **Version**: 3.3.2

## Problem

When running scalafmt if the documentation has some javadoc style links which are supported and if they are split across lines after formatting then scaladoc warns and the generated scaladoc does not render the link.

Input:
```
/**
 * Some text and {@link foo}
 */ 
```
Output:
```
/**
 * Some text and {@link
 * foo}
 */ 
```

## Workaround

I think if they are converted to scaladoc style [[link name]] they will not split. 

My code base was ported from Java so this is a large task and the new doc formatting breaks from the previous behavior.

**Comment by ekrich** [comment]
I forgot this was upstream but could be used as a test case - https://github.com/scalameta/scalameta/issues/2552

**Comment by kitbellew** [comment]
if it ever gets fixed in the parser, the formatter will handle it, too. i will close this as duplicate.
