### ISSUE TITLE
Starting with v3.3.1 scalafmt formats boilerplate code in a weird way

### ISSUE THREAD

**Issue by satorg** [scalameta/scalafmt#3079]
See typelevel/cats#4116

**Configuration**:
```
version=3.3.3
align.openParenCallSite = true
align.openParenDefnSite = true
maxColumn = 120
continuationIndent.defnSite = 2
assumeStandardLibraryStripMargin = true
danglingParentheses.preset = true
rewrite.rules = [AvoidInfix, SortImports, RedundantParens, SortModifiers]
docstrings = JavaDoc
newlines.afterCurlyLambda = preserve
docstrings.style = keep
docstrings.oneline = unfold

runner.dialect = scala213source3
fileOverride {
  "glob:**/*.sbt" {
    runner.dialect = sbt1
  }
  "glob:**/src/{main,test}/scala-2.12/**" {
    runner.dialect = scala212source3
  }
  "glob:**/src/{main,test}/scala-3.x/**" {
    runner.dialect = scala3
  }
}
project.excludeFilters = [
  "scalafix/*"
]

```

## Problem

Scalafmt formats code in boilerplate blocks which is not expected to happen.
Furthermore, the formatted results look pretty ugly: the formatting breaks block margins:
https://github.com/typelevel/cats/pull/4116/files?diff=unified&w=0#diff-dedd06aeff4542c5b99c68ad8ee7fecde2588c7adba68944521cda08e709aa83L153-R154

## Expectation

The boilerplate code blocks should not be formatted by default since the result code can be very different from the source template.

Or at least there should be an option to disable it in configs.

**Comment by kitbellew** [comment]
what is boilerplate code?

**Comment by satorg** [comment]
@kitbellew I mean code templates for sbt-boilerplate plug-in

**Comment by kitbellew** [comment]
Сергей, я понятия не имею, что это такое. с точки зрения scala, что это за конструкция?
