### ISSUE TITLE
Update to metaconfig 10

### ISSUE THREAD

**Issue by virusdave** [scalameta/scalafmt#3098]
Currently there's a dependency on Metaconfig 9.x.x, but due to [this issue](https://github.com/scalameta/metaconfig/pull/154), a newer version is available which vendors the underlying `pprint` library, which recently went through binary-incompatible changes.  

What this means is that right now, scalafmt isn't usable in a context where centralized dependency management & resolution requires putting the latest version of pprint into the classpath.  Updating the dependency _should_ be sufficient to solve this problem (and would merit a bug report to metaconfig if this isn't the case).

Requesting an update to dependency version and publish with that change (ideally backported to 3.3.x latest release).

Thank you!  😍

**Comment by kitbellew** [comment]
and how will this work with contexts where only 0.9.x versions are available, and 0.10.0 is not yet available? :)

have you considered using a standalone version: https://scalameta.org/scalafmt/docs/installation.html#standalone
