### ISSUE TITLE
Feature Request: Is it possible to sort functions/methods and value/variables alphabetically?

### ISSUE THREAD

**Issue by calvinlfer** [scalameta/scalafmt#3100]
Is it possible to sort functions/methods and value/variables alphabetically? I would love this feature :)

**Comment by kitbellew** [comment]
generally, i am close to closing as dangerous or impossible; you could have better luck with scalafix which (unlike scalafmt) "understands" what inside the expression semantically. @tgodzik wdyt?

for instance, what to do here:
```
val foo = 1
val bar = foo + 1
```
or here
```
import Foo
val bar = Foo.bar
import bar._
```

**Comment by tgodzik** [comment]
It could be possible with defs on the same level, but nothing more. Vals I agree are too dangerous.

Though with scalafmt this might be quite difficult in the current infrastructure anyway, no? Maybe really a syntax rule in scalafix?
