### ISSUE TITLE
Illegal Scala 3 code is produced when `align.inInterpolation = true`

### ISSUE THREAD

**Issue by Atry** [scalameta/scalafmt#3113]
- **Version**: 3.4.2
- **Integration**: VSCode & Metals
- **Configuration**:
```
runner.dialect = scala3
version = "3.4.2"
maxColumn = 80
align.inInterpolation = true
```

## Steps

Given code like this:
```scala

val s = raw"""
          ${
            if true then
              println()
              "1"
            else
              "2"
          }
          ${if false then "3" else "4"}
        """
```

When I run scalafmt from `Format Document` command in VSCode:
## Problem

Scalafmt formats code like this:
```scala

val s = raw"""
          ${if true then
               println()
               "1"
             else "2"}
          ${if false then "3" else "4"}
        """
```

and the following compile error is raised by the Scala 3 compiler:

```
end of statement expected but 'else' found
```

## Expectation

I would like the formatted output to compile

**Comment by kitbellew** [comment]
looks like scala 3 must use a different `newlines.inInterpolation` setting. i can add a check and use `oneline` instead.
