### ISSUE TITLE
Cannot format interpolation and escape quotation: `s"\"$t\""`

### ISSUE THREAD

**Issue by qiujiangkun** [scalameta/scalafmt#3122]
- **Version**: latest bundled
- **Integration**: IntelliJ
- **Configuration**:
```
version = 2.0.1
maxColumn = 100
```

## Steps

Given code like this:
```scala
val t = 1
val s = s"\"$t\""

```

When I run scalafmt like this:

```bash
scalafmt
```

## Problem

Scalafmt formats code like this:
![image](https://user-images.githubusercontent.com/33482468/153743874-953db5b1-66a3-4899-a3b2-0fcf7cc38579.png)

## Expectation

I would like the formatted output to look like this:
```scala
val t = 1
val s = s"\"$t\""
```

**Comment by kitbellew** [comment]
> version = 2.0.1

can you please verify with the latest version and reopen if still relevant? we don't issue hotfixes to old versions.

**Comment by qiujiangkun** [comment]
Sorry that I didn't find the config file used in Intellij Idea. I just find the configuration and updated the version above

**Comment by kitbellew** [comment]
this is not the latest version, @qiujiangkun

**Comment by qiujiangkun** [comment]
Thanks. This version has no problems
```
version = "3.4.3"
runner.dialect = scala3
maxColumn = 100
align.preset = none
```

**Comment by kitbellew** [comment]
very good :) using the latest version is important.

**Comment by qiujiangkun** [comment]
https://youtrack.jetbrains.com/issue/SCL-19774
