### ISSUE TITLE
no indent for case statements in match clauses

### ISSUE THREAD

**Issue by bblfish** [scalameta/scalafmt#3123]
- **Version**: 3.4.3 (I am using it via the latest sbt-typelevel )

## Steps

Given valid Scala 3 code like this:
```scala
list match
case head :: tail => fn(head) :: complex( 
       tail, parameters 
     )
case Nil => Nil
```

When I run scalafmt like this:

```bash
scalafmt
```

## Problem

Scalafmt formats code like this:
```scala
list match
    case head :: tail => f(head):: complex( 
           tail, parameters 
        )
    case Nil => Nil
```

i.e. it indents the `case` clauses.

## Expectation

I would like the formatted output to be as in the original, without indentation on the `case`
statements, as that is just wasted horizontal space. There is no need for the indentation here, as the `case` statement is a keyword indentation.

Other languages like Haskell don't use the case keyword so it makes sense to have
indentation
```haskell
case x of 
     1 ->  "A"
     2 ->  "B"
     3 ->  "C"
```
But in Scala the `case` **is** the indentation (5 chars wide) and the above would look like 

```scala
x match 
case 1 ->  "A"
case 2 ->  "B"
case 3 ->  "C"
```

So we see that by deleting the `case` keywords we have the same as in Haskell.

## Workaround

Don't know

## Notes

See also..

**Comment by kitbellew** [comment]
@bblfish we discussed this on discord, this would require adding a new parameter. which in itself wouldn't be a huge problem, but this modification of your code unfortunately is:
```
val a = list match
case head :: tail =>
  fn(head) :: complex(
    tail,
    parameters
  )
case Nil => Nil
```

**Comment by bblfish** [comment]
I think I would have written you example above something like this
```scala
val a = list match
   case head :: tail =>
     fn(head) :: complex(
       tail,
       parameters
     )
   case Nil => Nil
```
because one has to indent after an `=`
```scala
val a = 
   list match
   case head :: tail =>
     fn(head) :: complex(
       tail,
       parameters
     )
   case Nil => Nil
```
I checked that it compiles 
```scala
val list = List(1,2,3)
def fn(x: Int) = x + 1
def complex(l: List[Int], args: String*) = l.map(_ * 2)
val a = list match
   case head :: tail =>
     fn(head) :: complex(
       tail,
       "ignore me"
     )
   case Nil => Nil
 ```

**Comment by kitbellew** [comment]
> I think I would have written you example above something like this
> 
> ```scala
> val a = list match
>    case head :: tail =>
>      fn(head) :: complex(
>        tail,
>        parameters
>      )
>    case Nil => Nil
> ```
that's the problem. no, you don't have to indent after val because your match is on the same line, and you are asking not to indent after match.

writing a rule which indents after val if there's a match is possible although highly nontrivial. however, i guarantee that within a month of releasing this change, someone will file a complaint about the extra indent caused by val when they asked for no indent after match.

so, which of the evils should we choose?

**Comment by bblfish** [comment]
it seems to compile ok without indentation after the `val a`.

```scala
scala> val list = List(1,2,3)
     | def fn(x: Int) = x + 3
     | def complex(l: List[Int], args: String*) = l.map(_ * 7)
     | val a = list match
     | case head :: tail =>
     |   fn(head) :: complex(
     |     tail,
     |     "ignore me"
     |   )
     | case Nil => Nil
     |
val list: List[Int] = List(1, 2, 3)
def fn(x: Int): Int
def complex(l: List[Int], args: String*): List[Int]
val a: List[Int] = List(4, 14, 21)
```

I can see how this also makes sense. With the color highlighting it is quite easy to see what is going on.
