### ISSUE TITLE
Words in Scaladoc are truncated unexpectedly when running Scalafmt

### ISSUE THREAD

**Issue by Atry** [scalameta/scalafmt#3125]
This template is a guideline, not a strict requirement.
- **Version**: 3.4.2
- **Integration**: VSCode
- **Configuration**:
```
runner.dialect = scala3
version = "3.4.2"
maxColumn = 80
align.inInterpolation = true
newlines.inInterpolation = oneline
```

## Steps

Given code like this:
```scala
/** Title
  * @example
  *   {{{
  *   println("example")
   some.example(foo)
  *   }}}
  */
def foo = ()
```

When I run scalafmt from VSCode

## Problem

Scalafmt formats code like this:
```scala
/** Title
  * @example
  *   {{{
  *   println("example")
  *   e.example(foo)
  *   }}}
  */
def foo = ()
```

## Expectation

I would like the formatted output to look like this:
```scala
/** Title
  * @example
  *   {{{
  *   println("example")
  *   some.example(foo)
  *   }}}
  */
def foo = ()```

**Comment by kitbellew** [comment]
> ```scala
> /** Title
>   * @example
>   *   {{{
>   *   println("example")
>    some.example(foo)
>   *   }}}
>   */
> ```

This is not valid scaladoc. The leading asterisk is required.

**Comment by Atry** [comment]
I create a new bug report including the `*` in the example at https://github.com/scalameta/scalafmt/issues/3128
