### ISSUE TITLE
Types product support in scala213source3

### ISSUE THREAD

**Issue by tellnobody1** [scalameta/scalafmt#3140]
- **Version**: 3.4.3
- **Integration**: SBT
- **Configuration**:
```
version = 3.4.3
runner.dialect = scala213source3
```

### Steps

Given code like this:
```scala
1: trait A = B
2:   & C
3:   & Has[D]
4:
```

When I run scalafmt like this:

```bash
sbt scalafmtAll
```

### Problem

Error on line 4:
```scala
error: [dialect scala213source3] type application is not allowed for postfix operators

^
```

### Expectation

No errors and code is not formatted.

### Workaround

Use old `with` keyword instead of `&`.

### Steps

Given code like this:
```scala
object A extends B & C {
}
```

When I run scalafmt like this:

```bash
sbt scalafmtAll
```

### Problem

Error:
```scala
error: [dialect scala213source3] ; expected but identifier found
object A extends B & C {
                   ^
```

### Expectation

No errors and code is not formatted.

### Workaround

Use old `with` keyword instead of `&`.

**Comment by kitbellew** [comment]
dialects are defined in scalameta, not scalafmt.
