### ISSUE TITLE
ScalafmtSbtReporter$ScalafmtSbtError: scalafmt: Search state exploded

### ISSUE THREAD

**Issue by AlexITC** [scalameta/scalafmt#3141]
This template is a guideline, not a strict requirement.
- **Version**: 3.4.3
- **Integration**: sbt
- **Configuration**: In the linked repo

## Steps

Unfortunately, I haven't had enough time to isolate the problem but I'm linking a Scala [file](https://github.com/wiringbits/scala-webapp-template/commit/06c0e6066900c71383b6a2f46644a9702f727f51) that crashes scalafmt, the problem seems related to snippets like:

```scala
set("&$disabled", CSSProperties()
```

Going to the linked repository and running `sbt scalafmtCheckAll` reproduces the problem.

## Problem

Scalafmt formats code like this:
```
[info] scalafmt: Formatting 45 Scala sources (/home/dell/projects/mine/scala-webapp-template/web)...
[error] org.scalafmt.sbt.ScalafmtSbtReporter$ScalafmtSbtError: scalafmt: Search state exploded on '(∙Colors[3824:3830]', line 91 [/scala-webapp-template/web/src/main/scala/net/wiringbits/AppTheme.scala]
[error] (web / Compile / scalafmt) org.scalafmt.sbt.ScalafmtSbtReporter$ScalafmtSbtError: scalafmt: Search state exploded on '(∙Colors[3824:3830]', line 91 [/scala-webapp-template/web/src/main/scala/net/wiringbits/AppTheme.scala]

```

## Workaround

I have had to disable scalafmt for such file.

**Comment by tusharmath** [comment]
Facing the same issue. Trying to re-create a build will post it here shortly.

**Comment by tusharmath** [comment]
Here is the repro — https://github.com/dream11/zio-http/runs/5373382741?check_suite_focus=true#step:6:50

**Comment by kitbellew** [comment]
@AlexITC @tusharmath where in the _documentation_ did you look fo ways to deal with this? i will make sure the answer is there.

**Comment by AlexITC** [comment]
@kitbellew https://scalameta.org/scalafmt/docs/configuration.html#-format-off

**Comment by tusharmath** [comment]
The other thing that I have observed is that it is happening on line number 267 in `Http.scala`. It doesn't matter what's on that line number, even if there is a comment, scalafmt throws this exception.
