### ISSUE TITLE
Default preset breaks string interpolation

### ISSUE THREAD

**Issue by Ryanward02** [scalameta/scalafmt#3142]
This template is a guideline, not a strict requirement.
- **Version**: 0.5
- **Integration**: IntelliJ
- **Configuration**:
```
version = 2.0.1
maxColumn = 100
```

## Steps

Given code like this:
```Scala

object w {
  def get(): String = “world”
}
val x: String = s”hello ${w.get}”
```

When I run scalafmt like this:

```bash
sbt scalafmt
```

## Problem

Scalafmt formats code like this:
```scala

val x: String = s”hello $ { w.get } ”

```

## Expectation

I would like the formatted output to look like this:
```scala
val x: String = s”hello ${ w.get } ”
```

scalafmt should, at a minimum, leave the initial brace next to the $, as code does not compile after running scalafmt.

## Workaround

I've found that by...

concatenation of strings fixes the issue, but string interpolation is very useful, not to mention cleaner and algorithmically less complex

## Notes

See also..

**Comment by tgodzik** [comment]
Thanks for reporting! `2.0.1` is a very old version, could try the snippet with the newest one?
