### ISSUE TITLE
`indentOperator` doesn't apply to union and intersection type expressions

### ISSUE THREAD

**Issue by martingd** [scalameta/scalafmt#3153]
## Configuration ##
```
version = "3.4.3"
runner.dialect = scala3

newlines.source = keep

indentOperator.excludeRegex = "^(&|\\||&&|\\|\\|)$"
indentOperator.exemptScope = aloneArgOrBody
```

## Problem ##
Given the above configuration and given this code:

```scala
val x =
  1 |
  2 |
  3 |
  4

type T =
  Byte |
  Short |
  Int |
  Long |
  Double
```

when I run scalafmt via CLI like this: `scalafmt test.scala --stdout`

The output is:

```scala
val x =
  1 |
  2 |
  3 |
  4

type T =
  Byte |
    Short |
    Int |
    Long |
    Double
```

## Expectation
I would like the formatted output to keep its original indentation:
```scala
val x =
  1 |
  2 |
  3 |
  4

type T =
  Byte |
  Short |
  Int |
  Long |
  Double
```

However, it seems the `indentOperator` configuration only applies to value expressions and not type expressions (e.g., union types).

## Workaround
None.

**Comment by kitbellew** [comment]
@martingd what if you used scala213 dialect instead? will that be formatted differently?

**Comment by kitbellew** [comment]
scalafmt is not a compiler. it uses scalameta to parse the code, and for scala2 the parser produces a different tree which is handled correctly, which you confirmed for me. so, need to change the parser.

**Comment by martingd** [comment]
@kitbellew I understand it's not a compiler. :)
I think I misunderstood what it was you would obtain by trying out the scala213 dialect.
