### ISSUE TITLE
`Search state exploded` even though `// format: off` is used

### ISSUE THREAD

**Issue by robstoll** [scalameta/scalafmt#3159]
## Configuration (required) ##
```
version = 3.4.3
```

## Command-line parameters (required) ##
scalafmtAll

## Steps
deeply nested function calls so `Search state exploded` is expected

## Problem

looks like starting from 3.0.0 scalafmt ignores `// format: off`
I don't have the problem with 2.7.5

## Expectation
Also scalafmt 3.x takes `// format: off` into account

## Workaround
downgrade to 2.7.5 :(

## Notes
Interesting side note. if I remove the `// format : off` then it does not run into the `Search state exploded` problem

**Comment by kitbellew** [comment]
will you close this issue devoid of any actionable examples, or should i?

**Comment by tgodzik** [comment]
> will you close this issue devoid of any actionable examples, or should i?

Let's try to keep a more positive tone :sweat_smile: 

But I do agree that we need any kind of reproduction, otherwise it's really hard to fix the problem. Did you also try the other options: https://scalameta.org/scalafmt/docs/configuration.html#disabling-or-customizing-formatting

**Comment by kitbellew** [comment]
i can add "please" 😀

apart from missing examples, the author uses sbt and not CLI parameters, as requested in the issue template.

**Comment by robstoll** [comment]
Nice reaction 😀 I thought the problem at hand does not need a sample since it looks to me, that the implementation since 3.0.0 tries to analyze a format off-block. Is this intended? If not the easiest reproduction would be to put some code scalafmt is not able to format (I don't know any but I am sure you do) in a format off block and check in the test that scalafmt does not crash.
I hope this idea helps, otherwise I will try to come up with a minimal sample.

**Comment by kitbellew** [comment]
@robstoll you're correct that the formatter does analyze that block but that didn't change in any version, it's always been done like that. of course, the reason for that is that the excluded block affects formatting of the code around it.

you keep referring to version 3.0.0; in addition to providing an example, can you please verify that the version you're testing with is actually the latest one?

**Comment by robstoll** [comment]
It also happens with 3.4.3. the regression is in 3.0.0 (no error in 2.7.5)
In my particular case, I exclude the whole file. So there is no point in analysing it. Maybe a separate suppress flag for a whole file would be helpful in such situations. I'll try to come up with a reproduction sample

**Comment by robstoll** [comment]
Oh... Isn't there an exclude filter? That would be the perfect workaround for me. I'll check later. Feel free to close this issue. I can still try to come up with a sample if it helps to reduce/fix the "search space exploded" problem.

**Comment by kitbellew** [comment]
yes, there are exclude filters you can specify in the config file.

but I'm intrigued: what about this file that makes you exclude it (even though it successfully formats) and makes the formatter fail?

**Comment by robstoll** [comment]
The file deals with tuples. It's generated and contains 22 functions with 2 to 23 type parameters. At some point, scalafmt puts every type parameter on an own line, same same for the parameters, bloating the functions up to a point where they are basically unreadable. If I would be able to increase the max column for this file only (maybe this option exists) then it might work better.

**Comment by kitbellew** [comment]
we usually exclude directories which contain generated code. you can try other parameters, such as newlines.source=keep.

**Comment by robstoll** [comment]
closing this as the exclude filter is the perfect workaround
