### ISSUE TITLE
Newline before multi-line can't be "kept" as in source

### ISSUE THREAD

**Issue by iuliand-db** [scalameta/scalafmt#3173]
## Configuration (required) ##
```
version = 3.4.3

runner.dialect = scala212
docstrings.style = keep
maxColumn = 100

newlines.source = keep
newlines.beforeMultiline = keep
# newlines.forceBeforeMultilineAssign = never
```

## Command-line parameters (required) ##

When I run scalafmt via CLI like this: `-c scalafmt.conf test-scalafmt.scala`

## Steps

Given code like this:
```scala
class Foo {
  def foo(): Unit = {
    // foo
    val foo = if (true) {
        ""
      } else {
        "a"
      }
  }
}
```

## Problem

Scalafmt formats code like this:
```scala
class Foo {
  def foo(): Unit = {
    // foo
    val foo =
      if (true) {
        ""
      } else {
        "a"
      }
  }
}
```

## Expectation

I would like the formatted output to look like this (not change the val line):
```scala
class Foo {
  def foo(): Unit = {
    // foo
    val foo = if (true) {
      ""
    } else {
      "a"
    }
  }
}

```

## Workaround

No workaround found after fiddling with settings for several hours :(

**Comment by kitbellew** [comment]
this parameter usually keeps a newline while you have the absence of one, that is not guaranteed to be kept.

also, there's a limit to what will be kept. if you'd like the formatter to keep all newlines exactly as they are, why do you run it?

**Comment by iuliand-db** [comment]
@kitbellew I don't want to keep all newlines as they are, I am trying to upgrade a 3 million LOC code base from scalafmt 2.0 to 3.4.3, while minimizing formatting changes. Seems like this way of formatting was "correct" a while back.

**Comment by kitbellew** [comment]
it may have been but now if with else and try with catch are not. we try to minimize changes but we occasionally do introduce changes and not just bug fixes.

**Comment by iuliand-db** [comment]
I understand that, but the line is not longer than `maxColumn`. It doesn't need to add a new line in this case, despite using `newlines.source = keep` (or removing the config which according to the docs would enable the classic mode). Seems like it could be a bug.
