### ISSUE TITLE
No way to keep single-line comments unchanged

### ISSUE THREAD

**Issue by iuliand-db** [scalameta/scalafmt#3174]
It looks like there's no way to prevent scalafmt from inserting a space between `//` and the first character of the comment. To make things more interesting, top-level comments are not affected (they are left alone), but comments nested inside some other entity get the extra space.

## Configuration (required) ##
```
version = 3.4.3

runner.dialect = scala212
docstrings.style = keep
maxColumn = 100

newlines.source = keep
newlines.beforeMultiline = keep
# newlines.forceBeforeMultilineAssign = never
```

## Command-line parameters (required) ##

When I run scalafmt via CLI like this: `-c scalafmt.conf test-scalafmt.scala`

## Steps

Given code like this:
```scala
//foo
//----
class Foo {
  //foo
  //---
  def foo() = ???
}
```

## Problem

Scalafmt formats code like this:
```scala
//foo
//----
class Foo {
  // foo
  // ---
  def foo() = ???
}
```

## Expectation

I would like the formatted output to look like this (unchanged):
```scala
//foo
//----
class Foo {
  //foo
  //---
  def foo() = ???
}
```

## Workaround

No workaround.

**Comment by kitbellew** [comment]
unindented (not top level) comments are handled differently because many IDEs comment code out that way.

and no, there's no parameter to disable adding a space in indented comments.
