### ISSUE TITLE
Scalafmt Import rule sorts given alphabetically.

### ISSUE THREAD

**Issue by SimY4** [scalameta/scalafmt#3189]
## Configuration (required) ##
```
version = "3.5.2"
runner.dialect = Scala3
rewrite.rules = [Imports]
rewrite.imports.sort = scalastyle
```

## Command-line parameters (required) ##

When I run scalafmt via CLI like this: 
```
scalafmt -s .scalafmt.conf NotImportant.scala
```

## Steps

Given code like this:
```scala
package example

import model.{ SomeClass, given }

class NotImportant {
}
```

## Problem

Scalafmt formats code like this:
```scala
package example

import model.{ given, SomeClass }

class NotImportant {}
```

## Expectation

I would like the formatted output to look like this:
```scala
package example

import model.{ SomeClass, given }

class NotImportant {}
```

## Notes

givens are considered wildcard imports and should remain being last in the list of import group.

**Comment by kitbellew** [comment]
@SimY4 can you please explain how a `given` is like a wildcard import?

specifically, for regular wildcard imports, they only affect renames (`a => b`) and unimports (`c => _`) but not any other imports, both in sorting and in ability to expand a group.

**Comment by SimY4** [comment]
@kitbellew It's what the compiler would tell you if you put the given in not the rightmost position.

**Comment by kitbellew** [comment]
> When I run scalafmt via CLI like this:
> 
> ```
> addCommandAlias("fmt", "; root/scalafmtSbt; root/scalafmtAll")
> ```

this is not CLI, this is probably `sbt`; the intention was to use the actual `scalafmt` binary: https://scalameta.org/scalafmt/docs/installation.html#cli

**Comment by SimY4** [comment]
@kitbellew I'm not sure what outcome you're aiming here. The issue template says:

> - if the problem does not present via CLI, instead please submit the issue in
>  the appropriate tool's repository
>  - for instance, if the tool is `sbt` with the `sbt-scalafmt` plugin: please
>    submit in `sbt-scalafmt` and include scalafmt parameters from `build.sbt`
>    and the `sbt` command used

**Comment by kitbellew** [comment]
> @kitbellew I'm not sure what outcome in this conversation you're aiming for here. The issue template says:
> 
> > * if the problem does not present via CLI, instead please submit the issue in
> >   the appropriate tool's repository
> > * for instance, if the tool is `sbt` with the `sbt-scalafmt` plugin: please
> >   submit in `sbt-scalafmt` and include scalafmt parameters from `build.sbt`
> >   and the `sbt` command used
> 
> I used sbt-scalafmt and I provided the way I invoke it.

this repository is not for sbt-scalafmt.

**Comment by SimY4** [comment]
The scalafmt command would be:

```
scalafmt -s .scalafmt.conf NotImportant.scala
```
