### ISSUE TITLE
Improve ScalafmtDynamicError messages

### ISSUE THREAD

**Issue by kitbellew** [scalameta/scalafmt#3192]
Influenced by https://youtrack.jetbrains.com/issue/SCL-20123

**Comment by unkarjedy** [comment]
Can we publish a version with this in order we can close https://youtrack.jetbrains.com/issue/SCL-20123?

**Comment by unkarjedy** [comment]
@kitbellew 
I might be out of context, but how upgrading to new scalameta parser can block publishing minor version with existing working code?
