### ISSUE TITLE
Indented if condition is incorrectly unindented

### ISSUE THREAD

**Issue by Katrix** [scalameta/scalafmt#3204]
## Configuration (required) ##
```
version = "3.5.2"
runner.dialect = scala3
```

NB: before submitting, please confirm that the problem is observed in the
*latest published* version of the formatter! We don't publish hotfixes for older
versions, and the problem you have observed in an older version may have already
been fixed.

## Command-line parameters (required) ##

When I run scalafmt via CLI like this: `scalafmt -i`

## Steps

Given code like this:
```scala
if
  val x = 4  
  4 == 3
then 5 
else 4
```

## Problem

Scalafmt formats code like this:
```scala
if
val x = 4  
4 == 3
then 5 
else 4
```

## Expectation

I would like the formatted output to look like this:
```scala
if
  val x = 4  
  4 == 3
then 5 
else 4
```

## Workaround

Disable scalafmt for the if condition with comments

**Comment by kitbellew** [comment]
@tgodzik is this a parser issue?

**Comment by dos65** [comment]
@kitbellew this code is parsed correctly. Looks like an issue with scalafmt
