### ISSUE TITLE
RedundantParens setting breaks sbt files

### ISSUE THREAD

**Issue by ckipp01** [scalameta/scalafmt#3234]
## Configuration (required) ##

Please paste the contents of your `.scalafmt.conf` file here:
```
version = 3.5.5
runner.dialect = scala213
preset = default
rewrite.rules = [RedundantParens]
```

## Command-line parameters (required) ##

```
scala-fmt build.sbt
```

## Steps

Given code like this:
```scala
lazy val foo = project

lazy val doThing = taskKey[Unit]("This does a thing")

ThisBuild / doThing := (foo / Compile / runMain)
  .toTask("exmple.Foo")
  .value
```

## Problem

Scalafmt formats code like this:
```scala
lazy val foo = project

lazy val doThing = taskKey[Unit]("This does a thing")

ThisBuild / doThing := foo / Compile / runMain
  .toTask("exmple.Foo")
  .value
```

## Expectation

Removing the parens in this example isn't redundant, but rather breaks your build. For example after this is done, your build definition can't load.

```
/Users/ckipp/Documents/scala-workspace/sbt-sanity/build.sbt:14: error: overloaded method value / with alternatives:
  (taskAxis: sbt.ScopeAxis[sbt.internal.util.AttributeKey[_]])sbt.SlashSyntax.RichScope <and>
  (key: sbt.internal.util.AttributeKey[_])sbt.SlashSyntax.RichScope <and>
  [K](key: sbt.Scoped.ScopingSetting[K])K
 cannot be applied to (Unit)
ThisBuild / doThing := foo / Compile / runMain
                                     ^
[error] Type error in expression
[warn] Project loading failed: (r)etry, (q)uit, (l)ast, or (i)gnore? (default: r)
```

## Workaround

Ignore formatting here or revert

**Comment by kitbellew** [comment]
should be fixed in #3232, in 3.5.6. (although 3.5.6 has its own bug now, will fix shortly.)

**Comment by ckipp01** [comment]
Ahh, you're so speedy @kitbellew, thanks!

**Comment by ckipp01** [comment]
> @ckipp01 so, does it work in 3.5.6?

Ah sorry I didn't realize it was already released. The example code up above now is correct, it doesn't remove them. In my project where I hit on this it doesn't though, but I have a more involved config, so I need to figure out what exactly is causing it.
