### ISSUE TITLE
v3.5.7 native binary doesn't like its own version in the config

### ISSUE THREAD

**Issue by laughedelic** [scalameta/scalafmt#3237]
## Configuration

```
version = 3.5.7
...
```

## Command-line parameters / Steps

I tried installing the latest native binary, but it fails to run with this configuration:

```
►  curl --fail -Lo scalafmt-native https://github.com/scalameta/scalafmt/releases/download/v3.5.7/scalafmt-macos
►  chmod u+x scalafmt-native
►  ./scalafmt-native
error: invalid Scalafmt version.

This Scalafmt installation has version '0.0.0' and the version configured in '.scalafmt.conf' is '3.5.7'.
To fix this problem, add the following line to .scalafmt.conf:

version = '0.0.0'

NOTE: this error happens only when running a native Scalafmt binary.
Scalafmt automatically installs and invokes the correct version of Scalafmt when running on the JVM.
```

## Problem

- This happens with both macOS and Linux native binaries v3.5.7 (first observed on GitHub actions)
- JVM Scalafmt 3.5.7 installed via Coursier runs fine with the same configuration

## Expectation

Native launchers should be able to run with the same version in the config.

## Workaround

Setting version to `0.0.0` as the error message says, lets it run. But I don't think this is the intended usage.

**Comment by kitbellew** [comment]
@tgodzik @olafurpg can you help? i don't know how native images are created, or why, without any relevant changes to the build process, this happened since v3.5.5 a day before. i tried rerunning the v3.5.7 CI build, and it failed this time around.

**Comment by tgodzik** [comment]
I have never setup native image myself, but maybe it has something to do with the native image bump? Or anything from scala steward ? https://github.com/scalameta/scalafmt/pulls?q=is%3Apr+author%3Ascala-steward

**Comment by tgodzik** [comment]
Also, can id be something do with the way the CLI options are defaulted?

**Comment by kitbellew** [comment]
@laughedelic unfortunately, i don't know how this part of the process work. you can either wait until the next release (provided the same fluke doesn't happen), or use the artifacts attached to this CI build: https://github.com/scalameta/scalafmt/actions/runs/2384949653
