### ISSUE TITLE
Incorrect removal of parens around an inline match

### ISSUE THREAD

**Issue by mpilquist** [scalameta/scalafmt#3238]
Using 3.5.7, this:

```scala
(inline erasedValue[A] match
  case ... =>
).asInstanceOf[F[A]]
```

...is getting reformatted to:

```scala
inline erasedValue[A] match
  case ... =>
.asInstanceOf[F[A]]
```

Config:
```
version = "3.5.7"

style = default

runner.dialect = scala3

maxColumn = 100

docstrings.wrap = "no"

rewrite.rules = [
  AvoidInfix
  RedundantBraces
  RedundantParens
  AsciiSortImports
  PreferCurlyFors
]

rewrite.neverInfix.excludeFilters = [until
  to
  by
  eq
  ne
  "should.*"
  "contain.*"
  "must.*"
  in
  be
  taggedAs
  thrownBy
  synchronized
  have
  when
  size
  theSameElementsAs]
```

Example impact: https://github.com/scodec/scodec/pull/404/files

**Comment by kitbellew** [comment]
@mpilquist 
- did this work in v3.5.4 or v3.5.3?
- sometimes the nuance is in the specific language expression, so next time please provide actual failing code rather than `...`

**Comment by mpilquist** [comment]
It worked in 3.5.2. We couldn't upgrade to 3.5.3 due to https://github.com/scalameta/scalafmt/issues/3215.

Please see the linked PR that shows the exact expressions which are being reformatted incorrectly. Specifically, all the reformatting in this file: https://github.com/scodec/scodec/pull/404/files#diff-2cbd14928a4d64cf8f552130337ddf77af2c33fcd65fcebae41b1f06e3c789c3
