### ISSUE TITLE
Feature Request: Remove space between Annotation and Constructor Parameters

### ISSUE THREAD

**Issue by Rocketeer007** [scalameta/scalafmt#3260]
## Configuration (required) ##

```
version = 3.5.8
runner.dialect = scala213

#preset = IntelliJ

maxColumn = 150
docstrings.style = keep
#docstrings.style = SpaceAsterisk
docstrings.wrap = no
docstrings.blankFirstLine = yes
docstrings.forceBlankLineBefore = false

importSelectors = singleLine

optIn.configStyleArguments = true

align.openParenDefnSite = true
align.closeParenSite = true

newlines.source = keep
newlines.beforeMultiline = keep
newlines.topLevelStatementBlankLines = [
  {
    blanks { before = 0 }
  }
]

rewrite.rules = [AvoidInfix]
rewrite.neverInfix.excludeFilters."+" = [ "map", "forward", "publish" ]

align.preset = none
```

## Steps

Given code like this:
```scala
class MyClass @Inject()(parameter1: String, parameter2: String)
```

## Problem

Scalafmt formats code like this:
```scala
class MyClass @Inject() (parameter1: String, parameter2: String)
```

## Expectation

I would like the formatted output to look like this:
```scala
class MyClass @Inject()(parameter1: String, parameter2: String)
```

## Notes

This appears to be a deliberate decision from the project maintainers (see https://github.com/scalameta/scalafmt/pull/1516, and the discussion on https://github.com/scalameta/scalafmt/issues/618), however, this goes against the current rules of my project, and I would very much like to apply Scalafmt without having to change this particular convention.

If the project maintainers would be amenable, I'll create a PR to add a configuration setting for this particular feature.

**Comment by kitbellew** [comment]
please ask on discord whether the community is ok with adding a parameter for this.

**Comment by Rocketeer007** [comment]
I've tried to ask on Discord, but I think I'm being kicked from the server about 10 minutes after I join. 

I'm no Discord expert - is there some verification step I've missed?

**Comment by kitbellew** [comment]
i am sorry, i don't know.
