### ISSUE TITLE
ScalaFmt removes needed curly braces

### ISSUE THREAD

**Issue by QuadStingray** [scalameta/scalafmt#3263]
## Description
ScalaFmt (sbt-plugin and IntelliJ Formatter) removing the needed curly braces around an one line statement.

## Configuration (required) ##
```
version = "3.0.0-RC5"

preset = defaultWithAlign
project.git = true
maxColumn = 160
unindentTopLevelOperators = true
danglingParentheses.preset = true
spaces.inImportCurlyBraces = true
newlines.alwaysBeforeElseAfterCurlyIf = true
newlines.beforeCurlyLambdaParams = true

rewrite.rules = [AvoidInfix, PreferCurlyFors, SortImports, SortModifiers, RedundantBraces]

rewrite.redundantBraces.methodBodies = true
rewrite.redundantBraces.includeUnitMethods = true
rewrite.redundantBraces.parensForOneLineApply = false
rewrite.redundantBraces.maxLines = 0
rewrite.redundantBraces.ifElseExpressions = false
rewrite.redundantBraces.methodBodies = false
rewrite.redundantBraces.includeUnitMethods = false
```

NB: before submitting, please confirm that the problem is observed in the
*latest published* version of the formatter! We don't publish hotfixes for older
versions, and the problem you have observed in an older version may have already
been fixed.

## Command-line parameters (required) ##
I`m using sbt plugin:
```
addSbtPlugin("org.scalameta" % "sbt-scalafmt" % "2.4.6")
```

## Steps

Given code like this:
```scala

  def tracePerformance(a: => Unit, message: String = ""): Unit = {
    val result = measure(a)
    performanceLogger.trace(
      "%s (%s) executed in %s ms".format(
        {
          if (StringTools.isStringTrimmedEmpty(message))
            "Code Block in Function %s".format(Thread.currentThread.getStackTrace()(3).getMethodName)
          else
            message
        },
        getClass.getName,
        result
      )
    )
  }

  override def user: User = {
    if (_user == null) {
      tracePerformance(
        {
          _user = createUser()
        },
        "create JDBC User"
      )
    }
    _user
  }

```

## Problem

Scalafmt formats code like this:
```scala
  override def user: User = {
    if (_user == null) {
      tracePerformance(
        {
          _user = createUser()
        },
        "create JDBC User"
      )
    }
    _user
  }
```

## Expectation

I would like the formatted output to look like this:
```scala
  override def user: User = {
    if (_user == null) {
      tracePerformance({
          _user = createUser()
        },
        "create JDBC User"
      )
    }
    _user
  }
```

## Workaround

Add an other line in the curly braces block. 
```scala
  override def user: User = {
    if (_user == null) {
      tracePerformance({
          _user = createUser()
          _user
        },
        "create JDBC User"
      )
    }
    _user
  }
```

**Comment by kitbellew** [comment]
why would you provide an sbt plug-in invocation when you're explicitly asked, multiple times, to use command line, coursier-built executable?

also, your example has all the braces everywhere.

**Comment by QuadStingray** [comment]
Sorry, I think the "problem"
is global so I put the issue message to this repo, but I also can change it to the sbt-Plugin repo when you say it's better there?

Because the braces I have copied the wrong code to the problem field sorry! 

```scala

override def user: User = {
    if (_user == null) {
      tracePerformance(_user = createUser(),"create JDBC User")
    }
    _user
  }

```

**Comment by tgodzik** [comment]
Thanks for reporting! Could you check if this works on the newest version of Scalafmt? `version = "3.0.0-RC5"` is pretty old and also a release candidate, so I would expect it to not work totally corectly.

**Comment by kitbellew** [comment]
> Sorry, I think the "problem" is global so I put the issue message to this repo, but I also can change it to the sbt-Plugin repo when you say it's better there?

i think what you're missing is that in order to report a formatting problem, you need to install command line formatter first and reproduce with that, even if you're normally using some other integration.

**Comment by kitbellew** [comment]
> Thanks for reporting! Could you check if this works on the newest version of Scalafmt? `version = "3.0.0-RC5"` is pretty old and also a release candidate, so I would expect it to not work totally corectly.

i missed that part. the submitter somehow overlooked key requirements we have requested in the submission.
