### ISSUE TITLE
Feature Request: newline before single-statement method body

### ISSUE THREAD

**Issue by odelrio** [scalameta/scalafmt#3271]
I would like my method signatures to break the line after `=` when the body is not a code block, even if it fits.

Examples:

```scala
// maxColumn = 80


def sum(a: Int, b: Int): Int =
  a + b
  
def greatest(a: Int, b: Int): Int =
  if (a > b) a
  else b
```

**Comment by tgodzik** [comment]
Thanks for reporting! Wouldn't unfold help out here? 

https://scalameta.org/scalafmt/docs/configuration.html#newlines
