### ISSUE TITLE
Is there a way to annotate a list/map to always keep it sorted?

### ISSUE THREAD

**Issue by feiluo-db** [scalameta/scalafmt#3290]
## Steps

Given code like this:
```scala
val myList = (
  "b",
  "c",
  "d",
  "a",
  ....
)
```

## Expectation

I would like to add a comment/annotation to this long list to keep it sorted.
```scala
val myList = (
// sorted: start
  "b",
  "c",
  "d",
  "a",
  ....
// sorted: end
)
```

**Comment by tgodzik** [comment]
Thanks for reporting! I think it's unlikely that it can be covered by scalaftmt, since this changes the semantics of the program and would go beyond what a formater should do.
