### ISSUE TITLE
fileOverride not able to override the dialect?

### ISSUE THREAD

**Issue by cchantep** [scalameta/scalafmt#3301]
Trouble with `fileOverride` seemingly not working.

`sbt scalafmtAll` raised [an error](https://github.com/playframework/anorm/runs/7895842297?check_suite_focus=true#step:9:57) on Scala 3 test sources, showing it uses the default dialect `Scala213Source3` whereas according `fileOverride` in [configuration](https://github.com/playframework/anorm/pull/474/files?file-filters%5B%5D=.conf&show-deleted-files=true&show-viewed-files=true#diff-88adef9b969d41ed5848ebca29ae7b61f25ed76010b0ed18079a8e2f06e195d8R19), the `scala3` dialect should be applied.

```
...
[error] org.scalafmt.sbt.ScalafmtSbtReporter$ScalafmtSbtError: scalafmt: /home/runner/work/anorm/anorm/core/src/test/scala-3/TestUtils.scala:7: error: [dialect scala213source3] ; expected but : found
...
```

Testing the glob expression in bash, the file mentioned in the error is matching :

```bash
$ shopt -s globstar

$ ls **/src/*/scala-3/**/*.scala | grep TestUtils
core/src/test/scala-3/TestUtils.scala
```bash

## Configuration (required) ##

`project/plugins.sbt`:

```scala
addSbtPlugin("org.scalameta" % "sbt-scalafmt" % "2.4.6")
```

`.scalafmt.conf`:

```
version = 3.5.8
runner.dialect = Scala213Source3

align.preset = true
assumeStandardLibraryStripMargin = true
danglingParentheses.preset = true
docstrings.style = Asterisk
docstrings.wrap = false
maxColumn = 120
project.git = true
rewrite.rules = [ AvoidInfix, RedundantParens, SortModifiers, PreferCurlyFors ]
rewrite.sortModifiers.order = [ "private", "protected", "final", "sealed", "abstract", "implicit", "override", "lazy" ]
spaces.inImportCurlyBraces = true   # more idiomatic to include whitepsace in import x.{ yyy }
trailingCommas = preserve

newlines.afterCurlyLambda = preserve
newlines.beforeCurlyLambdaParams = multilineWithCaseOnly

fileOverride {
  "glob:**/src/*/scala-3/**/*.scala" {
    runner.dialect = scala3
  }
}
```

## Command-line parameters (required) ##

When I run scalafmt via CLI like this: `scalafmtAll`

## Steps

Given code like this in file `core/src/test/scala-3/TestUtils.scala`:

```scala
package anorm

import scala.compiletime.testing.{ typeCheckErrors, Error }

import org.specs2.execute.{ TypecheckError, TypecheckSuccess, Typechecked }

object TestUtils:

  inline def typecheck(inline code: String): Typechecked =
    typeCheckErrors(code).headOption match {
      case Some(Error(msg, _, _, _)) =>
        Typechecked(code, TypecheckError(msg))

      case _ =>
        Typechecked(code, TypecheckSuccess)
    }

end TestUtils
```

## Problem

Raises blocking error:

```scala
...
[error] org.scalafmt.sbt.ScalafmtSbtReporter$ScalafmtSbtError: scalafmt: /home/runner/work/anorm/anorm/core/src/test/scala-3/TestUtils.scala:7: error: [dialect scala213source3] ; expected but : found
...
```

## Expectation

No error

**Comment by kitbellew** [comment]
> ## Command-line parameters (required)
> When I run scalafmt via CLI like this: `scalafmtAll`

you must run it using the scalafmt binary and show the command line parameters for that. sbt submissions are not accepted.

**Comment by kitbellew** [comment]
also,

1. see https://scalameta.org/scalafmt/docs/configuration.html#projectlayout (your dialect pattern is automatically covered)
2. the [PathMatcher](https://docs.oracle.com/javase/8/docs/api/java/nio/file/FileSystem.html#getPathMatcher-java.lang.String-) patterns might not be identical to what `bash` does
3. `glob:**/src/*/scala-3/**/*.scala` **does not** match `core/src/test/scala-3/TestUtils.scala` because the name contains only one slash between `scala-3` and `.scala` whereas the pattern contains two.

**Comment by cchantep** [comment]
> also,
> 
>     1. see https://scalameta.org/scalafmt/docs/configuration.html#projectlayout (your dialect pattern is automatically covered)

Ok

> 
>     3. `glob:**/src/*/scala-3/**/*.scala` **does not** match `core/src/test/scala-3/TestUtils.scala` because the name contains only one slash between `scala-3` and `.scala` whereas the pattern contains two.

Doesn't make sense, it defeat the utility of `**` which was used there just for that.

**Comment by kitbellew** [comment]
> > ```
> > 3. `glob:**/src/*/scala-3/**/*.scala` **does not** match `core/src/test/scala-3/TestUtils.scala` because the name contains only one slash between `scala-3` and `.scala` whereas the pattern contains two.
> > ```
> 
> Doesn't make sense, it defeat the utility of `**` which was used there just for that.

Instead of
```
glob:**/src/*/scala-3/**/*.scala
```
you could use
```
glob:**/src/*/scala-3/**.scala
```
