### ISSUE TITLE
Scalafmt 3.5.9: Scala 2.11 source with annotations containing with 'using' throws syntax error

### ISSUE THREAD

**Issue by stringbean** [scalameta/scalafmt#3308]
There is a regression in scalafmt 3.5.9 that breaks parsing of annotations with an element named `using` (eg `@Example(using = "something")`).

With some testing this does not appear to affect any other element names. Unfortunately our codebase makes extensive use of Jackson and the `@JsonSerialize` annotation 😭 

## Configuration (required) ##

Please paste the contents of your `.scalafmt.conf` file here:
```properties
version = 3.5.9
# also affects scala212 & scala213 dialects
runner.dialect = scala211
```

## Command-line parameters (required) ##

Running scalafmt (in an sbt project) using:

```sh
scalafmt --check src
```

## Steps

Given code like this:
```scala
@JsonAutoDetect(fieldVisibility = Visibility.ANY)
case class Preferences(
    @JsonSerialize(using = classOf[LocaleSerializer]) locale: Locale,
    currency: String
)
```

## Problem

The following error is returned by scalafmt:

```text
/Users/mike/tmp/scalameta-test/src/main/scala/com/zestia/meta/Example.scala:12: error: [dialect scala211] illegal start of simple expression
    @JsonSerialize(using = classOf[LocaleSerializer]) locale: Locale,
                                  ^
error: ParseError=2
```

## Expectation

The code should be parsed and formatted correctly as Scala 2.x source.

## Workaround

Setting the version in `.scalafmt.conf` back to 3.5.8 allows formatting correctly:

```properties
version = 3.5.8
runner.dialect = scala211
```

```sh
scalafmt  --check  src
# All files are formatted with scalafmt :)
```

Additionally escaping `using` allows the code to be parsed correctly:

```scala
@JsonAutoDetect(fieldVisibility = Visibility.ANY)
case class Preferences(
    @JsonSerialize(`using` = classOf[LocaleSerializer]) locale: Locale,
    currency: String
)
```

```sh
scalafmt  --check  src
# All files are formatted with scalafmt :)
```

## Notes

Scalameta 4.5.12 seems to be happy parsing the code using the `Scala211` dialect:

```scala
val code =
  """@JsonAutoDetect(fieldVisibility = Visibility.ANY)
    |case class Preferences(
    |    @(JsonSerialize @field)(using = classOf[LocaleSerializer]) locale: Locale,
    |    currency: String
    |)
    |""".stripMargin

val tree = dialects.Scala211(code).parse[Source].get
println(tree.syntax)

// case class Preferences(
//     @(JsonSerialize@field)(using = classOf[LocaleSerializer]) locale: Locale,
//     currency: String
// )
```

But switching to `Scala3` dialect results in a similar error to scalafmt:

```scala
val code =
  """@JsonAutoDetect(fieldVisibility = Visibility.ANY)
    |case class Preferences(
    |    @(JsonSerialize @field)(using = classOf[LocaleSerializer]) locale: Locale,
    |    currency: String
    |)
    |""".stripMargin

val tree = dialects.Scala3(code).parse[Source].get
println(tree.syntax)

//  error: illegal start of simple expression
//     @(JsonSerialize @field)(using = classOf[LocaleSerializer]) locale: Locale,
```

This seems to imply that the dialect isn't getting passed down to Scalameta correctly...

**Comment by kitbellew** [comment]
fixed in scalameta/scalameta#2803, will be in next release.
