### ISSUE TITLE
afterInfix breaks long destructuring pattern causing compiler error

### ISSUE THREAD

**Issue by leonbur** [scalameta/scalafmt#3313]
UPDATE:

Hi,
When formatting a simple destructuring statement using ~`maxColumn`~ `afterInfix=many` the compiler stops recognizing the pattern.
for example:
```
val servicePort :: producerServerPort :: grpcSidecarServicePort :: managementPort :: grpcSidecarUserPort :: jsonRpcSidecarUserPort :: Nil = selectRandomPorts(6)
```
becomes
```
val servicePort :: producerServerPort :: grpcSidecarServicePort :: managementPort :: grpcSidecarUserPort :: jsonRpcSidecarUserPort :: 
Nil = selectRandomPorts(6)
```

and will result in 
```
error: illegal start of simple pattern
Nil = selectRandomPorts(6)
```

scalafmt.conf:
```
version=3.5.9
runner.dialect=scala212

maxColumn = 140
newlines {
  afterInfix=many
}
```

Note: Compiling in Scala 2.12

**Comment by kitbellew** [comment]
@leonbur could you please submit with all the information requested? specifically, how you are running `scalafmt` **binary** executable to obtain this formatting. (since i can't repro, most likely you are not using scalafmt.)

**Comment by kitbellew** [comment]
please reopen if you can provide a reproducible example and setup.

**Comment by leonbur** [comment]
> @leonbur could you please submit with all the information requested? specifically, how you are running `scalafmt` **binary** executable to obtain this formatting. (since i can't repro, most likely you are not using scalafmt.)

Hi, sorry. I'm running it from cli on an MBP (M1).
installed through coursier

**Comment by kitbellew** [comment]
so, what is your code? the snippet you provided is not valid top level scale so I can't create a file containing that one line and run it via cli. i need the actual reproducible setup, full class or object and the corresponding scalafmt configuration file.

**Comment by leonbur** [comment]
it's as small as 
```
object TestEnv {
  val servicePort :: producerServerPort :: grpcSidecarServicePort :: managementPort :: grpcSidecarUserPort :: jsonRpcSidecarUserPort :: Nil = selectRandomPorts(6)
}
```
before formatting

**Comment by kitbellew** [comment]
i cannot reproduce; with your example and the config file provided, this is what i get after running `scalafmt`:
```
object TestEnv {
  val servicePort :: producerServerPort :: grpcSidecarServicePort :: managementPort :: grpcSidecarUserPort :: jsonRpcSidecarUserPort :: Nil =
    selectRandomPorts(6)
}
```

**Comment by leonbur** [comment]
I'm very very sorry for wasting your time, I've retested and noticed I made a mistake in the initial report. the config should have `newlines.afterInfix=many`
```
version=3.5.9
runner.dialect=scala212

maxColumn = 140
newlines {
  afterInfix=many
}
```
This will cause the aforementioned problem.

**Comment by leonbur** [comment]
Is there an ETA for the bugfixed release?
