### ISSUE TITLE
Scalafmt seems to ignore COURSIER_REPOSITORIES

### ISSUE THREAD

**Issue by PawanKartikS** [scalameta/scalafmt#3316]
Our environment does not support egress so we use Nexus repository manager. While we are able to use coursier to fetch what we want by specifying `COURSIER_REPOSITORIES` AND `COURSIER_CREDENTIALS`, `scalafmt` seems to hit `oss.sonatype.org` while resolving the version specified in the `.scalafmt.conf` file. If the former env variable isn't set, it straight away goes to maven. Am I correct in assuming that `scalafmt` supports `COURSIER_REPOSITORIES`, [ref](https://github.com/scalameta/scalafmt/blob/47650706f50b1a36ed71c505658044f71252a826/scalafmt-dynamic/src/main/scala/org/scalafmt/dynamic/CoursierDependencyDownloader.scala#L29)? If it does indeed support it, shouldn't it hit our Nexus instead?

Version: 3.5.9

Additional helpful information:
I've tried running `coursier` to fetch something which hit our Nexus and was successful. The next immediate command that I ran was `scalafmt` as `scalafmt Foo.scala --debug` which hit some other endpoint/host instead of our Nexus. And because the egress is blocked, it simply sat there with the progress bar at 0%. I've double checked that the env variables are correct. Coursier being able to pull what I've asked for also shows that the configuration is correct.

## Configuration ##

```
version = 3.5.9
...
```

## Command-line parameters ##

`scalafmt Main.scala --debug`

## Expectation

I'd expect that `scalafmt` format the code as per its functionality.

**Comment by PawanKartikS** [comment]
I just specified 1 repository, our Nexus endpoint.

**Comment by tanishiking** [comment]
Can you download the scalafmt binary from the Nexus repository?
scalafmt-cli does indeed support `COURSIER_REPOSITORIES`.

**Comment by tanishiking** [comment]
Hmm, then I have no idea what's going on in your environment 🤔

**Comment by PawanKartikS** [comment]
Ah. :/

**Comment by PawanKartikS** [comment]
Are there any logs to see what repositories scalafmt is picking up and other related details?

**Comment by PawanKartikS** [comment]
@tanishiking I have an update for you. I'm not sure how relevant it is but I thought I should point it out. When scalafmt is invoked, it very briefly, for a sec, hits our Nexus repo and then switches back to oss.sonatype.org. It happens so quickly that it was nearly impossible to notice. I had to record my screen and move frame by frame to notice this happen. Are there any scenarios why the scalafmt would switch the repo it is using without facing any error?

**Comment by tanishiking** [comment]
That happens if the binary is not found in the repository (that's why I asked "Can you download the scalafmt binary from the Nexus repository?")
Can you find ` org.scalameta:scalafmt-core_2.13:3.5.9` instead of `scalafmt-cli` (I guess you can though...)

**Comment by PawanKartikS** [comment]
Yes, I just pulled in `org.scalameta:scalafmt-core_2.13:3.5.9` successfully. I even was able to pull a few other versions.
