### ISSUE TITLE
Rewrite imports with asterix to wildcard imports (or vice versa)

### ISSUE THREAD

**Issue by mlachkar** [scalameta/scalafmt#3326]
After enabling -Xsource:3, I have started to see a mix of imports with wildcards and other with asterix. Is there already a configuration to enforce one style only ? Thank you ?

**Comment by tgodzik** [comment]
Thanks for reporting! Did you try https://scalameta.org/scalafmt/docs/configuration.html#rewritescala3converttonewsyntax?

I think it might work for Scala 2 with dialect `Scala213Source3`

**Comment by mlachkar-da** [comment]
Hello! I have tried it , but it only works on one direction from `_` to `*` and it also adds more rewrite which are not compatible with scala213.

**Comment by tgodzik** [comment]
Which ones? We check for the specific dialect options before applying any of the rewrites. Do you have an example? That might be something to fix.

**Comment by kitbellew** [comment]
> Hello! I have tried it , but it only works on one direction from `_` to `*` and it also adds more rewrite which are not compatible with scala213.

it's true that the rewrite is one direction only (from scala2 to scala3) but if the rewrites are incompatible with your given dialect, in the next release you will be able to modify the dialect parameters directly and achieve the right combination. Please also see #3332.

**Comment by mlachkar-da** [comment]
@tgodzik I will take some time and post the errors I have when I run the rewrite rule. 

@kitbellew Thank you, I have seen the dialect overwrite. I think it's nice feature, but I m using `3.0.6` and upgrading would break the current style

**Comment by tgodzik** [comment]
> @tgodzik I will take some time and post the errors I have when I run the rewrite rule.
> 
> @kitbellew Thank you, I have seen the dialect overwrite. I think it's nice feature, but I m using `3.0.6` and upgrading would break the current style

Actually, that's also a bug. Upgrading scalafmt shouldn't break the current style. @kitbellew takes great care to not change the default behaviour. Do you have an example of what would change?

**Comment by mlachkar-da** [comment]
yes.
those are the annoying changes. 
```diff 
    logger.info(s"Auto-connecting local participants ${connectParticipants
-      .map(_._1.unwrap)} to local domains ${activeDomains.map(_.name.unwrap)}")
+        .map(_._1.unwrap)} to local domains ${activeDomains.map(_.name.unwrap)}")
```

```diff
-    )(consoleEnvironment.environment.executionContext)
+    )(
+      consoleEnvironment.environment.executionContext
+    )

So if you know how I can deactivate them, it would be helpful and then I can upgrade

**Comment by tgodzik** [comment]
Thanks! I think we should probably fix those, what do you think @kitbellew ?

**Comment by kitbellew** [comment]
> yes. those are the annoying changes.
> 
> ```diff
>     logger.info(s"Auto-connecting local participants ${connectParticipants
> -      .map(_._1.unwrap)} to local domains ${activeDomains.map(_.name.unwrap)}")
> +        .map(_._1.unwrap)} to local domains ${activeDomains.map(_.name.unwrap)}")
> ```

This is probably intentional. One indent is from `(` (argument continuation), and the new one is from `${`.

> ```diff
> -    )(consoleEnvironment.environment.executionContext)
> +    )(
> +      consoleEnvironment.environment.executionContext
> +    )
> ```

this one shouldn't happen, i think. @mlachkar, what's the configuration and what's the original code snippet (smallest reproducible)?

**Comment by mlachkar-da** [comment]
I will answer soon!

**Comment by mlachkar-da** [comment]
```
version = 3.0.6

project.git = true

align.preset = none # never align to make the fmt more diff friendly
maxColumn = 100
runner.fatalWarnings = true
trailingCommas = multiple
# Disable scala doc wrapping (behavior changed in v3.0.0).
docstrings.wrap = no
newlines.topLevelStatementBlankLines = [
  { blanks { after = 1 }, regex = "^Import" }
]

runner.dialect = "scala213"
```

**Comment by mlachkar-da** [comment]
this one also can be annoying
```
-    }.toSeq)
+        }
+        .toSeq
```
Is there an option to deactivate this ?

**Comment by kitbellew** [comment]
> > ```diff
> > -    )(consoleEnvironment.environment.executionContext)
> > +    )(
> > +      consoleEnvironment.environment.executionContext
> > +    )
> > ```

and what's the source for that?

**Comment by mlachkar-da** [comment]
Can we reopen this issue while we are still discussing it ? thanks

**Comment by mlachkar-da** [comment]
so https://github.com/scalameta/scalafmt/issues/3309 is fixing the issue below ? 

> > > ```diff
> > > -    )(consoleEnvironment.environment.executionContext)
> > > +    )(
> > > +      consoleEnvironment.environment.executionContext
> > > +    )
> > > ```
> 
> and what's the source for that?

**Comment by mlachkar-da** [comment]
I have just tried to upgrade to `3.5.8` instead of `3.5.9` and thus issue appears only in `3.5.9`. I mean this one 
```diff
-    )(consoleEnvironment.environment.executionContext)
+    )(
+      consoleEnvironment.environment.executionContext
+    )
```
There are many example of this kind of rewrite here https://github.com/digital-asset/canton/pull/53/files#diff-b841bd0fa65eeff2f86e0bd4e8a9661990350f9ddd9f9b2d7ef9ada5253a9ae9R40-R42

For this one, I don't know if it's the same issue
```diff
-        } else Seq()
-      } else Seq()
-    }.toSeq)
+       } else Seq()
+     } else Seq()
+   }
+    .toSeq
+. )
```

**Comment by kitbellew** [comment]
> so #3309 is fixing the issue below ?
> 
> > > > ```diff
> > > > -    )(consoleEnvironment.environment.executionContext)
> > > > +    )(
> > > > +      consoleEnvironment.environment.executionContext
> > > > +    )
> > > > ```
> > 
> > 
> > and what's the source for that?

Probably. Can you try a nightly version (or check out and build formatter locally)?

**Comment by kitbellew** [comment]
> For this one, I don't know if it's the same issue
> 
> ```diff
> -        } else Seq()
> -      } else Seq()
> -    }.toSeq)
> +       } else Seq()
> +     } else Seq()
> +   }
> +    .toSeq
> +. )
> ```

Not the same. Also, there's only one such case. Several points to consider or try:

- `.toSeq` is split because before that `.flatMap` is split from `_.typeSignature.members`; try reading https://scalameta.org/scalafmt/docs/configuration.html#classic-select-chains (i do not remember what each parameter does, one of them might help -- but might also change formatting in other places)
- the split between `symbols.toSeq.flatMap(` and `_.typeSignature.members` is possibly because of config-style arguments (https://scalameta.org/scalafmt/docs/configuration.html#newlines-config-style-formatting)
- the split between `.toSeq` and `)` is also possibly because of config-style arguments, or else dangling parentheses (https://scalameta.org/scalafmt/docs/configuration.html#danglingparenthesescallsite)

**Comment by mlachkar-da** [comment]
I have added this in my plugins.sbt
```
resolvers += Resolver.sonatypeRepo("snapshots")
```
and then modified the version of scalafmt 
```
version = "3.5.9+41-60b84efb-SNAPSHOT"
```
but I m getting an error : `Invalid version: 3.5.9+41-60b84efb-SNAPSHOT`

How can I use a snapshot version ?

**Comment by mlachkar-da** [comment]
following an exchange with @tanishiking 
```
We should be able to use SNAPSHOT versions, but it looks like Scalafmt version parser has some kind of bug and failed to parse it
https://github.com/scalameta/scalafmt/blob/713ac5b90a077d13d6925e683b461136aeccb359/scalafmt-dynamic/src/main/scala/org/scalafmt/dynamic/ScalafmtVersion.scala#L36-L52
```

**Comment by mlachkar-da** [comment]
I dont have this issue anymore in 2.5.9-snapshot! Thank you so much for your help !

**Comment by kitbellew** [comment]
@mlachkar-da which issue is gone, and what still remains? :)

**Comment by mlachkar-da** [comment]
> > so #3309 is fixing the issue below ?
> > > > > ```diff
> > > > > -    )(consoleEnvironment.environment.executionContext)
> > > > > +    )(
> > > > > +      consoleEnvironment.environment.executionContext
> > > > > +    )
> > > > > ```
> > > 
> > > 
> > > and what's the source for that?
> 
> Probably. Can you try a nightly version (or check out and build formatter locally)?

This is one is gone!

**Comment by mlachkar-da** [comment]
> > For this one, I don't know if it's the same issue
> > ```diff
> > -        } else Seq()
> > -      } else Seq()
> > -    }.toSeq)
> > +       } else Seq()
> > +     } else Seq()
> > +   }
> > +    .toSeq
> > +. )
> > ```
> 
> Not the same. Also, there's only one such case. Several points to consider or try:
> 
> * `.toSeq` is split because before that `.flatMap` is split from `_.typeSignature.members`; try reading https://scalameta.org/scalafmt/docs/configuration.html#classic-select-chains (i do not remember what each parameter does, one of them might help -- but might also change formatting in other places)
> * the split between `symbols.toSeq.flatMap(` and `_.typeSignature.members` is possibly because of config-style arguments (https://scalameta.org/scalafmt/docs/configuration.html#newlines-config-style-formatting)
> * the split between `.toSeq` and `)` is also possibly because of config-style arguments, or else dangling parentheses (https://scalameta.org/scalafmt/docs/configuration.html#danglingparenthesescallsite)

This one is still there.

**Comment by mlachkar-da** [comment]
are you planning a release soon ? My intellij is not able to download a snapshot version of scalafmt. thank you

**Comment by kitbellew** [comment]
@mlachkar-da anything else remaining?

**Comment by mlachkar-da** [comment]
no. Thanks! 
We can close the ticket
