### ISSUE TITLE
Rewrite when column width is increased

### ISSUE THREAD

**Issue by tusharmath** [scalameta/scalafmt#3341]
## Configuration (required) ##

```
version = "3.5.3"
runner.dialect = scala3
align.preset = more
maxColumn = 160
```

## Command-line parameters (required) ##

```
scalafmt
```
## Steps

Given code like this:
```scala
    final case class Address(
        street: String,
        suite: String,
        city: String,
        zipcode: String,
        geo: Geo
    )

```

## Problem

Scalafmt doesn't format code at all. The output remains the same.
```scala
    final case class Address(
        street: String,
        suite: String,
        city: String,
        zipcode: String,
        geo: Geo
    )
```

## Expectation

If the line can be fit into the provided max column, scalafmt should try to fit it.

I would like the formatted output to look like this:
```scala
    final case class Address(street: String, suite: String, city: String, zipcode: String, geo: Geo)
```

## Workaround

None available.

**Comment by kitbellew** [comment]
this is by design (preserves newlines in most cases). use `newlines.source = fold`.

**Comment by tusharmath** [comment]
Thanks!
