### ISSUE TITLE
Feature: Implement git ratcheting

### ISSUE THREAD

**Issue by mdedetrich** [scalameta/scalafmt#3344]
After going through and updating various Scala OS projects old version of Scalafmt (typically the 2.x.x series) to the newest versions one of the problems that invariably happens is dealing with bag bang formats which generate massive diff's. This typically creates understandable friction amongst the OS projects, the most recent one I am dealing with is updating the Scalafmt version of an Akka fork.

For Java projects this problem is solved via a technique called ratcheting (see https://github.com/diffplug/spotless/tree/main/plugin-gradle#ratchet). The basic premise is that rather than formatting the entire codebase you instead only format the files that have changed from a specific git reference, typically this is the main upstream tracked branch (i.e. `origin/main` or `origin/master`). What this means is that you can do significant changes in the `.scalafmt.conf` and only the current file being edited/committed will be the one picked up by Scalafmt. In summary this has the following advantages

- Avoids the situation where you have a giant commit from a single person. Note only does this create misleading insights about collaboration's but also messes with tools like git blame. With git ratcheting, only the person editing the file will get triggered with a scalafmt diff, not the entire project
- Greatly increases buy in for updating between significant versions of Scalafmt for various projects. A large portion of Scala OS projects (especially the big ones) still tend to use older versions of Scalafmt and due to the nature of Scalafmt changes over time practically speaking its quite common to not be able to exactly replicate the older Scalafmt configuration in the latest version of Scalafmt.
- Decreases the hesitance in experimenting with different Scalafmt options. Due to the fact that changing Scalafmt can create massive project wide diffs, most people tend to just pick a Scalafmt configuration and stick with it for a while. Not only that, it also exacerbates the problem of projects sticking to old scalafmt versions for long periods of time.
  - This is further amplified due to how variable Scala syntax is and how configurable Scalafmt in general is (at least compared to Java)
  
## Design
On the top of I can imagine the design of such feature is to reuse the existing `project` configuration. Assuming you have `project.git = true` in your `.scalafmt.conf`, you can then enable your ratcheting by having something like.

```
project.ratchet.gitref = "origin/main" // default value null, errors if project.git != true
```

This would instruct scalafmt to calculate the files that have been changed between the current commit + unchanged changes and the `gitref` and apply that to the final file filter. If projects have various branches on remote then one can just have a different value for `project.ratchet.gitref` in those different branches.

**Comment by tgodzik** [comment]
Thanks for reporting!

Wouldn't using `scalafmt --diff --diff-branch main` for the CLI help out here? It should only format things changed from main branch.

**Comment by kitbellew** [comment]
@tgodzik is correct. scalafmt configuration sets the parameters of the entire scope of possibility but if you'd like to constrain in a particular invocation, both the binary and the sbt integration have the necessary parameters to do so.

please close this request when you're satisfied with these options.

**Comment by mdedetrich** [comment]
> Thanks for reporting!

> Wouldn't using scalafmt --diff --diff-branch main for the CLI help out here? It should only format things changed from main branch.

Does this work against remote as well or only local branches? Doing `main` against local branches is not going to work because if you update it locally then the git ratcheting stops working. Quoting from spotless's ratcheting mechanism referenced earlier 

> However, we strongly recommend that you use a non-local branch, such as a tag or origin/main. The problem with HEAD or any local branch is that as soon as you commit a file, that is now the canonical formatting, even if it was formatted incorrectly. By instead specifying origin/main or a tag, your CI server will fail unless every changed file is at least as good or better than it was before the change.

You would need to support something like `scalafmt --diff --diff-branch origin/main`

**Comment by kitbellew** [comment]
> > Wouldn't using scalafmt --diff --diff-branch main for the CLI help out here? It should only format things changed from main branch.
> 
> Does this work against remote as well or only local branches? ...
> ...
> You would need to support something like `scalafmt --diff --diff-branch origin/main`

Generally, I would have hoped that in the time it took to prepare this elaborate treatise on git ratcheting, you would have been able to glance through [documentation](https://scalameta.org/scalafmt/docs/installation.html#--help) and quickly test it out.

You could also implement a git pre-commit hook and use the additional `--reportError` parameter which would both format the code and report if it's different.

**Comment by mdedetrich** [comment]
> Generally, I would have hoped that in the time it took to prepare this elaborate treatise on git ratcheting, you would have been able to glance through [documentation](https://scalameta.org/scalafmt/docs/installation.html#--help) and quickly test it out.

I just tested this and indeed the `--diff` along wtih `--diff-branch` works however having it only as cli args is problematic (as stated earlier). Would adding it as a configuration option for `.scalafmt.conf` be considered appropriate?

**Comment by kitbellew** [comment]
> > Generally, I would have hoped that in the time it took to prepare this elaborate treatise on git ratcheting, you would have been able to glance through [documentation](https://scalameta.org/scalafmt/docs/installation.html#--help) and quickly test it out.
> 
> I just tested this and indeed the `--diff` along wtih `--diff-branch` and it works however having it only as cli args is problematic for various reasons (as stated earlier). Would adding it as a configuration option for `.scalafmt.conf` be considered appropriate?
> 
> I can contribute the changes if necessary.

thank you but i don't think it belongs in the configuration. it's a function of a specific invocation.

**Comment by mdedetrich** [comment]
> thank you but i don't think it belongs in the configuration. it's a function of a specific invocation.

Cannot the same be said wrt `project.git` which is also specific to invocation? Afaik `project.git` does a filter based on git.

If it doesn't belong in configuration how would you best solve the problem I was describing earlier, i.e. 

> Also the other feature of ratcheting is that the option should be available as a configuration, not just a CLI argument. Although having it in CLI is desirable, the other main point is that if people run scalafmt locally that it doesn't format the entire codebase. If its only a CLI argument then you need to tell people to run scalafmt --diff .... and not only that but this command change is different for each branch that tracks a different remote branch (and yes I know you can make aliases but that poses other problems, i.e. Intellij's native scalafmt support).

Without having it as a configuration option it means that for large projects (like Akka) we are basically forcing all users to invoke scalafmt in a very specific way (via scalafmt cli diff flags) every time they work on the codebase rather than using natural integrations (such as Intellij/VSCode).

I was also thinking that this may make sense in scalafmt-sbt but then the problem is the same, if someone is using Intellij's scalafmt integration with Command + Shift + L (for example) then it will just format the entire codebase which is not what we wan't.

**Comment by tgodzik** [comment]
> Without having it as a configuration option it means that for large projects (like Akka) we are basically forcing all users to invoke scalafmt in a very specific way (via scalafmt cli diff flags) every time they work on the codebase rather than using natural integrations (such as Intellij/VSCode).

Using Intellij or VS Code should only modify the current file, so this shouldn't be an issue I think. Unless you want the users to only be able to format specific parts of code in which case scalafmt will not be able to do that.

**Comment by tgodzik** [comment]
> scalafmt integration with Command + Shift + L (for example) then it will just format the entire codebase which is not what we wan't.

Does it modify every file in the codebase? :fearful:

**Comment by mdedetrich** [comment]
Sorry I didn't mean Intellij's integration (was editing the post while you commented), I meant commands like `scalafmtAll` within sbt shell (yes you are correct Command + Shift + L only works on current file)

**Comment by kitbellew** [comment]
> > thank you but i don't think it belongs in the configuration. it's a function of a specific invocation.
> 
> Cannot the same be said wrt `project.git` which is also specific to invocation? Afaik `project.git` does a filter based on git.

You are absolutely right, this parameter should **not** be there either: it's not implemented by the formatter itself but by every single conceivable wrapper. And some wrappers probably do not support it leading to confusion.

> Without having it as a configuration option it means that for large projects (like Akka) we are basically forcing all users to invoke scalafmt in a very specific way (via scalafmt cli diff flags) every time they work on the codebase rather than using natural integrations (such as Intellij/VSCode).

In my view, we should not be forcing users to invoke anything at all (and least of all IDE). In my previous job (for which I started to maintain this tool), we had a git precommit hook which explicitly formatted everything automatically and simply asked users to amend the commit before retrying.

@tgodzik addressed the other points.

**Comment by tgodzik** [comment]
Maybe for sbt you can use the diff setting in sbt?

https://scalameta.org/scalafmt/docs/installation.html#settings

If someone is working with a different branch they can still diff with main since potentially the branch had the diff with main branch already formatted.

**Comment by mdedetrich** [comment]
Yeah I was just about to say that I think that this belongs in sbt-scalafmt. I will close this issue as I think that most people won't use the raw CLI runner but instead either `scalafmtAll`/`scalafmtSbt` via sbt shell or via other integrations.

If the sbt-scalafmt option doesn't work I will then open up an issue on that repo.

Thanks for the time!
