### ISSUE TITLE
Align vertically LeftArrow and Assign with at least one space at left. In for comprehension

### ISSUE THREAD

**Issue by alexandru-tetelea** [scalameta/scalafmt#3361]
Hi is there a way to align = and <- in for comprehension so that horizontally there always be at least one space between <- and the longest variable?
For example, this test will pass: We can see that there is at least one space between <- and the variable: 'longestName'

```scala
version = 3.5.9
runner.dialect = scala212
maxColumn = 120

align {
  preset = most
}
<<< Strange formatting of match clause test
object A {
     def get(name: String, tags: Map[String, String]): IO[M] =
       for {
         longestName    <- ref.get
         shortName = test(test, test, test)
         _                  <- ref.set(test)
       } yield test(name)(tags)
}
>>>
object A {
  def get(name: String, tags: Map[String, String]): IO[M] =
    for {
      longestName <- ref.get
      shortName    = test(test, test, test)
      _           <- ref.set(test)
    } yield test(name)(tags)
}
```

But also this test will pass: But vertically we don't have at least one space between `longestName` and <-
```scala
version = 3.5.9
runner.dialect = scala212
maxColumn = 120

align {
  preset = most
}
<<< Strange formatting of match clause test
object A {
     def get(name: String, tags: Map[String, String]): IO[M] =
       for {
         shortName    <- ref.get // Not aligned vertically
         longestName = test(test, test, test)
         _                  <- ref.set(test)
       } yield test(name)(tags)
}
>>>
object A {
  def get(name: String, tags: Map[String, String]): IO[M] =
    for {
      shortName  <- ref.get // vertically there is not at least one space between `longestName` and `<-`
      longestName = test(test, test, test)
      _          <- ref.set(test)
    } yield test(name)(tags)
}

```

**Comment by kitbellew** [comment]
alignment applies only on one side of the token, in this case after. you're looking for both before and after, and it's not supported.

since i don't really understand the attraction of vertical alignment, and the resulting reshuffling of multiple lines when a single one is modified, is this a real visual concern or simply a bit of ocd?

**Comment by alexandru-tetelea** [comment]
:)) It's just how code was formatted manually in my team.

**Comment by kitbellew** [comment]
@alexandru-tetelea scalafmt was not designed to reproduce all possible custom formats, but to make it _sufficiently_ readable for a few typical variations.
