### ISSUE TITLE
Force closing paranthese on a new line when `verticalMultiline.atDefnSite = true` is used. Similar to def

### ISSUE THREAD

**Issue by alexandru-tetelea** [scalameta/scalafmt#3362]
Hi, I'm trying to use 'verticalMultiline.atDefnSite = true'. 
On methods, it works as expected. But I cannot force the closing parenthesis to go on a new line.

I have this code:
```scala
case class Test(id: ID) {
def other(
  a: String,b: String) = a + b + c
}
```

After applying this config:
```scala
version = 3.5.9
runner.dialect = scala212
newlines.source = unfold
verticalMultiline.atDefnSite = true
danglingParentheses.defnSite = true
verticalMultiline.arityThreshold = 1
danglingParentheses.callSite = true
```

I get this formatted code:
```scala
case class Test(
    id: ID) {
  def other(
      a: String,
      b: String
    ) = a + b + c
}
```

Is there a way to force the closing parenthesis from the class to go on a new line? like this:
```scala
case class Test(
    id: ID
) {
  def other(
      a: String,
      b: String
    ) = a + b + c
}
```

**Comment by kitbellew** [comment]
there's a parameter for that.

**Comment by alexandru-tetelea** [comment]
@kitbellew could you share what it's called?

**Comment by kitbellew** [comment]
@alexandru-tetelea it's documented on the configuration page, with some examples. you shouldn't have missed it if you read the page.

**Comment by alexandru-tetelea** [comment]
@kitbellew I've read that page many times. Without `verticalMultiline.DefnSite = true` it works properly, but once I add it that last parenthesis is not going on a new line

**Comment by tgodzik** [comment]
I think that maybe you could change to:
`danglingParentheses.callSite = false` 
?

**Comment by alexandru-tetelea** [comment]
Not sure what I'm doing wrong. But in any combination, if I add verticalMultiline.atDefnSite = true the last parenthesis is not going on the next line. If I remove it then it works.

This test passes
```scala
version = 3.6.1
runner.dialect = scala212
maxColumn = 50

<<< Test
case class Test(id: ID, id1: Long, id2: Long, id3: Param)
>>>
case class Test(
    id: ID,
    id1: Long,
    id2: Long,
    id3: Param
)

```

and this one fails 
```scala
version = 3.6.1
runner.dialect = scala212
maxColumn = 50
verticalMultiline {
  atDefnSite = true
}

<<< Test
case class Test(id: ID, id1: Long, id2: Long, id3: Param)
>>>
case class Test(
    id: ID,
    id1: Long,
    id2: Long,
    id3: Param
)
```

**Comment by alexandru-tetelea** [comment]
Should I create a bug? Because on docs verticalMultiline.DefnSite = true should not change last parenthesis position

**Comment by tgodzik** [comment]
It does look weird that it works for defs, but for case classes it will leave `)` next to the last param. Looks like a bug.

It's actually the current behaviour https://scalameta.org/scalafmt/docs/configuration.html#verticalmultilinearitythreshold

@kitbellew isn't it a bug?

**Comment by kitbellew** [comment]
it's not a bug. I'm simply suggesting to the author to read the entire documentation section on vertical multilines.

**Comment by tgodzik** [comment]
> it's not a bug. I'm simply suggesting to the author to read the entire documentation section on vertical multilines.

You've got 2 people confused here, I think it would be a bit easier if you actually let us know what we're missing :sweat_smile: 

This seems a bit overly passive aggressive and it's just a simple lack of understanding.

**Comment by alexandru-tetelea** [comment]
@kitbellew  From the [config](https://scalameta.org/scalafmt/docs/configuration.html#vertical-multiline) page I found only this: 

> If enabled this formats methods such that parameters are on their own line indented by [indent.defnSite](https://scalameta.org/scalafmt/docs/configuration.html#indentdefnsite). Separation between parameter groups are indented by two spaces less than indent.defnSite. The return type is on its own line at the end.

But it does not explain why this parameter affects class formatting and moves the closing parenthesis after the last parameter.

**Comment by kitbellew** [comment]
let me know why you missed it, then: https://scalameta.org/scalafmt/docs/configuration.html#verticalmultilineexcludedanglingparens (and the section it explicitly points to)

**Comment by tgodzik** [comment]
I think it was unclear that the default [class, trait] is when `vertical-multiline` is used.

This:
`For backwards compatibility, the default depends on whether [Vertical Multiline](https://scalameta.org/scalafmt/docs/configuration.html#vertical-multiline) mode is used. If it is, the default is [class, trait]; otherwise, it's empty.`

should also probably also be around https://scalameta.org/scalafmt/docs/configuration.html#verticalmultilineexcludedanglingparens

**Comment by alexandru-tetelea** [comment]
Thank you for helping with finding out where the problem is @kitbellew @tgodzik. 
I've missed this logic and surely the answer was in the docs.
