### ISSUE TITLE
feat: add more options for DSL

### ISSUE THREAD

**Issue by numero-744** [scalameta/scalafmt#3385]
Hello,

## Configuration

This issue is about options available as of https://scalameta.org/scalafmt/docs/configuration.html and is not specific to a currently released version of `scalafmt`.

It suggests more options and describe how they would behave. These options do not follow the [Scala Style Guide](https://docs.scala-lang.org/style/) as it is for DSL (examples here are for SpinalHDL, a DSL to describe digital hardware).

*Note: examples provided here are minimal to show the syntax, they are not real-case logic.*

## Suggestion 1: Add DSL keywords to add space after them

The idea is to get [`spaces.afterKeywordBeforeParen`](https://scalameta.org/scalafmt/docs/configuration.html#spacesafterkeywordbeforeparen) working for custom keywords

For instance, a configuration could be:
```scala
spaces.afterWordsBeforeParen = ["when", "switch", "is"]
```

Given code like this (formatted):
```scala
when(a === b) {
  c := d
}
switch(c) {
  is(False) {
    e := False
  }
  is(True) {
    e := a
  }
}
```

I would like the formatted output to look like this, with an extra space before the opening brace:
```scala
when (a === b) {
  c := d
}
switch (c) {
  is (False) {
    e := False
  }
  is (True) {
    e := a
  }
}
```

## Suggestion 2: special management of infix operators

SpinalHDL provides modifiers to act on hardware types (representing wires).

For instance, a configuration could be:
```scala
spaces.afterAlnumInfix = false
```

It would remove the space after an infix operator followed by a `(`, but only if this operator is only alphanumeric.

Another (maybe better) configuration could be:

```scala
spaces.removeAfterInfix = ["init"]
```

It would be useful to split the modifier (method) and the path to the wire acted on, by using dots for the path and not for the modifier.

Given code like this (formatted):
```scala
val x = Reg(RGB())
x.r init (0)
x.g init (0)
x.b init (0)
```

*Note: another option is `x.b.init(0)` but the path is mixed with the modifier*

I would like the formatted output to look like this, with an extra space before the opening brace:
```scala
val x = Reg(RGB())
x.r init(0)
x.g init(0)
x.b init(0)
```

Here I see I act on the signal `x.b` to set it's `init` value to 0.

**Comment by kitbellew** [comment]
@numero-744 my suggestion would be to socialize this request with the larger community on discord (who are normally quite conservative on adding new parameters), and if it doesn't get majority support, we'd have to close it.

my opinion, though is:

- mixing actual reserved keywords and simple functions which _look_ like keywords is not ideal; `when(a)` **is readable** and is exactly what's used in scalatest.
- `x.r init 0` looks more like dsl and has the fewest characters.

**Comment by tgodzik** [comment]
I would say that unless there is more users that would need this then I wouldn't add these new parameters.

**Comment by numero-744** [comment]
@kitbellew About `when(a)` being readable, how do you do to make things consistent with an `elsewhen`?

```scala
    when(c) { // no space before (
      o := i1
    } elsewhen (i0(0)) { // space before (
      o := i0
    } otherwise {
      o := 0
    }
```
