### ISSUE TITLE
3.7.0 removing parentheses in ctor and breaking compile

### ISSUE THREAD

**Issue by armanbilge** [scalameta/scalafmt#3438]
See:
- https://github.com/typelevel/spire/pull/1229

**Comment by xuwei-k** [comment]
- another example https://github.com/wartremover/wartremover/pull/762

**Comment by kitbellew** [comment]
@armanbilge @xuwei-k can you please help me with examples? i can't figure out from your links what was changed and how.

**Comment by armanbilge** [comment]
The diff after running scalafmt 3.7.0 is here: https://github.com/typelevel/spire/commit/daaac7babd555ca2496a2cf1de01142439339e79

**Comment by xuwei-k** [comment]
`.scalafmt.conf`

```conf
version = "3.7.0"
runner.dialect = Scala213
rewrite.rules = [RedundantParens]
```

A.scala

```scala
package x

class A(f: PartialFunction[Int, Int])

object A {
  val a = new A({ case x => x })
}
```

project/plugins.sbt

```scala
addSbtPlugin("org.scalameta" % "sbt-scalafmt" % "2.5.0")
```

run `sbt scalafmt`

```diff
 object A {
-  val a = new A({ case x => x })
+  val a = new A { case x => x }
 }
```

sbt compile after scalafmt

```
A.scala:6:19: illegal start of definition
[error]   val a = new A { case x => x }
[error]                   ^
[error] one error found
```

**Comment by kitbellew** [comment]
thank you both for the examples, fix under review.
