### ISSUE TITLE
3.7.0 issue with some function types

### ISSUE THREAD

**Issue by satorg** [scalameta/scalafmt#3442]
## Configuration (required) ##

```
version = "3.7.0"
runner.dialect=scala3
```

## Command-line parameters (required) ##

```
scalafmt -c scalafmt370_funtype_issue.conf scalafmt370_funtype_issue.scala
```

## Steps

```scala
val a = (b: Int => Int) => ???
```

## Problem

Scalafmt ***fails*** with the following error:

```
$ scalafmt -c scalafmt370_funtype_issue.conf scalafmt370_funtype_issue.scala 
/<full path omitted>/scalafmt370_funtype_issue.scala:1: error: [dialect scala3] ; expected but => found
val a = (b: Int => Int) => ???
                        ^
```

## Expectation

The Scalafmt should not fail on such a file – the file compiles by Scala v3.2.1 successfully.
Moreover, it only fails if `version="3.7.0"` AND `runner.dialect=scala3` OR `runner.dialect=scala3future`.
It does not fail for previous formatter versions (e.g. `version="3.6.1"`).
Neither it fails if `runner.dialect` is set to one of the `scala2*` dialects, including `scala213`, `scala213source3`, etc.

## Workaround

None 🤷 

## Notes

Initially it popped up in this PR: typelevel/cats#4377
Here in the issue is a simplified reproducible version.

**Comment by kitbellew** [comment]
Fixed in scalameta/scalameta#3052, will be in next release.
