### ISSUE TITLE
Is it possible to setup a priority between rules ? 

### ISSUE THREAD

**Issue by Driox** [scalameta/scalafmt#3457]
For instance how can I choose to have `align` to have higher / lower priority than `maxColumn` ?

`maxColumn` has higher priority
```
  private[this] def retry_count_cache_key(xxx: String) =
    s"some_very_very_very_very_very_long_string_$xxx"
  private[this] def retry_cache_key(xxx: String)       = s"some_short_string$xxx"
  private[this] val retry_timing_in_seconds            = 30 seconds
```

`align` has higher priority
```
  private[this] def retry_count_cache_key(xxx: String) = s"some_very_very_very_very_very_long_string_$xxx"
  private[this] def retry_cache_key(xxx: String)       = s"some_short_string$xxx"
  private[this] val retry_timing_in_seconds            = 30 seconds
```

**Comment by kitbellew** [comment]
in general, not possible. in this specific case, there's a parameter.

**Comment by tgodzik** [comment]
Out of curiosity, are you talking about  https://scalameta.org/scalafmt/docs/configuration.html#alignallowoverflow ?

**Comment by kitbellew** [comment]
> Out of curiosity, are you talking about https://scalameta.org/scalafmt/docs/configuration.html#alignallowoverflow ?

yes, that's the one.

**Comment by Driox** [comment]
> in general, not possible

Is it a choice by design or a technical limitation or  something else ?

**Comment by tgodzik** [comment]
> > in general, not possible
> 
> Is it a choice by design or a technical limitation or something else ?

I think this adds even more to complexity and it might hard to test all the possible rule interactions.
