### ISSUE TITLE
`align.allowOverflow` don't override `maxColumn`

### ISSUE THREAD

**Issue by Driox** [scalameta/scalafmt#3464]
Following the discussion in this issue https://github.com/scalameta/scalafmt/issues/3457 

- I can't make the parameters `align.allowOverflow` override `maxColumn`
- I also can't align def and val on the same token
    - nb: this used to work on previous version, like `3.5.9`

## Configuration (required) ##

```
version = "3.7.1"
project.git = true
runner.dialect = scala213
maxColumn = 120
align.preset = most
align.allowOverflow = true
align.multiline = true
continuationIndent {
  defnSite = 2
  extendSite = 2
  withSiteRelativeToExtends = 2
}
assumeStandardLibraryStripMargin = true
docstrings.style = keep
newlines.source = keep
lineEndings = preserve
includeCurlyBraceInSelectChains = true
danglingParentheses {
  defnSite = true
  callSite = true
  ctrlSite = true
}

spaces {
  inImportCurlyBraces     = true
  afterKeywordBeforeParen = false
}
optIn.annotationNewlines = true

rewrite.rules = [SortImports, PreferCurlyFors]
rewrite.redundantBraces.generalExpressions = false
rewrite.redundantBraces.methodBodies = false
rewrite.redundantBraces.includeUnitMethods = false
rewrite.redundantBraces.stringInterpolation = false

align.tokens.add = [
  { code = ":", owner = "Param" }
  { code = "=" }
  { code = "?|" }
  { code = "?|>" }
  { code = "|>" }
  { code = "withClue" }
]

```

## Command-line parameters (required) ##

When I run scalafmt via CLI like this: 

```
~/Dev/scala/sorus develop +2 !11 ?6 ❯ scalafmt                                                                                                                                                                                              11.0.12+0
'align.tokens.add' is deprecated; use align.tokens."+" instead.
Reformatting...
  100,0% [##########] 10 source files formatted
```

## Steps

Given code like this:
```scala
package helpers.sorus

import scala.concurrent.duration._

class AuthenticationService() {

  private[this] def retry_count_cache_key(xxx: String) = s"some_very_very_very_very_very_very_very_very_very_very_very_long_string_$xxx"
  private[this] def retry_cache_key(xxx: String) = s"some_short_string$xxx"
  private[this] val retry_timing_in_seconds = 30 seconds
  val x                                     = "some_very_very_very_very_very_very_very_very_very_very_very_very_very_very_very_very_very_very_veryvery_very_very_very_very_very_very_very_very_very_very_very_very_very_very_very_very_very_very_long_string"
  val xx                       = "àç098098"
  val xxx                               = "àç098098"
  val xxxxx                                 = "àç098098"

  def coucou(): Int = {
    println(s"""
      ${retry_count_cache_key("123")}
      ${retry_cache_key("123")}
      $retry_timing_in_seconds
    """)

    12
  }
}

```

## Problem

Scalafmt formats code like this:
```scala
package helpers.sorus

import scala.concurrent.duration._

class AuthenticationService() {

  private[this] def retry_count_cache_key(xxx: String) =
    s"some_very_very_very_very_very_very_very_very_very_very_very_long_string_$xxx"
  private[this] def retry_cache_key(xxx: String) = s"some_short_string$xxx"
  private[this] val retry_timing_in_seconds = 30 seconds
  val x                                     =
    "some_very_very_very_very_very_very_very_very_very_very_very_very_very_very_very_very_very_very_veryvery_very_very_very_very_very_very_very_very_very_very_very_very_very_very_very_very_very_very_long_string"
  val xx                                    = "àç098098"
  val xxx                                   = "àç098098"
  val xxxxx                                 = "àç098098"

  def coucou(): Int = {
    println(s"""
      ${retry_count_cache_key("123")}
      ${retry_cache_key("123")}
      $retry_timing_in_seconds
    """)

    12
  }
}

```

## Expectation

I would like the formatted output to look like this:
```scala
package helpers.sorus

import scala.concurrent.duration._

class AuthenticationService() {

  private[this] def retry_count_cache_key(xxx: String) = s"some_very_very_very_very_very_very_very_very_very_very_very_long_string_$xxx"
  private[this] def retry_cache_key(xxx: String)       = s"some_short_string$xxx"
  private[this] val retry_timing_in_seconds            = 30 seconds
  val x                                                = "some_very_very_very_very_very_very_very_very_very_very_very_very_very_very_very_very_very_very_veryvery_very_very_very_very_very_very_very_very_very_very_very_very_very_very_very_very_very_very_long_string"
  val xx                                               = "àç098098"
  val xxx                                              = "àç098098"
  val xxxxx                                            = "àç098098"

  def coucou(): Int = {
    println(s"""
      ${retry_count_cache_key("123")}
      ${retry_cache_key("123")}
      $retry_timing_in_seconds
    """)

    12
  }
}

```

# Note 

this is the output when I switch version to 3.5.9

- long string are still ko
- def and val are aligned according to `=`  

```scala
package helpers.sorus

import scala.concurrent.duration._

class AuthenticationService() {

  private[this] def retry_count_cache_key(xxx: String) =
    s"some_very_very_very_very_very_very_very_very_very_very_very_long_string_$xxx"
  private[this] def retry_cache_key(xxx: String)       = s"some_short_string$xxx"
  private[this] val retry_timing_in_seconds            = 30 seconds
  val x                                                =
    "some_very_very_very_very_very_very_very_very_very_very_very_very_very_very_very_very_very_very_veryvery_very_very_very_very_very_very_very_very_very_very_very_very_very_very_very_very_very_very_long_string"
  val xx                                               = "àç098098"
  val xxx                                              = "àç098098"
  val xxxxx                                            = "àç098098"

  def coucou(): Int = {
    println(s"""
      ${retry_count_cache_key("123")}
      ${retry_cache_key("123")}
      $retry_timing_in_seconds
    """)

    12
  }
}

```

**Comment by kitbellew** [comment]
@Driox there's only one parameter that can in some cases override maxColumn: https://scalameta.org/scalafmt/docs/configuration.html#newlinesavoidforsimpleoverflow. as the documentation for `align.allowOverflow` states, that parameter only applies if _without alignment_ the line didn't overflow. so this part works as expected.

i will take a look at def-vs-val.

**Comment by Driox** [comment]
Maybe I missunderstand something but in [this issue](https://github.com/scalameta/scalafmt/issues/3457) you tell me that `allowOverflow` can override `maxColumn `

> in general, not possible. in this specific case, there's a parameter.
> Out of curiosity, are you talking about https://scalameta.org/scalafmt/docs/configuration.html#alignallowoverflow ?
> yes, that's the one.

It's a very strange behaviour to have side by side
- some lines that align with an overflow
- some lines that can't align because of an overflow 

Is it possible to have a consistent behaviour ? possibly where align override maxColumn ?
Maybe with a plugin / extension / rewrite rules / other ?

**Comment by kitbellew** [comment]
@Driox allowOverflow was added 

> Maybe I missunderstand something but in [this issue](https://github.com/scalameta/scalafmt/issues/3457) you tell me that `allowOverflow` can override `maxColumn `

It doesn't override but it can ignore. If the line didn't overflow before alignment, then any overflow exclusively due to alignment is overridden. Without it, the line remained unaligned. But it is an `align.xxx` parameter and therefore does not apply during the main stage when line breaks are determined.

> It's a very strange behaviour to have side by side
> 
> * some lines that align with an overflow
> * some lines that can't align because of an overflow
> 
> Is it possible to have a consistent behaviour ? possibly where align override maxColumn ? Maybe with a plugin / extension / rewrite rules / other ?

I am not sure if there's a solution that can be called consistent. Even if we could figure out the technical side of things (as I said, alignment parameters apply only during the final stage when the previously formatted code is output, and not during the main stage when newlines are assigned), I'd say that abiding by maxColumn in some cases and completely ignoring it in others is quite inconsistent.

The only leeway we have allowed with maxColumn is when such overflow is either minor or inevitable anyway.

Can you please create a separate issue on def-vs-val in 3.5.9 and now, so I could close this discussion on maxColumn?

**Comment by Driox** [comment]
I create the issue for def vs val : https://github.com/scalameta/scalafmt/issues/3465

> alignment parameters apply only during the final stage when the previously formatted code is output, and not during the main stage when newlines are assigned

Is there documentation on the different formatting stages ?

**Comment by kitbellew** [comment]
> Is there documentation on the different formatting stages ?

Not really :)
