### ISSUE TITLE
scalafmt does not respect fileOverride with `rewrite.scala3` rules

### ISSUE THREAD

**Issue by carlosedp** [scalameta/scalafmt#3485]
## Configuration (required) ##

Please paste the contents of your `.scalafmt.conf` file here:
```
version = 3.7.2
runner.dialect = scala3

fileOverride {
  "glob:build.sc" {
     runner.dialect = scala213
  }
}

maxColumn = 120
align.preset = most
align.multiline = false
continuationIndent.defnSite = 2
continuationIndent.extendSite = 2
assumeStandardLibraryStripMargin = true
docstrings.style = Asterisk
docstrings.wrapMaxColumn = 80
lineEndings = preserve
includeCurlyBraceInSelectChains = false
danglingParentheses.preset = true
danglingParentheses.defnSite = true
danglingParentheses.callSite = true
danglingParentheses.exclude = [
  "`trait`"
]
align.tokens."+" = [
  {
    code = ":"
  }
]
optIn.annotationNewlines = true
newlines.beforeCurlyLambdaParams = false
newlines.alwaysBeforeMultilineDef = false
newlines.implicitParamListModifierForce = [before]
rewrite.trailingCommas.style = "always"
# rewrite.scala3.convertToNewSyntax = true
# rewrite.scala3.removeOptionalBraces = true

rewrite.rules = [
  RedundantBraces,
  RedundantParens,
  PreferCurlyFors
]

verticalMultiline.atDefnSite = true
verticalMultiline.arityThreshold = 100

rewrite.redundantBraces.generalExpressions = false
rewriteTokens = {
  "⇒": "=>"
  "→": "->"
  "←": "<-"
}
```

## Steps

If I uncomment the `rewrite.scala3` rules above, my `build.sc` which is a mill build file and uses Scala 2.13 syntax also get rewritten to Scala 3 even though it's listed in `fileOverride` section to use scala213 dialect.

**Comment by kitbellew** [comment]
I am fairly certain that the matching is on the full path name of the file (including all directories). and every unix path contains at least one `/`.

**Comment by carlosedp** [comment]
Oh it worked. Weird that it didn't complain about the syntax itself... only when I added the rewrite rules.

Thanks @kitbellew and sorry about the noise!

**Comment by carlosedp** [comment]
Just retested it and same happens with:

```
fileOverride {
  "glob:/build.sc" {
     runner.dialect = scala213
  }
}
```

**Comment by kitbellew** [comment]
what is the absolute file name? is it directly under the root partition?

**Comment by carlosedp** [comment]
It's in the root of the project... since it's a glob, I tried some variations and this worked:

```
fileOverride {
  "glob:**/build.sc" {
    runner.dialect = scala213
  }
}
```

Having the `**/build.sc` ignored the file on the rewrite.

**Comment by kitbellew** [comment]
> It's in the root of the project... since it's a glob, I tried some variations and this worked:

as i mentioned earlier, the match is on the entire absolute file name (`/foo/bar/your_project/build.sc`), it's not a substring match of any kind.
