### ISSUE TITLE
CLI: non-zero exit code for formatting failure

### ISSUE THREAD

**Issue by olafurpg** [scalameta/scalafmt#349]
The behavior of the CLI should be
- warning is printed out
- exit code is non-zero
- no stack trace (less noise, easier for text editor integrations to consume and present a helpful message to users)

when
- formatting failed, and
- the CLI is formatting only a single file, for example via `--stdin` or `-f foo.scala` (not `-f <directory>`)

The current behavior is a bit annoying if you really care about knowing if something went wrong

``` scala
$ cat foo.scala
object a {
$ cat foo.scala | scalafmt --stdin
[warn] Error in stdin.scala: <input>:1: error: } expected but end of file found
object a {
          ^
// exit code 0
```

If we want to be fancy, we could reuse [rustfmt](https://github.com/rust-lang-nursery/rustfmt/blob/master/README.md#running) conventions for exit codes:

> If `rustfmt` successfully reformatted the code it will exit with `0` exit
> status. Exit status `1` signals some unexpected error, like an unknown option or
> a failure to read a file. Exit status `2` is returned if there are syntax errors
> in the input files. `rustfmt` can't format syntatically invalid code. Finally,
> exit status `3` is returned if there are some issues which can't be resolved
> automatically. For example, if you have a very long comment line `rustfmt`
> doesn't split it. Instead it prints a warning and exits with `3`.

One possible way to achieve this is to:
- set `runner.fatalWarnings = tre` when `inputMethods.length == 1`
- catch the exception somewhere higher,
- print the error message to `common.err`,
- return appropriate int exit code (for example, change return type to Int instead of Unit here: https://github.com/olafurpg/scalafmt/blob/7ea32fd4141bfcd17acc9bb3cffaa48fc5af8e03/cli/src/main/scala/org/scalafmt/cli/Cli.scala#L47)
- `System.exit(returnCode)` somewhere at the end of the universe, where the tests don't run

**Comment by siddarth** [comment]
`--test` allegedly does this, but i don't think it works?

**Comment by olafurpg** [comment]
I updated the description to better reflect the current goals of this issue. `--test` is meant to run in CI, which is a bit different from what I had in mind for this ticket.
