### ISSUE TITLE
`newlines.beforeOpenParenDefnSite = unfold` unnecessarily wraps extension clause in the presence of a doc comment

### ISSUE THREAD

**Issue by djneades** [scalameta/scalafmt#3497]
## Configuration (required) ##
`.scalafmt.conf`:
```
version = "3.7.2"
maxColumn = 80

runner.dialect = scala3

newlines {
   beforeOpenParenDefnSite = unfold
}
```
## Command-line parameters (required) ##

When I run scalafmt via CLI like this: `scalafmt test.scala`

## Steps

Given code like this:
```scala
extension (s: String)

  /** ... */
  def foo(): Unit = ???
  def bar(): Unit = ???
```

## Problem

Scalafmt formats code like this:
```scala
extension
  (s: String)

  /** ... */
  def foo(): Unit = ???
  def bar(): Unit = ???
```

## Expectation

I should like the formatted output to look like this:
```scala
extension (s: String)

  /** ... */
  def foo(): Unit = ???
  def bar(): Unit = ???
```

## Workaround

n/a

## Notes

Since `extension (s: String)` easily fits on a single line, it should not be wrapped on to two lines even with `newlines.beforeOpenParenDefnSite = unfold`.

If the doc comment `/** ... */` is removed from before the `def foo()`, the formatting works as expected (except that there is no space after the `extension` keyword, but that may be configurable).

**Comment by kitbellew** [comment]
> Given that `spaces.afterKeywordBeforeParen` defaults to `true`, I am also not sure why (in the absence of the doc comment) the `extension` line is formatted to `extension(ef: EffectMsg)` rather than `extension (ef: EffectMsg)` using the above `.scalafmt.conf`. Am I misunderstanding something there?

please submit a separate issue.

**Comment by djneades** [comment]
> please submit a separate issue.

@kitbellew Done! Please see #3499.
