### ISSUE TITLE
Try-Finally without curlies formats funny

### ISSUE THREAD

**Issue by lihaoyi** [scalameta/scalafmt#350]
Original:

``` scala
object Foo {
  try loop(blocks, startingImports, Imports(), wrapperIndex = 1 )
  finally scriptImportCallback = outerScriptImportCallback
}
```

Scalafmt:

``` scala
object Foo {
  try loop(blocks, startingImports, Imports(), wrapperIndex = 1) finally scriptImportCallback =
    outerScriptImportCallback
}
```

I would like the input to look like this:

``` scala
object Foo {
  try loop(blocks, startingImports, Imports(), wrapperIndex = 1 )
  finally scriptImportCallback = outerScriptImportCallback
}
```

Using:
- 0.2.8
- `scalafmt -i -f Foo.scala`

Note that this seems peculiar to `try`/`finally`: I couldn't reproduce it with `if(true)`/`else`

**Comment by lihaoyi** [comment]
Related case

Before:
```scala
object Foo {
  try proc.waitFor()
  catch {case e: Throwable => run() }
}
```
After:
```scala
object Foo {
  try proc.waitFor() catch { case e: Throwable => run() }
}
```

Wanted:

```scala
object Foo {
  try proc.waitFor()
  catch {case e: Throwable => run() }
}
```

Again, this only seems to happen with `try`: replacing it with `if(true)`/`else` makes it behave as I want, keeping it spread over two lines

**Comment by olafurpg** [comment]
I only learned recently that it's even possible to skip curly braces in try/catch. This should be a straightforward fix.

**Comment by olafurpg** [comment]
Your examples work now. The only case I can't get to look good is when the catch is a single line partial function

```scala
object Foo {
  try loop(blocks, startingImports, Imports(), wrapperIndex = 1 )
  catch { case x => ??? }
  finally scriptImportCallback = outerScriptImportCallback
}
```

Solving that will be related to fixing #271. I don't think it's a common style so I'm gonna let that wait for a later release.

**Comment by ches** [comment]
Closed issue (and old at that), so @olafurpg let me know if this merits opening a new one, but commenting here because I'm assuming it stemmed from this change:

Original:

```scala
val template: String = try source.mkString finally source.close()
```

scalafmt:

```scala
val template: String = try source.mkString
finally source.close()
```

Quality or style of this code may be up for debate, but it came from a real-world code base. `try` is an expression after all, so it's a reasonable pattern. Workaround for now is to indent the assignment value and get the more decipherable:

```scala
val template: String =
  try source.mkString
  finally source.close()
```

**Comment by olafurpg** [comment]
Sure, this merits re-opening. Thanks for providing the workaround @ches
