### ISSUE TITLE
Invalid config entry in docs: rewrite.redundantBraces.defnBodies = true

### ISSUE THREAD

**Issue by pawelkaczor** [scalameta/scalafmt#3502]
Docs say:

### RedundantBraces: defnBodies

This parameter takes the following values:

- none: [....]
- all: [...]
- noParams: [...]

The example shows a different value (true):

![image](https://user-images.githubusercontent.com/41667/224638280-0fbf377f-b2cb-4931-9964-128a16c0a57e.png)

**Comment by kitbellew** [comment]
@pawelkaczor would you like to contribute the change you are looking for, to make it clearer? we simply thought that the docs explain what the parameter does and when, and the example shows what happens, and the comment just above mentions that this parameter used to be a boolean.

**Comment by pawelkaczor** [comment]
@kitbellew Perhaps I'm missing something but the example (the latest version) is just incorrect / invalid. Scalafmt (the latest version) won't work with it, right? If so, it should be fixed.

**Comment by kitbellew** [comment]
> @kitbellew Perhaps I'm missing something but the example (the latest version) is just incorrect / invalid. Scalafmt (the latest version) won't work with it, right? If so, it should be fixed.

The examples shown in the documentation are all actually working examples, as the formatting is provided by the underlying formatter library. So, it's not invalid; `true` is equivalent to `all`, that's... all.

**Comment by pawelkaczor** [comment]
@kitbellew  Ok, thank you for the clarification. I think we can close the issue.
