### ISSUE TITLE
Rule for vertical alignment of `if then else` blocks

### ISSUE THREAD

**Issue by 987Nabil** [scalameta/scalafmt#3516]
I suggest to have an option for vertical alignment of `if then else` blocks, that would reformat this
```scala
if x
then y
else z
```
to
```scala
if   x
then y
else z
```

Maybe also
```scala
if x
then y
else if a
then b
else if c
then d
else z
```
to

```scala
if      x
then    y
else if a
then    b
else if c
then    d
else    z
```

**Comment by kitbellew** [comment]
@987Nabil it's impossible currently. by our definition, you want to align x, y, z, a, b, c, d (and not if, then, else which are already aligned).

**Comment by 987Nabil** [comment]
@kitbellew so, if it is currently possible, then with which settings? I tried setting vertical alignment to the highest level and it keeps formating the rhs of the key words to exactly one space.

**Comment by kitbellew** [comment]
> @kitbellew so, if it is currently possible, then with which settings? I tried setting vertical alignment to the highest level and it keeps formating the rhs of the key words to exactly one space.

as i explained above, it's currently impossible. cannot be achieved. no settings.

**Comment by 987Nabil** [comment]
@kitbellew sorry I must have read it wrong. I thought you wrote `possible` 😅
