### ISSUE TITLE
verticalMultiline.arityThreshold setting is ignored (regression in v3.7.2)

### ISSUE THREAD

**Issue by agilesteel** [scalameta/scalafmt#3517]
The `verticalMultiline.arityThreshold` setting is ignored starting from `v3.7.2`. It worked for years including in `v3.7.1`.

```hocon
version = "3.7.2"
maxColumn = 100
runner.dialect = Scala213
verticalMultiline {
  arityThreshold = 3
  atDefnSite = yes
  newlineAfterOpenParen = yes
}
```

## Steps

Given code like this:
```scala
object Main {
  def main(args: Array[String]): Unit =
    println("hello world")
}
```

## Problem

Scalafmt formats code like this:
```scala
object Main {
  def main(
      args: Array[String]
    ): Unit =
    println("hello world")
}
```

## Expectation

I would like the formatted output to look like this since the arityThreshold is not reached:
```scala
object Main {
  def main(args: Array[String]): Unit =
    println("hello world")
}
```

**Comment by kitbellew** [comment]
is it a duplicate of #3509?

**Comment by agilesteel** [comment]
Yep, looks like it. Thanks! Closing it.
