### ISSUE TITLE
Format options for the `derives` keyword

### ISSUE THREAD

**Issue by gvolpe** [scalameta/scalafmt#3526]
## Configuration (required) ##

Please paste the contents of your `.scalafmt.conf` file here:

```
version = 3.7.3
runner.dialect = scala3
style = defaultWithAlign
maxColumn = 100
project {
  git = true
}
rewrite {
  scala3 {
    convertToNewSyntax = true
    removeOptionalBraces = true
    insertEndMarkerMinLines = 30
    removeEndMarkerMaxLines = 29
  }
  trailingCommas.style = never
}
fileOverride {
  "glob:**/build.sbt" {
    runner.dialect = scala213
  }
  "glob:**/project/**" {
    runner.dialect = scala213
  }
}
newlines.topLevelStatementBlankLines = [
  {
    minBreaks = 2
    blanks { before = 1 }
  }
]
```

## Command-line parameters (required) ##

When I run scalafmt via CLI like this: `scalafmt`

If you were not using CLI initially:
- please check using `scalafmt` CLI before submitting here (required) ✅ 

```console
$ scalafmt --version
scalafmt 3.7.3
```

## Steps

Given code like this:

```scala
case class Person(
    name: String,
    age: Int
) derives Eq, Show
```

## Problem

Scalafmt formats code like this:

```scala
case class Person(
    name: String,
    age: Int
) derives Eq, 
         Show
```

## Expectation

I would like the formatted output to look like this:

```scala
case class Person(
    name: String,
    age: Int
) derives Eq, Show
```

## Workaround

I could not find any workaround and the [derives test file](https://github.com/scalameta/scalafmt/blob/master/scalafmt-tests/src/test/resources/scala3/Derives.stat) doesn't seem to consider this use case.

**Comment by gvolpe** [comment]
@kitbellew thanks a lot, that did the trick! 

I was mainly searching for `derives` in the docs and didn't realize the config for `extends` would apply to it as well, might be worth adding that to the docs? Thanks again 🙇🏽

**Comment by gvolpe** [comment]
Re-opening this as I realized after applying this config to a large codebase, it doesn't exactly give us the result we would like.

While this is a decent workaround at the moment, do you think it would be possible to distinguish between `derives` and `extends`/`with` to have different configurations? e.g. in some codebases, we'd prefer something like this:

```scala
class Engine(dep: Dependency)
  extends IEngine 
  with LongClassNameFactory,
     AnotherLongTraitNameBean,
     LastButNotLeastBuilder

case class Person(
    name: String,
    age: Int
) derives Eq, Show
```

The current configuration `binPack.parentConstructors = Always` will format the `derives` part as desired, but the `extends` and `with` part will be inlined as follows (undesired).

```scala
class Engine(dep: Dependency)
  extends IEngine 
  with LongClassNameFactory, AnotherLongTraitNameBean, LastButNotLeastBuilder
```

**Comment by kitbellew** [comment]
no, there are too many parameters already and borderline unmanageable complexity, so we intentionally do not distinguish between similar concepts, such as extends/derives/with, or implicit/using.

**Comment by kitbellew** [comment]
> ```scala
> class Engine(dep: Dependency)
>   extends IEngine 
>   with LongClassNameFactory, AnotherLongTraitNameBean, LastButNotLeastBuilder
> ```

just to be sure: this last part fits within your desired 100 line length, correct? also, the parameter has more options than Always.

**Comment by tgodzik** [comment]
> > ```scala
> > class Engine(dep: Dependency)
> >   extends IEngine 
> >   with LongClassNameFactory, AnotherLongTraitNameBean, LastButNotLeastBuilder
> > ```
> 
> just to be sure: this last part fits within your desired 100 line length, correct? also, the parameter has more options than Always.

I might be wrong but I think we might want to drop `with` in that regards from Scala 3 though someone from the compiler should confirm.

**Comment by tgodzik** [comment]
Confirmed it with a colleague. At some point it will be replaced completely with `,`, but probably not any time soon.
