### ISSUE TITLE
Newlines keep reverts to binpack

### ISSUE THREAD

**Issue by ekrich** [scalameta/scalafmt#3529]
## Configuration (required) ##
scalafmt 3.7.3

Refer to the following branch.
https://github.com/ekrich/sblas/tree/topic/api

Please paste the contents of your `.scalafmt.conf` file here:

https://github.com/ekrich/sblas/blob/topic/api/.scalafmt.conf

## Command-line parameters (required) ##

I run scalafmt to check one file via shift-option-f in VSCode
or via the command line at the base of the project via
scripts/scalafmt

See: https://github.com/ekrich/sblas/blob/topic/api/scripts/scalafmt

## Steps

As seen here: 
https://github.com/ekrich/sblas/blob/topic/api/sblas/src/test/scala/org/ekrich/blas/apitest/BlasApiTest.scala#L31-L64

Given code like this:
```scala
val A = Array(
      0.11f, 0.12f, 0.13f,
      0.21f, 0.22f, 0.23f)

    val ldb = 2

    val B = Array(
      1011f, 1012f,
      1021f, 1022f,
      1031f, 1032f)

    val ldc = 2

    val C = Array(
      0.00f, 0.00f,
      0.00f, 0.00f)

    /* Compute C = A B */

    cblas_sgemm (
      CblasRowMajor,
      CblasNoTrans, CblasNoTrans, 2, 2, 3,
      1.0f, A.at(0), lda, B.at(0), ldb, 0.0f, C.at(0), ldc);
```

## Problem

Scalafmt formats code like this:
```scala
    val A = Array(
      0.11f, 0.12f, 0.13f,
      0.21f, 0.22f, 0.23f)

    val ldb = 2

    val B = Array(
      1011f, 1012f,
      1021f, 1022f,
      1031f, 1032f)

    val ldc = 2

    val C = Array(
      0.00f,
      0.00f,
      0.00f,
      0.00f
    )

    /* Compute C = A B */

    cblas_sgemm(
      CblasRowMajor,
      CblasNoTrans,
      CblasNoTrans,
      2,
      2,
      3,
      1.0f,
      A.at(0),
      lda,
      B.at(0),
      ldb,
      0.0f,
      C.at(0),
      ldc
    )
```

## Expectation

I would like the code to stay formatted as is in the input.

## Workaround

Insert this before the third matrix (Array)
`// format: off`

## Notes
N/A

**Comment by kitbellew** [comment]
> ```scala
>     val C = Array(
>       0.00f, 0.00f,
>       0.00f, 0.00f)
> 
>     cblas_sgemm (
>       CblasRowMajor,
>       CblasNoTrans, CblasNoTrans, 2, 2, 3,
>       1.0f, A.at(0), lda, B.at(0), ldb, 0.0f, C.at(0), ldc);
> ```

Several reasons:

- you don't have any `binPack` parameters set explicitly hence only defaults
- the formatting you observe (or don't observe) is due to https://scalameta.org/scalafmt/docs/configuration.html#literal-argument-lists
- your first example (`val C`) contains 4 arguments which is less than `binPack.literalsMinArgCount = 5`, which is how it's different from `val A` and 'val B` which both contain 6 arguments;
- your second example (`cblas_sgemm`) contains `A.at(0)` which is not considered a literal by default, hence literal binpacking does not apply (you could enable `binPack.literalsIncludeSimpleExpr` for that).

So, it looks like it works as expected. Feel free to close or follow up.

**Comment by ekrich** [comment]
Thank-you for your help.

This is obviously the user not really understanding how all the features fit together so I will document it here so people can see the logic in this `binpack` approach. The use case is that line breaks in linear n-dimensional matrices mean something so we would like to preserve that. Scalafmt still adjusts indent, spacing, and wrapping if too long. In the function call site above the grouping of args may make sense for the function be called so we want to allow that. This may go against ideas about formatting but it makes sense in this context.

```properties
# allows binPack call site to be formatted with 
# args binpacked or one for each arg if desired.
newlines.source = keep

# binPack args  for more control
# matrix can have two element
# one col for row order or one line for column order
binPack.literalsMinArgCount = 2
binPack.literalsIncludeSimpleExpr = true
binPack.unsafeCallSite = true # allow user wrapping at call sites
```
