### ISSUE TITLE
`RedundantBraces` rewrite removes parentheses that are required syntactically

### ISSUE THREAD

**Issue by mrdziuban** [scalameta/scalafmt#3540]
## Configuration (required) ##

```
version = "3.7.3"
runner.dialect = scala213
rewrite.rules = [RedundantBraces]
```

## Command-line parameters (required) ##

```bash
scalafmt --config /path/to/.scalafmt.conf /path/to/Foo.scala
```

## Steps

Given code like this:

```scala
class Foo[A](f: A => Unit)
object Bar extends Foo[(Int, String)]({ case (i, s) => () })
```

## Problem

Scalafmt removes the parentheses around the function passed to the `Foo` constructor, like this:

```scala
class Foo[A](f: A => Unit)
object Bar extends Foo[(Int, String)] { case (i, s) => () }
```

## Expectation

The parentheses should remain as they're required for the syntax to be valid. Maybe this is a nuance of functions passed to class constructors.

## Workaround

Other than disabling the `RedundantBraces` rewrite, the only other workaround I've found is to add a `// format: off` comment to disable scalafmt on this code.

**Comment by DorQuendi** [comment]
I have the same issue, where redundant braces are removed, where they are required by the syntax. Specifically in two cases.
1. code with multiple parameter sets followed by dot notation call
`(a(x)(y)).call(...)`
is rewritten to invalid syntax:
`a(x)(y).call(...)`
2. braces are removed also from constructors with 0 parameters:
`ClassA()`
is rewritten to:
`ClassA`
While this is ok in scala, it is an issue when using native Java classes.
