### ISSUE TITLE
Consider changing the default behavior when no version is set

### ISSUE THREAD

**Issue by ckipp01** [scalameta/scalafmt#3543]
## Configuration (required) ##

You can mimic what I'm about to show by just having an empty `.scalafmt.conf` file.

The version of the scalafmt cli that I'm using to test this is `3.7.3`.

## Steps

1. Have an empty `.scalafmt.conf` file in a workspace
2. Use `scalafmt .` to attempt to format that workspace
3. You'll see the error below:

```
error: missing version (current 3.7.3)
```

## Problem

I ironically hit on this about a week ago and knew that I screwed up and must have left my version empty. However recently I came across [this thread](https://fosstodon.org/@mo8it/110396291266757088) where a newcomer to the language hit on this and it wasn't clear at all what they should do about it. For those familiar to scalafmt, it may be super obvious that you need to add the version to the `.scalafmt.conf` file, but how would a newcomer know that?

## Expectation

I'd expect at the very least maybe a more detailed message like:

```
error: missing version (current 3.7.3)

To fix this, you should add the following to your .scalafmt.conf file:
version = 3.7.3
```

Another option would be to just add it for them. Since they don't currently have one, maybe just

1. assume the latest and format with it
2. add that version to the `.scalafmt.conf` file
3. give an info message to the user that you did that

**Comment by kitbellew** [comment]
i can add an extra sentence to the error message.

however, i don't think we should manipulate the configuration file.

i also don't think we should assume any defaults, this was the case before and we intentionally removed this. multiple users of the codebase might have a different version of the formatter installed, and each of them might end up with a slightly different result which would then be inadvertently and intentionally sent for review, or simply merged.

**Comment by kitbellew** [comment]
also, version is not the only required option. scala dialect must also be specified, and there's no default.

**Comment by ckipp01** [comment]
> however, i don't think we should manipulate the configuration file.

Do you maybe have some reasoning as to why? Scalafmt is in the perfect to position to know _what_ is missing. I'm assuming in this case where there is no version set, setting a version would be pretty harmless, and also ensure that it's consistently being used in the future. Maybe if the worry is changing it without really giving the user a choice, we could do that? Is it possible with the CLI library to prompt a use with something like?

```
You have no version set for scalafmt. The latest is 3.7.3. Would you like us to update your .scalafmt.conf?

1. yes
2. no
```

No idea if that's possible.

> i also don't think we should assume any defaults, this was the case before and we intentionally removed this. 

Sure, but by inserting the version you wouldn't be relying on a default, but rather the newly added version.

> also, version is not the only required option. scala dialect must also be specified, and there's no default.

The same thing as above could apply here then. It'd be amazing to just have

```
You have no dialect set. Which would you like to use?

1. scala3
2. scala213
3. scala212
```

And let the user just choose and their config file gets updated to reflect it.

**Comment by kitbellew** [comment]
> Do you maybe have some reasoning as to why? Scalafmt is in the perfect to position to know _what_ is missing.

Yes, it knows _what_ is missing but...

> I'm assuming in this case where there is no version set, setting a version would be pretty harmless, and also ensure that it's consistently being used in the future. Maybe if the worry is changing it without really giving the user a choice, we could do that? Is it possible with the CLI library to prompt a use with something like?

... it doesn't know _where_ it's missing; so in addition to providing choices on values for various parameters, it would also have to ask where the user wants to store that; `.scalafmt.conf`, even by default, can be stored in multiple locations, and there's a search hierarchy. And on top of that, scalafmt would then have to add the new configuration file to source version control system (otherwise the result is pointless), which is not something it can do in all fairness.

Speaking of the "scala rant" on the linked thread: if the user figured out how to install the tooling (download the binary or configure the sbt plugin), knowing to create a configuration file is as trivial (or as difficult). Editing a file is a basic operation that anyone should be able to do; I modified the error message to rephrase the recommendation, to make it as prescriptive as possible.
