### ISSUE TITLE
Keep the continuation/chain indented with the first call

### ISSUE THREAD

**Issue by almulalic** [scalameta/scalafmt#3558]
## Configuration (required) ##

Please paste the contents of your `.scalafmt.conf` file here:
```
version = 3.7.4
align = some
maxColumn = 150
rewrite.rules = [SortImports, PreferCurlyFors ]
...
```

Im using it with VSCode through the metal plugin

## Problem

Scalafmt formats code like this:
```scala
var data = df.read
  .format(
    "org.apache.spark.sql.execution.datasources.json.JsonFileFormat"
  )
  .load(data_path)
```

## Expectation

I would like the formatted output to look like this:
```scala
var data = df.read
                     .format(
                         "org.apache.spark.sql.execution.datasources.json.JsonFileFormat"
                     )
                    .load(data_path)
```
or
```
var data = df
                     .read
                     .format(
                         "org.apache.spark.sql.execution.datasources.json.JsonFileFormat"
                     )
                    .load(data_path)
```

## Workaround

Only hardcoding the offset works, which is sadly not what im looking for. For example setting indent.main, I would like for it to be dynamic, something like:
indent.main = lineBeforeNewline.length+2

## Notes

Tried to go through documentation but I didn't fint anything that works. If older versions supported something like this I would

**Comment by almulalic** [comment]
I tried to delete the boilerplate but missed couple of them, sorry :)

**Comment by kitbellew** [comment]
please discuss this on scalafmt discord channel, and if there's support for this, please re-open.
