### ISSUE TITLE
version 3.7.5 breaks extension functions

### ISSUE THREAD

**Issue by lenguyenthanh** [scalameta/scalafmt#3568]
The new version seems to break some extension functions code in this [pr](https://github.com/lichess-org/scalachess/pull/433/files)

## Configuration (required) ##

```
version = "3.7.5"
runner.dialect = scala3

align.preset = more
maxColumn = 110
spaces.inImportCurlyBraces = true
rewrite.rules = [SortImports, SortModifiers]
rewrite.redundantBraces.stringInterpolation = true
project.excludeFilters = [
  "FullOpeningPart*"
  "EcopeningDB.scala"
  "Fixtures.scala"
]
docstrings.style = keep // don't format comment
```
## Command-line parameters (required) ##

`sbt scalafmtAll`

## Steps

Given code like this:
```scala
object File extends OpaqueInt[File]:
  extension (a: File)
    inline def index: Int = a

    inline def offset(delta: Int): Option[File] =
      if (-8 < delta && delta < 8) atIndex(a + delta)
      else None
```

## Problem

Scalafmt formats code like this:
```scala
object File extends OpaqueInt[File]:
  extension (a: File) inline def index: Int = a

  inline def offset(delta: Int): Option[File] =
    if (-8 < delta && delta < 8) atIndex(a + delta)
    else None

```

More examples in this pr: https://github.com/lichess-org/scalachess/pull/433/files.

I tried to make a smaller example but it works fine.

## Expectation

I would like the formatted output to look the same as before

**Comment by kitbellew** [comment]
Fixed in scalameta/scalameta#3218.
