### ISSUE TITLE
scalafmt output code results in "illegal start of simple expression" 

### ISSUE THREAD

**Issue by Atry** [scalameta/scalafmt#3589]
## Configuration (required) ##

```
runner.dialect = scala3
version = "3.7.10"
maxColumn = 80
```

## Command-line parameters (required) ##

When I run scalafmt via CLI like this: `scalafmt --non-interactive --mode changed`

## Steps

Given code like this:
```scala
    def withFilter(condition: A => Boolean): BindingSeq.WithFilter[A] = macro Macros.withFilter
```

## Problem

Scalafmt formats code like this:
```scala
    def withFilter(condition: A => Boolean): BindingSeq.WithFilter[A] = macro
      Macros.withFilter
```

It's illegal Scala code, resulting in errors:

```
[error] /home/runner/work/Binding.scala/Binding.scala/Binding/shared/src/main/scala-2/com/thoughtworks/binding/Binding2Or3.scala:188:1: illegal start of simple expression
[error]       Macros.withFilter
[error] ^
```

See https://github.com/ThoughtWorksInc/Binding.scala/actions/runs/5570178953/jobs/10174036016?pr=521 for full log
## Expectation

I would like the formatted output to look like this:
```scala
    def withFilter(condition: A => Boolean): BindingSeq.WithFilter[A] =
      macro Macros.withFilter
```

**Comment by kitbellew** [comment]
@Atry what is the compiler version you are running? this was an intentional change based on #3188, is it possible it was changed in a later version of scala3? cc @tgodzik

**Comment by tgodzik** [comment]
Looks like this doesn't work for Scala 2, maybe it doesn't allow macro on the next line? It seems it's the newest Scala 2.13.11 that it's failing on.

**Comment by kitbellew** [comment]
@Atry 

> ```
> runner.dialect = scala3
> version = "3.7.10"
> maxColumn = 80
> ```

@tgodzik 

> Looks like this doesn't work for Scala 2, maybe it doesn't allow macro on the next line? It seems it's the newest Scala 2.13.11 that it's failing on.

so if the compiler is scala2, then the dialect cannot be scala3.

**Comment by kitbellew** [comment]
> What dialect should a project cross-built between Scala 2 and Scala 3 use?
> 
> For example, some code is portable between Scala 2 and Scala 3, and some other code is works for specific Scala version. https://github.com/ThoughtWorksInc/Binding.scala/tree/12.x/Binding/shared/src/main

_some_ code is portable but macros, to be portable, have to be on one line (scala 2 doesn't allow break after `macro`, and scala 3 before), and the formatter can't guarantee that.

**Comment by tgodzik** [comment]
I think the best option here might be to turn off formatting for that part of code, especially since it will rarely need to be changed.

**Comment by kitbellew** [comment]
> I think the best option here might be to turn off formatting for that part of code, especially since it will rarely need to be changed.

excellent suggestion! that should fix the problem.
