### ISSUE TITLE
formatter breaks code, making it non-compilable with indent.fewerBraces = beforeSelect and indent.significant = 1

### ISSUE THREAD

**Issue by unkarjedy** [scalameta/scalafmt#3590]
`.scalafmt.conf`:
```
version = 3.7.10

runner.dialect = Scala3
indent.significant = 3
indent.fewerBraces = beforeSelect
```

before:
```scala
class test:
   foo1:
        2 + 2
   .foo0

export Foo.*
object Foo {
  def foo0: Foo.type = ???
  def foo00(): Foo.type = ???
  def foo1(i: Int): Foo.type = ???
}
```

after:
```scala
class test:
   foo1:
        2 + 2
     .foo0

export Foo.*
object Foo {
  def foo0: Foo.type = ???
  def foo00(): Foo.type = ???
  def foo1(i: Int): Foo.type = ???
}
```

<img width="560" alt="image" src="https://github.com/scalameta/scalafmt/assets/3989292/201ac558-ba11-468d-b3b2-7ac8b8d90cbf">

That's actual for many other "beforeSelect" tests in [OptionalBraces](https://github.com/scalameta/scalafmt/blob/bb93f55d0585c63842931649f8ca17d560afcc44/scalafmt-tests/src/test/resources/scala3/OptionalBraces.stat#L8)

**Comment by unkarjedy** [comment]
Faced a similar issue when working on IntelliJ Formatter:
https://youtrack.jetbrains.com/issue/SCL-20780/formatter-handle-fewer-braces-syntax#focus=Comments-27-7334769.0-0

**Comment by tgodzik** [comment]
Thanks for reporting! Which compiler version are you using?

**Comment by kitbellew** [comment]
@unkarjedy what's the compiler version? this functionality was added very recently to the compiler, 3.3.1-rc1 or something like that

**Comment by unkarjedy** [comment]
Ah, I was using Scala 3.3.0.
Indeed, it works fine with 3.3.1-RC1

**Comment by unkarjedy** [comment]
Will leave it here FTR: https://github.com/lampepfl/dotty/pull/17056

**Comment by unkarjedy** [comment]
Indeed. I was blind to the warning.

**Comment by unkarjedy** [comment]
Though, if you use `indent.significant = 1` the issue still exist:
```
version = 3.7.10
runner.dialect = Scala3
indent.significant = 1
indent.fewerBraces = beforeSelect
```

before:
```scala
class test:
 foo1:
  2 + 2
 .foo0
```
after:
```scala
class test:
 foo1:
    2 + 2
   .foo0
```

<img width="534" alt="image" src="https://github.com/scalameta/scalafmt/assets/3989292/cbbf62b1-7d6f-4953-88a1-223ef70c41fe">

**Comment by unkarjedy** [comment]
I don't have a strong preference here. 
One solution could be to not add indent in this case, even when `indent.fewerBraces = beforeSelect` or `always`
