### ISSUE TITLE
Do not insert space after arity-0 infix operator, before parens

### ISSUE THREAD

**Issue by georgms** [scalameta/scalafmt#3607]
## Configuration (required) ##

Please paste the contents of your `.scalafmt.conf` file here:
```
version = 3.7.12
runner.dialect = scala212
maxColumn = 120
```

## Command-line parameters (required) ##

When I run scalafmt via CLI like this: `coursier launch scalafmt`

## Steps

Given code like this:
```scala
val logger = mock[Logger]
logger.warn(any) shouldDoNothing()
```

## Problem

Scalafmt formats code like this:
```scala
val logger = mock[Logger]
logger.warn(any) shouldDoNothing () // Note the extra space after `shouldDoNothing`
```

## Expectation

I would like the formatted output to look like this:
```scala

val logger = mock[Logger]
logger.warn(any) shouldDoNothing()
```

## Workaround

–

## Notes

Note that `shouldDoNothing` is an arity-0 macro provided by Mockito Scala:

```scala
def shouldDoNothing(): Unit = macro DoSomethingMacro.doesNothing
```

**Comment by kitbellew** [comment]
1. this was already discussed in #3385.
2. why should arity-0 be treated differently from arity-2?
