### ISSUE TITLE
Blank lines are not removed in case of single import line

### ISSUE THREAD

**Issue by andrew-selvia** [scalameta/scalafmt#3631]
## Configuration (required) ##

```hocon
newlines.topLevelStatementBlankLines = [{ blanks = -1 }]
runner.dialect = scala3
version = 3.7.14
```

## Command-line parameters (required) ##

No special parameters; just calling `scalafmt` as installed via Coursier:
```shell
scalafmt A.scala
```

## Steps

Given code like this:
```scala
package org.scalafmt

import scala.*

object A
```

## Problem

Scalafmt formats code like this:
```scala
package org.scalafmt

import scala.*

object A
```

## Expectation

I would like the formatted output to look like this:
```scala
package org.scalafmt

import scala.*
object A
```

## Workaround

I've found that by adding a second import statement:
```scala
package org.scalafmt

import scala.*
import scala.*

object A
```

the code is formatted as expected:
```scala
package org.scalafmt

import scala.*
import scala.*
object A
```

**Comment by kitbellew** [comment]
please take a look at the `minBreaks` parameter: https://scalameta.org/scalafmt/docs/configuration.html#newlinestoplevelstatementblanklines

**Comment by andrew-selvia** [comment]
Thanks @kitbellew!

For anyone who stumbles upon this, here's the solution:
```hocon
newlines.topLevelStatementBlankLines = [{
  blanks = -1
  minBreaks = 0
}]
runner.dialect = scala3
version = 3.7.14
```
