### ISSUE TITLE
Using `--stdin` (without `--stdout`) sometimes does not cause formatted output to go to stdout

### ISSUE THREAD

**Issue by undergroundquizscene** [scalameta/scalafmt#3632]
- [X] latest version of CLI and latest version in `.scalafmt.conf`

## Configuration (required) ##

Please paste the contents of your `.scalafmt.conf` file here:
```
version = 3.7.14
runner.dialect=scala213

maxColumn = 120
trailingCommas = always
align.preset = none
fileOverride {
  "glob:**/support-internationalisation/src/test/scala/**" {
     runner.dialect = scala3
  }
  "glob:**/support-internationalisation/src/main/scala/**" {
     runner.dialect = scala3
  }
}
```

## Steps

Given Something.scala:

```scala
class Something() {
  def something() = {}
}
```

Running `scalafmt --debug Something.scala` produces this output and the file does not change (**as expected**):

```
Using core runner [3.7.14]
Working directory: /Users/emily_bourke/code/support-frontend/support-frontend/app/utils
parsed config (v3.7.14)
Files to be formatted:
/Users/emily_bourke/code/support-frontend/support-frontend/app/utils/Something.scala
```

Running `scalafmt --debug --stdout Something.scala` produces this output and the file does not change (**as expected**):

```
Using core runner [3.7.14]
Working directory: /Users/emily_bourke/code/support-frontend/support-frontend/app/utils
parsed config (v3.7.14)
Files to be formatted:
/Users/emily_bourke/code/support-frontend/support-frontend/app/utils/Something.scala
class Something() {
  def something() = {}
}
```

Running `cat Something.scala | scalafmt --debug --stdin --stdout` produces this output and the file does not change (**as expected**):

```
Using core runner [3.7.14]
Working directory: /Users/emily_bourke/code/support-frontend/support-frontend/app/utils
parsed config (v3.7.14)
class Something() {
  def something() = {}
}
```

Based on the help documentation (which says `scalafmt --stdin # read from stdin and print to stdout`) I would expect removing `--stdout` to make no difference, but running `cat Something.scala | scalafmt --debug --stdin` produces the following output and the file does not change. 

```
Using core runner [3.7.14]
Working directory: /Users/emily_bourke/code/support-frontend/support-frontend/app/utils
parsed config (v3.7.14)
```

**Why is the file not output onto stdout in this case?** (This happens when the file is correctly formatted, and mostly doesn’t happen (or never happens – not sure) if the file needs formatting.)

## Workaround

I can add the `--stdout` flag (and raise a PR to do that in `format-all-mode`).

## Notes

- I’m using fish as my shell
- I came across this problem while using [format-all-mode](https://github.com/lassik/emacs-format-all-the-code) in Doom Emacs
- Explanation and documentation of this behaviour would be acceptable to me instead of changing it

**Comment by kitbellew** [comment]
`--stdin` does not imply `--stdout`. the help needs to be adjusted.

**Comment by undergroundquizscene** [comment]
> `--stdin` does not imply `--stdout`. the help needs to be adjusted.

Perfect, thanks for clarifying :)
