### ISSUE TITLE
[Feature request] Align equals sign in case class explicit field assignment

### ISSUE THREAD

**Issue by lucasasalmins** [scalameta/scalafmt#3638]
## Configuration (required) ##

Please paste the contents of your `.scalafmt.conf` file here:
```
version=2.5.2
align = most
maxColumn = 160
```
## Problem

Scalafmt formats code like this:
```scala
val john = Person(
  name = "John",
  age = 24,
  address = Address(...)
)
```

## Expectation

I would like the formatted output to look like this:
```scala
val john = Person(
  name    = "John",
  age     = 24,
  address = Address(...)
)
```

## Workaround

I find the aligned `=` supremely more readable, especially for larger case classes. I use `// format: off / on` to manually achieve this but would love scalafmt to handle this for me like gofmt does for example

Has this ever been raised, is it possible, what are your thoughts?

**Comment by kitbellew** [comment]
default configuration is insufficient, you could try additional parameters.

**Comment by lucasasalmins** [comment]
Hey @kitbellew, thanks for the reply. I'm not sure what you mean, would you mind elaborating?

**Comment by kitbellew** [comment]
there are a number of parameters which are not used in your case, you could try them. they're described here: https://scalameta.org/scalafmt/docs/configuration.html
