### ISSUE TITLE
Add prefix group support

### ISSUE THREAD

**Issue by He-Pin** [scalameta/scalafmt#3639]
I want to group the import with some prefix group, and the result should be something like :

```scala
import org.apache.pekko
import pekko.dispatch.ExecutionContexts
import pekko.stream.ActorAttributes.SupervisionStrategy
import pekko.stream.Attributes.{ Name, SourceLocation }
import pekko.stream.MapAsyncPartitioned._
```

Is that possible? thanks.

**Comment by kitbellew** [comment]
alas, no.

**Comment by He-Pin** [comment]
...... @kitbellew Why close it? People can contribute a rule I think.

**Comment by kitbellew** [comment]
this type of rule is best reserved for scalafix, as it requires semantic understanding. scalafmt doesn't know that pekko.xyz is in reality org.apache.pekko.xyz if one goes after the other (but not the other way around). but also not that if there is an intervening import again. when it comes to relative imports, scalafmt prefers not to be involved.
