### ISSUE TITLE
`fileOverride` `PathMatcher` not being respected?

### ISSUE THREAD

**Issue by KaranAhlawat** [scalameta/scalafmt#3661]
## Configuration (required) ##

```
version = 3.7.14
runner.dialect = scala3
fileOverride {
  ".sc" {
    runner.dialect = scala213
  }
}
rewrite {
  rules = [RedundantBraces]
  scala3 {
    convertToNewSyntax = true
    removeOptionalBraces = yes
  }
}
indent.defnSite = 2
```

## Command-line parameters (required) ##

`cat build.sc | scalafmt-native --config .scalafmt.conf --stdin`

## Steps

Given code like this:
```scala
import os.Path
import mill._
import mill.scalalib._
import mill.scalalib.scalafmt.ScalafmtModule

import $file.deps

object modules extends Module {
  object core extends ScalaModule {
    def scalaVersion = "3.3.1"
    def scalacOptions = T(deps.compilerOptions)
    def ivyDeps = Agg(
      ivy"org.typelevel::cats-core:${deps.catsVersion}",
      ivy"org.typelevel::cats-effect:${deps.catsEffectVersion}",
      ivy"org.typelevel::squants:${deps.squantsVersion}",
      ivy"io.github.iltotore::iron:${deps.ironVersion}",
      ivy"dev.optics::monocle-core:${deps.monocleVersion}",
      ivy"com.github.cb372::cats-retry:${deps.catsRetryVersion}",
      ivy"org.typelevel::log4cats-slf4j:${deps.log4CatsVersion}"
    )
  }
}
```

## Problem

Scalafmt formats code like this:
```scala
import os.Path
import mill.*
import mill.scalalib.*
import mill.scalalib.scalafmt.ScalafmtModule

import $file.deps

object modules extends Module:
  object core extends ScalaModule:
    def scalaVersion = "3.3.1"
    def scalacOptions = T(deps.compilerOptions)
    def ivyDeps = Agg(
      ivy"org.typelevel::cats-core:${deps.catsVersion}",
      ivy"org.typelevel::cats-effect:${deps.catsEffectVersion}",
      ivy"org.typelevel::squants:${deps.squantsVersion}",
      ivy"io.github.iltotore::iron:${deps.ironVersion}",
      ivy"dev.optics::monocle-core:${deps.monocleVersion}",
      ivy"com.github.cb372::cats-retry:${deps.catsRetryVersion}",
      ivy"org.typelevel::log4cats-slf4j:${deps.log4CatsVersion}"
    )
```

## Expectation

I would like the formatted output to look like this:
```scala
import os.Path
import mill._
import mill.scalalib._
import mill.scalalib.scalafmt.ScalafmtModule

import $file.deps

object modules extends Module {
  object core extends ScalaModule {
    def scalaVersion = "3.3.1"
    def scalacOptions = T(deps.compilerOptions)
    def ivyDeps = Agg(
      ivy"org.typelevel::cats-core:${deps.catsVersion}",
      ivy"org.typelevel::cats-effect:${deps.catsEffectVersion}",
      ivy"org.typelevel::squants:${deps.squantsVersion}",
      ivy"io.github.iltotore::iron:${deps.ironVersion}",
      ivy"dev.optics::monocle-core:${deps.monocleVersion}",
      ivy"com.github.cb372::cats-retry:${deps.catsRetryVersion}",
      ivy"org.typelevel::log4cats-slf4j:${deps.log4CatsVersion}"
    )
  }
}
```

This is because the indentation syntax is not a part of Scala 2.13

## Notes

As mentioned in #3660, `fileOverride` takes a `PathMatcher` pattern which is a glob or a regex. However, looking at the `scalafmt` website, it mentions that since `v3.2.0`, you can provide a `.ext` inside the `fileOverride` (here is the snippet from the website):

(since v3.2.0) setting only the dialect:

    fileOverride { "glob:**/*.sbt" = sbt1 }

(since v3.2.0) setting based on the file extension:

    fileOverride { ".sbt" { runner.dialect = sbt1 } }
    this is simply a shortcut for glob:**.ext

I also tried `glob:**.sc`, also to no effect.

**Comment by kitbellew** [comment]
@KaranAhlawat thank you for submitting detailed, well-documented reports. However, please take some time and assume first that there is no bug, and look for an explanation elsewhere, just like in the previous case. Only if you completely exhaust that, do submit another issue.

Now, about this problem. Since you insist on piping code to the formatter, it has no way of knowing the name of the file.

**Comment by KaranAhlawat** [comment]
Thank you again, and I'm very sorry for the unprofessional behavior. You're right, I should have taken more time to analyze the issue, and will do so in the future 😅
