### ISSUE TITLE
The `rewrite.redundantBraces.stringInterpolation = false` has no effect

### ISSUE THREAD

**Issue by iilyak** [scalameta/scalafmt#3673]
## Configuration (required) ##

Please paste the contents of your `.scalafmt.conf` file here:
```
# I am always confused with the names of things so here is a little
# cheatsheet
#
# [ Brackets ]
# { Braces }
# ( Paranthesis )

version = "3.7.15"
maxColumn = 120
align.preset = more
align.multiline = false
continuationIndent.defnSite = 2
assumeStandardLibraryStripMargin = true
docstrings.style = Asterisk
docstrings.wrapMaxColumn = 120
lineEndings = preserve
includeCurlyBraceInSelectChains = false
danglingParentheses.preset = true
optIn.annotationNewlines = true
newlines.alwaysBeforeMultilineDef = false
runner.dialect = scala213
rewrite.rules = [RedundantBraces]

#
# Require { braces } for functions
#
# ```scala
# def f() = {
#  1 + 1
# }
# ```
rewrite.redundantBraces.defnBodies = false

#
# Forbid removal of { braces } in following code
#
# while (x < 10) {
#   x += 1
# }
#
rewrite.redundantBraces.generalExpressions = false

#
# Require { braces } in string interpolations
# ```scala
# s"user id is ${id}"
# ```
#
# Note: Unfortunatelly this setting doesn't work
#  So there is no way to prevent formatting the code like
#
# s"MyActor($foo, ${mbox.name}) event: $event"
#
rewrite.redundantBraces.stringInterpolation = false

# The { braces } in function defienition are only required
# for functions spanning more than one line
#
# ```scala
# def one_line = "hello"
#
# def multi_line = {
#   val foo = 5
#   foo + 4
# }
# ```
rewrite.redundantBraces.maxBreaks = 1
rewrite.insertBraces.minLines = 1
rewrite.redundantBraces.methodBodies = false

#
# { Braces } are mandatory in `if/esle` blocks
#
# ```scala
# if (a > b) {
#  doSomething()
# } else {
#  doAnything()
# }
# ```
rewrite.redundantBraces.ifElseExpressions = false

rewriteTokens = {
  "⇒": "=>"
  "→": "->"
  "←": "<-"
}

project.git = true
project.excludeFilters = [.history]
project.includePaths = ["glob:**/{domain,experiments,benchmarks}/**.scala"]
...
```

## Command-line parameters (required) ##

When I run scalafmt via CLI like this: `scalafmt`

## Steps

Given code like this:
```scala
  def handle_event(event: Event): UIO[Unit] =
    ZIO.debug(s"MyActor(${foo}, ${mbox.name}) event: ${event}")
```

## Problem

Scalafmt formats code like this:
```scala
  def handle_event(event: Event): UIO[Unit] = {
    ZIO.debug(s"MyActor($foo, ${mbox.name}) event: $event")
  }
```

## Expectation

I would like the formatted output to look like this:
```scala
  def handle_event(event: Event): UIO[Unit] = {
    ZIO.debug(s"MyActor(${foo}, ${mbox.name}) event: ${event}")
  }
```

**Comment by kitbellew** [comment]
@iilyak unfortunately, I can't reproduce this problem, and I tried multiple ways.

**Comment by iilyak** [comment]
I use scala 2.13.8 if it matters

**Comment by kitbellew** [comment]
the only explanation is that you don't _only_ use scalafmt and there might be some other tool, perhaps within IDE or your build, which applies additional changes.

or you use a very old version of scalafmt binary which might not fully support all dynamic versions of scalafmt and in reality doesn't use 3.7.15.

try fully describing your environment, providing the name of the file you're trying to format, the name of the .scalafmt.conf, the current working directory, the root of git checkout tree, the output of `scalafmt --version` and the full command-line invocation of the formatter that, as you say, doesn't do what you want (while you make sure to quit any possible IDE or external tool which may interfere) and the contents of the file before and after the invocation.

**Comment by iilyak** [comment]
I think it was a race condition or something between scalafmt and vscode.

I was testing from shell using `scalafmt`. While the same file was opened in vscode.

Once I stopped `vscode` and tried `scalafmt` I see that the formatting of the interpolations `${foo}` doesn't change (as expected).

Closing it as user's fault. Thank you for your help.
