### ISSUE TITLE
`scalafmt --check` reports "--test failed" but no indication as to why

### ISSUE THREAD

**Issue by philwalk** [scalameta/scalafmt#3675]
- latest version of CLI and latest version in `.scalafmt.conf`
```
# scalafmt --version
scalafmt 3.7.15
```

## Configuration (required) ##

Please paste the contents of your `.scalafmt.conf` file here:
```
version = 3.7.15
preset = default
runner.dialect = Scala3
align.preset = more

maxColumn = 200

comments.wrap = no
docstrings.style = keep
newlines.source = keep

align.stripMargin = false

indent.matchSite = 0
indent.fewerBraces = never
indent.callSite = 2
continuationIndent.callSite = 4

assumeStandardLibraryStripMargin = true
align.stripMargin = true
fileOverride {
  "glob:**/scala-3.3.1/**" {
    runner.dialect = scala3
  }
}
optIn.breakChainOnFirstMethodDot = false
rewrite.trailingCommas.style = keep

project.excludeFilters = [
  "biz*.sc"
  "metals.sbt"
]
```

## Command-line parameters (required) ##

When I run scalafmt via CLI like this: `scalafmt --check`

## Steps
```
`scalafmt --check`
```

## Problem
The output provides no indication as to why the failure occurred:

```bash
Looking for unformatted files... (27.27 %, 15 / 55)

Looking for unformatted files... (94.55 %, 52 / 55)

error: --test failed
```

## Expectation
Error details to help determine how to resolve the failure.

## Notes
Here's the output with the `--debug` option:
```
# scalafmt --check --debug
Using core runner [3.7.15]
Working directory: C:\Users\philwalk\workspace\pallet
parsed config (v3.7.15)
Files to be formatted:
C:\Users\philwalk\workspace\pallet\biz2.sc
C:\Users\philwalk\workspace\pallet\build.sbt
C:\Users\philwalk\workspace\pallet\jsrc\bashPath.sc
C:\Users\philwalk\workspace\pallet\jsrc\bashPathCli.sc
C:\Users\philwalk\workspace\pallet\jsrc\cmdInfo.sc
C:\Users\philwalk\workspace\pallet\jsrc\demo.sc
C:\Users\philwalk\workspace\pallet\jsrc\dirlist.sc
C:\Users\philwalk\workspace\pallet\jsrc\dummyCmdline.sc
C:\Users\philwalk\workspace\pallet\jsrc\eztest.sc
C:\Users\philwalk\workspace\pallet\jsrc\find.sc
C:\Users\philwalk\workspace\pallet\jsrc\fstab.sc
C:\Users\philwalk\workspace\pallet\jsrc\fstabCli.sc
C:\Users\philwalk\workspace\pallet\jsrc\globArg.sc
C:\Users\philwalk\workspace\pallet\jsrc\mainName.sc
C:\Users\philwalk\workspace\pallet\jsrc\nativePathString.sc
C:\Users\philwalk\workspace\pallet\jsrc\ownPid.sc
C:\Users\philwalk\workspace\pallet\jsrc\palletRef.sc
C:\Users\philwalk\workspace\pallet\jsrc\pathStrings.sc
C:\Users\philwalk\workspace\pallet\jsrc\pidCommands.sc
C:\Users\philwalk\workspace\pallet\jsrc\platform.sc
C:\Users\philwalk\workspace\pallet\jsrc\procCmdline.sc
C:\Users\philwalk\workspace\pallet\jsrc\showMainArgs.sc
C:\Users\philwalk\workspace\pallet\jsrc\showPlatform.sc
C:\Users\philwalk\workspace\pallet\jsrc\testversions.sc
C:\Users\philwalk\workspace\pallet\jsrc\typeMinusAp.sc
C:\Users\philwalk\workspace\pallet\jsrc\wait.sc
C:\Users\philwalk\workspace\pallet\jsrc\where.sc
C:\Users\philwalk\workspace\pallet\project\plugins.sbt
C:\Users\philwalk\workspace\pallet\sonatype.sbt
C:\Users\philwalk\workspace\pallet\src\main\scala\vastblue\Args.scala
C:\Users\philwalk\workspace\pallet\src\main\scala\vastblue\CmdInfo.scala
C:\Users\philwalk\workspace\pallet\src\main\scala\vastblue\Demo.scala
C:\Users\philwalk\workspace\pallet\src\main\scala\vastblue\file\Paths.scala
C:\Users\philwalk\workspace\pallet\src\main\scala\vastblue\file\Util.scala
C:\Users\philwalk\workspace\pallet\src\main\scala\vastblue\Find.scala
C:\Users\philwalk\workspace\pallet\src\main\scala\vastblue\GlobArg.scala
C:\Users\philwalk\workspace\pallet\src\main\scala\vastblue\MainArgs.scala
C:\Users\philwalk\workspace\pallet\src\main\scala\vastblue\MainName.scala
C:\Users\philwalk\workspace\pallet\src\main\scala\vastblue\Platform.scala
C:\Users\philwalk\workspace\pallet\src\main\scala\vastblue\script.scala
C:\Users\philwalk\workspace\pallet\src\main\scala\vastblue\Unexpand.scala
C:\Users\philwalk\workspace\pallet\src\main\scala-2.13\vastblue\DriveRoot.scala
C:\Users\philwalk\workspace\pallet\src\main\scala-2.13\vastblue\file\EzPath.scala
C:\Users\philwalk\workspace\pallet\src\main\scala-2.13\vastblue\Info.scala
C:\Users\philwalk\workspace\pallet\src\main\scala-2.13\vastblue\pathextend.scala
C:\Users\philwalk\workspace\pallet\src\main\scala-3\vastblue\DriveRoot.scala
C:\Users\philwalk\workspace\pallet\src\main\scala-3\vastblue\file\EzPath.scala
C:\Users\philwalk\workspace\pallet\src\main\scala-3\vastblue\Info.scala
C:\Users\philwalk\workspace\pallet\src\main\scala-3\vastblue\pathextend.scala
C:\Users\philwalk\workspace\pallet\src\test\scala\TestUniPath.scala
C:\Users\philwalk\workspace\pallet\src\test\scala\vastblue\ArgsTest.scala
C:\Users\philwalk\workspace\pallet\src\test\scala\vastblue\file\EzPathTest.scala
C:\Users\philwalk\workspace\pallet\src\test\scala\vastblue\file\PathnameTest.scala
C:\Users\philwalk\workspace\pallet\src\test\scala\vastblue\file\PathSpec.scala
C:\Users\philwalk\workspace\pallet\src\test\scala\vastblue\file\RootRelativeTest.scala

Looking for unformatted files... (27.27 %, 15 / 55)

Looking for unformatted files... (96.36 %, 53 / 55)

error: --test failed
```

**Comment by kitbellew** [comment]
can you share the codebase, or at least the failing file(s), to be able to reproduce? otherwise, i don't know what i can help with.

**Comment by philwalk** [comment]
Here's a minimal project that does report a failure, with details (so it isn't the same as this symptom), although it shows a bug, and it might be the root cause of this error.   This code reports the following (incorrect) error message):
```sh
# scalafmt --check
error: missing Scalafmt version.
Consider adding the following to C:\Users\philwalk\workspace\scalafmt-bug\.scalafmt.conf:
version = 3.7.15
```
The problem with the error message is that `.scalafmt.conf` does indeed specify the version, as required.

A tarball with the sources:   https://drive.google.com/file/d/185IsousUaMvBtL0hFGObX41EY1EWq2yc/view?usp=drive_link

**Comment by kitbellew** [comment]
your minimal project uses a different `.scalafmt.conf`, specifically,
```
project.includeFilters = [
  jsrc/* # need double quotes
]
```

**Comment by philwalk** [comment]
the original `.scalafmt.conf` automatically included `jsrc/*` , but for some reason I had to add it in order for the modified file tree to include `jsrc`. 

In any event, the tarball file tree exposes a bug, which may or may not be the cause of the original error.

When `scalafmt --check` fails, is there any way to verify that at least one error has been detected?   This is difficult precisely because no information about the failure is provided.

**Comment by philwalk** [comment]
Here's a slightly different set of files that contains an identical `.scalafmt.conf` file:

[scalafmt-bug2.tar.gz](https://github.com/scalameta/scalafmt/files/13244486/scalafmt-bug2.tar.gz)

**Comment by kitbellew** [comment]
@philwalk i downloaded your latest tarball, installed 3.7.15 (since that's what you claim to use) and ran `scalafmt-3.7.15 --check` in the `scalafmt-bug2` directory. got `All files are formatted with scalafmt :)`.

**Comment by philwalk** [comment]
I definitely am using `3.7.15`, so I will have to investigate.  Thanks for looking into this!

**Comment by philwalk** [comment]
This has been somewhat subtle to capture, hopefully you're able to duplicate the problem with this set of files.
[pallet-bug.tar.gz](https://github.com/scalameta/scalafmt/files/13251958/pallet-bug.tar.gz)

**Comment by kitbellew** [comment]
@philwalk you have windows files and you don't set the `lineEndings` value explicitly, hence it's `unix` (but could also be `windows` or `preserve`).

therefore, formatted code will be using unix line endings and thus different from the original, but the logic showing diffs only looks at lines themselves, not how they are terminated, hence the diff in your case is empty, which is why you see _nothing_.

**Comment by philwalk** [comment]
@kitbellew Thanks for figuring this out!
So either of the following would be a good fix:

- print an error message if line endings don't match the default `lineEndings` setting.
- disable errors associated with mismatched `lineEndings`, unless a `lineEndings` value is specified.

The second approach makes more sense to me, because it might be valid to have a scala project having files with intentionally mixed line endings (as test sources, for example).

**Comment by kitbellew** [comment]
unfortunately, that's not how this works. check must return an error if the regular formatter run would modify the files, even just by changing a line ending.
