### ISSUE TITLE
Sclafmt ignores newlines.source=keep, glues multiple lines into one 

### ISSUE THREAD

**Issue by dimatkach** [scalameta/scalafmt#3688]
## Configuration (required) ##

Please paste the contents of your `.scalafmt.conf` file here:
```
version =3.7.15
newlines.source=keep
maxColumn=40 ## just to demonstrate 
```

(I had some other options, but they don't seem to be relevant, and didn't change the behavior anyway). 

## Command-line parameters (required) ##

Coursier seems to want to install the entire freaking Universe, including spark, openapi generator, several different versions of python and java, X11 (???), aws,  to name a few (most of which I already have .anyway), I had to kill it after running for 40 minutes, so can't try it with the CLI, sorry. 

I am using 3.7.15 with SBT plugin: `sbt scalafmt` 

## Steps

Given code like this:
```scala
type Foo = Bar
  with Bat
  with Bak
  with Baz
  with Bar
  with Bam
  with Boom
```

## Problem

Scalafmt formats code like this:
```scala
type Foo = Bar with Bar with Bak with Bar
  with Bam with Boom
```

## Expectation

I would like the formatted output to look like my original code because I am explicitly asking to keep my line breaks with 
`newlines.source=keep` 

## Workaround

Not use scalafmt?

**Comment by kitbellew** [comment]
> (I had some other options, but they don't seem to be relevant, and didn't change the behavior anyway).

and you re-tested without them? I tried your configuration and code example, and I can't reproduce, unfortunately; my test works exactly as you expected.

> Coursier seems to want to install the entire ...

I cannot comment on that but I haven't seen it take more than a minute on a decent connection.

> ... so can't try it with the CLI, sorry.

In that case, you should submit your issue to the repository which contains your integration. This repository is not for SBT-related submissions.

> I am using 3.7.15 with SBT plugin: `sbt scalafmt`

But just in case: I don't think `sbt scalafmt` is actually a [valid command](https://scalameta.org/scalafmt/docs/installation.html#task-keys).

> ## Workaround
> Not use scalafmt?

Не может так оказаться, что это уже произошло? Один деятель неделю назад обнаружил, что трудолюбивый vscode паралельно что-то портил.

**Comment by dimatkach** [comment]
@kitbellew I dunno ... must be one of those "works on my machine" cases I guess 😄 
Here is the complete case I am reproducing reliably (yes, with CLI ... coursier finally finished!) 

```
[test-branch] [1123]> cat .scalafmt.conf
version = "3.7.16"
runner.dialect = scala213
newlines.source=keep
maxColumn = 40
[test-branch] [1124]> scalafmt --version
scalafmt 3.7.16
[test-branch] [1125]> scalafmt --test foobar.scala 
--- a/Users/dtkach/workspace/cdp-core/foobar.scala
+++ b/Users/dtkach/workspace/cdp-core/foobar.scala
@@ -1,9 +1,4 @@
 class Foo {
-  type It = Foo with
-    Bar with
-    Baz with
-    Bat with
-    Bak with
-    Bam with
-    Ban
+  type It = Foo with Bar with Baz
+    with Bat with Bak with Bam with Ban
 }
error: --test failed
```

<img width="385" alt="Screenshot 2023-11-10 at 6 39 29 PM" src="https://github.com/scalameta/scalafmt/assets/4604190/61f790e2-1da0-46c0-a288-9794d1a4d5f6">

**Comment by dimatkach** [comment]
"not planned" ... Love it 🤣

**Comment by kitbellew** [comment]
i closed it as "can't reproduce", which you agreed with.

**Comment by dimatkach** [comment]
I did? Hm ... I guess, "Here is the complete case I am reproducing reliably" can be construed to mean "I agree it is not reproducible" in some of the infinite number of the Universes ... :D

**Comment by kitbellew** [comment]
> @kitbellew I dunno ... must be one of those "works on my machine" cases I guess 😄 

what would you like me to do, @dimatkach? i ran exactly what you suggested, and it works as expected. i suggested that there was a similar case recently when a running IDE process was messing with the results of formatting. what else?
