### ISSUE TITLE
Error message when there is no .scalafmt.conf is misleading

### ISSUE THREAD

**Issue by JD557** [scalameta/scalafmt#3693]
## Configuration (required) ##

None

## Steps ##

When I run scalafmt via CLI like this: `scalafmt`

I get a message:

```
error: missing Scalafmt configuration file.
Consider creating '\.scalafmt.conf' with the following:
version = 3.7.16
```

However, if I create such a file, I get:
```
Default dialect is deprecated; use explicit: [sbt0137,sbt1,scala211,scala212,scala212source3,scala213,scala213source3,scala3,scala3future]
Also see https://scalameta.org/scalafmt/docs/configuration.html#scala-dialects"
```

## Expectation

I would expect the example to recommend a dialect, or at least be something like:

```
error: missing Scalafmt configuration file.
Consider creating '\.scalafmt.conf' with the following:
version = 3.7.16
runner.dialect = # pick one of : [sbt0137,sbt1,scala211,scala212,scala212source3,scala213,scala213source3,scala3,scala3future]
```

**Comment by kitbellew** [comment]
@JD557 if you'd like, i can remove the message about the version. after all, the error is about the missing config file, and listing all required parameters is impractical and too cumbersome. let me know if that would make it more fair, and less misleading.

**Comment by JD557** [comment]
Makes sense.

While that can make the bootstrap a bit more cumbersome for the beginner (get the file error; create the file; get the version error; add the version; get the dialect error; add the dialect), I think it's less surprising.

Maybe the missing file error message could point to https://scalameta.org/scalafmt/docs/configuration.html?
It's a bit of a shame that the example in the top there is also missing the required parameters, though :/
