### ISSUE TITLE
if() force braces when multiline not working properly

### ISSUE THREAD

**Issue by alexps99** [scalameta/scalafmt#3697]
if() force braces when multiline not working properly or i m not understanding

In what world this example is multiline when it has only 1 statement?
![imagen](https://github.com/scalameta/scalafmt/assets/48829017/ec0b562d-7282-47e6-99b0-8e0b5cacef85)

![imagen](https://github.com/scalameta/scalafmt/assets/48829017/62b50875-b22e-4001-b651-57f6dda2d554)

**Comment by alexps99** [comment]
Woops, wrong tab

**Comment by tgodzik** [comment]
Actually, I wonder if we could make something similar for VS Code. Maybe a plugin that has all the options and a small visualization tool (something similar has the setting page of git lenses) where you would see all the changes right away.

Would probably be cool project for someone. @kitbellew do you think it's worth opening an issue to track that? It would basically be the documentation on steroids.

![image](https://github.com/scalameta/scalafmt/assets/3807253/489dd37c-2150-4eb6-92f9-c33c6c57a349)

It would be great small project to tinker with.

**Comment by kitbellew** [comment]
@tgodzik are you suggesting that for metals? I'm assuming that some users would find it useful, of course...

**Comment by tgodzik** [comment]
I am thinking it could be a separate plugin, no need for metals here. Unless, we can't do without it. 

I would think a smaller scope would be easier to handle.

**Comment by tgodzik** [comment]
I would think this would just be an overlay over .scalafmt.conf and would modify it as the result of changing the settings. I don't think we have any standard.

User could just install the plugin, open a workspace with scalafmt config and open the settings page, modify things there.

**Comment by kitbellew** [comment]
sure! if someone knows how to write such plugins, that would be great!
