### ISSUE TITLE
Inconsistent `extends` alignment with `align.preset = more`

### ISSUE THREAD

**Issue by NColey** [scalameta/scalafmt#3762]
# Configuration

* cli version  => `3.7.17`
* current .scalafmt.conf version => `3.7.17`
* previous .scalafmt.conf version => `2.3.2`

Most relevant `.scalafmt.conf` file details, will post the whole file below:

```
version = 3.7.17
runner.dialect = scala213
align.preset = more
```

## Command Line Parameters

When I run scalafmt like this: `scalafmt` (no additional arguments)

## Steps

Given code like:

```
case object A     extends Something
case object AAA   extends Something
```

and the following alignment settings:

```
align.preset = more
```

## Problem

Scalafmt formats the above code like this:

```
case object A extends Something
case object AAA extends Something
```

## Expectation

I would like the code to remain like this:

```
case object A     extends Something
case object AAA   extends Something
```

## Additional Context

I'm upgrading a project that was on scalafmt.conf version `2.3.2` and updating it to `3.7.17`. This is my first interaction with this project so my CLI version is the latest. The project previously had the alignment setting `align = more` and that aligned `extends` in case classes as expected. 

Following the upgrade and rewriting `align = more` as `align.preset = more` running `scalafmt` removes the alignment from `extends` where it was previously aligned. According to the docs [align.preset = more](https://scalameta.org/scalafmt/docs/configuration.html#alignpresetmore) should align `extends`. I'll add that I also observed this behavior with `align.preset = most`.

I have additionally tried the following config settings:

```
align {
  preset = more
}
```

and

```
align {
  preset = more
  tokens = [
    {code = "extends", owners = [{regex = "Defn.(Class|Trait|Object)"}]}
  ]
}
```

and

```
align {
  preset = more
  tokens = [
    {code = "extends", owner = "Defn.(Class|Trait|Object)"}
  ]
}
```

I am only seeing alignment settings not being respected for `extends`, not in any other case.

## The Entire .scalafmt.conf File

There are other settings in place in this project that may or not be in conflict. Here is the current state of the file:

```
version = 3.7.17
runner.dialect = scala213
align.preset = more
align {
  openParenCallSite = false
  openParenDefnSite = false
  tokens = [
    {code = "=>", owner = "Case|Term.Function"}
    {code = "%", owner = "Term.ApplyInfix"}
    {code = "%%", owner = "Term.ApplyInfix"}
    {code = "%%%", owner = "Term.ApplyInfix"}
    {code = "->", owner = "Term.ApplyInfix"}
    {code = "//", owner = ".*"}
    {code = ":", owner = "Term.Param|Defn.(Def|Val)"}
    {code = "<-", owner = "Enumerator.Generator"}
    {code = "=", owner = ".*"}
    {code = "extends", owner = "Defn.(Class|Trait|Object)"}
    {code = "{", owner = "Template"}
    {code = "}", owner = "Template"}
    {code = "←", owner = "Enumerator.Generator"}
    {code = "→", owner = "Term.ApplyInfix"}
    {code = "⇒", owner = "Case"}
    {code = ",", owner = "Pat.*"}
  ]
}
assumeStandardLibraryStripMargin = true
binPack {
  literalArgumentLists = false
}
continuationIndent {
  callSite = 2
  defnSite = 2
  extendSite = 2
}
danglingParentheses.preset = true
danglingParentheses.exclude = []
docstrings.style = Asterisk
maxColumn = 120
rewrite {
  redundantBraces {
    stringInterpolation = true
    methodBodies = true
    includeUnitMethods = true
    maxLines = 100
    generalExpressions = false
  }
  rules = [
    AvoidInfix
    PreferCurlyFors
    RedundantParens
    SortImports
    SortModifiers
  ]
  sortModifiers {
    order = [
      "`implicit`"
      "`final`"
      "`sealed`"
      "`abstract`"
      "`override`"
      "`private`"
      "`protected`"
      "`lazy`"
    ]
  }
}
verticalAlignMultilineOperators = false
verticalMultiline {
  newlineAfterOpenParen = true
  atDefnSite = true
  arityThreshold = 2
}
newlines {
  source = keep
  beforeCurlyLambdaParams = multilineWithCaseOnly
}
```

**Comment by kitbellew** [comment]
@NColey if your example is correct, then the problem is `case class A` must be followed by a list of parameters (otherwise it should be a `case object`). when i tried `class A` instead, it aligned correctly.

**Comment by NColey** [comment]
@kitbellew I'm sorry that was a typo on my end. The issue I'm seeing is specifically with `case object`s.

**Comment by kitbellew** [comment]
@NColey weird. `case object` works for me. specifically, i added this:
```
<<< ONLY #3762
object a {
  case object A extends Something
  case object AAA extends Something
}
>>>
object a {
  case object A   extends Something
  case object AAA extends Something
}
```
to the end of `DefaultWithAlign.stat` file and ran `FormatTests`.

**Comment by NColey** [comment]
@kitbellew so I created a super minimal reproduction of the issue [here](https://github.com/NColey/scalafmt-issue-repro) if that helps. If you clone that down and run `scalafmt` with the latest CLI it will remove the alignment from extends.

Re `maxColumn` -- when I bumped the version from `2.3.2` to `3.7.17` I responded to anything that was flagged as an error (i.e settings being renamed or removed) and that one wasn't flagged as an issue so I left it as is. That said, if you look at the repo where I have reproduced this issue you can see I tried it with and without adjustments to `maxColumn` and it still un-aligns case objects on the `extends` portion.

**Comment by kitbellew** [comment]
@NColey `extends` is no longer owned by `Defn.Object` but by the `Template` field within it. so if you remove all your `align { ... }` customizations, it formats correctly.

**Comment by kitbellew** [comment]
you should use AST Explorer linked from `https://scalameta.org/scalafmt/docs/configuration.html#aligntokens`, it will show you tokens and trees.

**Comment by NColey** [comment]
OH! Oh wow thank you, that totally was the issue. I appreciate the AST Explorer suggestion as well, thank you so much 🙏 . I'll close this issue now but appreciate your help here.
