### ISSUE TITLE
How can I make "then" at the end of line, not next line

### ISSUE THREAD

**Issue by Liyw979** [scalameta/scalafmt#3764]
after format:
![image](https://github.com/scalameta/scalafmt/assets/16919236/fb8a1bfd-e2aa-4f57-8fc1-861b83c82336)

I want:
![image](https://github.com/scalameta/scalafmt/assets/16919236/22dcd778-fbc2-4732-a24c-50c7ecdc6aa0)

**Comment by kitbellew** [comment]
https://scalameta.org/scalafmt/docs/configuration.html#danglingparenthesesctrlsite
