### ISSUE TITLE
scalafmt rewrites scala 2 syntax into scala 3 in build.sbt file

### ISSUE THREAD

**Issue by mtomko** [scalameta/scalafmt#3787]
## Configuration (required) ##
See https://github.com/mtomko/scalafmt-repro2

Please paste the contents of your `.scalafmt.conf` file here:
```
version=3.8.0
runner.dialect = scala3
rewrite.scala3.removeOptionalBraces = true
```

## Command-line parameters (required) ##

When I run scalafmt via CLI like this: `scalafmt`

## Steps

Given code like this:
```scala
ThisBuild / scalaVersion := "3.3.1"

lazy val versions = new {
  val cats = "2.10.0"
}

libraryDependencies += "org.typelevel" %% "cats-core" % versions.cats
```

## Problem

Scalafmt formats code like this:
```scala
ThisBuild / scalaVersion := "3.3.1"

lazy val versions = new:
  val cats = "2.10.0"

libraryDependencies += "org.typelevel" %% "cats-core" % versions.cats
```

## Expectation

I would like the formatted output to look like this:
```scala
ThisBuild / scalaVersion := "3.3.1"

lazy val versions = new {
  val cats = "2.10.0"
}

libraryDependencies += "org.typelevel" %% "cats-core" % versions.cats
```

## Notes

Briefly discussed on discord: https://discord.com/channels/632642981228314653/632665341864181780/1209538770303721533

**Comment by mzuehlke** [comment]
This fix doesn't work for files in the `project` folder.
They still get converted to braceless style which isn't working for sbt

**Comment by kitbellew** [comment]
> This fix doesn't work for files in the `project` folder. They still get converted to braceless style which isn't working for sbt

can you please be more specific? which files?

**Comment by mzuehlke** [comment]
This is a minimal repo: https://github.com/mzuehlke/scalafmt-sbt-project-bug

Invoking `sbt scalafmtSbt` leads to the following diff:

```diff
diff --git a/project/Dependencies.scala b/project/Dependencies.scala
index 749733c..911726f 100644
--- a/project/Dependencies.scala
+++ b/project/Dependencies.scala
@@ -1,5 +1,4 @@
 import sbt.*

-object Dependencies {
+object Dependencies:
   val cats = "org.typelevel" %% "cats-core" % "2.10.0"
-}
```

**Comment by kitbellew** [comment]
@mzuehlke i think you have unrealistic expectations. this is not an sbt file, it's a scala file. if you specify in your configuration that your dialect is scala3, at least for scala files that's what it will be.

**Comment by mzuehlke** [comment]
Thanks for the clarification. If this is the expected behaviour that's fine. 👍 

Maybe an addition to the config would be helpful so that everyone who adds **scala3** specific options know that a `fileOverride` for the "project" folder is needed.
