### ISSUE TITLE
3.8.0 regression: tuple expression at the start of a line are moved to prior line (inside of match cases)

### ISSUE THREAD

**Issue by rmgk** [scalameta/scalafmt#3790]
This template is mostly a guideline, not a strict requirement, except
the sections marked `(required)`.

Please make sure that the issue is observable using the latest version of `scalafmt` and
within the `scalafmt` **CLI**: `https://scalameta.org/scalafmt/docs/installation.html#cli`

Using the CLI is _mandatory_, in one of these configurations:
- latest version of CLI and latest version in `.scalafmt.conf`
- previous version of CLI and latest version in `.scalafmt.conf`
- latest version of CLI and previous version in `.scalafmt.conf`

## Configuration (required) ##

Please paste the contents of your `.scalafmt.conf` file here:
```
version = 3.8.0
runner.dialect = scala3
...
```

## Command-line parameters (required) ##

cs launch scalafmt -- .

## Steps

Given code like this:
```scala
0
(1, 2)
```

## Problem

Scalafmt formats code like this:
```scala
0 (1, 2)
```

## Expectation

Should be unchanged. Reformatting changes the semantics.

## Notes

Does not seem to happen in every context where a line starts with a tuple. The following is a full example where the reformatting happens.

```
val a = 1 match {
  case 1 =>
    println(1)
    (1, 2)
}
```

**Comment by Gedochao** [comment]
Came here to report this. 
Seems like we won't update `scalafmt` in Scala CLI until this is fixed.

**Comment by Gedochao** [comment]
Seems to be the same thing as:
- https://github.com/scalameta/scalafmt/issues/3789
One of these should be marked as a duplicate.
