### ISSUE TITLE
With `newlines.source = keep` linebreaks are not preserved in lists with non-numeric entries

### ISSUE THREAD

**Issue by OndrejSpanel** [scalameta/scalafmt#3894]
## Configuration (required) ##

```
version = 3.8.1
maxColumn = 120
runner.dialect = scala3
newlines.source = keep
```

## Command-line parameters (required) ##

When I run scalafmt via CLI like this: `scalafmt`

## Steps

Given code like this:
```scala
object Main {
  val a = Set(
    0,
    1, 2, 3,
    4, 5, 6, 7, 8, 9, 10 + 0
  )
  def main(args: Array[String]): Unit = {}
}
```

## Problem

Scalafmt formats code like this:
```scala
object Main {
  val a = Set(
    0,
    1,
    2,
    3,
    4,
    5,
    6,
    7,
    8,
    9,
    10 + 0
  )
  def main(args: Array[String]): Unit = {}
}

```

## Expectation

I would like the formatted output to look like this:
```scala
object Main {
  val a = Set(
    0,
    1, 2, 3,
    4, 5, 6, 7, 8, 9, 10 + 0
  )
  def main(args: Array[String]): Unit = {}
}
```

## Notes

When all values are numeric literals. it works fine. As soon as any single value is anything else, line-breaks are inserted.

**Comment by kitbellew** [comment]
this type of formatting is called binpacking, and there's a separate parameter for that. source=keep doesn't guarantee all breaks will be preserved, only when it doesn't contradict other parameters or other constraints.
