### ISSUE TITLE
Preserve newlines more strictly

### ISSUE THREAD

**Issue by OndrejSpanel** [scalameta/scalafmt#3896]
I would like newlines in my sources to be preserved very strictly, as I am mostly using them with consideration. I would prefer scalafmt to only introduce / remove whitespaces, perhaps removing newlines when there are multiple empty lines, but even that is something I do not need.

I hoped `newlines.source = keep` will do this, but it does not, there are still many situations where `scalafmt` insist on breaking lines differently, esp. breaking things which I have placed on a single line intentionally.

Would it be perhaps possible to introduce a new mode to `newlines.source` which would result in such behaviour? I am afraid in current state I am unable to use the tool no matter how I like it otherwise.

**Comment by kitbellew** [comment]
please report each specific bug with formatting separately, with examples (exactly like the issue template requests), making sure first that it's a bug and not an interaction with another parameter.

**Comment by kitbellew** [comment]
I'm confused. you found the parameters that seemingly solve your previous two issues; do they not?

you can discuss stuff on discord if you'd like to involve the rest of the community.

**Comment by OndrejSpanel** [comment]
I found parameters which solve #3895, but not #3894.

> you can discuss stuff on discord if you'd like to involve the rest of the community.

Can you give me some URL or some other pointer to find the right Discord community? The homepage contains links to Gitter which seems to be quite dead.

**Comment by kitbellew** [comment]
> Can you give me some URL or some other pointer to find the right Discord community? The homepage contains links to Gitter which seems to be quite dead.

i don't know what to say. discord link is immediately to the right of gitter's.

**Comment by tgodzik** [comment]
Might be worth to also put it on https://scalameta.org/scalafmt/ aside from README in the repo here.

**Comment by OndrejSpanel** [comment]
This is what I see on https://scalameta.org/scalafmt/, which I think is a scalafmt homepage:

![image](https://github.com/scalameta/scalafmt/assets/6927223/99d7b522-1a74-458b-8195-d456f47689ed)

Even searching `discord` on that page finds nothing.

**Comment by OndrejSpanel** [comment]
I have found the link eventually on https://github.com/scalameta

When I click on the link and accept the invitation, the result is "Unable to accept invite". Google offers this explanation:

> Discord displays the "unable to accept invite" error when the invitation link expires, the link has already been used by the maximum number of users permitted, or the server admin has revoked it manually.

**Comment by tgodzik** [comment]
I thought the link didn't have an expiration date, sorry about that. I updated it.

**Comment by kitbellew** [comment]
@OndrejSpanel could you please provide specific examples when line breaks are not reasonably preserved (other than #3894), or close this issue?

**Comment by OndrejSpanel** [comment]
I am not aware of any other case.
