### ISSUE TITLE
RedundantParens removes too much parens

### ISSUE THREAD

**Issue by sjoerdmulder** [scalameta/scalafmt#3901]
## Configuration (required) ##

Please paste the contents of your `.scalafmt.conf` file here:
```
version = 3.8.1
runner.dialect = scala3
rewrite.rules = [RedundantParens]
```

## Command-line parameters (required) ##

When I run scalafmt via CLI like this: `scalafmt`

## Steps

I know it's a bit weird code (in actual code the `a: Any` is a marker-trait so that the inner match gives match error when a new implementation is added.)

Currently the formatted doesn't compiled anymore with a `'=>' expected but 'match' found.` error

Given code like this:
```scala
    Seq.empty.collect {
      case a: Any if (a match {
        case b: Any => b
      }) => a
    }
```

## Problem

Scalafmt formats code like this:
```scala
    Seq.empty.collect {
      case a: Any if a match {
            case b: Any => b
          } =>
        a
    }
```

## Expectation

I would like the formatted output to look like this since the current formatted code by scalafmt
```scala
    Seq.empty.collect {
      case a: Any if (a match {
            case b: Any => b
          }) =>
        a
    }
```

**Comment by kitbellew** [comment]
@sjoerdmulder can you explain the problem you encounter? you have requested removal of redudant parens, and in scala3 (your chosen dialect), these parens are redundant.

**Comment by sjoerdmulder** [comment]
Ahhh sorry my bad! We are already using the scala3 formatting to prepare for scala3 migration but we still compile with scala2.13... so for scala 2.13 this is invalid code... using the `Scala213Source3` as explained doesn't have the issue.
