### ISSUE TITLE
Feature request: code style for `match` dot-notation

### ISSUE THREAD

**Issue by kubukoz** [scalameta/scalafmt#3932]
## Problem

Currently, Scala 3 users can choose to insert a dot before `match`, making it chainable with method calls using dot-notation.

For example:

```scala
List(1).match {
case a => a
}.map(_ + 1)
```

However, the same example can be written with usual "infix" match notation:

```scala
(List(1) match {
  case a => a
}).map(_ + 1)
```

or

```scala
List(1) match {
  case a => a
} map (_ + 1)
```

## Expectation

I would like to have a configuration key that allows choosing a particular style. This could be a customization of `AvoidInfix`, or perhaps an addition to `rewrite.scala3`.

I would conside various modes:

- always use `foo match`
- use `foo.match` if there are any method calls further in the chain (`foo.match { }.map`)
- always use `foo.match`

## Workaround

Manually checking and updating the use-sites of `match`.

**Comment by kitbellew** [comment]
what's the purpose of this, just out of curiosity? i can't imagine why we would implement something like this but if there's a reason potent enough...

**Comment by kubukoz** [comment]
Just code consistency - at the moment it's kinda arbitrary, and you can mix&match (pun unintended) the dot-ful and dot-less approach however you like (as long as it parses). It's not a deal-breaker for me of course, but I don't think it's very different from other things scalafmt allows you to standardize :)

**Comment by kitbellew** [comment]
it should be able to help you achieve a consistent "dot-full" code already. other options seem contrary to our style.

**Comment by kubukoz** [comment]
consistent dot-full would also make sense (to me) if the Scala 3 dialect is chosen.

**Comment by kitbellew** [comment]
it can easily be accomplished with avoidinfix and scala3 rewrite.
