### ISSUE TITLE
Wrong indentation with scala213source3 when short-circuiting boolean operators start a line in final position of a block

### ISSUE THREAD

**Issue by ex-ratt** [scalameta/scalafmt#4084]
## Configuration ##

```
version = 3.8.2
runner.dialect = scala213source3 
```

## Command-line parameters ##

When I run scalafmt via CLI like this: `scalafmt Test.scala`

## Steps

Given code like this:
```scala
case class Test(condition1: Boolean, condition2: Boolean, condition3: Boolean) {
  def test: Boolean = {
    condition1
      && condition2
      && condition3
  }
}
```

## Problem

Scalafmt formats code like this (changes indentation in lines starting with operators):
```scala
case class Test(condition1: Boolean, condition2: Boolean, condition3: Boolean) {
  def test: Boolean = {
    condition1
    && condition2
    && condition3
  }
} 
```

This happens with operator `||` as well (but not with other operators).

## Expectation

I would not expect the indentation to change. Instead, I would have assumed no change at all.

## Workaround

The indentation stays the same if:

- the braces are omitted,
- non-short-circuiting boolean operators are used (`&` or `|`), or
- the expression is assigned to a value within the block.

**Comment by kitbellew** [comment]
@ex-ratt does this lead to incorrect code? if not, it works exactly as configured.

**Comment by ex-ratt** [comment]
Yes, the code still compiles and seems to work as well.

You don't find it odd that the indentation is not consistent across different operators and situations?

**Comment by kitbellew** [comment]
if you don't mind, i will close this. what you're describing is default yet configurable behavior. the configuration parameters are well documented.

**Comment by ex-ratt** [comment]
Hi, I don't mind. Had a look through the config to figure out what I was missing. In case someone else stumbles across this:

There is a configuration `indentOperator.excludeRegex` with a default value of `^(&&|\\|\\|)$`, which excludes `&&` and `||` from indentation. I would not have thought that the default handles these operators different from others, which is why I didn't even think about checking.

My bad. Thanks for pointing this out :)
