### ISSUE TITLE
Customize space for specific infix operators

### ISSUE THREAD

**Issue by charpov** [scalameta/scalafmt#4089]
I have defined `~` as infix method so I can write things like:
```scala
3 * x~2
```
Unfortunately, Scalafmt reformats this as `3 * x ~ 2`.
To keep the code formatted as I like, it'd be nice to have a configuration `spaces.neverAroundInfixOperators` similar to the existing `spaces.neverAroundInfixTypes`.

*Note:* Scala combinators also use `~` as an infix operator and have examples such as:
```scala
def expr: Parser[Any] = term~rep("+"~term | "-"~term)
```
If this code is formatted using Scalafmt, I wonder what's the trick...

**Comment by kitbellew** [comment]
if `~` is infix, then so is `*`, so why not `3*x~2`?

what is the difference, by the way, between `x~2` and `x ~ 2`?

**Comment by charpov** [comment]
That's my point. I need a configuration so `*` and `~` are treated differently, like `|` and `~` are treated differently in the combinator example.

**Comment by kitbellew** [comment]
why do they need to be treated differently? personal, aesthetic preference or actual semantic difference?

**Comment by charpov** [comment]
Aesthetics, yes. Just like `spaces.neverAroundInfixTypes`. Can Scalafmt impact semantics? Isn't the tool all about aesthetics?

**Comment by kitbellew** [comment]
off curse, but it's not an infinitely configurable aesthetics tool. the combinator examples that i have found use spaces around the tilde so it might not even be a standard notation.

i will label it a feature request, and if there's enough support voiced for it on the discord channel, we can revisit.

**Comment by charpov** [comment]
Sounds good.

Scalafmt is not infinitely configurable, but it does have *a lot* of configuration options. And what I'm asking for is very much like `spaces.neverAroundInfixTypes`, which already exists. It's hard to justify that one deserves to be there but the other is only "aesthetics". (Concerns with implementation and/or performance would be another matter.)

The combinator example is from the book *Advanced Programming in Scala*, 5th edition.
