### ISSUE TITLE
Scalafmt inserts the wrong endmarker, creating invalid code (Scala3)

### ISSUE THREAD

**Issue by blandflakes** [scalameta/scalafmt#4098]
## Configuration (required) ##

Please paste the **smallest** possible set of `.scalafmt.conf`
configuration parameters that reproduces the problem:
```
runner.dialect = "Scala3"
version = "3.8.2"
rewrite.scala3.insertEndMarkerMinLines = 10
```

## Command-line parameters (required) ##

When I run scalafmt via CLI like this: `scalafmt -c .scalafmt.conf`

## Steps

Given code like this:
```scala
class FmtTest:

  private val const = 3

  def testBrokenMatch(s: String) =
    s match
      case "hello" =>
        val a = 1
        val b = 1
        val c = 1
        val d = 1
        val e = 1
        val f = 1
        val g = 1
        val h = 1
        val i = 1
        val j = 1
        val k = 1
        val l = 1
    end match
  
end FmtTest
```

## Problem

Scalafmt formats code like this:
```scala
class FmtTest:

  private val const = 3

  def testBrokenMatch(s: String) =
    s match
      case "hello" =>
        val a = 1
        val b = 1
        val c = 1
        val d = 1
        val e = 1
        val f = 1
        val g = 1
        val h = 1
        val i = 1
        val j = 1
        val k = 1
        val l = 1
    end match

  end FmtTest
end FmtTest
```

The extra FmtTest of course then fails fmt in future calls as it is not valid.

## Expectation

I would like the formatted output to look like this:
```scala
class FmtTest:

  private val const = 3

  def testBrokenMatch(s: String) =
    s match
      case "hello" =>
        val a = 1
        val b = 1
        val c = 1
        val d = 1
        val e = 1
        val f = 1
        val g = 1
        val h = 1
        val i = 1
        val j = 1
        val k = 1
        val l = 1
    end match
  end testBrokenMatch // Or nothing
end FmtTest
```

## Workaround

I've found that by adding the `end testBrokenMatch` marker myself, scalafmt does not add an extra `end FmtTest` anymore.

Additionally, if I don't include include `end match`, scalafmt doesn't alter the code at all.

## Notes

The private val or an import seems required to trigger the formatting threshold of trying to insert the extra marker.

I see a similar situation with simply calling a method and passing a body for which an end marker can't be labeled, such as munit's test:

```scala
class MyTest extends munit.FunSuite:
  import com.github.plokhotnyuk.jsoniter_scala.core.*
  test("some test name"):
    // body here, ending with an `end match`

end MyTest
```

In this case, scalafmt will insert an extra `end MyTest`.

**Comment by tanin47** [comment]
Just curious if this has been released. I seem to encounter a bug where scalafmt would insert `/* EndMarker */` into a scalal file (and also seemingly modify the lines around it to be invalid code).

Thank you.

**Comment by kitbellew** [comment]
> I seem to encounter a bug where scalafmt would insert `/* EndMarker */` into a scalal file (and also seemingly modify the lines around it to be invalid code).

this was an Intellij behaviour when formatting a subset of lines, nothing to do with scalafmt.

**Comment by tanin47** [comment]
Thank you. It seems to happen when enabling scalafmt in IntelliJ. Switching to IntelliJ formatter solves the issue, but then the format doesn't quite align with the format that we configure in scalafmt. 

I'll file an issue with IntelliJ.

**Comment by kitbellew** [comment]
@tanin47 do not use range formatting in intellij (meaning, selecting a subset of lines to reformat; do a full file format only).
