### ISSUE TITLE
[question] Pattern matching constructor indentation

### ISSUE THREAD

**Issue by YanDoroshenko** [scalameta/scalafmt#4112]
Hi.
I'm trying to align constructor parameters in pattern matching. Seems like they are being indented by 4 by default and I can't find which configuration parameter is responsible for this behavior. I've tried all of them from the `indent` group that made sense and nothing seems to affect it.

## Configuration (required) ##

Please paste the **smallest** possible set of `.scalafmt.conf`
configuration parameters that reproduces the problem:
```
version = 3.8.2
runner.dialect = scala213
preset = Intellij

maxColumn = 20
...
```

## Command-line parameters (required) ##

When I run scalafmt via CLI like this: `scalafmt`

## Steps

Given code like this:
```scala
object Test {

  val x: Tuple2[
    Int,
    Int
  ]

  x match {
    case Tuple2(
          a,
          b
        ) =>
      ???
  }
}
```

## Problem

Scalafmt formats code like this:
```scala
object Test {

  val x: Tuple2[
    Int,
    Int
  ]

  x match {
    case Tuple2(
          a,
          b
        ) =>
      ???
  }
}
```

## Expectation

I would like the formatted output to look like this:
```scala
object Test {

  val x: Tuple2[
    Int,
    Int
  ]

  x match {
    case Tuple2(
      a,
      b
        ) =>
      ???
  }
}
```

**Comment by kitbellew** [comment]
you are correct, there are no parameters to accomplish this.

**Comment by kitbellew** [comment]
@YanDoroshenko going forward, if you have a question rather than a bug report, please use the discord channel to ask it, please.
