### ISSUE TITLE
Invalid state for bit operations

### ISSUE THREAD

**Issue by timothyklim** [scalameta/scalafmt#4116]
## Steps

Given code like this:
```scala
(~validByte).toByte
```

## Problem

Scalafmt formats code like this:
```scala
~validByte.toByte
```
and makes code broken because for scalac its like `~(validByte.toByte)` and expression become as Int type.

## Expectation

I would like the formatted output to look like this:
```scala
(~validByte).toByte
```

## Notes

version: 3.8.3

**Comment by kitbellew** [comment]
@timothyklim do you believe your submission, as formulated, is reproducible? would you perhaps like to revise it to include everything that was mandatory in the issue template?

**Comment by timothyklim** [comment]
> @timothyklim do you believe your submission, as formulated, is reproducible? would you perhaps like to revise it to include everything that was mandatory in the issue template?

Sorry sorry, I forgot that part:
```
version = 3.8.3

rewrite.rules = [RedundantParens]

runner.dialect = scala3future
```

**Comment by timothyklim** [comment]
> version = 3.8.3

version = 3.8.2 works fine with that code
