### ISSUE TITLE
Broken code literals in Scaladoc

### ISSUE THREAD

**Issue by charpov** [scalameta/scalafmt#4147]
When Scalafmt reformats Scaladoc comments, it can break code samples, which IntelliJ then flags as a malformed comment:

```scala
/** Some `code sample of some sort` in a comment. */
```
might become:
```scala
/** Some `code sample
  * of some sort` in
  * a comment.
  */
```

Scaladoc still works (and ignores stars inside the code), so one could argue that IntelliJ is to blame, but I still feel Scalafmt should not break tokens between backticks.

**Comment by kitbellew** [comment]
@charpov valid scaladoc code fragment should be enclosed in `{...}` or `{{{...}}}`.

**Comment by charpov** [comment]
`{...}` doesn't work for me (the braces are included in the html) and `{{{...}}}` creates a code block, which is not what I want.

Do you have a reference for the use of `{...}` in Scaladoc?

**Comment by charpov** [comment]
Still doesn't work for me: I get a code block even if no newline after the opening `{{{`.

**Comment by kitbellew** [comment]
thanks, I'll take a look later.

**Comment by charpov** [comment]
I now think Scalameta is to blame. I started an issue there (<https://github.com/scalameta/scalameta/issues/3908>).

**Comment by charpov** [comment]
Scalameta is adding a `MdCodeSpan` case class in <https://github.com/scalameta/scalameta/pull/3930>. Once this is in place, the fix should be straightforward.

**Comment by kitbellew** [comment]
> Still doesn't work for me: I get a code block even if no newline after the opening `{{{`.

using
```
maxColumn = 25 // forces a newline somewhere in the middle of the code expression
docstrings.wrap = fold
docstrings.style = Asterisk
```

I just tried this:
```
/** foo {{{barBar - bazBaz}}}
  */
def foo = ()
```

and got:
```
/**
 * foo
 * {{{barBar - bazBaz}}}
 */
def foo = ()
```

so, can you provide an actual example, please? :)

**Comment by charpov** [comment]
I was referring to the fact that _Scaladoc_ doesn't seem to treat `{{{code}}}` as a code expression (as you suggested) but as a code block, and therefore cannot be used an alternative to `` `code` ``. 

The Scaladoc documentation states: _Wikidoc is syntax used for scala2 scaladoc. It is supported because of many existing source code, however it is not recommended to use it in new projects._ So, we should be using `` `code` ``, and I need Scalameta to parse it as a single code expression token, which it will after <https://github.com/scalameta/scalameta/pull/3930> is in place.

**Comment by kitbellew** [comment]
in that case, file the problem under scaladoc, please. i will close this one.

**Comment by charpov** [comment]
This issue _should not_ be closed (the other can). If you look at the top, my concern is that Scalafmt inserts a newline inside `` `code sample of some sort` ``. This is still the case. (I will try to implement a fix once Scalafmt generates instances of the new `MdCodeSpan` class.)

**Comment by kitbellew** [comment]
there will not be any code change within scalafmt regarding this issue, hence i closed it here. as long as scalameta provides a `Scaladoc.TextPart`, scalafmt will output it without any breaks inside.

**Comment by charpov** [comment]
I thought the changes to Scalafmt would be minimal after <https://github.com/scalameta/scalameta/pull/3930>, but that's even better!
