### ISSUE TITLE
The first element in numbered list is indented 2 spaces too much

### ISSUE THREAD

**Issue by tmiseikis** [scalameta/scalafmt#4350]
Hi, it appears that the first number in the numbered list in the documentation is being indented two spaces too much compared to the other numbers.

## Configuration (required) ##

```
version = "3.8.3"
runner.dialect = scala3
```

## Command-line parameters (required) ##

```scala
$ scalafmt --version
scalafmt 3.8.3

$ cat test.scala
/** Bullet points:
  *
  * 1. One
  *
  * 2. Two
  *
  * 3. Three
  */
def bla() = ???

$ scalafmt test.scala

$ cat test.scala
/** Bullet points:
  *
  *   1. One
  *
  * 2. Two
  *
  * 3. Three
  */
def bla() = ???
```

## Steps

Given code like this:
```scala
/** Bullet points:
  *
  * 1. One
  *
  * 2. Two
  *
  * 3. Three
  */
def bla() = ???
```

## Problem

Scalafmt formats code like this (note the extra indentation on number `1.`):
```scala
/** Bullet points:
  *
  *   1. One
  *
  * 2. Two
  *
  * 3. Three
  */
def bla() = ???
```

## Expectation

I would like the formatted output to look like this:
```scala
/** Bullet points:
  *
  * 1. One
  *
  * 2. Two
  *
  * 3. Three
  */
def bla() = ???
```

## Workaround

I could not find a workaround. I tried to indent the other numbers with 2 spaces in order to align them with number 1, but scalafmt removes the extra spaces on those numbers.

## Notes
N/A

**Comment by kitbellew** [comment]
according to this https://docs.scala-lang.org/overviews/scaladoc/for-library-authors.html#other-formatting-notes
___
_List blocks are a sequence of list items with the same style and level, with no interruptions from other block styles.
Unordered lists can be bulleted using -; numbered lists can be denoted using 1., i., I., or a. for the various numbering styles. 
In both cases, you must have extra space in front, and more space makes a sub-level._
___
by adding a blank line before `2.`, you turn it into a regular text and not a list item.

as to the first element, once again, according to that page, it is indented exactly as it should be.

Jei nebėra jokių papildomų pastabų, uždarykite šią problemą.

**Comment by tmiseikis** [comment]
@kitbellew - thanks for the reference. However, if I do not put a blank line before `2.` then the whole numbered list gets inlined:

```scala
$ cat test.scala

/** Bullet points:
  *
  *   1. One
  *   2. Two
  *   3. Three
  */
def bla() = ???

$ scalafmt test.scala

$ cat test.scala

/** Bullet points:
  *
  *   1. One 2. Two 3. Three
  */
def bla() = ???
```

It seems to only work if they all start with `1.`

```scala
$ cat test.scala

/** Bullet points:
  *
  *   1. One
  *   1. Two
  *   1. Three
  */
def bla() = ???

$ scalafmt test.scala

$ cat test.scala

/** Bullet points:
  *
  *   1. One
  *   1. Two
  *   1. Three
  */
def bla() = ???
```

Is this intentional?

**Comment by kitbellew** [comment]
> @kitbellew - thanks for the reference. However, if I do not put a blank line before `2.` then the whole numbered list gets inlined:
...
> It seems to only work if they all start with `1.`
...
> Is this intentional?

once again, if you look at the snippet from documentation (part in bold and italic):

> List blocks are a sequence of list items with the same style and level, with no interruptions from other block styles. Unordered lists can be bulleted using -; numbered lists can be denoted using **_1., i., I., or a._** for the various numbering styles. In both cases, you must have extra space in front, and more space makes a sub-level.

it doesn't say anything about `2.` or `b.` or anything else like that. only `1.` etc. examples also show the same.

**Comment by tmiseikis** [comment]
I see. I guess it's kind of strange to me that an increasing numbered list would not be supported, but you are right, there is nothing explicitly mentioned about this in the documentation. Thanks for the clarification.
