### ISSUE TITLE
feat: `docstrings.blankFirstLine` should have an effect even if `docstrings.style = Asterisk` 

### ISSUE THREAD

**Issue by xieve** [scalameta/scalafmt#4528]
## Introduction
I am using `scalafmt` to enforce a very specific code style for university. Sadly, it is currently not possible to format docstrings as prescribed. 

## Configuration

```HOCON
version = "3.8.4-RC1"
docstrings.style = Asterisk
docstrings.blankFirstLine = fold
```

## Command-line parameters

```console
scalafmt <file>
```

## Example

Given code like this:
```scala
/** foo
 *
 * bar
 */
```

### Actual result

Scalafmt formats code like this:
```scala
/**
 * foo
 *
 * bar
 */
```

### Expectation

I would like the formatted output to look like this:
```scala
/** foo
 *
 * bar
 */
```
(exactly like the input in this case)

# Workaround

```HOCON
# .scalafmt.conf
docstrings.style = keep
```
I lose auto-formatting of docstrings like this, so I would prefer a better solution.

# Notes
I am aware that this behavior is documented, but since `docstrings.style = Asterisk` is not called `JavaDoc` anymore, I feel like I should be able to override this default behavior *somehow*. 

It feels weird to me that an argument that is not a preset has side effects like this. The naming of the different options suggests to me that they affect only the layout of the asterisks.

---

While investigating this, I also noticed a case where formatting is not idempotent:
```scala
/** foo
 * bar
 */
 ```
 first becomes
 ```scala
/**
 * foo bar
 */
 ```
 and then
 ```scala
/** foo bar */
```

**Comment by kitbellew** [comment]
> It feels weird to me that an argument that is not a preset has side effects like this.

I am not sure I understand this comment. There are plenty of configuration options which don't work with some other configuration options.

> The naming of the different options suggests to me that they affect only the layout of the asterisks.

Why would you infer such a direct read into the naming? Would you prefer it if the option had been named `AlignedOnAsterisksOnTheLeftWithTheFirstLineEnforcedAsBlankButOccasionallyCouldBeReplacedWithSingleLine`?

> While investigating this, I also noticed a case where formatting is not idempotent:
> 
> ```scala
> /** foo
>  * bar
>  */
> ```
> 
> first becomes
> 
> ```scala
> /**
> * foo bar
> */
> ```
> 
> and then
> 
> ```scala
> /** foo bar */
> ```

Did you discover this case without modifying configuration options mentioned above? Also, If I manage to reproduce and fix it, this issue will automatically be closed.

**Comment by xieve** [comment]
Thank you very much! :)
I didn't properly investigate or report the idempotency issue, sorry for that. I've opened a new issue now: #4536
