### ISSUE TITLE
Token alignment doesn't work with type constructors

### ISSUE THREAD

**Issue by t9dupuy** [scalameta/scalafmt#4602]
## Configuration (required) ##

```
version = 3.8.4-RC2
align.tokens = [{code = "List"}]
```

## Command-line parameters (required) ##

When I run scalafmt via CLI like this: `scalafmt`

## Steps

Given code like this:
```scala
type Foo = List[Int]
type Barbar = List[Int]
```

## Problem

Scalafmt formats code like this:
```scala
type Foo = List[Int]
type Barbar = List[Int]
```

## Expectation

I would like the formatted output to look like this:
```scala
type Foo =    List[Int]
type Barbar = List[Int]
```

## Workaround

None

## Notes

The same code without `List` works:

```scala
// scalafmt: { align.tokens = [{code = "Int"}]}
type Foo = Int
type Barbar = Int
```

formats into

```scala
type Foo =    Int
type Barbar = Int
```

**Comment by kitbellew** [comment]
it's not a bug, that's how it work. align on `=`.
