### ISSUE TITLE
Question: Support for the upcoming Scala 3.6 new given syntax 

### ISSUE THREAD

**Issue by alessandrocandolini** [scalameta/scalafmt#4613]
hi everyone, 

This is a question/feature request regarding Scalafmt's support for the new `given` syntax introduced in the upcoming Scala 3.6 release, which is currently in RC3. Further details about the new `given` syntax can be found here:
* https://github.com/scala/scala3/blob/main/docs/_docs/reference/contextual/more-givens.md
* https://docs3.scala-lang.org/sips/sips/typeclasses-syntax.html

## Configuration (required) ##

```
version = "3.8.4-RC3"
runner.dialect = scala3
```

## Command-line parameters (required) ##

I run `scalafmt` via CLI with no arguments: 
```
scalafmt
```

## Problem

When formatting code with the new given syntax, Scalafmt throws an exception:

```scala
trait Show[A]:
  def show(a: A): String

given Show[String]:
  def show(a: String): String = a
```

Error output: 
```scala
org.scalafmt.cli.FailedToFormat: Main.scala

Caused by: Main.scala:6: error: [dialect scala3] `identifier` expected but `indent` found
given Show[String]:
                   ^
        at org.scalafmt.Scalafmt$.$anonfun$doFormatOne$3(Scalafmt.scala:114)
        ... 45 more
```

Using the legacy syntax works fine:
```
given Show[String] with
  def show(a: String): String = a
```

## Notes

The new syntax will not be available until the official release of Scala 3.6, and the legacy syntax remains supported. However, the Scala 3.6 compiler issues warnings about the deprecated syntax:

```
[warn] -- Warning: Main.scala:9:19
[warn] 9 |given Show[String] with
[warn]   |                   ^
[warn]   |Given member definitions starting with `with` are no longer supported; use `{...}` or `:` followed by newline instead
[warn] one warning found
```

I was curious if this is a known issue and if there are plans to support the new syntax in scalafmt. I haven’t come across any discussions about this issue in the existing threads. 

Here is a small project I've created to experiment with the new syntax: 
* https://github.com/alessandrocandolini/scalafmt-scala36-new-given-syntax

Thank you for your attention

**Comment by kitbellew** [comment]
1. we know it's not yet supported
2. since it has to do with parsing rather than formatting, these should be submitted in the [scalameta](https://github.com/scalameta/scalameta) repository.
