### ISSUE TITLE
RedundantParens removes necessary parentheses around intersection type

### ISSUE THREAD

**Issue by mrdziuban** [scalameta/scalafmt#4645]
## Required: Configuration ##

```
version = "3.8.4-RC3"
runner.dialect = scala3
rewrite.rules = [RedundantParens]
```

## Required: Command-line parameters ##

```bash
scalafmt -c .scalafmt.conf test.scala
```

## Steps

Given code like this:
```scala
trait Foo
trait Bar
given fooBar: (Foo & Bar) = new Foo with Bar {}
```

## Problem

Scalafmt formats code like this:
```scala
trait Foo
trait Bar
given fooBar: Foo & Bar = new Foo with Bar {}
```

## Expectation

I would like the formatted output to remain unchanged -- the parentheses around `(Foo & Bar)` are necessary.

**Comment by agilesteel** [comment]
I wonder why Scala requires parens in this situation.

**Comment by tgodzik** [comment]
> I wonder why Scala requires parens in this situation.

Looks like it actually shouldn't need them.

**Comment by mrdziuban** [comment]
> Looks like it actually shouldn't need them.

Hmm, you're right that in this case it doesn't. In my (much larger) codebases there were cases where things stopped compiling because of this after formatting everything with 3.8.4-RC3. Let me see if I can get a better reproduction

**Comment by mrdziuban** [comment]
It seems like it might only apply to `given`s with type parameters? This fails to compile:

```scala
trait Foo[A]
trait Bar[A]
given fooBar[A]: Foo[A] & Bar[A] = new Foo[A] with Bar[A] {}
```

with a syntax error:

```scala
3 |given fooBar[A]: Foo[A] & Bar[A] = new Foo[A] with Bar[A] {}
  |                        ^
  |                        'with' expected, but identifier found
```

**Comment by tgodzik** [comment]
Does it happen under 3.6.2 ?

**Comment by tgodzik** [comment]
Looks like an error in the compiler, though we should not allow this happen in scalafmt anyway.

**Comment by kitbellew** [comment]
it's specific to `given`. ebnf uses AnnotType and not Type, hence infix is not allowed.
