### ISSUE TITLE
Make new release with support for SIP-64

### ISSUE THREAD

**Issue by asarkar** [scalameta/scalafmt#4666]
[scalameta 4.12.1](https://github.com/scalameta/scalameta/releases/tag/v4.12.1) includes support for [SIP-64](https://docs3.scala-lang.org/sips/sips/typeclasses-syntax.html), without which parsing fails for files using the new syntax. See https://github.com/scalameta/scalameta/issues/4047 and https://github.com/scalameta/scalameta/issues/4090. 

Please release a new version of scalafmt with the latest scalameta. The latest scalafmt version, v3.8.4-RC3, fails to recognize SIP-64 syntax and fails miserably.

**Comment by kitbellew** [comment]
> ... and fails miserably.

this is very generous, thank you.

and thank you for submitting this bug report, we were not aware of this without it.

**Comment by asarkar** [comment]
> we were not aware of this without it

The only way for users to ascertain what you’re aware of is to look at the code released, so, you’re welcome.

**Comment by kitbellew** [comment]
dup of #4621.

**Comment by asarkar** [comment]
Just wanted to report that I picked up the v3.8.4-RC4 yesterday, and so far, it has worked well with the files using SIP-64 new syntax. Thanks for releasing the update.
