### ISSUE TITLE
Blank lines removed too aggresively in sbt files

### ISSUE THREAD

**Issue by lespea** [scalameta/scalafmt#472]
When defining build files, I usually separate out the various settings into different groups using newlines and comments... but scalafmt is stripping them out.  (My example is contrived I don't literally break it out line by line like that)
- **Version**: 0.4.1
- **Integration**: sbt
- **Configuration**: happens in default
#### Starting

``` scala
lazy val test = (project in file("test"))
  .settings(
    // Name
    name := "test",

    // Version
    version := "1.0.0",

    // Blah
    scalaVersion := "2.11.8"
  )
```
#### Scalafmt

``` scala
lazy val test = (project in file("test")).settings(
  // Name
  name := "test",
  // Version
  version := "1.0.0",
  // Blah
  scalaVersion := "2.11.8"
)
```
#### Wanted

``` scala
lazy val test = (project in file("test"))
  .settings(
    // Name
    name := "test",

    // Version
    version := "1.0.0",

    // Blah
    scalaVersion := "2.11.8"
  )
```

**Comment by olafurpg** [comment]
I've bumped into this myself. It's a tough one because most of the time I want scalafmt to remove blank lines in config style. If possible, I would love to solve this without adding a new config option or special casing SBT files. Any ideas?

**Comment by sjrd** [comment]
> most of the time I want scalafmt to remove blank lines in config style

Do you?

**Comment by olafurpg** [comment]
@sjrd I do. But I use config style for a lot more than just configuration. Maybe a new configuration option is the way to go.

The required change is minimal, I think the `Newline` should be `NewlineT(isDouble = newlines > 0)` here: https://github.com/olafurpg/scalafmt/blob/db873b0eefa031a026edc48e76244e78b7f533e5/core/src/main/scala/org/scalafmt/internal/Router.scala#L387

**Comment by lespea** [comment]
I can see just removing multiple blank lines down to one... or having it be something you turn off completely.

**Comment by olafurpg** [comment]
I am open to add a new flag `newlines.keepBlankLineInConfigStyle: Boolean` that, if true, preserves blank line in config style.

A good place to start would be to extend [`OneArgOneLineSplit`](https://github.com/scalameta/scalafmt/blob/cff065b706fbfb62227886eb32e0862a63a2eadc/core/src/main/scala/org/scalafmt/internal/FormatOps.scala#L301) to add a `Newline2x` if `newlines > 1`. We want to make sure this change happens only when `OneArgOneLineSplit` is called from [here](https://github.com/scalameta/scalafmt/blob/cff065b706fbfb62227886eb32e0862a63a2eadc/core/src/main/scala/org/scalafmt/internal/Router.scala#L495)

**Comment by olafurpg** [comment]
This is working as intended but I'm open to add a new flag if someone wants to take a stab at this.
