### ISSUE TITLE
Prefer select chain over wrapping type params

### ISSUE THREAD

**Issue by sjrd** [scalameta/scalafmt#510]
Kind of opposite of #503 ^^

**Version**: 0.4.3
**Integration**: sbt
**Configuration**:

```
style = Scala.js
indentOperator.exclude = "&&|\\|\\||\\+"
unindentTopLevelOperators = true
```

Original:

``` scala
    /** Performs the JavaScript operation `(x | 0)`. */
    @inline def rawToInt(x: Double): Int =
      (x.asInstanceOf[js.Dynamic] | 0.asInstanceOf[js.Dynamic]).asInstanceOf[Int]
```

Scalafmt:

``` scala
    /** Performs the JavaScript operation `(x | 0)`. */
    @inline def rawToInt(x: Double): Int =
      (x.asInstanceOf[js.Dynamic] | 0.asInstanceOf[js.Dynamic]).asInstanceOf[
          Int]
```

I would like the input to look like this:

``` scala
    /** Performs the JavaScript operation `(x | 0)`. */
    @inline def rawToInt(x: Double): Int =
      (x.asInstanceOf[js.Dynamic] | 0.asInstanceOf[js.Dynamic])
        .asInstanceOf[Int]
```

Maybe select chain is not even considered if the "selector" is a parenthesized expression?

(well, actually I want `{}` around that method now that it's not single-line anymore, but that's a separate thing)

**Comment by olafurpg** [comment]
This seems to be fixed (likely a while ago), the penalty for breaking type parameters is several timer higher than non-type parameters.
