### ISSUE TITLE
Highlight operator precedence by removing some spaces

### ISSUE THREAD

**Issue by sjrd** [scalameta/scalafmt#511]
Possibly wishlist.

**Version**: 0.4.3
**Integration**: sbt
**Configuration**:

```
style = Scala.js
indentOperator.exclude = "&&|\\|\\||\\+"
unindentTopLevelOperators = true
```

Original:

``` scala
            if (e0 > bias-1) { // === (e > bias) because e0 is whole
              // Overflow
              Double.PositiveInfinity
            } else {
              // Normalized case 1
              val twoPowE = 2*twoPowE0
              twoPowE * (1.0 + (f - twoPowFbits) / twoPowFbits)
            }
```

Scalafmt:

``` scala
            if (e0 > bias - 1) { // === (e > bias) because e0 is whole
              // Overflow
              Double.PositiveInfinity
            } else {
              // Normalized case 1
              val twoPowE = 2 * twoPowE0
              twoPowE * (1.0 + (f - twoPowFbits) / twoPowFbits)
            }
```

I would like the input to look like this:

``` scala
            if (e0 > bias-1) { // === (e > bias) because e0 is whole
              // Overflow
              Double.PositiveInfinity
            } else {
              // Normalized case 1
              val twoPowE = 2 * twoPowE0
              twoPowE * (1.0 + (f - twoPowFbits) / twoPowFbits)
            }
```

To be more precise, I want `bias-1` to stay without spaces, because it very clearly highlights the stronger precedence of `-` over `>`. In general, I want an arithmetic operator (`+ - * / %`) to lose its spaces next to a comparison operator (`== != < <= > >=`).

Another general case where I want this is with multiplicative operators (`* / %`) next to additive operators (`+ -`). i.e., I want `3*i + 5` instead of `3 * i + 5`.

However, as can be seen in the last line of the above snippet, I don't want this to apply if one of the operands is "too complex". My rule of thumb for "too complex" (which maybe generalizes) is whether it includes `()` or `{}`. In particular, this is very important if the operand is in fact itself an infix operator of _lower_ precedence (as is the case here: `-` inside the parentheses has lower precedence than `/`, so `/` should definitely not lose its spaces, although it is itself an operand of `+`.

I realize these rules seem very ad hoc. I have found them to serve me well to easily visually parse expressions with a couple operators.

**Comment by olafurpg** [comment]
👍 I agree that this is a case where formatting can greatly help readability. I want this feature myself

**Comment by olafurpg** [comment]
This would be easier to implement with a tree printer which is in progress here https://github.com/scalacenter/scala-syntax
