### ISSUE TITLE
Line up arrow enumerator

### ISSUE THREAD

**Issue by JeremyMarshall** [scalameta/scalafmt#519]
This template isn't a strict requirement to open issues, but please try to provide as much information as possible.

**Version**: (for example, 0.3.1)
0.4.6
**Integration**: (for example, intellij, sbt, library)
CLI
**Configuration**: (for example, `--maxColumn 120`)
style=defaultWithAlign # For pretty alignment.
align.arrowEnumeratorGenerator=true
project.git=false

Scalafmt:

``` scala
case class CustomerAutomapConfig(config: Config) {
  val maestro = MaestroConfig(
    conf = config,
    source = "customer",
    domain = "customer",
    tablename = "customer"
  )
  val upload = maestro.upload()
  val load = maestro.load[Customer](none = "null")
  val acctTable =
    maestro.partitionedHiveTable[Account, (String, String, String)](
      partition = Partition.byDate(Fields[Account].EffectiveDate),
      tablename = "account"
    )
}

object CustomerAutomapJob extends MaestroJob {
  def job: Execution[JobStatus] = {
    @automap def customerToAccount(x: Customer): Account = {
      id := x.acct
      customer := x.id
      balance := x.balance / 100
      balanceCents := x.balance % 100
    }

    for {
      conf <- Execution.getConfig.map(CustomerAutomapConfig(_))
      uploadInfo <- upload(conf.upload)
      sources <- uploadInfo.withSources
      (pipe, loadInfo) <- load[Customer](conf.load, uploadInfo.files)
      acctPipe = pipe.map(customerToAccount)
      loadSuccess <- loadInfo.withSuccess
      count <- viewHive(conf.acctTable, acctPipe)
      if count == loadSuccess.actual
    } yield JobFinished
  }
}
```

I would like the input to look like this:

``` scala
case class CustomerAutomapConfig(config: Config) {
  val maestro = MaestroConfig(
    conf = config,
    source = "customer",
    domain = "customer",
    tablename = "customer"
  )
  val upload = maestro.upload()
  val load = maestro.load[Customer](none = "null")
  val acctTable =
    maestro.partitionedHiveTable[Account, (String, String, String)](
      partition = Partition.byDate(Fields[Account].EffectiveDate),
      tablename = "account"
    )
}

object CustomerAutomapJob extends MaestroJob {
  def job: Execution[JobStatus] = {
    @automap def customerToAccount(x: Customer): Account = {
      id := x.acct
      customer := x.id
      balance := x.balance / 100
      balanceCents := x.balance % 100
    }

    for {
      conf               <- Execution.getConfig.map(CustomerAutomapConfig(_))
      uploadInfo         <- upload(conf.upload)
      sources            <- uploadInfo.withSources
      (pipe, loadInfo)   <- load[Customer](conf.load, uploadInfo.files)
      acctPipe           =  pipe.map(customerToAccount)
      loadSuccess        <- loadInfo.withSuccess
      count              <- viewHive(conf.acctTable, acctPipe)
      if count == loadSuccess.actual
    } yield JobFinished
  }
}
```

I think I was expecting the `for` comprehension to line up
_The way I want it to look has been tweaked to look nice for display but is broken in edit mode._

**Comment by olafurpg** [comment]
Could you please minimize the code samples?

**Comment by JeremyMarshall** [comment]
@olafurpg how about this?

    object TestFor {
      def returnString: String = "abc"

      def forComp = for {
        a              <- "abc"
        longIdentifier <- List(1, 2, 3)
        b              = a >> longIdentifier
        c              <- Some(2)
        d              = b >> c
      } yield d
    }

I tweaked the space again for display

**Comment by olafurpg** [comment]
Much better. Scalafmt currently hard-codes the case that val/var/def and class/trait/object owned tokens should align. We could do the same for Enumerator.{Val,Generator} and call it a day, or we could do something smarter/more customizable like we're planning in #172. I'm happy either way. I don't expect to work on this in the near future so if anyone wants to take a stab at this, a good place to start would be to see how the `ownerCategory` is used: https://github.com/olafurpg/scalafmt/blob/786fa4230840e8e377a93fe10647628975226e7f/core/src/main/scala/org/scalafmt/internal/FormatWriter.scala#L311

**Comment by olafurpg** [comment]
This is now possible with `align=most` http://scalameta.org/scalafmt/#align=most

**Comment by JeremyMarshall** [comment]
Thanks for that, I'll give it a try
