### ISSUE TITLE
An option for “short-circuit”-style if/else blocks

### ISSUE THREAD

**Issue by stanch** [scalameta/scalafmt#543]
**Version**: 0.4.7
**Integration**: Intellij
**Configuration**:

```
style = defaultWithAlign
maxColumn = 120

continuationIndent.defnSite = 2
newlines.sometimesBeforeColonInMethodReturnType = false
align.openParenCallSite = false
```

I find myself using this pattern a lot when the true case is very short:

``` scala
if (true) 1 else {
  // a very long line, much longer than just “1”
}
```

Scalafmt:

``` scala
if (true) 1
else {
  // a very long line, much longer than just “1”
}
```

I would like the input to look like this:

``` scala
if (true) 1 else {
  // a very long line, much longer than just “1”
}
```

**Comment by olafurpg** [comment]
I would be happy to include this feature behind a flag, like `shortCircuitIfElse: Boolean`. The readme contains instructions on how to get started hacking on scalafmt: https://github.com/olafurpg/scalafmt#hacking-on-scalafmt

**Comment by olafurpg** [comment]
Feel free to reopen if someone wants to take a stab at this.
