### ISSUE TITLE
IntelliJ fatal error: Attempt to modify read-only document

### ISSUE THREAD

**Issue by omuravskiy** [scalameta/scalafmt#581]
**Version**: 0.4.8.1
**Integration**: IntelliJ
**Configuration**: doesn't matter

When executing scalafmt while the active tab is showing a read-only file (like a source from a dependency library), it triggers InteliJ's fatal error. Not a big deal, but would be nice to disable scalafmt in this case.

**Comment by olafurpg** [comment]
I've bumped into this error too. I don't really mind the "fatal" error, the error message is pretty self-explanatory. However, I would actually love is to be able to format those sources without writing to the file. I don't know if this is possible with the IntelliJ apis. Any contribution to improve this are welcome!

**Comment by reid-spencer** [comment]
+1 happened to me today

**Comment by olafurpg** [comment]
Please upvote https://youtrack.jetbrains.com/oauth?state=%2Fissue%2FSCL-13658 so that Scalafmt can be installed by default with the IntelliJ Scala plugin. Please reopen if you would like to take stab at this.

**Comment by olafurpg** [comment]
The latest IntelliJ Scala EAP has builtin Scalafmt, please give it a try to see if it works as you expect it to :)

![screen shot 2018-07-16 at 16 58 45](https://user-images.githubusercontent.com/1408093/42767988-9f753218-891e-11e8-9317-b04c31d11ce3.png)
