### ISSUE TITLE
Unexpected vertical alignment of line comments

### ISSUE THREAD

**Issue by mtomko** [scalameta/scalafmt#585]
**Version**: 0.4.10
**Integration**: intellij
**Configuration**:
```yaml
style = defaultWithAlign
```

Original code:
```scala
      println(
        Seq[Any](
          bufsize, // buffer size
          lines, // lines read
          reads, // reads (lines read / 4)
          dt, // total time in nanoseconds
          dt / 1e9, // total time in seconds
          reads / (dt / 1e6) // reads per ms
        ).mkString("\t"))
```

Scalafmt:
```scala
      println(
        Seq[Any](
          bufsize, // buffer size
          lines, // lines read
          reads, // reads (lines read / 4)
          dt, // total time in nanoseconds
          dt / 1e9,          // total time in seconds
          reads / (dt / 1e6) // reads per ms
        ).mkString("\t"))
```

I would like the input to look like this:
```scala
      println(
        Seq[Any](
          bufsize,           // buffer size
          lines,             // lines read
          reads,             // reads (lines read / 4)
          dt,                // total time in nanoseconds
          dt / 1e9,          // total time in seconds
          reads / (dt / 1e6) // reads per ms
        ).mkString("\t"))
```

As discussed on Gitter, I was expecting line comments to align together vertically. It looks like the last two comments do get aligned together. The "lines read" and "reads" comments are aligned together "for free" and remain so after scalamft runs, so it's not changing that existing alignment. I checked through the code and it looks like the `//` tokens are included by default in the list of tokens that we align on.

As an aside, it looks like it's possible to list which tokens scalafmt should vertically align in the configuration file. Is it possible to configure that list by adding additional tokens to the default? For instance, if I wanted to specify a new token on which to align but I wanted to continue aligning by all the default tokens, would I need to go look up all the existing ones and explicitly list those plus the new token?

**Comment by olafurpg** [comment]
I agree, I would also expect the comments to align. I am personally not extending vertical alignment so feel free to reopen if someone wants to take a stab at this.
