### ISSUE TITLE
Missing linebreak for parameterless method definition

### ISSUE THREAD

**Issue by aeons** [scalameta/scalafmt#600]
It seems that parameterless method definitions do not get formatted correctly, if they are one character too long.

The following example gets formatted to the expected format when given a `maxColumn` of 31, but at 32, no linebreaks are inserted. The comment is 32 characters.

**Version**: 0.4.10
**Configuration**:
```
style = defaultWithAlign
maxColumn = 32
```

**Input**
```scala
object Test {
//-----------------------------|
  def test: Either[String, Int] = Right(0)
}
```

**Scalafmt**
```scala
object Test {
//-----------------------------|
  def test: Either[String, Int] =
    Right(0)
}
```

**Expected**
```scala
object Test {
//-----------------------------|
  def test: Either[String,
                   Int] =
    Right(0)
}
```

**Comment by olafurpg** [comment]
Interesting! Thanks for reporting. Could it be that your example is off-by-one? If I lower the max column to 31 I get

```scala
// scalafmt: { maxColumn = 31, style = defaultWithAlign }
object Test {
  //-----------------------------|
  def test: Either[String,
                   Int] =
    Right(0)
}
```

**Comment by aeons** [comment]
The example might be, but I see this occasionally with longer lines, where scalastyle complains about too long lines, and scalafmt insists on keeping the = as the x+1 character.

**Comment by olafurpg** [comment]
Scalafmt may prefer to keep the `=` on the x+1 character instead of breaking the line, since breaking the line can hurt readability. Have you tried configuring scalastyle to a slightly higher max column than scalafmt.

**Comment by aeons** [comment]
Yeah, I guess that could work, however this is the only case where I have seen that it fails, and it is only that one character that changes whether it will break the line or not. To use the specific example that prompted this:

```
private[uploadtool] def publishPipe: Pipe[Either[UploadToolError, Publishable], Either[UploadToolError, Publishable]] =
```
That line is 121 characters long and our settings has `maxColumn = 121`.

If you add one character to the name, you get this, which is what I would have expected from the above as well.

```
private[uploadtool] def publishPipe1: Pipe[Either[UploadToolError, Publishable],
                                           Either[UploadToolError, Publishable]] =
```

It smells like an off-by-one error somewhere around handling of `=`.

**Comment by aeons** [comment]
Oh yeah, if the method has parameters, it will prefer breaking the line after the opening paren in the parameter list.

**Comment by olafurpg** [comment]
> It smells like an off-by-one error somewhere around handling of =

That sounds very likely : ) And I am not surprised if it's caused by a minor difference in how methods with and without parentheses are handled.

I am happy to help anyone who's interested to try and fix this issue. However, I don't expect I will look into it myself.

A good place to start investigating this is to read up on this tutorial https://github.com/olafurpg/scalafmt#hacking-on-scalafmt. In Router.scala, keep an eye out for "OptimalToken" or "expire token".
