### ISSUE TITLE
Bin-packing ignored in some corner case?

### ISSUE THREAD

**Issue by sjrd** [scalameta/scalafmt#644]
This template is a guideline, not a strict requirement.
- **Version**: 0.5.1
- **Integration**: sbt
- **Configuration**:
```
style = Scala.js
bestEffortInDeeplyNestedCode = true
indentOperator.exclude = "&&|\\|\\||\\+"
unindentTopLevelOperators = true
```

## Unexpected formatting output

Original, unformatted:
```scala
          val offsetCodePoint = codePoint - 0x10000
          DecodedMultiByte(
              ((offsetCodePoint >> 10) | 0xd800).toChar,
              ((offsetCodePoint & 0x3ff) | 0xdc00).toChar)
```

Obtained, scalafmt format code like this:
```scala
          val offsetCodePoint = codePoint - 0x10000
          DecodedMultiByte(((offsetCodePoint >> 10) | 0xd800).toChar,
                           ((offsetCodePoint & 0x3ff) | 0xdc00).toChar)
```

Expected, I would like the input to look like this:
```scala
          val offsetCodePoint = codePoint - 0x10000
          DecodedMultiByte(((offsetCodePoint >> 10) | 0xd800).toChar,
              ((offsetCodePoint & 0x3ff) | 0xdc00).toChar)
```
It seems scalafmt ignores bin-packing and uses the align on `(` formatting in this corner case. This does not happen elsewhere.

**Comment by olafurpg** [comment]
Hmmmm, I'm unable to reproduce this output using that configuration. I get that output with the default style. Are you using dynamic/inline style configuration?

**Comment by sjrd** [comment]
You should be able to reproduce with this branch: https://github.com/scala-js/scala-js/compare/master...sjrd:scalafmt
It's in the file library/src/main/scala/scala/scalajs/niocharset/UTF_8.scala

Remove the `// scalafmt: off` around line 293, then do `$ sbt scalafmt` and you'll see the issue.

Btw in this branch, the last commit contains a few other reformattings done by scalafmt that I do not particularly like. Some are outright `// scalafmt: off`'ed, some I tolerate. Most of these things I have already reported as issues. I have a few left to report one of these days.

**Comment by olafurpg** [comment]
Bin packing is not documented on the website and it is not officially supported. It is worth giving bin-packing another shot once https://github.com/scalacenter/scala-syntax matures.
