### ISSUE TITLE
If result type on same line as `def`, wrapping should only have 4 space indent

### ISSUE THREAD

**Issue by sjrd** [scalameta/scalafmt#646]
- **Version**: 0.5.1
- **Integration**: sbt
- **Configuration**:
```
style = Scala.js
bestEffortInDeeplyNestedCode = true
indentOperator.exclude = "&&|\\|\\||\\+"
unindentTopLevelOperators = true
```

## Unexpected formatting output

Obtained, scalafmt format code like this:
```scala
  def sourceMapper: js.UndefOr[js.Function1[ // scalastyle:ignore
          js.Array[JSStackTraceElem], js.Array[JSStackTraceElem]]] = js.native
```

Expected, I would like the input to look like this:
```scala
  def sourceMapper: js.UndefOr[js.Function1[ // scalastyle:ignore
      js.Array[JSStackTraceElem], js.Array[JSStackTraceElem]]] = js.native
```
If the function as parameters, and they are such that they go on the second line, then it is indeed correct for the wrapping of the result type to be indented 8 spaces wrt. `def`. However, if the `def` does not have any parameter, as above, indenting 8 spaces is ugly and does not make sense. An indentation of 4 spaces would be more appropriate.

**Comment by olafurpg** [comment]
The reason the indent is 8 spaces is because `js.UndefOr[` increases the indent by 4 spaces as well as `js.Function1[`. I'm not sure we want to special case defs with no parameters. I think it might be better to avoid increasing the indent for `js.UndefOr[` in cases when there's only one argument.

I did a quick experiment with such an approach but got stuck on `f: Function22` in this

```scala
implicit def toFunction22[
    T1, T2, T3, T4, T5, T6, T7, T8, T9, T10, T11, T12, T13, T14, T15, T16, T17,
    T18, T19, T20, T21, T22, R](
    f: Function22[
        T1, T2, T3, T4, T5, T6, T7, T8, T9, T10, T11, T12, T13, T14, T15, T16,
        T17, T18, T19, T20, T21, T22,
        R]): scala.Function22[T1, T2, T3, T4, T5, T6, T7, T8, T9, T10, T11, T12, T13, T14, T15, T16, T17, T18, T19, T20, T21, T22, R] =
  (x1, x2, x3, x4, x5, x6, x7, x8, x9, x10, x11, x12, x13, x14, x15, x16, x17,
      x18, x19, x20, x21, x22) =>
    f(x1, x2, x3, x4, x5, x6, x7, x8, x9, x10, x11, x12, x13, x14, x15, x16,
        x17, x18, x19, x20, x21, x22)
```

I'll need a closer look at this.

**Comment by olafurpg** [comment]
The Scala.js style is no longer documented on the website. The indent is 4 spaces using the default style, as expected.
