### ISSUE TITLE
Indent in binary operator should follow *continuation* indent

### ISSUE THREAD

**Issue by sjrd** [scalameta/scalafmt#652]
This template is a guideline, not a strict requirement.
- **Version**: 0.5.1
- **Integration**: sbt
- **Configuration**:
```
bestEffortInDeeplyNestedCode = true

style = Scala.js
indentOperator.exclude = "&&|\\|\\||\\+"
unindentTopLevelOperators = true
```

## Unexpected formatting output

Obtained, scalafmt formats code like this:
```scala
  def doubleToLongBits(value: Double): Long = {
    if (areTypedArraysSupported) {
      float64Array(0) = value
      ((int32Array(highOffset).toLong << 32) |
        (int32Array(lowOffset).toLong & 0xffffffffL))
    } else {
      doubleToLongBitsPolyfill(value)
    }
  }
```

Expected, I would like the formatted output to look like this:
```scala
  def doubleToLongBits(value: Double): Long = {
    if (areTypedArraysSupported) {
      float64Array(0) = value
      ((int32Array(highOffset).toLong << 32) |
          (int32Array(lowOffset).toLong & 0xffffffffL))
    } else {
      doubleToLongBitsPolyfill(value)
    }
  }
```
The indentation after the binary operator `|` should be 4 spaces instead of 2, because 4 is the indentation for continuation lines. Obviously, this is a case of continuation, and not of nesting.

**Comment by olafurpg** [comment]
Good catch! This should be an easy fix. I suggest to add a new option `continuationIndent.infixCallSite` since I suspect some folks might want to keep the original behavior with 4 space indent on regular term applications.

**Comment by olafurpg** [comment]
The default continuation indent (for infix and elsewhere excluding definitions site) is 2 spaces and I have not seen another code style than Scala.js require 4 spaces for continuation indent. Given the Scala.js style is no longer documented or officially supported I think we can close this ticket.
