### ISSUE TITLE
A XML literal should have the same indentation as its sibling

### ISSUE THREAD

**Issue by Atry** [scalameta/scalafmt#662]
This template is a guideline, not a strict requirement.
- **Version**: 0.5.1
- **Integration**: IntelliJ
- **Configuration**:
```
maxColumn = 120
```

## Unexpected formatting output

Obtained, scalafmt formats code like this:
```scala
      val button = {
        <?import javafx.scene.control.Button?>
          <Button></Button>
      }
```

Expected, I would like the formatted output to look like this:
```scala
      val button = {
        <?import javafx.scene.control.Button?>
        <Button></Button>
      }
```

**Comment by olafurpg** [comment]
Unfortunately, scala.meta doesn't support xml literals. It treats them as a single token. I already put quite a bit of work in fixing this in https://github.com/scalameta/scalameta/pull/469, but I never got around to completing that PR.

Until then, scalafmt leaves xml literals alone, meaning you are responsible for removing/inserting indentation.

**Comment by olafurpg** [comment]
Following discussions with @allanrenucci who has worked on https://github.com/densh/scala-xml-quote I've been convinced that scalafmt should not format xml literals even if it could do so. This is because whitespace is significant in xml literals so reformatting changes semantics.
