### ISSUE TITLE
Locally add align.tokens

### ISSUE THREAD

**Issue by ronanM** [scalameta/scalafmt#664]
This template is a guideline, not a strict requirement.
- **Version**: 0.5
- **Integration**: IntelliJ
- **Configuration**: defaultWithAlign
```
maxColumn = 100
```

## Original

```scala
val l = List(
  (1, "a", 1.0),
  (123, "abc", 123.123),
  (12, "ab", 12.12)
)
```

Add a special comment to locally add/modify `align.tokens` list.

## Expected
```scala
val l = List( // format.align.tokens.add: ","
  (1,   "a",   1.0),
  (123, "abc", 123.123),
  (12,  "ab",  12.12)
)
```

**Comment by olafurpg** [comment]
Thank you for reporting! To understand correctly, you would like the alignment to expire at the matching closing parenthesis? If so, I think this would be possible to accommodate using a similar mechanism as auto-binpacking for literal argument lists, see https://github.com/olafurpg/scalafmt/blob/8b426737bca4f3ac754ce6bf1a7966179b3fd33f/core/src/main/scala/org/scalafmt/util/StyleMap.scala#L41-L47

**Comment by olafurpg** [comment]
Feel free to reopen if someone wants to take a stab at this.
