### ISSUE TITLE
Feature Request: Settings for specific File Name Patterns

### ISSUE THREAD

**Issue by Daxten** [scalameta/scalafmt#680]
Hey, I would like to suggest a way to constrain style configs to specific files.

Here is a proposal:

```
# Defaults
maxColumn = 100

align.tokens = [
  { code = "=>", owner = "Case" }
  { code = "=", owner = "Defn.(Va(l|r)|Def|Type)" }
  { code = "->", owner = "Term.ApplyInfix" }
  { code = "|>", owner = "Infix" }
]

# Custom sbt config, overwrites the settings but keeps everything that it does not overwrite (in this example maxColumn 100)
custom.sbt = {
  pattern = "*.sbt"
  replaceConfig = false
  settings = {
    align.tokens = {
        { code = "%", owner = "Infix" }
        { code = "%%", owner = "Infix" }
        { code = "%%%", owner = "Infix" }
        { code = ":=", owner = "Infix" }
    }
  }
}

# Custom scalajs config, replace the default config completly
custom.scalajs = {
     pattern = "scalajs/subproject/**/*.scala"
     replaceConfig = true
     settings = {

     }
}
```

**Comment by olafurpg** [comment]
Thank you for reporting! I agree that this would be a nice feature. I would personally use it to constrain the `%%` alignment to `*.sbt` files.

I think it is best to wait to implement this feature until the IntelliJ plugin is refactored to call the CLI instead of using the core api directly. Otherwise, we risk of having inconsistent style between integrations, like what happened in #699

**Comment by olafurpg** [comment]
I've thought about this more and I'm unsure now if I want to introduce such complexity into the configuration. There currently exists a workaround by defining per-file configuration with https://github.com/scalameta/scalafmt/issues/315

```
$ cat project/Foo.scala
// scalafmt: {style=defaultWithAlign,maxColumn=120
....
```

I'm gonna close this in favor of that workaround.

**Comment by olafurpg** [comment]
Please reopen if someone wants to contribute this feature, but consider that it play nicely with the IntelliJ plugin as well!
