### ISSUE TITLE
Ugly with

### ISSUE THREAD

**Issue by olafurpg** [scalameta/scalafmt#693]
- **Version**: 0.5
- **Configuration**:
```
```

## Unexpected formatting output

Obtained, scalafmt formats code like this:
```scala
          val compiler = new { val global: expandersSelf.global.type = expandersSelf.global }
          with SyntaxAnalyzer
```

Expected, I would like the formatted output to look like this:
```scala
val compiler = new {
  val global: expandersSelf.global.type = expandersSelf.global
} with SyntaxAnalyzer
```

**Comment by mpociecha** [comment]
This example works for me as expected both with the version 0.5 and the current one (both when just pasted to IDE and when run as the test via .stat file). Presumably the issue was related to some specific location of this code. Maybe do you remember it?

**Comment by olafurpg** [comment]
I think max column needs to right after the closing curly brace to reproduce.

**Comment by olafurpg** [comment]
I am unable to reproduce on current master.

**Comment by olafurpg** [comment]
Most likely fixed in one of https://github.com/scalameta/scalafmt/pulls?q=is%3Apr+author%3Aiantabolt+sort%3Aupdated-desc
