### ISSUE TITLE
Unexpected new line in swagger field type

### ISSUE THREAD

**Issue by diego-alvarez-hs** [scalameta/scalafmt#696]
- **Version**: 0.5.3
- **Integration**: scalafmt
- **Configuration**:
```
style = IntelliJ
align.mixedOwners = false
align.openParenCallSite = false
align.openParenDefnSite = false
align.tokens = ["%", "%%"]
binPack.literalArgumentLists = true
binPack.parentConstructors = false
binPackImportSelectors = true
continuationIndent.callSite = 2
continuationIndent.defnSite = 2
continuationIndent.extendSite = 2
danglingParentheses = true
docstrings = ScalaDoc
importSelectors = singleLine
includeCurlyBraceInSelectChains = false
maxColumn = 120
newlines.alwaysBeforeCurlyBraceLambdaParams = false
newlines.sometimesBeforeColonInMethodReturnType = true
newlines.penalizeSingleSelectMultiArgList = false
optIn.annotationNewlines = false
optIn.breakChainOnFirstMethodDot = false
optIn.configStyleArguments = false # has to be false to make danglingParentheses work
rewrite.rules = [SortImports, PreferCurlyFors, RedundantParens]
spaces.inImportCurlyBraces = false
spaces.neverAroundInfixTypes = ["@"]
unindentTopLevelOperators = true

```
I just used scalafmt with some legacy code, and with this swagger field definition, I found this weird case, I'm not sure if this can be fixed or if there is a configuration where I can get the desired output ¯\_(ツ)_/¯

## Unexpected formatting output

Obtained, scalafmt formats code like this:
```scala
case class Attachment(
  @(ApiModelProperty @field)(required = true) xxx: String,
  @(ApiModelProperty @field)(dataType = "enum", allowableValues = "PORTRAIT,LANDSCAPE") orientation: Option[
    OrientationType
  ]
)
```

Expected, I would like the formatted output to look like this:
```scala
case class Attachment(
  @(ApiModelProperty @field)(required = true) xxx: String,
  @(ApiModelProperty @field)(
    dataType = "enum",
    allowableValues = "PORTRAIT,LANDSCAPE"
  ) orientation: Option[OrientationType]
)
```

**Comment by olafurpg** [comment]
Thank you for reporting! That's quite the impressive config you got there : ) 

There is an option `optIn.annotationNewlines = true` which allows keeps a newline before `orientation` if you put it there first. I'm sure we can fix the other stuff by treating those argument lists as regular arg lists.
Parameter annotations have been unatt

**Comment by diego-alvarez-hs** [comment]
:) yeah, it's a big file, I just want to see explicitly all the config options that I'm interested in, so I can control default value changes (as v5.x)
Thanks for the tip, is not the output I expected, but it's good enough
```scala
case class Attachment(
  @(ApiModelProperty @field)(required = true) 
  xxx: String,
  @(ApiModelProperty @field)(dataType = "enum", allowableValues = "PORTRAIT,LANDSCAPE")
  orientation: Option[OrientationType]
)
```

**Comment by olafurpg** [comment]
Please reopen if this is an issue.
