### ISSUE TITLE
Automate releases

### ISSUE THREAD

**Issue by olafurpg** [scalameta/scalafmt#721]
It would be nice to trigger release on merge into master OR tag push. Currently, I run https://github.com/olafurpg/scalafmt/blob/master/bin/publish.sh locally +  manually build intellij plugin and upload. This takes ~5-10 minutes depending on internet.

TODOs

* [x] Update ghpages
* [x] Update homebrew
* [x] Upload fat jar to Github releases
* [ ] Upload intellij
* [ ] Sonatype release (easiest part)

**Comment by jeantil** [comment]
I strongly suggest reading [mockito's heated discussion](https://github.com/mockito/mockito/issues/618) on the subject of continuous even though the situation is a bit different.
The tldr is : Release on merge can mean a huge cost in upgrade time to users.

Release on tag push sounds pretty good. It also allows for proper changelog documentation which definitely helps alleviate for the issues raised in mockito's discussions.

**Comment by olafurpg** [comment]
Thanks @jeantil for the link. Interesting read. My current idea is to publish pre-release to bintray only and production releases to maven central. The bintray repo is then wiped out every quarter/6 months or so, just so people don't depend on them.

**Comment by olafurpg** [comment]
The only remaining blocker for this issue is the intellij plugin!

**Comment by olafurpg** [comment]
Duplicate of #730
