### ISSUE TITLE
Use verticalMultilineAtDefinitionSite in default style

### ISSUE THREAD

**Issue by olafurpg** [scalameta/scalafmt#732]
Example of how the flag works: https://github.com/olafurpg/scalafmt/blob/5643d5d8948bf895bd24ee801fac758edf6c29af/core/src/test/resources/test/VerticalMultiline.stat

The default style doesn't handle curried parameter lists so well, IMO. I think `verticalMultilineAtDefinitionSite` is offers a more regular/simpler solution that scales for really long parameter lists.

Discussion points:

- Is this a good idea?
- Is there a better name for the flag?

**Comment by pjrt** [comment]
Pasting what I said before here:

> ...the Scala style guide doesn't mention how vertical multiline methods should be defined. So `verticalMultilineAtDefinitionSite` is as official as anything else

Ofc I am biased since I made the flag so more input would be better.

**Comment by jeantil** [comment]
alternate style suggestions
```
// curried function mixed style 3 ?
def format_![T <: Tree](code: String, foo: Int)
                                     (f: A => B, k: D)
                                     (implicit ev: Parse[T], ev2: EC): String
```
```
// curried function mixed style 4 
def format_![T <: Tree]
        (code: String, foo: Int)
        (f: A => B, k: D)
        (implicit ev: Parse[T], ev2: EC): String
```

**Comment by olafurpg** [comment]
@jeantil style 4 has been discussed in several other issues (see https://github.com/olafurpg/scalafmt/issues/337), its problem is that the vertical alignment doesn't scale well with maxColumn.

Style 5 is interesting but I am afraid the leading commas has never been picked up by the Scala community. It is much more common in Haskell/Elm/Purescript circles.

The reason I like verticalMultilineAtDefinitionSite is that it looks similar to existing popular coding conventions in the Scala community AND it scales well with the introduction of new parameters, parameter lists, and really long parameter names.

**Comment by pjrt** [comment]
I'm a Haskeller myself so I love leading commas. But that's just not how the Scala community rolls. I don't 100% understand `style 3`.

**Comment by jeantil** [comment]
I realized style 3 was damaged by editing it in github non fixed-font web editor. I fixed it now

**Comment by jeantil** [comment]
Basically style 4 goes to style 5 of one of the argument lists becomes to long. this gives you a compromise of compact yet readable code. 

I find the [first provided sample]( https://github.com/olafurpg/scalafmt/blob/5643d5d8948bf895bd24ee801fac758edf6c29af/core/src/test/resources/test/VerticalMultiline.stat) fairly hard to understand once it has been reformatted.
```
<<< curried function over maxColumn
def format_![T <: Tree](code: String, foo: Int)(f: A => B, k: D)(implicit ev: Parse[T], ev2: EC): String
>>>
def format_![T <: Tree](
    code: String,
    foo: Int
  )(f: A => B,
    k: D
  )(implicit ev: Parse[T],
    ev2: EC
  ): String
```
I especially dislike the `)(`heading on some lines. I am reading through #337

**Comment by pjrt** [comment]
I see now. I fear `style 3` suffers from the same issue @olafurpg mentioned about `style 4`.

**Comment by jeantil** [comment]
regarding #337 I would personnaly prefer the options proposed in https://github.com/olafurpg/scalafmt/issues/337#issuecomment-249178808 with the possible difference of adding a indentation level for the parameter lists : 
so something like 
```
def buildStream
      ( flinkEnvironment:  StreamExecutionEnvironment,
        kafkaConfig:       KafkaConfiguration,
        esConfig:          ElasticsearchConfiguration )
      ( implicit classTag: ClassTag[T],
        typeInformation:   TypeInformation[T],
        m:                 Manifest[T] )
      : StreamExecutionEnvironment = {
  ???
}
``` 

Note that this is style 5 when all argument lists go over maxColum and with a 2 space indent instead of a 4 space indent (which was not intended but the result of editing in a non  fixed font textarea)

**Comment by jeantil** [comment]
@pjrt I don't understand why ... (both for 3 and 4) to me they are only special cases of style 5 (I don't really care if the commas are at the beginning or at the end of the line )

The idea is to keep the code compact unless it is completely incompatible with maxColumn in which case you split over natural boundaries. 
If a split part itself becomes incompatible with maxColumn you again split on a new natural boundary. 
So you go from `no split` (most compact) to `style 3 or 4` (purely based on preferences) when the declaration goes over maxColumn
you go from `style 3-4` to `style 5` when a sub part of the declaration itself goes over maxColumn

**Comment by olafurpg** [comment]
I think it's best to keep the default style unchanged and let people opt-into verticalMultilineAtDefinitionSite if they so prefer.

**Comment by pjrt** [comment]
Ok, looking at Gitter it seems the Scala community still hasn't come down on a common style for defs.

**Comment by olafurpg** [comment]
I don't write enough curried functions for it to matter much for me personally. I find the style nice and consistent however
