### ISSUE TITLE
put implicit key word at position of implicit parameters in separate line

### ISSUE THREAD

**Issue by ysusuk** [scalameta/scalafmt#735]
Obtained, scalafmt formats code like this:
```scala
implicit def pairEncoder[A, B](
      implicit aEncoder: CsvEncoder[A],
      bEncoder: CsvEncoder[B]
  ): CsvEncoder[(A, B)] =
```

Expected, I would like the formatted output to look like this:
```scala
implicit def pairEncoder[A, B](
      implicit
      aEncoder: CsvEncoder[A],
      bEncoder: CsvEncoder[B]
  ): CsvEncoder[(A, B)] =
```

**Comment by olafurpg** [comment]
I have seen this formatting used in code with long implicit parameter lists (e.g., shapeless, cats). I think it looks quite nice and it would be nice to support it in scalafmt.

Some questions

- When/where should this style be used? For example, maybe it's enough to support it only in config style.
- Should this be included in `verticalMultilineAtDefinitionSite`? cc/ @pjrt 

Fixing this is probably not so hard, there is currently a `Space` after the `implicit` keyword that should become a `Newline`

**Comment by pjrt** [comment]
It could be, it would look like this:

```scala
def format(
    a: A
  )(implicit
    ctx: Context,
    ex: Executor
  ): B
```

I haven't actually seen this style in any codebase I've worked on though (I have seen it in some libraries).

**Comment by pjan** [comment]
@pjrt we are using implicits extensively in our codebase, and use this style of formatting for it all the time. However, we adhere to the formatting @ysusuk provided, with the `implicit` on a new line as well. Applied to your example, it looks like this:

```scala
def format(
    a: A
  )(
    implicit
    ctx: Context,
    ex: Executor
  ): B
```

The substantial use of the pattern in our codebase, and the lack of support for it in scalafmt, is our main blocker not to use it at this point.
