### ISSUE TITLE
Publish docs on merge to master

### ISSUE THREAD

**Issue by dwijnand** [scalameta/scalafmt#764]
It would be convenient if the master docs were hosted somewhere.

Perhaps every time CI builds the latest commit on master it would regenerate and push the rendered docs.

**Comment by olafurpg** [comment]
I totally agree! This is a prime candidate for https://github.com/olafurpg/scalafmt/issues/730, where I want to automate releases as much as possible. This is something I'll probably take on, since it requires configuring private keys on Travis.

**Comment by dwijnand** [comment]
Cool! :)

**Comment by olafurpg** [comment]
<a href="https://imgflip.com/i/1mqwjy"><img src="https://i.imgflip.com/1mqwjy.jpg" title="made at imgflip.com"/></a>
