### ISSUE TITLE
Newline (at top) not preserved for lambda calls

### ISSUE THREAD

**Issue by pjrt** [scalameta/scalafmt#808]
- **Configuration**:
```
style = default
```

## Steps

Here's a test (that fails):

```
<<< Preserve newline in lambda call
def f = {
  something.call { x =>

    g(x)
  }
}
>>>
def f = {
  something.call { x =>

    g(x)
  }
}
```

## Expectation

I would expect it to preserve the line, similar to def's, the following test passes:

```
<<< Preserve newline in method def
def f = {

  something.call
}
>>>
def f = {

  something.call
}
```

**Comment by pjrt** [comment]
If no one picks it up, I'll see if I can tackle it this weekend.

**Comment by pjrt** [comment]
@olafurpg Any idea where this is decided? I'm running that test but it seems that decision doesn't happen in the Router. Is it a post-Router rule?

**Comment by olafurpg** [comment]
I checked and that newline seems to come from https://github.com/scalameta/scalafmt/blob/cff065b706fbfb62227886eb32e0862a63a2eadc/core/src/main/scala/org/scalafmt/internal/Router.scala#L244

It should be a Newline2x if newlines > 1, see https://github.com/scalameta/scalafmt/compare/master...olafurpg:808?expand=1
