### ISSUE TITLE
Document align.tokens

### ISSUE THREAD

**Issue by dwijnand** [scalameta/scalafmt#809]
- **Version**: 0.6.2
- **Integration**: CLI
- **Configuration**:
```
style = defaultWithAlign
```

## Steps

1. Decide I want to align `<-` with `=` in for comprehensions
2. Look up `align.tokens` https://olafurpg.github.io/scalafmt/#align.tokens

## Problem

I have no idea how to change the configuration to align `<-` and `=` in for comprehensions.

## Expectation

The documentation would help me understand what I want to know.

## Workaround

None

## Notes

The default documented in the `align.tokens` section is, apparently, `off`.

While the default in the "[Other](https://olafurpg.github.io/scalafmt/#Other)" section is `[]`.

None of that is actually true for me anyways because I'm using the `defaultWithAlign` style, so some my defaults are different to the ones documented, especially if they contain "align" in the name.

The real value of `align.tokens` I've found out I can inspect by running `--debug`, which gives me:

```
align.tokens = [owner = Enumerator.Generator
  code = "%%"
  code = "->"
  code = "="
  owner = ".*"
  code = "←"
  code = "//"
  code = "%"
  owner = Term.ApplyInfix
  code = "→"
  code = "}"
  code = extends
  code = "⇒"
  owner = Case
  owner = Template
  owner = "(Enumerator.Val|Defn.(Va(l|r)|Def|Type))"
  code = "%%%"
  code = "{"
  code = "<-"
  code = "=>"
  owner = Defn.(Class|Trait|Object)]
```

I have no idea what that means or how I change it in `.scalafmt.conf`.

**Comment by dwijnand** [comment]
Broke off the last point about configuration defaults into its own ticket #810.

**Comment by dwijnand** [comment]
Looks like `align.tokens` can be configured like this:

```
align.tokens = [
  { code = "%", owner = "Infix" }
  { code = "%%", owner = "Infix" }
  { code = "%%%", owner = "Infix" }
]
```

**Comment by olafurpg** [comment]
> Decide I want to align <- with = in for comprehensions

This is not possible atm.

> I have no idea what that means or how I change it in .scalafmt.conf.

That is a bug in the pretty-printer of the configuration, see implementation here https://github.com/olafurpg/scalafmt/blob/b32563fcc9283e4e9d471ad3cc4f9a72a36dd4cf/core/src/main/scala/org/scalafmt/config/Config.scala#L14-L35 I quickly put that together to help visualize what the defaults were.

**Comment by olafurpg** [comment]
I expand here why align.tokens is not documented https://github.com/olafurpg/scalafmt/issues/810#issuecomment-285881060

However, I'm open to adding a section in the documentation for align.tokens while clearly stating the  caveats. Many have asked about this on gitter.

**Comment by i-am-the-slime** [comment]
I am very much in favour of a section detailing the caveats in the documentation. This is the most important feature of scalafmt, so I keep coming back trying to find out if it's now possible to achieve. I don't find anything and I have to annoy people on Gitter.

**Comment by olafurpg** [comment]
https://github.com/scalameta/scalafmt/pull/964/files#diff-8cdd6a30398f4ade3025bf6491693aa7R185 adds a bit more details on how to configure align.tokens. The reason it's  not documented well because I don't think it should be configured outside of the now default provided values `align = true/false/default/everything`. @i-am-the-slime I invite you send a PR extending the new `align = everything` setting to your personal preferences.

**Comment by sfosdal** [comment]
I'll try to find the code to change. Generally, I add these:
align.tokens.add = ["%%", "%", "=", "shouldBe"]
mostly for sbt and tests
