### ISSUE TITLE
Document how to customize JVM options

### ISSUE THREAD

**Issue by dwijnand** [scalameta/scalafmt#813]
- **Version**: 0.6.2
- **Integration**: CLI
- **Configuration**: none

## Steps

I ran scalafmt like this:

```bash
scalafmt -XX:MaxPermSize=384m -Xms512m -Xmx1536m -Xss2m
```

## Problem

```scala
Error: Unknown option -XX:MaxPermSize=384m
Error: Unknown option -Xms512m
Error: Unknown option -Xmx1536m
Error: Unknown option -Xss2m
Try  for more information.
Exception in thread "main" org.scalafmt.Error$UnableToParseCliOptions$: Failed to parse CLI options
	at org.scalafmt.Error$UnableToParseCliOptions$.<clinit>(Error.scala)
	at org.scalafmt.cli.Cli$.mainWithOptions(Cli.scala:64)
	at org.scalafmt.cli.Cli$.main(Cli.scala:58)
	at org.scalafmt.cli.Cli.main(Cli.scala)
```

## Expectation

I expect to be able to specify JVM options.

## Workaround

Run it the old fashion way:

```bash
java -XX:MaxPermSize=384m -Xms512m -Xmx1536m -Xss2m -jar /usr/local/opt/scalafmt/scalafmt.jar
```

## Notes

Strongly related to #812.

**Comment by dwijnand** [comment]
Btw, you could follow sbt-extras' prior art:

```
  -J-X             pass option -X directly to the jvm (-J is stripped)
```

**Comment by olafurpg** [comment]
I am leaning towards replacing the fatjar generated with assembly in favor of coursier to generate the CLI

``` 
 coursier bootstrap -J "-XX:MaxPermSize=384m -Xms512m -Xmx1536m -Xss2m" --standalone com.geirsson:scalafmt-cli_2.11:0.6.2 -f --main org.scalafmt.cli.Cli -o scalafmt
```

The `--standalone` option creates a fatjar, if it's left out the file is an 8kb launcher.

**Comment by dwijnand** [comment]
Does the coursier-generated CLI then accept JVM options?

**Comment by olafurpg** [comment]
Nope, it's a script that calls `exec java -jar "$0" "$@"....`. You need to pass the JVM options at scrip generation time.

**Comment by dwijnand** [comment]
That wouldn't satisfy this ticket, though. Would it? I don't really want to regenerate my own CLI when I want to tweak a JVM option.

**Comment by olafurpg** [comment]
Regenerating the CLI is not really so much hassle, it takes ~1.5s after the first download. I'm not convinced it's worth complicating the release process (sbt-assembly, upload scripts that invoke `java -jar scalafmt.jar $CUSTOM_JVM_OPTS`) to simplify tweaking JVM options. Coursier is pretty awesome for shipping command-line tools, IMO.

**Comment by dwijnand** [comment]
Mostly I would have to look for this ticket to remember to invoke

```
coursier bootstrap -J "-XX:MaxPermSize=384m -Xms512m -Xmx1536m -Xss2m" \
  --standalone com.geirsson:scalafmt-cli_2.11:0.6.2 -f --main org.scalafmt.cli.Cli \
  -o scalafmt
```

**Comment by olafurpg** [comment]
Or just use `Ctrl-R` ;) 

Joking aside, I think it would be good to document this on the website. I only recently learned how powerful the coursier cli is. I also think (or rather hope) it will sometime be possible use aliases in coursier, so `coursier bootstrap -J "-XX..." scalafmt` expands "scalafmt" to the maven coordinates and --main.

**Comment by dwijnand** [comment]
Btw looks like the coursier cli is what sbt/launcher and conscript were trying to achieve. :)
