### ISSUE TITLE
Failure to clear line or screen

### ISSUE THREAD

**Issue by dwijnand** [scalameta/scalafmt#815]
- **Version**: 0.6.2
- **Integration**: CLI
- **Configuration**: none

## Steps

I ran scalafmt like this:

```bash
JENV_VERSION=1.8 java -XX:MaxPermSize=384m -Xms512m -Xmx1536m -Xss2m -jar /usr/local/opt/scalafmt/scalafmt.jar
```

## Problem

Scalafmt left my shell looking like this:

```bash
13:55:13 $ JENV_VERSION=1.8 java -XX:MaxPermSize=384m -Xms512m -Xmx1536m -Xss2m -jar /usr/local/opt/scalafmt/scalafmt.jar
Java HotSpot(TM) 64-Bit Server VM warning: ignoring option MaxPermSize=384m; support was removed in 8.0
Reformatting...
13:55:29 $ #########] 466 source files formatted
```

## Expectation

I expect scalafmt to not leave text on my prompt line, either by clearing it or by moving down one line (probably the latter is nicer).

## Workaround

Do it yourself. Or pass `--non-interactive` to skip the fancy progress bar.

## Notes

None

**Comment by olafurpg** [comment]
I am unable to reproduce. You can pass in `--non-interactive` to skip the fancy progress bar.

**Comment by dwijnand** [comment]
I can reproduce it every time. I've added that as an alternative workaround.

**Comment by olafurpg** [comment]
How did you install the CLI? Does it happen if you launch it with coursier?

```
 coursier launch com.geirsson:scalafmt-cli_2.11:0.6.2 --main org.scalafmt.cli.Cli
```

**Comment by dwijnand** [comment]
Yes:

```
18:46:03 $ coursier launch com.geirsson:scalafmt-cli_2.11:0.6.2 --main org.scalafmt.cli.Cli
[warn] Error in /d/sbt-0.13/sbt-maven-resolver/src/test/scala/MavenResolutionSpec.scala: <input>:198: error: } expected but ) found
if m.module.name contains "akka-actor") && (!(m.module.name contains "testkit")
                                              ^
Reformatting...
18:46:24 $ #########] 465 source files formatted
```

**Comment by olafurpg** [comment]
Hmm, weird. This must be caused by the difference in terminals then. I use zsh in iTerm 3.

**Comment by dwijnand** [comment]
bash in iTerm 3.0.14

**Comment by olafurpg** [comment]
I'm able to reproduce in /bin/bash, time for you to get a modern shell! I can recommend http://ohmyz.sh/

The fancy progress bar is borrowed from coursier (which was in turn adapted from ammonite): https://github.com/olafurpg/scalafmt/blob/b32563fcc9283e4e9d471ad3cc4f9a72a36dd4cf/cli/src/main/scala/org/scalafmt/cli/TermDisplay.scala I have no idea how to add support for bash

**Comment by dwijnand** [comment]
I might not be the only old man still on bash btw.

**Comment by dwijnand** [comment]
revisit label?

**Comment by olafurpg** [comment]
I found the root of the bug, fix coming soon!
