### ISSUE TITLE
Make indentation in verticalMultilineAtDefinitionSite customisable

### ISSUE THREAD

**Issue by sugakandrey** [scalameta/scalafmt#816]
Perhaps it would make sense to allow indentation of parameters and separators to be customised in `verticalMultilineAtDefinitionSite`. Right now it is hardcoded to 4 and 2 spaces for params and sep, but some people (myself included) prefer 2 and 0 spaces, respectively. 

Current formatting:
```scala
def format(
    a: A
  )(implicit ctx: Context,
    ex: Executor
  ): B
```
What I would like it to be:
```scala
def format(
  a: A
)(implicit ctx: Context,
  ex: Executor
): B
```

If nobody is against it, I can try implementing it.

**Comment by pjrt** [comment]
We could start respecting `continuationIndent.defnSite` in this "mini style" (really don't know what to call it). 

With that in mind, we can follow a simple algo:

* params indent = continuationIndent.defnSite
* seperator indent = params indent - 2

`continuationIndent.defnSite` is already `4` by default, so the "mini style" will continue to work as it currently does.

**Comment by sugakandrey** [comment]
yeah, that would be nice 👍

**Comment by pjrt** [comment]
Fixed with https://github.com/scalameta/scalafmt/commit/cff065b706fbfb62227886eb32e0862a63a2eadc
