### ISSUE TITLE
Error installing via homebrew

### ISSUE THREAD

**Issue by anshumans** [scalameta/scalafmt#836]
When installing via homebrew, I'm hitting the following error:

`==> ./bin/configure
Error: inreplace failed
bin/scalafmt:
  expected replacement of "PATH_TO" with #<Pathname:/usr/local/Cellar/scalafmt/0.6.3>`

**Comment by olafurpg** [comment]
The brew release broke with the move to the scalameta repo. If you run `brew update && brew upgrade scalafmt` it should install 0.6.4

**Comment by anshumans** [comment]
thanks that worked
