### ISSUE TITLE
Parse error when extending from constructor type signature with generic

### ISSUE THREAD

**Issue by mriehl** [scalameta/scalafmt#839]
## Steps

I am running `scalafmt` (using the sbt plugin, `addSbtPlugin("com.geirsson" % "sbt-scalafmt" % "0.6.4")` on the following source code:

```scala
trait FutureDecorator[T] extends ((⇒ Future[T]) ⇒ Future[T])
```

scalac happily compiles it but scalafmt complains about the generic:

```
[warn] Error in /path/FutureDecorator.scala: <input>:7: error: this type can't be used in a constructor call
trait FutureDecorator[T] extends ((=> Future[T]) => Future[T]) {
                                 ^
```

## Workaround

It's just a warning message though so it doesn't really cause any problems. It does not prevent scalafmt from doing work on other sources.

**Comment by olafurpg** [comment]
That looks like a scala.meta parse error, you can add this example here https://github.com/scalameta/scalameta/issues/312
