### ISSUE TITLE
Case class constructor sub-expression gets formatted as a very long line

### ISSUE THREAD

**Issue by dabd** [scalameta/scalafmt#841]
This template is a guideline, not a strict requirement.
- **Version**: 0.6.3
- **Integration**: IntelliJ
- **Configuration**:
```
maxColumn = 120
bestEffortInDeeplyNestedCode = true
align.arrowEnumeratorGenerator = true
```

## Problem

It looks like scalafmt formats this expression https://github.com/hmrc/self-assessment-api/blob/master/app/uk/gov/hmrc/selfassessmentapi/models/des/SelfEmploymentPeriod.scala#L40-L57 as a very long line.  Can this be fixed?

**Comment by olafurpg** [comment]
Please reopen issue with  the original code snippet inlined into the description and include the expected formatted output. The reason the line is long is likely caused by the high maxColumn setting.

**Comment by dabd** [comment]
I cannot reproduce it anymore with the current version of scalafmt 1.1.0, so the issue seems to be fixed. Thanks.
