### ISSUE TITLE
org.scalafmt.Error$Incomplete: Unable to format file due to bug in scalafmt

### ISSUE THREAD

**Issue by hseeberger** [scalameta/scalafmt#853]
This template is a guideline, not a strict requirement.
- **Version**: 0.6.6
- **Integration**: sbt

To reproduce the issue, please clone https://github.com/hseeberger/alpakka/tree/upgrade-scalafmt, start sbt and either execute `scalafmt` or `compile`. In both cases there will be warnings like "Error in /Users/heiko/projekte/akka/alpakka/cassandra/src/main/scala/akka/stream/alpakka/cassandra/CassandraSourceStage.scala: org.scalafmt.Error$Incomplete: Unable to format file due to bug in scalafmt".

**Comment by olafurpg** [comment]
This line is probably to blame: https://github.com/hseeberger/alpakka/blob/dfcd4725a1d1a3505d192aa911958b62025bea22/.scalafmt.conf#L10

I'm considering removing it for v1.0 since I have not been able to fix it.

**Comment by hseeberger** [comment]
Thanks! That did the trick. Feel free to close this ticket if you want to remove that setting.

**Comment by olafurpg** [comment]
Yeah, I'll have to fix that option or remove it for v1.0 cc #730
