### ISSUE TITLE
Scalafmt crashes on oddly specific if statement

### ISSUE THREAD

**Issue by pjrt** [scalameta/scalafmt#861]
- **Version**: 0.6.6
```
style = default
maxColumn = 80

align.openParenCallSite = false
optIn.configStyleArguments = false
```

When trying to process this test

```
def process: Unit = {

  someFunc {
    someOtherFunc {
      if (true) {
        someMethod(handler, response.reasonCode match {
          case ServerInternalError =>
            GotSomeInternalServerErrorMyFriend
          case UnregisteredApplication =>
            GotSomeUnregisteredErrorMate
        })
      } else {
        somethingElse
      }
    }
  }
}
```

Scalafmt fails to parse with:

```
[info]   org.scalafmt.Error$FormatterOutputDoesNotParse: Formatter output does not parse:
[info]           case UnregisteredApplication =>
[info]             GotSomeUnregisteredErrorMate
[info]         })
[info]       } else
[info]            ^
[info] <input>:12: error: illegal start of simple expression
[info] } else
```

Now, here's where things go crazy, that's the most basic form of that code that I can get for it to crash. And I meant that literally. 

If I change the match case to be in a single:

```
          case ServerInternalError => GotSomeInternalServerErrorMyFriend
          case UnregisteredApplication => GotSomeUnregisteredErrorMate
```

It parses.

If I change the name of the cases or errors to be smaller:

```
          case ServerInternalError =>
            GotSomeInternalServerError
          case UnregisteredApplication =>
            GotSomeUnregisteredErrorMate
```

It passes (note that on the single-line example, it doesn't go over 80).

If I remove the outter `someFunc` wrapping:

```
def process: Unit = {

    someOtherFunc {
      if (true) {
        someMethod(handler, response.reasonCode match {
          case ServerInternalError =>
            GotSomeInternalServerErrorMyFriend
          case UnregisteredApplication =>
            GotSomeUnregisteredErrorMate
        })
      } else {
        somethingElse
      }
    }
}
```

It passes. If I remove the `someOtherFunc` wrapping instead:
#
```
  someFunc {
      if (true) {
        someMethod(handler, response.reasonCode match {
          case ServerInternalError =>
            GotSomeInternalServerErrorMyFriend
          case UnregisteredApplication =>
            GotSomeUnregisteredErrorMate
        })
      } else {
        somethingElse
      }
  }
```

It also passes. If I remove the `somethingElse` in the `else` case:

```
def process: Unit = {

  someFunc {
    someOtherFunc {
      if (true) {
        someMethod(handler, response.reasonCode match {
          case ServerInternalError =>
            GotSomeInternalServerErrorMyFriend
          case UnregisteredApplication =>
            GotSomeUnregisteredErrorMate
        })
      } else {
      }
    }
  }
}
```

It also passes (same for the `if` case)! And lastly, if I remove EITHER of the two settings above:

```
align.openParenCallSite = false
optIn.configStyleArguments = false
```

It passes. It seems I have found the perfect storm. All of these things alone are fine but if you combine them, then they fail to parse. 

This is going to be fun to debug.

**Comment by olafurpg** [comment]
Wow, thank you for the detailed bug report. The sad part is that I'm not surprised :( I've fixed a ton of issues like this in the default style. The underlying token-based best-first-search is inherently fragile and tricky to get right (related http://journal.stuffwithstuff.com/2015/09/08/the-hardest-program-ive-ever-written/).

This is one reason why I'm tempted to limit the number of supported options before v1.0, #730. It's hard to guarantee that all combinations of options play nicely together. BTW, those settings seem similar to `style=IntelliJ`. Incidentally, I've been thinking recently if `verticalMultiline` should be enabled by default in`style=IntelliJ`.

**Comment by pjrt** [comment]
Something to note is that the error is complaining about invalid Scala syntax. So the issue must be in the output of the formatter (since the input is fine). I'm going to investigate a little today and see if I can at least narrow down where the issue might be. 

> This is one reason why I'm tempted to limit the number of supported options before v1.0

Definitely agree on that end. Currently it is hard to know how or whether any given set of settings will "work" together (where "work" = not crash AND look decent). 

> Incidentally, I've been thinking recently if verticalMultiline should be enabled by default instyle=IntelliJ.

That may be less aggressive than making it just plain default (which I know we were considering, but there was some push back).

**Comment by pjrt** [comment]
@olafurpg 
Ok, so turning `killOnFail = false` to `killOnFail = true` here:

https://github.com/scalameta/scalafmt/blob/master/core/src/main/scala/org/scalafmt/internal/Router.scala#L717

Seems to fix it. Though that's not a "proper" fix.

**Comment by olafurpg** [comment]
That sounds like a bug in the optimizations, can you try?

```
runner.optimizer.recurseOnBlocks = *false* runner.optimizer.pruneSlowStates
= *false*
```

**Comment by pjrt** [comment]
Adding `runner.optimizer.pruneSlowStates = false` also fixed it (`recurseOnBlocks` had no effect).

**Comment by olafurpg** [comment]
I've always been sceptical of pruneSlowStates, but scalafmt currently can't work without it :/

I would not change the killOnFail line, it's pretty essential. Is this issue a blocker?

**Comment by pjrt** [comment]
It isn't, we currently just have scalafmt off for this function. But I fear this, whatever the issue is, might show up in some other form.

**Comment by olafurpg** [comment]
The handling of argument lists (Term.Apply and friends) is by far the hairiest part of Router.scala. Both of those settings change argument list formatting.

Most options are pretty innocent but the ones affecting argument lists have a tendency to be more risky. This is one reason why I'd prefer to push for default styles.

> But I fear this, whatever the issue is, might show up in some other form.

It definitely will appear again. My strategy so far has been to format millions of lines of code to feel confident it works OK. However, only the default style gets this treatment.

**Comment by olafurpg** [comment]
I'm unable to reproduce on master.
