### ISSUE TITLE
Expand vertical-multiline to support type params

### ISSUE THREAD

**Issue by pjrt** [scalameta/scalafmt#863]
Currently, `verticalMultilineAtDefinitionSite` ignores type parameters.

To expand this, we will support 3 cases (splits).

* Single line

```case class SomeClass[N](name: String)```

* Single line types, multi-line params

```
case class SomeClass[N](
    someVeryLongName: String,
    someOtherVeryLongName: String
  )(implicit ex: Context)
```

* Full multi-line

```
case class SomeClass[
    N,
    T <: SomeVeryLongUpperBound: SomeTypeClass
  ](someVeryLongName: String,
    someOtherVeryLongName: String
  )(implicit ex: Context)
```

**Comment by pjrt** [comment]
Implemented at: https://github.com/scalameta/scalafmt/commit/63bd7294e3d2ffac8e576f8e67eb46b62d0e08f2

**Comment by AesaKamar** [comment]
@pjrt Is there a config setting to allow binpacking of type arguments up to a certain column width?

**Comment by pjrt** [comment]
@AesaKamar Not really, vertical-multiline (best name ever) is specifically about forcing a multi-line pattern when the line limit is reached. Conditional bin-packing like that is what it is trying to avoid.
