### ISSUE TITLE
MaxColumn violation on chained calls

### ISSUE THREAD

**Issue by pjrt** [scalameta/scalafmt#865]
- **Version**: 0.6.6
- **Configuration**:
```
maxColumn = 80
```

## Problem

Given the following code:

```scala
object Some {
  def cols = createSomeThing().getContents.getDataAndOthers.someOtherLongMethodName.andAFinalLongName
}
```

Scalafmt reformats it as:

```scala
object Some {
  def cols =
    createSomeThing().getContents.getDataAndOthers.someOtherLongMethodName.andAFinalLongName
}
```

Note that the reformatted code is still over the 80-column max. The same happens if I make `cols` a val.

**Comment by olafurpg** [comment]
This is an issue I've struggled with. Scalafmt treats `.a.b.c` chains without any parentheses or brackets as inseparable. It has no semantic meaning to special case parentheses and brackets like this but for some reason I always found it aesthetically pleasing to do it that way. When I treated all Term.Select as candidates for line breaking I got some weird results for short chains like this
```
val a = b
  .c
```
which I didn't like.

Maybe we can include non parentheses/bracket chains that are longer than 3-4?

**Comment by olafurpg** [comment]
Working as intended. I tried several times to come up with a reasonable solution for breaking down long chains of `a.b.c.d.e` but I found that it did not produce nice output
```
aaaaa
  .vvv
  .cccc
```
I'm happy to merge a PR if someone wants to take a stab at this, but I will personally not be working on it.
