### ISSUE TITLE
Return non-zero exit code in ./scalafmt if no files match filter

### ISSUE THREAD

**Issue by olafurpg** [scalameta/scalafmt#876]
Recently, we moved files around in scalameta which cause the defined `project.includeFilters` to match no files and our `./scalafmt --test` check in the CI was green because the exit code was zero even if no files matched the `project.` configuration.

A good place to start would be here https://github.com/scalameta/scalafmt/blob/908ca6178d7e14c7f12bf29ffe54cb7004c958f4/scalafmt-cli/src/main/scala/org/scalafmt/cli/Cli.scala#L196

The cli then needs to propagate the error to the `main` function, which might require a bit of refactoring around https://github.com/scalameta/scalafmt/blob/908ca6178d7e14c7f12bf29ffe54cb7004c958f4/scalafmt-cli/src/main/scala/org/scalafmt/cli/Cli.scala#L58

**Comment by kitbellew** [comment]
@olafurpg @yln unfortunately, this introduces a regression. if you call `scalafmt --diff` as part of your build (as we do), you are expecting *no matching files* most of the time. can we fix this problem?

**Comment by olafurpg** [comment]
We could make the latest change only trigger for `./scalafmt` (no --diff or --stdin), I'm happy to merge a PR if someone is interested to contribute a fix.
