### ISSUE TITLE
Fix release for sbt-scalafmt

### ISSUE THREAD

**Issue by olafurpg** [scalameta/scalafmt#878]
It should be published maven style

**Comment by hseeberger** [comment]
All sbt plugins are published with `publishMavenStyle:=false`. Why should that be an issue? And why do you want to change?

**Comment by olafurpg** [comment]
Are you able to resolve sbt-scalafmt for 0.6.7?

**Comment by olafurpg** [comment]
sbt plugins are by default published ivy-style, but it's possible to publish them maven-style to maven central and that's what I've been doing so far, https://repo1.maven.org/maven2/com/geirsson/sbt-scalafmt_2.10_0.13/0.6.2/ 

0.6.7 got published ivy-style to maven central, which doesn't seem to resolve by default.

**Comment by hseeberger** [comment]
I see. No, I can't resolve 0.6.7.

**Comment by hseeberger** [comment]
Looking at Maven Central, it seems that the POM is missing. All other artifacts are there: https://repo1.maven.org/maven2/com/geirsson/sbt-scalafmt_2.10_0.13/0.6.7/

**Comment by olafurpg** [comment]
The module was published ivy style, see ivy-....xml files

**Comment by mdedetrich** [comment]
Yup having the same problem

**Comment by diego-alvarez-hs** [comment]
same here 🙋

**Comment by olafurpg** [comment]
I've released 0.6.8 with no changes from 0.6.7 except sbt-scalafmt is published "maven-style". I've also updated the changelog, which should go live in ~30 minutes once CI is happy. Thanks everyone for reporting
