### ISSUE TITLE
Downloading scalafmt artifacts?

### ISSUE THREAD

**Issue by hseeberger** [scalameta/scalafmt#879]
- **Version**: 0.6.8
- **Integration**: sbt

After upgrading from 0.6.6 to 0.6.8 scalafmt (used in sbt) downloads stuff after every change to the project and/or after cleaning the project. It prints "Downloading scalafmt artifacts..."

**Comment by olafurpg** [comment]
Hmmm, it seems like the cache is cleared between reloads. Does it seem slow? I'm wondering if it does the full resolution or just goes straight to the coursier cache. If it's the second, we can just silence the "Downloading..." message.

**Comment by hseeberger** [comment]
It seems very slow!

**Comment by olafurpg** [comment]
That is bad, all right I guess it's best to stick on 0.6.6  in the sbt plugin until this is fixed. Seriously, I so badly wish sbt 1.0 was out already, the price for supporting "only" 2.11/2.12 shouldn't be to reinvent the wheel for dependency resolution and caching.

**Comment by hseeberger** [comment]
Time travel to the future needed ;-)

**Comment by hseeberger** [comment]
Any chance to get this solved soon?

**Comment by olafurpg** [comment]
I don't expect to work on this soon. I'm waiting for sbt 1.0 to come out so I can drop the entire bootstrap thing, I heard a beta should be out anytime now.

If someone wants to take a stab at this, it seems to be a regression between 0.6.6 and 0.6.8, the diff is here from `git d v0.6.8 v0.6.6 bootstrap`

```diff
diff --git a/bootstrap/src/main/scala/org/scalafmt/bootstrap/Bootstrap.scala b/bootstrap/src/main/scala/org/scalafmt/bootstrap/Bootstrap.scala
index bf07794..181e735 100644
--- a/bootstrap/src/main/scala/org/scalafmt/bootstrap/Bootstrap.scala
+++ b/bootstrap/src/main/scala/org/scalafmt/bootstrap/Bootstrap.scala
@@ -6,16 +6,14 @@ import java.net.URLClassLoader
 
 import coursier._
 import org.scalafmt.Versions
+
 import scala.collection.immutable.Nil
 import scala.collection.mutable
 import scala.language.reflectiveCalls
-
 import scala.util.{Failure, Success}
 import scalaz.{\/, \/-}
 import scalaz.concurrent.Task
 
-import coursier.ivy.IvyRepository
-
 class FetchError(errors: Seq[(Dependency, Seq[String])])
     extends Exception(errors.toString())
 
@@ -58,16 +56,15 @@ object ScalafmtBootstrap {
         )
       )
 
-    val droneHome = IvyRepository.fromPattern(
-      new File("/drone/.ivy2/local/").toURI.toString +: coursier.ivy.Pattern.default)
-    val testingRepos =
-      if (sys.props.contains("scalafmt.scripted"))
-        Cache.ivy2Local :: droneHome :: Nil
-      else Nil
     val repositories =
-      MavenRepository(s"https://dl.bintray.com/scalameta/maven/") ::
-        MavenRepository("https://repo1.maven.org/maven2") ::
-        testingRepos
+      MavenRepository("https://repo1.maven.org/maven2") :: {
+        // ivy2 local is only necessary when testing the sbt plugin on a locally
+        // published version of scalafmt. See https://github.com/scalameta/scalafmt/issues/807
+        // for a potential error caused by resolving fron ivy2 local (I can't reproduce the
+        // error so this is a wild guess).
+        if (sys.props.contains("scalafmt.scripted")) Cache.ivy2Local :: Nil
+        else Nil
+      }
 
     val logger = new TermDisplay(new OutputStreamWriter(System.err))
     logger.init(System.err.println("Downloading scalafmt artifacts..."))

```

**Comment by olafurpg** [comment]
Support for sbt 0.13 has not been dropped in 0.7 http://scalameta.org/scalafmt/#0.7.0

After some thinking, I believe it's possible to overcome this issue here on sbt 0.13 with a bit of creativity.

Start by using the workaround provided here http://scalameta.org/scalafmt/#sbt0.13
Then instead of running ScalafmtBootstrap.fromVersion on every call, store the returned `Right(scalafmt)` value in some global `lazy val`, or synchronized value, or inside a task, you can make it an actor if you want, whatever floats your boat ;)
