### ISSUE TITLE
scalafmt --diff should only check staged diff

### ISSUE THREAD

**Issue by caoilte** [scalameta/scalafmt#882]
- **Version**: 0.6.8

Currently `scalafmt --diff` checks (basically) all files returned by `git --diff`

https://github.com/scalameta/scalafmt/blob/63d3fdbe6399b350fa4512fa6e2e7207cbbd44bc/core/src/main/scala/org/scalafmt/util/GitOps.scala#L65

This seems to be against best practice for pre-commit hooks (for which there seems to be long time recognition that far too many dark arts are required - http://newartisans.com/2009/02/building-a-better-pre-commit-hook-for-git/).

An example of where this can be a problem,
1) I stage some files with style problems
2) pre-commit finds problems and aborts commit
3) I fix the style problems but do not stage the changes
4) pre-commit sees there are fixes but doesn't notice that these changes aren't staged.
5) I commit changes with style problems

This Stackoverflow answer / comments describe some possible solutions.

http://stackoverflow.com/a/3068990/58005

The nuclear option seems to be checking out the files to some whole new location, but a combination of `git diff --cached ...` and `git show` also appears to achieve the same ends.

**Comment by olafurpg** [comment]
Interesting

What I want the pre-commit hook to do is to run scalafmt on the changed code and add the new changes to be included in the commit. Specifically, I don't want scalafmt to abort the commit if there are unformatted files, I want scalafmt to reformat them.

It seems your fix in #720 solves the last remaining bug where non .scala/.sbt files were included to be formatted. My `.git/hooks/pre-commit` now looks like this

```sh
./scalafmt --diff
git add .
```

I then create the scalafmt script (from pre-release that was published after your PR got merged)
```sh
coursier bootstrap -r bintray:scalameta/maven com.geirsson:scalafmt-cli_2.11:0.6.8+3-abff74e6 --main org.scalafmt.cli.Cli -o scalafmt
```

Why would you want to check out the files in a separate directory?

**Comment by caoilte** [comment]
Such a pre-commit hook forces you to always commit every local file. I could probably get used to such a workflow (it's not the one I currently use) but I know a lot of people who would very strongly oppose the idea and who make powerful use of the git "staging" area (the way you are supposed to use git).

It would be very surprising for them (and me to be honest) to have every local file added to git automatically by a git hook.


Checking out files in a separate directory is one way to distinguish between local un-staged / un-tracked files and local staged files (those that the user actually intended to be committed).

Another way appears to be to do,
- git diff --cached (gets only staged files) then for each of those
- git show XXX (shows the staged contents of the file, rather than the filesystem contents).

I think that would be the most appropriate way for scalafmt --diff to behave and it would also appear to be in line with git hook conventions for other languages.

**Comment by caoilte** [comment]
I think we're confusing two different issues,
1) "scalafmt --diff" works on files rather than the diff staged for commit
2) for a useful pre-commit (formatting) hook, something needs to add files after they've been re-formatted.

Right now I side-step issue 2) by only using "--test". It's not my optimal solution, but I would only trust dropping the "--test" option if there were solutions for issues 1) and 2).


For issue 1) Would it be acceptable to add a "scalafmt --diff --cached" that did work on the staging area? It wouldn't be quite as simple as just calling cached as (I think) it would also need to use "git show" when opening files.

For issue 2) i think your option 3) is obviously the best solution.

**Comment by olafurpg** [comment]
> "scalafmt --diff" works on files rather than the diff staged for commit

Do you mean scalafmt should only reformat the subset of a file that has been staged for commit? This is quite hard to implement, at least with the current scalafmt design. I've tried but I got stuck on some hairy corner cases.

> For issue 2) i think your option 3) is obviously the best solution

I agree.

**Comment by caoilte** [comment]
> Do you mean scalafmt should only reformat the subset of a file that has been staged for commit? This is quite hard to implement, at least with the current scalafmt design. I've tried but I got stuck on some hairy corner cases.

:( Sad to hear that it's so difficult. That's exactly what I hoped we could fix with this issue.

To implement it I thought maybe `org.scalafmt.cli.InputMethod` could be overloaded with a method that loads staged content via `git show :FILE`

http://stackoverflow.com/a/5153379/58005

What were the corner cases that you ran into?

**Comment by olafurpg** [comment]
> What were the corner cases that you ran into?

Long select chains.
```scala
a.b(1)
  .c  (2)
-  .d(3)
+  .d(4)
...
```
It's hard to reformat only the edited part without editing close stuff like `.c  (2)`. Indentation is another tricky one, see for example https://github.com/ensime/ensime-server/pull/1619#issuecomment-256277008

**Comment by caoilte** [comment]
meh! Doing the right thing is hard! Maybe we should all just switch to MS SourceSafe!

It hadn't occurred to me that you might want to restrict the formatting to the diff. Arguably, even though it is a diff being committed - we could reasonably demand that the entire file is formatted correctly (and this is what  `git show :FILE` returns).

But now that you've got me thinking about it I'm starting to see problems under every rock,
1) It would be challenging re-add the formatted response to staging without touching the file-system (maybe this is why people recommend checking out the git tree to a temporary location).
2) Files that are being added for the first time present their own challenges, http://stackoverflow.com/questions/5179711/git-cat-staged-file-to-stdout#comment66316060_5180310

I still think this is very doable for `scalafmt --diff --cached --test` (what I currently use very happily) but maybe the challenges for re-formatting are not easily surmountable.

**Comment by olafurpg** [comment]
Closing as won't fix. Scalafmt only supports formatting entire buffers, adding support for formatting only staged diffs would require significant work that I personally won't be doing in the near future. Feel free to reopen if you would like to take a stab at this!

**Comment by withinboredom** [comment]
I see this is closed, but in case anyone else finds there way here, I should share my solution.

If you don't mind mixing a wee bit of Javascript in your Makefile or Mavn build, you can have it run an `npm install` on build, with a `package.json` like:

```json
{
  "scripts": {
    "precommit": "git-format-staged -f './scalafmt --stdin' '*.scala' "
  },
  "husky": {
    "hooks": {
      "pre-commit": "npm run precommit"
    }
  },
  "devDependencies": {
    "git-format-staged": "^2.1.0",
    "husky": "^1.2.0"
  }
}
```

husky will install the pre-commit hook and run the `precommit` script. Seems to work so far.
