### ISSUE TITLE
scalafmt diff-branch prints number of files read, not modified

### ISSUE THREAD

**Issue by bshirtcliff** [scalameta/scalafmt#889]
- **Version**: 0.6.8
- **Integration**: IntelliJ
- **Configuration**:
```
maxColumn = 100
```

## Steps

I ran scalafmt like this:

```bash
scalafmt -i --config scala_services/.scalafmt.conf --diff-branch upstream/master
```

## Problem

Scalafmt formats code like this:
```scala
  100.0% [##########] 35 source files formatted
```

## Expectation

I would like the formatted output to look like this:
```scala
  100.0% [##########] 35 source files read, 2 formatted
```

## Workaround

I've found that by ignoring the feedback - it's too scary.

## Notes

Thanks - scalafmt is great!

**Comment by olafurpg** [comment]
Thank you for reporting! Scalafmt doesn't know until the end of the run how many files were supported. However, I believe it's possible to support something like



```scala
  100.0% [##########] 35 source files read
Done! 2 file(s) formatted
```
If you are interested in contributing this enhancement, I believe the required change is quite small. We could do something similar to here https://github.com/scalameta/scalafmt/blob/de90239d3dec7998da41f2ac4eba092a6c4d27d7/scalafmt-cli/src/main/scala/org/scalafmt/cli/Cli.scala#L225 when --test is used.

**Comment by olafurpg** [comment]
Thanks for reporting! The cli is working as intended, the progress bar is there to give an estimate for how much work is remaining. For large projects, seeing the total number of files is helpful.
