### ISSUE TITLE
Update default settings to match with sbt style preference

### ISSUE THREAD

**Issue by olafurpg** [scalameta/scalafmt#890]
See https://github.com/sbt/sbt/pull/3125

```scala
# http://docs.scala-lang.org/style/scaladoc.html recommends the JavaDoc style.
# scala/scala is written that way too https://github.com/scala/scala/blob/v2.12.2/src/library/scala/Predef.scala
# Scala.js uses this too
docstrings = JavaDoc
// before
/** Foobar
  * Kasbar
  */
// after
/** Foobar
 *  Kasbar
 */

# This also seems more idiomatic to include whitespace in import x.{ yyy }
spaces.inImportCurlyBraces = true
// before
import a.{b}
// after
import a.{ b }

# This works around sequence wildcard (`_*`) turning into `_ *`
spaces.beforeSeqWildcard = true
// before (this was never intentional, I may remove this option)
  case PathList(ps @ _ *) => MergeStrategy.first
// after
  case PathList(ps @ _*) => MergeStrategy.first
```

I added the "up for debate" label in case someone wants to pitch in their ideas against this, but I'm 👍 for this change and I'm happy to make the switch in the next major release

**Comment by eed3si9n** [comment]
I didn't see this issue before I started writing https://github.com/scalameta/scalafmt/issues/891.

**Comment by sjrd** [comment]
What's the current format and what's the newly purposed default, exactly?

**Comment by olafurpg** [comment]
@sjrd good question, I've updated the description to include examples.

**Comment by sjrd** [comment]
Ah yes, `_*` should definitely stick together. I've never seen a style where it doesn't.

For the others, I don't care much which one is default. FTR Scala.js uses JavaDoc style and no-space inside import braces, but these two things don't have a widely accepted consensus AFAICT.

**Comment by dwijnand** [comment]
Your docstrings example before/after is backwards.

**Comment by eed3si9n** [comment]
One more customization that sbt/sbt#3125 added was:

```
# Vertical alignment only => for pattern matching
align.tokens.add = [
  { code = "=>",  owner = "Case"  }
]
```

### single line case alignments in the wild

This alignment is enabled also for [scalajs style](https://github.com/scalameta/scalafmt/blob/v0.6.8/core/src/main/scala/org/scalafmt/config/Settings.scala#L67) as `AlignToken.caseArrow`.

Here's survey of the same projects from #891.

- scala/scala (mostly no, but there are some hand-coded ones)
- akka/akka (yes. enforced by `AlignSingleLineCaseStatements` https://github.com/akka/akka/blob/v2.5.0/project/Formatting.scala#L29)
- scalatest/scalatest (no)
- typelevel/cats (no)

### observations

case alignment *cannot* be said that it's a de facto standard style. But among the three projects that adopted mechanical formatting (Akka, Scala.js and sbt), case alignment rate is 100%. That could be an evidence that it's too annoying to do it for humans, but it might be a good default.

**Comment by olafurpg** [comment]
Thanks @dwijnand, I updated the example.

@eed3si9n Thank you for researching this so thoroughly. Even if I personally dislike vertical alignment, I'm open to include vertical alignment of case arrows in the default style if that's what's most commonly done in the community. I think the benefit of a generally accepted default style outweighs my personal preferences :) 

Any suggestion on how we can democratically make this decision? One option is to let people share reactions on a comment. For example, I could comment in a neutral way like this


> 😄 I **don't** want vertical alignment for case arrows in the default style
> 🎉 I want vertical alignment for case arrows in the default style

We can keep the vote open for 1-2 weeks and then the majority wins. WDYT?

**Comment by dwijnand** [comment]
GitHub reactions work - I suggest two comments to vote on rather than trying to repurpose `:smile:` and `:tada:`. Another often used alternative is Twitter polls.

**Comment by olafurpg** [comment]
I agree two comments is better. I prefer using Github since many people who have an opinion may not be on Twitter.

**Comment by olafurpg** [comment]
Sounds good, let's do this then! I propose that we keep this poll open for ~2 week and close on Sunday May 14th (any timezone).

**Comment by olafurpg** [comment]
I don't want vertical alignment for case arrows in the default style

**Comment by olafurpg** [comment]
Vote: I want vertical alignment for case arrows in the default style

**Comment by ShaneDelmore** [comment]
My experience backs @eed3si9n thoughts here, I have traditionally preferred no alignment even though I have seen compelling examples where it improved readability for two reasons.  1.  I don't want to have to change other lines when I add a new longer case.  2.  It clutters diffs.  

These days every diff tool I can think of including github can ignore whitespace in diffs and when automated there is no maintenance cost to other devs to update alignment so I am not seeing people complain about it as much when it's automated.

**Comment by eed3si9n** [comment]
To make the options stand out could you put YES and NO like:

> Vote: **NO**, I don't want vertical alignment for case arrows in the default style

> Vote: **YES**, I want vertical alignment for case arrows in the default style

**Comment by xeno-by** [comment]
NO

**Comment by olafurpg** [comment]
@eed3si9n I added the examples to avoid confusion, I thought assigning NO and YES to either option might cause bias.

**Comment by olafurpg** [comment]
@xeno-by Please upvote with 👍 to your prefered option. Commenting "NO" does not count.

**Comment by ShaneDelmore** [comment]
The example confused me enough I voted for the wrong one.  Oops.  Fixed now.

**Comment by olafurpg** [comment]
@ShaneDelmore Good point, I've updated the comments to only include the OK case.

**Comment by pjrt** [comment]
Though I prefer alignment, this isn't something I feel should be in the default. The reason being:

1. I've actually never seen it in the wild for Scala (only on my own stuff). 
2. Given the history we have with alignment in Scalafmt (kind of buggy), we should be hesitant to put it in default.

**Comment by jvican** [comment]
These are my reasons to vote against this proposal:
  
* When adding a new case that is longer than the rest, the diff will report on the whole match case being changed when only a new clause did.
* Column char limit does not affect case alignment, e.g. you can have a case statement being 250 chars long even when the `maxColumn` option is 100.
  
The only reason I see others may have to vote in favor of it is "better readability". However, I don't consider it to be more readable than its counterpart. Long cases force you to scroll (or look) horizontally rather than vertically and that disturbs the natural way of reading text.
  
In any case, I'm happy with the result of the poll.

**Comment by pjrt** [comment]
> In any case, I'm happy with the result of the poll.

I'm actually not happy with the results (currently align is winning by a large margin). I feel people will pick the option that looks better over the one that is easier to implement and maintain. That one, ofc, being the aligned one.

**Comment by ShaneDelmore** [comment]
@jvican This probably won't change your mind but if it helps you you can add  ?w=1 to the end of different in github to hide whitespace.  There are also browser plugins to hide it by default.

**Comment by hseeberger** [comment]
Vote: I want vertical alignment for case arrows in the default style

**Comment by dwijnand** [comment]
I think `case a`/`case aa` doesn't properly demonstrate aligned vs not aligned. Here's an example from the sbt/sbt codebase. Which one of these would _you_ like to see in your codebase and in other codebases using scalafmt's default options?

```scala
option match {
  case JarManifest(mergeManifest)          => mergeManifests(manifest, mergeManifest)
  case MainClass(mainClassName)            => main.put(Attributes.Name.MAIN_CLASS, mainClassName)
  case ManifestAttributes(attributes @ _*) => main.asScala ++= attributes
  case _                                   => log.warn("Ignored unknown package option " + option)
}
```

or

```scala
option match {
  case JarManifest(mergeManifest) => mergeManifests(manifest, mergeManifest)
  case MainClass(mainClassName) => main.put(Attributes.Name.MAIN_CLASS, mainClassName)
  case ManifestAttributes(attributes @ _*) => main.asScala ++= attributes
  case _ => log.warn("Ignored unknown package option " + option)
}
```

**Comment by olafurpg** [comment]
Thank you everyone who participated in the voting! That seems to be a strong victory for vertical alignment in case arrows, for better or worse 😄 Those who dislike vertical alignment will always be able to disable this change in the default style with `align.tokens = []`. 

I have set the deadline for the v1.0 milestone on June 5th https://github.com/scalameta/scalafmt/milestones/12

**Comment by pauldraper** [comment]
I don't really care what the defaults are. (I expect to specify most things.)

But for the the dissenting opinion, I don't like changing one `case` and having 10 `case`s change in my Git history. My history is precious, and I'd prefer changing it as little as reasonable.

**Comment by olafurpg** [comment]
I just merged https://github.com/scalameta/scalafmt/pull/964, which changes the default style to align on case arrows  Along the way, `style=defaultWithAlign` is no longer documented as a provided style. Instead, the `align` settings now supports four alternatives

```
align = none # absolutely nothing
align = some # default, open parens and case arrow
align = more # style=defaultWithAlign
align = most # new experimental setting that enables more than "more" :)
```

Along the way, the docs for the `align` setting and it's nested keys have been greatly expanded.

Thank you everyone who participated in the discussions and voted!
