### ISSUE TITLE
The "ScalaDoc" docstrings

### ISSUE THREAD

**Issue by eed3si9n** [scalameta/scalafmt#891]
Ref sbt/sbt#3125

- **Version**: 0.6.8
- **Integration**: sbt
- **Configuration**:
```
maxColumn = 100
```

Scalafmt defaults to docstrings setting called `ScalaDoc`, which formats like:

```scala
/** Align by second asterisk.
  *
  */
```

and the other style is called `JavaDoc`.
Does the source of this recommendation come from http://docs.scala-lang.org/overviews/scaladoc/for-library-authors.html? The name might be misleading since ScalaDoc will function normally with "JavaDoc" style.

- Style Guide http://docs.scala-lang.org/style/scaladoc.html recommends the "JavaDoc" style.
- Many of the OSS projects use the "JavaDoc" style. Here are some random sampling:
   - https://github.com/scala/scala/blob/v2.12.2/src/library/scala/Predef.scala
   - https://github.com/akka/akka/blob/v2.5.0/akka-actor/src/main/scala/akka/actor/Actor.scala
   - https://github.com/scalatest/scalatest/blob/release-3.0.2/scalatest/src/main/scala/org/scalatest/FlatSpec.scala
   - https://github.com/typelevel/cats/blob/v0.9.0/core/src/main/scala/cats/Monad.scala

It might be better to rename them to more neutral sounding styles (like FirstAsterisk and SecondAsterisk?) and default to what's currently called "JavaDoc".

**Comment by olafurpg** [comment]
Thank you for opening this detailed issue. I agree that JavaDoc/ScalaDoc may be confusing names, I'm in favor of adopting more neutral names and switch the default to the current "javadoc" setting.

The reasoning behind the current names comes from here: http://docs.scala-lang.org/style/scaladoc most notably

> An alternative Scaladoc comment style right-aligns the column of asterisks under the second asterisk, in the third column. The Scaladoc tool also accepts Javadoc comment formatting, with text following the single asterisks, separated by a single space.

It might be worth to update that section since it indeed seems like the "javadoc" comment formatting is more conventional.

**Comment by olafurpg** [comment]
I see that the scala style guide uses a single space indent for the top line and 2 space indent when aligning by the first asterisk

```scala
/** Kasbar
 *  Foobar
 */
```
scala/scala does the same. However, cats/scalatest/akka use single space indent for the non-header lines

```scala
/** Kasbar
 * Foobar
 */
```

Which is the right one? Should scalafmt enforce either one?

**Comment by eed3si9n** [comment]
Good catch. Javadoc burns the first line, and not use it. See [List.java](http://hg.openjdk.java.net/jdk8/jdk8/jdk/file/687fd7c7986d/src/share/classes/java/util/List.java):

```java
/**
 * An ordered collection (also known as a <i>sequence</i>).  The user of this
 * interface has precise control over where in the list each element is
 * inserted.  The user can access elements by their integer index (position in
 * the list), and search for elements in the list.<p>
...
```

Cats, ScalaTest, and Akka are following the style consistently:

```scala
/**
 * Monad.
 * ...
```

```scala
/**
 * Marker trait to signal that this class should not be verified for serializability.
 */
```

```scala
/**
 * Facilitates a &ldquo;behavior-driven&rdquo; style of development (BDD), in which tests
 * ...
```

Count sbt too in the camp:

```scala
  /**
   * The API for the source file `src` at the time represented by this instance.
   * This method returns an empty API if the file had no API or is not known to this instance.
   */
```

So it's actually, and scala/scala is the odd one out here:

```scala
/**
 * Kasbar
 * Foobar
 */
```

> Which is the right one? 

Not sure if it's the matter of correctness, but in terms of JavaDoc tradition, skipping the first line is the right style.

> Should scalafmt enforce either one?

Yes. I think it should.

**Comment by olafurpg** [comment]
I would like to get back to this one before v1, but I'm not sure what to do exactly. Are you proposing that scalafmt should enforce the first sentence to appear on the second line?

```scala

/** Kasbar
 * Foobar
 */

// INTO

/**
 * Kasbar
 * Foobar
 */
```

**Comment by eed3si9n** [comment]
> I would like to get back to this one before v1, but I'm not sure what to do exactly. Are you proposing that scalafmt should enforce the first sentence to appear on the second line?

Yes. Keeping the first line blank seems to be the tradition carried over from Javadoc, adopted by Cats, ScalaTest, Akka, and sbt.

**Comment by olafurpg** [comment]
Related discussion https://contributors.scala-lang.org/t/quiet-changes-to-the-style-guide/923/7

**Comment by magnolia-k** [comment]
The current Scaladoc style guide describes the style of comment as follows and it is not written to suggest any one.

[https://docs.scala-lang.org/style/scaladoc.html](https://docs.scala-lang.org/style/scaladoc.html)

> The Scaladoc tool does not mandate a documentation comment style.

Therefore, it is necessary to discuss which mode should be the default mode, but should support at least three styles stated in the style guide and should also match the mode name?

(Since the name is descriptive and too long, it is necessary to think a little short mode name)
