### ISSUE TITLE
Don't add NL before single-line defs

### ISSUE THREAD

**Issue by dwijnand** [scalameta/scalafmt#892]
This template is a guideline, not a strict requirement.
- **Version**: 0.6.8
- **Integration**: CLI
- **Configuration**:
```
newlines.alwaysBeforeTopLevelStatements=true
```

## Steps

I ran scalafmt like this:

```bash
scalafmt
```

## Problem

Scalafmt formats code like this:
```scala
object Main {
  def x = 1

  def y = 2

  def z = 3

  def foo = {
    println("foo")
  }

  def bar = {
    println("bar")
  }
}
```

## Expectation

I would like the formatted output to look like this:
```scala
object Main {
  def x = 1
  def y = 2
  def z = 3

  def foo = {
    println("foo")
  }

  def bar = {
    println("bar")
  }
}
```

**Comment by Daxten** [comment]
Hey, I can make a PR for this this weekend

**Comment by Daxten** [comment]
I'm thinking about generally only adding newlines if the statement is more then 1 line. Atm it adds newlines before toplevel statements.. I will think about this later and comment back

**Comment by Daxten** [comment]
alwaysBeforeTopLevelStatements
alwaysBeforeMultilineStatements

a new option would make sense I think!

**Comment by olafurpg** [comment]
I believe with #920, this is now fixed. I opened https://github.com/scalameta/scalafmt/issues/922 which is related, but I prefer not to let that one block v1.0
