### ISSUE TITLE
Add NL before multi-line vals

### ISSUE THREAD

**Issue by dwijnand** [scalameta/scalafmt#893]
This template is a guideline, not a strict requirement.
- **Version**: 0.6.8
- **Integration**: CLI
- **Configuration**:
```
newlines.alwaysBeforeTopLevelStatements=true
```

## Steps

I ran scalafmt like this:

```bash
scalafmt
```

## Problem

Scalafmt formats code like this:
```scala
object Main {
  val x = 1
  val y = 2
  val z = 3

  val foo = {
    println("foo")
  }
  val bar = {
    println("bar")
  }
}
```

## Expectation

I would like the formatted output to look like this:
```scala
object Main {
  val x = 1
  val y = 2
  val z = 3

  val foo = {
    println("foo")
  }

  val bar = {
    println("bar")
  }
}
```

## Notes

Related to #892 "Don't add NL before single-line defs"

**Comment by Daxten** [comment]
Hey, I can make a PR for this this weekend

**Comment by olafurpg** [comment]
Please give 0.7.0-RC1 a try and see if the updates to the new option are OK. The main reason I made this release RC1 was to battle test the latest changes to  alwaysBeforeTopLevelStatements  in #904

**Comment by olafurpg** [comment]
I believe with #920, this is now fixed. I opened https://github.com/scalameta/scalafmt/issues/922 which is related, but I prefer not to let that one block v1.0
