### ISSUE TITLE
Port sbt-scalafmt to sbt 1

### ISSUE THREAD

**Issue by olafurpg** [scalameta/scalafmt#894]
Now that sbt 1.0.0-M5 is out (beta) with support for writing plugins with Scala 2.12, it should be a lot simpler to write an sbt-scalafmt plugin. See announcement http://developer.lightbend.com/blog/2017-04-18-sbt-1-0-roadmap-and-beta1/#cross-building-sbt-1-0-plugin-from-sbt-0-13

Here's my WIP branch to create an entirely new sbt plugin "sbt-scalafmt1" using sbt 1: https://github.com/scalameta/scalafmt/compare/master...olafurpg:sbt-1.0?expand=1 the build settings should be good, at least sbt-scalafmt1 compiles fine. The "only" missing part is the plugin implementation.

I won't have much time in the coming 2-3 weeks to work on this,  I'm both busy preparing my talk for flatMap(Oslo) and porting scalafmt to scala-native/Scala.js is frankly higher on my priority list. If someone wants to take a swing at this then please feel free to work from that branch if you want.

**Comment by olafurpg** [comment]
PS. I'm totally open to have a `scalafmtReformatOnCompile` setting in this plugin.

**Comment by eed3si9n** [comment]
> I won't have much time in the coming 2-3 weeks to work on this, I'm both busy preparing my talk for flatMap(Oslo) and porting scalafmt to scala-native/Scala.js is frankly higher on my priority list. If someone wants to take a swing at this then please feel free to work from that branch if you want.

In the mean time can we back publish current 0.6.8 plugin with sbt 1.0.0-M5?

**Comment by olafurpg** [comment]
@eed3si9n 0.6.8 uses the scalafmt-bootstrap module to overcome the 2.10 requirement, which introduces unnecessary complexity. I suspect it's much simpler to implement the same functionality for sbt 1.0, it's probably a matter of copy pasting this file here https://github.com/scalameta/scalafmt/blob/c0fc2943faa5c18af83bcc2ddcc1d2526e74077d/scalafmtSbt/src/main/scala/org/scalafmt/sbt/ScalafmtPlugin.scala#L11 and replacing `ScalafmtBootstrap` with `org.scalafmt.cli.Cli`. I can give it a try this weekend

**Comment by olafurpg** [comment]
I just published 0.7.0-RC1 with support for sbt 1.0.0-M5. Sbt 0.13 is no longer supported, see changelog http://scalameta.org/scalafmt/#0.7.0-RC1
