### ISSUE TITLE
Unexpected indent for single select + match

### ISSUE THREAD

**Issue by olafurpg** [scalameta/scalafmt#895]
```diff
- scalafmt
+ expected
    new ClassloadObject(this.getClass.getClassLoader)
      .createInstanceFor(fqn) match {
-        case Success(e) => Configured.Ok(e)
-        case Failure(e) => Configured.NotOk(ConfError.msg(e.getMessage))
-      }
+          case Success(e) => Configured.Ok(e)
+          case Failure(e) => Configured.NotOk(ConfError.msg(e.getMessage))
+        }
```

**Comment by jiminhsieh** [comment]
@olafurpg After I formatted your example with 1.4.0, here is the result. 
```scala
  new ClassloadObject(this.getClass.getClassLoader)
    .createInstanceFor(fqn) match {
    case Success(e) => Configured.Ok(e)
    case Failure(e) => Configured.NotOk(ConfError.msg(e.getMessage))
  }
```
It seemed pretty well and not like the result you posted. Could you clarify this issue? Thanks! :)

**Comment by olafurpg** [comment]
@jiminhsieh I updated the description to clarify obtained/expected output.

The problem here is that the match is not include in the "select chain" for a single select. If someone wants to take a stab at this, here are relevant links

* where indent is set for select chains https://github.com/scalameta/scalafmt/blob/b098eb994ec8cde832f459d388255a91641037f7/scalafmt-core/shared/src/main/scala/org/scalafmt/internal/Router.scala#L955 `optimalToken` is the "expire token" where the indent stops.

* Here is where the optimal token is computed https://github.com/scalameta/scalafmt/blob/b098eb994ec8cde832f459d388255a91641037f7/scalafmt-core/shared/src/main/scala/org/scalafmt/internal/FormatOps.scala#L468

**Comment by olafurpg** [comment]
@jiminhsieh You are correct, the output is working as expected from v1.4. Thanks!
