### ISSUE TITLE
Get appveyor green again

### ISSUE THREAD

**Issue by olafurpg** [scalameta/scalafmt#897]
Appveyor has been red for a while https://ci.appveyor.com/project/olafurpg/scalafmt/history This doesn't affect windows users, but it does affect contributors on Windows. If someone with a windows machine could take a look at this then I would very grateful. I don't have a Windows machine to reproduce on a local environment, which makes it very slow for me to troubleshoot the problem.

cc/ @mmatloka @mpociecha

**Comment by olafurpg** [comment]
The latest error: https://ci.appveyor.com/project/olafurpg/scalafmt/build/68#L1289

```
warn] one warning found
coursier.ResolutionException: Encountered 1 error(s) in dependency resolution:
  com.geirsson:scalafmt-cli_2.12:0.6.8+12-dcfaf6fe:
    not found:
      https://repo.typesafe.com/typesafe/ivy-releases/com.geirsson/scalafmt-cli_2.12/0.6.8+12-dcfaf6fe/ivys/ivy.xml
      https://repo.scala-sbt.org/scalasbt/sbt-plugin-releases/com.geirsson/scalafmt-cli_2.12/0.6.8+12-dcfaf6fe/ivys/ivy.xml
      C:\Users\appveyor\.ivy2\local\com.geirsson\scalafmt-cli_2.12\0.6.8+12-dcfaf6fe\ivys\ivy.xml
      https://repo1.maven.org/maven2/com/geirsson/scalafmt-cli_2.12/0.6.8+12-dcfaf6fe/scalafmt-cli_2.12-0.6.8+12-dcfaf6fe.pom
[error] (scalafmtSbt/*:coursierResolution) coursier.ResolutionException: Encountered 1 error(s) in dependency resolution:
[error]   com.geirsson:scalafmt-cli_2.12:0.6.8+12-dcfaf6fe:
[error]     not found:
[error]       https://repo.typesafe.com/typesafe/ivy-releases/com.geirsson/scalafmt-cli_2.12/0.6.8+12-dcfaf6fe/ivys/ivy.xml
[error]       https://repo.scala-sbt.org/scalasbt/sbt-plugin-releases/com.geirsson/scalafmt-cli_2.12/0.6.8+12-dcfaf6fe/ivys/ivy.xml
[error]       C:\Users\appveyor\.ivy2\local\com.geirsson\scalafmt-cli_2.12\0.6.8+12-dcfaf6fe\ivys\ivy.xml
[error]       https://repo1.maven.org/maven2/com/geirsson/scalafmt-cli_2.12/0.6.8+12-dcfaf6fe/scalafmt-cli_2.12-0.6.8+12-dcfaf6fe.pom
```

I'm sure it's a small error in build.sbt

**Comment by mmatloka** [comment]
I have run build locally on current master, it actually finds all the dependencies etc, just fails afterward on some tests.

```[info] *** 19 TESTS FAILED ***
[error] Failed tests:
[error] 	org.scalafmt.FidelityTest
[error] 	org.scalafmt.FormatTests
```

```[error] Failed tests:
[error] 	org.scalafmt.benchmarks.BenchmarkOK
```

**Comment by olafurpg** [comment]
Thanks @mmatloka  The dependency issue was caused by a configuration bug in appveyor.yml The regression seems to have been introduced in https://ci.appveyor.com/project/olafurpg/scalafmt/build/56 which was my fault, I will try to see what's happening.

**Comment by olafurpg** [comment]
I managed to get a green build on appveyor https://ci.appveyor.com/project/olafurpg/scalafmt/build/79 from a commit in #898.  I opened #902 to see if I can get it green before merging #898

**Comment by olafurpg** [comment]
@mmatloka The test pass on appveyor now, can you check if the latest master passes on your machine? https://github.com/scalameta/scalafmt/pull/902
