### ISSUE TITLE
PR # 904 started adding new lines after comments

### ISSUE THREAD

**Issue by diego-alvarez-hs** [scalameta/scalafmt#911]
- **Version**: 0.7.0-RC1
- **Integration**: sbt
- **Configuration**:
```
maxColumn = 100
newlines.alwaysBeforeTopLevelStatements = true
```
After updated to version `0.7.0-RC1` it started to add new lines after comments
https://github.com/scalameta/scalafmt/pull/904

## Steps

I ran scalafmt like this:

```bash
scalafmt
```

## Problem

Scalafmt formats code like this:
```scala
/** Implements the ..... /status/about, etc */

class Status @Inject()(ws: WSClient) extends Controller with Foo {

// scalastyle:off magic.number

trait TestConfigs extends PatienceConfiguration {
```

## Expectation

I would like the formatted output to look like this:
```scala
/** Implements the ..... /status/about, etc */
class Status @Inject()(ws: WSClient) extends Controller with Foo {

// scalastyle:off magic.number
trait TestConfigs extends PatienceConfiguration {

```

## Workaround

I've found that by returning to version 0.6.8 fixes the problem

**Comment by olafurpg** [comment]
Thank you for reporting! This is my fault from #904, I will fix this before 0.7 final.
