### ISSUE TITLE
Too eager at breaking down curly brace lambdas

### ISSUE THREAD

**Issue by dwijnand** [scalameta/scalafmt#913]
This template is a guideline, not a strict requirement.
- **Version**: 0.6.8
- **Integration**: CLI
- **Configuration**:
```
maxColumn = 100
```

## Steps

I ran scalafmt like this:

```bash
scalafmt
```

## Problem

Scalafmt formats code like this:
```scala
class Discovery(baseClasses: Set[String], annotations: Set[String]) {
  def apply(s: Seq[Definition]): Seq[(Definition, Discovered)] =
    s.map { d =>
      (d, apply(d))
    }
}

class LoggerReporter(
    sourcePositionMapper: Position => Position = { p =>
      p
    }
)
```

## Expectation

I would like the formatted output to look like this:
```scala
class Discovery(baseClasses: Set[String], annotations: Set[String]) {
   def apply(s: Seq[Definition]): Seq[(Definition, Discovered)] =
     s.map { d => (d, apply(d)) }
}

class LoggerReporter(
  sourcePositionMapper: Position => Position = { p => p }
)
```

**Comment by dwijnand** [comment]
Any insights as to why this is happening and/or how to fix it?

**Comment by olafurpg** [comment]
The handling of line breaks after `{` is shared for block and lambdas https://github.com/scalameta/scalafmt/blob/3df7c037dd7936ed87de8279dac4b7fc5bc0336f/scalafmt-core/shared/src/main/scala/org/scalafmt/internal/Router.scala#L178-L236 I've took a stab at this once and struggles to make it work without breaking a lot of tests. It's probably best to handle lambdas separately in another case.

When I started scalafmt I felt like this output here
```scala
foo { 
  loooooooooooooooong =>
    ...
}
```
made sense but in hindsight I think I would probably prefer this today
```scala
foo { loooooooooooooooong =>
    ...
}
```
even if `loooooong` breaks the column limit. This change would also simplify the implementation, since then there are only two alternative layouts instead of three.

**Comment by olafurpg** [comment]
This issue bugs me too almost daily, so I would love if someone took a swing at fixing it. I haven't been able to dedicate much time to scalafmt past months except to review the occasional PR and cut new releases (which takes a while because of IntelliJ plugin).

**Comment by sjrd** [comment]
What I often have in my code is not
```scala
foo {
  loooooooooooooooong =>
    ...
}
```
but rather
```scala
foo.babar.bar(someArgs).map {
  nonSingleCharName =>
    ...
}
```
And I wouldn't like that to turn into
```scala
foo.babar.bar(someArgs).map { nonSingleCharName =>
  ...
}
```
resulting in breaking the column limit.

**Comment by olafurpg** [comment]
@sjrd scalafmt might be likely to force this on you instead for better or worse
```scala
  foo.babar
    .bar(someArgs)
    .map { nonSingleCharName =>
      // ...
    }
```

**Comment by dwijnand** [comment]
IMO the default behaviour should be to leave it wrapped if it was already wrapped, or wrap it if it exceeds the column limit. Definitely not wrap always.

Perhaps the issue template led me to state that I wanted it to unwrap, which wasn't what I meant. I want it not to wrap unless it's hitting the column limit.

**Comment by olafurpg** [comment]
Superseded by #917 via https://github.com/scalacenter/scala-syntax Core changes to the formatting output will be far easier to accommodate with a tree printer.

**Comment by dwijnand** [comment]
What's the state of this ticket, now?

Should I report it to scalacenter/scala-syntax?

Looks like myself and 5 :+1: voters are interested in this ticket about code formatting.

**Comment by olafurpg** [comment]
The status I'd say is "good idea, no one willing to work on it ". I'm happy to collaborate with someone who wants to contribute this improvement but keeping it open without activity is not the best strategy to make that happen.

**Comment by dwijnand** [comment]
I'm not sure if closing it is the _better_ strategy to seek an improvement contribution, however.

If that's the status, should this be labeled "registered" then?

(I'm partially asking because I'm just interested from a general "what are the different social protocols around issue trackers" POV)

**Comment by olafurpg** [comment]
I forgot to label revisit, done.

> I'm not sure if closing it is the better strategy to seek an improvement contribution, however.
> (I'm partially asking because I'm just interested from a general "what are the different social protocols around issue trackers" POV)

IMO it kind of boils down to recruiting people to work on non-trivial issues, which is a hard problem. GitHub issues are a decent job board and many people looking to contribute do browse through the open tickets (including this one). When a ticket is left untouched for over a year the chances someone will pick that up grow slim. Having 170 stale issues for nice-to-have improvements is not an effective way to attract contributors, and it's not helpful for me either as a project maintainer.

**Comment by dwijnand** [comment]
> I forgot to label revisit, done.

:+1:

> Having 170 stale issues for nice-to-have improvements is not an effective way to attract contributors, and it's not helpful for me either as a project maintainer.

Everyone's got different ideas and "protocols". The closing and labeling one I've seen used here, in the dotty repo and the ensime repo.

Btw, it would appear that GitHub is promoting instead selectively labeling issues to guide in new contributors:

https://help.github.com/articles/helping-new-contributors-find-your-project-with-labels/

**Comment by olafurpg** [comment]
I use "Good first contribution" (or similar) for low hanging fruits and it's been successful (esp at sprees). I recently fixed the remaining such tickets that had been open for many months. I estimate this ticket otoh is not so low hanging so it's not a good candidate for such a label.

**Comment by dwijnand** [comment]
My thinking has been "good first issue" (your "good first contribution") for hackathon-sized tickets (1-2 hours) and "help wanted" for anything larger (i.e could be a few evenings, could be a few evenings and weekends).

**Comment by dwijnand** [comment]
Interesting question. I'd probably attend and push for more hackathons. Maybe even see if I can drum up some sponsorship like ENSIME.

**Comment by dwijnand** [comment]
Consider applying C4...

**Comment by olafurpg** [comment]
That's a good suggestion 👍

**Comment by ysde** [comment]
Hi guys

Is this issue fixed?

Thank you

**Comment by ysde** [comment]
Hi guys

Is this issue fixed?

Thank you
