### ISSUE TITLE
New line wrapping backend with paiges

### ISSUE THREAD

**Issue by olafurpg** [scalameta/scalafmt#917]
Background: http://www.scala-lang.org/gsoc/2017.html#new-line-wrapping-algorithm-for-scalafmt
There now exists a Scala implementation of the "Prettier printer" line wrapping algorithm: https://github.com/typelevel/paiges This same algorithms is for example used in https://github.com/prettier/prettier 

I'm opening this issue to track progress on using paiges as an alternative line wrapping backend to [BestFirstFirst](https://github.com/scalameta/scalafmt/blob/908ca6178d7e14c7f12bf29ffe54cb7004c958f4/scalafmt-core/shared/src/main/scala/org/scalafmt/internal/BestFirstSearch.scala) and [Router](https://github.com/scalameta/scalafmt/blob/908ca6178d7e14c7f12bf29ffe54cb7004c958f4/scalafmt-core/shared/src/main/scala/org/scalafmt/internal/Router.scala).

I took a quick stab at this a few weeks ago and got amazing results for deeply nested function calls. Example https://gist.github.com/olafurpg/44ee2d0a8c5b8330702cf00d23d0978a What's impressive with paiges is that 
- it took me 10 minutes to get that example output (compared to 2-3 months with BestFirstSearch and it's still unable to handle code with that amount of nesting).
- it's fast! That example gist formats in ~300ms

Here are some (totally solvable) challenges that come with this new approach

### Q: how do we handle comments?
A paiges-based formatter would do a top-down tree traversal. Some comments are not directly associated with a tree, for example

```scala
foo(
  a, // comment
  b
)

def foo() = { // comment 
  // ...
}
```
My guess: we use a similar trick as in https://github.com/scalameta/scalameta/blob/fac0de590bf0633567a12ce38de2cf40c5b1b547/scalameta/contrib/shared/src/test/scala/scala/meta/contrib/AssociatedCommentsTest.scala (this seems similar to what's explained [here](http://jlongster.com/prettier-1.0#Comments))

### Q: What do we do with vertical alignment?

Paiges has an `align` combinator but iiuc it won't handle things like

```scala
case a  => b
case aa => b
```
My guess: we move vertical alignment into a separate module and run it as a standalone `String => String` transformation on the rendered output of the paiges line wrapper. Vertical alignment is currently implemented in a somewhat similar way but avoid a second parse step by working on data structures produced by BestFirstSearch. I don't see a way to avoid the second parse if we use paiges, but 1) parsing is pretty cheap compared to the line wrapping and 2) the performance boost gained from paiges compared to BestFirstSearch will probably offset additional overhead.

### What configuration options do we want to support in this new backend?

The best explanation of how I feel about options for formatters is here: http://jlongster.com/prettier-1.0#Options In particular, I think we should be more active in weeding out options that cause people to say "I will never use scalafmt without this option". Towards that end, I'd like to  introduce some more formal process on how decisions are made regarding the introduction of new options. Any ideas on how this process should be are welcome, a voting system like in https://github.com/scalameta/scalafmt/issues/890#issuecomment-298186375 could be one option.

PS. Regarding v1.0 (see #730), my idea has been to release v1.0 soon with the current scalafmt implementation. If this paiges approach turns out to be useful, then I would like to call it v2.0.

**Comment by NicolasRouquette** [comment]
Here are 5 proposals for the flexibility to force line breaks before/after certain tokens where possible by the syntax. I briefly explored the feasibility of doing this with the current `Router` and saw the helpful comment to this issue.

## 1) Break before `(` in a parameter list for a class or function definition but not an expression

This would yield the following: 

```scala
case class Example
(x: String)

def foo[A <: Foo, B[X] <: Iterable[X]]
(x: B[A#SomeDependentType])
(implicit y: B[A#SomethingElse])
```

 Instead of, e.g.,:

```scala
case class Example(
                   x: String)

def foo[A <: Foo, B[X] <: Iterable[X]](
                                       x: B[A#SomeDependentType])(implicit y: B[A#SomethingElse])
```
  
This helps avoid indenting the parameter definitions when the formatting of the class or function name & template parameters would otherwise push the parameter list far to the right; e.g.:

```scala
case class SomeDescriptiveStuff[A <: Foo, B[X] <: Iterable[X]](
                                                               override val x: B[A#SomeDependentType])
    extends ...
```
 
## 2) Break before and after an annotation

Instead of:

```scala
@foo(where="here") @bar(x="0.0", y="1.2") case class Baz()
```

This would yield:

```scala
@foo(...)
@bar(...) 
case class Baz()
```

In conjunction with breaking before parameter lists, this would be particularly helpful for annotated parameters, e.g.:

```scala
@foo(...)
@bar(...) 
case class Baz[A <: Foo, B[X] <: Iterable[X]]
(
 @foo(...)
 x: B[A#SomeDependentType])
(implicit 
 @bar(...)
 y: B[A#SomethingElse]))
```

## 3) Break before ':' (type of a definition) and before '=' (definition body)
 
This helps retain a lot of space for formatting the definition type and body on separate lines
with minimal prefix on the left.

```scala
def lookupStuff(x: X)
: Option[Stuff]
= lookupHere(x) orElse lookupThere(x)
```

## 4) Break before '.' in expressions

Instead of, e.g.,:

```scala
foo(
  expression1.
     veryLongExpression2.
     veryLongExpression3,
  veryLongExpression3.
     expression4)
```

This would yield the following:

```scala
foo(
  expression1
    .veryLongExpression2
    .veryLongExpression3,
  veryLongExpression3
    .expression4)
```

At the beginning of the line, the '.' gives a useful visual clue that the expression on the right applies to the expression above that line.

## 5) Break before ',' in a tuple

For example:

```scala
(somethingLong
,somethingElse
,blah)
```

At the beginning of the line, the ',' gives a useful visual clue that the expression on the right is a distinct argument value than the one above that line.

**Comment by olafurpg** [comment]
@NicolasRouquette Can you please post your ideas in a separate issue? This ticket is to keep track of progress on reimplementing the line wrapping algorithm, not to discuss new/alternative formatting layouts.

**Comment by NicolasRouquette** [comment]
Thanks @olafurpg for moving my comments to a new issue.

**Comment by olafurpg** [comment]
For anyone interested, my WIP towards this issue lives in a separate repo https://github.com/olafurpg/scala-syntax I am very optimistic about this approach, but there are several challenges

- comments, they need more sophisticated handling because this approach prints from ASTs instead of tokens
- vertical alignment, I haven't looked into it but my feeling is that it's possible to provide it but it may be slightly different from the current implementation. It will likely be better in some cases and worse in other.

**Comment by olafurpg** [comment]
Superseded by a new repo https://github.com/scalacenter/scala-syntax This is a large project that is too big to track in a single ticket. Once scala-syntax is more mature I'd like to investigate how to integrate it with scalafmt
