### ISSUE TITLE
Insert blank line for single-line def following multiline statement

### ISSUE THREAD

**Issue by olafurpg** [scalameta/scalafmt#922]
```scala
// newlines.alwaysBeforeTopLevelStatements=true

// original
def foo = {
  println("foo")
}
def bar = 2

// scalafmt
def foo = {
  println("foo")
}
def bar = 2

// expected
def foo = {
  println("foo")
}

def bar = 2
```
Observe blank line before `def bar`.

Workaround: manually insert blank line before `def bar`

**Comment by dwijnand** [comment]
The title doesn't match the description.

**Comment by olafurpg** [comment]
Thanks @dwijnand, updated :)

**Comment by olafurpg** [comment]
Working as intended, users can manually insert a blank line to obtain the expected output.

**Comment by dwijnand** [comment]
`newlines.alwaysBeforeTopLevelStatements`, for some definition of "always" 😉

**Comment by olafurpg** [comment]
Aah, whoops 😅 I welcome a PR if someone wants to take a stab at this, the setting was contributed by a user and is seemingly no longer maintained ¯\_(ツ)_/¯
