### ISSUE TITLE
please publish for sbt 0.13

### ISSUE THREAD

**Issue by fommil** [scalameta/scalafmt#923]
I have many projects that cannot upgrade to sbt 1.0 at this time.

Also, sbt 1.0 (final) isn't even released yet.

**Comment by fommil** [comment]
(I'm aware of http://scalameta.org/scalafmt/#sbt0.13 although surely a better workaround of that nature would be to copy the entire plugin source)

**Comment by fommil** [comment]
btw, even using the workaround I get this every time I type `scalafmt` so it looks like coursier is behaving weirdly

```
[error] Downloading https://dl.bintray.com/scalameta/maven/com/geirsson/scalafmt-cli_2.11/0.7.0-RC1/scalafmt-cli_2.11-0.7.0-RC1.pom
[error] Downloading https://dl.bintray.com/scalameta/maven/com/geirsson/scalafmt-cli_2.11/0.7.0-RC1/scalafmt-cli_2.11-0.7.0-RC1.pom.sha1
[error] Downloading https://dl.bintray.com/scalameta/maven/org/scalameta/scalameta_2.11/1.7.0/scalameta_2.11-1.7.0.pom.sha1
[error] Downloading https://dl.bintray.com/scalameta/maven/com/geirsson/scalafmt-core_2.11/0.7.0-RC1/scalafmt-core_2.11-0.7.0-RC1.pom
[error] Downloading https://dl.bintray.com/scalameta/maven/com/martiansoftware/nailgun-server/0.9.1/nailgun-server-0.9.1.pom
[error] Downloading https://dl.bintray.com/scalameta/maven/com/github/scopt/scopt_2.11/3.5.0/scopt_2.11-3.5.0.pom.sha1
[error] Downloading https://dl.bintray.com/scalameta/maven/org/scalameta/scalameta_2.11/1.7.0/scalameta_2.11-1.7.0.pom
[error] Downloading https://dl.bintray.com/scalameta/maven/com/martiansoftware/nailgun-server/0.9.1/nailgun-server-0.9.1.pom.sha1
[error] Downloading https://dl.bintray.com/scalameta/maven/com/geirsson/scalafmt-core_2.11/0.7.0-RC1/scalafmt-core_2.11-0.7.0-RC1.pom.sha1
[error] Downloading https://dl.bintray.com/scalameta/maven/com/github/scopt/scopt_2.11/3.5.0/scopt_2.11-3.5.0.pom
[error] Downloading https://dl.bintray.com/scalameta/maven/org/scala-lang/scala-library/2.11.11/scala-library-2.11.11.pom.sha1
[error] Downloading https://dl.bintray.com/scalameta/maven/org/scala-lang/scala-library/2.11.11/scala-library-2.11.11.pom
[error] Downloading https://dl.bintray.com/scalameta/maven/com/martiansoftware/nailgun-all/0.9.1/nailgun-all-0.9.1.pom
[error] Downloading https://dl.bintray.com/scalameta/maven/com/martiansoftware/nailgun-all/0.9.1/nailgun-all-0.9.1.pom.sha1
[error] Downloading https://dl.bintray.com/scalameta/maven/org/sonatype/oss/oss-parent/7/oss-parent-7.pom
[error] Downloading https://dl.bintray.com/scalameta/maven/org/sonatype/oss/oss-parent/7/oss-parent-7.pom.sha1
[error] Downloading https://dl.bintray.com/scalameta/maven/com/geirsson/metaconfig-typesafe-config_2.11/0.3.2/metaconfig-typesafe-config_2.11-0.3.2.pom.sha1
[error] Downloading https://dl.bintray.com/scalameta/maven/com/geirsson/metaconfig-typesafe-config_2.11/0.3.2/metaconfig-typesafe-config_2.11-0.3.2.pom
[error] Downloading https://dl.bintray.com/scalameta/maven/org/scalameta/common_2.11/1.7.0/common_2.11-1.7.0.pom
[error] Downloading https://dl.bintray.com/scalameta/maven/org/scalameta/common_2.11/1.7.0/common_2.11-1.7.0.pom.sha1
[error] Downloading https://dl.bintray.com/scalameta/maven/org/scalameta/semantic_2.11/1.7.0/semantic_2.11-1.7.0.pom.sha1
[error] Downloading https://dl.bintray.com/scalameta/maven/org/scalameta/semantic_2.11/1.7.0/semantic_2.11-1.7.0.pom
[error] Downloading https://dl.bintray.com/scalameta/maven/org/scalameta/transversers_2.11/1.7.0/transversers_2.11-1.7.0.pom.sha1
[error] Downloading https://dl.bintray.com/scalameta/maven/com/geirsson/metaconfig-core_2.11/0.3.2/metaconfig-core_2.11-0.3.2.pom
[error] Downloading https://dl.bintray.com/scalameta/maven/org/scalameta/transversers_2.11/1.7.0/transversers_2.11-1.7.0.pom
[error] Downloading https://dl.bintray.com/scalameta/maven/com/geirsson/metaconfig-core_2.11/0.3.2/metaconfig-core_2.11-0.3.2.pom.sha1
[error] Downloading https://dl.bintray.com/scalameta/maven/org/scalameta/inline_2.11/1.7.0/inline_2.11-1.7.0.pom
[error] Downloading https://dl.bintray.com/scalameta/maven/org/scalameta/parsers_2.11/1.7.0/parsers_2.11-1.7.0.pom
[error] Downloading https://dl.bintray.com/scalameta/maven/org/scalameta/inline_2.11/1.7.0/inline_2.11-1.7.0.pom.sha1
[error] Downloading https://dl.bintray.com/scalameta/maven/org/scalameta/parsers_2.11/1.7.0/parsers_2.11-1.7.0.pom.sha1
[error] Downloading https://dl.bintray.com/scalameta/maven/org/scalameta/quasiquotes_2.11/1.7.0/quasiquotes_2.11-1.7.0.pom
[error] Downloading https://dl.bintray.com/scalameta/maven/org/scalameta/quasiquotes_2.11/1.7.0/quasiquotes_2.11-1.7.0.pom.sha1
[error] Downloading https://dl.bintray.com/scalameta/maven/org/scalameta/dialects_2.11/1.7.0/dialects_2.11-1.7.0.pom
[error] Downloading https://dl.bintray.com/scalameta/maven/org/scalameta/tokenizers_2.11/1.7.0/tokenizers_2.11-1.7.0.pom
[error] Downloading https://dl.bintray.com/scalameta/maven/org/scalameta/tokenizers_2.11/1.7.0/tokenizers_2.11-1.7.0.pom.sha1
[error] Downloading https://dl.bintray.com/scalameta/maven/org/scalameta/dialects_2.11/1.7.0/dialects_2.11-1.7.0.pom.sha1
[error] Downloading https://dl.bintray.com/scalameta/maven/org/scalameta/trees_2.11/1.7.0/trees_2.11-1.7.0.pom
[error] Downloading https://dl.bintray.com/scalameta/maven/org/scalameta/trees_2.11/1.7.0/trees_2.11-1.7.0.pom.sha1
[error] Downloading https://dl.bintray.com/scalameta/maven/com/trueaccord/scalapb/scalapb-runtime_2.11/0.6.0-pre2/scalapb-runtime_2.11-0.6.0-pre2.pom
[error] Downloading https://dl.bintray.com/scalameta/maven/com/typesafe/config/1.2.1/config-1.2.1.pom
[error] Downloading https://dl.bintray.com/scalameta/maven/com/typesafe/config/1.2.1/config-1.2.1.pom.sha1
[error] Downloading https://dl.bintray.com/scalameta/maven/com/lihaoyi/sourcecode_2.11/0.1.3/sourcecode_2.11-0.1.3.pom
[error] Downloading https://dl.bintray.com/scalameta/maven/com/trueaccord/scalapb/scalapb-runtime_2.11/0.6.0-pre2/scalapb-runtime_2.11-0.6.0-pre2.pom.sha1
[error] Downloading https://dl.bintray.com/scalameta/maven/com/lihaoyi/sourcecode_2.11/0.1.3/sourcecode_2.11-0.1.3.pom.sha1
[error] Downloading https://dl.bintray.com/scalameta/maven/org/scalameta/tokens_2.11/1.7.0/tokens_2.11-1.7.0.pom
[error] Downloading https://dl.bintray.com/scalameta/maven/org/scalameta/inputs_2.11/1.7.0/inputs_2.11-1.7.0.pom
[error] Downloading https://dl.bintray.com/scalameta/maven/com/lihaoyi/scalaparse_2.11/0.4.2/scalaparse_2.11-0.4.2.pom
[error] Downloading https://dl.bintray.com/scalameta/maven/org/scalameta/tokens_2.11/1.7.0/tokens_2.11-1.7.0.pom.sha1
[error] Downloading https://dl.bintray.com/scalameta/maven/com/lihaoyi/scalaparse_2.11/0.4.2/scalaparse_2.11-0.4.2.pom.sha1
[error] Downloading https://dl.bintray.com/scalameta/maven/org/scalameta/inputs_2.11/1.7.0/inputs_2.11-1.7.0.pom.sha1
[error] Downloading https://dl.bintray.com/scalameta/maven/com/lihaoyi/fastparse_2.11/0.4.2/fastparse_2.11-0.4.2.pom.sha1
[error] Downloading https://dl.bintray.com/scalameta/maven/com/google/protobuf/protobuf-java/3.2.0/protobuf-java-3.2.0.pom
[error] Downloading https://dl.bintray.com/scalameta/maven/com/lihaoyi/fastparse_2.11/0.4.2/fastparse_2.11-0.4.2.pom
[error] Downloading https://dl.bintray.com/scalameta/maven/com/google/protobuf/protobuf-java/3.2.0/protobuf-java-3.2.0.pom.sha1
[error] Downloading https://dl.bintray.com/scalameta/maven/org/scalameta/io_2.11/1.7.0/io_2.11-1.7.0.pom.sha1
[error] Downloading https://dl.bintray.com/scalameta/maven/org/scalameta/io_2.11/1.7.0/io_2.11-1.7.0.pom
[error] Downloading https://dl.bintray.com/scalameta/maven/com/trueaccord/lenses/lenses_2.11/0.4.10/lenses_2.11-0.4.10.pom.sha1
[error] Downloading https://dl.bintray.com/scalameta/maven/com/trueaccord/lenses/lenses_2.11/0.4.10/lenses_2.11-0.4.10.pom
[error] Downloading https://dl.bintray.com/scalameta/maven/com/google/protobuf/protobuf-parent/3.2.0/protobuf-parent-3.2.0.pom.sha1
[error] Downloading https://dl.bintray.com/scalameta/maven/com/google/protobuf/protobuf-parent/3.2.0/protobuf-parent-3.2.0.pom
[error] Downloading https://dl.bintray.com/scalameta/maven/com/google/google/1/google-1.pom
[error] Downloading https://dl.bintray.com/scalameta/maven/com/google/google/1/google-1.pom.sha1
[error] Downloading https://dl.bintray.com/scalameta/maven/com/lihaoyi/fastparse-utils_2.11/0.4.2/fastparse-utils_2.11-0.4.2.pom
[error] Downloading https://dl.bintray.com/scalameta/maven/com/lihaoyi/fastparse-utils_2.11/0.4.2/fastparse-utils_2.11-0.4.2.pom.sha1
```

**Comment by xeno-by** [comment]
If we rewrite current macros in meta against `scala.tools.nsc.Global` (instead of the normal `scala.reflect.macros.Universe`), then I believe the migration to 2.10 (https://github.com/scalameta/scalameta/issues/295) should be easy. 

@fommil Would you have time to look into that? I wanted to do this myself, but I'm absolutely swamped until ScalaDays Copenhagen unfortunately.

**Comment by fommil** [comment]
@xeno-by we just the sbt plugin, no need to port `scala.meta` to 2.10. I have absolutely zero time until I finish my book, sorry.

**Comment by pauldraper** [comment]
Ha ha, great time

I just *barely* published [neo-sbt-scalafmt](https://github.com/lucidsoftware/neo-sbt-scalafmt).

Highlights:

* in-process
* uses normal ivy resolution
* supports scalafmt 0.6 and 0.7
* supports SBT 0.13 and 1.0

I also worked to remove as much overhead as possible, so it could frequently run (e.g. pre-compile) for very large projects.

**Comment by olafurpg** [comment]
Awesome @pauldraper! Thank you for putting that together. I added a comment https://github.com/lucidsoftware/neo-sbt-scalafmt/commit/f760c4a25df59c07b8b52ace95f19ff0096d43f6#commitcomment-22056885 sharing some problems I hit using a similar config approach. You might get some upset customers ^^ (https://github.com/scalameta/scalafmt/issues/596)

I am happy to merge an sbt plugin for 0.13 into the main repo if someone is motivated to take ownership of the plugin and help respond to reported issues on the sbt plugin. You would become a project collaborator with merge rights and listed in the readme as a maintainer https://github.com/scalameta/scalafmt#team

@fommil I admit it's a bit harsh to drop sbt 0.13 support, I explain in https://github.com/scalameta/scalafmt/pull/896#issuecomment-296373008 a bit more the motivation behind it. The maintenance burden was too high considering that I personally don't use the plugin and the free time I have to work on scalafmt these days is very limited. I want to focus that work on getting a stable 1.0 out #730 and then maybe work on the future #917.  

I'll keep this issue open in case someone wants to contribute a plugin for sbt 0.13, I suspect a lot of users would appreciate that contribution since it will probably be a while until everyone switch to sbt 1.0.

**Comment by pauldraper** [comment]
@olafurpg Hah, I did encounter that :D https://gitter.im/sbt/sbt?at=59100a1d9d90dc7a1c57ff3e

I figured out that

```scala
ivyScala := ivyScala.value.map(_.copy(overrideScalaVersion = false))
```

was the fix. Looking through that SBT issue, I see the same suggestion. It's possible someone is relying this default (nuisance) behavior, but I bet not.

I'm happy to take over SBT support. The only question is whether you prefer versioning everything (SBT, Intellij, Maven, the eventual VS Code plugin) together in this repository.

**Comment by olafurpg** [comment]
> ivyScala := ivyScala.value.map(_.copy(overrideScalaVersion = false))

@pauldraper Amazing! If that all it took, then that's great news. I don't know how many projects would have issues with this workaround, maybe @dwijnand can give us some insights.

Thank you for helping out :) I think a good start would be to point the sbt installation docs to neo-sbt-scalafmt and get some feedback. Then we can decide later if we want to merge the repos or keep them separate, I am open for either way. WDYT?

I noticed that neo-sbt-scalafmt requires `enablePlugins(ScalafmtPlugin)`. Any particular reason you opted for that route instead of using `override def trigger: PluginTrigger = allRequirements` to enable it automatically for all projects?

**Comment by olafurpg** [comment]
@pauldraper you have a pending collaborator invitation and I opened https://github.com/scalameta/scalafmt/pull/926 to list neo-sbt-scalafmt in the docs 🎉

**Comment by dwijnand** [comment]
https://github.com/sbt/sbt/pull/2634 and https://github.com/sbt/sbt/issues/2286 are the motivation for the feature that `overrideScalaVersion = false` opts out of.

**Comment by pauldraper** [comment]
@dwijnand thanks for the context.

**Comment by pauldraper** [comment]
@olafurpg 

> I noticed that neo-sbt-scalafmt requires enablePlugins(ScalafmtPlugin). Any particular reason you opted for that route instead of using override def trigger: PluginTrigger = allRequirements to enable it automatically for all projects?

No reason in particular. I notice that sbt-scalariform does allRequirements too. I'll probably add that.

**Comment by olafurpg** [comment]
@pauldraper I think most users would want the plugin to automatically be enabled. I believe it's still possible to opt-out of that with `disablePlugins(ScalafmtPlugin)`. 

http://scalameta.org/scalafmt/#neo-sbt-scalafmt is now documented on the website! 🎉 

@fommil Please give neo-sbt-scalafmt a try. I'm afraid there won't be an sbt 0.13 release for com.geirsson/sbt-scalafmt unless someone volunteers to send a PR adding it back. As I mention in https://github.com/scalameta/scalafmt/issues/923#issuecomment-299924498, my time to work on scalafmt is already quite limited and I prefer to invest that time on getting v1.0 out and #917
