### ISSUE TITLE
bootstrap "scalafmt --diff" fails with FNFE for build.sbt when run from subdir

### ISSUE THREAD

**Issue by kitbellew** [scalameta/scalafmt#927]
This template is a guideline, not a strict requirement.
- **Version**: 0.7.0-RC1
- **Integration**: bootstrap CLI
- **Configuration**:
```
style = default
maxColumn = 100
lineEndings = unix
continuationIndent.callSite = 2
continuationIndent.defnSite = 4
continuationIndent.extendSite = 4
align.tokens = []
align.arrowEnumeratorGenerator = false
align.openParenCallSite = false
includeCurlyBraceInSelectChains = true
optIn.annotationNewlines = true
optIn.configStyleArguments = true
optIn.breakChainOnFirstMethodDot = true
newlines.alwaysBeforeTopLevelStatements = false
newlines.alwaysBeforeCurlyBraceLambdaParams = true
newlines.afterCurlyLambda = never
newlines.sometimesBeforeColonInMethodReturnType = false
newlines.penalizeSingleSelectMultiArgList = true
newlines.afterImplicitKWInVerticalMultiline = true
newlines.beforeImplicitKWInVerticalMultiline = true
binPack.literalArgumentLists = true
binPack.parentConstructors = false
runner.optimizer.forceConfigStyleOnOffset = 50
runner.optimizer.forceConfigStyleMinArgCount = 3
rewrite.rules = [ExpandImportSelectors, PreferCurlyFors]
danglingParentheses = true
runner.fatalWarnings = true
verticalMultilineAtDefinitionSite = false
```

## Steps

I ran scalafmt like this:

```bash
git clone xxxx/yyy.git
cd yyy # in git top-level dir
mkdir utils
pushd utils
# store scalafmt in a subdirectory
coursier bootstrap com.geirsson:scalafmt-cli_2.11:0.7.0-RC1 --main org.scalafmt.cli.Cli -o scalafmt
popd # back to git top-level dir
vim .scalafmt.conf
pushd spark # go to project subdir
ln -s ../.scalafmt.conf . # this is for Intellij
../utils/scalafmt --diff
```

## Problem

Scalafmt exits with the ```FileNotFoundException``` looking for ```yyy/spark/spark/build.sbt``` (note "spark/" is mentioned twice).

## Expectation

I would like the tool not to fail and find build.sbt in ```yyy/spark/build.sbt``` if necessary.

## Workaround

I've found that by running ```scalafmt --diff``` from the git top-level directory (instead of the project subdirectory), this error is avoided.

## Notes

See also..

**Comment by olafurpg** [comment]
Thank you for reporting! Good catch :)

The culprit line is probably this one here https://github.com/scalameta/scalafmt/blob/492ad03eb057a92e48514b27801a8a6035156b00/scalafmt-core/shared/src/main/scala/org/scalafmt/util/GitOps.scala#L74

Instead of using the working directory as base, we should probably use `GitOps.rootDir`. If someone wants to take a swing at this, a good way to test this change would be here https://github.com/scalameta/scalafmt/blob/492ad03eb057a92e48514b27801a8a6035156b00/scalafmt-tests/src/test/scala/org/scalafmt/cli/CliTest.scala#L307

**Comment by pjrt** [comment]
This issue wasn't fixed. It is still happening. :(

**Comment by olafurpg** [comment]
I believe this issue got fixed in #961. Can you verify @kitbellew ?

**Comment by kitbellew** [comment]
@olafurpg sorry for a *very* long delay. this problem seems to have disappeared. (although others have turned up now.)

**Comment by olafurpg** [comment]
@kitbellew can you elaborate on the other problems? Please open a new ticket.

**Comment by kitbellew** [comment]
@olafurpg created a couple of issues, hopefully not too many duplicates:

https://github.com/scalameta/scalafmt/issues/1040
https://github.com/scalameta/scalafmt/issues/1041
https://github.com/scalameta/scalafmt/issues/1042

and some feature requests:

https://github.com/scalameta/scalafmt/issues/1039
https://github.com/scalameta/scalafmt/issues/1043

Thanks for your great tool!
