### ISSUE TITLE
Help text should explain the --files parameter

### ISSUE THREAD

**Issue by non** [scalameta/scalafmt#940]
Currently `scalafmt -help` (and the user-facing docs) don't explain that when using multiple files with `-f` or `--files` you use commas to separate the arguments, rather than providing one -f per file, or putting the files in a string separated by whitespace, or as trailing args.

It would be nice to have either an example of the form `-f foo.scala,bar.scala` or a mention somewhere that the files are comma-delimited.

**Comment by olafurpg** [comment]
Thank you for reporting! Incidentally, we have been working on cleaning up the cli for v1.0 in #875 and #939. This is one of the things that will get fixed. The `--files`/`-f` option will become optional and hidden from the --help message. Instead, files are passed at the end of the argument list space separated `scalafmt Foo.scala Bar.scala`. This change should play nicer with bash globs like `scalafmt *.scala`

**Comment by non** [comment]
That sounds great! Glad this is in the works.

**Comment by olafurpg** [comment]
#939 has now been merged, the new --help page is available here http://scalameta.org/scalafmt/#--help in a nutshell, -i is enabled by default and --files is optional

```
scalafmt Foo.scala
```
