### ISSUE TITLE
Unable to format file due to bug in scalafmt

### ISSUE THREAD

**Issue by krzkaczor** [scalameta/scalafmt#965]
This template is a guideline, not a strict requirement.
- **Version**: scalafmt 1.0.0-RC1
- **Integration**: IntelliJ, CLI
- **Configuration**:
```
style = defaultWithAlign
maxColumn = 120
newlines.sometimesBeforeColonInMethodReturnType = false
align.openParenCallSite = false
rewrite.rules = [RedundantBraces, RedundantParens]
```

## Steps

Method like this:
```
  def test(dataFrame: DataFrame) = {
    val zeroAccumulator = Array.fill(1)((0.0, 0))

    dataFrame.rdd.aggregate(zeroAccumulator)({(acc, row) => acc.zip(row.toSeq).map{ case (x, y) => {
      if(true) (1, 2)
      else (x._1 + 2, x._2 + 1)
    }}},
      {(acc1, acc2) => acc1.zip(acc2).map{ case (x, y) => (x._1 + y._1, x._2 + y._2)}})
      .map{case (sum, count) => sum}
  }
```
Results in:

```
[warn] Error in test.scala: org.scalafmt.Error$Incomplete: Unable to format file due to bug in scalafmt
```

This method ofc doesnt make any sense but syntax is correct and it should be possible to format in anyway. I tried to provide minimal example to reproduce the issue and it's the closest I could get.

**Comment by olafurpg** [comment]
Thank you for reporting! I am able to reproduce. Fixing it will require some focused work, however. As a workaround, you can manually remove the newline after `}}},` and then scalafmt will format that input. I understand manually finding what to edit may take some time, sorry about that!
