### ISSUE TITLE
Scalafmt Cli doesn't work with Appveyor and powerhell script

### ISSUE THREAD

**Issue by muxanick** [scalameta/scalafmt#967]
- **Version**: 0.6.8
- **Integration**: CLI
- **Configuration**: Appveyor and powershell

## Steps

I used coursier to bootstrap jar file.
I ran scalafmt on AppVeyor from powershell script `scalafmt.ps1`:
`&java -jar $SCALAFMT --test`

(`$SCALAFMT` is path to downloaded jar)

It also could be reproduced locally in powershell by command:
`&java -jar $SCALAFMT --test 2>error.log`

(then `error.log` will have an exception)

## Problem

Output looks like that:
`java.exe : [2KLooking for unformatted files... (2.68 %, 18 / 671)`

Appveyor sees raised exception from the script:
```
At C:\bin\scalafmt.ps1:42 char:13
    + CategoryInfo          : NotSpecified: ([2KLooking for...68 %, 18 / 671):String) [], RemoteException
    + FullyQualifiedErrorId : NativeCommandError
```

## Expectation

No exception while outputs strings.
it would be good to have a command line option to not output `[2K` before strings,
that prefix raised native exception and breaks the rest output.

## Workaround

I've found that I can suppress all output to stderr but it also suppresses all output from scalafmt,
that it also interesting question why `scalafmt` outputs everything to stderr? even normal text

**Comment by olafurpg** [comment]
Thank you for reporting! 

What happens if you run `coursier launch com.geirsson:scalafmt-cli_2.12:1.0.0-RC1 --main org.scalafmt.cli.Cli`?

I don't have a Windows computer to reproduce. Help here would be very welcome.

**Comment by muxanick** [comment]
@olafurpg thanks for replying me,
I tested 1.0.0-RC1 same error with `[2KReformatting...`

**Comment by olafurpg** [comment]
Maybe the TermDisplay is emitting something weird, https://github.com/scalameta/scalafmt/blob/fb7db664c51b1ef8077e4c9953a25db82c72002f/scalafmt-cli/src/main/scala/org/scalafmt/cli/Cli.scala#L134

I don't know why it would print out the weird escape characters otherwise.

**Comment by olafurpg** [comment]
Alternatively, we could modify `ScalafixOptions.common.out: OutputStream` here https://github.com/scalameta/scalafmt/blob/fb7db664c51b1ef8077e4c9953a25db82c72002f/scalafmt-cli/src/main/scala/org/scalafmt/cli/Cli.scala#L62 to filter out escape keys if running under windows.

**Comment by muxanick** [comment]
@olafurpg on your first link I see ` new OutputStreamWriter(options.common.err),`.
why `.err`? maybe change it to out?

**Comment by olafurpg** [comment]
System.out is used for printing out formatted code with --stdout, which was enabled by default until the last release. Some editor integrations like vim-autoformat use --stdout. There are cases with --stdout where scalafmt uses stderr to emit diagnostics/warnings.

**Comment by muxanick** [comment]
@olafurpg would it be good to have some additional command-line option to not use stderr for information mesages? For CI for instance would be perfect.

**Comment by olafurpg** [comment]
Sure thing, I'm happy to merge a PR adding such a flag. What do you think would be a good name for that flag? --no-stderr ?

**Comment by muxanick** [comment]
@olafurpg sounds good, thanks
