### ISSUE TITLE
regression: spaces.beforeSeqWildcard is gone but it's false

### ISSUE THREAD

**Issue by eed3si9n** [scalameta/scalafmt#973]
- **Version**: 1.0.0-RC2
- **Integration**: commandline
- **Configuration**:

```
maxColumn = 100
project.git = true
project.excludeFilters = [ /sbt-test/, /input_sources/, /contraband-scala/ ]

# http://docs.scala-lang.org/style/scaladoc.html recommends the JavaDoc style.
# scala/scala is written that way too https://github.com/scala/scala/blob/v2.12.2/src/library/scala/Predef.scala
docstrings = JavaDoc

# This also seems more idiomatic to include whitespace in import x.{ yyy }
spaces.inImportCurlyBraces = true

# Vertical alignment only => for pattern matching
align.tokens.add = [
  { code = "=>",  owner = "Case"  }
]
```

## Steps

I ran scalafmt like this:

```bash
scalafmt
```

## Problem

Scalafmt formats code like this:

```scala
       s.remainingCommands match {
         case List()            => exit(true)
         case List(x, xs @ _ *) => runCmd(x, xs.toList)
       }
```

## Expectation

I would like the formatted output to look like this:
```scala
       s.remainingCommands match {
         case List()           => exit(true)
         case List(x, xs @ _*) => runCmd(x, xs.toList)
       }
```

## Notes

Ref https://github.com/scalameta/scalafmt/pull/921/commits/300e6f86be670058ea870d7d1e20f2a743477252

```diff
-      case FormatToken(Underscore(), Ident("*"), _)
-          if style.spaces.beforeSeqWildcard =>
-        Seq(
-          Split(NoSplit, 0)
-        )
```

**Comment by olafurpg** [comment]
Thank you for reporting! It seems the option name was flipped, `spaces.beforeSeqWildcard = true` meant "no space before seq wildcard". I assumed the reverse. I will try to fix this asap and cut another release (and hopefully find time to finally write up the changelog).

**Comment by eed3si9n** [comment]
I'm still seeing this using 1.0.0-RC3 via sbt plugin.

**Comment by eed3si9n** [comment]
Actually it might be issue on neo-sbt-scalafmt side.
I set `scalafmtVersion in ThisBuild` to `1.0.0-RC3` but I'm seeing `.ivy2/cache/com.geirsson/scalafmt-core_2.11/jars/scalafmt-core_2.11-0.6.8.jar` on the classpath.

**Comment by eed3si9n** [comment]
I just used CLI and I'm saw this diff:

```diff
-      case elem @ Elem(prefix, "dependency", attributes, scope, children @ _*)
+      case elem @ Elem(prefix, "dependency", attributes, scope, children @ _ *)
```

**Comment by olafurpg** [comment]
I am able to reproduce with 1.0.0-RC3 but not on master. `scalafmt --build-info` shows a commit 27cf302fd3 that's not in master's history. I suspect the release got broken. I just changed the publish script to clean before release and cut a RC4 release.

```
$ cat 973.scala
object faa {
  x match { case List(x @ _ *) => }
}
$ coursier launch com.geirsson:scalafmt-cli_2.11:1.0.0-RC4 -r sonatype:releases --main org.scalafmt.cli.Cli -- --stdout 973.scala
object faa {
  x match { case List(x @ _*) => }
}
```
