### ISSUE TITLE
Off-by-one error in maxColumn

### ISSUE THREAD

**Issue by alexnixon** [scalameta/scalafmt#976]
This template is a guideline, not a strict requirement.
- **Version**: 1.0.0-RC3
- **Integration**: IntelliJ
- **Configuration**:
```
align = true
maxColumn = 80
```

Firstly - I've just started using scalafmt and it seems like a fantastic tool. Thanks!

Given `maxColumn = 80` I would expect scalafmt to *allow* a character in the 80th column. However scalafmt reformats
```
object Wat {
  val a = "aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa"
}
```
as
```
object Wat {
  val a =
    "aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa"
}
```
Despite the line not exceeding 80 characters in length. It's particularly noticeable when you have Intellij's margin marker enabled which shows your code as being within bounds:

![image](https://user-images.githubusercontent.com/121612/27227993-bf2d34f6-529d-11e7-897f-df6977fb70fe.png)

**Comment by olafurpg** [comment]
Thank you for reporting! You are correct, I've opened #982 changing it so that scalafmt allows a character on the n-th column.
