### ISSUE TITLE
Intellij Plugin bestEffortInDeeplyNestedCode not recognized

### ISSUE THREAD

**Issue by samudurand** [scalameta/scalafmt#977]
The latest version of the Intellij plugin does not recognize the flag bestEffortInDeeplyNestedCode, it generates an 'invalid field'. And I didn't see any mention of the removal of that property in the changelog of ScalaFmt.
Did I miss something ?

**Comment by olafurpg** [comment]
Thank you for reporting! This option has been removed for v1, see http://scalameta.org/scalafmt/#Deeplynestedcode for possible workarounds. I've added a note in the changelog.
