### ISSUE TITLE
Completely turn off optIn.breakChainOnFirstMethodDot

### ISSUE THREAD

**Issue by LMnet** [scalameta/scalafmt#988]
- **Version**: 1.0.0-RC4
- **Integration**: neo-sbt-scalafmt
- **Configuration**:
```
maxColumn = 120
continuationIndent.defnSite = 2
align = none
align.openParenCallSite = false
danglingParentheses = true
includeCurlyBraceInSelectChains = false
optIn.breakChainOnFirstMethodDot = true
newlines.penalizeSingleSelectMultiArgList = false
rewrite.rules = [AvoidInfix]

```

## Steps

I ran scalafmt like this:

```bash
sbt scalafmt
```

## Problem

Original code:

```scala
sql"""
  |some sql code here
""".stripMargin
  .map(_.long(1)).single().future()

val termination = httpApi.bindingFuture
  .flatMap(_.unbind())
  .flatMap(_ => actorSystem.terminate())
```

With `optIn.breakChainOnFirstMethodDot = false` scalafmt formats code like this:
```scala
sql"""
  |some sql code here
""".stripMargin.map(_.long(1)).single().future()

val termination = httpApi.bindingFuture.flatMap(_.unbind()).flatMap(_ => actorSystem.terminate())
```

With `optIn.breakChainOnFirstMethodDot = true` scalafmt formats code like this:
```scala
sql"""
  |some sql code here
""".stripMargin
  .map(_.long(1))
  .single()
  .future()

val termination = httpApi.bindingFuture
  .flatMap(_.unbind())
  .flatMap(_ => actorSystem.terminate())
```

## Expectation

I would like to preserve original code for both code fragments. I don't want to generalize rules for dot calls in my codebase.

## Workaround

No workaround at the moment as far as I know.

**Comment by olafurpg** [comment]
There is no workaround for this at the moment. Contributions are welcome if someone is interested in taking a stab at this.
