### ISSUE TITLE
How do you disable val/var vertical alignment?

### ISSUE THREAD

**Issue by alexflav23** [scalameta/scalafmt#993]
This template is a guideline, not a strict requirement.
- **Version**: Latest
- **Integration**: CLI
- **Configuration**:
```
style = defaultWithAlign
maxColumn = 120
```

## Steps

I ran scalafmt like this:

```bash
scalafmt
```

## Problem

Scalafmt formats code like this. Github is interfering with the rendering here, at least on my browser. Definitions are vertically aligned, however I want to disable this behaviour.

```scala
val x            = 5
val testinga = 10
```

## Expectation

I would like the formatted output to look like this:
```scala
val x = 5
val testinga = 10
```

## Notes

Have not been able to find a suitable documentation, several options on the official page such as `treeCategory` in `align` are deemed invalid by the CLI.

How does one disable this dreadful behaviour?

**Comment by ShaneDelmore** [comment]
The style selected is defaultWithAlign, which is requesting alignment.  If you want to disable it you can set it to none.  http://scalameta.org/scalafmt/#align=none

**Comment by ShaneDelmore** [comment]
Align = some might be what you want http://scalameta.org/scalafmt/#align=some

**Comment by olafurpg** [comment]
The default style has `align=some`. That may be more to @alexflav23's taste

**Comment by alexflav23** [comment]
Hi @olafurpg,

As a further comment to this, the docs on the website may not 100% up to date, and they do not even show how to pick different align styles or which property should be configured, unless I misunderstand how it is structured.

Currently align is an object with multiple properties, some of which while available in the official documentation, still fail to compile. Can vertical alignment be controlled individually with every align style or how does this work?

Regards.

**Comment by olafurpg** [comment]
There may be some missing context from the docs  here https://github.com/scalameta/scalafmt/blob/ba64e7a4f3767b8fc489cd70d9d3229b23f1a22f/scalafmt-core/shared/src/main/scala/org/scalafmt/config/Align.scala I personally recommend sticking to one of the provided defaults `none/some/more/most` documented in the docs

**Comment by alexflav23** [comment]
@olafurpg What's the config input? `align=Align.some`?

**Comment by olafurpg** [comment]
http://scalameta.org/scalafmt/#align

**Comment by alexflav23** [comment]
````
Exception in thread "main" metaconfig.FailedToReadClass: Failed to read 'ScalafmtConfig'. Align cannot be 'some' (of class String).
```

**Comment by olafurpg** [comment]
You may be using an old version of scalafmt

**Comment by alexflav23** [comment]
@olafurpg I guess that's possible, this is what came from Homebrew. Might be worthwhile to associate docs to a version then.

```bash
flavian$ scalafmt -version
scalafmt 0.6.8
```

Doing this inside ScalaFMT conf definitely does not work: `align=some`.

**Comment by alexflav23** [comment]
@olafurpg All good now, brew upgraded me to 1.0.4
