### ISSUE TITLE
Support vertical alignment of if and else statements

### ISSUE THREAD

**Issue by nrinaudo** [scalameta/scalafmt#995]
## Input code

```scala
if(someCondition) foo
else bar
```

## Desired behaviour
This should obviously not be the _default_ behaviour, but I'd love an option to toggle it on:

```scala
if(someCondition) foo
else              bar
````

**Comment by olafurpg** [comment]
This kind of alignment doesn't fit directly with the current "align similar tokens" model. It should be possible to achieve this however by making the first tokens in the if/else bodies "similar". Whether two tokens align is currently handled by two phases

1) `isCandiate`: https://github.com/scalameta/scalafmt/blob/master/scalafmt-core/shared/src/main/scala/org/scalafmt/internal/FormatWriter.scala#L226 Individual tokens are selected for potential vertical alignment
2) `columnsMatch`: https://github.com/scalameta/scalafmt/blob/ba64e7a4f3767b8fc489cd70d9d3229b23f1a22f/scalafmt-core/shared/src/main/scala/org/scalafmt/internal/FormatWriter.scala#L266 alignment candidates from two lines are matched against each other. This is where for example scalafmt will disregard aligning a `=>` tokens with a `%` token.

I think it should be possible to 1) customize `isCandidate` to return true for first tokens of if/else bodies and 2) make if/else token candidates match in `columnsMatch`. 

It's possible to test vertical alignment like here https://github.com/scalameta/scalafmt/blob/ba64e7a4f3767b8fc489cd70d9d3229b23f1a22f/scalafmt-tests/src/test/resources/align/MixedTokens.stat I would recommend creating a new "test suite" `IfElseTokens.stat` and add a new `ifElseTokens: Boolean` field (name up for debate) to [`Align.scala` ](https://github.com/scalameta/scalafmt/blob/ba64e7a4f3767b8fc489cd70d9d3229b23f1a22f/scalafmt-core/shared/src/main/scala/org/scalafmt/config/Align.scala#L59) to create an option to use this feature.

**Comment by olafurpg** [comment]
Feel free to reopen if you would like to take a stab at this
