### ISSUE TITLE
scala.meta inline macros not supported

### ISSUE THREAD

**Issue by fommil** [scalameta/scalafmt#999]
in this exact version of our project https://github.com/fommil/stalagmite/tree/552944186524c72ef74a997a4e21c8ff6a6509d4

`sbt fmt` outputs

```
[warn] /home/fommil/Projects/stalagmite/src/main/scala/fommil/stalagmite/DataImpl.scala:158: error: ; expected but def found
[warn] inline def apply(defn: Any): Any = meta {
[warn]          ^
```

on valid code https://github.com/fommil/stalagmite/blob/552944186524c72ef74a997a4e21c8ff6a6509d4/src/main/scala/fommil/stalagmite/DataImpl.scala#L158

// @vovapolu

**Comment by olafurpg** [comment]
What scalafmt version are you on? This is supposed to be fixed in 1.0, but maybe I forgot to allow inline in the default dialect

**Comment by fommil** [comment]
https://github.com/fommil/stalagmite/blob/master/build.sbt#L39

**Comment by olafurpg** [comment]
```
$ coursier launch com.geirsson:scalafmt-cli_2.12:1.1.0 -- --stdout foo.scala
object foo {
  trait foo(a: Int)
  inline def apply = 2
}
```

I'm able to reproduce if I remove the leading trait

```
$ cat foo.scala
object foo {
  inline def apply = 2
}
$ coursier launch com.geirsson:scalafmt-cli_2.12:1.1.0 -- --stdout foo.scala
[warn] Error in /Users/ollie/dev/scalafmt/target/foo.scala: <input>:2: error: ; expected but def found
inline def apply = 2
         ^
```
which means this is a bug in the scalameta parser. Please report an issue in scalameta/scalameta.

In the future please try to minimise the repro and include necessary information in the description.

**Comment by olafurpg** [comment]
A workaround is to put a dummy statement in front of `inline def`.

**Comment by fommil** [comment]
1. why is this closed, did you fix it somewhere?
2. what do you mean by a dummy statement?

**Comment by fommil** [comment]
what do you mean by "put a dummy statement in front of `inline def`"?

**Comment by olafurpg** [comment]
Any statement above `inline def`

```scala
$ coursier launch com.geirsson:scalafmt-cli_2.12:1.1.0 -- --stdout foo.scala
object foo {
  val dummy = 2
  inline def apply = 2
}
```
